import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {test} from "node:test";
import {NEON_BP_APPLICANT_RELAY_OPERATIONS,NEON_BP_PROFILE_MATCH_RELAY_OPERATIONS} from "../../packages/platform/gateway/bff-relay/src/index";

const fixture=JSON.parse(readFileSync(new URL("../../packages/contracts/platform/fixtures/business-partner-r3-invited-supplier.v1.json",import.meta.url),"utf8"));
test("R3 freezes invitation and MESH as proposal-only supplier paths",()=>{assert.equal(fixture.$schema,"athyper.business-partner-r3-fixture/1");assert.deepEqual(fixture.scenarios.map((item:{id:string})=>item.id),["BP-SUP-004","BP-SUP-006"]);assert.deepEqual(fixture.invariants,{proposalOnly:true,directMasterWrite:false,crossInvitationRead:false,applicantInternalCaseRead:false,ownerBoundCorrection:true,protectedEvidence:true,explicitMeshFieldAcceptance:true,independentApproval:true});});
test("R3 exposes only bounded applicant and MESH proposal relays",()=>{assert.deepEqual(NEON_BP_APPLICANT_RELAY_OPERATIONS.map(item=>item.id),["neon.business-partner-applicant.accept","neon.business-partner-applicant.status","neon.business-partner-applicant.correction","neon.business-partner-applicant.evidence","neon.business-partner-applicant.evidence-stage","neon.business-partner-applicant.evidence-complete","neon.business-partner-applicant.submit"]);assert.equal(NEON_BP_PROFILE_MATCH_RELAY_OPERATIONS.length,5);assert.ok(NEON_BP_APPLICANT_RELAY_OPERATIONS.every(item=>item.path.startsWith("/api/neon/external/business-partner-invitations/")));assert.ok(!NEON_BP_APPLICANT_RELAY_OPERATIONS.some(item=>/business-partners\/:|materialize|decision/.test(item.path)));});
test("R3 external acceptance response and status are projected, not persistence records",()=>{const source=readFileSync(new URL("../../server/packages/services/master-data/src/business-partner-invitation-service.ts",import.meta.url),"utf8");assert.match(source,/externalProjection\(command\.journeyKind,result\.request\)/);assert.match(source,/Object\.entries\(request\.proposedPayload\)\.filter/);for(const forbidden of ["tokenHash","inviteeEmailHash","workflowRequestId","approvedBy"])assert.doesNotMatch(source,new RegExp(`editablePayload[^;]+${forbidden}`));});
