import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { MESH_BP_BANK_DISCLOSURE_RELAY_OPERATIONS, MESH_BP_NETWORK_EXCHANGE_RELAY_OPERATIONS, NEON_BP_MESH_ACCOUNT_LINK_RELAY_OPERATIONS, NEON_BP_PROFILE_PROJECTION_RELAY_OPERATIONS, NEON_BP_PROFILE_MATCH_RELAY_OPERATIONS } from "../../packages/platform/gateway/bff-relay/src/index";

const root=new URL("../../",import.meta.url),fixture=JSON.parse(readFileSync(new URL("packages/contracts/platform/fixtures/business-partner-r6-mesh-complete.v1.json",root),"utf8"));
const meshSurface=readFileSync(new URL("packages/planes/mesh/business-partner/src/index.tsx",root),"utf8"),neonSurface=readFileSync(new URL("packages/planes/neon/business-partner/src/mesh-proposal-experience.tsx",root),"utf8"),service=readFileSync(new URL("server/packages/planes/mesh/src/business-partner-network-exchange.ts",root),"utf8"),policyAdapter=readFileSync(new URL("server/packages/planes/mesh/src/business-partner-self-registration-policy.ts",root),"utf8");

test("R6 freezes BP-SUP-005 and BP-SUP-007 without granting exchange authority to Neon",()=>{assert.equal(fixture.$schema,"athyper.business-partner-r6-fixture/1");assert.deepEqual(fixture.scenarios.map((item:{id:string})=>item.id),["BP-SUP-005","BP-SUP-007"]);assert.equal(fixture.invariants.registrationAcceptCreatesNeonMasterData,false);assert.equal(fixture.invariants.targetEnvironmentEvidenceRetained,false);assert.equal(fixture.invariants.externalSelfRegistrationPolicyAdapterAvailable,true);assert.match(policyAdapter,/internal_sponsor_required/);assert.match(policyAdapter,/https:/);assert.doesNotMatch(service,/INSERT INTO master\.|UPDATE master\./);});
test("R6 relays the complete account relationship disclosure quarantine link and ack path",()=>{const paths=[...MESH_BP_NETWORK_EXCHANGE_RELAY_OPERATIONS,...MESH_BP_BANK_DISCLOSURE_RELAY_OPERATIONS,...NEON_BP_PROFILE_PROJECTION_RELAY_OPERATIONS,...NEON_BP_MESH_ACCOUNT_LINK_RELAY_OPERATIONS].map(item=>`${item.method} ${item.path}`);for(const expected of ["GET /api/mesh/business-partner-network-workspace","POST /api/mesh/business-partner-network-relationships","POST /api/mesh/business-partner-registration-exchanges","POST /api/mesh/business-partner-bank-disclosures","GET /api/neon/business-partner-profile-events/quarantine","GET /api/neon/business-partner-profile-events/receipts","POST /api/neon/business-partner-profile-events/:eventId/replays","POST /api/neon/mesh-business-partner-account-links","POST /api/neon/mesh-business-partner-account-links/:linkId/decisions"])assert.ok(paths.includes(expected),`missing ${expected}`);});
test("R6 makes every lifecycle branch UI-drivable and displays retained proof",()=>{assert.ok(meshSurface.includes("requestRelationship"));for(const action of fixture.branches.relationship.slice(1))assert.ok(meshSurface.includes(`\"${action}\"`),`missing relationship ${action}`);for(const action of ["accept","reject","cancel","expire"])assert.ok(meshSurface.includes(`\"${action}\"`),`missing exchange ${action}`);for(const token of ["evidenceId","contractHash","invitationTokenHash","secureRetrievalReference"])assert.ok(meshSurface.includes(token),`missing ${token}`);for(const token of ["quarantine","replays","profileProjectionId","Approve link as checker","projectionId"])assert.ok(neonSurface.includes(token),`missing ${token}`);assert.match(neonSurface,/immutable|retained/i);});

test("R6 exposes a governed read-only change comparison and returned source acknowledgements",()=>{
  assert.ok(NEON_BP_PROFILE_MATCH_RELAY_OPERATIONS.some(item=>item.method==="POST"&&item.path==="/api/neon/business-partner-profile-change-previews"));
  assert.ok(neonSurface.includes("Compare profile changes"));
  assert.ok(meshSurface.includes("Recipient acknowledgements"));
});
