import type { AtlasContentBlock, AtlasFinishReason, AtlasModelMessage, AtlasModelProvider, AtlasProviderError, AtlasProviderEvent, AtlasProviderInvocation, AtlasProviderUsage } from "@athyper/server-contract-ai";

export const ANTHROPIC_MESSAGES_ADAPTER_ID = "anthropic-messages";
export const ANTHROPIC_MESSAGES_ADAPTER_VERSION = "1";
const DEFAULT_URL = "https://api.anthropic.com/v1/messages";

export interface AnthropicAdapterOptions { readonly fetch?: typeof fetch; readonly endpoint?: string; readonly timeoutMs?: number; readonly anthropicVersion?: string }
export class AnthropicModelProvider implements AtlasModelProvider {
  readonly providerId = "anthropic" as const; readonly adapterId = ANTHROPIC_MESSAGES_ADAPTER_ID; readonly adapterVersion = ANTHROPIC_MESSAGES_ADAPTER_VERSION;
  private readonly fetcher: typeof fetch; private readonly endpoint: string; private readonly timeoutMs: number; private readonly version: string;
  constructor(options: AnthropicAdapterOptions = {}) { this.fetcher = options.fetch ?? fetch; this.endpoint = options.endpoint ?? DEFAULT_URL; this.timeoutMs = options.timeoutMs ?? 120_000; this.version = options.anthropicVersion ?? "2023-06-01"; }
  async *invoke(invocation: AtlasProviderInvocation): AsyncIterable<AtlasProviderEvent> {
    const mismatch = validate(invocation, this); if (mismatch) { yield { kind: "failed", error: mismatch }; return; }
    const scope = requestScope(invocation.signal, this.timeoutMs);
    try {
      const response = await this.fetcher(this.endpoint, { method: "POST", headers: { "content-type": "application/json", accept: "text/event-stream", "x-api-key": invocation.credential.secret, "anthropic-version": this.version }, body: JSON.stringify(buildBody(invocation)), signal: scope.signal });
      if (!response.ok) { yield { kind: "failed", error: httpError(response.status) }; return; }
      if (!response.body || !(response.headers.get("content-type") ?? "").toLowerCase().startsWith("text/event-stream")) { yield { kind: "failed", error: protocol("invalid_stream") }; return; }
      const calls = new Map<number, { id: string; name: string; json: string }>(); let finish: AtlasFinishReason = "stop"; let terminal = false;
      for await (const frame of readSse(response.body)) {
        if (!frame.data || frame.data === "[DONE]") continue; let event: any; try { event = JSON.parse(frame.data); } catch { yield { kind: "failed", error: protocol("invalid_json") }; return; }
        if (event.type === "message_start") { const model = string(event.message?.model); if (!model) { yield { kind: "failed", error: protocol("missing_model") }; return; } yield { kind: "response_started", providerRequestId: string(event.message?.id), actualModelId: model }; const usage = anthropicUsage(event.message?.usage); if (usage) yield { kind: "usage", mode: "snapshot", final: false, usage }; }
        else if (event.type === "content_block_start" && event.content_block?.type === "tool_use") { const call = { id: requiredString(event.content_block.id, "tool_call_id"), name: requiredString(event.content_block.name, "tool_name"), json: "" }; calls.set(number(event.index), call); yield { kind: "tool_call_start", callId: call.id, toolName: call.name }; }
        else if (event.type === "content_block_delta" && event.delta?.type === "text_delta") { if (typeof event.delta.text === "string") yield { kind: "text_delta", text: event.delta.text }; }
        else if (event.type === "content_block_delta" && event.delta?.type === "input_json_delta") { const call = calls.get(number(event.index)); if (!call || typeof event.delta.partial_json !== "string") { yield { kind: "failed", error: protocol("orphan_tool_delta") }; return; } call.json += event.delta.partial_json; yield { kind: "tool_call_input_delta", callId: call.id, jsonFragment: event.delta.partial_json }; }
        else if (event.type === "content_block_stop") { const call = calls.get(number(event.index)); if (call) { let args: Record<string, unknown>; try { args = JSON.parse(call.json || "{}"); } catch { yield { kind: "failed", error: protocol("invalid_tool_arguments") }; return; } yield { kind: "tool_call_complete", callId: call.id, toolName: call.name, input: args }; calls.delete(number(event.index)); } }
        else if (event.type === "message_delta") { finish = finishReason(event.delta?.stop_reason); const usage = anthropicUsage(event.usage); if (usage) yield { kind: "usage", mode: "snapshot", final: true, usage }; }
        else if (event.type === "message_stop") { terminal = true; yield { kind: "completed", reason: finish }; return; }
        else if (event.type === "error") { terminal = true; yield { kind: "failed", error: anthropicError(event.error?.type) }; return; }
      }
      if (!terminal) yield { kind: "failed", error: protocol("stream_incomplete") };
    } catch (error) { if (scope.timedOut()) yield { kind: "failed", error: fail("timeout", "provider_timeout", true) }; else if (invocation.signal?.aborted || isAbort(error)) yield { kind: "cancelled" }; else yield { kind: "failed", error: fail("upstream_error", "provider_unavailable", true) }; }
    finally { scope.cleanup(); }
  }
}
export function buildAnthropicMessagesRequest(invocation: AtlasProviderInvocation) { return buildBody(invocation); }
function buildBody(invocation: AtlasProviderInvocation) { const system = invocation.prompt.messages.filter((m) => m.role === "system").flatMap((m) => textBlocks(m.content)).join("\n"); const messages = invocation.prompt.messages.filter((m) => m.role !== "system").map(toAnthropicMessage); return { model: invocation.binding.upstreamModelId, max_tokens: invocation.prompt.maxOutputTokens, stream: true, ...(system ? { system } : {}), messages, ...(invocation.prompt.tools?.length ? { tools: invocation.prompt.tools.map((tool) => ({ name: tool.name, description: tool.description, input_schema: tool.inputSchema })) } : {}) }; }
function toAnthropicMessage(message: AtlasModelMessage) { return { role: message.role === "assistant" ? "assistant" : "user", content: message.content.map((block) => block.type === "text" ? { type: "text", text: block.text } : block.type === "tool_use" ? { type: "tool_use", id: block.callId, name: block.toolName, input: block.input } : { type: "tool_result", tool_use_id: block.callId, content: JSON.stringify(block.result), is_error: block.isError === true }) }; }
function textBlocks(content: readonly AtlasContentBlock[]): string[] { return content.flatMap((block) => block.type === "text" ? [block.text] : []); }
function anthropicUsage(value: any): AtlasProviderUsage | null { if (!value || typeof value !== "object") return null; return { inputTokens: finite(value.input_tokens), outputTokens: finite(value.output_tokens), cacheReadTokens: finite(value.cache_read_input_tokens), cacheWriteTokens: finite(value.cache_creation_input_tokens) }; }
function finishReason(value: unknown): AtlasFinishReason { return value === "max_tokens" ? "length" : value === "tool_use" ? "tool_call" : value === "refusal" ? "refusal" : "stop"; }
function anthropicError(value: unknown): AtlasProviderError { if (value === "authentication_error") return fail("authentication", "authentication_failed", false); if (value === "permission_error") return fail("permission", "permission_denied", false); if (value === "rate_limit_error") return fail("rate_limited", "rate_limited", true); if (value === "overloaded_error") return fail("overloaded", "provider_overloaded", true); return fail("upstream_error", "provider_error", true); }
function validate(invocation: AtlasProviderInvocation, adapter: AnthropicModelProvider): AtlasProviderError | null { const b = invocation.binding; if (b.providerId !== adapter.providerId || b.adapterId !== adapter.adapterId || b.adapterVersion !== adapter.adapterVersion || b.status !== "available" || !b.capabilities.streaming) return fail("invalid_request", "binding_adapter_mismatch", false); if (invocation.credential.ownerId !== b.credentialOwnerId || !invocation.credential.secret.trim()) return fail("authentication", "credential_binding_mismatch", false); return null; }
function httpError(status: number): AtlasProviderError { if (status === 401) return fail("authentication", "authentication_failed", false); if (status === 403) return fail("permission", "permission_denied", false); if (status === 429) return fail("rate_limited", "rate_limited", true); if (status === 529 || status >= 500) return fail("overloaded", "provider_overloaded", true); return fail("invalid_request", `provider_http_${status}`, false); }
function protocol(code: string): AtlasProviderError { return fail(code === "stream_incomplete" ? "stream_incomplete" : "protocol_error", code, false); }
function fail(errorClass: AtlasProviderError["errorClass"], code: string, retryable: boolean): AtlasProviderError { return { errorClass, code, safeMessage: "The Atlas provider request could not be completed.", retryable }; }
function requiredString(value: unknown, code: string): string { const result = string(value); if (!result) throw new Error(code); return result; } function string(value: unknown): string | null { return typeof value === "string" && value.trim() ? value : null; } function number(value: unknown): number { return typeof value === "number" && Number.isInteger(value) ? value : -1; } function finite(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : undefined; }
async function* readSse(body: ReadableStream<Uint8Array>): AsyncGenerator<{ event: string; data: string }> { const reader = body.getReader(); const decoder = new TextDecoder(); let buffer = ""; try { while (true) { const read = await reader.read(); buffer += decoder.decode(read.value, { stream: !read.done }); const parts = buffer.split(/\r?\n\r?\n/); buffer = parts.pop() ?? ""; for (const part of parts) { const event = part.split(/\r?\n/).find((line) => line.startsWith("event:"))?.slice(6).trim() ?? ""; const data = part.split(/\r?\n/).filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trimStart()).join("\n"); yield { event, data }; } if (read.done) break; } } finally { reader.releaseLock(); } }
function requestScope(parent: AbortSignal | undefined, timeoutMs: number) { const controller = new AbortController(); let timeout = false; const abort = () => controller.abort(parent?.reason); parent?.addEventListener("abort", abort, { once: true }); const timer = setTimeout(() => { timeout = true; controller.abort(); }, timeoutMs); return { signal: controller.signal, timedOut: () => timeout, cleanup: () => { clearTimeout(timer); parent?.removeEventListener("abort", abort); } }; }
function isAbort(error: unknown): boolean { return error instanceof DOMException && error.name === "AbortError"; }
