x-notification-smtp-environment: &notification-smtp-environment
  EMAIL_PROVIDER: smtp
  SMTP_HOST_FILE: /run/secrets/smtp-host
  SMTP_PORT_FILE: /run/secrets/smtp-port
  SMTP_SECURE_FILE: /run/secrets/smtp-secure
  SMTP_FROM_FILE: /run/secrets/smtp-from
  SMTP_USER_FILE: /run/secrets/smtp-user
  SMTP_PASS_FILE: /run/secrets/smtp-password

x-notification-smtp-secrets: &notification-smtp-secrets
  - smtp-host
  - smtp-port
  - smtp-secure
  - smtp-from
  - smtp-user
  - smtp-password

services:
  api:
    environment: *notification-smtp-environment
    secrets: *notification-smtp-secrets

  worker:
    environment: *notification-smtp-environment
    secrets: *notification-smtp-secrets

secrets:
  smtp-host:
    file: ${ATHYPER_RUNTIME_ROOT:?set ATHYPER_RUNTIME_ROOT}/instances/${ATHYPER_INSTANCE:?set ATHYPER_INSTANCE}/secrets/smtp-host
  smtp-port:
    file: ${ATHYPER_RUNTIME_ROOT:?set ATHYPER_RUNTIME_ROOT}/instances/${ATHYPER_INSTANCE:?set ATHYPER_INSTANCE}/secrets/smtp-port
  smtp-secure:
    file: ${ATHYPER_RUNTIME_ROOT:?set ATHYPER_RUNTIME_ROOT}/instances/${ATHYPER_INSTANCE:?set ATHYPER_INSTANCE}/secrets/smtp-secure
  smtp-from:
    file: ${ATHYPER_RUNTIME_ROOT:?set ATHYPER_RUNTIME_ROOT}/instances/${ATHYPER_INSTANCE:?set ATHYPER_INSTANCE}/secrets/smtp-from
  smtp-user:
    file: ${ATHYPER_RUNTIME_ROOT:?set ATHYPER_RUNTIME_ROOT}/instances/${ATHYPER_INSTANCE:?set ATHYPER_INSTANCE}/secrets/smtp-user
  smtp-password:
    file: ${ATHYPER_RUNTIME_ROOT:?set ATHYPER_RUNTIME_ROOT}/instances/${ATHYPER_INSTANCE:?set ATHYPER_INSTANCE}/secrets/smtp-password
