-- Generated by scripts/checks/security/generate-security-definer-contract.ts.
-- Source: contracts/security/security-definer-ownership.v1.json.
-- No table ownership, administrative privileges, runtime membership, or blanket grants.
DO $definer_privileges$
DECLARE
    role_contract jsonb;
    object_contract jsonb;
    schema_name text;
    routine_signature text;
    role_name text;
    policy_contract jsonb;
    old_policy record;
    policy_index integer;
BEGIN
    FOR role_contract IN SELECT value FROM jsonb_array_elements('[
  {
    "name": "athyper_definer_product_publication",
    "bypassRls": false,
    "schemas": [
      "master",
      "control",
      "metadata",
      "snapshot",
      "publication",
      "shared",
      "ops",
      "public"
    ],
    "tables": [
      {
        "relation": "master.principal",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "master.principal_identity_binding",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "control.policy_definition",
        "privileges": [
          "SELECT",
          "UPDATE"
        ]
      },
      {
        "relation": "control.policy_rule",
        "privileges": [
          "SELECT",
          "UPDATE"
        ]
      },
      {
        "relation": "metadata.entity",
        "privileges": [
          "SELECT",
          "UPDATE"
        ]
      },
      {
        "relation": "metadata.entity_change_set",
        "privileges": [
          "SELECT",
          "UPDATE"
        ]
      },
      {
        "relation": "metadata.entity_release",
        "privileges": [
          "SELECT",
          "INSERT",
          "UPDATE"
        ]
      },
      {
        "relation": "metadata.entity_product_review_receipt",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "snapshot.entity_draft_save",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "snapshot.entity_contract_revision",
        "privileges": [
          "SELECT",
          "INSERT"
        ]
      },
      {
        "relation": "snapshot.entity_release_artifact",
        "privileges": [
          "SELECT",
          "INSERT"
        ]
      },
      {
        "relation": "publication.release",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "publication.entity_release_link",
        "privileges": [
          "SELECT",
          "INSERT"
        ]
      },
      {
        "relation": "publication.artifact",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "publication.artifact_compilation",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "ops.job_execution",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "publication.deployment",
        "privileges": [
          "SELECT"
        ]
      },
      {
        "relation": "publication.deployment_acknowledgement",
        "privileges": [
          "SELECT"
        ]
      }
    ],
    "functions": [
      "snapshot.fn_compute_entity_contract_revision_hash(uuid, uuid, uuid, integer, text, uuid, text, text, text, text[], metadata.compatibility_level_d, metadata.contract_validation_status_d, jsonb, timestamp with time zone, uuid)",
      "metadata.current_actor_id(uuid)",
      "metadata.fn_compute_entity_release_hash(uuid, uuid, uuid, uuid, bigint, text, metadata.entity_release_kind_d, uuid, uuid, text, text, text, text, metadata.compatibility_level_d, text[], text, text, text, uuid, timestamp with time zone, uuid)",
      "shared.uuidv7()",
      "master.current_principal_id_soft()",
      "shared.current_tenant_id_soft()",
      "shared.current_tenant_id()",
      "control.publication_policy_enrollment_is_active(uuid, text, uuid, uuid)",
      "publication.fn_successor_canonical_json(jsonb)",
      "publication.fn_compiled_entity_compilation_source(uuid)",
      "snapshot.fn_compute_entity_contract_hash(jsonb)",
      "snapshot.fn_compute_entity_release_artifact_hash(uuid, uuid, uuid, text, text, text, jsonb)",
      "public.digest(bytea, text)",
      "public.digest(text, text)"
    ],
    "policies": [
      {
        "relation": "master.principal",
        "command": "SELECT",
        "using": "(tenant_id = shared.current_tenant_id_soft())",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "master.principal_identity_binding",
        "command": "SELECT",
        "using": "(tenant_id = shared.current_tenant_id_soft())",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "control.policy_definition",
        "command": "SELECT",
        "using": "(tenant_id = shared.current_tenant_id_soft())",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "control.policy_definition",
        "command": "UPDATE",
        "using": "(tenant_id = shared.current_tenant_id_soft())",
        "check": "false",
        "reason": "Permit policy row locks; reject every policy write by the publication owner."
      },
      {
        "relation": "control.policy_rule",
        "command": "SELECT",
        "using": "(EXISTS ( SELECT 1\n   FROM control.policy_definition d\n  WHERE ((d.id = policy_rule.policy_definition_id) AND (d.tenant_id = shared.current_tenant_id_soft()))))",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "control.policy_rule",
        "command": "UPDATE",
        "using": "(EXISTS ( SELECT 1\n   FROM control.policy_definition d\n  WHERE ((d.id = policy_rule.policy_definition_id) AND (d.tenant_id = shared.current_tenant_id_soft()))))",
        "check": "false",
        "reason": "Permit policy row locks; reject every policy write by the publication owner."
      },
      {
        "relation": "metadata.entity",
        "command": "SELECT",
        "using": "((tenant_id IS NULL) OR (tenant_id = shared.current_tenant_id_soft()))",
        "reason": "Preserve existing tenant compilation reads as well as global product sources, without allowing cross-tenant reads. Mutation policies remain global-only."
      },
      {
        "relation": "metadata.entity",
        "command": "UPDATE",
        "check": "(tenant_id IS NULL)",
        "reason": "Exact enrolled source and human review are checked in private publication commands before global source mutation.",
        "using": "(tenant_id IS NULL)"
      },
      {
        "relation": "metadata.entity_change_set",
        "command": "SELECT",
        "using": "((tenant_id IS NULL) OR (tenant_id = shared.current_tenant_id_soft()))",
        "reason": "Preserve existing tenant compilation reads as well as global product sources, without allowing cross-tenant reads. Mutation policies remain global-only."
      },
      {
        "relation": "metadata.entity_change_set",
        "command": "UPDATE",
        "check": "(tenant_id IS NULL)",
        "reason": "Exact enrolled source and human review are checked in private publication commands before global source mutation.",
        "using": "(tenant_id IS NULL)"
      },
      {
        "relation": "metadata.entity_release",
        "command": "SELECT",
        "using": "((tenant_id IS NULL) OR (tenant_id = shared.current_tenant_id_soft()))",
        "reason": "Preserve existing tenant compilation reads as well as global product sources, without allowing cross-tenant reads. Mutation policies remain global-only."
      },
      {
        "relation": "metadata.entity_release",
        "command": "INSERT",
        "check": "(tenant_id IS NULL)",
        "reason": "Exact enrolled source and human review are checked in private publication commands before global source mutation."
      },
      {
        "relation": "metadata.entity_release",
        "command": "UPDATE",
        "using": "(tenant_id IS NULL)",
        "check": "false",
        "reason": "Permit policy row locks; reject every policy write by the publication owner."
      },
      {
        "relation": "metadata.entity_product_review_receipt",
        "command": "SELECT",
        "using": "(authority_tenant_id = shared.current_tenant_id_soft())",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "snapshot.entity_draft_save",
        "command": "SELECT",
        "using": "((tenant_id IS NULL) OR (tenant_id = shared.current_tenant_id_soft()))",
        "reason": "Preserve existing tenant compilation reads as well as global product sources, without allowing cross-tenant reads. Mutation policies remain global-only."
      },
      {
        "relation": "snapshot.entity_contract_revision",
        "command": "SELECT",
        "using": "((tenant_id IS NULL) OR (tenant_id = shared.current_tenant_id_soft()))",
        "reason": "Preserve existing tenant compilation reads as well as global product sources, without allowing cross-tenant reads. Mutation policies remain global-only."
      },
      {
        "relation": "snapshot.entity_contract_revision",
        "command": "INSERT",
        "check": "(tenant_id IS NULL)",
        "reason": "Exact enrolled source and human review are checked in private publication commands before global source mutation."
      },
      {
        "relation": "snapshot.entity_release_artifact",
        "command": "SELECT",
        "using": "((tenant_id IS NULL) OR (tenant_id = shared.current_tenant_id_soft()))",
        "reason": "Preserve existing tenant compilation reads as well as global product sources, without allowing cross-tenant reads. Mutation policies remain global-only."
      },
      {
        "relation": "snapshot.entity_release_artifact",
        "command": "INSERT",
        "check": "(tenant_id IS NULL)",
        "reason": "Exact enrolled source and human review are checked in private publication commands before global source mutation."
      },
      {
        "relation": "publication.release",
        "command": "SELECT",
        "using": "(tenant_id = shared.current_tenant_id_soft())",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "publication.entity_release_link",
        "command": "SELECT",
        "using": "(EXISTS ( SELECT 1\n   FROM publication.release r\n  WHERE ((r.id = entity_release_link.publication_release_id) AND (r.tenant_id = shared.current_tenant_id_soft()))))",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "publication.entity_release_link",
        "command": "INSERT",
        "check": "(EXISTS ( SELECT 1\n   FROM publication.release r\n  WHERE ((r.id = entity_release_link.publication_release_id) AND (r.tenant_id = shared.current_tenant_id_soft()))))",
        "reason": "Exact enrolled source and human review are checked in private publication commands before global source mutation."
      },
      {
        "relation": "publication.artifact",
        "command": "SELECT",
        "using": "(EXISTS ( SELECT 1\n   FROM publication.release r\n  WHERE ((r.id = artifact.publication_release_id) AND (r.tenant_id = shared.current_tenant_id_soft()))))",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "publication.artifact_compilation",
        "command": "SELECT",
        "using": "(EXISTS ( SELECT 1\n   FROM publication.release r\n  WHERE ((r.id = artifact_compilation.publication_release_id) AND (r.tenant_id = shared.current_tenant_id_soft()))))",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "ops.job_execution",
        "command": "SELECT",
        "using": "(tenant_id = shared.current_tenant_id_soft())",
        "reason": "Bounded product publication functions read current authority or global source evidence; no caller role membership."
      },
      {
        "relation": "publication.deployment",
        "command": "SELECT",
        "using": "EXISTS (SELECT 1 FROM publication.artifact a JOIN publication.release r ON r.id=a.publication_release_id WHERE a.id=deployment.artifact_id AND r.tenant_id=shared.current_tenant_id_soft())",
        "reason": "Read only current-authority signed deployment coordinates and acknowledgements for exact recovery admission."
      },
      {
        "relation": "publication.deployment_acknowledgement",
        "command": "SELECT",
        "using": "EXISTS (SELECT 1 FROM publication.deployment d JOIN publication.artifact a ON a.id=d.artifact_id JOIN publication.release r ON r.id=a.publication_release_id WHERE d.id=deployment_acknowledgement.deployment_id AND r.tenant_id=shared.current_tenant_id_soft())",
        "reason": "Read only current-authority signed deployment coordinates and acknowledgements for exact recovery admission."
      }
    ]
  }
]'::jsonb) LOOP
        role_name := role_contract->>'name';
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = role_name) THEN
            EXECUTE format('CREATE ROLE %I NOLOGIN', role_name);
        END IF;
        EXECUTE format('ALTER ROLE %I NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOINHERIT %s',
            role_name, CASE WHEN (role_contract->>'bypassRls')::boolean THEN 'BYPASSRLS' ELSE 'NOBYPASSRLS' END);
        IF EXISTS (SELECT 1 FROM pg_auth_members WHERE member = (SELECT oid FROM pg_roles WHERE rolname = role_name)) THEN
            RAISE EXCEPTION 'Definer owner % must not inherit or assume other roles', role_name;
        END IF;
        FOR schema_name IN SELECT jsonb_array_elements_text(role_contract->'schemas') LOOP
            IF to_regnamespace(schema_name) IS NOT NULL THEN
                EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I', schema_name, role_name);
            END IF;
        END LOOP;
        FOR object_contract IN SELECT value FROM jsonb_array_elements(role_contract->'tables') LOOP
            IF to_regclass(object_contract->>'relation') IS NOT NULL THEN
                EXECUTE format('GRANT %s ON TABLE %s TO %I',
                    (SELECT string_agg(value, ',') FROM jsonb_array_elements_text(object_contract->'privileges')),
                    (object_contract->>'relation')::regclass, role_name);
            END IF;
        END LOOP;
        FOR routine_signature IN SELECT jsonb_array_elements_text(role_contract->'functions') LOOP
            IF to_regprocedure(routine_signature) IS NOT NULL THEN
                EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO %I', routine_signature::regprocedure, role_name);
            END IF;
        END LOOP;
        FOR routine_signature IN SELECT jsonb_array_elements_text(COALESCE(role_contract->'tenantReadPolicies','[]'::jsonb)) LOOP
            IF to_regclass(routine_signature) IS NOT NULL THEN
                EXECUTE format('DROP POLICY IF EXISTS %I ON %s', role_name || '_tenant_read', routine_signature::regclass);
                EXECUTE format('CREATE POLICY %I ON %s FOR SELECT TO %I USING (tenant_id = shared.current_tenant_id_soft())',
                    role_name || '_tenant_read', routine_signature::regclass, role_name);
            END IF;
        END LOOP;
        -- Reconcile only this contract's reserved policy namespace so a stricter
        -- successor cannot leave an older permissive policy active alongside it.
        FOR old_policy IN SELECT pol.polname,pol.polrelid::regclass AS relation FROM pg_policy pol
            WHERE starts_with(pol.polname,role_name || '_p_') AND (SELECT oid FROM pg_roles WHERE rolname=role_name)=ANY(pol.polroles) LOOP
            EXECUTE format('DROP POLICY %I ON %s',old_policy.polname,old_policy.relation);
        END LOOP;
        policy_index := 0;
        FOR policy_contract IN SELECT value FROM jsonb_array_elements(COALESCE(role_contract->'policies','[]'::jsonb)) LOOP
            IF to_regclass(policy_contract->>'relation') IS NOT NULL THEN
                EXECUTE format('CREATE POLICY %I ON %s FOR %s TO %I%s%s',
                    role_name || '_p_' || policy_index, (policy_contract->>'relation')::regclass,policy_contract->>'command',role_name,
                    CASE WHEN policy_contract ? 'using' THEN ' USING (' || (policy_contract->>'using') || ')' ELSE '' END,
                    CASE WHEN policy_contract ? 'check' THEN ' WITH CHECK (' || (policy_contract->>'check') || ')' ELSE '' END);
            END IF;
            policy_index := policy_index + 1;
        END LOOP;
    END LOOP;
END
$definer_privileges$;
ALTER FUNCTION publication.fn_system_entity_authority(uuid, text) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_record_system_entity_validation(uuid, bigint, jsonb, jsonb, uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_transition_system_entity_change_set(uuid, bigint, text, text, uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_create_system_entity_release(uuid, uuid, bigint, jsonb, text[], uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_store_system_entity_artifact(uuid, text, jsonb, jsonb) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_link_system_entity_release(uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_compiled_entity_compilation_source_v2(uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_entity_successor_saved_graph(uuid, uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_entity_successor_enrollment_source(jsonb) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_create_system_entity_successor(uuid, uuid, bigint, uuid, jsonb, text[], uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_system_entity_successor_policy(uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_compiled_entity_compilation_source_v3(uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_compilation_recovery_source(jsonb, boolean) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_human_review_identity_status(uuid, uuid, uuid, uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_human_reviewed_entity_policy(jsonb, uuid, text) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_system_entity_execution_metadata(uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_human_publication_review_evidence(uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_human_execution_context(uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION publication.fn_human_publication_preparation_source(uuid) OWNER TO athyper_definer_product_publication;
ALTER FUNCTION control.publication_policy_enrollment_is_active(uuid, text, uuid, uuid) OWNER TO athyper_definer_product_publication;
