// @vitest-environment jsdom
import {act} from "react";
import {createRoot,type Root} from "react-dom/client";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
const state=vi.hoisted(()=>({selectScope:vi.fn(),scope:{} as Record<string,string>,relationships:[] as Record<string,string>[]}));
vi.mock("../business-partner-360-context",()=>({useBusinessPartner360:()=>({summary:{identity:{id:"partner"},scope:state.scope,roles:[{code:"supplier",status:"active"}],completeness:{readOnly:false},sections:[{code:"supplier-company",authorization:"granted"},{code:"customer-company",authorization:"granted"}],recordHeader:{actions:[{key:"configure_company",label:"Configure company",placement:"secondary",href:"/mdg/business-partner/partner/scope/new?companyCodeId=uk&operatingOrganizationId=org"}]}},selectScope:state.selectScope})}));
vi.mock("../company-relationships",async()=>({...await vi.importActual("../company-relationships"),useCompanyRelationships:()=>({rows:state.relationships})}));
vi.mock("@athyper/product-neon-shell",()=>({useNeonWorkContext:()=>({companies:[{companyCodeId:"uk",displayName:"UK"},{companyCodeId:"eu",displayName:"EU"}]}),useNeonOperatingOrganization:()=>({organizations:[{id:"org",displayName:"Trading",companyAssignments:[{companyCodeId:"uk"},{companyCodeId:"eu"}]},{id:"org2",displayName:"Second",companyAssignments:[{companyCodeId:"eu"}]}]})}));
vi.mock("@athyper/platform-ui",()=>({Card:({children}:any)=><section>{children}</section>}));
vi.mock("./role-company-sections",()=>({SupplierCompanySection:()=> <p>Supplier settings</p>,CustomerCompanySection:()=> <p>Customer settings</p>}));
vi.mock("../../banking-workspace",()=>({BankingWorkspace:({initialCompanyCodeId}:any)=><p>Accounts for {initialCompanyCodeId}</p>}));
import {RolesWorkspace} from "./roles-workspace";
let root:Root,host:HTMLDivElement;
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});state.selectScope.mockReset();state.scope={};state.relationships=[{companyCodeId:"uk",companyName:"UK",operatingOrganizationId:"org",operatingOrganizationName:"Trading",role:"supplier",roleStatus:"active",assignmentStatus:"active",profileStatus:"active"}];window.history.replaceState({},"","/?tab=roles");host=document.createElement("div");document.body.append(host);root=createRoot(host);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();});
it("opens the matrix without assuming a company and resolves a unique organization",async()=>{await act(async()=>root.render(<RolesWorkspace/>));expect(host.textContent).toContain("UK");expect(host.textContent).not.toContain("Supplier settings");await act(async()=>{const s=host.querySelector("#roles-company") as HTMLSelectElement;s.value="uk";s.dispatchEvent(new Event("change",{bubbles:true}));});expect(state.selectScope).toHaveBeenCalledWith("org","uk");});
it("asks for organization when company participation is ambiguous",async()=>{await act(async()=>root.render(<RolesWorkspace/>));await act(async()=>{const s=host.querySelector("#roles-company") as HTMLSelectElement;s.value="eu";s.dispatchEvent(new Event("change",{bubbles:true}));});expect(state.selectScope).not.toHaveBeenCalled();expect(host.textContent).toContain("Select organization");});
it("keeps the selected company across all sibling tabs and extension links",async()=>{state.scope={companyCodeId:"uk",operatingOrganizationId:"org"};await act(async()=>root.render(<RolesWorkspace/>));expect(host.textContent).toContain("Supplier settings");await act(async()=>{(host.querySelector("#role-tab-selling") as HTMLButtonElement).click();});expect(host.textContent).toContain("Customer settings");expect(host.querySelector("a")?.getAttribute("href")).toBe("/mdg/business-partner/partner/scope/new?companyCodeId=uk&operatingOrganizationId=org");await act(async()=>{(host.querySelector("#role-tab-banks") as HTMLButtonElement).click();});expect(host.textContent).toContain("Accounts for uk");expect(window.location.search).toContain("roleTab=banks");});

it("resolves a company-only overview deep link to its unique organization",async()=>{state.scope={companyCodeId:"uk"};await act(async()=>root.render(<RolesWorkspace/>));expect(state.selectScope).toHaveBeenCalledWith("org","uk");});
