"use client";
import { useQuery } from "@tanstack/react-query";

export type CertificationDomainKey="currency_fx"|"tax"|"payments_settlement"|"banking_treasury";
export interface CertificationDomainReadiness{domain:CertificationDomainKey;label:string;state:"not_started"|"in_progress"|"ready"|"blocked";passed:number;total:number;blockerCount:number;warningCount:number;checks:Array<{code:string;label:string;passed:boolean;classification:"setup"}>;operationalHealth?:{state:"healthy"|"attention"|"not_applicable";attentionCount:number;affectsCertification:false};primaryAction:{label:string;href:string};}
export interface CompanyCertificationReadiness{company:{id:string;code:string;name:string;legalEntityCode:string|null};asOfDate:string;domains:CertificationDomainReadiness[];summary:{passed:number;total:number;blockerCount:number;warningCount:number;readyForCertification:boolean};certification:{id:string|null;status:string|null;certifiedAt:string|null;fresh:boolean;materialChangeAt:string|null};rollout:{capabilityEnabled:boolean;mode:"observe"|"enforce";effectiveFrom:string|null;postingGateActive:boolean};status:"not_started"|"in_progress"|"blocked"|"ready_for_certification"|"certified"|"stale";computedAt:string;}
export interface CertificationReadinessRollup{scope:{type:"tenant"|"legal_entity";code:string};companies:CompanyCertificationReadiness[];summary:{companyCount:number;certifiedCount:number;readyCount:number;blockedCount:number};computedAt:string;}

export function useCompanyCertificationReadiness(companyCode:string){return useQuery({queryKey:["finance","setup","certification-readiness",companyCode],queryFn:async()=>{const params=new URLSearchParams({scopeType:"company",scopeCode:companyCode});const response=await fetch(`/api/finance/setup/certification-readiness?${params}`,{credentials:"include",cache:"no-store"});if(!response.ok)throw new Error(`Certification readiness failed: ${response.status}`);return response.json() as Promise<CompanyCertificationReadiness>;},enabled:Boolean(companyCode),staleTime:30_000});}

export function useCertificationReadinessRollup(scopeType:"tenant"|"legal_entity",scopeCode:string){return useQuery({queryKey:["finance","setup","certification-readiness-rollup",scopeType,scopeCode],queryFn:async()=>{const params=new URLSearchParams({scopeType,scopeCode});const response=await fetch(`/api/finance/setup/certification-readiness?${params}`,{credentials:"include",cache:"no-store"});if(!response.ok)throw new Error(`Certification roll-up failed: ${response.status}`);return response.json() as Promise<CertificationReadinessRollup>;},enabled:Boolean(scopeCode),staleTime:30_000});}
