"use client";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
export type SetupRow=Record<string,unknown>;
export interface PaymentTerm extends SetupRow{id:string;code:string;name:string;version:number;status:string;dueRuleType:string;dueDays:number|null;clauses:SetupRow[];discountTiers:SetupRow[];}
export interface PaymentTermDefinitions{terms:PaymentTerm[];holidayCalendars:SetupRow[];}
export interface PaymentsSetup{company:{id:string;code:string;name:string;tenantCode:string;functionalCurrency:string};asOfDate:string;methods:SetupRow[];policies:SetupRow[];bindings:SetupRow[];interfaces:SetupRow[];settlements:SetupRow[];houseBanks:SetupRow[];books:SetupRow[];postingRoleCoverage:SetupRow[];diagnostics:Array<{code:string;severity:string;message:string;policyId?:string}>;readiness:{eligibleMethods:boolean;houseBanksReady:boolean;interfacesReady:boolean;settlementReady:boolean;postingRolesReady:boolean;ready:boolean};}
export interface InterfaceTrace{request:SetupRow;found:boolean;ambiguous:boolean;winner:SetupRow|null;candidates:Array<SetupRow&{matched:boolean;reasons:string[];specificity:number[]}>;explanation:string;}
async function json<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...init?.headers}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.message??`${response.status} ${response.statusText}`);}return response.json() as Promise<T>;}
export function usePaymentTerms(tenantCode:string){return useQuery({queryKey:["finance","setup","payment-terms",tenantCode],queryFn:()=>json<PaymentTermDefinitions>(`/api/finance/setup/tenant/${encodeURIComponent(tenantCode)}/payment-terms`),enabled:Boolean(tenantCode)});}
export function useSavePaymentTerm(tenantCode:string){const qc=useQueryClient();return useMutation({mutationFn:(body:SetupRow)=>json(`/api/finance/setup/tenant/${encodeURIComponent(tenantCode)}/payment-terms`,{method:"POST",body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:["finance","setup","payment-terms",tenantCode]})});}
export function useCompanyPaymentsSetup(companyCode:string){return useQuery({queryKey:["finance","setup","payments",companyCode],queryFn:()=>json<PaymentsSetup>(`/api/finance/setup/company/${encodeURIComponent(companyCode)}/payments`),enabled:Boolean(companyCode)});}
function companyMutation(companyCode:string,path:string){const qc=useQueryClient();return useMutation({mutationFn:(body:SetupRow)=>json(`/api/finance/setup/company/${encodeURIComponent(companyCode)}/payments/${path}`,{method:"POST",body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:["finance","setup","payments",companyCode]})});}
export function useSavePaymentPolicy(companyCode:string){return companyMutation(companyCode,"policies");}
export function useSaveInterfaceBinding(companyCode:string){return companyMutation(companyCode,"interface-bindings");}
export function useSaveSettlementRule(companyCode:string){return companyMutation(companyCode,"settlement-rules");}
export function useInterfaceRoutingTrace(companyCode:string){return useMutation({mutationFn:(body:SetupRow)=>json<InterfaceTrace>(`/api/finance/setup/company/${encodeURIComponent(companyCode)}/payments/interface-trace`,{method:"POST",body:JSON.stringify(body)})});}
