"use client";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
export interface TaxComponent {id:string;taxGroupId:string;taxGroupVersionId:string|null;taxRateScheduleId:string;calculationSeq:number;rateOverride:string|null;componentCode:string|null;rateValue:string;rateKind:string;taxDirection:string;recoverabilityMode:string;reverseChargeMode:string;whtBasis:string|null;taxTypeId:string;jurisdictionId:string;}
export interface TaxGroup {id:string;code:string;name:string;description:string|null;jurisdictionId:string|null;jurisdictionCode:string|null;status:string;versionId:string|null;versionNo:number|null;effectiveFrom:string|null;effectiveTo:string|null;isCompound:boolean;roundingRuleId:string|null;versionStatus:string|null;components:TaxComponent[];}
export interface TaxSetupPayload {company:{id:string;code:string;name:string;functionalCurrency:string;tenantCode:string;countryCode:string|null;regulatoryFramework:string|null;legalEntity:{id:string;code:string;name:string};legacyRegistration:{number:string|null;jurisdictionId:string|null}};asOfDate:string;registrations:Array<Record<string,unknown>>;groups:TaxGroup[];rateSchedules:Array<Record<string,unknown>>;roundingRules:Array<Record<string,unknown>>;jurisdictions:Array<Record<string,unknown>>;whtThresholds:Array<Record<string,unknown>>;resolutionRuleCount:number;postingRoleCoverage:{requiredRoles:string[];rows:Array<{roleCode:string;roleName:string;cells:Array<{bookCode:string;status:string}>}>};readiness:{registrationReady:boolean;groupsReady:boolean;rulesReady:boolean;postingRolesReady:boolean;ready:boolean};}
export interface TaxDefinitions {groups:TaxGroup[];rateSchedules:Array<Record<string,unknown>>;roundingRules:Array<Record<string,unknown>>;jurisdictions:Array<Record<string,unknown>>;taxTypes:Array<Record<string,unknown>>;whtThresholds:Array<Record<string,unknown>>;}
export interface TaxSimulation {request:Record<string,unknown>;winner:Record<string,unknown>|null;ambiguous:boolean;candidates:Array<{ruleId:string;ruleCode:string;priority:number;matched:boolean;reasons:string[]}>;group?:Record<string,unknown>;rounding?:Record<string,unknown>;components:Array<Record<string,unknown>>;totals:{taxAmount:number;whtAmount:number;roundingAdjustment:number;grossAmount?:number};requiredPostingRoles:Array<{roleCode:string;ready:boolean}>;}
async function json<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...init?.headers}});if(!response.ok){const b=await response.json().catch(()=>({}));throw new Error(b.message??`${response.status} ${response.statusText}`);}return response.json() as Promise<T>;}
export function useCompanyTaxSetup(companyCode:string){return useQuery({queryKey:["finance","setup","tax",companyCode],queryFn:()=>json<TaxSetupPayload>(`/api/finance/setup/company/${encodeURIComponent(companyCode)}/tax`),enabled:Boolean(companyCode)});}
export function useTaxDefinitions(tenantCode:string){return useQuery({queryKey:["finance","setup","tax","definitions",tenantCode],queryFn:()=>json<TaxDefinitions>(`/api/finance/setup/tenant/${encodeURIComponent(tenantCode)}/tax/groups`),enabled:Boolean(tenantCode)});}
export function useTaxSimulation(companyCode:string){return useMutation({mutationFn:(body:Record<string,unknown>)=>json<TaxSimulation>(`/api/finance/setup/company/${encodeURIComponent(companyCode)}/tax/simulate`,{method:"POST",body:JSON.stringify(body)})});}
export function useSaveTaxRegistration(companyCode:string){const qc=useQueryClient();return useMutation({mutationFn:(body:Record<string,unknown>)=>json(`/api/finance/setup/company/${encodeURIComponent(companyCode)}/tax/registrations`,{method:"POST",body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:["finance","setup","tax",companyCode]})});}
export function useSaveTaxGroupVersion(tenantCode:string){const qc=useQueryClient();return useMutation({mutationFn:(body:Record<string,unknown>)=>json(`/api/finance/setup/tenant/${encodeURIComponent(tenantCode)}/tax/groups/versions`,{method:"POST",body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:["finance","setup","tax","definitions",tenantCode]})});}
export function useSaveWhtThreshold(tenantCode:string){const qc=useQueryClient();return useMutation({mutationFn:(body:Record<string,unknown>)=>json(`/api/finance/setup/tenant/${encodeURIComponent(tenantCode)}/tax/wht-thresholds`,{method:"POST",body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:["finance","setup","tax","definitions",tenantCode]})});}
