CREATE INDEX entity_surface_operation_change_set_ix ON metadata.entity_surface_operation (change_set_id, entity_surface_id, interaction_target, position);
CREATE INDEX entity_surface_operation_operation_ix ON metadata.entity_surface_operation (change_set_id, entity_operation_id);
CREATE INDEX entity_operation_rule_change_set_ix ON metadata.entity_operation_rule (change_set_id, entity_operation_id, priority);
CREATE INDEX entity_operation_rule_selectors_ix ON metadata.entity_operation_rule (change_set_id, plane_code, lifecycle_state_code, lifecycle_transition_code);
CREATE INDEX entity_flow_change_set_ix ON metadata.entity_flow (change_set_id, flow_kind, flow_key);
CREATE INDEX entity_flow_step_flow_ix ON metadata.entity_flow_step (entity_flow_id, position);
CREATE INDEX entity_flow_step_surface_ix ON metadata.entity_flow_step (change_set_id, entity_surface_id);
CREATE INDEX entity_policy_binding_policy_ix ON metadata.entity_policy_binding (policy_definition_id, change_set_id);
CREATE INDEX entity_policy_binding_operation_ix ON metadata.entity_policy_binding (change_set_id, entity_operation_id, binding_stage, priority);
CREATE INDEX entity_field_policy_binding_policy_ix ON metadata.entity_field_policy_binding (policy_definition_id, change_set_id);
CREATE INDEX entity_field_policy_binding_field_ix ON metadata.entity_field_policy_binding (change_set_id, entity_field_id, binding_stage, priority);
CREATE INDEX entity_contract_test_case_change_set_ix ON metadata.entity_contract_test_case (change_set_id, test_kind, test_key);
CREATE INDEX entity_contract_test_case_operation_ix ON metadata.entity_contract_test_case (change_set_id, entity_operation_id) WHERE entity_operation_id IS NOT NULL;
CREATE INDEX entity_contract_test_case_flow_ix ON metadata.entity_contract_test_case (change_set_id, entity_flow_id) WHERE entity_flow_id IS NOT NULL;
