import { createHash, randomUUID } from "node:crypto";
import type { AuditRecorder } from "@athyper/server-contract-audit";
import type { Authorizer, VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { OutboxWriter } from "@athyper/server-contract-events";
import type { ProvisioningCreateCommand, ProvisioningCreateResult, ProvisioningVertical } from "./provisioning-vertical.js";

export type ProvisioningAttemptStatus="claimed"|"started"|"applied"|"failed"|"cancelled";
export interface ProvisioningAttemptReceipt{readonly attemptId:string;readonly requestId:string;readonly attemptNo:number;readonly workerId:string;readonly status:ProvisioningAttemptStatus;readonly rowVersion:number;readonly leaseExpiresAt:string;readonly startedAt?:string;readonly terminalAt?:string;readonly errorCode?:string;readonly receipt:Readonly<Record<string,unknown>>;readonly replayed:boolean}
export type ProvisioningAttemptResult={readonly kind:"transitioned"|"replayed";readonly receipt:ProvisioningAttemptReceipt}|{readonly kind:"conflict";readonly reason:"already_claimed"|"invalid_state"|"stale_version"|"already_applied"};
export interface IdentityProvisioningAttemptRepository<Transaction>{claim(input:{readonly tenantId:string;readonly requestId:string;readonly attemptId:string;readonly workerId:string;readonly claimTokenHash:string;readonly claimedAt:string;readonly leaseExpiresAt:string;readonly retryOnly:boolean},transaction:Transaction):Promise<ProvisioningAttemptResult>;transition(input:{readonly tenantId:string;readonly requestId:string;readonly attemptId:string;readonly expectedStatus:"claimed"|"started";readonly to:"started"|"applied"|"failed"|"cancelled";readonly claimTokenHash:string;readonly expectedVersion:number;readonly occurredAt:string;readonly errorCode?:string;readonly providerSubject?:string;readonly receipt:Readonly<Record<string,unknown>>},transaction:Transaction):Promise<ProvisioningAttemptResult>}
export interface IdentityProvisioningServiceOptions<Transaction>{readonly create:ProvisioningVertical;readonly repository:IdentityProvisioningAttemptRepository<Transaction>;readonly transactions:{run<Result>(actor:{tenantId:string;principalId:string},work:(transaction:Transaction)=>Promise<Result>):Promise<Result>};readonly authorizer:Authorizer;readonly audit:AuditRecorder<Transaction>;readonly outbox:OutboxWriter<Transaction>;readonly now?:()=>Date;readonly createId?:()=>string;readonly leaseMs?:number}

export class IdentityProvisioningService<Transaction>{private readonly now:()=>Date;private readonly createId:()=>string;private readonly leaseMs:number;constructor(private readonly options:IdentityProvisioningServiceOptions<Transaction>){this.now=options.now??(()=>new Date());this.createId=options.createId??randomUUID;this.leaseMs=options.leaseMs??60_000;if(this.leaseMs<1)throw new TypeError("Provisioning lease must be positive");}
 request(command:ProvisioningCreateCommand):Promise<ProvisioningCreateResult>{return this.options.create.request(command);}
 claim(command:{context:VerifiedRequestContext;requestId:string;workerId:string;claimToken:string}):Promise<ProvisioningAttemptResult>{return this.claimAttempt(command,false);}
 retry(command:{context:VerifiedRequestContext;requestId:string;workerId:string;claimToken:string}):Promise<ProvisioningAttemptResult>{return this.claimAttempt(command,true);}
 start(command:TransitionCommand):Promise<ProvisioningAttemptResult>{return this.transition(command,"claimed","started");}
 apply(command:TransitionCommand&{providerSubject?:string}):Promise<ProvisioningAttemptResult>{return this.transition(command,"started","applied");}
 fail(command:TransitionCommand&{errorCode:string}):Promise<ProvisioningAttemptResult>{return this.transition(command,command.expectedStatus??"started","failed");}
 cancel(command:TransitionCommand&{errorCode?:string}):Promise<ProvisioningAttemptResult>{return this.transition({...command,errorCode:command.errorCode??"worker_cancelled"},command.expectedStatus??"started","cancelled");}
 private async claimAttempt(command:{context:VerifiedRequestContext;requestId:string;workerId:string;claimToken:string},retryOnly:boolean){await authorize(this.options.authorizer,command.context);const now=this.now(),input={tenantId:command.context.tenantId,requestId:command.requestId,attemptId:this.createId(),workerId:bounded(command.workerId,128),claimTokenHash:sha(command.claimToken),claimedAt:now.toISOString(),leaseExpiresAt:new Date(now.getTime()+this.leaseMs).toISOString(),retryOnly};return this.options.transactions.run({tenantId:command.context.tenantId,principalId:command.context.principalId},async tx=>{const result=await this.options.repository.claim(input,tx);if(result.kind==="transitioned")await evidence(this.options,command.context,result.receipt,"claimed",tx);return result;});}
 private async transition(command:TransitionCommand,expectedStatus:"claimed"|"started",to:"started"|"applied"|"failed"|"cancelled"){await authorize(this.options.authorizer,command.context);version(command.expectedVersion);const receipt=boundedReceipt(command.receipt??{}),occurredAt=this.now().toISOString();return this.options.transactions.run({tenantId:command.context.tenantId,principalId:command.context.principalId},async tx=>{const result=await this.options.repository.transition({tenantId:command.context.tenantId,requestId:command.requestId,attemptId:command.attemptId,expectedStatus,to,claimTokenHash:sha(command.claimToken),expectedVersion:command.expectedVersion,occurredAt,...(command.errorCode?{errorCode:bounded(command.errorCode,128)}:{}),...(command.providerSubject?{providerSubject:bounded(command.providerSubject,320)}:{}),receipt},tx);if(result.kind==="transitioned")await evidence(this.options,command.context,result.receipt,to,tx);return result;});}}
interface TransitionCommand{readonly context:VerifiedRequestContext;readonly requestId:string;readonly attemptId:string;readonly claimToken:string;readonly expectedVersion:number;readonly expectedStatus?:"claimed"|"started";readonly errorCode?:string;readonly providerSubject?:string;readonly receipt?:Readonly<Record<string,unknown>>}
async function authorize(authorizer:Authorizer,context:VerifiedRequestContext){const result=await authorizer.authorize({context,permissionCode:"iam.provisioning.execute"});if(!result.allowed)throw new Error("IAM_PROVISIONING_FORBIDDEN");}
async function evidence<T>(options:IdentityProvisioningServiceOptions<T>,context:VerifiedRequestContext,receipt:ProvisioningAttemptReceipt,status:string,tx:T){const eventCode=`iam.provisioning.${status}`;await options.outbox.append({tenantId:context.tenantId,topic:"iam.provisioning",eventType:eventCode,eventKey:`${receipt.requestId}:${receipt.attemptNo}:${status}`,entityType:"trustiam.identity_provisioning_attempt",entityId:receipt.attemptId,aggregateType:"trustiam.identity_provisioning_request",aggregateId:receipt.requestId,actorId:context.principalId,correlationId:context.correlationId,payload:{requestId:receipt.requestId,attemptId:receipt.attemptId,attemptNo:receipt.attemptNo,status}},tx);await options.audit.record({eventCode,action:status,outcome:status==="failed"?"failure":"success",actor:{kind:"service",principalId:context.principalId},tenantId:context.tenantId,entityType:"trustiam.identity_provisioning_attempt",entityId:receipt.attemptId,requestId:context.requestId,...(context.correlationId?{correlationId:context.correlationId}:{}),metadata:{requestId:receipt.requestId,attemptNo:receipt.attemptNo,workerId:receipt.workerId}},tx);}
function boundedReceipt(value:Readonly<Record<string,unknown>>){if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError("Provisioning receipt must be a bounded object");const text=JSON.stringify(value);if(text===undefined||Buffer.byteLength(text,"utf8")>32768||sensitive(value))throw new TypeError("Provisioning receipt must be bounded and content-free");return value;}function sensitive(value:unknown):boolean{if(Array.isArray(value))return value.some(sensitive);if(!value||typeof value!=="object")return false;return Object.entries(value as Record<string,unknown>).some(([key,child])=>/(secret|password|token|body|content|credential)/i.test(key)||sensitive(child));}function sha(value:string){if(!value)throw new TypeError("Claim token is required");return createHash("sha256").update(value).digest("hex");}function bounded(value:string,max:number){const result=value.trim();if(!result||Buffer.byteLength(result,"utf8")>max)throw new TypeError("Provisioning value is invalid");return result;}function version(value:number){if(!Number.isSafeInteger(value)||value<1)throw new TypeError("Provisioning version must be positive");}
