import { sql, type Kysely, type Transaction } from "kysely";
import { projectionJobIdentity, type ExactPlaneProjectionApplier, type ProjectionAttemptCoordinate, type ProjectionReconciliationRepository, type ProjectionReconciliationWork } from "./projection-reconciliation.js";

type Db=Record<string,never>;type Row=Record<string,unknown>;type Executor=Kysely<Db>|Transaction<Db>;

export class KyselyProjectionReconciliationRepository implements ProjectionReconciliationRepository {
  constructor(private readonly studio:Kysely<Db>){}
  claim(input:{workerId:string;claimTokenHash:string;claimedAt:string;leaseExpiresAt:string}):Promise<ProjectionReconciliationWork|undefined>{return this.studio.transaction().execute(async tx=>{
    await sql`UPDATE trustiam.projection_reconciliation_attempt SET status='failed',failure_class='transient',error_code='PROJECTION_LEASE_EXPIRED',terminal_at=${input.claimedAt}::timestamptz,next_attempt_at=${input.claimedAt}::timestamptz,updated_by=created_by WHERE status IN ('claimed','running') AND lease_expires_at<=${input.claimedAt}::timestamptz`.execute(tx);
    const source=(await sql<Row>`SELECT p.*,o.realm_key,o.external_organization_id,o.organization_alias,o.display_name
      FROM trustiam.application_projection p JOIN trustiam.organization o ON o.authority_tenant_id=p.authority_tenant_id AND o.id=p.organization_id
      WHERE p.reconciliation_status IN ('pending','drifted','failed') AND p.status IN ('pending','provisioning','active','suspended')
        AND NOT EXISTS(SELECT 1 FROM trustiam.projection_reconciliation_attempt open_attempt WHERE open_attempt.authority_tenant_id=p.authority_tenant_id AND open_attempt.projection_id=p.id AND open_attempt.status IN ('claimed','running','retrying'))
        AND COALESCE((SELECT CASE WHEN last_attempt.status='dead_letter' THEN last_attempt.replay_requested_at IS NOT NULL WHEN last_attempt.status='failed' THEN last_attempt.next_attempt_at<=${input.claimedAt}::timestamptz ELSE true END FROM trustiam.projection_reconciliation_attempt last_attempt WHERE last_attempt.authority_tenant_id=p.authority_tenant_id AND last_attempt.projection_id=p.id ORDER BY last_attempt.attempt_no DESC LIMIT 1),true)
      ORDER BY p.updated_at NULLS FIRST,p.created_at FOR UPDATE OF p SKIP LOCKED LIMIT 1`.execute(tx)).rows[0];if(!source)return undefined;
    const projectionId=text(source,"id"),authorityTenantId=text(source,"authority_tenant_id"),desiredVersion=integer(source,"desired_version"),desiredHash=text(source,"desired_hash"),targetPlane=text(source,"target_plane") as ProjectionReconciliationWork["targetPlane"],targetTenantId=text(source,"target_tenant_id");
    const sequence=(await sql<{attempt_no:number;fencing_token:string}>`SELECT coalesce(max(attempt_no),0)::int+1 attempt_no,coalesce(max(fencing_token),0)::bigint+1 fencing_token FROM trustiam.projection_reconciliation_attempt WHERE authority_tenant_id=${authorityTenantId}::uuid AND projection_id=${projectionId}::uuid`.execute(tx)).rows[0]!;
    const identity=projectionJobIdentity({projectionId,desiredVersion,desiredHash,targetPlane,targetTenantId,attemptNo:sequence.attempt_no});
    const attempt=(await sql<Row>`INSERT INTO trustiam.projection_reconciliation_attempt(authority_tenant_id,projection_id,desired_version,desired_hash,target_plane,target_tenant_id,attempt_no,job_identity_hash,worker_id,claim_token_hash,fencing_token,status,lease_expires_at,manual_replay_of,created_at,created_by)
      VALUES(${authorityTenantId}::uuid,${projectionId}::uuid,${desiredVersion},${desiredHash},${targetPlane},${targetTenantId}::uuid,${sequence.attempt_no},${identity},${input.workerId},${input.claimTokenHash},${Number(sequence.fencing_token)},'claimed',${input.leaseExpiresAt}::timestamptz,(SELECT id FROM trustiam.projection_reconciliation_attempt WHERE authority_tenant_id=${authorityTenantId}::uuid AND projection_id=${projectionId}::uuid AND status='dead_letter' AND replay_requested_at IS NOT NULL ORDER BY attempt_no DESC LIMIT 1),${input.claimedAt}::timestamptz,${text(source,"created_by")}::uuid) RETURNING id`.execute(tx)).rows[0]!;
    const providers=(await sql<Row>`SELECT id,provider_code,protocol,external_provider_id FROM trustiam.organization_provider WHERE authority_tenant_id=${authorityTenantId}::uuid AND organization_id=${text(source,"organization_id")}::uuid AND status='active' ORDER BY provider_code`.execute(tx)).rows;
    const scopes=(await sql<Row>`SELECT id,scope_kind,target_id,ceiling_mode,network_role_ceiling,desired_version FROM trustiam.projection_scope WHERE authority_tenant_id=${authorityTenantId}::uuid AND projection_id=${projectionId}::uuid AND status='active' AND desired_version=${desiredVersion} ORDER BY scope_kind,target_id`.execute(tx)).rows;
    const desiredPayload={projection:{id:projectionId,sourceProjectionId:projectionId,sourceVersion:desiredVersion,sourceHash:desiredHash,realmKey:text(source,"realm_key"),externalOrganizationId:text(source,"external_organization_id"),organizationAlias:optional(source,"organization_alias"),organizationName:text(source,"display_name"),metadata:object(source["metadata"])},providers:providers.map(row=>({id:text(row,"id"),providerCode:text(row,"provider_code"),protocol:text(row,"protocol"),externalProviderId:optional(row,"external_provider_id"),sourceProviderId:text(row,"id"),sourceVersion:desiredVersion})),scopes:scopes.map(row=>({id:text(row,"id"),scopeTargetId:text(row,"target_id"),ceilingMode:text(row,"ceiling_mode"),networkRoleCeiling:optional(row,"network_role_ceiling"),sourceScopeId:text(row,"id"),sourceVersion:integer(row,"desired_version")}))};
    return{attemptId:text(attempt,"id"),authorityTenantId,projectionId,desiredVersion,desiredHash,targetPlane,targetTenantId,attemptNo:sequence.attempt_no,jobIdentityHash:identity,claimTokenHash:input.claimTokenHash,fencingToken:Number(sequence.fencing_token),desiredPayload};
  });}
  async current(work:ProjectionReconciliationWork){const row=(await sql<{current:boolean}>`SELECT EXISTS(SELECT 1 FROM trustiam.application_projection p WHERE p.authority_tenant_id=${work.authorityTenantId}::uuid AND p.id=${work.projectionId}::uuid AND p.desired_version=${work.desiredVersion} AND p.desired_hash=${work.desiredHash} AND p.target_plane=${work.targetPlane} AND p.target_tenant_id=${work.targetTenantId}::uuid AND NOT EXISTS(SELECT 1 FROM trustiam.projection_reconciliation_attempt newer WHERE newer.authority_tenant_id=p.authority_tenant_id AND newer.projection_id=p.id AND newer.fencing_token>${work.fencingToken})) current`.execute(this.studio)).rows[0];return row?.current===true;}
  start(c:ProjectionAttemptCoordinate,startedAt:string){return this.transition(c,sql`status='running',started_at=${startedAt}::timestamptz`,'claimed');}
  succeed(c:ProjectionAttemptCoordinate,input:{observedAt:string;receipt:Readonly<Record<string,unknown>>}){return this.studio.transaction().execute(async tx=>{const changed=await this.transition(c,sql`status='succeeded',terminal_at=${input.observedAt}::timestamptz,receipt=${JSON.stringify(input.receipt)}::jsonb`,'running',tx);if(!changed)return false;const updated=await sql`UPDATE trustiam.application_projection SET reconciliation_status='in_sync',last_reconciled_at=${input.observedAt}::timestamptz,last_error_code=NULL,updated_by=created_by WHERE id=(SELECT projection_id FROM trustiam.projection_reconciliation_attempt WHERE id=${c.attemptId}::uuid) AND desired_version=${c.desiredVersion} AND desired_hash=${c.desiredHash}`.execute(tx);return Number(updated.numAffectedRows??0)===1;});}
  fail(c:ProjectionAttemptCoordinate,input:{failedAt:string;classification:"transient"|"permanent"|"stale";errorCode:string;nextAttemptAt?:string;deadLetter:boolean;receipt:Readonly<Record<string,unknown>>}){return this.studio.transaction().execute(async tx=>{const state=input.deadLetter?'dead_letter':'failed';const changed=await this.transition(c,sql`status=${state},failure_class=${input.classification},error_code=${input.errorCode},next_attempt_at=${input.nextAttemptAt??null}::timestamptz,terminal_at=${input.failedAt}::timestamptz,receipt=${JSON.stringify(input.receipt)}::jsonb`,'running',tx)||await this.transition(c,sql`status=${state},failure_class=${input.classification},error_code=${input.errorCode},next_attempt_at=${input.nextAttemptAt??null}::timestamptz,terminal_at=${input.failedAt}::timestamptz,receipt=${JSON.stringify(input.receipt)}::jsonb`,'claimed',tx);if(!changed)return false;await sql`UPDATE trustiam.application_projection SET reconciliation_status='failed',last_reconciled_at=${input.failedAt}::timestamptz,last_error_code=${input.errorCode},updated_by=created_by WHERE id=(SELECT projection_id FROM trustiam.projection_reconciliation_attempt WHERE id=${c.attemptId}::uuid) AND desired_version=${c.desiredVersion} AND desired_hash=${c.desiredHash}`.execute(tx);return true;});}
  async replay(input:{authorityTenantId:string;deadLetterAttemptId:string;actorId:string;requestedAt:string}){const changed=await sql`UPDATE trustiam.projection_reconciliation_attempt SET replay_requested_at=${input.requestedAt}::timestamptz,replay_requested_by=${input.actorId}::uuid,updated_by=${input.actorId}::uuid WHERE authority_tenant_id=${input.authorityTenantId}::uuid AND id=${input.deadLetterAttemptId}::uuid AND status='dead_letter' AND replay_requested_at IS NULL`.execute(this.studio);return Number(changed.numAffectedRows??0)===1;}
  async health(authorityTenantId:string){const row=(await sql<Row>`SELECT count(*) FILTER(WHERE p.reconciliation_status='in_sync')::int in_sync,count(*) FILTER(WHERE p.reconciliation_status='pending')::int pending,count(*) FILTER(WHERE p.reconciliation_status='drifted')::int drifted,count(*) FILTER(WHERE p.reconciliation_status='failed')::int failed,(SELECT count(*)::int FROM trustiam.projection_reconciliation_attempt a WHERE a.authority_tenant_id=${authorityTenantId}::uuid AND a.status='dead_letter' AND a.replay_requested_at IS NULL) dead_letters,min(coalesce(p.updated_at,p.created_at)) FILTER(WHERE p.reconciliation_status<>'in_sync') oldest FROM trustiam.application_projection p WHERE p.authority_tenant_id=${authorityTenantId}::uuid`.execute(this.studio)).rows[0]??{};return{inSync:integer(row,"in_sync",0),pending:integer(row,"pending",0),drifted:integer(row,"drifted",0),failed:integer(row,"failed",0),deadLetters:integer(row,"dead_letters",0),...(row["oldest"]?{oldestUnreconciledAt:new Date(String(row["oldest"])).toISOString()}:{})};}
  private async transition(c:ProjectionAttemptCoordinate,set:ReturnType<typeof sql>,from:string,executor:Executor=this.studio){const result=await sql`UPDATE trustiam.projection_reconciliation_attempt SET ${set},updated_by=created_by WHERE id=${c.attemptId}::uuid AND status=${from} AND claim_token_hash=${c.claimTokenHash} AND fencing_token=${c.fencingToken} AND desired_version=${c.desiredVersion} AND desired_hash=${c.desiredHash} AND lease_expires_at>clock_timestamp()`.execute(executor);return Number(result.numAffectedRows??0)===1;}
}

export class KyselyExactPlaneProjectionApplier implements ExactPlaneProjectionApplier {
  constructor(private readonly targets:{run<Result>(plane:ProjectionReconciliationWork["targetPlane"],work:(transaction:Transaction<Db>)=>Promise<Result>):Promise<Result>},private readonly actorId:string){}
  apply(work:ProjectionReconciliationWork){return this.targets.run(work.targetPlane,async transaction=>{if(!await currentTargetWork(work,transaction))throw coded("PROJECTION_TARGET_TENANT_MISMATCH");const payload=work.desiredPayload as {projection:Record<string,unknown>;providers:unknown[];scopes:unknown[]};await sql`SELECT authz.fn_stage_application_projection(${work.targetTenantId}::uuid,${JSON.stringify(payload.projection)}::jsonb,${JSON.stringify(payload.providers)}::jsonb,${JSON.stringify(payload.scopes)}::jsonb,${this.actorId}::uuid)`.execute(transaction);const row=requiredRow((await sql<Row>`SELECT (authz.fn_activate_application_projection(${work.targetTenantId}::uuid,${work.projectionId}::uuid,${work.desiredVersion},${work.desiredHash},${this.actorId}::uuid)).*`.execute(transaction)).rows[0]);return{desiredVersion:integer(row,"source_version"),desiredHash:text(row,"source_hash"),targetProjectionId:text(row,"id")};});}
}
async function currentTargetWork(work:ProjectionReconciliationWork,transaction:Transaction<Db>){const row=(await sql<{matches:boolean}>`SELECT current_setting('app.database_plane',true)=${work.targetPlane} matches`.execute(transaction)).rows[0];return row?.matches===true;}
function requiredRow(row:Row|undefined){if(!row)throw coded("PROJECTION_TARGET_ACTIVATION_EMPTY");return row;}function text(row:Row,key:string){const value=row[key];if(typeof value!=="string")throw coded(`PROJECTION_ROW_INVALID_${key.toUpperCase()}`);return value;}function optional(row:Row,key:string){const value=row[key];return typeof value==="string"&&value.trim()?value:undefined;}function integer(row:Row,key:string,fallback?:number){const value=Number(row[key]);if(Number.isInteger(value))return value;if(fallback!==undefined)return fallback;throw coded(`PROJECTION_ROW_INVALID_${key.toUpperCase()}`);}function object(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}function coded(code:string){return Object.assign(new Error(code),{code});}
