import {sql,type Transaction} from "kysely";
import type {NotificationChannel,NotificationChannelHandler,NotificationDeliveryRequest,NotificationEventPublisher} from "@athyper/server-contract-notifications";
import type {NotificationAttachmentReference,NotificationTransportAttachment} from "@athyper/server-contract-notifications";
import type {NotificationAttachmentResolver} from "@athyper/server-contract-documents";
import type {JobExecutionResult,JobHandler} from "@athyper/server-contract-jobs";
import type {PlaneKey} from "@athyper/server-foundation/context";
import type {PlaneTransactionCoordinator} from "@athyper/server-foundation/transaction";

export const DELIVERY_SWEEP_JOB="notifications.delivery-sweep";
export interface DeliverySweepRequest{readonly planeKey:PlaneKey;readonly tenantId:string;readonly principalId:string;readonly workerId:string;readonly batchSize?:number;}
export interface ClaimedNotificationDelivery{readonly id:string;readonly tenantId:string;readonly planeKey:PlaneKey;readonly messageId:string;readonly principalId:string;readonly actorPrincipalId:string;readonly recipientAddress:string;readonly channel:NotificationChannel;readonly templateKey:string;readonly subject:string|null;readonly payload:Readonly<Record<string,unknown>>;readonly attemptCount:number;readonly maxAttempts:number;readonly workerId:string;}
export interface DeliveryOutcome{readonly delivered:boolean;readonly retryable:boolean;readonly externalId?:string;readonly confirmation?:"delivered"|"provider_accepted";readonly error?:string;readonly durationMs:number;readonly suppressed?:boolean;}
export interface DurableNotificationDeliveryRepository{claim(input:DeliverySweepRequest):Promise<readonly ClaimedNotificationDelivery[]>;attachments(delivery:ClaimedNotificationDelivery):Promise<readonly StoredAttachmentReference[]>;complete(delivery:ClaimedNotificationDelivery,outcome:DeliveryOutcome,actorId:string):Promise<void>;}
interface StoredAttachmentReference extends NotificationAttachmentReference { readonly sortOrder:number; }

export function createDurableNotificationDeliveryRepository(options:{readonly transactions:PlaneTransactionCoordinator<Transaction<Record<string,never>>>;readonly onTerminalFailure?:(delivery:ClaimedNotificationDelivery,error:string,transaction:Transaction<Record<string,never>>)=>Promise<void>}):DurableNotificationDeliveryRepository{return {
 async claim(input){const batch=bounded(input.batchSize??50,1,250);return options.transactions.run(input.planeKey,input,async tx=>{const result=await sql<Record<string,unknown>>`SELECT claimed.*,message.plane_key,message.template_key,message.subject,message.payload AS message_payload,message.created_by AS actor_principal_id FROM event.fn_notification_claim_deliveries(${input.tenantId}::uuid,${input.workerId},${batch},60) claimed JOIN event.notification_message message ON message.tenant_id=claimed.tenant_id AND message.id=claimed.message_id`.execute(tx);return result.rows.map(row=>candidate(row,input.workerId));});},
 async attachments(delivery){return options.transactions.run(delivery.planeKey,{tenantId:delivery.tenantId,principalId:delivery.principalId},async tx=>{const result=await sql<Record<string,unknown>>`SELECT attachment_id,attachment_version_id,version_policy,requested_disposition,is_required,display_name,sort_order FROM event.notification_message_attachment WHERE tenant_id=${delivery.tenantId}::uuid AND message_id=${delivery.messageId}::uuid ORDER BY sort_order,id`.execute(tx);return result.rows.map(reference);});},
 async complete(delivery,outcome,actorId){await options.transactions.run(delivery.planeKey,{tenantId:delivery.tenantId,principalId:actorId},async tx=>{const terminal=!outcome.delivered&&(!outcome.retryable||delivery.attemptCount>=delivery.maxAttempts);if(terminal&&!outcome.suppressed&&options.onTerminalFailure)await options.onTerminalFailure(delivery,outcome.error??'DELIVERY_FAILED',tx);if(outcome.suppressed){await sql`UPDATE event.notification_delivery SET status='cancelled',last_error=${outcome.error??'NOTIFICATION_SUPPRESSED'},error_category=NULL,next_retry_at=NULL,locked_until=NULL,metadata=metadata||jsonb_build_object('suppressed',true,'suppressionReason',${outcome.error??'NOTIFICATION_SUPPRESSED'}),channel_detail=channel_detail-'claimed_by'-'claimed_at',updated_at=now(),updated_by=${actorId}::uuid WHERE tenant_id=${delivery.tenantId}::uuid AND id=${delivery.id}::uuid`.execute(tx);}else if(outcome.delivered){const providerAccepted=outcome.confirmation==="provider_accepted";await sql`UPDATE event.notification_delivery SET status=${providerAccepted?"sent":"delivered"},external_id=${outcome.externalId??null},sent_at=COALESCE(sent_at,now()),delivered_at=${providerAccepted?null:sql`now()`},last_error=NULL,error_category=NULL,next_retry_at=NULL,locked_until=NULL,channel_detail=channel_detail-'claimed_by'-'claimed_at',updated_at=now(),updated_by=${actorId}::uuid WHERE tenant_id=${delivery.tenantId}::uuid AND id=${delivery.id}::uuid`.execute(tx);if(delivery.channel==="in_app")await sql`INSERT INTO event.notification_inbox_state (tenant_id,message_id,delivery_id,principal_id,channel_code) VALUES (${delivery.tenantId}::uuid,${delivery.messageId}::uuid,${delivery.id}::uuid,${delivery.principalId}::uuid,'in_app') ON CONFLICT DO NOTHING`.execute(tx);}else{const delay=Math.min(3_600_000,Math.max(5_000,30_000*2**Math.max(0,delivery.attemptCount-1)));await sql`UPDATE event.notification_delivery SET status='failed',last_error=${(outcome.error??"delivery failed").slice(0,4000)},error_category=${outcome.retryable?"transient":"permanent"},next_retry_at=${terminal?null:new Date(Date.now()+delay).toISOString()}::timestamptz,locked_until=NULL,channel_detail=channel_detail-'claimed_by'-'claimed_at',updated_at=now(),updated_by=${actorId}::uuid WHERE tenant_id=${delivery.tenantId}::uuid AND id=${delivery.id}::uuid`.execute(tx);if(terminal)await sql`INSERT INTO log.notification_dlq (tenant_id,queue_name,job_name,payload,error_message,retry_count,last_attempted_at) VALUES (${delivery.tenantId}::uuid,'notifications.delivery',${delivery.channel},${JSON.stringify({deliveryId:delivery.id,messageId:delivery.messageId,channel:delivery.channel})}::jsonb,${(outcome.error??"delivery failed").slice(0,4000)},${delivery.attemptCount},now())`.execute(tx);}
 await sql`INSERT INTO log.notification_delivery_attempt (tenant_id,delivery_id,request_url,request_method,duration_ms,is_success,error,is_redacted,redaction_version,created_by) VALUES (${delivery.tenantId}::uuid,${delivery.id}::uuid,${`provider:${delivery.channel}`},'POST',${Math.max(0,Math.round(outcome.durationMs))},${outcome.delivered},${outcome.error??null},true,'notification-v1',${actorId}::uuid)`.execute(tx);
 await sql`UPDATE event.notification_message message SET delivered_count=aggregate.delivered,failed_count=aggregate.failed,status=CASE WHEN aggregate.pending>0 THEN 'delivering' WHEN aggregate.failed=0 THEN 'completed' WHEN aggregate.delivered=0 THEN 'failed' ELSE 'partially_sent' END,completed_at=CASE WHEN aggregate.pending=0 THEN now() ELSE NULL END,updated_at=now(),updated_by=${actorId}::uuid FROM (SELECT message_id,count(*) FILTER(WHERE status='delivered')::int delivered,count(*) FILTER(WHERE status='failed' AND (attempt_count>=max_attempts OR error_category='permanent'))::int failed,count(*) FILTER(WHERE status IN ('pending','queued','sending','sent') OR (status='failed' AND attempt_count<max_attempts AND error_category<>'permanent'))::int pending FROM event.notification_delivery WHERE tenant_id=${delivery.tenantId}::uuid AND message_id=${delivery.messageId}::uuid GROUP BY message_id) aggregate WHERE message.tenant_id=${delivery.tenantId}::uuid AND message.id=aggregate.message_id`.execute(tx);});}
};}

export function createDeliverySweepHandler(options:{readonly repository:DurableNotificationDeliveryRepository;readonly handlers:ReadonlyMap<NotificationChannel,NotificationChannelHandler>;readonly events:NotificationEventPublisher;readonly attachments?:NotificationAttachmentResolver;readonly authorizeDelivery?:(delivery:ClaimedNotificationDelivery)=>Promise<{allowed:boolean;reason?:string}>}):JobHandler<typeof DELIVERY_SWEEP_JOB,DeliverySweepRequest>{return {async handle(job,context):Promise<JobExecutionResult>{const request=valid(job.data);const claimed=await options.repository.claim(request);let delivered=0,failed=0,suppressed=0;for(const item of claimed){if(context.signal.aborted)throw new Error("Notification delivery sweep aborted");const started=Date.now();try{if(options.authorizeDelivery){const access=await options.authorizeDelivery(item);if(!access.allowed){await options.repository.complete(item,{delivered:false,retryable:false,suppressed:true,error:access.reason??'NOTIFICATION_RECIPIENT_INELIGIBLE',durationMs:Date.now()-started},item.actorPrincipalId);suppressed++;continue;}}const attachments=await resolveAttachments(options,item);if(item.channel==="in_app"){await options.repository.complete(item,{delivered:true,retryable:false,externalId:item.messageId,durationMs:Date.now()-started},item.actorPrincipalId);await options.events.publish({type:"notification.created",tenantId:item.tenantId,principalId:item.principalId,notificationId:item.messageId,occurredAt:new Date().toISOString()});delivered++;continue;}const handler=options.handlers.get(item.channel);if(!handler)throw permanent(`No ${item.channel} notification handler is configured`);const result=await handler.send(toRequest(item,attachments));await options.repository.complete(item,{delivered:true,retryable:false,...(result.externalId?{externalId:result.externalId}:{}),...(result.confirmation?{confirmation:result.confirmation}:{}),durationMs:Date.now()-started},item.actorPrincipalId);delivered++;}catch(error){await options.repository.complete(item,{delivered:false,retryable:retryable(error),error:error instanceof Error?error.message:String(error),durationMs:Date.now()-started},item.actorPrincipalId);failed++;}}return {status:"completed",output:{claimed:claimed.length,delivered,failed,...(suppressed?{suppressed}:{})}};}};}
async function resolveAttachments(options:{readonly repository:DurableNotificationDeliveryRepository;readonly attachments?:NotificationAttachmentResolver},item:ClaimedNotificationDelivery):Promise<readonly NotificationTransportAttachment[]>{const references=await options.repository.attachments(item);if(references.length===0)return[];if(!options.attachments)throw permanent("Notification attachment resolver is not configured");const resolved:NotificationTransportAttachment[]=[];for(const reference of references){try{const accessMode=reference.requestedDisposition==="embed"&&item.channel==="email"?"content":"link";const attachment=await options.attachments.resolveForDelivery({planeKey:item.planeKey,tenantId:item.tenantId,actorPrincipalId:item.principalId,recipientPrincipalId:item.principalId,attachmentId:reference.attachmentId,versionPolicy:reference.versionPolicy,...(reference.attachmentVersionId?{attachmentVersionId:reference.attachmentVersionId}:{}),accessMode,purpose:"notification_delivery",deliveryId:item.id});resolved.push({...attachment,filename:reference.displayName??attachment.filename});}catch(error){if(reference.required)throw error;}}return resolved;}
function toRequest(item:ClaimedNotificationDelivery,attachments:readonly NotificationTransportAttachment[]):NotificationDeliveryRequest{return {deliveryId:item.id,channel:item.channel,recipientAddress:item.recipientAddress,templateKey:item.templateKey,subject:item.subject,payload:item.payload,planeKey:item.planeKey,tenantId:item.tenantId,recipientId:item.principalId,...(attachments.length?{attachments}:{})};}
function candidate(row:Record<string,unknown>,workerId:string):ClaimedNotificationDelivery{const details=object(row["channel_detail"]);return {id:String(row["id"]),tenantId:String(row["tenant_id"]),planeKey:row["plane_key"] as PlaneKey,messageId:String(row["message_id"]),principalId:String(row["recipient_id"]),actorPrincipalId:String(row["actor_principal_id"]),recipientAddress:String(row["recipient_addr"]),channel:row["channel"] as NotificationChannel,templateKey:String(row["template_key"]),subject:typeof row["subject"]==="string"?row["subject"]:null,payload:Object.keys(details).length?details:object(row["message_payload"]),attemptCount:Number(row["attempt_count"]),maxAttempts:Number(row["max_attempts"]),workerId};}
function reference(row:Record<string,unknown>):StoredAttachmentReference{return {attachmentId:String(row["attachment_id"]),versionPolicy:row["version_policy"] as "current"|"pinned",...(typeof row["attachment_version_id"]==="string"?{attachmentVersionId:row["attachment_version_id"]}:{}),requestedDisposition:row["requested_disposition"] as "link"|"embed"|"auto",required:row["is_required"]!==false,...(typeof row["display_name"]==="string"?{displayName:row["display_name"]}:{}),sortOrder:Number(row["sort_order"])};}
function object(value:unknown):Record<string,unknown>{if(value&&typeof value==="object"&&!Array.isArray(value))return value as Record<string,unknown>;if(typeof value==="string"){const parsed=JSON.parse(value) as unknown;if(parsed&&typeof parsed==="object"&&!Array.isArray(parsed))return parsed as Record<string,unknown>;}return {};}
function retryable(error:unknown){return !error||typeof error!=="object"||Reflect.get(error,"retryable")!==false;}function permanent(message:string){const error=new Error(message);Object.assign(error,{retryable:false});return error;}function bounded(value:number,min:number,max:number){if(!Number.isInteger(value)||value<min||value>max)throw new TypeError(`batchSize must be ${min}-${max}`);return value;}function valid(value:DeliverySweepRequest){if(!/^[0-9a-f-]{36}$/i.test(value.tenantId)||!/^[0-9a-f-]{36}$/i.test(value.principalId)||!value.workerId.trim()||!["studio","neon","mesh"].includes(value.planeKey))throw new TypeError("Invalid notification delivery sweep request");return value;}
