import {sql,type Kysely} from "kysely";
import type {JobExecutionResult,JobHandler,JobPublisher} from "@athyper/server-contract-jobs";
import type {PlaneKey} from "@athyper/server-foundation/context";
import {DELIVERY_SWEEP_JOB,type DeliverySweepRequest} from "./durable-delivery.js";
import {PLAN_NOTIFICATION_OUTBOX_JOB,type NotificationOutboxSweepRequest} from "./outbox-planning.js";
import {FLUSH_NOTIFICATION_DIGEST_JOB,type DigestFlushRequest,type DigestFrequency} from "./digest.js";

export const NOTIFICATION_MAINTENANCE_QUEUE="notifications.maintenance";
export const DISCOVER_NOTIFICATION_WORK_JOB="notifications.discover-work";
export const WEBHOOK_SWEEP_JOB="notifications.webhook-sweep";
export const WEBHOOK_DELIVERY_QUEUE="webhooks";
export const WEBHOOK_DELIVERY_JOB="webhook.deliver";
export interface NotificationDiscoveryRequest{readonly planeKey:PlaneKey;readonly principalId:string;readonly frequency?:DigestFrequency;}
export interface NotificationWorkCatalog{listTenants(planeKey:PlaneKey,kind:"message"|"digest"|"webhook",frequency?:DigestFrequency):Promise<readonly string[]>;listWebhookDeliveries(planeKey:PlaneKey,tenantId:string,limit:number):Promise<readonly {deliveryId:string;attempt:number}[]>;}
export function createKyselyNotificationWorkCatalog(databases:Partial<Record<PlaneKey,Kysely<Record<string,never>>>>):NotificationWorkCatalog{return {async listTenants(planeKey,kind,frequency){const db=required(databases[planeKey],planeKey);const result=await sql<{tenant_id:string}>`SELECT tenant_id FROM event.fn_notification_work_tenants(${kind},${frequency??null},1000)`.execute(db);return result.rows.map(row=>row.tenant_id);},async listWebhookDeliveries(planeKey,tenantId,limit){const db=required(databases[planeKey],planeKey);const result=await sql<{id:string;attempt_count:number}>`SELECT id,attempt_count FROM event.notification_delivery WHERE tenant_id=${tenantId}::uuid AND channel='webhook' AND (status IN ('pending','failed') OR (status='sending' AND locked_until<=now())) AND attempt_count<max_attempts AND (next_retry_at IS NULL OR next_retry_at<=now()) ORDER BY coalesce(next_retry_at,created_at),created_at LIMIT ${limit}`.execute(db);return result.rows.map(row=>({deliveryId:row.id,attempt:row.attempt_count+1}));}};}
export function createNotificationDiscoveryHandler(options:{readonly catalog:NotificationWorkCatalog;readonly jobs:JobPublisher}):JobHandler<typeof DISCOVER_NOTIFICATION_WORK_JOB,NotificationDiscoveryRequest>{return {async handle(job):Promise<JobExecutionResult>{const request=job.data;const kind=request.frequency?"digest":"message";const tenants=await options.catalog.listTenants(request.planeKey,kind,request.frequency);for(const tenantId of tenants){if(request.frequency){const payload:DigestFlushRequest={planeKey:request.planeKey,tenantId,principalId:request.principalId,frequency:request.frequency};await options.jobs.enqueue(NOTIFICATION_MAINTENANCE_QUEUE,FLUSH_NOTIFICATION_DIGEST_JOB,payload,{jobId:`notification-digest-${request.planeKey}-${tenantId}-${request.frequency}-${bucket(request.frequency)}`,maxAttempts:3,removeOnComplete:1000,removeOnFail:5000});continue;}const common={planeKey:request.planeKey,tenantId,principalId:request.principalId,workerId:`notification-${process.pid}`};await options.jobs.enqueue(NOTIFICATION_MAINTENANCE_QUEUE,PLAN_NOTIFICATION_OUTBOX_JOB,common satisfies NotificationOutboxSweepRequest,{jobId:`notification-plan-${request.planeKey}-${tenantId}-${minute()}`,maxAttempts:3,removeOnComplete:1000,removeOnFail:5000});await options.jobs.enqueue(NOTIFICATION_MAINTENANCE_QUEUE,DELIVERY_SWEEP_JOB,common satisfies DeliverySweepRequest,{jobId:`notification-delivery-${request.planeKey}-${tenantId}-${minute()}`,maxAttempts:3,removeOnComplete:1000,removeOnFail:5000});await options.jobs.enqueue(NOTIFICATION_MAINTENANCE_QUEUE,WEBHOOK_SWEEP_JOB,{planeKey:request.planeKey,tenantId,principalId:request.principalId},{jobId:`notification-webhooks-${request.planeKey}-${tenantId}-${minute()}`,maxAttempts:3,removeOnComplete:1000,removeOnFail:5000});}return {status:"completed",output:{tenants:tenants.length,kind}};}};}
export function createWebhookSweepHandler(options:{readonly catalog:NotificationWorkCatalog;readonly jobs:JobPublisher}):JobHandler<typeof WEBHOOK_SWEEP_JOB,{readonly planeKey:PlaneKey;readonly tenantId:string;readonly principalId:string}>{return {async handle(job):Promise<JobExecutionResult>{const request=job.data;const deliveries=await options.catalog.listWebhookDeliveries(request.planeKey,request.tenantId,100);for(const delivery of deliveries)await options.jobs.enqueue(WEBHOOK_DELIVERY_QUEUE,WEBHOOK_DELIVERY_JOB,{...request,deliveryId:delivery.deliveryId},{jobId:`webhook-${request.planeKey}-${delivery.deliveryId}-${delivery.attempt}`,maxAttempts:5,removeOnComplete:1000,removeOnFail:5000});return {status:"completed",output:{enqueued:deliveries.length}};}};}
function required<T>(value:T|undefined,planeKey:string):T{if(!value)throw new Error(`Notification database is not configured for ${planeKey}`);return value;}function minute(){return Math.floor(Date.now()/60_000);}function bucket(frequency:DigestFrequency){const size=frequency==="hourly_digest"?3_600_000:frequency==="daily_digest"?86_400_000:604_800_000;return Math.floor(Date.now()/size);}
