import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { InAppNotificationRepository, NotificationEventPublisher, NotificationEventSubscriber, PushSubscriptionRepository } from "@athyper/server-contract-notifications";
import type { Application, RequestHandler, Response } from "express";
import { openNotificationSseStream } from "./notification-event-bus.js";
import type { NotificationPreference, createNotificationPreferenceService } from "./notification-preferences.js";

export function registerNotificationRoutes(application:Application,options:{
  readonly authenticate:RequestHandler;
  readonly readContext:(response:Response)=>VerifiedRequestContext;
  readonly inbox:InAppNotificationRepository;
  readonly push:PushSubscriptionRepository;
  readonly events:NotificationEventPublisher&NotificationEventSubscriber;
  readonly preferences?:ReturnType<typeof createNotificationPreferenceService>;
}){
  if(options.preferences){
    application.get("/api/notifications/preferences",options.authenticate,async(_request,response,next)=>{try{const context=options.readContext(response);const snapshot=await options.preferences!.get(context);response.setHeader("ETag",`\"${snapshot.version}\"`);response.status(200).json(snapshot);}catch(error){next(error);}});
    application.patch("/api/notifications/preferences",options.authenticate,async(request,response,next)=>{try{const context=options.readContext(response);const expectedVersion=ifMatch(request.headers["if-match"]);const body=record(request.body);if(!Array.isArray(body["preferences"]))throw new TypeError("preferences must be an array");const preferences=body["preferences"].map(preferenceInput);const snapshot=await options.preferences!.patch(context,expectedVersion,preferences);response.setHeader("ETag",`\"${snapshot.version}\"`);response.status(200).json(snapshot);}catch(error){next(error);}});
  }
  application.get("/api/notifications/inbox",options.authenticate,async(request,response,next)=>{try{const context=options.readContext(response);const notifications=await options.inbox.list({tenantId:context.tenantId,principalId:context.principalId,planeKey:context.planeKey,limit:integer(request.query["limit"],50)});response.status(200).json({notifications});}catch(error){next(error);}});
  application.post("/api/notifications/:id/read",options.authenticate,async(request,response,next)=>{try{const context=options.readContext(response);const id=uuid(request.params["id"]);const occurredAt=new Date().toISOString();const updated=await options.inbox.markRead({tenantId:context.tenantId,principalId:context.principalId,planeKey:context.planeKey,notificationId:id,readAt:occurredAt});if(!updated){response.status(404).json({error:"NOTIFICATION_NOT_FOUND"});return;}await options.events.publish({type:"notification.read",tenantId:context.tenantId,principalId:context.principalId,notificationId:id,occurredAt});response.status(204).end();}catch(error){next(error);}});
  application.get("/api/notifications/stream",options.authenticate,(request,response)=>{const context=options.readContext(response);response.status(200);response.setHeader("Content-Type","text/event-stream");response.setHeader("Cache-Control","no-cache, no-transform");response.setHeader("Connection","keep-alive");response.flushHeaders();const controller=new AbortController();request.once("close",()=>controller.abort());openNotificationSseStream({subscriber:options.events,tenantId:context.tenantId,principalId:context.principalId,write:chunk=>response.write(chunk),signal:controller.signal});});
  application.post("/api/notifications/push-subscriptions",options.authenticate,async(request,response,next)=>{try{const context=options.readContext(response);const body=record(request.body);const subscription=await options.push.upsert({tenantId:context.tenantId,principalId:context.principalId,planeKey:context.planeKey,platform:platform(body["platform"]),deviceId:text(body["deviceId"]??body["device_id"],"deviceId"),endpoint:text(body["endpoint"],"endpoint"),...(optional(body["p256dhKey"]??body["p256dh_key"])?{p256dhKey:optional(body["p256dhKey"]??body["p256dh_key"])}:{}),...(optional(body["authKey"]??body["auth_key"])?{authKey:optional(body["authKey"]??body["auth_key"])}:{}),...(optional(body["deviceToken"]??body["device_token"])?{deviceToken:optional(body["deviceToken"]??body["device_token"])}:{}),...(request.headers["user-agent"]?{userAgent:request.headers["user-agent"]}:{})});response.status(201).json(subscription);}catch(error){next(error);}});
  application.delete("/api/notifications/push-subscriptions/:id",options.authenticate,async(request,response,next)=>{try{const context=options.readContext(response);await options.push.deactivate({tenantId:context.tenantId,principalId:context.principalId,planeKey:context.planeKey,subscriptionId:uuid(request.params["id"]),reason:"user_unsubscribed"});response.status(204).end();}catch(error){next(error);}});
}
function integer(value:unknown,fallback:number){if(value===undefined)return fallback;const parsed=Number(value);if(!Number.isInteger(parsed)||parsed<1||parsed>100)throw new TypeError("limit must be between 1 and 100");return parsed;}
function uuid(value:unknown){const normalized=String(value??"");if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(normalized))throw new TypeError("Invalid UUID");return normalized;}
function record(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError("JSON object body required");return value as Record<string,unknown>;}
function text(value:unknown,name:string){if(typeof value!=="string"||!value.trim())throw new TypeError(`${name} is required`);return value.trim();}
function optional(value:unknown){return typeof value==="string"&&value.trim()?value.trim():undefined;}
function platform(value:unknown){const result=text(value,"platform");if(!["web","android","ios"].includes(result))throw new TypeError("Invalid push platform");return result as "web"|"android"|"ios";}
function ifMatch(value:unknown){if(typeof value!=="string")throw new TypeError("If-Match header is required");const match=/^(?:W\/)?\"?(\d+)\"?$/.exec(value.trim());if(!match)throw new TypeError("If-Match must contain a numeric preference version");return Number(match[1]);}
function preferenceInput(value:unknown):Omit<NotificationPreference,"tenantId"|"principalId"|"version">{const body=record(value);const eventCode=text(body["eventCode"],"eventCode");if(!/^[a-z][a-z0-9_.-]+$/.test(eventCode))throw new TypeError("Invalid eventCode");if(!Array.isArray(body["channels"]))throw new TypeError("channels must be an array");const channels=body["channels"].map(channel);return{eventCode,channels};}
function channel(value:unknown){const result=text(value,"channel");if(!["in_app","email","sms","push","whatsapp"].includes(result))throw new TypeError("Invalid notification channel");return result as "in_app"|"email"|"sms"|"push"|"whatsapp";}
