// Generated by tooling/scripts/catalog/generate-platform-catalog.mjs. Do not edit.
import type { CatalogWorkspaceRoute } from "./index.js";

export const PLATFORM_CATALOG_ROUTES = Object.freeze({
  "studio": [
    {
      "code": "foundation",
      "routeSlug": "foundation",
      "name": "Platform Foundation",
      "modules": [
        {
          "code": "fnd",
          "routeSlug": "foundation",
          "name": "Foundation Runtime",
          "entities": []
        },
        {
          "code": "rel",
          "routeSlug": "reference-data",
          "name": "Reference & Shared Data",
          "entities": []
        }
      ]
    },
    {
      "code": "entity",
      "routeSlug": "entity",
      "name": "Entity Studio",
      "modules": [
        {
          "code": "meta",
          "routeSlug": "metadata",
          "name": "Metadata & Entity Studio",
          "entities": []
        },
        {
          "code": "pol",
          "routeSlug": "policies",
          "name": "Policy & Rules Engine",
          "entities": []
        },
        {
          "code": "wfl",
          "routeSlug": "workflows",
          "name": "Workflow Designer",
          "entities": []
        },
        {
          "code": "pub",
          "routeSlug": "publishing",
          "name": "Publication & Release Management",
          "entities": []
        },
        {
          "code": "doc",
          "routeSlug": "documents",
          "name": "Document Generation & Processing",
          "entities": []
        },
        {
          "code": "cms",
          "routeSlug": "content",
          "name": "Content & Object Storage",
          "entities": []
        },
        {
          "code": "exp",
          "routeSlug": "experiences",
          "name": "Experience & Navigation Design",
          "entities": []
        }
      ]
    },
    {
      "code": "trustiam",
      "routeSlug": "trust-iam",
      "name": "TrustIAM Studio",
      "modules": [
        {
          "code": "iam",
          "routeSlug": "identity-access",
          "name": "Identity & Access Management",
          "entities": []
        },
        {
          "code": "onb",
          "routeSlug": "onboarding",
          "name": "Trust & Onboarding",
          "entities": []
        },
        {
          "code": "aud",
          "routeSlug": "governance-audit",
          "name": "Identity Governance & Audit",
          "entities": []
        }
      ]
    },
    {
      "code": "plans",
      "routeSlug": "plans",
      "name": "Plans & Entitlements Studio",
      "modules": [
        {
          "code": "pcat",
          "routeSlug": "platform-catalog",
          "name": "Platform Catalog Management",
          "entities": []
        },
        {
          "code": "sub",
          "routeSlug": "subscriptions",
          "name": "Subscription Management",
          "entities": []
        },
        {
          "code": "ent",
          "routeSlug": "entitlements",
          "name": "Plan & Module Entitlements",
          "entities": []
        },
        {
          "code": "usg",
          "routeSlug": "usage",
          "name": "Usage & Quota",
          "entities": []
        }
      ]
    },
    {
      "code": "observability",
      "routeSlug": "observability",
      "name": "Observability Studio",
      "modules": [
        {
          "code": "obs",
          "routeSlug": "platform-observability",
          "name": "Platform Observability",
          "entities": []
        },
        {
          "code": "err",
          "routeSlug": "errors",
          "name": "Error Tracking",
          "entities": []
        },
        {
          "code": "sre",
          "routeSlug": "reliability",
          "name": "Service Reliability",
          "entities": []
        }
      ]
    },
    {
      "code": "communications",
      "routeSlug": "communications",
      "name": "Communications Studio",
      "modules": [
        {
          "code": "ntf",
          "routeSlug": "notifications",
          "name": "Notifications & Messaging",
          "entities": []
        },
        {
          "code": "act",
          "routeSlug": "activity",
          "name": "Activity & Commentary",
          "entities": []
        }
      ]
    },
    {
      "code": "integration",
      "routeSlug": "integration",
      "name": "Integration & Automation Studio",
      "modules": [
        {
          "code": "int",
          "routeSlug": "integration-hub",
          "name": "Integration Hub",
          "entities": []
        },
        {
          "code": "job",
          "routeSlug": "automation",
          "name": "Automation & Jobs",
          "entities": []
        }
      ]
    },
    {
      "code": "atlas_ai",
      "routeSlug": "atlas-ai",
      "name": "Atlas AI Studio",
      "modules": [
        {
          "code": "aip",
          "routeSlug": "providers",
          "name": "AI Provider & Model Management",
          "entities": []
        },
        {
          "code": "agt",
          "routeSlug": "agents",
          "name": "Agents & Governed Tools",
          "entities": []
        },
        {
          "code": "knw",
          "routeSlug": "knowledge",
          "name": "Knowledge & Retrieval",
          "entities": []
        },
        {
          "code": "aig",
          "routeSlug": "governance",
          "name": "AI Governance & Safety",
          "entities": []
        }
      ]
    },
    {
      "code": "extension",
      "routeSlug": "extensions",
      "name": "Extension Studio",
      "modules": [
        {
          "code": "ext",
          "routeSlug": "plugins",
          "name": "Plugins & Extensions",
          "entities": []
        },
        {
          "code": "dev",
          "routeSlug": "developer-tools",
          "name": "Developer Tools & SDK",
          "entities": []
        }
      ]
    },
    {
      "code": "platform_ops",
      "routeSlug": "platform-operations",
      "name": "Platform Operations Studio",
      "modules": [
        {
          "code": "ops",
          "routeSlug": "operations",
          "name": "Platform Operations",
          "entities": []
        },
        {
          "code": "sec",
          "routeSlug": "security",
          "name": "Secrets & Security",
          "entities": []
        },
        {
          "code": "sea",
          "routeSlug": "search",
          "name": "Search",
          "entities": []
        },
        {
          "code": "ana",
          "routeSlug": "analytics",
          "name": "Platform Analytics",
          "entities": []
        }
      ]
    }
  ],
  "neon": [
    {
      "code": "core",
      "routeSlug": "core",
      "name": "Core Platform",
      "iconKey": "settings",
      "modules": [
        {
          "code": "fnd",
          "routeSlug": "foundation",
          "name": "Foundation Runtime",
          "iconKey": "settings",
          "entities": []
        },
        {
          "code": "meta",
          "routeSlug": "metadata",
          "name": "Metadata Runtime",
          "iconKey": "database",
          "entities": []
        },
        {
          "code": "iam",
          "routeSlug": "identity-access",
          "name": "Identity & Access Management",
          "iconKey": "shield-check",
          "entities": []
        },
        {
          "code": "aud",
          "routeSlug": "audit",
          "name": "Audit & Governance",
          "iconKey": "clipboard-check",
          "entities": []
        },
        {
          "code": "pol",
          "routeSlug": "policies",
          "name": "Policy & Rules Engine",
          "iconKey": "shield-check",
          "entities": []
        },
        {
          "code": "wfl",
          "routeSlug": "workflows",
          "name": "Workflow Engine",
          "iconKey": "route",
          "entities": []
        },
        {
          "code": "job",
          "routeSlug": "automation",
          "name": "Automation & Jobs",
          "iconKey": "settings",
          "entities": []
        },
        {
          "code": "doc",
          "routeSlug": "documents",
          "name": "Document Services",
          "iconKey": "file-signature",
          "entities": []
        },
        {
          "code": "ntf",
          "routeSlug": "notification-services",
          "name": "Notification Services",
          "iconKey": "bell",
          "entities": []
        },
        {
          "code": "int",
          "routeSlug": "integration",
          "name": "Integration Hub",
          "iconKey": "organization",
          "entities": []
        },
        {
          "code": "cms",
          "routeSlug": "content",
          "name": "Content Services",
          "iconKey": "database",
          "entities": []
        },
        {
          "code": "act",
          "routeSlug": "activity",
          "name": "Activity & Commentary",
          "iconKey": "message",
          "entities": []
        },
        {
          "code": "rel",
          "routeSlug": "reference-data",
          "name": "Reference & Shared Data",
          "iconKey": "database-check",
          "entities": []
        }
      ]
    },
    {
      "code": "mdg",
      "routeSlug": "mdg",
      "name": "Master Data Governance",
      "iconKey": "database-check",
      "modules": [
        {
          "code": "bp",
          "routeSlug": "business-partner",
          "name": "Business Partner Management",
          "iconKey": "contact",
          "entities": []
        },
        {
          "code": "item",
          "routeSlug": "product-item",
          "name": "Product & Item Governance",
          "iconKey": "package",
          "entities": []
        },
        {
          "code": "finmd",
          "routeSlug": "financial-master",
          "name": "Financial Master Data",
          "iconKey": "database-currency",
          "entities": []
        },
        {
          "code": "org",
          "routeSlug": "organization-reference",
          "name": "Organization & Reference Data",
          "iconKey": "organization",
          "entities": []
        },
        {
          "code": "loc",
          "routeSlug": "location-address",
          "name": "Location & Address Governance",
          "iconKey": "map-pin",
          "entities": []
        },
        {
          "code": "dqs",
          "routeSlug": "data-quality",
          "name": "Data Quality & Stewardship",
          "iconKey": "database-check",
          "entities": []
        }
      ]
    },
    {
      "code": "fin",
      "routeSlug": "finance",
      "name": "Finance",
      "iconKey": "landmark",
      "modules": [
        {
          "code": "acc",
          "routeSlug": "financial-accounting",
          "name": "Financial Accounting",
          "iconKey": "book-open",
          "entities": []
        },
        {
          "code": "ap",
          "routeSlug": "accounts-payable",
          "name": "Accounts Payable",
          "iconKey": "receipt-out",
          "entities": []
        },
        {
          "code": "ar",
          "routeSlug": "accounts-receivable",
          "name": "Accounts Receivable",
          "iconKey": "receipt-in",
          "entities": []
        },
        {
          "code": "treasury",
          "routeSlug": "cash-treasury",
          "name": "Cash & Treasury Management",
          "iconKey": "coins",
          "entities": []
        },
        {
          "code": "budget",
          "routeSlug": "budget-control",
          "name": "Budget Management & Control",
          "iconKey": "wallet",
          "entities": []
        },
        {
          "code": "tax",
          "routeSlug": "tax",
          "name": "Tax Management",
          "iconKey": "percent-receipt",
          "entities": []
        },
        {
          "code": "faa",
          "routeSlug": "fixed-assets",
          "name": "Fixed Asset Accounting",
          "iconKey": "building-calculator",
          "entities": []
        }
      ]
    },
    {
      "code": "scm",
      "routeSlug": "supply-chain",
      "name": "Supply Chain",
      "iconKey": "route",
      "modules": [
        {
          "code": "srm",
          "routeSlug": "supplier-management",
          "name": "Supplier Management",
          "iconKey": "factory-handshake",
          "entities": []
        },
        {
          "code": "source",
          "routeSlug": "strategic-sourcing",
          "name": "Strategic Sourcing",
          "iconKey": "target",
          "entities": []
        },
        {
          "code": "contract",
          "routeSlug": "contracts",
          "name": "Contract Management",
          "iconKey": "file-signature",
          "entities": []
        },
        {
          "code": "buy",
          "routeSlug": "procurement",
          "name": "Procurement",
          "iconKey": "shopping-cart",
          "entities": []
        },
        {
          "code": "demand",
          "routeSlug": "planning",
          "name": "Demand & Supply Planning",
          "iconKey": "chart",
          "entities": []
        },
        {
          "code": "inventory",
          "routeSlug": "inventory",
          "name": "Inventory Management",
          "iconKey": "boxes",
          "entities": []
        },
        {
          "code": "wms",
          "routeSlug": "warehouse",
          "name": "Warehouse Management",
          "iconKey": "warehouse",
          "entities": []
        },
        {
          "code": "qms",
          "routeSlug": "quality",
          "name": "Quality Management",
          "iconKey": "clipboard-check",
          "entities": []
        },
        {
          "code": "logistics",
          "routeSlug": "transport-logistics",
          "name": "Transportation & Logistics",
          "iconKey": "truck",
          "entities": []
        }
      ]
    },
    {
      "code": "com",
      "routeSlug": "commercial",
      "name": "Commercial",
      "iconKey": "handshake",
      "modules": [
        {
          "code": "crm",
          "routeSlug": "crm",
          "name": "Customer Relationship Management",
          "iconKey": "contact",
          "entities": []
        },
        {
          "code": "sale",
          "routeSlug": "sales-orders",
          "name": "Sales & Order Management",
          "iconKey": "receipt-out",
          "entities": []
        },
        {
          "code": "pcm",
          "routeSlug": "pricing",
          "name": "Pricing & Commercial Management",
          "iconKey": "tag",
          "entities": []
        }
      ]
    },
    {
      "code": "ppl",
      "routeSlug": "people",
      "name": "People",
      "iconKey": "users",
      "modules": [
        {
          "code": "hr",
          "routeSlug": "core-hr",
          "name": "Core Human Resources",
          "iconKey": "id-card",
          "entities": []
        },
        {
          "code": "tna",
          "routeSlug": "time-attendance",
          "name": "Time & Attendance",
          "iconKey": "user-clock",
          "entities": []
        },
        {
          "code": "tal",
          "routeSlug": "talent",
          "name": "Talent Management",
          "iconKey": "user-star",
          "entities": []
        },
        {
          "code": "payroll",
          "routeSlug": "payroll",
          "name": "Payroll",
          "iconKey": "banknote",
          "entities": []
        },
        {
          "code": "workforce",
          "routeSlug": "external-workforce",
          "name": "External Workforce",
          "iconKey": "user-briefcase",
          "entities": []
        }
      ]
    },
    {
      "code": "prs",
      "routeSlug": "projects-services",
      "name": "Projects & Services",
      "iconKey": "briefcase",
      "modules": [
        {
          "code": "prjcost",
          "routeSlug": "projects",
          "name": "Project Management",
          "iconKey": "gantt",
          "entities": []
        },
        {
          "code": "psa",
          "routeSlug": "professional-services",
          "name": "Professional Services",
          "iconKey": "briefcase",
          "entities": []
        },
        {
          "code": "itsm",
          "routeSlug": "service-management",
          "name": "Service Management",
          "iconKey": "headset",
          "entities": []
        }
      ]
    },
    {
      "code": "ops",
      "routeSlug": "operations-management",
      "name": "Operations",
      "iconKey": "factory",
      "modules": [
        {
          "code": "mfg",
          "routeSlug": "manufacturing",
          "name": "Manufacturing",
          "iconKey": "factory",
          "entities": []
        },
        {
          "code": "maint",
          "routeSlug": "maintenance",
          "name": "Maintenance Management",
          "iconKey": "wrench",
          "entities": []
        }
      ]
    },
    {
      "code": "ast",
      "routeSlug": "assets-facilities",
      "name": "Assets & Facilities",
      "iconKey": "building",
      "modules": [
        {
          "code": "asset",
          "routeSlug": "enterprise-assets",
          "name": "Enterprise Asset Management",
          "iconKey": "asset",
          "entities": []
        },
        {
          "code": "assetrems",
          "routeSlug": "real-estate",
          "name": "Real Estate Management",
          "iconKey": "building-key",
          "entities": []
        },
        {
          "code": "assetfm",
          "routeSlug": "facilities",
          "name": "Facilities Management",
          "iconKey": "building-wrench",
          "entities": []
        }
      ]
    }
  ],
  "mesh": [
    {
      "code": "core",
      "routeSlug": "core",
      "name": "Core Platform",
      "modules": [
        {
          "code": "fnd",
          "routeSlug": "foundation",
          "name": "Foundation Runtime",
          "entities": []
        },
        {
          "code": "iam",
          "routeSlug": "identity-access",
          "name": "Identity & Access Management",
          "entities": []
        },
        {
          "code": "aud",
          "routeSlug": "audit",
          "name": "Audit & Governance",
          "entities": []
        },
        {
          "code": "pol",
          "routeSlug": "policies",
          "name": "Policy & Rules Engine",
          "entities": []
        },
        {
          "code": "wfl",
          "routeSlug": "workflows",
          "name": "Workflow Engine",
          "entities": []
        },
        {
          "code": "job",
          "routeSlug": "automation",
          "name": "Automation & Jobs",
          "entities": []
        },
        {
          "code": "doc",
          "routeSlug": "documents",
          "name": "Document Services",
          "entities": []
        },
        {
          "code": "ntf",
          "routeSlug": "notifications",
          "name": "Notification Services",
          "entities": []
        },
        {
          "code": "int",
          "routeSlug": "integration",
          "name": "Integration Hub",
          "entities": []
        },
        {
          "code": "cms",
          "routeSlug": "content",
          "name": "Content Services",
          "entities": []
        },
        {
          "code": "act",
          "routeSlug": "activity",
          "name": "Activity & Commentary",
          "entities": []
        },
        {
          "code": "rel",
          "routeSlug": "reference-data",
          "name": "Reference & Shared Data",
          "entities": []
        }
      ]
    },
    {
      "code": "network_rel",
      "routeSlug": "network-relationships",
      "name": "Network & Relationships",
      "modules": [
        {
          "code": "npm",
          "routeSlug": "partner-network",
          "name": "Network & Partner Management",
          "entities": []
        },
        {
          "code": "mkd",
          "routeSlug": "marketplace",
          "name": "Marketplace & Discovery",
          "entities": []
        },
        {
          "code": "rlc",
          "routeSlug": "relationships",
          "name": "Relationship Collaboration",
          "entities": []
        },
        {
          "code": "nin",
          "routeSlug": "intelligence",
          "name": "Network Intelligence",
          "entities": []
        }
      ]
    },
    {
      "code": "commercial_collab",
      "routeSlug": "commercial-collaboration",
      "name": "Commercial Collaboration",
      "modules": [
        {
          "code": "mso",
          "routeSlug": "sourcing",
          "name": "Sourcing",
          "entities": []
        },
        {
          "code": "mct",
          "routeSlug": "contract",
          "name": "Contract",
          "entities": []
        },
        {
          "code": "btx",
          "routeSlug": "transaction",
          "name": "Business Transaction",
          "entities": []
        }
      ]
    },
    {
      "code": "supply_services",
      "routeSlug": "supply-services",
      "name": "Supply & Services Collaboration",
      "modules": [
        {
          "code": "scc",
          "routeSlug": "supply-chain",
          "name": "Supply Chain",
          "entities": []
        },
        {
          "code": "wsc",
          "routeSlug": "workforce-services",
          "name": "Workforce & Services",
          "entities": []
        }
      ]
    },
    {
      "code": "financial_collab",
      "routeSlug": "financial-collaboration",
      "name": "Financial Collaboration",
      "modules": [
        {
          "code": "pwc",
          "routeSlug": "payments-working-capital",
          "name": "Payments & Working Capital",
          "entities": []
        },
        {
          "code": "trf",
          "routeSlug": "trade-finance",
          "name": "Trade Finance",
          "entities": []
        },
        {
          "code": "fpg",
          "routeSlug": "financing-programs",
          "name": "Financing Programs",
          "entities": []
        },
        {
          "code": "fpn",
          "routeSlug": "partner-network",
          "name": "Financial Partner Network",
          "entities": []
        }
      ]
    }
  ]
} as const satisfies Readonly<Record<"studio" | "neon" | "mesh", readonly CatalogWorkspaceRoute[]>>);
