#!/usr/bin/env tsx
/** Generates the Starlight colour bridge for both docs sites from the active theme
 * tokens, so the docs follow the product palette instead of a hand-kept copy. */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ATLAS_MODERN_BRAND } from "@athyper/platform-brand";
import { COLOR_TOKENS, DOCS_DARK_ACCENT } from "../src/tokens";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(packageRoot, "../../../..");
const outputs = ["apps/docs-external", "apps/docs-internal"].map((site) =>
  path.join(repoRoot, site, "src/styles/atlas-theme.css"),
);
const check = process.argv.includes("--check");

const brand = ATLAS_MODERN_BRAND.colors.primary.toLowerCase();
const light = COLOR_TOKENS.light, dark = COLOR_TOKENS.dark;
const between = (a: string, b: string) => `color-mix(in srgb, ${a} 50%, ${b})`;

const css = `/*
 * Generated by @athyper/platform-theme/scripts/build-docs-css.ts from the theme
 * tokens (COLOR_TOKENS) and the Atlas Modern brand. DO NOT EDIT DIRECTLY — run:
 * pnpm --filter @athyper/platform-theme docs-theme:build
 *
 * Restyles Starlight's palette with the Atlas Modern tokens. No layout or
 * component changes, only the custom properties Starlight itself reads.
 */
@layer starlight.base {
  :root {
    /* Atlas Modern, dark (Starlight's unattributed root is its dark set). */
    --sl-color-accent-low: color-mix(in srgb, ${brand} 24%, black);
    --sl-color-accent: ${DOCS_DARK_ACCENT.accent};
    --sl-color-accent-high: ${DOCS_DARK_ACCENT.accentHigh};

    --sl-color-white: ${dark.foreground};
    --sl-color-gray-1: ${between(dark.foreground, dark.mutedForeground)};
    --sl-color-gray-2: ${dark.mutedForeground};
    --sl-color-gray-3: ${between(dark.mutedForeground, dark.input)};
    --sl-color-gray-4: ${dark.input};
    --sl-color-gray-5: ${dark.border};
    --sl-color-gray-6: ${dark.surfaceRaised};
    --sl-color-black: ${dark.background};

    --sl-color-text: var(--sl-color-gray-2);
    --sl-color-text-accent: var(--sl-color-accent-high);
    --sl-color-bg: var(--sl-color-black);
    --sl-color-bg-nav: ${dark.surface};
    --sl-color-bg-sidebar: ${dark.surface};
    --sl-color-bg-inline-code: ${dark.muted};
    --sl-color-bg-accent: var(--sl-color-accent-high);
    --sl-color-hairline-light: var(--sl-color-gray-5);
    --sl-color-hairline: var(--sl-color-gray-6);
    --sl-color-hairline-shade: var(--sl-color-black);

    --sl-font: 'Geist', 'Inter', var(--sl-font-system);
  }

  :root[data-theme='light'] {
    /* Atlas Modern, light */
    --sl-color-accent-low: color-mix(in srgb, ${brand} 8%, white);
    --sl-color-accent: ${brand};
    --sl-color-accent-high: color-mix(in srgb, ${brand} 82%, black);

    --sl-color-white: ${light.foreground};
    --sl-color-gray-1: ${between(light.foreground, light.mutedForeground)};
    --sl-color-gray-2: ${light.mutedForeground};
    --sl-color-gray-3: ${between(light.mutedForeground, light.input)};
    --sl-color-gray-4: ${light.input};
    --sl-color-gray-5: ${light.border};
    --sl-color-gray-6: ${light.muted};
    --sl-color-gray-7: ${light.background};
    --sl-color-black: ${light.surface};

    --sl-color-text-accent: var(--sl-color-accent);
    --sl-color-bg: ${light.background};
    --sl-color-bg-nav: ${light.background};
    --sl-color-bg-inline-code: var(--sl-color-gray-6);
    --sl-color-bg-accent: var(--sl-color-accent);
    --sl-color-hairline-light: var(--sl-color-gray-6);
    --sl-color-hairline-shade: var(--sl-color-gray-6);
  }
}

/*
 * Persistent dark sidebar matching the product shell's rail (story-start to
 * story-end from the brand colour). Dark mode mixes further toward black so it
 * reads as part of one dark theme; light mode keeps the product rail's gradient.
 * Outside any @layer so it wins over Starlight's own sidebar rules.
 */
.sidebar-pane {
  background: linear-gradient(
    165deg,
    color-mix(in srgb, ${brand} 14%, black),
    color-mix(in srgb, ${brand} 38%, black)
  );
  border-inline-end: none;

  /* Re-scope the tokens Starlight's sidebar markup reads so link text stays
     legible on the fixed dark background whatever the page theme. */
  --sl-color-gray-2: color-mix(in srgb, white 78%, transparent);
  --sl-color-white: white;
  --sl-color-hairline-light: color-mix(in srgb, white 14%, transparent);
}

:root[data-theme='light'] .sidebar-pane {
  background: linear-gradient(
    165deg,
    color-mix(in srgb, ${brand} 24%, black),
    color-mix(in srgb, ${brand} 64%, black)
  );
}

.sidebar-pane a[aria-current='page'] {
  background: color-mix(in srgb, white 16%, transparent);
  color: white;
  box-shadow: inset 3px 0 0 color-mix(in srgb, ${brand} 38%, white);
}

.sidebar-pane .large {
  color: white;
}
`;

let stale = false;
for (const output of outputs) {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current === css) continue;
  if (check) {
    stale = true;
    console.error(`${path.relative(repoRoot, output)} is out of date; run the docs theme build.`);
  } else await writeFile(output, css);
}
if (stale) process.exit(1);
