INSERT INTO master.audit_event_contract (
    code,event_code_pattern,priority,allowed_operations,default_severity,
    allowed_actor_types,allowed_scope,reason_required,capture_mode,
    max_payload_bytes,schema_version,metadata,status
)
VALUES
    (
        'document_row_change',
        '^document\.[a-z][a-z0-9_]*\.row_(created|updated|deleted)$',
        10,ARRAY['create','update','delete']::audit.operation_d[],'info',
        ARRAY['user','service_account','bot','integration','support','system']::audit.actor_type_d[],
        'tenant',false,'changed_fields',16384,1,
        '{"owner":"database","purpose":"baseline_row_evidence"}'::jsonb,'active'
    ),
    (
        'document_business_event',
        '^document\.[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$',
        20,ARRAY['create','update','delete','restore','execute','approve','reject','import','export']::audit.operation_d[],'info',
        ARRAY['user','service_account','bot','integration','support','system']::audit.actor_type_d[],
        'tenant',false,'safe_values',65536,1,
        '{"owner":"application","purpose":"semantic_business_evidence"}'::jsonb,'active'
    ),
    (
        'attachment_access_event',
        '^document\.attachment\.(accessed|previewed|downloaded)$',
        15,ARRAY['execute','export']::audit.operation_d[],'info',
        ARRAY['user','service_account','bot','integration','support','system']::audit.actor_type_d[],
        'tenant',false,'metadata',16384,1,
        '{"owner":"application","purpose":"attachment_access_evidence","sensitive":true}'::jsonb,'active'
    ),
    (
        'workflow_business_event',
        '^workflow\.[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$',
        25,ARRAY['create','update','execute','approve','reject']::audit.operation_d[],'info',
        ARRAY['user','service_account','bot','integration','support','system']::audit.actor_type_d[],
        'tenant',false,'safe_values',65536,1,
        '{"owner":"workflow","purpose":"workflow_transition_evidence"}'::jsonb,'active'
    ),
    (
        'accounting_business_event',
        '^accounting\.[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$',
        27,ARRAY['create','update','execute','approve','reject','import','export']::audit.operation_d[],'warning',
        ARRAY['user','service_account','bot','integration','support','system']::audit.actor_type_d[],
        'tenant',false,'safe_values',65536,1,
        '{"owner":"finance","purpose":"accounting_business_evidence"}'::jsonb,'active'
    ),
    (
        'ai_byok_event',
        '^ai\.byok\.[a-z][a-z0-9_]*$',
        30,ARRAY['create','update','delete','execute']::audit.operation_d[],'warning',
        ARRAY['user','service_account','support','system']::audit.actor_type_d[],
        'tenant',false,'metadata',16384,1,
        '{"sensitive":true}'::jsonb,'active'
    ),
    (
        'metadata_entity_authoring_event',
        '^metadata\.entity(\.[a-z][a-z0-9_]*){1,3}$',
        35,ARRAY['create','update','execute','approve','reject']::audit.operation_d[],'info',
        ARRAY['user','service_account','bot','support','system']::audit.actor_type_d[],
        'either',false,'safe_values',65536,1,
        '{"owner":"meta-entity-authoring","purpose":"entity_contract_authoring_evidence"}'::jsonb,'active'
    ),
    (
        'ai_support_event',
        '^ai\.support\.[a-z][a-z0-9_]*$',
        40,ARRAY['execute','export']::audit.operation_d[],'warning',
        ARRAY['support']::audit.actor_type_d[],
        'tenant',true,'metadata',16384,1,
        '{"sensitive":true}'::jsonb,'active'
    ),
    (
        'platform_system_event',
        '^(system|platform)\.[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$',
        50,ARRAY['create','update','delete','restore','execute','import','export']::audit.operation_d[],'info',
        ARRAY['service_account','bot','system']::audit.actor_type_d[],
        'either',false,'metadata',32768,1,
        '{"owner":"platform"}'::jsonb,'active'
    )
ON CONFLICT(code) DO UPDATE SET
    event_code_pattern=EXCLUDED.event_code_pattern,
    priority=EXCLUDED.priority,
    allowed_operations=EXCLUDED.allowed_operations,
    default_severity=EXCLUDED.default_severity,
    allowed_actor_types=EXCLUDED.allowed_actor_types,
    allowed_scope=EXCLUDED.allowed_scope,
    reason_required=EXCLUDED.reason_required,
    capture_mode=EXCLUDED.capture_mode,
    max_payload_bytes=EXCLUDED.max_payload_bytes,
    schema_version=EXCLUDED.schema_version,
    metadata=EXCLUDED.metadata,
    status=EXCLUDED.status;

SELECT audit.ensure_monthly_partitions(date_trunc('month',CURRENT_DATE)::date,4);
