import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { RecordMutationResult, RecordMutationService, RecordQueryService } from "@athyper/server-contract-records";
import { HttpError, defineRouteContract, registerContractRoute } from "@athyper/server-runtime-http";
import type { Application, Request, RequestHandler, Response } from "express";
import { RecordServiceError } from "./errors.js";

export interface RecordsRouteOptions {
  readonly authenticate: RequestHandler;
  readonly readContext: (response: Response) => VerifiedRequestContext;
  readonly queries: RecordQueryService;
  readonly mutations: RecordMutationService;
}

export function registerRecordsRoutes(application: Application, options: RecordsRouteOptions): void {
  registerContractRoute(application, contracts.list, options.authenticate, async (request, response, next) => { try { const limit = integerQuery(request.query["limit"]); const search = stringQuery(request.query["search"]); response.json(await options.queries.list({ context: options.readContext(response), entityCode: param(request.params["entityCode"], "entityCode"), ...(limit !== undefined ? { limit } : {}), ...(search ? { search } : {}) })); } catch (error) { sendError(error, next); } });
  registerContractRoute(application, contracts.get, options.authenticate, async (request, response, next) => { try { const result = await options.queries.get({ context: options.readContext(response), entityCode: param(request.params["entityCode"], "entityCode"), recordId: param(request.params["recordId"], "recordId") }); response.status(result.data ? 200 : 404).json(result); } catch (error) { sendError(error, next); } });
  registerContractRoute(application, contracts.create, options.authenticate, async (request, response, next) => { try { sendMutation(await options.mutations.create({ context: options.readContext(response), entityCode: param(request.params["entityCode"], "entityCode"), input: body(request.body), origin: "classic", validationMode: "strict", idempotencyKey: header(request.headers["idempotency-key"]) }), request, response, next); } catch (error) { sendError(error, next); } });
  registerContractRoute(application, contracts.patch, options.authenticate, async (request, response, next) => { try { sendMutation(await options.mutations.patch({ context: options.readContext(response), entityCode: param(request.params["entityCode"], "entityCode"), recordId: param(request.params["recordId"], "recordId"), input: body(request.body), origin: "classic", validationMode: "strict", expectedVersion: integerHeader(request.headers["if-match"]), idempotencyKey: header(request.headers["idempotency-key"]) }), request, response, next); } catch (error) { sendError(error, next); } });
  registerContractRoute(application, contracts.delete, options.authenticate, async (request, response, next) => { try { sendMutation(await options.mutations.delete({ context: options.readContext(response), entityCode: param(request.params["entityCode"], "entityCode"), recordId: param(request.params["recordId"], "recordId"), origin: "classic", validationMode: "strict", expectedVersion: integerHeader(request.headers["if-match"]), idempotencyKey: header(request.headers["idempotency-key"]) }), request, response, next); } catch (error) { sendError(error, next); } });
  registerContractRoute(application, contracts.transition, options.authenticate, async (request, response, next) => { try { sendMutation(await options.mutations.transition({ context: options.readContext(response), entityCode: param(request.params["entityCode"], "entityCode"), recordId: param(request.params["recordId"], "recordId"), transitionCode: param(request.params["transitionCode"], "transitionCode"), input: body(request.body), origin: "classic", validationMode: "strict", expectedVersion: integerHeader(request.headers["if-match"]), idempotencyKey: header(request.headers["idempotency-key"]) }), request, response, next); } catch (error) { sendError(error, next); } });
}

function sendMutation(result: RecordMutationResult, request: Request, response: Response, next: (error: unknown) => void): void {
  if (result.kind === "Committed") { response.status(result.action === "create" && !result.replayed ? 201 : 200).json(result); return; }
  const status: Record<string, number> = { NotFound: 404, CapabilityUnavailable: 409, IncompatibleAction: 409, Forbidden: 403, VersionRequired: 428, VersionConflict: 409, FieldsNotWritable: 422, ValidationFailed: 422, LockRequired: 423, InvalidTransition: 409 };
  const idempotencyStatus = result.kind === "IdempotencyConflict" ? (result.reason === "required" ? 428 : result.reason === "invalid" ? 400 : 409) : undefined;
  next(new HttpError(idempotencyStatus ?? status[result.kind] ?? 500, `RECORD_${result.kind.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase()}`, mutationDetail(result), { result, method: request.method }));
}
function mutationDetail(result: Exclude<RecordMutationResult, { kind: "Committed" }>): string { if (result.kind === "IdempotencyConflict") return `Idempotency key is ${result.reason.replace("_", " ")}`; if (result.kind === "Forbidden") return "The verified principal is not allowed to perform this mutation"; if (result.kind === "NotFound") return "The requested record was not found"; return `Record mutation failed: ${result.kind}`; }
function sendError(error: unknown, next: (error: unknown) => void): void { next(error instanceof RecordServiceError ? new HttpError(error.statusCode, error.code, error.message) : error); }
function body(value: unknown): Readonly<Record<string, unknown>> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new RecordServiceError(400, "INVALID_BODY", "JSON object required"); return value as Readonly<Record<string, unknown>>; }
function header(value: string | string[] | undefined): string | undefined { const first = Array.isArray(value) ? value[0] : value; return first?.trim() || undefined; }
function integerHeader(value: string | string[] | undefined): number | undefined { const raw = header(value)?.replace(/^"|"$/g, ""); if (!raw) return undefined; const parsed = Number(raw); if (!Number.isInteger(parsed) || parsed < 0) throw new RecordServiceError(400, "INVALID_VERSION", "If-Match must contain a non-negative integer"); return parsed; }
function stringQuery(value: unknown): string | undefined { return typeof value === "string" && value.trim() ? value.trim() : undefined; }
function integerQuery(value: unknown): number | undefined { if (value === undefined) return undefined; const parsed = Number(value); if (!Number.isInteger(parsed)) throw new RecordServiceError(400, "INVALID_LIMIT", "limit must be an integer"); return parsed; }
function param(value: string | string[] | undefined, name: string): string { const result = Array.isArray(value) ? value[0] : value; if (!result) throw new RecordServiceError(400, "INVALID_ROUTE_PARAMETER", `${name} is required`); return result; }

const objectSchema = { type: "object", additionalProperties: true } as const;
const problemResponses = { 400: { description: "Invalid request" }, 401: { description: "Authentication required" }, 403: { description: "Forbidden" }, 409: { description: "Conflict" }, 422: { description: "Validation failed" }, 428: { description: "Precondition required" } } as const;
const contracts = {
  list: defineRouteContract({ method: "get", path: "/api/records/:entityCode", operationId: "records.list", summary: "List records", tags: ["Records"], authenticated: true, responses: { 200: { description: "Record page", body: objectSchema }, 401: problemResponses[401], 403: problemResponses[403] } }),
  get: defineRouteContract({ method: "get", path: "/api/records/:entityCode/:recordId", operationId: "records.get", summary: "Get a record", tags: ["Records"], authenticated: true, responses: { 200: { description: "Record", body: objectSchema }, 404: { description: "Not found" } } }),
  create: defineRouteContract({ method: "post", path: "/api/records/:entityCode", operationId: "records.create", summary: "Create a record", tags: ["Records"], authenticated: true, request: { headers: { type: "object", properties: { "Idempotency-Key": { type: "string", minLength: 16, maxLength: 128 } }, required: ["Idempotency-Key"] }, body: objectSchema }, responses: { 201: { description: "Created", body: objectSchema }, ...problemResponses } }),
  patch: defineRouteContract({ method: "patch", path: "/api/records/:entityCode/:recordId", operationId: "records.patch", summary: "Patch a record", tags: ["Records"], authenticated: true, request: { headers: { type: "object", properties: { "Idempotency-Key": { type: "string", minLength: 16, maxLength: 128 }, "If-Match": { type: "integer", minimum: 0 } }, required: ["Idempotency-Key"] }, body: objectSchema }, responses: { 200: { description: "Patched", body: objectSchema }, ...problemResponses } }),
  delete: defineRouteContract({ method: "delete", path: "/api/records/:entityCode/:recordId", operationId: "records.delete", summary: "Delete a record", tags: ["Records"], authenticated: true, request: { headers: { type: "object", properties: { "Idempotency-Key": { type: "string", minLength: 16, maxLength: 128 }, "If-Match": { type: "integer", minimum: 0 } }, required: ["Idempotency-Key"] } }, responses: { 200: { description: "Deleted", body: objectSchema }, ...problemResponses } }),
  transition: defineRouteContract({ method: "post", path: "/api/records/:entityCode/:recordId/transitions/:transitionCode", operationId: "records.transition", summary: "Transition a record", tags: ["Records"], authenticated: true, request: { headers: { type: "object", properties: { "Idempotency-Key": { type: "string", minLength: 16, maxLength: 128 }, "If-Match": { type: "integer", minimum: 0 } }, required: ["Idempotency-Key"] }, body: objectSchema }, responses: { 200: { description: "Transitioned", body: objectSchema }, ...problemResponses } }),
} as const;
