import type { CycleReadinessResult, CycleCertification, CycleDeviation, CycleExecutionRepository, CycleExecutionStore, CycleRun, CycleTask, CycleTaskDependency, PublishedCycleTemplate } from "@athyper/server-contract-governance";
import type { PlaneKey } from "@athyper/server-foundation/context";
import type { PlaneTransactionCoordinator } from "@athyper/server-foundation/transaction";
import { sql, type Transaction } from "kysely";

type Database = Record<string, never>;
type Executor = Transaction<Database>;
type Row = Record<string, unknown>;

/** PostgreSQL execution store. Every callback receives a tenant-scoped transaction and run mutations serialize on cycle_run. */
export class KyselyCycleExecutionRepository implements CycleExecutionRepository {
  constructor(private readonly planeKey: PlaneKey, private readonly transactions: PlaneTransactionCoordinator<Executor>, private readonly completion?: (tenantId: string, runId: string, tx: Executor) => Promise<CycleReadinessResult>) {}

  async transaction<T>(actor: { readonly tenantId: string; readonly principalId: string }, operation: (store: CycleExecutionStore) => Promise<T>): Promise<T> {
    return this.transactions.run(this.planeKey,actor,async (transaction) => {
      await sql`SELECT set_config('app.current_tenant_id', ${actor.tenantId}, true), set_config('app.current_principal_id', ${actor.principalId}, true)`.execute(transaction);
      return operation(createStore(transaction, actor.tenantId, actor.principalId, this.completion));
    });
  }
}

function createStore(tx: Executor, tenantId: string, principalId: string, completion?: (tenantId: string, runId: string, tx: Executor) => Promise<CycleReadinessResult>): CycleExecutionStore {
  return {
    async evaluateCompletion(runId) { return completion ? completion(tenantId, runId, tx) : (await sql<{result: CycleReadinessResult}>`SELECT governance.evaluate_cycle_completion(${tenantId}::uuid,${runId}::uuid) result`.execute(tx)).rows[0]!.result; },
    async getPublishedTemplate(cycleTypeId, version) {
      const row = version === undefined
        ? (await sql<Row>`SELECT * FROM control.cycle_template_revision WHERE tenant_id=${tenantId}::uuid AND cycle_type_id=${cycleTypeId}::uuid ORDER BY revision_number DESC LIMIT 1`.execute(tx)).rows[0]
        : (await sql<Row>`SELECT * FROM control.cycle_template_revision WHERE tenant_id=${tenantId}::uuid AND cycle_type_id=${cycleTypeId}::uuid AND revision_number=${version}`.execute(tx)).rows[0];
      return row ? templateRow(row) : undefined;
    },
    async findRunByIdempotencyKey(key) { await sql`SELECT pg_advisory_xact_lock(hashtextextended(${tenantId + ":run:" + key}, 0))`.execute(tx); const row = (await sql<Row>`SELECT * FROM governance.cycle_run WHERE tenant_id=${tenantId}::uuid AND idempotency_key=${key} FOR UPDATE`.execute(tx)).rows[0]; return row ? runRow(row) : undefined; },
    async recordRunIdempotencyKey(key, runId) { const row = (await sql<Row>`SELECT 1 FROM governance.cycle_run WHERE tenant_id=${tenantId}::uuid AND id=${runId}::uuid AND idempotency_key=${key}`.execute(tx)).rows[0]; if (!row) conflict(); },
    async getRun(runId) { const row = (await sql<Row>`SELECT * FROM governance.cycle_run WHERE tenant_id=${tenantId}::uuid AND id=${runId}::uuid FOR UPDATE`.execute(tx)).rows[0]; return row ? runRow(row) : undefined; },
    async putRun(run) {
      const result = await sql`INSERT INTO governance.cycle_run(id,tenant_id,cycle_type_id,template_revision_id,template_revision_number,template_hash,code,name,period_start,period_end,scheduled_start_at,started_at,due_at,completed_at,parent_cycle_run_id,owner_principal_id,idempotency_key,data,status,created_at,created_by,updated_at,updated_by,version) VALUES(${run.id}::uuid,${tenantId}::uuid,${run.cycleTypeId}::uuid,${run.templateRevisionId}::uuid,${run.templateRevisionNumber},${run.templateHash},${run.code},${run.name},${run.periodStart ?? null}::date,${run.periodEnd ?? null}::date,${run.scheduledStartAt ?? null}::timestamptz,${run.startedAt ?? null}::timestamptz,${run.dueAt ?? null}::timestamptz,${run.completedAt ?? null}::timestamptz,${run.parentCycleRunId ?? null}::uuid,${run.ownerPrincipalId ?? null}::uuid,${run.idempotencyKey},${JSON.stringify(run.data)}::jsonb,${run.status}::governance.cycle_run_status_d,${run.createdAt}::timestamptz,${run.createdBy}::uuid,${run.updatedAt}::timestamptz,${run.updatedBy}::uuid,${run.version}) ON CONFLICT (id) DO UPDATE SET scheduled_start_at=EXCLUDED.scheduled_start_at,started_at=EXCLUDED.started_at,due_at=EXCLUDED.due_at,completed_at=EXCLUDED.completed_at,owner_principal_id=EXCLUDED.owner_principal_id,data=EXCLUDED.data,status=EXCLUDED.status,updated_by=EXCLUDED.updated_by,version=EXCLUDED.version WHERE governance.cycle_run.tenant_id=${tenantId}::uuid AND governance.cycle_run.version=EXCLUDED.version-1`.execute(tx);
      if (Number(result.numAffectedRows) !== 1) conflict();
    },
    async listChildRuns(parentRunId) { return (await sql<Row>`SELECT * FROM governance.cycle_run WHERE tenant_id=${tenantId}::uuid AND parent_cycle_run_id=${parentRunId}::uuid ORDER BY created_at,id`.execute(tx)).rows.map(runRow); },
    async listTasks(runId) { return (await sql<Row>`SELECT * FROM governance.cycle_task WHERE tenant_id=${tenantId}::uuid AND cycle_run_id=${runId}::uuid ORDER BY created_at,id`.execute(tx)).rows.map(taskRow); },
    async getTask(taskId) { const row = (await sql<Row>`SELECT task.* FROM governance.cycle_task task JOIN governance.cycle_run run ON run.tenant_id=task.tenant_id AND run.id=task.cycle_run_id WHERE task.tenant_id=${tenantId}::uuid AND task.id=${taskId}::uuid FOR UPDATE OF run,task`.execute(tx)).rows[0]; return row ? taskRow(row) : undefined; },
    async putTask(task) {
      const result = await sql`INSERT INTO governance.cycle_task(id,tenant_id,cycle_run_id,cycle_type_id,task_template_id,phase_id,code,name,completion_mode,is_mandatory,is_waivable,owner_principal_id,assigned_team_id,due_at,started_at,completed_at,completion_evidence,status,created_at,created_by,updated_at,updated_by,version) VALUES(${task.id}::uuid,${tenantId}::uuid,${task.cycleRunId}::uuid,${task.cycleTypeId}::uuid,${task.taskTemplateId}::uuid,${task.phaseId}::uuid,${task.code},${task.name},${task.completionMode}::control.cycle_completion_mode_d,${task.isMandatory},${task.isWaivable},${task.ownerPrincipalId ?? null}::uuid,${task.assignedTeamId ?? null}::uuid,${task.dueAt ?? null}::timestamptz,${task.startedAt ?? null}::timestamptz,${task.completedAt ?? null}::timestamptz,${JSON.stringify(task.completionEvidence)}::jsonb,${task.status}::governance.cycle_task_status_d,${task.createdAt}::timestamptz,${task.createdBy}::uuid,${task.updatedAt}::timestamptz,${task.updatedBy}::uuid,${task.version}) ON CONFLICT (id) DO UPDATE SET owner_principal_id=EXCLUDED.owner_principal_id,assigned_team_id=EXCLUDED.assigned_team_id,due_at=EXCLUDED.due_at,started_at=EXCLUDED.started_at,completed_at=EXCLUDED.completed_at,completion_evidence=EXCLUDED.completion_evidence,status=EXCLUDED.status,updated_by=EXCLUDED.updated_by,version=EXCLUDED.version WHERE governance.cycle_task.tenant_id=${tenantId}::uuid AND governance.cycle_task.version=EXCLUDED.version-1`.execute(tx);
      if (Number(result.numAffectedRows) !== 1) conflict();
    },
    async listDependencies(runId) { return (await sql<Row>`SELECT * FROM governance.cycle_task_dependency WHERE tenant_id=${tenantId}::uuid AND cycle_run_id=${runId}::uuid ORDER BY created_at,id`.execute(tx)).rows.map(dependencyRow); },
    async putDependency(edge) { const result = await sql`INSERT INTO governance.cycle_task_dependency(id,tenant_id,cycle_run_id,predecessor_task_id,successor_task_id,dependency_type,is_hard,created_by) VALUES(${edge.id}::uuid,${tenantId}::uuid,${edge.cycleRunId}::uuid,${edge.predecessorTaskId}::uuid,${edge.successorTaskId}::uuid,${edge.dependencyType}::control.cycle_dependency_type_d,${edge.isHard},${principalId}::uuid) ON CONFLICT (tenant_id,cycle_run_id,predecessor_task_id,successor_task_id) DO NOTHING`.execute(tx); if (Number(result.numAffectedRows) !== 1) conflict(); },
    async getDeviation(deviationId) { const row = (await sql<Row>`SELECT item.* FROM governance.cycle_deviation item JOIN governance.cycle_run run ON run.tenant_id=item.tenant_id AND run.id=item.cycle_run_id WHERE item.tenant_id=${tenantId}::uuid AND item.id=${deviationId}::uuid FOR UPDATE OF run,item`.execute(tx)).rows[0]; return row ? deviationRow(row) : undefined; },
    async listDeviations(runId) { return (await sql<Row>`SELECT * FROM governance.cycle_deviation WHERE tenant_id=${tenantId}::uuid AND cycle_run_id=${runId}::uuid ORDER BY created_at,id`.execute(tx)).rows.map(deviationRow); },
    async putDeviation(value) { const result = await sql`INSERT INTO governance.cycle_deviation(id,tenant_id,cycle_run_id,cycle_task_id,deviation_type,description,severity_code,status,resolution,carried_from_deviation_id,carried_to_cycle_run_id,carry_count,resolved_at,resolved_by,created_at,created_by) VALUES(${value.id}::uuid,${tenantId}::uuid,${value.cycleRunId}::uuid,${value.cycleTaskId ?? null}::uuid,${value.deviationType}::control.cycle_deviation_type_d,${value.description},${value.severity},${value.status},${value.resolution ?? null},${value.carriedFromDeviationId ?? null}::uuid,${value.carriedToCycleRunId ?? null}::uuid,${value.carryCount},${value.decidedAt ?? null}::timestamptz,${value.decidedBy ?? null}::uuid,${value.createdAt}::timestamptz,${value.createdBy}::uuid) ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status,resolution=EXCLUDED.resolution,carried_to_cycle_run_id=EXCLUDED.carried_to_cycle_run_id,resolved_at=EXCLUDED.resolved_at,resolved_by=EXCLUDED.resolved_by WHERE governance.cycle_deviation.tenant_id=${tenantId}::uuid AND governance.cycle_deviation.status='open'`.execute(tx); if (Number(result.numAffectedRows) !== 1) conflict(); },
    async findDeviationCarryByIdempotencyKey(key) { await sql`SELECT pg_advisory_xact_lock(hashtextextended(${tenantId + ":carry:" + key}, 0))`.execute(tx); const row = (await sql<Row>`SELECT * FROM governance.cycle_deviation WHERE tenant_id=${tenantId}::uuid AND carry_idempotency_key=${key} FOR UPDATE`.execute(tx)).rows[0]; return row ? deviationRow(row) : undefined; },
    async recordDeviationCarryIdempotencyKey(key, deviationId) { const result = await sql`UPDATE governance.cycle_deviation SET carry_idempotency_key=${key} WHERE tenant_id=${tenantId}::uuid AND id=${deviationId}::uuid AND carry_idempotency_key IS NULL`.execute(tx); if (Number(result.numAffectedRows) !== 1) conflict(); },
    async getCertification(certificationId) { const row = (await sql<Row>`SELECT item.* FROM governance.cycle_certification item JOIN governance.cycle_run run ON run.tenant_id=item.tenant_id AND run.id=item.cycle_run_id WHERE item.tenant_id=${tenantId}::uuid AND item.id=${certificationId}::uuid FOR UPDATE OF run,item`.execute(tx)).rows[0]; return row ? certificationRow(row) : undefined; },
    async listCertifications(runId) { return (await sql<Row>`SELECT * FROM governance.cycle_certification WHERE tenant_id=${tenantId}::uuid AND cycle_run_id=${runId}::uuid ORDER BY created_at,id`.execute(tx)).rows.map(certificationRow); },
    async putCertification(value) {
      const result = await sql`INSERT INTO governance.cycle_certification(id,tenant_id,cycle_run_id,certification_type_code,statement,evidence_snapshot,evidence_snapshot_id,submitted_by,submitted_at,certified_by,certified_at,signature,rejected_by,rejected_at,rejection_reason,status,created_at,created_by,version) VALUES(${value.id}::uuid,${tenantId}::uuid,${value.cycleRunId}::uuid,${value.certificationTypeCode},${value.statement},${value.evidenceSnapshot ? JSON.stringify(value.evidenceSnapshot) : null}::jsonb,${value.evidenceSnapshotId ?? null}::uuid,${value.submittedBy ?? null}::uuid,${value.submittedAt ?? null}::timestamptz,${value.certifiedBy ?? null}::uuid,${value.certifiedAt ?? null}::timestamptz,${value.signature ?? null},${value.rejectedBy ?? null}::uuid,${value.rejectedAt ?? null}::timestamptz,${value.rejectionReason ?? null},${value.status}::governance.certification_status_d,${value.createdAt}::timestamptz,${value.createdBy}::uuid,${value.version}) ON CONFLICT (id) DO UPDATE SET evidence_snapshot=EXCLUDED.evidence_snapshot,evidence_snapshot_id=EXCLUDED.evidence_snapshot_id,submitted_by=EXCLUDED.submitted_by,submitted_at=EXCLUDED.submitted_at,certified_by=EXCLUDED.certified_by,certified_at=EXCLUDED.certified_at,signature=EXCLUDED.signature,rejected_by=EXCLUDED.rejected_by,rejected_at=EXCLUDED.rejected_at,rejection_reason=EXCLUDED.rejection_reason,status=EXCLUDED.status,version=EXCLUDED.version WHERE governance.cycle_certification.tenant_id=${tenantId}::uuid AND governance.cycle_certification.version=EXCLUDED.version-1 AND governance.cycle_certification.status<>'approved'`.execute(tx);
      if (Number(result.numAffectedRows) !== 1) conflict();
    },
  };
}

function runRow(row: Row): CycleRun { return { id: string(row,"id"), tenantId:string(row,"tenant_id"), cycleTypeId:string(row,"cycle_type_id"), templateRevisionId:string(row,"template_revision_id"), templateRevisionNumber:number(row,"template_revision_number"), templateHash:string(row,"template_hash"), code:string(row,"code"), name:string(row,"name"), ...optionalDate(row,"period_start","periodStart",true), ...optionalDate(row,"period_end","periodEnd",true), ...optionalDate(row,"scheduled_start_at","scheduledStartAt"), ...optionalDate(row,"started_at","startedAt"), ...optionalDate(row,"due_at","dueAt"), ...optionalDate(row,"completed_at","completedAt"), ...optionalString(row,"parent_cycle_run_id","parentCycleRunId"), ...optionalString(row,"owner_principal_id","ownerPrincipalId"), idempotencyKey:string(row,"idempotency_key"), data:object(row["data"]), status:string(row,"status") as CycleRun["status"], createdAt:date(row["created_at"]), createdBy:string(row,"created_by"), updatedAt:date(row["updated_at"] ?? row["created_at"]), updatedBy:String(row["updated_by"] ?? row["created_by"]), version:number(row,"version") }; }
function taskRow(row: Row): CycleTask { return { id:string(row,"id"),tenantId:string(row,"tenant_id"),cycleRunId:string(row,"cycle_run_id"),cycleTypeId:string(row,"cycle_type_id"),taskTemplateId:string(row,"task_template_id"),phaseId:string(row,"phase_id"),code:string(row,"code"),name:string(row,"name"),completionMode:string(row,"completion_mode") as CycleTask["completionMode"],isMandatory:Boolean(row["is_mandatory"]),isWaivable:Boolean(row["is_waivable"]),...optionalString(row,"owner_principal_id","ownerPrincipalId"),...optionalString(row,"assigned_team_id","assignedTeamId"),...optionalDate(row,"due_at","dueAt"),...optionalDate(row,"started_at","startedAt"),...optionalDate(row,"completed_at","completedAt"),completionEvidence:object(row["completion_evidence"]),status:string(row,"status") as CycleTask["status"],createdAt:date(row["created_at"]),createdBy:string(row,"created_by"),updatedAt:date(row["updated_at"]??row["created_at"]),updatedBy:String(row["updated_by"]??row["created_by"]),version:number(row,"version")}; }
function dependencyRow(row:Row):CycleTaskDependency{return{id:string(row,"id"),tenantId:string(row,"tenant_id"),cycleRunId:string(row,"cycle_run_id"),predecessorTaskId:string(row,"predecessor_task_id"),successorTaskId:string(row,"successor_task_id"),dependencyType:string(row,"dependency_type") as CycleTaskDependency["dependencyType"],isHard:Boolean(row["is_hard"])}};
function deviationRow(row:Row):CycleDeviation{return{id:string(row,"id"),tenantId:string(row,"tenant_id"),cycleRunId:string(row,"cycle_run_id"),...optionalString(row,"cycle_task_id","cycleTaskId"),deviationType:string(row,"deviation_type") as CycleDeviation["deviationType"],description:string(row,"description"),severity:string(row,"severity_code") as CycleDeviation["severity"],status:string(row,"status") as CycleDeviation["status"],...optionalString(row,"resolution","resolution"),...optionalString(row,"carried_from_deviation_id","carriedFromDeviationId"),...optionalString(row,"carried_to_cycle_run_id","carriedToCycleRunId"),carryCount:number(row,"carry_count"),createdAt:date(row["created_at"]),createdBy:string(row,"created_by"),...optionalDate(row,"resolved_at","decidedAt"),...optionalString(row,"resolved_by","decidedBy")}};
function certificationRow(row:Row):CycleCertification{return{id:string(row,"id"),tenantId:string(row,"tenant_id"),cycleRunId:string(row,"cycle_run_id"),certificationTypeCode:string(row,"certification_type_code"),statement:string(row,"statement"),status:string(row,"status") as CycleCertification["status"],...(row["evidence_snapshot"]?{evidenceSnapshot:object(row["evidence_snapshot"])}:{}),...optionalString(row,"evidence_snapshot_id","evidenceSnapshotId"),...optionalString(row,"signature","signature"),...optionalDate(row,"submitted_at","submittedAt"),...optionalString(row,"submitted_by","submittedBy"),...optionalDate(row,"certified_at","certifiedAt"),...optionalString(row,"certified_by","certifiedBy"),...optionalDate(row,"rejected_at","rejectedAt"),...optionalString(row,"rejected_by","rejectedBy"),...optionalString(row,"rejection_reason","rejectionReason"),createdAt:date(row["created_at"]),createdBy:string(row,"created_by"),version:number(row,"version")}};
function templateRow(row:Row):PublishedCycleTemplate{const preview=object(row["template_json"]) as unknown as PublishedCycleTemplate;return{...preview,id:string(row,"id"),tenantId:string(row,"tenant_id"),version:number(row,"revision_number"),publishedAt:date(row["published_at"]),publishedBy:string(row,"published_by")}};
function object(value:unknown):Record<string,unknown>{if(typeof value==="string"){try{return JSON.parse(value) as Record<string,unknown>;}catch{return {};}}return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function string(row:Row,key:string):string{return String(row[key]);} function number(row:Row,key:string):number{return Number(row[key]);} function date(value:unknown):string{return value instanceof Date?value.toISOString():new Date(String(value)).toISOString();}
function optionalString<K extends string>(row:Row,column:string,key:K):{[P in K]?:string}{return row[column]===null||row[column]===undefined?{}:{[key]:String(row[column])} as {[P in K]?:string};}
function optionalDate<K extends string>(row:Row,column:string,key:K,dateOnly=false):{[P in K]?:string}{if(row[column]===null||row[column]===undefined)return{};const value=date(row[column]);return{[key]:dateOnly?value.slice(0,10):value} as {[P in K]?:string};}
function conflict():never{throw Object.assign(new Error("GOVERNANCE_EXPECTED_VERSION_CONFLICT"),{code:"GOVERNANCE_EXPECTED_VERSION_CONFLICT"});}
