#!/usr/bin/env tsx

import{readFile,writeFile,mkdir}from"node:fs/promises";
import{resolve,dirname}from"node:path";
import{pathToFileURL}from"node:url";
import{Client}from"pg";
import{assertLoopbackDatabaseTarget}from"../lib/database-target.js";

const CONFIRMATION="RUN-BS360-PERFORMANCE-EVIDENCE",PACK="business-partner-360.acceptance.v1";
type Plan=Readonly<Record<string,unknown>>;

export async function runBusinessPartner360PerformanceEvidence(options:{readonly neonDatabaseUrl:string;readonly confirmation?:string;readonly rows?:number;readonly output?:string}){
 assertLocal(options.neonDatabaseUrl);if(options.confirmation!==CONFIRMATION)throw new Error(`execution requires --confirm=${CONFIRMATION}`);const rows=Math.min(Math.max(options.rows??25_000,10_000),100_000),client=new Client({connectionString:options.neonDatabaseUrl,application_name:"bs360-performance-evidence"});await client.connect();
 try{const context=await one<{tenantId:string;principalId:string;businessPartnerId:string}>(client,`SELECT tenant.id::text "tenantId",principal.id::text "principalId",partner.id::text "businessPartnerId" FROM master.tenant tenant JOIN LATERAL(SELECT id FROM master.principal WHERE tenant_id=tenant.id ORDER BY code LIMIT 1)principal ON true JOIN master.business_partner partner ON partner.tenant_id=tenant.id AND partner.metadata->'_seed'->>'pack'=$1 AND partner.metadata->>'acceptanceFamily'='supplier' WHERE tenant.code='athyper' LIMIT 1`,[PACK]);await client.query("BEGIN");try{
   await client.query(`INSERT INTO master.business_partner_identifier(id,tenant_id,business_partner_id,scheme_code,identifier_value,issued_at,is_primary,metadata,status,status_changed_at,status_changed_by,created_at,created_by) SELECT uuid(md5('bs360-perf-id-'||value::text)),$1::uuid,$2::uuid,'business_registration','PERF-'||value::text,CURRENT_DATE,false,jsonb_build_object('maskedValue','PERF-****'||lpad((value%10000)::text,4,'0')),'active',clock_timestamp(),$3::uuid,clock_timestamp()-(value||' microseconds')::interval,$3::uuid FROM generate_series(1,$4::int)value`,[context.tenantId,context.businessPartnerId,context.principalId,rows]);
   await client.query(`INSERT INTO document.business_partner_request(id,tenant_id,request_no,request_kind,source_kind,registration_mode,target_business_partner_id,base_record_version,payload_schema_code,payload_schema_version,payload_schema_hash,proposed_payload,idempotency_key,status,created_at,created_by) SELECT uuid(md5('bs360-perf-request-'||value::text)),$1::uuid,'B360P.'||value::text,'amend_partner','manual','direct',$2::uuid,1,'business_partner.onboarding',1,$3,'{}'::jsonb,'bs360-perf-request-'||value::text,'draft',clock_timestamp()-(value||' microseconds')::interval,$4::uuid FROM generate_series(1,$5::int)value`,[context.tenantId,context.businessPartnerId,"a".repeat(64),context.principalId,rows]);
   await client.query("ANALYZE master.business_partner_identifier");await client.query("ANALYZE document.business_partner_request");
   const plans=[await explain(client,"identifierPage",`SELECT id::text,scheme_code,COALESCE(metadata->>'maskedValue','••••') masked_value,created_at FROM master.business_partner_identifier WHERE tenant_id=$1::uuid AND business_partner_id=$2::uuid AND status='active' AND(issued_at IS NULL OR issued_at<=CURRENT_DATE)AND(effective_until IS NULL OR effective_until>CURRENT_DATE)AND created_at<=clock_timestamp() ORDER BY created_at DESC,id DESC LIMIT 101`,[context.tenantId,context.businessPartnerId]),await explain(client,"openWork",`SELECT count(*)FILTER(WHERE status IN('draft','validation_failed','pending_approval','returned','approved','applying'))::int active_count,count(*)FILTER(WHERE status='returned')::int returned_count FROM document.business_partner_request WHERE tenant_id=$1::uuid AND(target_business_partner_id=$2::uuid OR materialized_business_partner_id=$2::uuid)`,[context.tenantId,context.businessPartnerId]),await explain(client,"recentActivity",`SELECT id::text,created_at,status FROM document.business_partner_request WHERE tenant_id=$1::uuid AND(target_business_partner_id=$2::uuid OR materialized_business_partner_id=$2::uuid) ORDER BY created_at DESC,id DESC LIMIT 5`,[context.tenantId,context.businessPartnerId])];
   const source=await readFile(resolve(import.meta.dirname,"../../../packages/services/master-data/src/kysely-business-partner-360-sections.ts"),"utf8"),noNPlusOne={contactsBatched:/contact_person_id=ANY/.test(source)&&/link\.owner_id=ANY/.test(source)&&!/people\.map\(async/.test(source),addressEventsBatched:/subject_address_id=ANY/.test(source)&&/PARTITION BY subject_address_id/.test(source)&&!/rows\.map\(async/.test(source)};if(!Object.values(noNPlusOne).every(Boolean))throw new Error("BP360 child readers are not bounded-query implementations");for(const plan of plans){if(plan.executionMs>750)throw new Error(`${plan.code} exceeded the 750 ms section budget`);if(plan.maxActualLoops>1_000)throw new Error(`${plan.code} contains an unexpectedly repeated plan node`);}const evidence={schemaVersion:1,kind:"athyper.business-partner-360.performance-evidence",capturedAt:new Date().toISOString(),database:"athyper_neon",sanitized:true,rolledBack:true,fixtureRows:{identifiers:rows,requests:rows},plans,noNPlusOne,passed:true};if(options.output){const repositoryRoot=resolve(import.meta.dirname,"../../../.."),destination=resolve(repositoryRoot,options.output);await mkdir(dirname(destination),{recursive:true});await writeFile(destination,`${JSON.stringify(evidence,null,2)}\n`);}return evidence;
  }finally{await client.query("ROLLBACK");}
 }finally{await client.end();}
}

async function explain(client:Client,code:string,statement:string,values:unknown[]){const result=await client.query(`EXPLAIN(ANALYZE,BUFFERS,FORMAT JSON) ${statement}`,values),document=result.rows[0]?.["QUERY PLAN"] as unknown,root=(Array.isArray(document)?document[0]:document)as Plan,plan=root["Plan"]as Plan,nodes=flatten(plan);return{code,planningMs:Number(root["Planning Time"]??0),executionMs:Number(root["Execution Time"]??0),actualRows:Number(plan["Actual Rows"]??0),maxActualLoops:Math.max(...nodes.map(node=>Number(node["Actual Loops"]??0))),indexes:[...new Set(nodes.map(node=>node["Index Name"]).filter((value):value is string=>typeof value==="string"))],nodeTypes:[...new Set(nodes.map(node=>String(node["Node Type"])))],sharedHitBlocks:nodes.reduce((total,node)=>total+Number(node["Shared Hit Blocks"]??0),0),sharedReadBlocks:nodes.reduce((total,node)=>total+Number(node["Shared Read Blocks"]??0),0),plan:root};}
function flatten(plan:Plan):Plan[]{return[plan,...((plan["Plans"]as Plan[]|undefined)??[]).flatMap(flatten)];}
async function one<T extends object>(client:Client,statement:string,values:unknown[]=[]){const result=await client.query<T>(statement,values);if(result.rows.length!==1)throw new Error(`expected one row, received ${result.rows.length}`);return result.rows[0]!;}
function assertLocal(value:string){assertLoopbackDatabaseTarget(value,"athyper_neon");}
function option(args:readonly string[],name:string){return args.find(value=>value.startsWith(`${name}=`))?.slice(name.length+1);}
if(import.meta.url===pathToFileURL(process.argv[1]??"").href){const args=process.argv.slice(2),url=option(args,"--neon-database-url")??process.env["ATHYPER_NEON_DATABASE_ADMIN_URL"];if(!url)throw new Error("--neon-database-url or ATHYPER_NEON_DATABASE_ADMIN_URL is required");const evidence=await runBusinessPartner360PerformanceEvidence({neonDatabaseUrl:url,confirmation:option(args,"--confirm"),rows:Number(option(args,"--rows")??25_000),...(option(args,"--output")?{output:option(args,"--output")}: {})});process.stdout.write(`${JSON.stringify({...evidence,plans:evidence.plans.map(({plan:_,...summary})=>summary)},null,2)}\n`);}
