BEGIN;
-- Restore the plane-specific governed workflow command overwritten by manifest order.
CREATE OR REPLACE FUNCTION document.command_entity_case_lifecycle(
 p_tenant_id uuid,p_case_id uuid,p_action text,p_expected_version bigint,p_cycle_run_id uuid,p_cycle_task_id uuid,p_reason text,p_idempotency_key text,p_actor_id uuid,p_correlation_id uuid DEFAULT NULL)
RETURNS TABLE(entity_case_id uuid,snapshot_id uuid,row_version bigint,status text,replayed boolean,outbox_id uuid)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,document,snapshot,runtime_meta,event,governance,shared,master SET row_security=on AS $$
DECLARE fingerprint text;prior event.command_execution%ROWTYPE;execution uuid;current document.entity_case%ROWTYPE;task governance.cycle_task%ROWTYPE;payload jsonb;next_snapshot uuid;next_version bigint;next_status text;outbox uuid;result jsonb;command_code text;lineage_hash text;
BEGIN
 IF current_database()<>'athyper_'||current_setting('app.database_plane',true) OR shared.current_tenant_id()<>p_tenant_id OR master.current_principal_id_soft() IS DISTINCT FROM p_actor_id THEN RAISE EXCEPTION 'Entity case lifecycle context mismatch' USING ERRCODE='insufficient_privilege';END IF;
 IF p_action NOT IN('submit','approve','reject','return') OR p_expected_version<1 OR (p_cycle_run_id IS NULL)<>(p_cycle_task_id IS NULL) OR btrim(p_idempotency_key)<>p_idempotency_key OR length(p_idempotency_key) NOT BETWEEN 8 AND 200 OR (p_action IN('reject','return') AND NULLIF(btrim(p_reason),'') IS NULL) OR length(COALESCE(p_reason,''))>2000 THEN RAISE EXCEPTION 'Entity case lifecycle arguments are invalid' USING ERRCODE='check_violation';END IF;
 command_code:=CASE WHEN p_action='submit' THEN 'entity.case.submit' ELSE 'entity.case.decision' END;
 fingerprint:=encode(public.digest(convert_to(jsonb_build_object('caseId',p_case_id,'action',p_action,'expectedVersion',p_expected_version,'cycleRunId',p_cycle_run_id,'cycleTaskId',p_cycle_task_id,'reason',p_reason,'actorId',p_actor_id)::text,'UTF8'),'sha256'),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant_id::text||':entity-case-lifecycle:'||p_idempotency_key,0));
 SELECT e.* INTO prior FROM event.command_execution e WHERE e.tenant_id=p_tenant_id AND e.command_code='entity.case.lifecycle' AND e.idempotency_key=p_idempotency_key;
 IF FOUND THEN IF prior.request_fingerprint<>fingerprint THEN RAISE EXCEPTION 'Entity case lifecycle idempotency conflict' USING ERRCODE='unique_violation';END IF;RETURN QUERY SELECT (prior.result_payload->>'caseId')::uuid,(prior.result_payload->>'snapshotId')::uuid,(prior.result_payload->>'rowVersion')::bigint,prior.result_payload->>'status',true,(prior.result_payload->>'outboxId')::uuid;RETURN;END IF;
 INSERT INTO event.command_execution(tenant_id,command_code,idempotency_key,request_fingerprint,status,actor_principal_id,source_service,correlation_id,started_at,status_changed_at,status_changed_by,created_by) VALUES(p_tenant_id,'entity.case.lifecycle',p_idempotency_key,fingerprint,'processing',p_actor_id,'governed-entity-case',p_correlation_id,clock_timestamp(),clock_timestamp(),p_actor_id,p_actor_id) RETURNING id INTO execution;
 PERFORM set_config('app.entity_case_command_execution_id',execution::text,true);PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant_id::text||':entity-case:'||p_case_id::text,0));
 SELECT c.* INTO current FROM document.entity_case c WHERE c.tenant_id=p_tenant_id AND c.id=p_case_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Entity case was not found' USING ERRCODE='no_data_found';END IF;
 IF current.row_version<>p_expected_version THEN RAISE EXCEPTION 'Entity case version is stale' USING ERRCODE='serialization_failure';END IF;
 IF p_cycle_task_id IS NOT NULL THEN SELECT t.* INTO task FROM governance.cycle_task t JOIN governance.cycle_run r ON r.tenant_id=t.tenant_id AND r.id=t.cycle_run_id WHERE t.tenant_id=p_tenant_id AND t.id=p_cycle_task_id AND t.cycle_run_id=p_cycle_run_id FOR UPDATE OF t;IF NOT FOUND THEN RAISE EXCEPTION 'Cycle run and task binding was not found' USING ERRCODE='foreign_key_violation';END IF;END IF;
 SELECT s.payload_json INTO payload FROM snapshot.entity_snapshot s WHERE s.tenant_id=p_tenant_id AND s.snapshot_id=current.current_snapshot_id;IF NOT FOUND THEN RAISE EXCEPTION 'Current entity case snapshot was not found' USING ERRCODE='data_corrupted';END IF;
 next_version:=current.row_version+1;
 IF p_action='submit' THEN
  IF current.status<>'draft' OR (p_cycle_task_id IS NOT NULL AND task.status NOT IN('pending','ready','in_progress')) THEN RAISE EXCEPTION 'Entity case is not submittable' USING ERRCODE='object_not_in_prerequisite_state';END IF;
  IF NOT EXISTS(SELECT 1 FROM document.entity_case_validation v WHERE v.tenant_id=p_tenant_id AND v.entity_case_id=p_case_id AND v.evaluated_snapshot_id=current.current_snapshot_id AND v.details->'validationSummary'->>'outcome'='passed') THEN RAISE EXCEPTION 'Entity case requires successful validation of the current snapshot' USING ERRCODE='object_not_in_prerequisite_state';END IF;
  IF cardinality(document.fn_validate_entity_case_payload((SELECT c.contract_json FROM runtime_meta.entity_contract c WHERE c.tenant_id=p_tenant_id AND c.id=current.entity_contract_id AND c.entity_contract_hash=current.entity_contract_hash AND c.status IN('published','superseded')),payload))>0 THEN RAISE EXCEPTION 'Entity case submission failed pinned contract validation' USING ERRCODE='check_violation';END IF;
  next_status:='submitted';
 ELSE
  IF current.status NOT IN('submitted','in_review') OR p_actor_id=current.created_by OR (p_cycle_task_id IS NOT NULL AND (task.status NOT IN('in_progress','ready') OR (task.owner_principal_id IS NOT NULL AND task.owner_principal_id<>p_actor_id) OR NOT EXISTS(SELECT 1 FROM governance.cycle_subject s WHERE s.tenant_id=p_tenant_id AND s.cycle_run_id=p_cycle_run_id AND s.cycle_task_id=p_cycle_task_id AND s.entity_case_id=p_case_id AND s.is_primary))) THEN RAISE EXCEPTION 'Entity case decision violates maker-checker authority' USING ERRCODE='insufficient_privilege';END IF;
  IF p_action='approve' AND current.operation_code='amend_partner' THEN
   PERFORM 1 FROM document.mesh_profile_change_resolution resolution
    JOIN document.mesh_profile_change_case link ON link.tenant_id=resolution.tenant_id AND link.resolution_id=resolution.id
    JOIN master.business_partner bp ON bp.tenant_id=resolution.tenant_id AND bp.id=resolution.business_partner_id
    JOIN control.mesh_business_partner_profile_projection projection ON projection.tenant_id=resolution.tenant_id AND projection.id=resolution.projection_id
    WHERE link.tenant_id=p_tenant_id AND link.entity_case_id=p_case_id AND bp.status='active'
     AND bp.record_version=resolution.expected_target_version AND projection.projection_status='active' AND projection.current_snapshot_id=resolution.incoming_snapshot_id
    FOR SHARE OF bp,projection;
   IF NOT FOUND THEN RAISE EXCEPTION 'Profile source or target changed before approval' USING ERRCODE='serialization_failure'; END IF;
  END IF;
  next_status:=CASE p_action WHEN 'approve' THEN 'approved' WHEN 'reject' THEN 'rejected' ELSE 'draft' END;
 END IF;
 next_snapshot:=snapshot.fn_capture_entity('document.entity_case',p_case_id,current.case_code,1,current.entity_contract_hash,next_version,'entity.case.'||p_action,'version',payload,p_correlation_id,NULL,NULL,NULL,'legal','governed-entity-case');
 lineage_hash:=encode(public.digest(convert_to(jsonb_build_object('caseId',p_case_id,'sourceSnapshotId',current.current_snapshot_id,'targetSnapshotId',next_snapshot,'action',p_action,'version',next_version)::text,'UTF8'),'sha256'),'hex');
 INSERT INTO snapshot.entity_case_snapshot_lineage(tenant_id,entity_case_id,source_snapshot_id,target_snapshot_id,lineage_role,transformation_code,transformation_version,evidence_hash,created_by) VALUES(p_tenant_id,p_case_id,current.current_snapshot_id,next_snapshot,CASE WHEN p_action='submit' THEN 'submitted_from' ELSE 'decided_from' END,'entity.case.'||p_action,'1',lineage_hash,p_actor_id);
 IF p_cycle_task_id IS NOT NULL THEN
  IF p_action='submit' THEN INSERT INTO governance.cycle_subject(tenant_id,cycle_run_id,cycle_task_id,subject_role,entity_case_id,is_primary,created_by) VALUES(p_tenant_id,p_cycle_run_id,p_cycle_task_id,'governed_case',p_case_id,true,p_actor_id) ON CONFLICT DO NOTHING;UPDATE governance.cycle_task SET status='in_progress',started_at=COALESCE(started_at,clock_timestamp()),updated_by=p_actor_id,version=version+1 WHERE tenant_id=p_tenant_id AND id=p_cycle_task_id;UPDATE governance.cycle_run run SET status='running',started_at=COALESCE(run.started_at,clock_timestamp()),updated_by=p_actor_id,version=run.version+1 WHERE run.tenant_id=p_tenant_id AND run.id=p_cycle_run_id AND run.status IN('draft','scheduled');
  ELSIF p_action='return' THEN UPDATE governance.cycle_task SET status='ready',started_at=NULL,completed_at=NULL,completion_evidence=jsonb_build_object('caseId',p_case_id,'decision','return','snapshotId',next_snapshot,'reason',p_reason),updated_by=p_actor_id,version=version+1 WHERE tenant_id=p_tenant_id AND id=p_cycle_task_id;
  ELSE UPDATE governance.cycle_task SET status='completed',completed_at=clock_timestamp(),completion_evidence=jsonb_build_object('caseId',p_case_id,'decision',p_action,'snapshotId',next_snapshot,'reason',p_reason),updated_by=p_actor_id,version=version+1 WHERE tenant_id=p_tenant_id AND id=p_cycle_task_id;UPDATE governance.cycle_run SET status='completed',completed_at=clock_timestamp(),updated_by=p_actor_id,version=version+1 WHERE tenant_id=p_tenant_id AND id=p_cycle_run_id;END IF;
 END IF;
 UPDATE document.entity_case SET current_snapshot_id=next_snapshot,submitted_snapshot_id=CASE WHEN p_action='submit' THEN next_snapshot ELSE submitted_snapshot_id END,decision_snapshot_id=CASE WHEN p_action IN('approve','reject') THEN next_snapshot WHEN p_action='return' THEN NULL ELSE decision_snapshot_id END,status=next_status,row_version=next_version,updated_by=p_actor_id WHERE tenant_id=p_tenant_id AND id=p_case_id;
 INSERT INTO document.entity_case_command_evidence(tenant_id,entity_case_id,command_code,idempotency_key,request_fingerprint,expected_version,before_version,after_version,before_status,after_status,outcome,result_code,result_snapshot_id,result_evidence,recorded_by) VALUES(p_tenant_id,p_case_id,command_code,p_idempotency_key,fingerprint,p_expected_version,current.row_version,next_version,current.status,next_status,'accepted',CASE p_action WHEN 'submit' THEN 'ENTITY_CASE_SUBMITTED' WHEN 'approve' THEN 'ENTITY_CASE_APPROVED' WHEN 'reject' THEN 'ENTITY_CASE_REJECTED' ELSE 'ENTITY_CASE_RETURNED' END,next_snapshot,jsonb_build_object('cycleRunId',p_cycle_run_id,'cycleTaskId',p_cycle_task_id,'reason',p_reason),p_actor_id);
 INSERT INTO event.outbox(tenant_id,topic,event_type,event_key,entity_type,entity_id,aggregate_type,aggregate_id,event_version,actor_id,source,correlation_id,partition_key,payload,created_by) VALUES(p_tenant_id,'governed-entity-case','entity.case.'||CASE WHEN p_action='submit' THEN 'submitted' ELSE p_action END,'entity-case:'||p_case_id::text||':v'||next_version::text||':'||p_idempotency_key,'document.entity_case',p_case_id,'entity_case',p_case_id,LEAST(next_version,2147483647)::integer,p_actor_id,'governed-entity-case',p_correlation_id,p_tenant_id::text,jsonb_build_object('caseId',p_case_id,'snapshotId',next_snapshot,'rowVersion',next_version,'status',next_status,'action',p_action,'cycleRunId',p_cycle_run_id,'cycleTaskId',p_cycle_task_id),p_actor_id) RETURNING id INTO outbox;
 result:=jsonb_build_object('caseId',p_case_id,'snapshotId',next_snapshot,'rowVersion',next_version,'status',CASE WHEN p_action='return' THEN 'returned' ELSE next_status END,'outboxId',outbox);UPDATE event.command_execution SET status='succeeded',result_payload=result,completed_at=clock_timestamp(),status_changed_at=clock_timestamp(),status_changed_by=p_actor_id,updated_by=p_actor_id WHERE id=execution;
 RETURN QUERY SELECT p_case_id,next_snapshot,next_version,CASE WHEN p_action='return' THEN 'returned' ELSE next_status END,false,outbox;
END $$;
COMMIT;
