import {readFileSync} from "node:fs";import {resolve} from "node:path";import {describe,expect,it} from "vitest";
import {summarizeCertificationDomains,type DomainReadiness,type FinanceCertificationDomain} from "../services/finance-certification-readiness.service.js";
const root=resolve(import.meta.dirname,"../../../../..");const read=(path:string)=>readFileSync(resolve(root,path),"utf8");
const domain=(key:FinanceCertificationDomain,passed:number,total:number):DomainReadiness=>({domain:key,label:key,state:passed===total?"ready":passed===0?"not_started":"blocked",passed,total,blockerCount:total-passed,warningCount:0,checks:[],primaryAction:{label:"open",href:"/"}});

describe("Finance Setup Phase 2 Stage F certification and rollout",()=>{
 it("requires exactly four ready domains",()=>{const ready=[domain("currency_fx",3,3),domain("tax",4,4),domain("payments_settlement",5,5),domain("banking_treasury",3,3)];expect(summarizeCertificationDomains(ready)).toMatchObject({passed:15,total:15,blockerCount:0,readyForCertification:true});expect(summarizeCertificationDomains(ready.slice(0,3))).toMatchObject({readyForCertification:false});});
 it("keeps single-company and multi-company certification decisions independent",()=>{const ready=[domain("currency_fx",3,3),domain("tax",4,4),domain("payments_settlement",5,5),domain("banking_treasury",3,3)],blocked=ready.map(row=>({...row}));blocked[1]=domain("tax",3,4);const single=[summarizeCertificationDomains(ready)];const multi=[summarizeCertificationDomains(ready),summarizeCertificationDomains(blocked)];expect(single.filter(row=>row.readyForCertification)).toHaveLength(1);expect(multi.filter(row=>row.readyForCertification)).toHaveLength(1);expect(multi[1]?.blockerCount).toBe(1);});
 it.each([
  ["multi-currency missing pair","currency_fx",2,3],
  ["multi-Book settlement gap","payments_settlement",4,5],
  ["multi-House-Bank validation gap","banking_treasury",2,3],
  ["multi-jurisdiction ambiguity","tax",3,4],
 ] as const)("blocks the %s matrix",(_name,key,passed,total)=>{const rows=[domain("currency_fx",3,3),domain("tax",4,4),domain("payments_settlement",5,5),domain("banking_treasury",3,3)];const index=rows.findIndex(row=>row.domain===key);rows[index]=domain(key,passed,total);expect(summarizeCertificationDomains(rows).readyForCertification).toBe(false);expect(summarizeCertificationDomains(rows).blockerCount).toBe(1);});
 it("ships endpoint, UI roll-up, safe defaults, invalidation, and rollout-aware posting gates",()=>{const route=read("server/packages/services/finance/routes/finance-setup.route.ts"),ui=read("packages/domain/finance/finance-workbench/src/views/company-hub/CertificationReadinessPanel.tsx"),defaults=read("server/db/seed/platform/003_control/110_finance_phase2_stage_f_rollout.sql"),invalidation=read("server/db/ddl/governance/09z_finance_phase2_domain_invalidation.sql"),gate=read("server/db/ddl/document/07z_finance_certification_rollout.sql");expect(route).toContain("/finance/setup/certification-readiness");for(const key of ["currency_fx","tax","payments_settlement","banking_treasury"])expect(read("server/packages/services/finance/services/finance-certification-readiness.service.ts")).toContain(key);expect(ui).toContain("Phase 2 certification roll-up");expect(defaults).toContain("'observe'");expect(defaults).toContain("is_enabled=true");expect(invalidation).toContain("trg_fin_ready_fx_policy");expect(invalidation).toContain("trg_fin_ready_tax_group_version");expect(invalidation).toContain("trg_fin_ready_payment_policy");expect(invalidation).toContain("trg_fin_ready_house_bank");expect(gate).toContain("rollout_mode<>'enforce'");expect(gate).toContain("fourDomainReadiness");});
});
