import type { AtlasContentBlock, AtlasModelMessage, AtlasModelProvider, AtlasProviderError, AtlasProviderEvent, AtlasProviderInvocation, AtlasProviderUsage } from "@athyper/server-contract-ai";

export const GEMINI_INTERACTIONS_ADAPTER_ID = "gemini-interactions";
export const GEMINI_INTERACTIONS_ADAPTER_VERSION = "1";
const DEFAULT_URL = "https://generativelanguage.googleapis.com/v1beta/interactions?alt=sse";
export interface GeminiAdapterOptions { readonly fetch?: typeof fetch; readonly endpoint?: string; readonly timeoutMs?: number }

export class GeminiModelProvider implements AtlasModelProvider {
  readonly providerId = "gemini" as const; readonly adapterId = GEMINI_INTERACTIONS_ADAPTER_ID; readonly adapterVersion = GEMINI_INTERACTIONS_ADAPTER_VERSION;
  private readonly fetcher: typeof fetch; private readonly endpoint: string; private readonly timeoutMs: number;
  constructor(options: GeminiAdapterOptions = {}) { this.fetcher = options.fetch ?? fetch; this.endpoint = options.endpoint ?? DEFAULT_URL; this.timeoutMs = options.timeoutMs ?? 120_000; }
  async *invoke(invocation: AtlasProviderInvocation): AsyncIterable<AtlasProviderEvent> {
    const mismatch = validate(invocation, this); if (mismatch) { yield { kind: "failed", error: mismatch }; return; }
    const scope = requestScope(invocation.signal, this.timeoutMs);
    try {
      const response = await this.fetcher(this.endpoint, { method: "POST", headers: { "content-type": "application/json", accept: "text/event-stream", "x-goog-api-key": invocation.credential.secret }, body: JSON.stringify(buildBody(invocation)), signal: scope.signal });
      if (!response.ok) { yield { kind: "failed", error: httpError(response.status) }; return; }
      if (!response.body || !(response.headers.get("content-type") ?? "").toLowerCase().startsWith("text/event-stream")) { yield { kind: "failed", error: protocol("invalid_stream") }; return; }
      const calls = new Map<number, { callId: string; name: string; json: string }>(); let started = false; let terminal = false; let sawTool = false;
      for await (const frame of readSse(response.body)) {
        if (!frame.data || frame.data === "[DONE]") continue; let event: any; try { event = JSON.parse(frame.data); } catch { yield { kind: "failed", error: protocol("invalid_json") }; return; }
        const eventType = event.event_type ?? frame.event;
        if (eventType === "interaction.created") { const model = normalizeModel(event.interaction?.model); if (!model) { yield { kind: "failed", error: protocol("missing_model") }; return; } started = true; yield { kind: "response_started", providerRequestId: nonEmpty(event.interaction?.id), actualModelId: model }; }
        else if (eventType === "step.start" && event.step?.type === "function_call") { const index = integer(event.index); const call = { callId: required(event.step.id ?? `gemini-step-${index}`), name: required(event.step.name), json: typeof event.step.arguments === "string" ? event.step.arguments : JSON.stringify(event.step.arguments ?? {}) }; calls.set(index, call); sawTool = true; yield { kind: "tool_call_start", callId: call.callId, toolName: call.name }; }
        else if (eventType === "step.delta" && event.delta?.type === "text" && typeof event.delta.text === "string") yield { kind: "text_delta", text: event.delta.text };
        else if (eventType === "step.delta" && (event.delta?.type === "arguments" || event.delta?.type === "arguments_delta")) { const call = calls.get(integer(event.index)); const fragment = typeof event.delta.partial_arguments === "string" ? event.delta.partial_arguments : typeof event.delta.arguments === "string" ? event.delta.arguments : null; if (!call || fragment === null) { yield { kind: "failed", error: protocol("orphan_tool_delta") }; return; } call.json += fragment; yield { kind: "tool_call_input_delta", callId: call.callId, jsonFragment: fragment }; }
        else if (eventType === "step.stop") { const call = calls.get(integer(event.index)); if (call) { let args: Record<string, unknown>; try { args = JSON.parse(call.json || "{}"); } catch { yield { kind: "failed", error: protocol("invalid_tool_arguments") }; return; } yield { kind: "tool_call_complete", callId: call.callId, toolName: call.name, input: args }; calls.delete(integer(event.index)); } const usage = geminiUsage(event.usage); if (usage) yield { kind: "usage", mode: "snapshot", final: false, usage }; }
        else if (eventType === "interaction.completed" || eventType === "interaction.complete") { const model = normalizeModel(event.interaction?.model); if (!started || (model && model !== invocation.binding.upstreamModelId)) { yield { kind: "failed", error: protocol("actual_model_mismatch") }; return; } const usage = geminiUsage(event.interaction?.usage); if (usage) yield { kind: "usage", mode: "snapshot", final: true, usage }; terminal = true; yield { kind: "completed", reason: sawTool || event.interaction?.status === "requires_action" ? "tool_call" : "stop" }; return; }
        else if (eventType === "interaction.failed" || eventType === "error") { terminal = true; yield { kind: "failed", error: providerFailure(event.error ?? event.interaction?.error) }; return; }
      }
      if (!terminal) yield { kind: "failed", error: protocol("stream_incomplete") };
    } catch (error) { if (scope.timedOut()) yield { kind: "failed", error: fail("timeout", "provider_timeout", true) }; else if (invocation.signal?.aborted || isAbort(error)) yield { kind: "cancelled" }; else yield { kind: "failed", error: fail("upstream_error", "provider_unavailable", true) }; }
    finally { scope.cleanup(); }
  }
}

/** Uses the stateless Interactions form: Atlas sends bounded history and store=false. */
export function buildGeminiInteractionsRequest(invocation: AtlasProviderInvocation) { return buildBody(invocation); }
function buildBody(invocation: AtlasProviderInvocation) { const system = invocation.prompt.messages.filter((message) => message.role === "system").flatMap((message) => textBlocks(message.content)).join("\n"); return { model: invocation.binding.upstreamModelId, input: invocation.prompt.messages.filter((message) => message.role !== "system").map(toGeminiInput), stream: true, store: false, ...(system ? { system_instruction: system } : {}), generation_config: { max_output_tokens: invocation.prompt.maxOutputTokens }, ...(invocation.prompt.tools?.length ? { tools: invocation.prompt.tools.map((tool) => ({ type: "function", name: tool.name, description: tool.description, parameters: tool.inputSchema })) } : {}) }; }
function toGeminiInput(message: AtlasModelMessage) { return { type: message.role === "assistant" ? "model_output" : message.role === "tool" ? "function_result" : "user_input", content: message.content.map((block) => block.type === "text" ? { type: "text", text: block.text } : block.type === "tool_use" ? { type: "function_call", id: block.callId, name: block.toolName, arguments: block.input } : { type: "function_result", id: block.callId, name: block.toolName, result: block.result, is_error: block.isError === true }) }; }
function textBlocks(content: readonly AtlasContentBlock[]): string[] { return content.flatMap((block) => block.type === "text" ? [block.text] : []); }
function geminiUsage(value: any): AtlasProviderUsage | null { if (!value || typeof value !== "object") return null; const cached = finite(value.total_cached_tokens ?? value.cached_tokens); const reasoning = finite(value.total_thought_tokens ?? value.thought_tokens); const input = finite(value.total_input_tokens ?? value.input_tokens); const output = finite(value.total_output_tokens ?? value.output_tokens); return { inputTokens: input === undefined ? undefined : Math.max(0, input - (cached ?? 0)), outputTokens: output === undefined ? undefined : Math.max(0, output - (reasoning ?? 0)), cacheReadTokens: cached, reasoningTokens: reasoning }; }
function providerFailure(error: any): AtlasProviderError { const code = nonEmpty(error?.code ?? error?.status) ?? "provider_error"; if (code.toLowerCase().includes("quota")) return fail("quota_exhausted", "quota_exhausted", false); if (code.toLowerCase().includes("safety")) return fail("safety_block", "safety_block", false); return fail("upstream_error", code.slice(0, 100), true); }
function validate(invocation: AtlasProviderInvocation, adapter: GeminiModelProvider): AtlasProviderError | null { const b = invocation.binding; if (b.providerId !== adapter.providerId || b.adapterId !== adapter.adapterId || b.adapterVersion !== adapter.adapterVersion || b.status !== "available" || !b.capabilities.streaming) return fail("invalid_request", "binding_adapter_mismatch", false); if (invocation.credential.ownerId !== b.credentialOwnerId || !invocation.credential.secret.trim()) return fail("authentication", "credential_binding_mismatch", false); return null; }
function httpError(status: number): AtlasProviderError { if (status === 400) return fail("invalid_request", "invalid_request", false); if (status === 401) return fail("authentication", "authentication_failed", false); if (status === 403) return fail("permission", "permission_denied", false); if (status === 404) return fail("model_unavailable", "model_unavailable", false); if (status === 429) return fail("rate_limited", "rate_limited", true); if (status >= 500) return fail("overloaded", "provider_overloaded", true); return fail("upstream_error", `provider_http_${status}`, false); }
function protocol(code: string): AtlasProviderError { return fail(code === "stream_incomplete" ? "stream_incomplete" : "protocol_error", code, false); }
function fail(errorClass: AtlasProviderError["errorClass"], code: string, retryable: boolean): AtlasProviderError { return { errorClass, code, safeMessage: "The Atlas provider request could not be completed.", retryable }; }
function normalizeModel(value: unknown): string | null { const result = nonEmpty(value); return result?.replace(/^models\//, "") ?? null; } function required(value: unknown): string { const result = nonEmpty(value); if (!result) throw new Error("missing_provider_identifier"); return result; } function nonEmpty(value: unknown): string | null { return typeof value === "string" && value.trim() ? value : null; } function integer(value: unknown): number { return typeof value === "number" && Number.isInteger(value) ? value : -1; } function finite(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : undefined; }
async function* readSse(body: ReadableStream<Uint8Array>): AsyncGenerator<{ event: string; data: string }> { const reader = body.getReader(); const decoder = new TextDecoder(); let buffer = ""; try { while (true) { const read = await reader.read(); buffer += decoder.decode(read.value, { stream: !read.done }); const parts = buffer.split(/\r?\n\r?\n/); buffer = parts.pop() ?? ""; for (const part of parts) { const event = part.split(/\r?\n/).find((line) => line.startsWith("event:"))?.slice(6).trim() ?? ""; const data = part.split(/\r?\n/).filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trimStart()).join("\n"); yield { event, data }; } if (read.done) break; } } finally { reader.releaseLock(); } }
function requestScope(parent: AbortSignal | undefined, timeoutMs: number) { const controller = new AbortController(); let timeout = false; const abort = () => controller.abort(parent?.reason); parent?.addEventListener("abort", abort, { once: true }); const timer = setTimeout(() => { timeout = true; controller.abort(); }, timeoutMs); return { signal: controller.signal, timedOut: () => timeout, cleanup: () => { clearTimeout(timer); parent?.removeEventListener("abort", abort); } }; }
function isAbort(error: unknown): boolean { return error instanceof DOMException && error.name === "AbortError"; }
