import {createHash} from "node:crypto";
import type {AuditEvent} from "@athyper/server-contract-audit";

export interface AuditIntegrityIssue {readonly code:"ORDER_VIOLATION"|"DUPLICATE_EVENT"|"PREVIOUS_HASH_MISMATCH"|"EVENT_HASH_MISMATCH"|"CHAIN_METADATA_INCOMPLETE"|"CHAIN_METADATA_MISSING";readonly eventId:string;readonly message:string;}
export interface AuditIntegrityDiagnostic {readonly valid:boolean;readonly verificationStatus:"verified"|"partial"|"unsupported";readonly eventCount:number;readonly snapshotHash:string;readonly chainHead?:string;readonly chainedEventCount:number;readonly issues:readonly AuditIntegrityIssue[];}

/** Incremental verifier suitable for large audit exports; raw metadata and payloads are never retained. */
export function createAuditIntegrityVerifier(options:{readonly precedingHash?:string}={}){const snapshot=createHash("sha256"),seen=new Set<string>(),issues:AuditIntegrityIssue[]=[];let count=0,chained=0,previousCoordinate="",chainHead:string|undefined;const genesis="0".repeat(64);return{
  append(event:AuditEvent){const coordinate=`${event.occurredAt}\u0000${event.id}`;if(previousCoordinate&&coordinate<previousCoordinate)issues.push(issue("ORDER_VIOLATION",event.id,"Events are not in occurredAt/id order"));previousCoordinate=coordinate;if(seen.has(event.id))issues.push(issue("DUPLICATE_EVENT",event.id,"Event id occurs more than once"));seen.add(event.id);const canonical=stableJson(event);snapshot.update(canonical);count++;const integrity=integrityMetadata(event);if(!integrity){issues.push(issue("CHAIN_METADATA_MISSING",event.id,"Chain verification requires integrity metadata"));return;}if(!integrity.previousHash||!integrity.eventHash){issues.push(issue("CHAIN_METADATA_INCOMPLETE",event.id,"Integrity metadata requires previousHash and eventHash"));return;}const expected=chainHead??options.precedingHash??genesis;if(integrity.previousHash!==expected)issues.push(issue("PREVIOUS_HASH_MISMATCH",event.id,"Event does not continue the preceding anchor or genesis hash"));const calculated=createHash("sha256").update(`${integrity.previousHash}\n${stableJson(withoutIntegrity(event))}`).digest("hex");if(calculated!==integrity.eventHash)issues.push(issue("EVENT_HASH_MISMATCH",event.id,"Stored event hash does not match canonical event content"));chainHead=integrity.eventHash;chained++;},
  finish():AuditIntegrityDiagnostic{const verificationStatus=count===0||chained===0?"unsupported":chained<count?"partial":"verified";return Object.freeze({valid:issues.length===0&&verificationStatus==="verified",verificationStatus,eventCount:count,snapshotHash:snapshot.digest("hex"),...(chainHead?{chainHead}:{}),chainedEventCount:chained,issues:Object.freeze([...issues])});}
};}
function integrityMetadata(event:AuditEvent):{previousHash?:string;eventHash?:string}|undefined{const value=event.metadata?.["integrity"];if(!value||typeof value!=="object"||Array.isArray(value))return undefined;const row=value as Record<string,unknown>;return{...(typeof row["previousHash"]==="string"?{previousHash:row["previousHash"]}:{}),...(typeof row["eventHash"]==="string"?{eventHash:row["eventHash"]}:{})};}
function withoutIntegrity(event:AuditEvent):unknown{if(!event.metadata||!("integrity" in event.metadata))return event;const {integrity:_integrity,...metadata}=event.metadata;return{...event,metadata};}
function issue(code:AuditIntegrityIssue["code"],eventId:string,message:string):AuditIntegrityIssue{return{code,eventId,message};}
function stableJson(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stableJson).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stableJson(item)}`).join(",")}}`;}
