-- ============================================================================
-- public/00_bootstrap.sql
-- Concept: Public Bootstrap — no pre-table functions required for this schema
-- Depends on: 01_schemas/001_schemas.sql
-- Note: No bootstrap functions required for the public schema.
-- ============================================================================
