-- 099_phase1a_entity_correction.sql
-- Phase 1a: Canonical platform entity metadata backfill across control, document, master, shared schemas.
--
-- Scope rule:
--   tenant_id IS NULL = platform standard metadata, safe for seed repair.
--   tenant_id IS NOT NULL = tenant override/customisation, never touched here.
--
-- SAFE UPDATE only — patches slug, entity_short, entity_class, governance_level,
-- security_tier, mutability, mapping_mode, label_singular, label_plural.
-- Does NOT rename entity_code or name on existing rows (Phase 1b handles that).
-- New platform rows are inserted with table-name-only name/entity_code/slug.
--
-- Lookup value mappings applied:
--   governance_level : audit_only → lite  |  light → standard
--   security_tier    : sensitive  → tenant_critical  |  business → operational
--   entity_class     : SHARED → REFERENCE
--
-- Idempotent: ON CONFLICT (table_schema, table_name) DO UPDATE

DO $$
DECLARE
    v_su  uuid := '00000000-0000-0000-0000-000000000000';
    v_fnd uuid;
    v_acc uuid;
    v_count integer;
BEGIN
    SELECT id INTO v_fnd FROM shared.module WHERE code = 'FND';
    SELECT id INTO v_acc FROM shared.module WHERE code = 'ACC';

    -- ── Slug backfill for rows still missing one ───────────────────────────────
    UPDATE control.entity
       SET slug       = replace(lower(table_name), '_', '-'),
           updated_at = now(),
           updated_by = v_su
     WHERE tenant_id IS NULL
       AND slug IS NULL
       AND table_schema IN ('control', 'document', 'master', 'shared');

    -- ── Canonical metadata upsert ──────────────────────────────────────────────
    -- Columns: tbl_schema, tbl_name, entity_short, entity_class,
    --          gov_level, sec_tier, mutab, label_s, label_p, backing
    WITH corrections (tbl_schema, tbl_name, entity_short, entity_class,
                      gov_level, sec_tier, mutab, label_s, label_p, backing) AS (VALUES

        -- ── control schema ────────────────────────────────────────────────────
        ('control','tax_group',                            'TG',     'CONTROL','full',  'operational',    'controlled','Tax Group',                           'Tax Groups',                           'table'),
        ('control','formula_expression',                   'FE',     'CONTROL','full',  'config',         'controlled','Formula',                             'Formulas',                             'table'),
        ('control','lifecycle',                            'LIFE',   'CONTROL','lite',  'platform_critical','locked', 'Lifecycle',                            'Lifecycles',                           'table'),
        ('control','notification_provider',                'NP',     'CONTROL','lite',  'platform_critical','locked', 'Notification Provider',                'Notification Providers',               'table'),
        ('control','notification_routing_rule',            'NRR',    'CONTROL','lite',  'platform_critical','locked', 'Notification Routing Rule',            'Notification Routing Rules',           'table'),
        ('control','outbox_routing_rule',                  'ORR',    'CONTROL','lite',  'platform_critical','locked', 'Outbox Routing Rule',                  'Outbox Routing Rules',                 'table'),
        ('control','lookup_value',                         'LV',     'CONTROL','lite',  'platform_critical','locked', 'Lookup Value',                         'Lookup Values',                        'table'),
        ('control','notification_template',                'NT',     'CONTROL','lite',  'platform_critical','locked', 'Notification Template',                'Notification Templates',               'table'),
        ('control','hook_action_registry',                 'HAR',    'CONTROL','lite',  'platform_critical','locked', 'Hook Action',                          'Hook Actions',                         'table'),
        ('control','workflow_definition',                  'WD',     'CONTROL','lite',  'platform_critical','locked', 'Workflow Definition',                  'Workflow Definitions',                 'table'),
        ('control','lifecycle_timer_policy',               'LTP',    'CONTROL','lite',  'platform_critical','locked', 'Lifecycle Timer Policy',               'Lifecycle Timer Policies',             'table'),
        ('control','lifecycle_state',                      'LS',     'CONTROL','lite',  'platform_critical','locked', 'Lifecycle State',                      'Lifecycle States',                     'table'),
        ('control','entity',                               'ENTI',   'CONTROL','lite',  'platform_critical','locked', 'Entity',                               'Entities',                             'table'),
        ('control','budget_check_config',                  'BCC',    'CONTROL','lite',  'platform_critical','locked', 'Budget Check Configuration',           'Budget Check Configurations',          'table'),
        ('control','policy_rule',                          'PR',     'CONTROL','lite',  'platform_critical','locked', 'Policy Rule',                          'Policy Rules',                         'table'),
        ('control','field_group_member',                   'FGM',    'CONTROL','lite',  'platform_critical','locked', 'Field Group Member',                   'Field Group Members',                  'table'),
        ('control','field_security_policy',                'FSP',    'CONTROL','lite',  'platform_critical','locked', 'Field Security Policy',                'Field Security Policies',              'table'),
        ('control','overlay',                              'OVER',   'CONTROL','lite',  'platform_critical','locked', 'Overlay',                              'Overlays',                             'table'),
        ('control','entity_operation',                     'EO',     'CONTROL','lite',  'platform_critical','locked', 'Entity Operation',                     'Entity Operations',                    'table'),
        ('control','entity_lifecycle',                     'EL',     'CONTROL','lite',  'platform_critical','locked', 'Entity Lifecycle Binding',             'Entity Lifecycle Bindings',            'table'),
        ('control','overlay_change',                       'OC',     'CONTROL','lite',  'platform_critical','locked', 'Overlay Change',                       'Overlay Changes',                      'table'),
        ('control','acct_profile_config',                  'APC',    'CONTROL','lite',  'platform_critical','locked', 'Accounting Profile Configuration',     'Accounting Profile Configurations',    'table'),
        ('control','transaction_flow_template',            'TFT',    'CONTROL','lite',  'platform_critical','locked', 'Transaction Flow Template',            'Transaction Flow Templates',           'table'),
        ('control','acct_profile_entry_template',          'APET',   'CONTROL','lite',  'platform_critical','locked', 'Accounting Entry Template',            'Accounting Entry Templates',           'table'),
        ('control','acct_profile_dimension_rule',          'APDR',   'CONTROL','lite',  'platform_critical','locked', 'Accounting Dimension Rule',            'Accounting Dimension Rules',           'table'),
        ('control','acct_profile_book_rule',               'APBR',   'CONTROL','lite',  'platform_critical','locked', 'Accounting Book Rule',                 'Accounting Book Rules',                'table'),
        ('control','acct_profile_commitment_config',       'APCC',   'CONTROL','lite',  'platform_critical','locked', 'Accounting Commitment Configuration',  'Accounting Commitment Configurations', 'table'),
        ('control','intent_to_accounting_profile_rule',    'ITAPR',  'CONTROL','lite',  'platform_critical','locked', 'Intent-to-Profile Rule',               'Intent-to-Profile Rules',              'table'),
        ('control','entity_policy',                        'EP',     'CONTROL','lite',  'platform_critical','locked', 'Entity Policy',                        'Entity Policies',                      'table'),
        ('control','dimension_policy_allowed_value',       'DPAV',   'CONTROL','lite',  'platform_critical','locked', 'Dimension Policy Allowed Value',       'Dimension Policy Allowed Values',      'table'),
        ('control','intent_profile_override',              'IPO',    'CONTROL','lite',  'platform_critical','locked', 'Intent Profile Override',              'Intent Profile Overrides',             'table'),
        ('control','dimension_policy',                     'DP',     'CONTROL','lite',  'platform_critical','locked', 'Dimension Policy',                     'Dimension Policies',                   'table'),
        ('control','wht_threshold_config',                 'WTC',    'CONTROL','lite',  'platform_critical','locked', 'Withholding Tax Threshold',            'Withholding Tax Thresholds',           'table'),
        ('control','planning_driver_assumption',           'PDA',    'CONTROL','lite',  'platform_critical','locked', 'Planning Driver Assumption',           'Planning Driver Assumptions',          'table'),
        ('control','forecast_line',                        'FL',     'CONTROL','lite',  'platform_critical','locked', 'Forecast Line',                        'Forecast Lines',                       'table'),
        ('control','planning_driver_version',              'PDV',    'CONTROL','lite',  'platform_critical','locked', 'Planning Driver Version',              'Planning Driver Versions',             'table'),
        ('control','planning_driver',                      'PD',     'CONTROL','lite',  'platform_critical','locked', 'Planning Driver',                      'Planning Drivers',                     'table'),
        ('control','forecast_budget_bridge',               'FBB',    'CONTROL','lite',  'platform_critical','locked', 'Forecast-to-Budget Bridge',            'Forecast-to-Budget Bridges',           'table'),
        ('control','tax_group_component',                  'TGC',    'CONTROL','lite',  'platform_critical','locked', 'Tax Group Component',                  'Tax Group Components',                 'table'),
        ('control','feature_flag',                         'FF',     'CONTROL','lite',  'platform_critical','locked', 'Feature Flag',                         'Feature Flags',                        'table'),
        ('control','metadata_change_application_log',      'MCAL',   'CONTROL','lite',  'platform_critical','locked', 'Metadata Change Application Log',      'Metadata Change Application Logs',     'table'),
        ('control','content_quota',                        'CQ',     'CONTROL','lite',  'platform_critical','locked', 'Content Quota',                        'Content Quotas',                       'table'),
        ('control','entity_flow_section',                  'EFS',    'CONTROL','lite',  'platform_critical','locked', 'Entity Flow Section',                  'Entity Flow Sections',                 'table'),
        ('control','tenant_blueprint_application',         'TBA',    'CONTROL','lite',  'platform_critical','locked', 'Tenant Blueprint Application',         'Tenant Blueprint Applications',        'table'),
        ('control','cron_schedule',                        'CS',     'CONTROL','lite',  'platform_critical','locked', 'Cron Schedule',                        'Cron Schedules',                       'table'),
        ('control','ai_action_policy',                     'AAP',    'CONTROL','lite',  'platform_critical','locked', 'AI Action Policy',                     'AI Action Policies',                   'table'),
        ('control','blueprint_registry',                   'BR',     'CONTROL','lite',  'platform_critical','locked', 'Blueprint',                            'Blueprints',                           'table'),
        ('control','match_tolerance_config',               'MTC',    'CONTROL','lite',  'platform_critical','locked', 'Match Tolerance Configuration',        'Match Tolerance Configurations',       'table'),
        ('control','lookup_domain',                        'LD',     'CONTROL','lite',  'platform_critical','locked', 'Lookup Domain',                        'Lookup Domains',                       'table'),
        ('control','lifecycle_transition_gate',            'LTG',    'CONTROL','lite',  'platform_critical','locked', 'Lifecycle Transition Gate',            'Lifecycle Transition Gates',           'table'),
        ('control','workflow_template',                    'WT',     'CONTROL','lite',  'platform_critical','locked', 'Workflow Template',                    'Workflow Templates',                   'table'),
        ('control','mfa_config',                           'MC',     'CONTROL','lite',  'platform_critical','locked', 'MFA Configuration',                   'MFA Configurations',                   'table'),
        ('control','lifecycle_transition_hook',            'LTH',    'CONTROL','lite',  'platform_critical','locked', 'Lifecycle Transition Hook',            'Lifecycle Transition Hooks',           'table'),
        ('control','lifecycle_hook_override',              'LHO',    'CONTROL','lite',  'platform_critical','locked', 'Lifecycle Hook Override',              'Lifecycle Hook Overrides',             'table'),
        ('control','workflow_template_stage',              'WTS',    'CONTROL','lite',  'platform_critical','locked', 'Workflow Stage Definition',            'Workflow Stage Definitions',           'table'),
        ('control','lifecycle_transition',                 'LT',     'CONTROL','lite',  'platform_critical','locked', 'Lifecycle Transition',                 'Lifecycle Transitions',                'table'),
        ('control','transaction_event_catalog',            'TEC',    'CONTROL','lite',  'platform_critical','locked', 'Transaction Event',                    'Transaction Events',                   'table'),
        ('control','entity_relation',                      'ER',     'CONTROL','lite',  'platform_critical','locked', 'Entity Relation',                      'Entity Relations',                     'table'),
        ('control','workflow_sla_policy',                  'WSP',    'CONTROL','lite',  'platform_critical','locked', 'Workflow SLA Policy',                  'Workflow SLA Policies',                'table'),
        ('control','acct_profile_settlement_config',       'APSC',   'CONTROL','lite',  'platform_critical','locked', 'Accounting Settlement Configuration',  'Accounting Settlement Configurations', 'table'),
        ('control','workflow_template_rule',               'WTR',    'CONTROL','lite',  'platform_critical','locked', 'Workflow Template Rule',               'Workflow Template Rules',              'table'),
        ('control','book_posting_rule',                    'BPR',    'CONTROL','lite',  'platform_critical','locked', 'Book Posting Rule',                    'Book Posting Rules',                   'table'),
        ('control','acct_profile_revenue_config',          'APRC',   'CONTROL','lite',  'platform_critical','locked', 'Accounting Revenue Configuration',     'Accounting Revenue Configurations',    'table'),
        ('control','acct_profile_event',                   'APE',    'CONTROL','lite',  'platform_critical','locked', 'Accounting Profile Event',             'Accounting Profile Events',            'table'),
        ('control','tax_rate_schedule',                    'TRS',    'CONTROL','lite',  'platform_critical','locked', 'Tax Rate Schedule',                    'Tax Rate Schedules',                   'table'),
        ('control','metadata_change_request',              'MCR',    'CONTROL','lite',  'platform_critical','locked', 'Metadata Change Request',              'Metadata Change Requests',             'table'),
        ('control','connector_type',                       'CT',     'CONTROL','lite',  'platform_critical','locked', 'Connector Type',                       'Connector Types',                      'table'),
        ('control','asset_class_book_policy',              'ACBP',   'CONTROL','lite',  'platform_critical','locked', 'Asset Class Book Policy',              'Asset Class Book Policies',            'table'),
        ('control','rounding_rule',                        'RR',     'CONTROL','lite',  'platform_critical','locked', 'Rounding Rule',                        'Rounding Rules',                       'table'),
        ('control','asset_class_book_policy_template',     'ACBPT',  'CONTROL','lite',  'platform_critical','locked', 'Asset Class Book Policy Template',     'Asset Class Book Policy Templates',    'table'),
        ('control','policy_rule_version',                  'PRV',    'CONTROL','lite',  'platform_critical','locked', 'Policy Rule Version',                  'Policy Rule Versions',                 'table'),
        ('control','entity_field',                         'EF',     'CONTROL','lite',  'platform_critical','locked', 'Entity Field',                         'Entity Fields',                        'table'),
        ('control','entity_version',                       'EV',     'CONTROL','lite',  'platform_critical','locked', 'Entity Version',                       'Entity Versions',                      'table'),
        ('control','ai_confidence_threshold',              'ACT',    'CONTROL','lite',  'platform_critical','locked', 'AI Confidence Threshold',              'AI Confidence Thresholds',             'table'),
        ('control','policy_test_case',                     'PTC',    'CONTROL','lite',  'platform_critical','locked', 'Policy Test Case',                     'Policy Test Cases',                    'table'),
        ('control','entity_flow',                          'ENFL',   'CONTROL','lite',  'platform_critical','locked', 'Entity Flow',                          'Entity Flows',                         'table'),
        ('control','entity_flow_step',                     'ENFLST', 'CONTROL','lite',  'platform_critical','locked', 'Entity Flow Step',                     'Entity Flow Steps',                    'table'),
        ('control','ai_drift_baseline',                    'ADB',    'CONTROL','lite',  'platform_critical','locked', 'AI Drift Baseline',                    'AI Drift Baselines',                   'table'),
        ('control','policy_definition',                    'PODE',   'CONTROL','lite',  'platform_critical','locked', 'Policy Definition',                    'Policy Definitions',                   'table'),
        ('control','entity_flow_field',                    'EFF',    'CONTROL','lite',  'platform_critical','locked', 'Entity Flow Field',                    'Entity Flow Fields',                   'table'),
        ('control','parameter_definition',                 'PADE',   'CONTROL','lite',  'platform_critical','locked', 'Parameter Definition',                 'Parameter Definitions',                'table'),
        ('control','intake_idempotency',                   'II',     'CONTROL','lite',  'platform_critical','locked', 'Intake Idempotency Key',               'Intake Idempotency Keys',              'table'),
        ('control','record_edit_lock',                     'REL',    'CONTROL','lite',  'platform_critical','locked', 'Record Edit Lock',                     'Record Edit Locks',                    'table'),
        ('control','planning_driver_formula',              'PDF',    'CONTROL','lite',  'platform_critical','locked', 'Planning Driver Formula',              'Planning Driver Formulas',             'table'),
        ('control','bank_format_rule',                     'BFR',    'CONTROL','lite',  'platform_critical','locked', 'Bank Format Rule',                     'Bank Format Rules',                    'table'),
        ('control','payment_method_company_policy',        'PMCP',   'CONTROL','lite',  'platform_critical','locked', 'Payment Method Company Policy',        'Payment Method Company Policies',      'table'),
        ('control','bank_interface_profile',               'BIP',    'CONTROL','lite',  'platform_critical','locked', 'Bank Interface Profile',               'Bank Interface Profiles',              'table'),
        ('control','payment_settlement_rule',              'PSR',    'CONTROL','lite',  'platform_critical','locked', 'Payment Settlement Rule',              'Payment Settlement Rules',             'table'),
        ('control','payment_method_interface_binding',     'PMIB',   'CONTROL','lite',  'platform_critical','locked', 'Payment Method Interface Binding',     'Payment Method Interface Bindings',    'table'),
        ('control','v_active_flow_templates',              'AFT',    'CONTROL','lite',  'platform_critical','locked', 'Active Flow Templates',                'Active Flow Templates',                'view'),
        ('control','v_blueprint_catalogue',                'BC',     'CONTROL','lite',  'platform_critical','locked', 'Blueprint Catalogue',                  'Blueprint Catalogues',                 'view'),
        ('control','entity_class_profile',                 'ECP',    'CONTROL','lite',  'platform_critical','locked', 'Entity Class Profile',                 'Entity Class Profiles',                'table'),
        ('control','field_group',                          'FG',     'CONTROL','lite',  'platform_critical','locked', 'Field Group',                          'Field Groups',                         'table'),
        ('control','entity_publish_state',                 'EPS',    'CONTROL','lite',  'platform_critical','locked', 'Entity Publish State',                 'Entity Publish States',                'table'),
        ('control','commodity_classification_config',      'CCC',    'CONTROL','lite',  'platform_critical','locked', 'Commodity Classification Configuration','Commodity Classification Configurations','table'),
        ('control','v_acct_profile_full',                  'APF',    'CONTROL','lite',  'platform_critical','locked', 'Accounting Profile Detail',            'Accounting Profile Details',           'view'),
        ('control','formula_expression_version',           'FEV',    'CONTROL','full',  'config',         'locked',   'Formula Version',                      'Formula Versions',                     'table'),
        ('control','rate_table',                           'RT',     'CONTROL','full',  'config',         'controlled','Rate Table',                          'Rate Tables',                          'table'),
        ('control','rate_table_row',                       'RTR',    'CONTROL','full',  'config',         'controlled','Rate Table Row',                      'Rate Table Rows',                      'table'),
        ('control','commodity_classification_to_intent_rule','CCTIR','CONTROL','full',  'operational',    'controlled','Classification-to-Intent Rule',       'Classification-to-Intent Rules',       'table'),
        ('control','commodity_code_to_category_rule',      'CCTCR',  'CONTROL','full',  'operational',    'controlled','Commodity Routing Rule',              'Commodity Routing Rules',              'table'),
        ('control','commodity_category_buy_policy',        'CCBP',   'CONTROL','full',  'operational',    'controlled','Commodity Buy Policy',                'Commodity Buy Policies',               'table'),
        ('control','supplier_posting_override',            'SPO',    'CONTROL','lite',  'platform_critical','locked', 'Supplier Posting Override',            'Supplier Posting Overrides',           'table'),
        ('control','commodity_category_sell_policy',       'CCSP',   'CONTROL','full',  'operational',    'controlled','Commodity Sell Policy',               'Commodity Sell Policies',              'table'),
        ('control','commodity_category_inventory_policy',  'CCIP',   'CONTROL','full',  'operational',    'controlled','Commodity Inventory Policy',          'Commodity Inventory Policies',         'table'),

        -- ── document schema ───────────────────────────────────────────────────
        ('document','journal_entry',                       'JE',     'DOCUMENT','lite', 'tenant_critical','locked',   'Journal Entry',                        'Journal Entries',                      'table'),
        ('document','purchase_requisition_line',           'PRL',    'DOCUMENT','lite', 'tenant_critical','locked',   'Purchase Requisition Line',            'Purchase Requisition Lines',           'table'),
        ('document','purchase_requisition',                'PRD',    'DOCUMENT','lite', 'tenant_critical','locked',   'Purchase Requisition',                 'Purchase Requisitions',                'table'),
        ('document','purchase_order_confirmation_line',    'POCL',   'DOCUMENT','lite', 'tenant_critical','locked',   'PO Confirmation Line',                 'PO Confirmation Lines',                'table'),
        ('document','commitment_release_allocation',       'CRA',    'DOCUMENT','lite', 'tenant_critical','locked',   'Commitment Release Allocation',        'Commitment Release Allocations',       'table'),
        ('document','purchase_invoice_line',               'PIL',    'DOCUMENT','full', 'tenant_critical','controlled','Purchase Invoice Line',               'Purchase Invoice Lines',               'table'),
        ('document','delivery_note_line',                  'DNL',    'DOCUMENT','lite', 'tenant_critical','locked',   'Delivery Note Line',                   'Delivery Note Lines',                  'table'),
        ('document','goods_receipt_line',                  'GRL',    'DOCUMENT','lite', 'tenant_critical','locked',   'Goods Receipt Line',                   'Goods Receipt Lines',                  'table'),
        ('document','journal_line',                        'JL',     'DOCUMENT','lite', 'tenant_critical','locked',   'Journal Line',                         'Journal Lines',                        'table'),
        ('document','service_entry_sheet_line',            'SESL',   'DOCUMENT','lite', 'tenant_critical','locked',   'Service Entry Sheet Line',             'Service Entry Sheet Lines',            'table'),
        ('document','journal_line_reference',              'JLR',    'DOCUMENT','lite', 'tenant_critical','locked',   'Journal Line Reference',               'Journal Line References',              'table'),
        ('document','depreciation_run_line',               'DRL',    'DOCUMENT','lite', 'tenant_critical','locked',   'Depreciation Run Line',                'Depreciation Run Lines',               'table'),
        ('document','commitment_line',                     'CL',     'DOCUMENT','lite', 'tenant_critical','locked',   'Commitment Line',                      'Commitment Lines',                     'table'),
        ('document','payment_entry_allocation',            'PEA',    'DOCUMENT','lite', 'tenant_critical','locked',   'Payment Allocation',                   'Payment Allocations',                  'table'),
        ('document','stocktake_line',                      'SL',     'DOCUMENT','lite', 'tenant_critical','locked',   'Stocktake Line',                       'Stocktake Lines',                      'table'),
        ('document','bank_statement_line',                 'BSL',    'DOCUMENT','lite', 'tenant_critical','locked',   'Bank Statement Line',                  'Bank Statement Lines',                 'table'),
        ('document','bank_recon_case_line',                'BRCL',   'DOCUMENT','lite', 'tenant_critical','locked',   'Bank Reconciliation Case Line',        'Bank Reconciliation Case Lines',       'table'),
        ('document','accounting_distribution',             'AD',     'DOCUMENT','full', 'tenant_critical','locked',   'Account Assignment Split',             'Account Assignment Splits',            'table'),
        ('document','purchase_order',                      'PO',     'DOCUMENT','lite', 'tenant_critical','locked',   'Purchase Order',                       'Purchase Orders',                      'view'),
        ('document','delivery_note',                       'DN',     'DOCUMENT','lite', 'tenant_critical','locked',   'Delivery Note',                        'Delivery Notes',                       'table'),
        ('document','commitment_party_snapshot',           'CPS',    'DOCUMENT','lite', 'tenant_critical','locked',   'Commitment Party Snapshot',            'Commitment Party Snapshots',           'table'),
        ('document','invoice_address_snapshot',            'IAS',    'DOCUMENT','lite', 'tenant_critical','locked',   'Invoice Address Snapshot',             'Invoice Address Snapshots',            'table'),
        ('document','doc_attachment',                      'DA',     'DOCUMENT','lite', 'tenant_critical','locked',   'Document Attachment',                  'Document Attachments',                 'table'),
        ('document','depreciation_schedule',               'DS',     'DOCUMENT','lite', 'tenant_critical','locked',   'Depreciation Schedule',                'Depreciation Schedules',               'table'),
        ('document','commitment_address_snapshot',         'CAS',    'DOCUMENT','lite', 'tenant_critical','locked',   'Commitment Address Snapshot',          'Commitment Address Snapshots',         'table'),
        ('document','invoice_party_snapshot',              'IPS',    'DOCUMENT','lite', 'tenant_critical','locked',   'Invoice Party Snapshot',               'Invoice Party Snapshots',              'table'),
        ('document','invoice_bank_snapshot',               'IBS',    'DOCUMENT','lite', 'tenant_critical','locked',   'Invoice Bank Snapshot',                'Invoice Bank Snapshots',               'table'),
        ('document','invoice_tax_snapshot',                'ITS',    'DOCUMENT','lite', 'tenant_critical','locked',   'Invoice Tax Snapshot',                 'Invoice Tax Snapshots',                'table'),
        ('document','intercompany_agreement',              'IA',     'DOCUMENT','lite', 'tenant_critical','locked',   'Intercompany Agreement',               'Intercompany Agreements',              'table'),
        ('document','purchase_order_confirmation',         'POC',    'DOCUMENT','lite', 'tenant_critical','locked',   'PO Confirmation',                      'PO Confirmations',                     'table'),
        ('document','import_request_chunk',                'IRC',    'DOCUMENT','lite', 'tenant_critical','locked',   'Import Chunk',                         'Import Chunks',                        'table'),
        ('document','goods_receipt',                       'GR',     'DOCUMENT','lite', 'tenant_critical','locked',   'Goods Receipt',                        'Goods Receipts',                       'table'),
        ('document','import_request',                      'IR',     'DOCUMENT','lite', 'tenant_critical','locked',   'Import Request',                       'Import Requests',                      'table'),
        ('document','bank_statement',                      'BS',     'DOCUMENT','lite', 'tenant_critical','locked',   'Bank Statement',                       'Bank Statements',                      'table'),
        ('document','party_advance_balance',               'PAB',    'DOCUMENT','lite', 'tenant_critical','locked',   'Party Advance Balance',                'Party Advance Balances',               'table'),
        ('document','render_job',                          'RJ',     'DOCUMENT','lite', 'tenant_critical','locked',   'Render Job',                           'Render Jobs',                          'table'),
        ('document','render_output',                       'RO',     'DOCUMENT','lite', 'tenant_critical','locked',   'Render Output',                        'Render Outputs',                       'table'),
        ('document','workflow_request',                    'WR',     'DOCUMENT','lite', 'tenant_critical','locked',   'Workflow Request',                     'Workflow Requests',                    'table'),
        ('document','workflow_stage',                      'WS',     'DOCUMENT','lite', 'tenant_critical','locked',   'Workflow Stage',                       'Workflow Stages',                      'table'),
        ('document','fx_revaluation_run',                  'FRR',    'DOCUMENT','lite', 'tenant_critical','locked',   'FX Revaluation Run',                   'FX Revaluation Runs',                  'table'),
        ('document','forecast_scenario',                   'FS',     'DOCUMENT','lite', 'tenant_critical','locked',   'Forecast Scenario',                    'Forecast Scenarios',                   'table'),
        ('document','obligation_horizon',                  'OH',     'DOCUMENT','lite', 'tenant_critical','locked',   'Obligation Horizon',                   'Obligation Horizons',                  'table'),
        ('document','payment_term_discount_result',        'PTDR',   'DOCUMENT','lite', 'tenant_critical','locked',   'Payment Term Discount Result',         'Payment Term Discount Results',        'table'),
        ('document','attendance_adjustment_request',       'AAR',    'DOCUMENT','full', 'operational',    'controlled','Attendance Adjustment',               'Attendance Adjustments',               'table'),
        ('document','asset_transaction',                   'AT',     'DOCUMENT','lite', 'tenant_critical','locked',   'Asset Transaction',                    'Asset Transactions',                   'table'),
        ('document','payment_remittance_output',           'PRO',    'DOCUMENT','lite', 'tenant_critical','locked',   'Payment Remittance Output',            'Payment Remittance Outputs',           'table'),
        ('document','depreciation_run',                    'DR',     'DOCUMENT','lite', 'tenant_critical','locked',   'Depreciation Run',                     'Depreciation Runs',                    'table'),
        ('document','payment_term_application',            'PTA',    'DOCUMENT','lite', 'tenant_critical','locked',   'Payment Term Application',             'Payment Term Applications',            'table'),
        ('document','ic_elimination',                      'IE',     'DOCUMENT','lite', 'tenant_critical','locked',   'Intercompany Elimination',             'Intercompany Eliminations',            'table'),
        ('document','attendance_day',                      'ADD',    'DOCUMENT','full', 'operational',    'controlled','Attendance Day',                      'Attendance Days',                      'table'),
        ('document','intercompany_transaction',            'IT',     'DOCUMENT','lite', 'tenant_critical','locked',   'Intercompany Transaction',             'Intercompany Transactions',            'table'),
        ('document','stocktake',                           'ST',     'DOCUMENT','lite', 'tenant_critical','locked',   'Stocktake',                            'Stocktakes',                           'table'),
        ('document','wht_certificate',                     'WC',     'DOCUMENT','lite', 'tenant_critical','locked',   'Withholding Tax Certificate',          'Withholding Tax Certificates',         'table'),
        ('document','service_entry_sheet',                 'SES',    'DOCUMENT','lite', 'tenant_critical','locked',   'Service Entry Sheet',                  'Service Entry Sheets',                 'table'),
        ('document','invoice_match_case',                  'IMC',    'DOCUMENT','lite', 'tenant_critical','locked',   'Invoice Match Case',                   'Invoice Match Cases',                  'table'),
        ('document','command_log',                         'CLD',    'DOCUMENT','lite', 'tenant_critical','locked',   'Command Log',                          'Command Logs',                         'table'),
        ('document','hr_case',                             'HC',     'DOCUMENT','full', 'operational',    'controlled','HR Case',                             'HR Cases',                             'table'),
        ('document','netting_batch',                       'NB',     'DOCUMENT','lite', 'tenant_critical','locked',   'Netting Batch',                        'Netting Batches',                      'table'),
        ('document','bank_recon_case',                     'BRC',    'DOCUMENT','lite', 'tenant_critical','locked',   'Bank Reconciliation Case',             'Bank Reconciliation Cases',            'table'),
        ('document','commitment',                          'CO',     'DOCUMENT','lite', 'tenant_critical','locked',   'Commitment',                           'Commitments',                          'table'),
        ('document','commitment_procurement',              'CP',     'DOCUMENT','lite', 'tenant_critical','locked',   'Procurement Commitment',               'Procurement Commitments',              'table'),
        ('document','match_exception',                     'ME',     'DOCUMENT','lite', 'tenant_critical','locked',   'Match Exception',                      'Match Exceptions',                     'table'),
        ('document','leave_balance_entry',                 'LBE',    'DOCUMENT','full', 'operational',    'locked',   'Leave Balance Entry',                  'Leave Balance Entries',                'table'),
        ('document','leave_request',                       'LR',     'DOCUMENT','full', 'operational',    'controlled','Leave Request',                       'Leave Requests',                       'table'),
        ('document','offboarding_case',                    'OCD',    'DOCUMENT','full', 'operational',    'controlled','Offboarding Case',                    'Offboarding Cases',                    'table'),
        ('document','onboarding_case',                     'OCDO',   'DOCUMENT','full', 'operational',    'controlled','Onboarding Case',                     'Onboarding Cases',                     'table'),
        ('document','people_request',                      'PEPR',   'DOCUMENT','full', 'operational',    'controlled','People Request',                      'People Requests',                      'table'),
        ('document','policy_acknowledgment',               'PA',     'DOCUMENT','full', 'operational',    'locked',   'Policy Acknowledgment',                'Policy Acknowledgments',               'table'),
        ('document','shift_assignment',                    'SA',     'DOCUMENT','full', 'operational',    'controlled','Shift Assignment',                    'Shift Assignments',                    'table'),
        ('document','time_punch',                          'TP',     'DOCUMENT','full', 'operational',    'controlled','Time Punch',                          'Time Punches',                         'table'),
        ('document','compensation_assignment',             'CA',     'DOCUMENT','full', 'tenant_critical','controlled','Compensation Assignment',             'Compensation Assignments',             'table'),
        ('document','compensation_change',                 'CC',     'DOCUMENT','full', 'tenant_critical','controlled','Compensation Change',                 'Compensation Changes',                 'table'),
        ('document','employee_tax_declaration',            'ETD',    'DOCUMENT','full', 'tenant_critical','controlled','Employee Tax Declaration',            'Employee Tax Declarations',            'table'),
        ('document','employee_tax_declaration_line',       'ETDL',   'DOCUMENT','full', 'tenant_critical','controlled','Tax Declaration Line',                'Tax Declaration Lines',                'table'),
        ('document','payroll_period',                      'PP',     'DOCUMENT','full', 'tenant_critical','controlled','Payroll Period',                      'Payroll Periods',                      'table'),
        ('document','payroll_result',                      'PYRES',  'DOCUMENT','full', 'tenant_critical','locked',   'Payroll Result',                       'Payroll Results',                      'table'),
        ('document','payroll_result_line',                 'PRLD',   'DOCUMENT','full', 'tenant_critical','locked',   'Payroll Result Line',                  'Payroll Result Lines',                 'table'),
        ('document','payroll_run',                         'PYRUN',  'DOCUMENT','full', 'tenant_critical','controlled','Payroll Run',                         'Payroll Runs',                         'table'),
        ('document','payroll_run_employee',                'PRE',    'DOCUMENT','full', 'tenant_critical','controlled','Payroll Run Employee',                'Payroll Run Employees',                'table'),
        ('document','user_profile_update_request',         'UPUR',   'DOCUMENT','full', 'tenant_critical','controlled','Profile Update Request',              'Profile Update Requests',              'table'),
        ('document','purchase_invoice',                    'PI',     'DOCUMENT','full', 'tenant_critical','controlled','Purchase Invoice',                    'Purchase Invoices',                    'table'),
        ('document','payment_entry',                       'PE',     'DOCUMENT','full', 'tenant_critical','controlled','Payment Entry',                       'Payment Entries',                      'table'),

        -- ── master schema ─────────────────────────────────────────────────────
        ('master','company_code_chart_assignment',         'CCCA',   'MASTER', 'full',  'tenant_critical','controlled','COA Assignment',                      'COA Assignments',                      'table'),
        ('master','party_contact_role',                    'PCR',    'MASTER', 'standard','operational', 'controlled','Party Contact Role',                   'Party Contact Roles',                  'table'),
        ('master','notification',                          'NO',     'MASTER', 'lite',  'operational',    'locked',   'Notification',                         'Notifications',                        'table'),
        ('master','company_code_dimension_default',        'CCDD',   'MASTER', 'full',  'operational',    'controlled','Dimension Default',                   'Dimension Defaults',                   'table'),
        ('master','party_risk_assessment',                 'PRA',    'MASTER', 'full',  'tenant_critical','controlled','Party Risk Assessment',               'Party Risk Assessments',               'table'),
        ('master','v_contact_summary',                     'CSM',    'MASTER', 'lite',  'operational',    'locked',   'Contact Summary',                      'Contact Summaries',                    'view'),
        ('master','attachment_folder',                     'AF',     'MASTER', 'standard','operational', 'controlled','Attachment Folder',                    'Attachment Folders',                   'table'),
        ('master','party_risk_review_event',               'PRRE',   'MASTER', 'lite',  'tenant_critical','locked',   'Party Risk Review Event',              'Party Risk Review Events',             'table'),
        ('master','v_bank_account_link_resolved',          'BALR',   'MASTER', 'lite',  'operational',    'locked',   'Resolved Bank Account Link',           'Resolved Bank Account Links',          'view'),
        ('master','v_bank_account_resolved',               'BAR',    'MASTER', 'lite',  'operational',    'locked',   'Resolved Bank Account',                'Resolved Bank Accounts',               'view'),
        ('master','v_business_partner_governance_summary', 'BPGS',   'MASTER', 'lite',  'tenant_critical','locked',   'Business Partner Governance Summary',  'Business Partner Governance Summaries','view'),
        ('master','v_effective_principal_ui',              'EPU',    'MASTER', 'lite',  'tenant_critical','locked',   'Effective Principal UI Profile',       'Effective Principal UI Profiles',      'view'),
        ('master','v_employee',                            'EM',     'MASTER', 'lite',  'operational',    'locked',   'Employee',                             'Employees (view)',                     'view'),
        ('master','v_entity_commodity',                    'EC',     'MASTER', 'lite',  'operational',    'locked',   'Entity Commodity',                     'Entity Commodities',                   'view'),
        ('master','v_resolved_address',                    'RA',     'MASTER', 'lite',  'operational',    'locked',   'Resolved Address',                     'Resolved Addresses',                   'view'),
        ('master','v_supplier_bank_account',               'SBA',    'MASTER', 'lite',  'operational',    'locked',   'Supplier Bank Account',                'Supplier Bank Accounts',               'view'),
        ('master','v_tenant_risk_source_config',           'TRSC',   'MASTER', 'lite',  'tenant_critical','locked',   'Tenant Risk Source Config',            'Tenant Risk Source Configs (view)',     'view'),
        ('master','party_contact_person',                  'PCP',    'MASTER', 'lite',  'operational',    'locked',   'Party Contact Person',                 'Party Contact People',                 'table'),
        ('master','certification',                         'CE',     'MASTER', 'lite',  'operational',    'locked',   'Certification',                        'Certifications',                       'table'),
        ('master','supplier_block',                        'SB',     'MASTER', 'lite',  'operational',    'locked',   'Supplier Block',                       'Supplier Blocks',                      'table'),
        ('master','business_partner_network_link',         'BPNL',   'MASTER', 'lite',  'operational',    'locked',   'Business Partner Network Link',        'Business Partner Network Links',       'table'),
        ('master','party_governance_relation',             'PGR',    'MASTER', 'lite',  'operational',    'locked',   'Party Governance Relation',            'Party Governance Relations',           'table'),
        ('master','customer_app_index',                    'CAI',    'MASTER', 'lite',  'operational',    'locked',   'Customer App Index',                   'Customer App Indices',                 'table'),
        ('master','party_identifier',                      'PIM',    'MASTER', 'lite',  'operational',    'locked',   'Party Identifier',                     'Party Identifiers',                    'table'),
        ('master','tenant_feature_entitlement',            'TFE',    'MASTER', 'full',  'tenant_critical','locked',   'Feature Entitlement',                  'Feature Entitlements',                 'table'),
        ('master','party_tax_profile',                     'PTP',    'MASTER', 'lite',  'operational',    'locked',   'Party Tax Profile',                    'Party Tax Profiles',                   'table'),
        ('master','spend_category',                        'SC',     'MASTER', 'lite',  'operational',    'locked',   'Spend Category',                       'Spend Categories',                     'table'),
        ('master','customer_block',                        'CB',     'MASTER', 'lite',  'operational',    'locked',   'Customer Block',                       'Customer Blocks',                      'table'),
        ('master','customer_qualification',                'CQM',    'MASTER', 'lite',  'operational',    'locked',   'Customer Qualification',               'Customer Qualifications',              'table'),
        ('master','supplier_qualification',                'SQ',     'MASTER', 'lite',  'operational',    'locked',   'Supplier Qualification',               'Supplier Qualifications',              'table'),
        ('master','supplier_spend_category',               'SSC',    'MASTER', 'standard','operational', 'controlled','Supplier Commodity Category',          'Supplier Commodity Categories',        'table'),
        ('master','v_business_partner_app_index',          'BPAI',   'MASTER', 'lite',  'operational',    'locked',   'Business Partner App Index',           'Business Partner App Indices (view)',  'view'),
        ('master','v_business_partner_address',            'BPA',    'MASTER', 'lite',  'operational',    'locked',   'Business Partner Address',             'Business Partner Addresses (view)',    'view'),
        ('master','v_business_partner_role_summary',       'BPRS',   'MASTER', 'lite',  'operational',    'locked',   'Business Partner Role Summary',        'Business Partner Role Summaries',      'view'),
        ('master','commodity_category',                    'CCM',    'MASTER', 'full',  'operational',    'extensible','Commodity Category',                  'Commodity Categories',                 'table'),
        ('master','asset_assignment_history',              'AAH',    'MASTER', 'lite',  'operational',    'locked',   'Asset Assignment History',             'Asset Assignment History',             'table'),
        ('master','comment',                               'COM',    'MASTER', 'full',  'operational',    'controlled','Comment',                             'Comments',                             'table'),
        ('master','comment_draft',                         'CD',     'MASTER', 'standard','operational', 'controlled','Comment Draft',                        'Comment Drafts',                       'table'),
        ('master','budget_allocation',                     'BA',     'MASTER', 'full',  'operational',    'controlled','Budget Allocation',                   'Budget Allocations',                   'table'),
        ('master','principal_ui_profile',                  'PUP',    'MASTER', 'lite',  'config',         'controlled','UI Profile',                          'UI Profiles',                          'table'),
        ('master','attachment_acl',                        'AA',     'MASTER', 'full',  'tenant_critical','controlled','Attachment Access',                   'Attachment Access',                    'table'),
        ('master','comment_feed_cursor',                   'CFC',    'MASTER', 'lite',  'config',         'locked',   'Feed Cursor',                          'Feed Cursors',                         'table'),
        ('master','lifecycle_instance',                    'LI',     'MASTER', 'full',  'operational',    'locked',   'Lifecycle Instance',                   'Lifecycle Instances',                  'table'),
        ('master','business_intent',                       'BI',     'MASTER', 'full',  'tenant_critical','controlled','Business Intent',                     'Business Intents',                     'table'),
        ('master','bank_account_house_config',             'BAHC',   'MASTER', 'full',  'tenant_critical','controlled','House Bank Configuration',            'House Bank Configurations',            'table'),
        ('master','principal_ui_preference',               'PUPM',   'MASTER', 'lite',  'config',         'controlled','UI Preference',                       'UI Preferences',                       'table'),
        ('master','saved_view',                            'SV',     'MASTER', 'standard','config',       'controlled','Saved View',                          'Saved Views',                          'table'),
        ('master','principal_notification_preference',     'PNP',    'MASTER', 'lite',  'config',         'controlled','Notification Preference',             'Notification Preferences',             'table'),
        ('master','content_item_access_grant',             'CIAG',   'MASTER', 'full',  'operational',    'controlled','Content Access Grant',                'Content Access Grants',                'table'),
        ('master','tenant',                                'TENANT', 'MASTER', 'full',  'platform_critical','locked', 'Tenant',                               'Tenants',                              'table'),
        ('master','tenant_module_subscription',            'TMS',    'MASTER', 'full',  'tenant_critical','locked',   'Module Subscription',                  'Module Subscriptions',                 'table'),
        ('master','tenant_permission_override',            'TPO',    'MASTER', 'full',  'platform_critical','locked', 'Permission Override',                  'Permission Overrides',                 'table'),
        ('master','company_code_access',                   'CCA',    'MASTER', 'full',  'tenant_critical','controlled','Company Code Access',                 'Company Code Access',                  'table'),
        ('master','access_grant',                          'AG',     'MASTER', 'full',  'platform_critical','controlled','Access Grant',                      'Access Grants',                        'table'),
        ('master','group_feature_grant',                   'GFG',    'MASTER', 'full',  'tenant_critical','controlled','Group Feature Grant',                 'Group Feature Grants',                 'table'),
        ('master','principal_feature_grant',               'PFG',    'MASTER', 'full',  'tenant_critical','controlled','User Feature Grant',                  'User Feature Grants',                  'table'),
        ('master','delegation_grant',                      'DG',     'MASTER', 'full',  'tenant_critical','controlled','Delegation Grant',                    'Delegation Grants',                    'table'),
        ('master','dimension_type',                        'DT',     'MASTER', 'full',  'operational',    'extensible','Dimension Type',                      'Dimension Types',                      'table'),
        ('master','dimension_value',                       'DV',     'MASTER', 'full',  'operational',    'extensible','Dimension Value',                     'Dimension Values',                     'table'),
        ('master','notification_default',                  'ND',     'MASTER', 'standard','config',       'controlled','Notification Default',                'Notification Defaults',                'table'),
        ('master','multipart_upload',                      'MU',     'MASTER', 'standard','operational',  'locked',   'Multipart Upload',                     'Multipart Uploads',                    'table'),
        ('master','principal_identity_binding',            'PIB',    'MASTER', 'full',  'platform_critical','locked', 'Identity Binding',                     'Identity Bindings',                    'table'),
        ('master','principal',                             'PRM',    'MASTER', 'full',  'platform_critical','controlled','User',                              'Users',                                'table'),
        ('master','principal_profile',                     'PPM',    'MASTER', 'full',  'tenant_critical','controlled','User Profile',                        'User Profiles',                        'table'),
        ('master','address',                               'ADM',    'MASTER', 'full',  'operational',    'controlled','Address',                             'Addresses',                            'table'),
        ('master','auth_group',                            'AGM',    'MASTER', 'full',  'tenant_critical','controlled','Group',                               'Groups',                               'table'),
        ('master','team',                                  'TEAM',   'MASTER', 'full',  'operational',    'controlled','Team',                                'Teams',                                'table'),
        ('master','tenant_profile',                        'TPM',    'MASTER', 'full',  'tenant_critical','controlled','Tenant Profile',                      'Tenant Profiles',                      'table'),
        ('master','attachment',                            'ATM',    'MASTER', 'full',  'operational',    'controlled','Attachment',                          'Attachments',                          'table'),
        ('master','conversation',                          'COMA',   'MASTER', 'full',  'operational',    'controlled','Conversation',                        'Conversations',                        'table'),
        ('master','document',                              'DO',     'MASTER', 'full',  'operational',    'controlled','Document',                            'Documents',                            'table'),
        ('master','brand_profile',                         'BP',     'MASTER', 'standard','config',       'controlled','Brand Profile',                       'Brand Profiles',                       'table'),
        ('master','letterhead',                            'LE',     'MASTER', 'standard','config',       'controlled','Letterhead',                          'Letterheads',                          'table'),
        ('master','template',                              'TE',     'MASTER', 'standard','config',       'controlled','Template',                            'Templates',                            'table'),
        ('master','print_profile',                         'PRPF',   'MASTER', 'standard','config',       'controlled','Print Profile',                       'Print Profiles',                       'table'),
        ('master','legal_entity',                          'LEM',    'MASTER', 'full',  'tenant_critical','controlled','Legal Entity',                        'Legal Entities',                       'table'),
        ('master','company_code',                          'CCMA',   'MASTER', 'full',  'tenant_critical','controlled','Company Code',                        'Company Codes',                        'table'),
        ('master','cost_center',                           'COSC',   'MASTER', 'full',  'operational',    'controlled','Cost Center',                         'Cost Centers',                         'table'),
        ('master','profit_center',                         'PC',     'MASTER', 'full',  'operational',    'controlled','Profit Center',                       'Profit Centers',                       'table'),
        ('master','site',                                  'SITE',   'MASTER', 'full',  'operational',    'controlled','Site',                                'Sites',                                'table'),
        ('master','warehouse',                             'WA',     'MASTER', 'full',  'operational',    'controlled','Warehouse',                           'Warehouses',                           'table'),
        ('master','chart_of_account',                      'COA',    'MASTER', 'full',  'tenant_critical','controlled','Chart of Accounts',                   'Charts of Accounts',                   'table'),
        ('master','gl_account',                            'GA',     'MASTER', 'full',  'tenant_critical','controlled','GL Account',                          'GL Accounts',                          'table'),
        ('master','ledger_book',                           'LB',     'MASTER', 'full',  'tenant_critical','controlled','Ledger Book',                         'Ledger Books',                         'table'),
        ('master','project',                               'PROJ',   'MASTER', 'full',  'operational',    'extensible','Project',                             'Projects',                             'table'),
        ('master','dimension_set',                         'DSM',    'MASTER', 'full',  'operational',    'controlled','Dimension Set',                       'Dimension Sets',                       'table'),
        ('master','fiscal_period',                         'FP',     'MASTER', 'full',  'tenant_critical','locked',   'Fiscal Period',                        'Fiscal Periods',                       'table'),
        ('master','employee',                              'EMM',    'MASTER', 'full',  'tenant_critical','controlled','Employee',                            'Employees',                            'table'),
        ('master','company_code_customer_profile',         'CCCP',   'MASTER', 'full',  'operational',    'controlled','Customer Company Profile',            'Customer Company Profiles',            'table'),
        ('master','asset_class',                           'AC',     'MASTER', 'full',  'config',         'controlled','Asset Class',                         'Asset Classes',                        'table'),
        ('master','asset',                                 'ASSET',  'MASTER', 'full',  'operational',    'extensible','Asset',                               'Assets',                               'table'),
        ('master','tax_jurisdiction',                      'TJ',     'MASTER', 'full',  'operational',    'controlled','Tax Jurisdiction',                    'Tax Jurisdictions',                    'table'),
        ('master','tax_type',                              'TT',     'MASTER', 'full',  'operational',    'controlled','Tax Type',                            'Tax Types',                            'table'),
        ('master','fx_rate',                               'FR',     'MASTER', 'full',  'operational',    'locked',   'FX Rate',                              'FX Rates',                             'table'),
        ('master','budget_profile',                        'BPM',    'MASTER', 'full',  'operational',    'controlled','Budget Profile',                      'Budget Profiles',                      'table'),
        ('master','planning_model',                        'PM',     'MASTER', 'full',  'operational',    'controlled','Planning Model',                      'Planning Models',                      'table'),
        ('master','bank_party',                            'BKP',    'MASTER', 'full',  'operational',    'controlled','Bank',                                'Banks',                                'table'),
        ('master','payment_method',                        'PMM',    'MASTER', 'full',  'operational',    'controlled','Payment Method',                      'Payment Methods',                      'table'),
        ('master','holiday_calendar',                      'HCM',    'MASTER', 'full',  'config',         'controlled','Holiday Calendar',                    'Holiday Calendars',                    'table'),
        ('master','payment_term',                          'PT',     'MASTER', 'full',  'operational',    'controlled','Payment Term',                        'Payment Terms',                        'table'),
        ('master','product',                               'PROD',   'MASTER', 'full',  'operational',    'extensible','Product',                             'Products',                             'table'),
        ('master','item',                                  'ITEM',   'MASTER', 'full',  'operational',    'extensible','Item',                                'Items',                                'table'),
        ('master','dashboard',                             'DAM',    'MASTER', 'standard','config',       'controlled','Dashboard',                           'Dashboards',                           'table'),
        ('master','content_item',                          'CI',     'MASTER', 'full',  'operational',    'controlled','Content Item',                        'Content Items',                        'table'),
        ('master','label',                                 'LABEL',  'MASTER', 'standard','config',       'locked',   'Label',                                'Labels',                               'table'),
        ('master','owner_type',                            'OT',     'MASTER', 'standard','config',       'locked',   'Owner Type',                           'Owner Types',                          'table'),
        ('master','v_business_partner_bank_account',       'BPBA',   'MASTER', 'full',  'tenant_critical','controlled','Business Partner Bank Account',       'Business Partner Bank Accounts',       'view'),
        ('master','career_band',                           'CBM',    'MASTER', 'full',  'operational',    'controlled','Career Band',                         'Career Bands',                         'table'),
        ('master','career_level',                          'CLM',    'MASTER', 'full',  'operational',    'controlled','Career Level',                        'Career Levels',                        'table'),
        ('master','designation',                           'DE',     'MASTER', 'full',  'operational',    'controlled','Designation',                         'Designations',                         'table'),
        ('master','employee_leave_enrollment',             'ELE',    'MASTER', 'full',  'operational',    'controlled','Leave Enrollment',                    'Leave Enrollments',                    'table'),
        ('master','employee_statutory_enrollment',         'ESE',    'MASTER', 'full',  'tenant_critical','controlled','Statutory Enrollment',                'Statutory Enrollments',                'table'),
        ('master','employment',                            'EMMA',   'MASTER', 'full',  'tenant_critical','controlled','Employment',                          'Employments',                          'table'),
        ('master','external_reference',                    'ERM',    'MASTER', 'full',  'operational',    'controlled','External Reference',                  'External References',                  'table'),
        ('master','job',                                   'JOB',    'MASTER', 'full',  'operational',    'controlled','Job',                                 'Jobs',                                 'table'),
        ('master','job_family',                            'JF',     'MASTER', 'full',  'operational',    'controlled','Job Family',                          'Job Families',                         'table'),
        ('master','job_function',                          'JFM',    'MASTER', 'full',  'operational',    'controlled','Job Function',                        'Job Functions',                        'table'),
        ('master','leave_plan',                            'LP',     'MASTER', 'full',  'operational',    'controlled','Leave Plan',                          'Leave Plans',                          'table'),
        ('master','leave_plan_rule',                       'LPR',    'MASTER', 'full',  'operational',    'controlled','Leave Plan Rule',                     'Leave Plan Rules',                     'table'),
        ('master','leave_type',                            'LTM',    'MASTER', 'full',  'operational',    'controlled','Leave Type',                          'Leave Types',                          'table'),
        ('master','org_unit',                              'OU',     'MASTER', 'full',  'operational',    'controlled','Org Unit',                            'Org Units',                            'table'),
        ('master','pay_component',                         'PCM',    'MASTER', 'full',  'tenant_critical','controlled','Pay Component',                       'Pay Components',                       'table'),
        ('master','pay_grade',                             'PG',     'MASTER', 'full',  'operational',    'controlled','Pay Grade',                           'Pay Grades',                           'table'),
        ('master','pay_group',                             'PGM',    'MASTER', 'full',  'tenant_critical','controlled','Pay Group',                           'Pay Groups',                           'table'),
        ('master','pay_structure',                         'PS',     'MASTER', 'full',  'tenant_critical','controlled','Pay Structure',                       'Pay Structures',                       'table'),
        ('master','pay_structure_line',                    'PSL',    'MASTER', 'full',  'tenant_critical','controlled','Pay Structure Line',                  'Pay Structure Lines',                  'table'),
        ('master','person',                                'PERSON', 'MASTER', 'full',  'tenant_critical','controlled','Person',                              'People',                               'table'),
        ('master','person_sensitive_profile',              'PSP',    'MASTER', 'full',  'tenant_critical','locked',   'Person Sensitive Profile',             'Person Sensitive Profiles',            'table'),
        ('master','position',                              'POM',    'MASTER', 'full',  'operational',    'controlled','Position',                            'Positions',                            'table'),
        ('master','shift_type',                            'STM',    'MASTER', 'full',  'operational',    'controlled','Shift Type',                          'Shift Types',                          'table'),
        ('master','statutory_scheme',                      'SS',     'MASTER', 'full',  'tenant_critical','controlled','Statutory Scheme',                    'Statutory Schemes',                    'table'),
        ('master','work_assignment',                       'WAM',    'MASTER', 'full',  'tenant_critical','controlled','Work Assignment',                     'Work Assignments',                     'table'),
        ('master','work_pattern',                          'WP',     'MASTER', 'full',  'operational',    'controlled','Work Pattern',                        'Work Patterns',                        'table'),
        ('master','work_pattern_day',                      'WPD',    'MASTER', 'full',  'operational',    'controlled','Work Pattern Day',                    'Work Pattern Days',                    'table'),
        ('master','asset_component',                       'ACM',    'MASTER', 'full',  'operational',    'controlled','Asset Component',                     'Asset Components',                     'table'),
        ('master','contact_link',                          'CLMA',   'MASTER', 'standard','operational', 'controlled','Contact Link',                         'Contact Links',                        'table'),
        ('master','contact_email',                         'CEM',    'MASTER', 'standard','operational', 'controlled','Contact Email',                        'Contact Emails',                       'table'),
        ('master','contact_phone',                         'CPM',    'MASTER', 'standard','operational', 'controlled','Contact Phone',                        'Contact Phones',                       'table'),
        ('master','label_entity_type',                     'LET',    'MASTER', 'standard','config',       'controlled','Label Entity Type',                   'Label Entity Types',                   'table'),
        ('master','address_link',                          'AL',     'MASTER', 'full',  'operational',    'controlled','Address Link',                        'Address Links',                        'table'),
        ('master','auth_group_role',                       'AGR',    'MASTER', 'full',  'tenant_critical','controlled','Group Role',                          'Group Roles',                          'table'),
        ('master','auth_group_member',                     'AGMM',   'MASTER', 'full',  'tenant_critical','controlled','Group Member',                        'Group Members',                        'table'),
        ('master','principal_persona',                     'PRPER',  'MASTER', 'full',  'tenant_critical','controlled','User Persona',                        'User Personas',                        'table'),
        ('master','team_member',                           'TM',     'MASTER', 'full',  'operational',    'controlled','Team Member',                         'Team Members',                         'table'),
        ('master','comment_mention',                       'CM',     'MASTER', 'standard','operational', 'locked',   'Comment Mention',                      'Comment Mentions',                     'table'),
        ('master','comment_reaction',                      'CR',     'MASTER', 'standard','operational', 'locked',   'Comment Reaction',                     'Comment Reactions',                    'table'),
        ('master','conversation_participant',              'CPMA',   'MASTER', 'standard','operational', 'controlled','Conversation Participant',             'Conversation Participants',             'table'),
        ('master','attachment_comment',                    'ACMA',   'MASTER', 'standard','operational', 'locked',   'Attachment Comment',                   'Attachment Comments',                  'table'),
        ('master','template_binding',                      'TB',     'MASTER', 'standard','config',       'controlled','Template Binding',                    'Template Bindings',                    'table'),
        ('master','entity_document_link',                  'EDL',    'MASTER', 'standard','operational', 'controlled','Entity Document Link',                 'Entity Document Links',                'table'),
        ('master','asset_book',                            'AB',     'MASTER', 'full',  'operational',    'controlled','Asset Book',                          'Asset Books',                          'table'),
        ('master','project_item',                          'PIMA',   'MASTER', 'full',  'operational',    'extensible','Project Item',                        'Project Items',                        'table'),
        ('master','company_code_gl_account',               'CCGA',   'MASTER', 'full',  'tenant_critical','controlled','Company GL Account',                  'Company GL Accounts',                  'table'),
        ('master','company_code_book_assignment',          'CCBA',   'MASTER', 'full',  'tenant_critical','controlled','Book Assignment',                     'Book Assignments',                     'table'),
        ('master','dimension_set_item',                    'DSI',    'MASTER', 'standard','operational', 'controlled','Dimension Set Item',                   'Dimension Set Items',                  'table'),
        ('master','bank_account_link',                     'BAL',    'MASTER', 'full',  'tenant_critical','controlled','Bank Account Link',                   'Bank Account Links',                   'table'),
        ('master','holiday_calendar_day',                  'HCD',    'MASTER', 'standard','config',       'locked',   'Holiday',                              'Holidays',                             'table'),
        ('master','payment_term_clause',                   'PTCM',   'MASTER', 'full',  'operational',    'controlled','Payment Term Clause',                 'Payment Term Clauses',                 'table'),
        ('master','payment_term_discount_tier',            'PTDT',   'MASTER', 'full',  'operational',    'controlled','Discount Tier',                       'Discount Tiers',                       'table'),
        ('master','dashboard_widget',                      'DW',     'MASTER', 'standard','config',       'controlled','Dashboard Widget',                    'Dashboard Widgets',                    'table'),
        ('master','content_item_link',                     'CIL',    'MASTER', 'standard','operational', 'controlled','Content Link',                         'Content Links',                        'table'),
        ('master','commodity_classification',              'COMC',   'MASTER', 'full',  'operational',    'controlled','Commodity Classification',            'Commodity Classifications',             'table'),
        ('master','risk_source',                           'RS',     'MASTER', 'standard','tenant_critical','controlled','Risk Source',                       'Risk Sources',                         'table'),
        ('master','tenant_parameter_definition',           'TPD',    'MASTER', 'full',  'config',         'controlled','Tenant Parameter Definition',         'Tenant Parameter Definitions',         'table'),
        ('master','business_partner_network_capability',   'BPNC',   'MASTER', 'standard','operational', 'controlled','Network Capability',                   'Network Capabilities',                 'table'),
        ('master','business_partner_relation',             'BPRM',   'MASTER', 'full',  'operational',    'controlled','Business Partner Relation',           'Business Partner Relations',           'table'),
        ('master','certification_type',                    'CTM',    'MASTER', 'standard','config',       'controlled','Certification Type',                  'Certification Types',                  'table'),
        ('master','filter_preset',                         'FPM',    'MASTER', 'standard','config',       'controlled','Filter Preset',                       'Filter Presets',                       'table'),
        ('master','intercompany_trading_pair',             'ITP',    'MASTER', 'full',  'operational',    'controlled','Intercompany Trading Pair',           'Intercompany Trading Pairs',           'table'),
        ('master','risk_dimension',                        'RD',     'MASTER', 'standard','tenant_critical','controlled','Risk Dimension',                    'Risk Dimensions',                      'table'),
        ('master','legal_entity_business_partner_link',    'LEBPL',  'MASTER', 'full',  'operational',    'controlled','Legal Entity Business Partner Link',  'Legal Entity Business Partner Links',  'table'),
        ('master','legal_entity_identity_binding',         'LEIB',   'MASTER', 'full',  'tenant_critical','locked',   'Legal Entity Identity Binding',        'Legal Entity Identity Bindings',       'table'),
        ('master','network_provider',                      'NPM',    'MASTER', 'standard','operational', 'controlled','Network Provider',                     'Network Providers',                    'table'),
        ('master','party_risk_dimension_score',            'PRDS',   'MASTER', 'full',  'tenant_critical','controlled','Party Risk Dimension Score',           'Party Risk Dimension Scores',          'table'),
        ('master','party_risk_driver',                     'PRDM',   'MASTER', 'full',  'tenant_critical','controlled','Party Risk Driver',                   'Party Risk Drivers',                   'table'),
        ('master','party_risk_evidence',                   'PREM',   'MASTER', 'full',  'tenant_critical','controlled','Party Risk Evidence',                 'Party Risk Evidence',                  'table'),
        ('master','party_risk_mitigation',                 'PRMM',   'MASTER', 'full',  'tenant_critical','controlled','Party Risk Mitigation',               'Party Risk Mitigations',               'table'),
        ('master','record_bookmark',                       'RB',     'MASTER', 'lite',  'config',         'controlled','Record Bookmark',                     'Record Bookmarks',                     'table'),
        ('master','risk_driver_registry',                  'RDR',    'MASTER', 'standard','tenant_critical','controlled','Risk Driver Registry',              'Risk Driver Registry',                 'table'),
        ('master','risk_model',                            'RM',     'MASTER', 'full',  'tenant_critical','controlled','Risk Model',                          'Risk Models',                          'table'),
        ('master','risk_model_dimension',                  'RMD',    'MASTER', 'full',  'tenant_critical','controlled','Risk Model Dimension',                'Risk Model Dimensions',                'table'),
        ('master','tenant_parameter_value',                'TPV',    'MASTER', 'full',  'config',         'controlled','Tenant Parameter Value',              'Tenant Parameter Values',              'table'),
        ('master','tenant_risk_source_config',             'TRSCM',  'MASTER', 'full',  'tenant_critical','controlled','Tenant Risk Source Config',           'Tenant Risk Source Configs',           'table'),
        ('master','trusted_device',                        'TD',     'MASTER', 'full',  'tenant_critical','locked',   'Trusted Device',                       'Trusted Devices',                      'table'),
        ('master','supplier',                              'SU',     'MASTER', 'full',  'operational',    'extensible','Supplier',                            'Suppliers',                            'table'),
        ('master','business_partner',                      'BPMA',   'MASTER', 'full',  'operational',    'extensible','Business Partner',                    'Business Partners',                    'table'),
        ('master','customer',                              'CU',     'MASTER', 'full',  'operational',    'extensible','Customer',                            'Customers',                            'table'),
        ('master','company_code_supplier_profile',         'CCSPM',  'MASTER', 'full',  'operational',    'controlled','Supplier Company Profile',            'Supplier Company Profiles',            'table'),
        ('master','supplier_app_index',                    'SAI',    'MASTER', 'lite',  'operational',    'locked',   'Supplier App Index',                   'Supplier App Indices',                 'table'),
        ('master','company_code_intent_policy',            'CCIPM',  'MASTER', 'full',  'tenant_critical','controlled','Company Intent Policy',               'Company Intent Policies',              'table'),
        ('master','company_code_supplier_intent_policy',   'CCSIP',  'MASTER', 'standard','operational', 'controlled','Supplier Intent Policy',              'Supplier Intent Policies',             'table'),
        ('master','company_code_supplier_posting_override','CCSPO',  'MASTER', 'standard','tenant_critical','controlled','Supplier Posting Override',         'Supplier Posting Overrides',           'table'),
        ('master','accounting_profile',                    'AP',     'MASTER', 'full',  'tenant_critical','controlled','Accounting Profile',                  'Accounting Profiles',                  'table'),
        ('master','bank_account',                          'BAM',    'MASTER', 'full',  'tenant_critical','controlled','Bank Account',                        'Bank Accounts',                        'table'),

        -- ── shared schema (entity_class SHARED → REFERENCE) ───────────────────
        ('shared','country',                               'COS',    'REFERENCE','lite','config',         'locked',   'Country',                              'Countries',                            'table'),
        ('shared','uom',                                   'UOM',    'REFERENCE','lite','config',         'locked',   'Unit of Measure',                      'Units of Measure',                     'table'),
        ('shared','commodity_code',                        'CCS',    'REFERENCE','lite','config',         'locked',   'Commodity Code',                       'Commodity Codes',                      'table'),
        ('shared','state_region',                          'SR',     'REFERENCE','lite','config',         'locked',   'State / Region',                       'States / Regions',                     'table'),
        ('shared','industry_code',                         'IC',     'REFERENCE','lite','config',         'locked',   'Industry Code',                        'Industry Codes',                       'table'),
        ('shared','locale',                                'LOCALE', 'REFERENCE','lite','config',         'locked',   'Locale',                               'Locales',                              'table'),
        ('shared','currency',                              'CUS',    'REFERENCE','lite','config',         'locked',   'Currency',                             'Currencies',                           'table'),
        ('shared','language',                              'LA',     'REFERENCE','lite','config',         'locked',   'Language',                             'Languages',                            'table'),
        ('shared','enterprise_feature',                    'EFSH',   'REFERENCE','lite','config',         'locked',   'Enterprise Feature',                   'Enterprise Features',                  'table'),
        ('shared','subscription_plan',                     'SP',     'REFERENCE','lite','config',         'locked',   'Subscription Plan',                    'Subscription Plans',                   'table'),
        ('shared','persona',                               'PES',    'REFERENCE','lite','config',         'locked',   'Persona',                              'Personas',                             'table'),
        ('shared','workspace',                             'WO',     'REFERENCE','lite','config',         'locked',   'Workspace',                            'Workspaces',                           'table'),
        ('shared','permission_category',                   'PCS',    'REFERENCE','lite','config',         'locked',   'Permission Category',                  'Permission Categories',                'table'),
        ('shared','industry_crosswalk',                    'ICS',    'REFERENCE','lite','config',         'locked',   'Industry Crosswalk',                   'Industry Crosswalks',                  'table'),
        ('shared','timezone',                              'TI',     'REFERENCE','lite','config',         'locked',   'Time Zone',                            'Time Zones',                           'table'),
        ('shared','module',                                'MODULE', 'REFERENCE','lite','config',         'locked',   'Module',                               'Modules',                              'table'),
        ('shared','plan_feature_access',                   'PFA',    'REFERENCE','lite','config',         'locked',   'Plan Feature Access',                  'Plan Feature Access',                  'table'),
        ('shared','plan_module_access',                    'PMA',    'REFERENCE','lite','config',         'locked',   'Plan Module Access',                   'Plan Module Access',                   'table'),
        ('shared','plan_permission_access',                'PPA',    'REFERENCE','lite','config',         'locked',   'Plan Permission Access',               'Plan Permission Access',               'table'),
        ('shared','role',                                  'ROLE',   'REFERENCE','lite','config',         'locked',   'Role',                                 'Roles',                                'table'),
        ('shared','permission',                            'PESH',   'REFERENCE','lite','config',         'locked',   'Permission',                           'Permissions',                          'table'),
        ('shared','commodity_crosswalk',                   'CCSH',   'REFERENCE','lite','config',         'locked',   'Commodity Crosswalk',                  'Commodity Crosswalks',                 'table'),
        ('shared','persona_permission',                    'PPS',    'REFERENCE','lite','config',         'locked',   'Persona Permission',                   'Persona Permissions',                  'table')

    ),
    resolved AS (
        SELECT
            c.tbl_schema,
            c.tbl_name,
            c.entity_short,
            c.entity_class,
            c.gov_level,
            c.sec_tier,
            c.mutab,
            c.label_s,
            c.label_p,
            c.backing,
            replace(lower(c.tbl_name), '_', '-') AS computed_slug,
            c.tbl_name                           AS computed_code,
            CASE c.tbl_schema
                WHEN 'shared'   THEN v_fnd
                WHEN 'control'  THEN v_fnd
                ELSE                 v_acc
            END AS mod_id
        FROM corrections c
        -- Only include rows where the table or view actually exists in the DB
        WHERE EXISTS (
            SELECT 1 FROM information_schema.tables  t
             WHERE t.table_schema = c.tbl_schema AND t.table_name = c.tbl_name
               AND t.table_type IN ('BASE TABLE', 'VIEW')
        )
    )
    INSERT INTO control.entity (
        module_id, name, entity_short, entity_code, slug,
        entity_class, ownership_model, kind, backing_type,
        governance_level, security_tier, mutability, mapping_mode,
        table_schema, table_name, label_singular, label_plural,
        status, created_by, updated_by
    )
    SELECT
        r.mod_id,
        r.computed_code,      -- name (table-name-only)
        r.entity_short,
        r.computed_code,      -- entity_code (table-name-only)
        r.computed_slug,
        r.entity_class,
        'system', 'ent',
        r.backing,
        r.gov_level,
        r.sec_tier,
        r.mutab,
        'exclusive',
        r.tbl_schema, r.tbl_name,
        r.label_s, r.label_p,
        'ACTIVE', v_su, v_su
    FROM resolved r
    ON CONFLICT (table_schema, table_name) DO UPDATE SET
        -- Safe fields only (Phase 1a).
        -- entity_code and name are NOT updated here to avoid breaking
        -- entity_lifecycle / entity_operation text references and TS code.
        slug             = EXCLUDED.slug,
        entity_short     = EXCLUDED.entity_short,
        entity_class     = EXCLUDED.entity_class,
        governance_level = EXCLUDED.governance_level,
        security_tier    = EXCLUDED.security_tier,
        mutability       = EXCLUDED.mutability,
        mapping_mode     = EXCLUDED.mapping_mode,
        label_singular   = EXCLUDED.label_singular,
        label_plural     = EXCLUDED.label_plural,
        backing_type     = EXCLUDED.backing_type,
        updated_at       = now(),
        updated_by       = v_su
    WHERE control.entity.tenant_id IS NULL
      AND control.entity.table_schema IN ('control', 'document', 'master', 'shared');

    GET DIAGNOSTICS v_count = ROW_COUNT;
    RAISE NOTICE 'Phase 1a entity correction: % rows upserted (inserted + updated)', v_count;

    -- ── entity_version seed for newly-inserted entities lacking version 1 ─────
    INSERT INTO control.entity_version (
        entity_id, tenant_id, version_no, status, label,
        change_type, effective_from, created_by, updated_by
    )
    SELECT
        e.id, e.tenant_id, 1, 'EFFECTIVE',
        'Initial Version',
        'structural', now(), v_su, v_su
    FROM control.entity e
    WHERE e.tenant_id IS NULL
      AND e.table_schema IN ('control', 'document', 'master', 'shared')
      AND NOT EXISTS (
          SELECT 1 FROM control.entity_version ev
           WHERE ev.entity_id = e.id AND ev.version_no = 1
      );

    RAISE NOTICE 'Phase 1a complete.';
END $$;
