import { BUSINESS_PARTNER_DEFINITION_BUNDLE_SCHEMA_V1,type BusinessPartnerDefinitionBundleV1 } from "@athyper/server-contract-publication";

const sources=["internal","portal","mesh","import","api"] as const;
const commonIdentity=["partner.displayName","partner.legalName","partner.countryCode","partner.category"];
const organizationIdentity=[...commonIdentity,"partner.registrationNumber","partner.taxIdentifiers","partner.addresses","partner.contacts"];
const personIdentity=["person.firstName","person.lastName","person.personalEmail","person.phone","person.consent"];

export function createBusinessPartnerFoundationDefinition(sourceContractHashes:Readonly<Record<"request"|"eligibility"|"meshProfile"|"meshMatch"|string,string>>):BusinessPartnerDefinitionBundleV1{
 const requestSchemas={
  "supplier.new":schema("supplier","new_partner",organizationIdentity,["scope.operatingOrganizationId"]),"supplier.add":schema("supplier","add_supplier",["targetBusinessPartnerId"],["scope.operatingOrganizationId"]),
  "supplier.qualify":schema("supplier","qualify",["targetBusinessPartnerId","qualification.criteria","qualification.evidence"],["scope.operatingOrganizationId"]),"supplier.company":schema("supplier","configure_company",["targetBusinessPartnerId","company.paymentTerms","company.currency"],["scope.operatingOrganizationId","scope.companyCodeId"]),"supplier.bank":schema("supplier","change_bank",["targetBusinessPartnerId","bankVerification.evidenceReference"],["scope.companyCodeId"]),
  "customer.new":schema("customer","new_partner",organizationIdentity,["scope.operatingOrganizationId"]),"customer.add":schema("customer","add_customer",["targetBusinessPartnerId"],["scope.operatingOrganizationId"]),"customer.credit":schema("customer","credit_review",["targetBusinessPartnerId","credit.requestedLimit","credit.currency","credit.evidence"],["scope.companyCodeId"]),"customer.company":schema("customer","configure_company",["targetBusinessPartnerId","company.paymentTerms","company.statementPolicy"],["scope.operatingOrganizationId","scope.companyCodeId"]),
  "workforce.new":schema("workforce","new_partner",personIdentity,["scope.legalEntityId","scope.companyCodeId","scope.orgUnitId","employment.startDate"]),"workforce.add":schema("workforce","add_workforce",["targetBusinessPartnerId",...personIdentity],["scope.legalEntityId","scope.companyCodeId","scope.orgUnitId","employment.startDate"]),"workforce.change":schema("workforce","change_employment",["targetBusinessPartnerId","employment.changeKind","employment.effectiveFrom"],["scope.legalEntityId","scope.companyCodeId","scope.orgUnitId"]),"workforce.offboard":schema("workforce","offboard",["targetBusinessPartnerId","offboarding.exitDate","offboarding.reasonCode","offboarding.resourceChecklist"],["scope.legalEntityId"]),
  "partner.amend":schema("governance","amend_partner",["targetBusinessPartnerId","baseRecordVersion"],[]),"partner.assign":schema("governance","assign_organization",["targetBusinessPartnerId","scope.operatingOrganizationId"],[]),"partner.deactivate":schema("governance","deactivate",["targetBusinessPartnerId","reasonCode"],[]),"partner.reactivate":schema("governance","reactivate",["targetBusinessPartnerId","reasonCode"],[]),"partner.archive":schema("governance","archive",["targetBusinessPartnerId","reasonCode"],[]),
 };
 return Object.freeze({schema:BUSINESS_PARTNER_DEFINITION_BUNDLE_SCHEMA_V1,bundleCode:"business_partner.onboarding",semanticVersion:"2.1.0",requestSchemas,
  fieldPolicies:{organization:{category:"organization",visible:[...organizationIdentity,"partner.legalForm","partner.incorporationDate","partner.websiteUrl","partner.industryCodes"],restricted:["partner.taxIdentifiers"],prohibited:["person.identityEvidence","person.dateOfBirth","employment.compensation"]},person:{category:"person",visible:[...personIdentity,"person.preferredName","employment.startDate"],restricted:["person.identityEvidence","person.dateOfBirth","person.nationalIdentifiers","employment.compensation"],prohibited:["bankVerification","supplier.qualification"]},portal:{write:[...organizationIdentity,...personIdentity,"evidence.references"],read:["requestNo","status","validationSummary","returnReasons"],prohibited:["workflow.decision","readiness.override","masterData"]}},
  validationDeclarations:[validation("BP_LEGAL_NAME_REQUIRED","partner.legalName","required","organization"),validation("BP_COUNTRY_REQUIRED","partner.countryCode","iso-3166-alpha2","organization"),validation("BP_PERSON_NAME_REQUIRED","person.firstName","required","person"),validation("BP_PERSON_CONSENT_REQUIRED","person.consent","consent-current","person"),validation("BP_SUPPLIER_SCOPE_REQUIRED","scope.operatingOrganizationId","uuid","supplier"),validation("BP_CUSTOMER_SCOPE_REQUIRED","scope.operatingOrganizationId","uuid","customer"),validation("BP_WORKFORCE_EMPLOYER_REQUIRED","scope.legalEntityId","uuid","workforce"),validation("BP_WORKFORCE_DATE_REQUIRED","employment.startDate","effective-date","workforce"),validation("BP_EVIDENCE_POLICY_REQUIRED","evidence.references","evidence-policy","all"),validation("BP_SOURCE_MAPPING_REQUIRED","source.kind","mapping-declared","all")],
  duplicateRules:{organization:{match:["normalizedLegalName+countryCode","registrationNumber+countryCode","taxIdentifierHash+countryCode"],resolution:"steward_review",categoryChange:"forbidden"},person:{match:["normalizedName+personalEmailHash","nationalIdentifierHash+countryCode"],resolution:"privacy_bound_steward_review",categoryChange:"forbidden"}},
  formDescriptors:{request:{version:"2.0.0",journeyBound:true,sections:["identity","role","organizationScope","employmentScope","classification","contacts","evidence","sourceProvenance"],conditionalVisibility:[{field:"organizationScope",categories:["organization"]},{field:"employmentScope",roles:["workforce"]},{field:"bankVerification",operations:["supplier.bank"]}]},supplierQualification:{version:"2.0.0",sections:["scope","criteria","commodityRegion","evidence","decision"]},customerCredit:{version:"2.0.0",sections:["companyScope","requestedLimit","riskEvidence","decision"]},workforceReview:{version:"2.0.0",sections:["person","employment","assignment","consent","rightToWork","backgroundEvidence"]}},
  viewDescriptors:{neonRequestList:{version:"2.0.0",columns:["requestNo","displayName","journey","operation","source","status","scope","slaDueAt","createdAt"]},neonRequestDetail:{version:"2.0.0",panels:["summary","identity","roleScope","sourceProvenance","validation","duplicates","evidence","workflowTimeline","applicationEvidence"]},neonReview:{version:"2.0.0",panels:["reviewedPayload","fieldDiff","validation","duplicateResolution","evidence","readiness"],actions:["return","reject","approve"],noSelfApproval:true},neonPartnerAggregate:{version:"2.1.0",compatibility:"read_only_until_360_cutover",panels:["identity","roles","organizationAssignments","companyConfiguration","qualification","credit","workforce","bankVerification","readinessWithoutRisk","sourceProvenance"],retirementSignal:"bp360_legacy_aggregate_consumers_zero"},neonPartner360:{version:"1.0.0",schemaVersion:1,sections:partner360Sections,presentation:{identityHeader:"sticky",scopeBar:"required_for_scoped_sections",navigation:"manifest_driven",restrictedValues:"masked_by_default"},completenessPacks:partner360CompletenessPacks,excludedCapabilities:["risk"]}},
  mappingContracts:Object.fromEntries(sources.map(source=>[source,{version:"2.0.0",source,destination:"business_partner_request",strategy:source==="mesh"?"selective_acceptance":"declarative_mapping",snapshotPinned:source==="mesh",directMasterWrite:false,allowedJourneys:source==="mesh"?["supplier","customer"]:["supplier","customer","workforce"],requiredProvenance:source==="internal"?["principalId"]:source==="portal"?["invitationId","applicantPrincipalId"]:source==="mesh"?["projectionId","snapshotId","acceptedFieldPaths"]:["systemCode","entityId","payloadHash"]}])),
  workflowDefinitions:{supplier:{version:"2.0.0",stages:[stage("stewardship",240),stage("compliance_tax",480),stage("procurement_owner",240)],sod:{makerCannotDecide:true,applicantCannotDecide:true,mfaAtDecision:true},escalation:["stage_owner","operating_organization_owner","data_governance_owner"]},customer:{version:"2.0.0",stages:[stage("stewardship",240),stage("compliance_consent",480),stage("sales_owner",240),stage("credit_review",480)],sod:{makerCannotDecide:true,applicantCannotDecide:true,mfaAtDecision:true},escalation:["stage_owner","sales_organization_owner","data_governance_owner"]},workforce:{version:"2.0.0",stages:[stage("hr_review",240),stage("hiring_manager",240),stage("compliance_privacy",480)],sod:{makerCannotDecide:true,applicantCannotDecide:true,mfaAtDecision:true,restrictedEvidencePurposeRequired:true},escalation:["stage_owner","hr_business_partner","privacy_officer"]},governance:{version:"2.0.0",stages:[stage("dependency_impact_review",480),stage("data_stewardship",240)],sod:{makerCannotDecide:true,mfaAtDecision:true},escalation:["data_governance_owner"]}},
  evidencePolicies:{supplier:{required:["legal_identity","tax","representation"],conditional:{"supplier.bank":["bank_ownership","verification_method"],"supplier.qualify":["qualification_criteria"]}},customer:{required:["legal_identity","tax_or_consent"],conditional:{"customer.credit":["credit_evidence"]}},workforce:{required:["consent","identity","right_to_work"],conditional:{"workforce.new":["background_policy_result"],"workforce.offboard":["resource_checklist"]},purposeBound:true}},
  readinessGates:{supplier:["BUSINESS_PARTNER_ACTIVE","PROCUREMENT_ASSIGNMENT_EFFECTIVE","COMPANY_PROFILE_COMPLETE","QUALIFICATION_CURRENT","NO_PROHIBITIVE_BLOCK","BANK_VERIFIED_WHEN_PAYABLE"],customer:["BUSINESS_PARTNER_ACTIVE","SALES_ASSIGNMENT_EFFECTIVE","COMPANY_PROFILE_COMPLETE","CREDIT_REVIEW_CURRENT","NO_PROHIBITIVE_BLOCK"],workforce:["BUSINESS_PARTNER_ACTIVE","EMPLOYEE_ACTIVE","EMPLOYMENT_EFFECTIVE","PRIMARY_ASSIGNMENT_EFFECTIVE","ONBOARDING_COMPLETE"]},
  reasonCodeCatalog:{BP_VALIDATION_FAILED:"Payload validation failed",BP_DUPLICATE_REVIEW_REQUIRED:"Duplicate review is required",BP_EVIDENCE_MISSING:"Required evidence is missing",BP_SCOPE_INVALID:"Requested scope is invalid",BP_SOD_VIOLATION:"Maker/checker separation failed",BP_SLA_ESCALATED:"Workflow SLA was escalated",SUPPLIER_NOT_READY:"Supplier readiness gates failed",CUSTOMER_NOT_READY:"Customer readiness gates failed",WORKFORCE_NOT_READY:"Workforce readiness gates failed",BP_DEFINITION_INCOMPATIBLE:"Definition is incompatible with the local runtime"},
  meshSafeSchemas:{organizationProfile:{version:"2.0.0",schemaVersion:2,fieldSetCode:"recipient_safe_v2",category:"organization",fields:["schemaCode","schemaVersion","fieldSetCode","authority.plane","authority.ownerTenantId","authority.ownerNetworkAccountId","recipient.tenantId","recipient.networkAccountId","recipient.networkRelationshipId","recipient.proposedNeonRole","partner.accountCode","partner.displayName","partner.legalName","partner.networkRole","partner.countryCode","partner.defaultCurrency","partner.logoAssetRef","partner.legalForm","partner.incorporationDate","partner.websiteUrl","partner.description","partner.preferredLanguageCode","commodityCapabilities.domainCode","commodityCapabilities.code","commodityCapabilities.name","commodityCapabilities.tradeRole","commodityCapabilities.effectiveFrom","commodityCapabilities.effectiveUntil","industryClassifications.domainCode","industryClassifications.code","industryClassifications.name","industryClassifications.assignmentKind","industryClassifications.isPrimary","industryClassifications.confidence","industryClassifications.effectiveFrom","industryClassifications.effectiveUntil"],prohibitedPatterns:["person.","workforce.","employment.","bankVerification.","taxIdentifiers.value"]},selectiveAcceptance:{version:"2.0.0",requires:["snapshotId","acceptedFieldPaths","payloadHash"],directMasterWrite:false}},
  compatibilityRules:{bundleSchemaVersion:"1.0.0",minimumConsumerVersions:{studio:"1.0.0",neon:"1.0.0",mesh:"1.0.0"},unknownFieldPolicy:"reject_for_policy_objects",removedRequiredField:"breaking",addOptionalField:"backward_compatible",workflowStageRemoval:"breaking",mappingChangeRequiresNewVersion:true,semanticVersionMonotonic:true,sourceHashExact:true,lastValidLocalReleaseOnStudioOutage:true,rollbackOnlyToExactPreviousActive:true},sourceContractHashes});
}
function schema(role:string,operation:string,required:readonly string[],scope:readonly string[]){return{version:"2.0.0",role,operation,supportedSources:sources,required:[...required,...scope],additionalProperties:false,definitionDriven:true};}
function validation(code:string,path:string,rule:string,appliesTo:string){return{code,path,rule,appliesTo,severity:"error"};}
function stage(code:string,slaMinutes:number){return{code,mode:"any",quorum:1,slaMinutes,remindersAtMinutes:[Math.floor(slaMinutes/2),Math.floor(slaMinutes*.8)],escalateAtMinutes:slaMinutes,noSelfApproval:true};}

const partner360Sections=Object.freeze([
 {code:"overview",routes:[],permission:"neon.relationship.business_partner.read",discoverableWhenDenied:false},
 {code:"identity",routes:["/api/neon/business-partners/:id/360/identity"],permission:"neon.relationship.business_partner_identity.read",discoverableWhenDenied:false},
 {code:"contacts",routes:["/api/neon/business-partners/:id/360/contacts"],permission:"neon.relationship.business_partner_contact.read",discoverableWhenDenied:false},
 {code:"addresses",routes:["/api/neon/business-partners/:id/360/addresses"],permission:"neon.relationship.business_partner_address.read",discoverableWhenDenied:false},
 {code:"identifiers-tax",routes:["/api/neon/business-partners/:id/360/identifiers"],permission:"neon.relationship.business_partner_identifier.read_masked",fieldPermissions:["neon.relationship.business_partner_tax.read_masked"],discoverableWhenDenied:false},
 {code:"roles-scope",routes:["/api/neon/business-partners/:id/360/roles"],permission:"neon.relationship.business_partner.read",discoverableWhenDenied:false},
 {code:"supplier-company",routes:["/api/neon/business-partners/:id/360/company-configuration"],permission:"neon.relationship.business_partner.read",discoverableWhenDenied:false},
 {code:"customer-company",routes:["/api/neon/business-partners/:id/360/company-configuration"],permission:"neon.relationship.business_partner.read",discoverableWhenDenied:false},
 {code:"banking",routes:["/api/neon/business-partners/:id/360/banking"],permission:"neon.relationship.business_partner_bank.read_masked",discoverableWhenDenied:false},
 {code:"qualifications-certificates",routes:["/api/neon/business-partners/:id/360/qualifications","/api/neon/business-partners/:id/360/certificates"],permission:"neon.relationship.business_partner_qualification.read",fieldPermissions:["neon.relationship.business_partner_certificate.read"],discoverableWhenDenied:false},
 {code:"credit",routes:["/api/neon/business-partners/:id/360/credit"],permission:"neon.relationship.business_partner_credit.read",discoverableWhenDenied:false},
 {code:"workforce",routes:["/api/neon/business-partners/:id/360/workforce"],permission:"neon.relationship.business_partner_workforce.read",fieldPermissions:["neon.relationship.business_partner_person.read"],discoverableWhenDenied:false},
 {code:"requests",routes:["/api/neon/business-partners/:id/360/requests"],permission:"neon.relationship.business_partner_request.read",discoverableWhenDenied:false},
 {code:"activity",routes:["/api/neon/business-partners/:id/360/activity"],permission:"neon.relationship.business_partner_activity.read",discoverableWhenDenied:false},
 {code:"business-activity",routes:["/api/neon/business-partners/:id/360/business-activity"],permission:"neon.relationship.business_partner.read",discoverableWhenDenied:false},
 {code:"network",routes:["/api/neon/business-partners/:id/360/network"],permission:"neon.relationship.business_partner_network.read",discoverableWhenDenied:false},
]);

const requirement=(code:string,fieldCode:string,sectionCode:string,severity:"required"|"recommended",actionCode:string,label:string,requiresVerified=false)=>({code,fieldCode,sectionCode,severity,actionCode,label,...(requiresVerified?{requiresVerified:true}:{})});
const partner360CompletenessPacks=Object.freeze([
 {code:"organization_base",version:1,category:"organization",scope:"global",requirements:[requirement("organization.legal_name","partner.legalName","identity","required","amend_partner","Add legal name"),requirement("organization.lifecycle","partner.lifecycleStatus","identity","required","lifecycle","Review lifecycle"),requirement("organization.primary_address","address.primary","addresses","required","amend_partner","Add primary address",true),requirement("organization.primary_contact","contact.primary","contacts","recommended","amend_partner","Add primary contact",true),requirement("organization.identifier","identifier.primary","identifiers-tax","recommended","amend_partner","Add verified identifier",true),requirement("organization.commercial_role","role.any_commercial","roles-scope","recommended","add_role","Add supplier or customer role")]},
 {code:"supplier_scope",version:1,category:"organization",role:"supplier",scope:"organization",requirements:[requirement("supplier.role","role.supplier","roles-scope","required","add_role","Add supplier role"),requirement("supplier.organization","scope.supplier.organization","roles-scope","required","assign_organization","Assign procurement organization")]},
 {code:"supplier_payable",version:1,category:"organization",role:"supplier",scope:"company",requirements:[requirement("supplier.company","company.supplier.profile","supplier-company","required","configure_company","Configure supplier company"),requirement("supplier.bank","bank.verified_presence","banking","required","change_bank","Verify bank account",true),requirement("supplier.qualification","qualification.current","qualifications-certificates","recommended","qualification","Start qualification",true),requirement("supplier.certificate","certification.current","qualifications-certificates","recommended","certification","Add certification",true)]},
 {code:"customer_scope",version:1,category:"organization",role:"customer",scope:"organization",requirements:[requirement("customer.role","role.customer","roles-scope","required","add_role","Add customer role"),requirement("customer.organization","scope.customer.organization","roles-scope","required","assign_organization","Assign sales organization")]},
 {code:"customer_credit",version:1,category:"organization",role:"customer",scope:"company",requirements:[requirement("customer.company","company.customer.profile","customer-company","required","configure_company","Configure customer company"),requirement("customer.credit","credit.current","credit","recommended","configure_company","Open credit review",true)]},
 {code:"person_base",version:1,category:"person",scope:"global",requirements:[requirement("person.name","person.name","identity","required","amend_partner","Complete personal identity"),requirement("person.contact","contact.primary","contacts","recommended","amend_partner","Add primary contact",true),requirement("person.identifier","person.identifier.verified_presence","identifiers-tax","recommended","amend_partner","Add verified identity",true)]},
 {code:"workforce_active",version:1,category:"person",role:"workforce",scope:"workforce",requirements:[requirement("workforce.role","role.workforce","roles-scope","required","add_role","Add workforce role"),requirement("workforce.employment","employment.active","workforce","required","change_employment","Add active employment",true),requirement("workforce.assignment","assignment.active","workforce","required","change_employment","Add active assignment",true),requirement("workforce.onboarding","onboarding.complete","workforce","recommended","change_employment","Complete onboarding",true)]},
]);
