import type { Authorizer,VerifiedRequestContext } from "@athyper/server-contract-auth";
import {defineRouteContract,registerContractRoute,type Application,type RequestHandler,type Response}from"@athyper/server-runtime-http";
import type{LocalBusinessPartnerDefinitionConsumer}from"./business-partner-definition-consumer.js";

const objectSchema={type:"object",additionalProperties:true}as const;
const active=defineRouteContract({method:"get",path:"/api/neon/business-partner-definitions/active-descriptors",operationId:"neon.activeBusinessPartnerDefinitionDescriptors",summary:"Read verified locally active Business Partner forms and views",tags:["NEON Business Partner Definitions"],authenticated:true,permission:"neon.relationship.business_partner.read",responses:{200:{description:"Pinned local descriptors",body:objectSchema},403:{description:"Forbidden"},503:{description:"No verified local definition"}}});
const activeRequestForm=defineRouteContract({method:"get",path:"/api/neon/business-partner-definitions/active-request-form",operationId:"neon.activeBusinessPartnerRequestForm",summary:"Read the verified locally active Supplier request form",tags:["NEON Business Partner Definitions"],authenticated:true,permission:"neon.relationship.entity_case.create",responses:{200:{description:"Pinned Supplier request form",body:objectSchema},403:{description:"Forbidden"},503:{description:"No verified local definition"}}});

export function registerLocalBusinessPartnerDefinitionRoutes(application:Application,options:{readonly authenticate:RequestHandler;readonly readContext:(response:Response)=>VerifiedRequestContext;readonly authorizer:Authorizer;readonly consumer:LocalBusinessPartnerDefinitionConsumer}){
 registerContractRoute(application,active,options.authenticate,async(_request,response,next)=>{try{const context=options.readContext(response),decision=await options.authorizer.authorize({context,permissionCode:"neon.relationship.business_partner.read"});if(!decision.allowed){response.status(403).json({error:"FORBIDDEN"});return;}response.json(await options.consumer.descriptors());}catch(error){next(error);}});
 registerContractRoute(application,activeRequestForm,options.authenticate,async(_request,response,next)=>{try{const context=options.readContext(response),decision=await options.authorizer.authorize({context,permissionCode:"neon.relationship.entity_case.create"});if(!decision.allowed){response.status(403).json({error:"FORBIDDEN"});return;}const descriptors=await options.consumer.descriptors(),definition=await options.consumer.requestSchema({kind:"new_partner",requestedRole:"supplier",sourceKind:"manual"});response.json({requestForm:{definition,descriptor:descriptors.forms["supplierRequest"]}});}catch(error){next(error);}});
}
