CREATE TABLE master.compensation_assignment (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    employee_id uuid NOT NULL,
    employment_id uuid NOT NULL,
    pay_group_id uuid NOT NULL,
    pay_structure_id uuid,
    currency_code character(3) NOT NULL,
    base_amount numeric(18,4) NOT NULL,
    annualized_amount numeric(18,4),
    effective_from date NOT NULL,
    effective_until date,
    source_compensation_change_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status master.compensation_assignment_status_d NOT NULL DEFAULT 'planned',
    status_changed_at timestamptz,
    status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT compensation_assignment_pkey PRIMARY KEY(id),
    CONSTRAINT compensation_assignment_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT compensation_assignment_code_uq UNIQUE(tenant_id,code),
    CONSTRAINT compensation_assignment_code_chk CHECK(code~'^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$'),
    CONSTRAINT compensation_assignment_amount_chk CHECK(base_amount>=0 AND (annualized_amount IS NULL OR annualized_amount>=0)),
    CONSTRAINT compensation_assignment_dates_chk CHECK(effective_until IS NULL OR effective_until>=effective_from),
    CONSTRAINT compensation_assignment_metadata_chk CHECK(jsonb_typeof(metadata)='object'),
    CONSTRAINT compensation_assignment_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT compensation_assignment_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

COMMENT ON TABLE master.compensation_assignment IS
  'Immutable effective-dated employee compensation fact. Approved compensation changes create a new assignment and supersede the prior row.';
