#!/usr/bin/env tsx

import { readFile, rename, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { Client } from "pg";
import { evaluateBusinessPartner360P0ApprovalFile } from "./evaluate-business-partner-360-p0-approvals.js";
import { evaluateBusinessPartner360P1QualificationFiles } from "./evaluate-business-partner-360-p1-qualification.js";

const FLAG="neon.business_partner.view_360",GATES=["functional","data","security_privacy","contract","performance","resilience","ux","operations"] as const;
type Stage="internal"|"canary"|"broad";
export async function recordBusinessPartner360RolloutObservation(options:{stage:Stage;startedAt:string;databaseUrl:string;prometheusUrl:string;cohortsPath:string;approvalsPath:string;p0Path:string;p1Path:string;observationsPath:string;confirmation?:string}){
  const expected=`RECORD-BP360-${options.stage.toUpperCase()}-OBSERVATION`;
  if(options.confirmation!==expected)throw new Error(`recording requires --confirm=${expected}`);
  assertDatabase(options.databaseUrl);
  const started=Date.parse(options.startedAt),now=Date.now();
  if(!Number.isFinite(started)||started>=now)throw new Error("--started-at must be an offset-aware past timestamp");
  const observationMinutes=Math.floor((now-started)/60000),minimum=options.stage==="internal"?60:options.stage==="canary"?1440:10080;
  if(observationMinutes<minimum)throw new Error(`${options.stage} observation requires at least ${minimum} minutes`);
  const root=resolve(import.meta.dirname,"../../.."),cohorts=JSON.parse(await readFile(resolve(root,options.cohortsPath),"utf8")),approvals=JSON.parse(await readFile(resolve(root,options.approvalsPath),"utf8")).approvals.filter((item:any)=>item.status==="approved");
  for(const gate of GATES)if(approvals.filter((item:any)=>item.gate===gate).length!==1)throw new Error(`${gate} approval is missing or duplicate`);
  const p0=await evaluateBusinessPartner360P0ApprovalFile(resolve(root,options.p0Path),root),p1=await evaluateBusinessPartner360P1QualificationFiles(resolve(root,options.p1Path),resolve(root,options.approvalsPath),root);
  if(!p0.p0Closed)throw new Error("P0 is not closed");
  if(!p1.releaseReady)throw new Error("P1 is not release ready");
  await assertStage(options.databaseUrl,options.stage,cohorts);
  const window=`${Math.ceil((now-started)/1000)}s`,read=(query:string)=>prom(options.prometheusUrl,query),[requestCount,summaryP95Ms,sectionP95Ms,errorRate,meshFallbackRate,summaryPayloadP95Bytes,sectionPayloadP95Bytes,definitionUnavailableCount,legacyCalls]=await Promise.all([
    read(`sum(increase(athyper_bp360_request_total[${window}]))`),read(`histogram_quantile(0.95,sum by(le)(rate(athyper_bp360_duration_ms_bucket{operation="summary"}[${window}])))`),read(`histogram_quantile(0.95,sum by(le)(rate(athyper_bp360_duration_ms_bucket{operation="section"}[${window}])))`),read(`sum(rate(athyper_bp360_request_total{outcome="failure"}[${window}]))/clamp_min(sum(rate(athyper_bp360_request_total[${window}])),0.001)`),read(`sum(rate(athyper_bp360_mesh_fallback_total[${window}]))/clamp_min(sum(rate(athyper_bp360_request_total{section="network"}[${window}])),0.001)`),read(`histogram_quantile(0.95,sum by(le)(rate(athyper_bp360_payload_bytes_bucket{operation="summary"}[${window}])))`),read(`histogram_quantile(0.95,sum by(le)(rate(athyper_bp360_payload_bytes_bucket{operation="section"}[${window}])))`),read(`sum(increase(athyper_bp360_completeness_total{status="definition_unavailable"}[${window}]))`),read(`sum(increase(athyper_business_partner_request_http_total{operation="get-aggregate"}[${window}]))`),
  ]);const passed=(gate:typeof GATES[number])=>approvals.some((item:any)=>item.gate===gate),evidence={stage:options.stage,capturedAt:new Date(now).toISOString(),observationStartedAt:new Date(started).toISOString(),observationMinutes,requestCount:Math.floor(requestCount),summaryP95Ms,sectionP95Ms,errorRate,meshFallbackRate,summaryPayloadP95Bytes,sectionPayloadP95Bytes,definitionUnavailableCount:Math.floor(definitionUnavailableCount),functionalPassed:passed("functional"),dataPassed:passed("data"),securityPrivacyPassed:passed("security_privacy"),contractPassed:passed("contract"),performancePassed:passed("performance"),resiliencePassed:passed("resilience"),uxPassed:passed("ux"),operationsPassed:passed("operations"),approvals,legacyAggregateCalls:Math.floor(legacyCalls)};const destination=resolve(root,options.observationsPath),document=JSON.parse(await readFile(destination,"utf8"));if(!Array.isArray(document.observations))throw new Error("observation ledger is invalid");document.observations.push(evidence);const temporary=`${destination}.tmp-${process.pid}`;await writeFile(temporary,`${JSON.stringify(document,null,2)}\n`,{mode:0o600});await rename(temporary,destination);return evidence;
}
async function assertStage(databaseUrl:string,stage:Stage,cohorts:{internal:string[];canary:string[]}){const client=new Client({connectionString:databaseUrl,application_name:"bp360-rollout-observer"});await client.connect();try{const flag=(await client.query(`SELECT rollout_pct "rolloutPct" FROM control.feature_flag_catalog WHERE code=$1 AND status='active'`,[FLAG])).rows[0];if(!flag)throw new Error("BP360 feature flag is absent");const enabled=(await client.query(`SELECT tenant.code FROM control.feature_flag_override override JOIN control.feature_flag_catalog flag ON flag.id=override.feature_flag_id JOIN master.tenant tenant ON tenant.id=override.tenant_id WHERE flag.code=$1 AND override.status='active' AND override.is_enabled ORDER BY tenant.code`,[FLAG])).rows.map(row=>String(row.code)),expected=(stage==="internal"?cohorts.internal:[...cohorts.internal,...cohorts.canary]).sort();if(enabled.length!==expected.length||enabled.some((code,index)=>code!==expected[index]))throw new Error(`${stage} enabled tenant set does not match the named cohort`);if(stage!=="broad"&&flag.rolloutPct!==0)throw new Error(`${stage} rollout percentage is invalid`);if(stage==="broad"&&flag.rolloutPct!==100)throw new Error("broad rollout is not enabled");}finally{await client.end();}}
async function prom(base:string,query:string){const url=new URL("/api/v1/query",base);url.searchParams.set("query",query);const response=await fetch(url,{headers:{accept:"application/json"},signal:AbortSignal.timeout(10_000)});if(!response.ok)throw new Error(`Prometheus query failed: ${response.status}`);const body=await response.json() as any,value=body?.data?.result?.[0]?.value?.[1],number=Number(value);if(body?.status!=="success"||!Number.isFinite(number))throw new Error(`Prometheus returned no finite sample for ${query.split("[")[0]}`);return number;}
function assertDatabase(value:string){const url=new URL(value);if(!["127.0.0.1","localhost","::1"].includes(url.hostname)||url.pathname!=="/athyper_neon")throw new Error("this build-stage observer accepts only local disposable athyper_neon");}function option(args:string[],name:string){return args.find(value=>value.startsWith(`${name}=`))?.slice(name.length+1);}function stage(value:string|undefined):Stage{if(value!=="internal"&&value!=="canary"&&value!=="broad")throw new Error("--stage must be internal|canary|broad");return value;}
if(import.meta.url===pathToFileURL(process.argv[1]??"").href){const args=process.argv.slice(2),databaseUrl=option(args,"--database-url")??process.env["ATHYPER_NEON_DATABASE_ADMIN_URL"];if(!databaseUrl)throw new Error("--database-url is required");process.stdout.write(`${JSON.stringify(await recordBusinessPartner360RolloutObservation({stage:stage(option(args,"--stage")),startedAt:option(args,"--started-at")??"",databaseUrl,prometheusUrl:option(args,"--prometheus-url")??"http://127.0.0.1:53900",cohortsPath:option(args,"--cohorts")??"docs/architecture/evidence/business-partner-360-rollout-cohorts.json",approvalsPath:option(args,"--approvals")??"docs/architecture/evidence/business-partner-360-release-approvals.json",p0Path:option(args,"--p0")??"docs/architecture/evidence/business-partner-360-p0-approvals.json",p1Path:option(args,"--p1")??"docs/architecture/evidence/business-partner-360-p1-qualification.json",observationsPath:option(args,"--observations")??"docs/architecture/evidence/business-partner-360-rollout-observations.json",confirmation:option(args,"--confirm")}),null,2)}\n`);}
