"use client";

import type { CatalogWorkspaceRoute } from "@athyper/contract-platform-navigation";
import { HomeIcon, MoreHorizontalIcon, resolveIcon, SearchIcon, StarIcon } from "@athyper/platform-icons";
import { useEffect, useLayoutEffect, useRef, useState } from "react";

export function WorkspaceModuleTabs({workspace,workspaceName,orderedModuleCodes,pinnedModuleCodes,activeModuleCode,badges={},onTogglePinned}:{readonly workspace:CatalogWorkspaceRoute;readonly workspaceName:string;readonly orderedModuleCodes:readonly string[];readonly pinnedModuleCodes:readonly string[];readonly activeModuleCode?:string;readonly badges?:Readonly<Record<string,string>>;readonly onTogglePinned:(moduleCode:string)=>void}){
  const byCode=new Map(workspace.modules.map((module)=>[module.code,module])),ordered=orderedModuleCodes.flatMap((code)=>{const module=byCode.get(code);return module?[module]:[]}),{container,limit}=useFittingModuleTabLimit(ordered.length,activeModuleCode),visible=visibleModules(ordered,limit,activeModuleCode),visibleCodes=new Set(visible.map((module)=>module.code)),overflow=ordered.filter((module)=>!visibleCodes.has(module.code)),tabs=[{code:"home",name:"Home",href:`/${workspace.routeSlug}`,iconKey:"home"},...visible.map((module)=>({code:module.code,name:module.name,href:`/${workspace.routeSlug}/${module.routeSlug}`,iconKey:module.iconKey??"info"}))];
  return <nav ref={container} className="athyper-experience__module-tabs athyper-experience__module-tabs--primary" aria-label={`${workspaceName} modules`}>{tabs.map((tab)=>{const active=tab.code===(activeModuleCode??"home"),Icon=tab.code==="home"?HomeIcon:resolveIcon(tab.iconKey);return <a key={tab.code} href={tab.href} aria-current={active?"page":undefined}><Icon size={17}/><span>{tab.name}</span></a>;})}{overflow.length?<ModuleMoreMenu workspaceRouteSlug={workspace.routeSlug} modules={overflow} pinnedModuleCodes={pinnedModuleCodes} badges={badges} onTogglePinned={onTogglePinned}/>:null}</nav>;
}

function ModuleMoreMenu({workspaceRouteSlug,modules,pinnedModuleCodes,badges,onTogglePinned}:{readonly workspaceRouteSlug:string;readonly modules:readonly CatalogWorkspaceRoute["modules"][number][];readonly pinnedModuleCodes:readonly string[];readonly badges:Readonly<Record<string,string>>;readonly onTogglePinned:(moduleCode:string)=>void}){const details=useRef<HTMLDetailsElement>(null),search=useRef<HTMLInputElement>(null),[query,setQuery]=useState(""),normalized=query.trim().toLocaleLowerCase(),matches=modules.filter((module)=>!normalized||`${module.name} ${module.code}`.toLocaleLowerCase().includes(normalized));useEffect(()=>{const close=(event:PointerEvent)=>{if(details.current?.open&&!details.current.contains(event.target as Node))details.current.open=false;},escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&details.current?.open){event.preventDefault();details.current.open=false;details.current.querySelector("summary")?.focus();}};window.addEventListener("pointerdown",close);window.addEventListener("keydown",escape);return()=>{window.removeEventListener("pointerdown",close);window.removeEventListener("keydown",escape);};},[]);return <details ref={details} className="athyper-experience__module-more" onToggle={(event)=>{if(event.currentTarget.open)requestAnimationFrame(()=>search.current?.focus());else setQuery("");}}><summary><MoreHorizontalIcon size={17}/><span>More</span><b>{modules.length}</b></summary><section><label><SearchIcon size={16}/><span className="athyper-visually-hidden">Search more modules</span><input ref={search} type="search" placeholder="Search modules" value={query} onChange={(event)=>setQuery(event.currentTarget.value)} autoComplete="off"/></label><p aria-live="polite">{matches.length} {matches.length===1?"module":"modules"}</p><ul>{matches.map((module)=>{const Icon=resolveIcon(module.iconKey??"info"),pinned=pinnedModuleCodes.includes(module.code);return <li key={module.code}><a href={`/${workspaceRouteSlug}/${module.routeSlug}`}><Icon size={18}/><span><strong>{module.name}</strong>{badges[module.code]?<small>{badges[module.code]}</small>:null}</span></a><button type="button" aria-label={`${pinned?"Unpin":"Pin"} ${module.name}`} aria-pressed={pinned} title={pinned?"Unpin module":"Pin module"} onClick={()=>onTogglePinned(module.code)}><StarIcon size={17} data-filled={pinned?"true":undefined}/></button></li>;})}</ul>{!matches.length?<div className="athyper-experience__module-more-empty">No matching modules</div>:null}</section></details>;}
function useFittingModuleTabLimit(moduleCount:number,activeModuleCode?:string){const container=useRef<HTMLElement>(null),[limit,setLimit]=useState(moduleCount);useLayoutEffect(()=>{setLimit(moduleCount);},[moduleCount,activeModuleCode]);useLayoutEffect(()=>{const element=container.current;if(element&&element.scrollWidth>element.clientWidth+1&&limit>0)setLimit((current)=>Math.max(0,current-1));},[limit,moduleCount,activeModuleCode]);useEffect(()=>{const element=container.current;if(!element||typeof ResizeObserver==="undefined")return;const observer=new ResizeObserver(()=>setLimit(moduleCount));observer.observe(element);return()=>observer.disconnect();},[moduleCount]);return{container,limit};}
function visibleModules<T extends{readonly code:string}>(modules:readonly T[],limit:number,activeModuleCode?:string):readonly T[]{const visible=modules.slice(0,limit);if(!activeModuleCode||visible.some((module)=>module.code===activeModuleCode))return visible;const active=modules.find((module)=>module.code===activeModuleCode);return active?[...visible.slice(0,Math.max(0,limit-1)),active]:visible;}

export function moduleBadgesFromItems(workspace:CatalogWorkspaceRoute,items:readonly Readonly<{href?:string}>[]):Readonly<Record<string,string>>{const counts:Record<string,number>={};for(const item of items){const href=item.href;if(!href)continue;const module=workspace.modules.find((candidate)=>href===`/${workspace.routeSlug}/${candidate.routeSlug}`||href.startsWith(`/${workspace.routeSlug}/${candidate.routeSlug}/`));if(module)counts[module.code]=(counts[module.code]??0)+1;}return Object.freeze(Object.fromEntries(Object.entries(counts).map(([code,count])=>[code,`${count} open`])));}
