"use client";

import { type HttpClient } from "@athyper/platform-api-client";
import { consumeNotificationStream, createNotificationClient, type NotificationItem } from "@athyper/platform-communications-notifications-client";
import type { ShellActivityDataSource, ShellInboxItem, ShellNotificationItem, ShellNotificationTone, ShellPushEnrollmentStatus } from "@athyper/platform-shell";
import { createWorkInboxClient, type WorkItem } from "@athyper/platform-shell-work-inbox";
import { createContext, createElement, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";

export interface ActivityCenterOptions { readonly client: HttpClient; readonly locale?: string; readonly notificationLimit?: number; readonly inboxLimit?: number; }
const ActivityCenterContext=createContext<ShellActivityDataSource|undefined>(undefined);
const PUSH_DEVICE_ID_KEY="athyper.notifications.device-id",PUSH_SUBSCRIPTION_ID_KEY="athyper.notifications.push-subscription-id";
export function ActivityCenterDataProvider({value,children}:{readonly value:ShellActivityDataSource;readonly children:ReactNode}){return createElement(ActivityCenterContext.Provider,{value},children);}
export function useActivityCenterData():ShellActivityDataSource{const value=useContext(ActivityCenterContext);if(!value)throw new Error("useActivityCenterData must be used inside ActivityCenterDataProvider");return value;}

export function useActivityCenterDataSource({client,locale="en",notificationLimit=50,inboxLimit=50}:ActivityCenterOptions):ShellActivityDataSource {
  const notificationsClient=useMemo(()=>createNotificationClient(client),[client]),inboxClient=useMemo(()=>createWorkInboxClient(client),[client]);
  const [notifications,setNotifications]=useState<readonly NotificationItem[]>([]),[workItems,setWorkItems]=useState<readonly WorkItem[]>([]),[notificationCursor,setNotificationCursor]=useState<string>(),[inboxCursor,setInboxCursor]=useState<string>(),[unreadCount,setUnreadCount]=useState(0),[openInboxCount,setOpenInboxCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState<string>(),[revision,setRevision]=useState(0),[pushEnrollmentStatus,setPushEnrollmentStatus]=useState<ShellPushEnrollmentStatus>("checking"),[pushEnrollmentError,setPushEnrollmentError]=useState<string>();
  const pushPublicKey=useRef<string|undefined>(undefined);
  const mounted=useRef(true);
  const refresh=useCallback(()=>setRevision((value)=>value+1),[]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError(undefined);Promise.all([notificationsClient.list({limit:notificationLimit,signal:controller.signal}),inboxClient.list({limit:inboxLimit,statuses:["open","claimed","in_progress","blocked"],signal:controller.signal})]).then(([notificationPage,inboxPage])=>{if(controller.signal.aborted)return;setNotifications(notificationPage.notifications);setNotificationCursor(notificationPage.nextCursor);setUnreadCount(notificationPage.unreadCount);setWorkItems(inboxPage.data);setInboxCursor(inboxPage.nextCursor);setOpenInboxCount(inboxPage.totalCount);setLoading(false);}).catch((cause:unknown)=>{if(controller.signal.aborted)return;setError(activityError(cause));setLoading(false);});return()=>controller.abort();},[notificationsClient,inboxClient,notificationLimit,inboxLimit,revision]);
  useEffect(()=>{const controller=new AbortController();let reconnectTimer:ReturnType<typeof setTimeout>|undefined,attempt=0;const connect=async()=>{try{const stream=await notificationsClient.stream(controller.signal);attempt=0;await consumeNotificationStream(stream,refresh,controller.signal);}catch{if(controller.signal.aborted)return;}if(!controller.signal.aborted){const delay=Math.min(30_000,1_000*2**Math.min(attempt++,5));reconnectTimer=setTimeout(()=>void connect(),delay);}};void connect();const poll=setInterval(refresh,60_000);const visible=()=>{if(document.visibilityState==="visible")refresh();};document.addEventListener("visibilitychange",visible);return()=>{controller.abort();clearInterval(poll);if(reconnectTimer)clearTimeout(reconnectTimer);document.removeEventListener("visibilitychange",visible);};},[notificationsClient,refresh]);
  useEffect(()=>{const controller=new AbortController();const inspect=async()=>{if(!supportsWebPush()){setPushEnrollmentStatus("unsupported");return;}if(Notification.permission==="denied"){setPushEnrollmentStatus("denied");return;}try{const configuration=await notificationsClient.pushConfiguration(controller.signal);if(controller.signal.aborted)return;if(!configuration.webPush.available||!configuration.webPush.publicKey){setPushEnrollmentStatus("unavailable");return;}pushPublicKey.current=configuration.webPush.publicKey;const registration=await navigator.serviceWorker.getRegistration("/"),subscription=await registration?.pushManager.getSubscription(),serverId=localStorage.getItem(PUSH_SUBSCRIPTION_ID_KEY);if(controller.signal.aborted)return;setPushEnrollmentStatus(subscription&&serverId?"enabled":"prompt");}catch(cause:unknown){if(controller.signal.aborted)return;setPushEnrollmentError(activityError(cause));setPushEnrollmentStatus("error");}};void inspect();return()=>controller.abort();},[notificationsClient]);

  const markRead=useCallback(async(item:ShellNotificationItem)=>{const current=notifications.find((value)=>value.id===item.id);if(!current||current.readAt)return;const readAt=new Date().toISOString();setNotifications((items)=>items.map((value)=>value.id===item.id?{...value,readAt}:value));setUnreadCount((value)=>Math.max(0,value-1));try{await notificationsClient.markRead(item.id);}catch{if(mounted.current)refresh();}},[notifications,notificationsClient,refresh]);
  const markAllRead=useCallback(async()=>{const readAt=new Date().toISOString();setNotifications((items)=>items.map((value)=>value.readAt?value:{...value,readAt}));setUnreadCount(0);try{await notificationsClient.markAllRead();}catch{if(mounted.current)refresh();}},[notificationsClient,refresh]);
  const complete=useCallback(async(item:ShellInboxItem)=>{const current=workItems.find((value)=>value.id===item.id);if(!current)return;setWorkItems((items)=>items.filter((value)=>value.id!==item.id));setOpenInboxCount((value)=>Math.max(0,value-1));try{const result=await inboxClient.act({id:current.id,action:"complete",currentRowVersion:current.rowVersion,idempotencyKey:`activity-complete:${current.id}:${current.rowVersion}`});if(result.kind!=="Committed")throw new Error(`Work item was not completed: ${result.kind}`);}catch{if(mounted.current)refresh();}},[workItems,inboxClient,refresh]);
  const loadMoreNotifications=useCallback(async()=>{if(!notificationCursor)return;const page=await notificationsClient.list({limit:notificationLimit,cursor:notificationCursor});if(!mounted.current)return;setNotifications((items)=>mergeById(items,page.notifications));setNotificationCursor(page.nextCursor);setUnreadCount(page.unreadCount);},[notificationCursor,notificationsClient,notificationLimit]);
  const loadMoreInbox=useCallback(async()=>{if(!inboxCursor)return;const page=await inboxClient.list({limit:inboxLimit,cursor:inboxCursor,statuses:["open","claimed","in_progress","blocked"]});if(!mounted.current)return;setWorkItems((items)=>mergeById(items,page.data));setInboxCursor(page.nextCursor);setOpenInboxCount(page.totalCount);},[inboxCursor,inboxClient,inboxLimit]);
  const enableBrowserPush=useCallback(async()=>{if(!supportsWebPush()){setPushEnrollmentStatus("unsupported");return;}setPushEnrollmentError(undefined);try{const permission=Notification.permission==="granted"?"granted":await Notification.requestPermission();if(permission!=="granted"){setPushEnrollmentStatus(permission==="denied"?"denied":"prompt");return;}let publicKey=pushPublicKey.current;if(!publicKey){const configuration=await notificationsClient.pushConfiguration();publicKey=configuration.webPush.publicKey;if(!configuration.webPush.available||!publicKey){setPushEnrollmentStatus("unavailable");return;}pushPublicKey.current=publicKey;}const applicationServerKey=decodeVapidPublicKey(publicKey);const registration=await navigator.serviceWorker.register("/notification-sw.js",{scope:"/"});const subscription=await registration.pushManager.getSubscription()??await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey});const serialized=subscription.toJSON(),record=await notificationsClient.subscribePush({platform:"web",deviceId:pushDeviceId(),endpoint:subscription.endpoint,...(serialized.keys?.p256dh?{p256dhKey:serialized.keys.p256dh}:{}),...(serialized.keys?.auth?{authKey:serialized.keys.auth}:{})});localStorage.setItem(PUSH_SUBSCRIPTION_ID_KEY,record.id);setPushEnrollmentStatus("enabled");}catch(cause:unknown){setPushEnrollmentError(activityError(cause));setPushEnrollmentStatus("error");}},[notificationsClient]);
  const disableBrowserPush=useCallback(async()=>{setPushEnrollmentError(undefined);try{const registration=await navigator.serviceWorker.getRegistration("/"),subscription=await registration?.pushManager.getSubscription(),serverId=localStorage.getItem(PUSH_SUBSCRIPTION_ID_KEY);if(subscription)await subscription.unsubscribe();if(serverId)await notificationsClient.unsubscribePush(serverId);localStorage.removeItem(PUSH_SUBSCRIPTION_ID_KEY);setPushEnrollmentStatus(Notification.permission==="denied"?"denied":"prompt");}catch(cause:unknown){setPushEnrollmentError(activityError(cause));setPushEnrollmentStatus("error");}},[notificationsClient]);
  return useMemo(()=>({notifications:notifications.map((item)=>toShellNotification(item,locale)),inbox:workItems.map((item)=>toShellInbox(item,locale)),unreadNotificationCount:unreadCount,openInboxCount,hasMoreNotifications:Boolean(notificationCursor),hasMoreInbox:Boolean(inboxCursor),loading,error,pushEnrollmentStatus,pushEnrollmentError,notificationsHref:"/notifications",inboxHref:"/inbox",onRetry:refresh,onMarkNotificationRead:markRead,onMarkAllNotificationsRead:markAllRead,onCompleteInboxItem:complete,onLoadMoreNotifications:loadMoreNotifications,onLoadMoreInbox:loadMoreInbox,onEnableBrowserPush:enableBrowserPush,onDisableBrowserPush:disableBrowserPush}),[notifications,workItems,notificationCursor,inboxCursor,unreadCount,openInboxCount,loading,error,pushEnrollmentStatus,pushEnrollmentError,locale,refresh,markRead,markAllRead,complete,loadMoreNotifications,loadMoreInbox,enableBrowserPush,disableBrowserPush]);
}

function toShellNotification(item:NotificationItem,locale:string):ShellNotificationItem{return Object.freeze({id:item.id,title:item.title,...(item.body?{detail:item.body}:{}),sourceLabel:sourceLabel(item.eventCode),groupLabel:dateGroup(item.createdAt,locale),timestamp:item.createdAt,timestampLabel:relativeTime(item.createdAt,locale),...(safeHref(item.href)?{href:item.href}:{}),unread:!item.readAt,tone:tone(item)});}
function toShellInbox(item:WorkItem,locale:string):ShellInboxItem{const href=payloadHref(item.payload);return Object.freeze({id:item.id,title:item.title,...(item.description?{detail:item.description}:{}),sourceLabel:humanize(item.workTypeCode),...(item.assigneePrincipalId?{assigneeLabel:"Assigned to you"}:{}),...(item.dueAt?{dueLabel:dueLabel(item.dueAt,locale)}:{}),groupLabel:dateGroup(item.createdAt,locale),...(href?{href}:{}),priority:item.priority==="urgent"?"urgent":item.priority==="high"?"high":"normal"});}
function tone(item:NotificationItem):ShellNotificationTone{if(item.priority==="urgent")return"critical";if(item.priority==="high")return"warning";if(/(?:completed|approved|success|passed)/.test(item.eventCode))return"success";return"info";}
function sourceLabel(eventCode:string):string{return humanize(eventCode.split(".")[0]??eventCode);}
function humanize(value:string):string{return value.replace(/[._-]+/g," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());}
function safeHref(value:string|undefined):value is string{return Boolean(value&&value.startsWith("/")&&!value.startsWith("//")&&!value.includes("\\"));}
function payloadHref(payload:Readonly<Record<string,unknown>>):string|undefined{for(const key of ["href","entity_href","action_url"]){const value=payload[key];if(typeof value==="string"&&safeHref(value))return value;}return undefined;}
function safeLocale(locale:string):string{try{return Intl.getCanonicalLocales(locale)[0]??"en";}catch{return"en";}}
function dateGroup(value:string,locale:string):string{const date=new Date(value),now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime(),day=new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime(),difference=Math.round((start-day)/86_400_000);if(difference===0)return"Today";if(difference===1)return"Yesterday";if(difference<7)return"This week";return new Intl.DateTimeFormat(safeLocale(locale),{month:"long",year:"numeric"}).format(date);}
function relativeTime(value:string,locale:string):string{const delta=new Date(value).getTime()-Date.now(),absolute=Math.abs(delta),formatter=new Intl.RelativeTimeFormat(safeLocale(locale),{numeric:"auto"});if(absolute<60_000)return formatter.format(Math.round(delta/1_000),"second");if(absolute<3_600_000)return formatter.format(Math.round(delta/60_000),"minute");if(absolute<86_400_000)return formatter.format(Math.round(delta/3_600_000),"hour");return formatter.format(Math.round(delta/86_400_000),"day");}
function dueLabel(value:string,locale:string):string{const delta=new Date(value).getTime()-Date.now();if(delta<0)return`Overdue ${relativeTime(value,locale).replace(" ago","")}`;return`Due ${relativeTime(value,locale)}`;}
function activityError(cause:unknown):string{return cause instanceof Error&&cause.message?cause.message:"Activity is temporarily unavailable.";}
function mergeById<T extends {readonly id:string}>(current:readonly T[],next:readonly T[]):readonly T[]{const seen=new Set(current.map((item)=>item.id));return Object.freeze([...current,...next.filter((item)=>!seen.has(item.id))]);}
function supportsWebPush():boolean{return typeof window!=="undefined"&&"Notification" in window&&"serviceWorker" in navigator&&"PushManager" in window;}
export function decodeVapidPublicKey(value:string):Uint8Array<ArrayBuffer>{const padding="=".repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,"+").replace(/_/g,"/"),bytes=atob(base64),result=new Uint8Array(new ArrayBuffer(bytes.length));for(let index=0;index<bytes.length;index+=1)result[index]=bytes.charCodeAt(index);return result;}
function pushDeviceId():string{const current=localStorage.getItem(PUSH_DEVICE_ID_KEY);if(current)return current;const generated=globalThis.crypto?.randomUUID?.()??`web-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(PUSH_DEVICE_ID_KEY,generated);return generated;}
