"use client";

import { ApiTransportError, meshNetworkAccountsOperation, updatePrincipalLocaleOperation, type MeshNetworkAccount, type MeshNetworkAccountCatalog } from "@athyper/platform-api-client";
import { useApiClient } from "@athyper/platform-shell-app-foundation";
import { CheckIcon } from "@athyper/platform-icons";
import { ActivityCenterDataProvider, useActivityCenterDataSource } from "@athyper/platform-shell-activity-center-data";
import { PlatformShell, ShellContextPickerPanel, ShellContextSelector, deriveShellNavigation, type NavigationDiagnostic, type PlatformShellProps, type ShellExperienceInput } from "@athyper/platform-shell";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { meshRoutes } from "./navigation";
export { meshRoutes } from "./navigation";

type MeshBootstrap = ShellExperienceInput & { readonly tenantId:string;readonly localization?:PlatformShellProps["localization"];readonly localePolicy?:PlatformShellProps["localePolicy"];readonly identity?:Readonly<{displayName:string;secondaryLabel?:string;initials?:string}>;readonly tenant?:Readonly<{code:string;displayName:string;countryCode?:string;logoAssetRef?:string}> };
export interface MeshAccountContextValue { readonly status:"loading"|"ready"|"error";readonly accounts:readonly MeshNetworkAccount[];readonly selected?:MeshNetworkAccount;readonly automaticallyResolved:boolean;readonly errorRequestId?:string;select(networkAccountId:string):void;retry():void; }
export interface MeshAccountContextDiagnostic { readonly event:"catalog_loaded"|"catalog_failed"|"selection_changed"|"selection_invalidated";readonly tenantId:string;readonly principalId:string;readonly accountCount?:number;readonly networkAccountId?:string;readonly reason?:"stored_not_permitted"|"tenant_mismatch"|"request_failed";readonly requestId?:string; }

const AccountContext=createContext<MeshAccountContextValue|undefined>(undefined);
const LABELS={actingAs:"Acting as",loading:"Resolving account",unavailable:"Account context is unavailable",retry:"Try again",none:"No authorized network accounts",choose:"Choose buyer or supplier account",search:"Search accounts",buyer:"Buyer accounts",supplier:"Supplier accounts",both:"Buyer & supplier accounts",related:"Related account records",support:"Support reference"} as const;

export function MeshShell({bootstrap,principalId,initialCollapsed,children,onNavigationDiagnostic,onAccountContextDiagnostic}:{readonly bootstrap:MeshBootstrap;readonly principalId:string;readonly initialCollapsed?:boolean;readonly children:ReactNode;readonly onNavigationDiagnostic?:(event:NavigationDiagnostic)=>void;readonly onAccountContextDiagnostic?:(event:MeshAccountContextDiagnostic)=>void}) {
  const client=useApiClient(),activity=useActivityCenterDataSource({client});
  const diagnostic=useMemo(()=>onNavigationDiagnostic??planeDiagnostic("mesh"),[onNavigationDiagnostic]);
  const navigation=useMemo(()=>deriveShellNavigation(meshRoutes,bootstrap,diagnostic),[bootstrap,diagnostic]);
  return <MeshAccountContextProvider tenantId={bootstrap.tenantId} principalId={principalId} onDiagnostic={onAccountContextDiagnostic??developmentAccountDiagnostic}>
    {(account)=><PlatformShell localization={bootstrap.localization} localePolicy={bootstrap.localePolicy} onLocaleChange={(locale)=>changeLocale(client,locale)} activity={activity} applicationName="Mesh" planeDescriptor="Business Collaboration Network" planeIconSrc="/brand/mesh/app-icon.png" planeWordmarkSrc="/brand/mesh/identity-lockup.svg" initialCollapsed={initialCollapsed} tenantId={bootstrap.tenantId} principalId={principalId} tenantLabel={bootstrap.tenant?.displayName ?? bootstrap.tenantId} tenantSecondaryLabel={bootstrap.tenant?.code.toUpperCase()} tenantCountryCode={bootstrap.tenant?.countryCode} tenantLogoAssetRef={bootstrap.tenant?.logoAssetRef} contextLabel="Business context" showOrganizationContext={false} accountLabel={bootstrap.identity?.displayName ?? principalId} accountInitials={bootstrap.identity?.initials} accountLoginId={bootstrap.identity?.secondaryLabel} accountEmail={bootstrap.identity?.secondaryLabel?.includes("@")?bootstrap.identity.secondaryLabel:undefined} transactionContext={meshTransactionContext(account)} workContextControl={<MeshAccountSelector value={account}/>} navigation={navigation}><ActivityCenterDataProvider value={activity}>{children}</ActivityCenterDataProvider></PlatformShell>}
  </MeshAccountContextProvider>;
}

function MeshAccountContextProvider({tenantId,principalId,onDiagnostic,children}:{readonly tenantId:string;readonly principalId:string;readonly onDiagnostic:(event:MeshAccountContextDiagnostic)=>void;readonly children:(value:MeshAccountContextValue)=>ReactNode}){
  const client=useApiClient(),[catalog,setCatalog]=useState<MeshNetworkAccountCatalog>(),[error,setError]=useState<ApiTransportError>(),[attempt,setAttempt]=useState(0),[selectedId,setSelectedId]=useState<string>(),[automaticallyResolved,setAutomaticallyResolved]=useState(false);
  const key=`athyper.mesh.network-account.v1:${tenantId}:${principalId}`;
  useEffect(()=>{const controller=new AbortController();setCatalog(undefined);setError(undefined);client.request(meshNetworkAccountsOperation,{signal:controller.signal}).then((value)=>{if(value.tenantId!==tenantId){onDiagnostic({event:"catalog_failed",tenantId,principalId,reason:"tenant_mismatch"});throw new Error("Network-account response does not match the active tenant");}setCatalog(value);let restored:string|undefined;try{const candidate=localStorage.getItem(key);if(candidate&&value.accounts.some((account)=>account.networkAccountId===candidate))restored=candidate;else if(candidate){localStorage.removeItem(key);onDiagnostic({event:"selection_invalidated",tenantId,principalId,reason:"stored_not_permitted"});}}catch{localStorage.removeItem(key);}const neonBuyers=value.accounts.filter((account)=>account.source==="neon_projection"&&(account.role==="buyer"||account.role==="both"));const inferred=!restored?(value.accounts.length===1?value.accounts[0]!.networkAccountId:neonBuyers.length===1?neonBuyers[0]!.networkAccountId:undefined):undefined;const initial=restored??inferred;setSelectedId(initial);setAutomaticallyResolved(Boolean(inferred));if(initial)localStorage.setItem(key,initial);onDiagnostic({event:"catalog_loaded",tenantId,principalId,accountCount:value.accounts.length,...(initial?{networkAccountId:initial}:{})});}).catch((cause)=>{if(controller.signal.aborted)return;const transport=cause instanceof ApiTransportError?cause:new ApiTransportError("parse",LABELS.unavailable);setError(transport);onDiagnostic({event:"catalog_failed",tenantId,principalId,reason:"request_failed",...(transport.requestId?{requestId:transport.requestId}:{})});});return()=>controller.abort();},[client,tenantId,principalId,key,attempt,onDiagnostic]);
  const select=useCallback((networkAccountId:string)=>{if(!catalog?.accounts.some((account)=>account.networkAccountId===networkAccountId))return;setSelectedId(networkAccountId);setAutomaticallyResolved(false);localStorage.setItem(key,networkAccountId);onDiagnostic({event:"selection_changed",tenantId,principalId,networkAccountId});},[catalog,key,tenantId,principalId,onDiagnostic]);
  const selected=selectedId?catalog?.accounts.find((account)=>account.networkAccountId===selectedId):undefined;
  const value=useMemo<MeshAccountContextValue>(()=>({status:error?"error":catalog?"ready":"loading",accounts:catalog?.accounts??[],...(selected?{selected}:{}),automaticallyResolved,...(error?.requestId?{errorRequestId:error.requestId}:{}),select,retry:()=>setAttempt((value)=>value+1)}),[catalog,error,selected,automaticallyResolved,select]);
  return <AccountContext.Provider value={value}>{children(value)}</AccountContext.Provider>;
}

function MeshAccountSelector({value}:{readonly value:MeshAccountContextValue}){
  const [query,setQuery]=useState("");
  if(value.status==="loading")return <span className="mesh-account-context" role="status">{LABELS.loading}</span>;
  if(value.status==="error")return <span className="mesh-account-context mesh-account-context--error"><span>{LABELS.unavailable}</span><button type="button" onClick={value.retry}>{LABELS.retry}</button>{value.errorRequestId?<small>{LABELS.support}: {value.errorRequestId}</small>:null}</span>;
  if(!value.accounts.length)return <span className="mesh-account-context" role="status">{LABELS.none}</span>;
  const normalized=query.trim().toLocaleLowerCase();const visible=value.accounts.filter((account)=>!normalized||[account.code,account.displayName,account.legalName,account.countryCode,account.defaultCurrency].some((candidate)=>candidate?.toLocaleLowerCase().includes(normalized)));
  const groups=(["buyer","supplier","both"] as const).map((role)=>({role,label:role==="buyer"?LABELS.buyer:role==="supplier"?LABELS.supplier:LABELS.both,accounts:visible.filter((account)=>account.role===role)})).filter((group)=>group.accounts.length);
  const selected=value.selected,sole=value.accounts.length===1;const choose=(id:string)=>{value.select(id);setQuery("");};
  const identity={name:selected?.displayName??LABELS.choose,countryCode:selected?.countryCode,logoAssetRef:selected?.logoAssetRef};
  const hoverLines=selected?[selected.displayName,`Partner Account · ${selected.code.toUpperCase()}`]:[LABELS.choose,`${value.accounts.length} authorized accounts`];
  return <ShellContextSelector ariaLabel={`Acting for: ${selected?.displayName??LABELS.choose}`} {...identity} interactive={!sole} respondToWorkContextRequest hoverLines={hoverLines} onClose={()=>setQuery("")}><ShellContextPickerPanel className="mesh-account-picker__panel" title="Choose account context" description="Actions and documents are scoped to the account you are acting for." searchLabel={LABELS.search} searchValue={query} onSearchChange={setQuery} resultSummary={`${visible.length} authorized ${visible.length===1?"account":"accounts"}`}><div className="mesh-account-picker__groups">{groups.map((group)=><section key={group.role}><header><strong>{group.label}</strong><small>{group.accounts.length} {group.accounts.length===1?"account":"accounts"}</small></header><ul>{group.accounts.map((account)=><li key={account.networkAccountId}><button data-context-picker-select type="button" aria-pressed={selected?.networkAccountId===account.networkAccountId} onClick={()=>choose(account.networkAccountId)}><strong>{selected?.networkAccountId===account.networkAccountId?<CheckIcon size={14}/>:null}{account.displayName}</strong><span>{accountReference(account)}</span>{account.relatedAccountCount>1?<mark>{LABELS.related}: {account.relatedAccountCount} — verify the account code before acting</mark>:null}</button></li>)}</ul></section>)}</div>{!visible.length?<p role="status">No accounts match your search.</p>:null}</ShellContextPickerPanel></ShellContextSelector>;
}

export function useMeshAccountContext():MeshAccountContextValue{const value=useContext(AccountContext);if(!value)throw new Error("useMeshAccountContext must be used inside MeshShell");return value;}
function accountReference(account:MeshNetworkAccount):string{return `${account.code.toUpperCase()}${account.countryCode?` · ${account.countryCode}`:""}${account.defaultCurrency?` · ${account.defaultCurrency}`:""}`;}
function roleLabel(role:MeshNetworkAccount["role"]):string{return role==="buyer"?"BUYER":role==="supplier"?"SUPPLIER":"BUYER & SUPPLIER";}
function meshTransactionContext(value:MeshAccountContextValue){return {label:"Acting for",value:value.status==="loading"?LABELS.loading:value.status==="error"?LABELS.unavailable:value.selected?`${roleLabel(value.selected.role)} · ${value.selected.displayName}`:LABELS.choose,...(value.selected?{secondaryLabel:accountReference(value.selected)}:{secondaryLabel:`${value.accounts.length} authorized accounts`}),changeable:value.status==="ready"&&value.accounts.length>1};}
function planeDiagnostic(plane:string){return(event:NavigationDiagnostic)=>{const production=(globalThis as{process?:{env?:{NODE_ENV?:string}}}).process?.env?.NODE_ENV==="production";(production?console.error:console.warn)(production?"[navigation-telemetry]":"[navigation-warning]",{plane,...event});};}
function developmentAccountDiagnostic(event:MeshAccountContextDiagnostic){if(typeof window==="undefined")return;window.dispatchEvent(new CustomEvent("athyper:telemetry",{detail:{...event,event:`mesh.account_context.${event.event}`}}));if(window.location.hostname==="localhost"||window.location.hostname.endsWith(".local"))console.info("[mesh/account-context]",event);}
async function changeLocale(client:ReturnType<typeof useApiClient>,localeCode:import("@athyper/platform-i18n").SupportedLocale){await client.request(updatePrincipalLocaleOperation,{body:{localeCode}});document.cookie=`athyper_locale=${localeCode}; Path=/; Max-Age=31536000; SameSite=Lax`;window.location.reload();}
