export {
  CanonicalAuthorizationEvaluator,
  authorizationFingerprint,
  evaluateLoadedFacts,
} from "./evaluator.js";
export {
  createMeshAuthorizationRepository,
  createNeonAdminAuthorizationRepository,
  type MeshFactLoader,
  type NeonAdminFactLoader,
} from "./repository-contracts.js";
export {
  CanonicalDelegationService,
  CanonicalOverrideService,
  CanonicalRecordAclService,
  WAVE4_EXCEPTION_ENFORCEMENT_STATUS,
  type CanonicalDelegationWriterRepository,
  type CanonicalOverrideWriterRepository,
  type CanonicalRecordAclWriterRepository,
  type CreateAllowOverrideCommand,
  type CreateDelegationCommand,
  type CreateRecordAclCommand,
  type DelegationWriteFacts,
  type OverrideWriteFacts,
  type RecordAclWriteFacts,
} from "./exception-services.js";
export {
  applyCollectionMaterialization,
  isScopeSubset,
  isValidScope,
  proofPathMatches,
  scopeMatches,
  type CollectionCandidate,
} from "./scope.js";
export {
  CANONICAL_AUTHORIZATION_CONTRACT_VERSION,
  type AllowProof,
  type AllowProofKind,
  type AuthorizationSubject,
  type CanonicalAuthorizationRepository,
  type CanonicalDecisionRequest,
  type CanonicalDecisionResult,
  type CanonicalPlane,
  type CollectionDecisionRequest,
  type CollectionDecisionResult,
  type CollectionMaterialization,
  type CommonDecisionGates,
  type DecisionEvidence,
  type DecisionFacts,
  type DecisionMode,
  type DecisionReason,
  type DelegationAllowProof,
  type DenyProof,
  type EntityResourceDecisionRequest,
  type EntityResourceDecisionResult,
  type EntitlementEvidence,
  type GroupRoleAllowProof,
  type MeshAuthorizationRepository,
  type NeonAdminAuthorizationRepository,
  type OrganizationalAllowClause,
  type OverrideAllowProof,
  type RecordAclAllowProof,
  type RegisteredCapabilityDecisionRequest,
  type RegisteredCapabilityDecisionResult,
  type ResolvedPermission,
  type ResourceCoordinates,
  type ScopeConstraint,
  type ScopeDimension,
  type SharedRecordPredicate,
} from "./types.js";
