import type { Operation } from "./index";

export type NeonOperatingOrganizationCapability="procurement"|"sales"|"shared_services";
export interface NeonOperatingOrganizationAssignment { readonly companyCodeId:string;readonly participationRole:string;readonly effectiveFrom:string;readonly effectiveUntil?:string; }
export interface NeonOperatingOrganization { readonly id:string;readonly code:string;readonly displayName:string;readonly domain:string;readonly parentId?:string;readonly path:readonly string[];readonly capabilities:readonly NeonOperatingOrganizationCapability[];readonly procurementProfileConfigured:boolean;readonly salesProfileConfigured:boolean;readonly companyAssignments:readonly NeonOperatingOrganizationAssignment[];readonly defaults:Readonly<{leadCompanyCodeId?:string;bookingCompanyCodeId?:string;invoicingCompanyCodeId?:string;currency?:string}>; }
export interface NeonOperatingOrganizationCatalog { readonly schemaVersion:1;readonly revision:string;readonly tenantId:string;readonly effectiveAt:string;readonly organizations:readonly NeonOperatingOrganization[]; }

export const neonOperatingOrganizationsOperation:Operation<NeonOperatingOrganizationCatalog>=Object.freeze({method:"GET",path:"/api/neon/operating-organizations",parse:parseNeonOperatingOrganizationCatalog,requestClass:"interactive",idempotency:"forbidden",response:"json"});

export function parseNeonOperatingOrganizationCatalog(value:unknown):NeonOperatingOrganizationCatalog{
  const record=obj(value,"operating organization catalog");if(record.schemaVersion!==1)throw new TypeError("operating organization catalog schemaVersion must be 1");
  const organizations=arr(record.organizations,"organizations").map((candidate,index)=>{const row=obj(candidate,`organizations[${index}]`),defaults=obj(row.defaults,`organizations[${index}].defaults`);const assignments=arr(row.companyAssignments,"companyAssignments").map((item,assignmentIndex)=>{const assignment=obj(item,`companyAssignments[${assignmentIndex}]`);return Object.freeze({companyCodeId:text(assignment.companyCodeId,"companyCodeId"),participationRole:code(assignment.participationRole,"participationRole"),effectiveFrom:date(assignment.effectiveFrom,"effectiveFrom"),...(optional(assignment.effectiveUntil)?{effectiveUntil:date(assignment.effectiveUntil,"effectiveUntil")}:{})});});return Object.freeze({id:text(row.id,"id"),code:code(row.code,"code"),displayName:text(row.displayName,"displayName"),domain:code(row.domain,"domain"),...(optional(row.parentId)?{parentId:optional(row.parentId)}:{}),path:Object.freeze(arr(row.path,"path").map((item)=>text(item,"path item"))),capabilities:Object.freeze([...new Set(arr(row.capabilities,"capabilities").map((item)=>oneOf(item,["procurement","sales","shared_services"] as const,"capability")))].sort()),procurementProfileConfigured:bool(row.procurementProfileConfigured,"procurementProfileConfigured"),salesProfileConfigured:bool(row.salesProfileConfigured,"salesProfileConfigured"),companyAssignments:Object.freeze(assignments),defaults:Object.freeze({...(optional(defaults.leadCompanyCodeId)?{leadCompanyCodeId:optional(defaults.leadCompanyCodeId)}:{}),...(optional(defaults.bookingCompanyCodeId)?{bookingCompanyCodeId:optional(defaults.bookingCompanyCodeId)}:{}),...(optional(defaults.invoicingCompanyCodeId)?{invoicingCompanyCodeId:optional(defaults.invoicingCompanyCodeId)}:{}),...(optional(defaults.currency)?{currency:optional(defaults.currency)}:{})})});});
  return Object.freeze({schemaVersion:1,revision:text(record.revision,"revision"),tenantId:text(record.tenantId,"tenantId"),effectiveAt:timestamp(record.effectiveAt,"effectiveAt"),organizations:Object.freeze(organizations)});
}

function obj(value:unknown,name:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError(`${name} must be an object`);return value as Record<string,unknown>;}function arr(value:unknown,name:string):readonly unknown[]{if(!Array.isArray(value))throw new TypeError(`${name} must be an array`);return value;}function text(value:unknown,name:string):string{if(typeof value!=="string"||!value.trim())throw new TypeError(`${name} must be non-empty`);return value.trim();}function optional(value:unknown):string|undefined{return typeof value==="string"&&value.trim()?value.trim():undefined;}function bool(value:unknown,name:string):boolean{if(typeof value!=="boolean")throw new TypeError(`${name} must be boolean`);return value;}function code(value:unknown,name:string):string{const result=text(value,name);if(!/^[a-z][a-z0-9_.-]{1,126}$/.test(result))throw new TypeError(`${name} must be a catalog code`);return result;}function date(value:unknown,name:string):string{const result=text(value,name);if(!/^\d{4}-\d{2}-\d{2}$/.test(result))throw new TypeError(`${name} must be an ISO date`);return result;}function timestamp(value:unknown,name:string):string{const result=text(value,name);if(!Number.isFinite(Date.parse(result)))throw new TypeError(`${name} must be an ISO timestamp`);return result;}function oneOf<const T extends readonly string[]>(value:unknown,values:T,name:string):T[number]{if(typeof value!=="string"||!values.includes(value as T[number]))throw new TypeError(`${name} is invalid`);return value as T[number];}
