import type { Operation } from "./index";

export type NeonCapabilityGroup="finance"|"procurement"|"inventory"|"sales"|"people"|"projects";
export interface NeonWorkContextCompany { readonly companyCodeId:string;readonly code:string;readonly displayName:string;readonly legalEntityId:string;readonly legalEntityCode:string;readonly legalEntityName:string;readonly countryCode?:string;readonly functionalCurrency:string;readonly capabilityGroups:readonly NeonCapabilityGroup[]; }
export interface NeonWorkContextBootstrap { readonly schemaVersion:1;readonly revision:string;readonly tenantId:string;readonly supportsAllPermitted:boolean;readonly companies:readonly NeonWorkContextCompany[]; }

export const neonWorkContextsOperation:Operation<NeonWorkContextBootstrap>=Object.freeze({method:"GET",path:"/api/neon/work-contexts",parse:parseNeonWorkContextBootstrap,requestClass:"interactive",idempotency:"forbidden",response:"json"});
export function parseNeonWorkContextBootstrap(value:unknown):NeonWorkContextBootstrap { const record=obj(value,"work contexts");if(record.schemaVersion!==1)throw new TypeError("work contexts schemaVersion must be 1");const companies=arr(record.companies,"companies").map((candidate,index)=>{const row=obj(candidate,`companies[${index}]`);return Object.freeze({companyCodeId:text(row.companyCodeId,"companyCodeId"),code:catalogCode(row.code,"code"),displayName:text(row.displayName,"displayName"),legalEntityId:text(row.legalEntityId,"legalEntityId"),legalEntityCode:catalogCode(row.legalEntityCode,"legalEntityCode"),legalEntityName:text(row.legalEntityName,"legalEntityName"),...(optional(row.countryCode)?{countryCode:optional(row.countryCode)}:{}),functionalCurrency:text(row.functionalCurrency,"functionalCurrency"),capabilityGroups:Object.freeze([...new Set(arr(row.capabilityGroups,"capabilityGroups").map((group)=>oneOf(group,["finance","procurement","inventory","sales","people","projects"] as const,"capabilityGroup")))].sort())});});return Object.freeze({schemaVersion:1,revision:text(record.revision,"revision"),tenantId:text(record.tenantId,"tenantId"),supportsAllPermitted:bool(record.supportsAllPermitted,"supportsAllPermitted"),companies:Object.freeze(companies)}); }
function obj(value:unknown,name:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError(`${name} must be an object`);return value as Record<string,unknown>;}function arr(value:unknown,name:string):readonly unknown[]{if(!Array.isArray(value))throw new TypeError(`${name} must be an array`);return value;}function text(value:unknown,name:string):string{if(typeof value!=="string"||!value.trim())throw new TypeError(`${name} must be non-empty`);return value.trim();}function optional(value:unknown):string|undefined{return typeof value==="string"&&value.trim()?value.trim():undefined;}function bool(value:unknown,name:string):boolean{if(typeof value!=="boolean")throw new TypeError(`${name} must be boolean`);return value;}function catalogCode(value:unknown,name:string):string{const result=text(value,name);if(!/^[a-z][a-z0-9_.-]{1,126}$/.test(result))throw new TypeError(`${name} must be a catalog code`);return result;}function oneOf<const T extends readonly string[]>(value:unknown,values:T,name:string):T[number]{if(typeof value!=="string"||!values.includes(value as T[number]))throw new TypeError(`${name} is invalid`);return value as T[number];}
