import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import { defineRouteContract, registerContractRoute } from "@athyper/server-runtime-http";
import type { Application, RequestHandler, Response } from "express";
import { experienceBootstrapSchema, meshNetworkAccountCatalogSchema, neonOperatingOrganizationCatalogSchema, neonWorkContextBootstrapSchema } from "./contracts.js";
import { ExperienceAccessError, type createExperienceService } from "./service.js";

type ExperienceService = ReturnType<typeof createExperienceService>;

export const getExperienceBootstrapContract = defineRouteContract({
  method: "get",
  path: "/api/platform/experience/bootstrap",
  operationId: "platformExperienceBootstrap",
  summary: "Resolve the sanitized effective application experience",
  tags: ["Platform experience"],
  authenticated: true,
  permission: "platform.experience.bootstrap",
  request: { headers: { type: "object", properties: { "x-athyper-client-version": { type: "string", maxLength: 64 } } } },
  responses: {
    200: { description: "Resolved experience or context-not-ready projection", body: experienceBootstrapSchema },
    403: { description: "Verified identity is not admitted to this plane", contentType: "application/problem+json" },
    503: { description: "Exact-plane experience repository unavailable", contentType: "application/problem+json" },
  },
});
export const getNeonWorkContextsContract = defineRouteContract({ method:"get",path:"/api/neon/work-contexts",operationId:"neonWorkContexts",summary:"Resolve permitted Neon company work contexts",tags:["Neon experience"],authenticated:true,permission:"platform.experience.bootstrap",request:{},responses:{200:{description:"Permitted localized company work contexts",body:neonWorkContextBootstrapSchema},403:{description:"Context is not admitted to Neon",contentType:"application/problem+json"},503:{description:"Exact-plane experience repository unavailable",contentType:"application/problem+json"}} });
export const getNeonOperatingOrganizationsContract = defineRouteContract({ method:"get",path:"/api/neon/operating-organizations",operationId:"neonOperatingOrganizations",summary:"Resolve permitted effective Neon operating organizations",tags:["Neon experience"],authenticated:true,permission:"platform.experience.bootstrap",request:{},responses:{200:{description:"Permitted effective operating-organization catalog",body:neonOperatingOrganizationCatalogSchema},403:{description:"Context is not admitted to Neon",contentType:"application/problem+json"},503:{description:"Exact-plane experience repository unavailable",contentType:"application/problem+json"}} });
export const getMeshNetworkAccountsContract = defineRouteContract({ method:"get",path:"/api/mesh/network-accounts",operationId:"meshNetworkAccounts",summary:"Resolve principal-authorized Mesh network accounts",tags:["Mesh experience"],authenticated:true,permission:"platform.experience.bootstrap",request:{},responses:{200:{description:"Principal-authorized buyer and supplier account catalog",body:meshNetworkAccountCatalogSchema},403:{description:"Context is not admitted to Mesh",contentType:"application/problem+json"},503:{description:"Exact-plane experience repository unavailable",contentType:"application/problem+json"}} });
const localeCodes=["en","ar","ms","zh-Hans","hi","ta","fr","de"] as const;
const localeCatalogInput={type:"object",additionalProperties:false,required:["localeCode","status","coveragePct","linguisticReviewPassed","layoutReviewPassed","automatedTestsPassed"],properties:{localeCode:{enum:localeCodes},status:{enum:["draft","translating","review","qualified","retired"]},coveragePct:{type:"integer",minimum:0,maximum:100},linguisticReviewPassed:{type:"boolean"},layoutReviewPassed:{type:"boolean"},automatedTestsPassed:{type:"boolean"}}} as const;
const localePolicyBody={type:"object",additionalProperties:false,required:["catalogs","enabledLocales","defaultLocale","fallbackLocale"],properties:{catalogs:{type:"array",minItems:8,maxItems:8,items:localeCatalogInput},enabledLocales:{type:"array",minItems:1,uniqueItems:true,items:{enum:localeCodes}},defaultLocale:{enum:localeCodes},fallbackLocale:{const:"en"}}} as const;
const localeCatalogResponse={type:"object",additionalProperties:false,required:[...localeCatalogInput.required,"englishName","nativeName","direction","rolloutWave","qualified"],properties:{...localeCatalogInput.properties,englishName:{type:"string"},nativeName:{type:"string"},direction:{enum:["ltr","rtl"]},rolloutWave:{type:"integer",minimum:0,maximum:3},qualified:{type:"boolean"}}} as const;
const localePolicyResponse={type:"object",additionalProperties:false,required:["planeKey","catalogs","enabledLocales","defaultLocale","fallbackLocale","revision"],properties:{planeKey:{enum:["studio","neon","mesh"]},catalogs:{type:"array",minItems:8,maxItems:8,items:localeCatalogResponse},enabledLocales:localePolicyBody.properties.enabledLocales,defaultLocale:localePolicyBody.properties.defaultLocale,fallbackLocale:localePolicyBody.properties.fallbackLocale,revision:{type:"string"}}} as const;
export const getLocalePolicyContract=defineRouteContract({method:"get",path:"/api/platform/localization/policies/:planeKey",operationId:"platformLocalePolicy",summary:"Read one exact-plane tenant locale policy",tags:["Platform localization"],authenticated:true,permission:"platform.experience.bootstrap",request:{},responses:{200:{description:"Plane locale policy",body:localePolicyResponse},403:{description:"Cross-plane policy access denied",contentType:"application/problem+json"}}});
export const updateLocalePolicyContract=defineRouteContract({method:"put",path:"/api/platform/localization/policies/:planeKey",operationId:"updatePlatformLocalePolicy",summary:"Activate tenant locales for a target plane from Studio",tags:["Platform localization"],authenticated:true,permission:"studio.platform.catalog.manage",request:{body:localePolicyBody},responses:{200:{description:"Updated plane locale policy",body:localePolicyResponse},400:{description:"Invalid locale policy",contentType:"application/problem+json"},403:{description:"Studio catalog authority required",contentType:"application/problem+json"}}});
export const updatePrincipalLocaleContract=defineRouteContract({method:"patch",path:"/api/platform/profile/locale",operationId:"updatePrincipalLocale",summary:"Select an enabled locale for the current principal and plane",tags:["Platform localization"],authenticated:true,permission:"platform.experience.bootstrap",request:{body:{type:"object",additionalProperties:false,required:["localeCode"],properties:{localeCode:{type:"string",minLength:2,maxLength:35}}}},responses:{200:{description:"Refreshed effective experience",body:experienceBootstrapSchema},400:{description:"Locale is not enabled",contentType:"application/problem+json"}}});
const surfaceReleaseResponse={type:"object",additionalProperties:true,required:["id","targetPlane","surfaceKey","layer","revision","status","definition","contentHash","source"],properties:{id:{type:"string",format:"uuid"},targetPlane:{enum:["studio","neon","mesh"]},surfaceKey:{type:"string"},layer:{enum:["shared","tenant"]},revision:{type:"integer"},status:{enum:["draft","published","retired"]},definition:{type:"object",additionalProperties:true},contentHash:{type:"string"},source:{enum:["human","atlas"]}}} as const;
export const saveExperienceSurfaceDraftContract=defineRouteContract({method:"post",path:"/api/studio/experience-surfaces/drafts",operationId:"saveExperienceSurfaceDraft",summary:"Validate and persist a human-authored experience surface draft",tags:["Studio experience"],authenticated:true,permission:"studio.platform.catalog.manage",request:{body:{type:"object",additionalProperties:false,required:["targetPlane","layer","definition"],properties:{targetPlane:{enum:["studio","neon","mesh"]},layer:{enum:["shared","tenant"]},definition:{type:"object",additionalProperties:true},expectedContentHash:{type:"string",pattern:"^[a-f0-9]{64}$"}}}},responses:{200:{description:"Validated draft",body:surfaceReleaseResponse},400:{description:"Invalid surface",contentType:"application/problem+json"},409:{description:"Draft changed after it was loaded",contentType:"application/problem+json"}}});
export const listExperienceSurfaceHistoryContract=defineRouteContract({method:"get",path:"/api/studio/experience-surfaces",operationId:"listExperienceSurfaceHistory",summary:"Load Studio release history for one surface",tags:["Studio experience"],authenticated:true,permission:"studio.platform.catalog.manage",request:{query:{type:"object",required:["targetPlane","surfaceKey"],properties:{targetPlane:{enum:["studio","neon","mesh"]},surfaceKey:{type:"string"}}}},responses:{200:{description:"Release history",body:{type:"object",additionalProperties:false,required:["releases"],properties:{releases:{type:"array",items:surfaceReleaseResponse}}}}}});
export const rollbackExperienceSurfaceContract=defineRouteContract({method:"post",path:"/api/studio/experience-surfaces/:releaseId/rollback",operationId:"rollbackExperienceSurface",summary:"Clone a historical release into a new human-review draft",tags:["Studio experience"],authenticated:true,permission:"studio.platform.catalog.manage",request:{},responses:{200:{description:"Rollback draft",body:surfaceReleaseResponse},404:{description:"Release not found",contentType:"application/problem+json"}}});
export const publishExperienceSurfaceContract=defineRouteContract({method:"post",path:"/api/studio/experience-surfaces/:releaseId/publish",operationId:"publishExperienceSurface",summary:"Publish a validated draft and apply its exact-plane projection",tags:["Studio experience"],authenticated:true,permission:"studio.platform.catalog.manage",request:{},responses:{200:{description:"Published release",body:surfaceReleaseResponse},404:{description:"Draft not found",contentType:"application/problem+json"},503:{description:"Target projection unavailable; publication may be retried",contentType:"application/problem+json"}}});
const effectiveSurfaceResponse={type:"object",additionalProperties:false,required:["surface","provenance"],properties:{surface:{type:"object",additionalProperties:true},provenance:{type:"object",additionalProperties:true}}} as const;
export const getExperienceSurfaceContract=defineRouteContract({method:"get",path:"/api/platform/experience/surfaces/:surfaceKey",operationId:"getExperienceSurface",summary:"Resolve the effective system, shared, tenant, and personal experience surface",tags:["Platform experience"],authenticated:true,permission:"platform.experience.bootstrap",request:{},responses:{200:{description:"Effective surface and resolution provenance",body:effectiveSurfaceResponse},404:{description:"Unknown system surface",contentType:"application/problem+json"}}});
export const savePersonalSurfaceArrangementContract=defineRouteContract({method:"put",path:"/api/platform/experience/surfaces/:surfaceKey/arrangement",operationId:"savePersonalSurfaceArrangement",summary:"Persist the current principal's arrangement for one effective surface revision",tags:["Platform experience"],authenticated:true,permission:"platform.experience.bootstrap",request:{body:{type:"object",additionalProperties:true,required:["schema","surfaceId","baseRevision"]}},responses:{200:{description:"Effective surface with the arrangement applied",body:effectiveSurfaceResponse},409:{description:"Arrangement targets a stale surface revision",contentType:"application/problem+json"}}});
export const deletePersonalSurfaceArrangementContract=defineRouteContract({method:"delete",path:"/api/platform/experience/surfaces/:surfaceKey/arrangement",operationId:"deletePersonalSurfaceArrangement",summary:"Reset the current principal's arrangement for one surface",tags:["Platform experience"],authenticated:true,permission:"platform.experience.bootstrap",request:{},responses:{200:{description:"Effective surface without personal arrangement",body:effectiveSurfaceResponse}}});
export const resolveRouteSlugRedirectContract=defineRouteContract({method:"get",path:"/api/platform/navigation/slug-redirect",operationId:"resolveRouteSlugRedirect",summary:"Resolve an active historical route slug in the exact plane",tags:["Platform navigation"],authenticated:true,permission:"platform.experience.bootstrap",request:{query:{type:"object",required:["path"],properties:{path:{type:"string",maxLength:1024}}}},responses:{200:{description:"Redirect resolution",body:{type:"object",additionalProperties:false,required:["targetPath","redirectStatus"],properties:{targetPath:{type:"string"},redirectStatus:{enum:[301,308]}}}},404:{description:"No active redirect",contentType:"application/problem+json"}}});
export const registerRouteSlugRedirectContract=defineRouteContract({method:"post",path:"/api/studio/navigation/slug-redirects",operationId:"registerRouteSlugRedirect",summary:"Register a catalog slug change in its exact target plane",tags:["Studio navigation"],authenticated:true,permission:"studio.platform.catalog.manage",request:{body:{type:"object",additionalProperties:false,required:["targetPlane","catalogKind","catalogCode","sourcePath","targetPath","redirectStatus","sourceReleaseId"],properties:{targetPlane:{enum:["studio","neon","mesh"]},catalogKind:{enum:["workspace","module","entity"]},catalogCode:{type:"string"},sourcePath:{type:"string"},targetPath:{type:"string"},redirectStatus:{enum:[301,308]},sourceReleaseId:{type:"string",format:"uuid"}}}},responses:{200:{description:"Active redirect",body:{type:"object",additionalProperties:false,required:["sourcePath","targetPath","redirectStatus"],properties:{sourcePath:{type:"string"},targetPath:{type:"string"},redirectStatus:{enum:[301,308]}}}},409:{description:"Redirect loop",contentType:"application/problem+json"}}});

export interface ExperienceRouteOptions {
  readonly authenticate: RequestHandler;
  readonly readContext: (response: Response) => VerifiedRequestContext;
  readonly service: ExperienceService;
}

export function registerExperienceRoutes(application: Application, options: ExperienceRouteOptions): void {
  const handler: RequestHandler = async (request, response, next) => {
    try {
      const rawVersion = request.header("x-athyper-client-version");
      const result = await options.service.bootstrap(options.readContext(response), rawVersion ? { clientVersion: rawVersion } : {});
      response.setHeader("ETag", `"${result.revision}"`);
      response.setHeader("Cache-Control", "private, no-store");
      response.status(200).json(result);
    } catch (error) {
      if (error instanceof ExperienceAccessError) { problem(response, error.status, error.code, error.message); return; }
      if (isUnavailable(error)) { problem(response, 503, errorCode(error), "The exact-plane experience repository is unavailable"); return; }
      next(error);
    }
  };
  registerContractRoute(application, getExperienceBootstrapContract, options.authenticate, handler);
  registerContractRoute(application,getNeonWorkContextsContract,options.authenticate,async(_request,response,next)=>{try{const result=await options.service.neonWorkContexts(options.readContext(response));response.setHeader("ETag",`"${result.revision}"`);response.setHeader("Cache-Control","private, no-store");response.status(200).json(result);}catch(error){if(error instanceof ExperienceAccessError){problem(response,error.status,error.code,error.message);return;}if(isUnavailable(error)){problem(response,503,errorCode(error),"The exact-plane experience repository is unavailable");return;}next(error);}});
  registerContractRoute(application,getNeonOperatingOrganizationsContract,options.authenticate,async(_request,response,next)=>{try{const result=await options.service.neonOperatingOrganizations(options.readContext(response));response.setHeader("ETag",`"${result.revision}"`);response.setHeader("Cache-Control","private, no-store");response.status(200).json(result);}catch(error){if(error instanceof ExperienceAccessError){problem(response,error.status,error.code,error.message);return;}if(isUnavailable(error)){problem(response,503,errorCode(error),"The exact-plane experience repository is unavailable");return;}next(error);}});
  registerContractRoute(application,getMeshNetworkAccountsContract,options.authenticate,async(_request,response,next)=>{try{const result=await options.service.meshNetworkAccounts(options.readContext(response));response.setHeader("ETag",`"${result.revision}"`);response.setHeader("Cache-Control","private, no-store");response.status(200).json(result);}catch(error){if(error instanceof ExperienceAccessError){problem(response,error.status,error.code,error.message);return;}if(isUnavailable(error)){problem(response,503,errorCode(error),"The exact-plane experience repository is unavailable");return;}next(error);}});
  registerContractRoute(application,getLocalePolicyContract,options.authenticate,async(request,response,next)=>{try{const result=await options.service.localePolicy(options.readContext(response),plane(request.params.planeKey));response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,updateLocalePolicyContract,options.authenticate,async(request,response,next)=>{try{const result=await options.service.updateLocalePolicy(options.readContext(response),plane(request.params.planeKey),localePolicyInput(request.body));response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,updatePrincipalLocaleContract,options.authenticate,async(request,response,next)=>{try{const body=request.body as Record<string,unknown>,localeCode=typeof body?.localeCode==="string"?body.localeCode:"";const result=await options.service.updatePrincipalLocale(options.readContext(response),localeCode);response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,saveExperienceSurfaceDraftContract,options.authenticate,async(request,response,next)=>{try{const body=surfaceDraftInput(request.body);const result=await options.service.saveSurfaceDraft(options.readContext(response),body);response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,listExperienceSurfaceHistoryContract,options.authenticate,async(request,response,next)=>{try{const result=await options.service.surfaceHistory(options.readContext(response),plane(request.query.targetPlane),code(request.query.surfaceKey));response.status(200).setHeader("Cache-Control","private, no-store").json({releases:result});}catch(error){handle(error,response,next);}});
  registerContractRoute(application,rollbackExperienceSurfaceContract,options.authenticate,async(request,response,next)=>{try{const result=await options.service.rollbackSurface(options.readContext(response),uuid(request.params.releaseId));response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,publishExperienceSurfaceContract,options.authenticate,async(request,response,next)=>{try{const releaseId=uuid(request.params.releaseId);const result=await options.service.publishSurface(options.readContext(response),releaseId);response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,getExperienceSurfaceContract,options.authenticate,async(request,response,next)=>{try{const result=await options.service.surface(options.readContext(response),code(request.params.surfaceKey));response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,savePersonalSurfaceArrangementContract,options.authenticate,async(request,response,next)=>{try{const result=await options.service.savePersonalArrangement(options.readContext(response),code(request.params.surfaceKey),request.body);response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,deletePersonalSurfaceArrangementContract,options.authenticate,async(request,response,next)=>{try{const result=await options.service.deletePersonalArrangement(options.readContext(response),code(request.params.surfaceKey));response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
  registerContractRoute(application,resolveRouteSlugRedirectContract,options.authenticate,async(request,response,next)=>{try{const path=typeof request.query.path==="string"?request.query.path:"";const result=await options.service.routeRedirect(options.readContext(response),path);if(!result){problem(response,404,"EXPERIENCE_ROUTE_REDIRECT_NOT_FOUND","No active redirect exists for this path");return;}response.status(200).setHeader("Cache-Control","private, no-store").json({targetPath:result.targetPath,redirectStatus:result.redirectStatus});}catch(error){handle(error,response,next);}});
  registerContractRoute(application,registerRouteSlugRedirectContract,options.authenticate,async(request,response,next)=>{try{const result=await options.service.registerRouteRedirect(options.readContext(response),redirectInput(request.body));response.status(200).setHeader("Cache-Control","private, no-store").json(result);}catch(error){handle(error,response,next);}});
}

function isUnavailable(error: unknown): boolean { return Boolean(error && typeof error === "object" && String(Reflect.get(error as object, "code")).includes("EXPERIENCE_EXACT_PLANE")); }
function errorCode(error: unknown): string { return error && typeof error === "object" ? String(Reflect.get(error, "code")) : "EXPERIENCE_EXACT_PLANE_REPOSITORY_UNAVAILABLE"; }
function problem(response: Response, status: number, code: string, detail: string): void { response.status(status).type("application/problem+json").json({ type: `urn:athyper:problem:${code.toLowerCase().replaceAll("_", "-")}`, title: code, status, detail, code }); }
function plane(value:unknown):"studio"|"neon"|"mesh"{if(value!=="studio"&&value!=="neon"&&value!=="mesh")throw new ExperienceAccessError(400,"EXPERIENCE_PLANE_INVALID","Plane is invalid");return value;}
function localePolicyInput(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))throw new ExperienceAccessError(400,"EXPERIENCE_LOCALE_POLICY_INVALID","Locale policy body is required");const row=value as Record<string,unknown>;const catalogs=Array.isArray(row.catalogs)?row.catalogs.flatMap((candidate)=>{if(!candidate||typeof candidate!=="object"||Array.isArray(candidate))return[];const item=candidate as Record<string,unknown>;return[{localeCode:typeof item.localeCode==="string"?item.localeCode:"",status:typeof item.status==="string"?item.status:"",coveragePct:Number(item.coveragePct),linguisticReviewPassed:item.linguisticReviewPassed===true,layoutReviewPassed:item.layoutReviewPassed===true,automatedTestsPassed:item.automatedTestsPassed===true}];}):[];return{catalogs,enabledLocales:Array.isArray(row.enabledLocales)?row.enabledLocales.filter((item):item is string=>typeof item==="string"):[],defaultLocale:typeof row.defaultLocale==="string"?row.defaultLocale:"",fallbackLocale:typeof row.fallbackLocale==="string"?row.fallbackLocale:""};}
function handle(error:unknown,response:Response,next:(error?:unknown)=>void){if(error instanceof ExperienceAccessError){problem(response,error.status,error.code,error.message);return;}if(isUnavailable(error)){problem(response,503,errorCode(error),"The exact-plane experience repository is unavailable");return;}next(error);}
function surfaceDraftInput(value:unknown):{targetPlane:"studio"|"neon"|"mesh";layer:"shared"|"tenant";definition:unknown;source:"human";expectedContentHash?:string}{if(!value||typeof value!=="object"||Array.isArray(value))throw new ExperienceAccessError(400,"EXPERIENCE_SURFACE_INVALID","Surface draft body is required");const body=value as Record<string,unknown>;const targetPlane=plane(body.targetPlane),layer=body.layer;if(layer!=="shared"&&layer!=="tenant")throw new ExperienceAccessError(400,"EXPERIENCE_SURFACE_INVALID","Surface layer is invalid");const expectedContentHash=typeof body.expectedContentHash==="string"&&/^[a-f0-9]{64}$/.test(body.expectedContentHash)?body.expectedContentHash:undefined;return{targetPlane,layer,definition:body.definition,source:"human",...(expectedContentHash?{expectedContentHash}:{})};}
function uuid(value:unknown):string{if(typeof value!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new ExperienceAccessError(400,"EXPERIENCE_RELEASE_ID_INVALID","Release id is invalid");return value;}
function code(value:unknown):string{if(typeof value!=="string"||!/^[a-z][a-z0-9_.-]{1,126}$/.test(value))throw new ExperienceAccessError(400,"EXPERIENCE_SURFACE_KEY_INVALID","Surface key is invalid");return value;}
function redirectInput(value:unknown):{targetPlane:"studio"|"neon"|"mesh";catalogKind:"workspace"|"module"|"entity";catalogCode:string;sourcePath:string;targetPath:string;redirectStatus:301|308;sourceReleaseId:string}{if(!value||typeof value!=="object"||Array.isArray(value))throw new ExperienceAccessError(400,"EXPERIENCE_ROUTE_REDIRECT_INVALID","Redirect body is required");const body=value as Record<string,unknown>,catalogKind=body.catalogKind,redirectStatus=body.redirectStatus;if(catalogKind!=="workspace"&&catalogKind!=="module"&&catalogKind!=="entity")throw new ExperienceAccessError(400,"EXPERIENCE_ROUTE_REDIRECT_INVALID","Catalog kind is invalid");if(redirectStatus!==301&&redirectStatus!==308)throw new ExperienceAccessError(400,"EXPERIENCE_ROUTE_REDIRECT_INVALID","Redirect status is invalid");return{targetPlane:plane(body.targetPlane),catalogKind,catalogCode:code(body.catalogCode),sourcePath:typeof body.sourcePath==="string"?body.sourcePath:"",targetPath:typeof body.targetPath==="string"?body.targetPath:"",redirectStatus,sourceReleaseId:uuid(body.sourceReleaseId)};}
