import { timingSafeEqual } from "node:crypto";
import type { ApiProblem } from "@athyper/contract-platform-api";

export type RelayMethod = "GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE";
export type RelayRequestClass = "json" | "upload" | "download" | "stream";
export interface RelayOperation { readonly id: string; readonly method: RelayMethod; readonly path: `/api/${string}`; readonly requestClass?: RelayRequestClass; readonly requiresTenant?: boolean; readonly tenantParam?: string; readonly idempotency?: "none" | "optional" | "required"; readonly maxBodyBytes?: number; }
export interface RelaySessionContext { readonly accessToken: string; readonly plane: string; readonly realmKey: string; readonly tenantId?: string; readonly principalId: string; readonly authEpoch: number; readonly assurance?: "baseline" | "elevated"; readonly csrfToken: string; readonly acceptedCsrfTokens?: readonly string[]; }
export interface RelaySessionAuthority { resolve(request: Request): Promise<RelaySessionContext | undefined>; refresh(request: Request): Promise<RelaySessionContext | undefined>; invalidate(request: Request, reason: "context_mismatch"): Promise<void>; }
export interface RelayDiagnostic { readonly event: "request" | "failure" | "refresh" | "context_mismatch"; readonly operationId?: string; readonly method: string; readonly status?: number; readonly requestId?: string; }
export interface RelayOptions { readonly plane: string; readonly runtimeApiUrl: string; readonly appOrigin: string; readonly operations: readonly RelayOperation[]; readonly session: RelaySessionAuthority; readonly fetch?: typeof fetch; readonly maxHeaderBytes?: number; readonly defaultBodyBytes?: number; readonly timeouts?: Partial<Record<RelayRequestClass, number>>; readonly onDiagnostic?: (diagnostic: RelayDiagnostic) => void; }
export interface RelayRouteContext { readonly params: Promise<{ readonly path: readonly string[] }>; }
export type RelayHandler = (request: Request, context: RelayRouteContext) => Promise<Response>;

const UNSAFE = new Set<RelayMethod>(["POST", "PUT", "PATCH", "DELETE"]);
const IDEMPOTENT = new Set<RelayMethod>(["GET", "HEAD", "PUT", "DELETE"]);
const BLOCKED_REQUEST_HEADERS = new Set(["authorization", "proxy-authorization", "cookie", "x-plane", "x-tenant-id", "x-principal-id", "x-realm", "x-org", "x-organization-id", "forwarded", "x-forwarded-for", "x-forwarded-host", "x-forwarded-proto", "x-real-ip", "x-client-ip", "true-client-ip", "cf-connecting-ip", "via", "host", "connection", "transfer-encoding", "te", "trailer", "upgrade", "keep-alive"]);
const SAFE_REQUEST_HEADERS = new Set(["accept", "accept-language", "content-type", "if-match", "if-none-match", "if-modified-since", "if-unmodified-since", "idempotency-key", "range", "traceparent", "tracestate", "x-request-id", "x-correlation-id"]);
const SAFE_RESPONSE_HEADERS = new Set(["content-type", "content-length", "content-disposition", "etag", "last-modified", "retry-after", "accept-ranges", "content-range", "x-request-id", "x-correlation-id", "traceparent"]);
const RAW_PATH_ATTACK = /%(?:2f|5c|2e|252f|255c|252e)/i;
const DEFAULT_TIMEOUTS: Readonly<Record<RelayRequestClass, number>> = { json: 15_000, upload: 120_000, download: 120_000, stream: 15_000 };

export const IAM_ME_OPERATION: RelayOperation = Object.freeze({ id: "iam.me", method: "GET", path: "/api/iam/me", requestClass: "json", requiresTenant: false });
export const EXPERIENCE_BOOTSTRAP_OPERATION: RelayOperation = Object.freeze({ id: "platform.experience.bootstrap", method: "GET", path: "/api/platform/experience/bootstrap", requestClass: "json", requiresTenant: true });
export const NEON_WORK_CONTEXTS_OPERATION: RelayOperation = Object.freeze({ id: "neon.work-contexts", method: "GET", path: "/api/neon/work-contexts", requestClass: "json", requiresTenant: true });
export const NEON_OPERATING_ORGANIZATIONS_OPERATION: RelayOperation = Object.freeze({ id: "neon.operating-organizations", method: "GET", path: "/api/neon/operating-organizations", requestClass: "json", requiresTenant: true });
export const MESH_NETWORK_ACCOUNTS_OPERATION: RelayOperation = Object.freeze({ id: "mesh.network-accounts", method: "GET", path: "/api/mesh/network-accounts", requestClass: "json", requiresTenant: true });
export const PLATFORM_VERIFICATION_SNAPSHOT_OPERATION: RelayOperation = Object.freeze({ id: "platform.verification.snapshot", method: "GET", path: "/api/platform/verification", requestClass: "json", requiresTenant: true });
export const PLATFORM_VERIFICATION_RUN_OPERATION: RelayOperation = Object.freeze({ id: "platform.verification.run", method: "POST", path: "/api/platform/verification/runs", requestClass: "json", requiresTenant: true, idempotency: "required", maxBodyBytes: 1024 });

export function createRelayHandler(options: RelayOptions): RelayHandler {
  const runtime = runtimeOrigin(options.runtimeApiUrl); const expectedOrigin = new URL(options.appOrigin).origin; const fetcher = options.fetch ?? globalThis.fetch;
  const operations = options.operations.map(compileOperation); if (!operations.length) throw new TypeError("Relay requires at least one allowlisted operation");
  const maxHeaderBytes = options.maxHeaderBytes ?? 32 * 1024; const defaultBodyBytes = options.defaultBodyBytes ?? 1024 * 1024; const timeouts = { ...DEFAULT_TIMEOUTS, ...options.timeouts };
  return async (request, context) => {
    try {
      enforceHeaderLimit(request.headers, maxHeaderBytes); const { path } = await context.params; const requestPath = new URL(request.url).pathname;
      if (!requestPath.startsWith("/api/relay/") || RAW_PATH_ATTACK.test(request.url)) return problem(400, "RELAY_INVALID_PATH", "Relay path is invalid");
      const normalizedPath = normalizePath(path); const method = request.method.toUpperCase() as RelayMethod; const match = findOperation(operations, method, normalizedPath);
      if (!match) return problem(404, "RELAY_OPERATION_NOT_ALLOWED", "The requested platform operation is not allowlisted");
      const { operation, params } = match; const session = await options.session.resolve(request);
      if (!session) return problem(401, "AUTHENTICATION_REQUIRED", "Authentication is required");
      if (session.plane !== options.plane) return problem(403, "AUTH_CONTEXT_MISMATCH", "The verified session belongs to another plane");
      if (operation.requiresTenant !== false && !session.tenantId) return problem(409, "AUTH_CONTEXT_MISMATCH", "Select a tenant context before continuing");
      if (operation.tenantParam && params[operation.tenantParam] !== session.tenantId) return problem(403, "AUTH_CONTEXT_MISMATCH", "The requested tenant does not match the verified session");
      if (UNSAFE.has(method)) { const originFailure = verifyUnsafeRequest(request, expectedOrigin, session.acceptedCsrfTokens ?? [session.csrfToken]); if (originFailure) return originFailure; }
      const idempotencyKey = request.headers.get("idempotency-key"); if (idempotencyKey && !validIdempotencyKey(idempotencyKey)) return problem(400, "RELAY_INVALID_IDEMPOTENCY_KEY", "Idempotency-Key is invalid");
      if (operation.idempotency === "required" && !idempotencyKey) return problem(428, "RELAY_IDEMPOTENCY_REQUIRED", "This operation requires an Idempotency-Key");
      if (operation.idempotency === "none" && idempotencyKey) return problem(400, "RELAY_IDEMPOTENCY_NOT_ALLOWED", "This operation does not accept an Idempotency-Key");
      const body = await prepareBody(request, operation, defaultBodyBytes); const canRetry = body.replayable && (IDEMPOTENT.has(method) || !!idempotencyKey);
      options.onDiagnostic?.({ event: "request", operationId: operation.id, method });
      let activeSession = session; let response = await forward(activeSession, 0);
      if (response.status === 401 && canRetry) { options.onDiagnostic?.({ event: "refresh", operationId: operation.id, method, status: 401 }); const refreshResult = await options.session.refresh(request); const refreshed = refreshResult ? await options.session.resolve(request) : undefined; if (sameAuthority(session, refreshed, options.plane)) { activeSession = refreshed; response = await forward(activeSession, 1); } }
      if (await isContextMismatch(response)) { await options.session.invalidate(request, "context_mismatch"); options.onDiagnostic?.({ event: "context_mismatch", operationId: operation.id, method, status: response.status, requestId: response.headers.get("x-request-id") ?? undefined }); return problem(409, "AUTH_CONTEXT_MISMATCH", "Session context changed; select context again", response.headers.get("x-request-id") ?? undefined, { "x-athyper-session-action": "select_context" }); }
      return relayResponse(response, request.signal, operation.requestClass ?? "json");

      async function forward(authority: RelaySessionContext, attempt: number): Promise<Response> {
        const headers = requestHeaders(request.headers); headers.set("authorization", `Bearer ${authority.accessToken}`); headers.set("x-plane", authority.plane); headers.set("x-realm", authority.realmKey); headers.set("x-principal-id", authority.principalId); headers.set("x-auth-epoch", String(authority.authEpoch)); if (authority.tenantId) headers.set("x-tenant-id", authority.tenantId);
        const controller = new AbortController(); const timeoutMs = timeouts[operation.requestClass ?? "json"]; const timer = setTimeout(() => controller.abort(new DOMException("Upstream timeout", "TimeoutError")), timeoutMs); const disconnect = () => controller.abort(request.signal.reason); if (request.signal.aborted) disconnect(); else request.signal.addEventListener("abort", disconnect, { once: true });
        try { const init: RequestInit & { duplex?: "half" } = { method, headers, body: body.forAttempt(attempt), signal: controller.signal, redirect: "error", cache: "no-store" }; if (init.body instanceof ReadableStream) init.duplex = "half"; const upstream = await fetcher(new URL(`${normalizedPath}${new URL(request.url).search}`, runtime).toString(), init); clearTimeout(timer); return upstream; }
        catch { clearTimeout(timer); if (body.exceeded()) return problem(413, "RELAY_BODY_TOO_LARGE", "Request body exceeds the operation limit"); if (request.signal.aborted) return new Response(null, { status: 499 }); if (controller.signal.aborted) return problem(504, "RELAY_UPSTREAM_TIMEOUT", "Platform request timed out"); options.onDiagnostic?.({ event: "failure", operationId: operation.id, method, status: 502 }); return problem(502, "RELAY_UPSTREAM_UNAVAILABLE", "Platform service is unavailable"); }
        finally { request.signal.removeEventListener("abort", disconnect); }
      }
    } catch (cause) {
      if (cause instanceof RelayInputError) return problem(cause.status, cause.code, cause.message);
      options.onDiagnostic?.({ event: "failure", method: request.method, status: 500 }); return problem(500, "RELAY_INTERNAL_ERROR", "Relay request failed");
    }
  };
}

interface CompiledOperation { readonly operation: RelayOperation; readonly segments: readonly string[]; }
function compileOperation(operation: RelayOperation): CompiledOperation { if (!operation.path.startsWith("/api/") || operation.path.includes("?") || operation.path.includes("#") || operation.path.includes("\\") || operation.path.split("/").includes("..")) throw new TypeError(`Invalid relay operation path: ${operation.path}`); return { operation: Object.freeze({ requestClass: "json", requiresTenant: true, idempotency: "none", ...operation }), segments: operation.path.slice(1).split("/") }; }
function findOperation(operations: readonly CompiledOperation[], method: RelayMethod, path: string) { const actual = path.slice(1).split("/"); for (const candidate of operations) { if (candidate.operation.method !== method || candidate.segments.length !== actual.length) continue; const params: Record<string, string> = {}; let matches = true; for (let index = 0; index < actual.length; index++) { const expected = candidate.segments[index]!; const value = actual[index]!; if (expected.startsWith(":")) params[expected.slice(1)] = value; else if (expected !== value) { matches = false; break; } } if (matches) return { operation: candidate.operation, params }; } return undefined; }
function normalizePath(segments: readonly string[]): `/api/${string}` { if (!segments.length) throw new RelayInputError(400, "RELAY_INVALID_PATH", "Relay path is empty"); const normalized = segments.map((segment) => { if (!segment || segment === "." || segment === ".." || segment.includes("/") || segment.includes("\\") || segment.includes("\0") || segment.includes("?") || segment.includes("#")) throw new RelayInputError(400, "RELAY_INVALID_PATH", "Relay path contains an unsafe segment"); return encodeURIComponent(segment); }); return `/api/${normalized.join("/")}`; }
function runtimeOrigin(value: string): URL { const url = new URL(value); if (!/^https?:$/.test(url.protocol) || url.username || url.password || url.search || url.hash) throw new TypeError("RUNTIME_API_URL must be a server-side HTTP(S) base URL without credentials, query, or fragment"); url.pathname = url.pathname.replace(/\/+$/, "").replace(/\/api$/i, "") + "/"; return url; }
function requestHeaders(input: Headers): Headers { const output = new Headers(); for (const [name, value] of input) { const lower = name.toLowerCase(); if (BLOCKED_REQUEST_HEADERS.has(lower) || !SAFE_REQUEST_HEADERS.has(lower) || lower === "content-length" || lower === "content-encoding") continue; output.set(lower, value); } return output; }
function enforceHeaderLimit(headers: Headers, limit: number): void { let bytes = 0; for (const [name, value] of headers) bytes += Buffer.byteLength(name) + Buffer.byteLength(value) + 4; if (bytes > limit) throw new RelayInputError(431, "RELAY_HEADERS_TOO_LARGE", "Request headers exceed the relay limit"); }
function verifyUnsafeRequest(request: Request, expectedOrigin: string, expectedCsrf: readonly string[]): Response | undefined { const origin = request.headers.get("origin"); const fetchSite = request.headers.get("sec-fetch-site"); if (origin !== expectedOrigin || (fetchSite && fetchSite !== "same-origin")) return problem(403, "RELAY_CROSS_ORIGIN", "Unsafe relay requests must be same-origin"); const supplied = request.headers.get("x-csrf-token"); if (!supplied || !expectedCsrf.some((candidate) => safeEqual(supplied, candidate))) return problem(403, "RELAY_CSRF_INVALID", "CSRF validation failed"); return undefined; }
function sameAuthority(previous: RelaySessionContext, refreshed: RelaySessionContext | undefined, plane: string): refreshed is RelaySessionContext { return !!refreshed && refreshed.plane === plane && refreshed.realmKey === previous.realmKey && refreshed.tenantId === previous.tenantId && refreshed.principalId === previous.principalId && refreshed.authEpoch === previous.authEpoch; }
function safeEqual(left: string, right: string): boolean { const a = Buffer.from(left); const b = Buffer.from(right); return a.length === b.length && timingSafeEqual(a, b); }
function validIdempotencyKey(value: string): boolean { return value.length <= 200 && /^[A-Za-z0-9._:-]+$/.test(value); }

interface PreparedBody { readonly replayable: boolean; forAttempt(attempt: number): BodyInit | undefined; exceeded(): boolean; }
async function prepareBody(request: Request, operation: RelayOperation, fallbackLimit: number): Promise<PreparedBody> { if (["GET", "HEAD"].includes(request.method)) return { replayable: true, forAttempt: () => undefined, exceeded: () => false }; const encoding = request.headers.get("content-encoding"); if (encoding && encoding.toLowerCase() !== "identity") throw new RelayInputError(415, "RELAY_CONTENT_ENCODING_UNSUPPORTED", "Compressed request bodies are not accepted by the relay"); const limit = operation.maxBodyBytes ?? fallbackLimit; const length = Number(request.headers.get("content-length")); if (Number.isFinite(length) && length > limit) throw new RelayInputError(413, "RELAY_BODY_TOO_LARGE", "Request body exceeds the operation limit"); if (!request.body) return { replayable: true, forAttempt: () => undefined, exceeded: () => false }; if ((operation.requestClass ?? "json") !== "upload") { const bytes = await readLimited(request.body, limit); return { replayable: true, forAttempt: () => bytes.slice(), exceeded: () => false }; } let size = 0; let tooLarge = false; const stream = request.body.pipeThrough(new TransformStream<Uint8Array, Uint8Array>({ transform(chunk, controller) { size += chunk.byteLength; if (size > limit) { tooLarge = true; controller.error(new RangeError("body limit")); } else controller.enqueue(chunk); } })); return { replayable: false, forAttempt: (attempt) => attempt === 0 ? stream : undefined, exceeded: () => tooLarge }; }
async function readLimited(stream: ReadableStream<Uint8Array>, limit: number): Promise<Uint8Array> { const reader = stream.getReader(); const chunks: Uint8Array[] = []; let total = 0; try { while (true) { const result = await reader.read(); if (result.done) break; total += result.value.byteLength; if (total > limit) throw new RelayInputError(413, "RELAY_BODY_TOO_LARGE", "Request body exceeds the operation limit"); chunks.push(result.value); } } finally { reader.releaseLock(); } const output = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { output.set(chunk, offset); offset += chunk.byteLength; } return output; }

async function isContextMismatch(response: Response): Promise<boolean> { if (response.status !== 403) return false; const type = response.headers.get("content-type") ?? ""; if (!/json/i.test(type) || !response.body) return false; const length = Number(response.headers.get("content-length")); if (Number.isFinite(length) && length > 64 * 1024) return false; try { const bytes = await readLimited(response.clone().body!, 64 * 1024); const value = JSON.parse(new TextDecoder().decode(bytes)) as Record<string, unknown>; return value.code === "AUTH_CONTEXT_MISMATCH" || value.error === "AUTH_CONTEXT_MISMATCH"; } catch { return false; } }
function relayResponse(upstream: Response, clientSignal: AbortSignal, requestClass: RelayRequestClass): Response { const headers = new Headers({ "cache-control": requestClass === "stream" ? "no-cache, no-transform" : "private, no-store" }); for (const [name, value] of upstream.headers) { const lower = name.toLowerCase(); if (!SAFE_RESPONSE_HEADERS.has(lower)) continue; if ((lower === "x-request-id" || lower === "x-correlation-id") && !safeIdentifier(value)) continue; headers.set(name, lower === "content-disposition" ? value.replace(/[\r\n\0]/g, "") : value); } const body = upstream.body ? cancelOnDisconnect(upstream.body, clientSignal) : null; return new Response(body, { status: upstream.status, statusText: upstream.statusText, headers }); }
function cancelOnDisconnect(body: ReadableStream<Uint8Array>, signal: AbortSignal): ReadableStream<Uint8Array> { const reader = body.getReader(); const cancel = () => void reader.cancel(signal.reason).catch(() => undefined); if (signal.aborted) cancel(); else signal.addEventListener("abort", cancel, { once: true }); return new ReadableStream({ async pull(controller) { try { const result = await reader.read(); if (result.done) { signal.removeEventListener("abort", cancel); controller.close(); } else controller.enqueue(result.value); } catch (cause) { controller.error(cause); } }, async cancel(reason) { signal.removeEventListener("abort", cancel); await reader.cancel(reason).catch(() => undefined); } }); }
function problem(status: number, code: string, title: string, requestId?: string, extraHeaders?: HeadersInit): Response { const value = { type: `https://athyper.dev/problems/${code}`, title, status, code, ...(requestId && safeIdentifier(requestId) ? { requestId } : {}) } satisfies ApiProblem; return new Response(JSON.stringify(value), { status, headers: { "content-type": "application/problem+json", "cache-control": "no-store", ...Object.fromEntries(new Headers(extraHeaders)) } }); }
function safeIdentifier(value: string): boolean { return /^[A-Za-z0-9._:-]{1,128}$/.test(value); }
class RelayInputError extends Error { constructor(readonly status: number, readonly code: string, message: string) { super(message); } }
