import { createOperation, encodePathSegment, type HttpClient } from "@athyper/platform-api-client";

export type WorkItemStatus="open"|"claimed"|"in_progress"|"blocked"|"completed"|"cancelled";
export type WorkItemPriority="low"|"normal"|"high"|"urgent";
export interface WorkItem {readonly id:string;readonly tenantId:string;readonly workTypeCode:string;readonly title:string;readonly description?:string;readonly sourceEntityCode:string;readonly sourceEntityId:string;readonly sourceActionCode?:string;readonly assigneePrincipalId?:string;readonly assigneeTeamId?:string;readonly claimantPrincipalId?:string;readonly availableAt:string;readonly dueAt?:string;readonly completedAt?:string;readonly priority:WorkItemPriority;readonly payload:Readonly<Record<string,unknown>>;readonly status:WorkItemStatus;readonly rowVersion:number;readonly createdAt:string;readonly createdBy:string;}
export interface WorkInboxPage{readonly data:readonly WorkItem[];readonly totalCount:number;readonly nextCursor?:string;}
export type WorkItemActionResult={readonly kind:"Committed";readonly workItem:WorkItem}|{readonly kind:"NotFound";readonly workItemId:string}|{readonly kind:"Forbidden";readonly permissionCode:string}|{readonly kind:"PolicyDenied";readonly policyIds:readonly string[];readonly reason?:string}|{readonly kind:"Conflict";readonly reason:string};
export const workInboxOperation=createOperation<WorkInboxPage>({method:"GET",path:"/api/workflow/inbox",parse:parsePage});
export const workItemActionOperation=createOperation<WorkItemActionResult,{readonly currentRowVersion:number;readonly outcome?:Readonly<Record<string,unknown>>}>({method:"POST",path:({id,action})=>`/api/workflow/items/${encodePathSegment(id)}/actions/${encodePathSegment(action)}`,parse:parseAction,idempotency:"required"});
export interface WorkInboxClient{list(options?:{readonly limit?:number;readonly cursor?:string;readonly statuses?:readonly WorkItemStatus[];readonly signal?:AbortSignal}):Promise<WorkInboxPage>;act(input:{readonly id:string;readonly action:string;readonly currentRowVersion:number;readonly outcome?:Readonly<Record<string,unknown>>;readonly idempotencyKey:string;readonly signal?:AbortSignal}):Promise<WorkItemActionResult>;}
export function createWorkInboxClient(client:HttpClient):WorkInboxClient{const implementation:WorkInboxClient={list:(options={})=>client.request(workInboxOperation,{signal:options.signal,query:{limit:options.limit??50,cursor:options.cursor,status:options.statuses?.join(",")}}),act:(input)=>client.request(workItemActionOperation,{params:{id:input.id,action:input.action},body:{currentRowVersion:input.currentRowVersion,...(input.outcome?{outcome:input.outcome}:{})},idempotencyKey:input.idempotencyKey,signal:input.signal})};return Object.freeze(implementation);}
function parsePage(value:unknown):WorkInboxPage{const body=record(value,"work inbox");if(!Array.isArray(body.data))throw new TypeError("data must be an array");const nextCursor=optional(body.nextCursor);return Object.freeze({data:Object.freeze(body.data.map(parseWorkItem)),totalCount:nonNegative(body.totalCount,"totalCount"),...(nextCursor?{nextCursor}:{})});}
function parseWorkItem(value:unknown):WorkItem{const body=record(value,"work item"),priority=body.priority,status=body.status;if(!["low","normal","high","urgent"].includes(String(priority)))throw new TypeError("Invalid priority");if(!["open","claimed","in_progress","blocked","completed","cancelled"].includes(String(status)))throw new TypeError("Invalid status");return Object.freeze({id:required(body.id,"id"),tenantId:required(body.tenantId,"tenantId"),workTypeCode:required(body.workTypeCode,"workTypeCode"),title:required(body.title,"title"),sourceEntityCode:required(body.sourceEntityCode,"sourceEntityCode"),sourceEntityId:required(body.sourceEntityId,"sourceEntityId"),availableAt:date(body.availableAt,"availableAt"),priority:priority as WorkItemPriority,payload:record(body.payload,"payload"),status:status as WorkItemStatus,rowVersion:positive(body.rowVersion,"rowVersion"),createdAt:date(body.createdAt,"createdAt"),createdBy:required(body.createdBy,"createdBy"),...optionals(body,["description","sourceActionCode","assigneePrincipalId","assigneeTeamId","claimantPrincipalId","dueAt","completedAt"] as const)});}
function parseAction(value:unknown):WorkItemActionResult{const body=record(value,"work item action"),kind=body.kind;if(kind==="Committed")return Object.freeze({kind,workItem:parseWorkItem(body.workItem)});if(kind==="NotFound")return Object.freeze({kind,workItemId:required(body.workItemId,"workItemId")});if(kind==="Forbidden")return Object.freeze({kind,permissionCode:required(body.permissionCode,"permissionCode")});if(kind==="PolicyDenied"){const reason=optional(body.reason);return Object.freeze({kind,policyIds:Array.isArray(body.policyIds)?Object.freeze(body.policyIds.map((value)=>required(value,"policyId"))):[],...(reason?{reason}:{})});}if(kind==="Conflict")return Object.freeze({kind,reason:required(body.reason,"reason")});throw new TypeError("Invalid work item action result");}
function record(value:unknown,name:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError(`${name} must be an object`);return value as Record<string,unknown>;}
function required(value:unknown,name:string):string{if(typeof value!=="string"||!value.trim())throw new TypeError(`${name} must be a non-empty string`);return value;}
function optional(value:unknown):string|undefined{return typeof value==="string"&&value.trim()?value:undefined;}
function date(value:unknown,name:string):string{const result=required(value,name);if(!Number.isFinite(Date.parse(result)))throw new TypeError(`${name} must be an ISO date`);return result;}
function positive(value:unknown,name:string):number{if(!Number.isSafeInteger(value)||Number(value)<1)throw new TypeError(`${name} must be a positive integer`);return Number(value);}
function nonNegative(value:unknown,name:string):number{if(!Number.isSafeInteger(value)||Number(value)<0)throw new TypeError(`${name} must be a non-negative integer`);return Number(value);}
function optionals<const K extends readonly string[]>(body:Record<string,unknown>,keys:K):Partial<Record<K[number],string>>{return Object.fromEntries(keys.flatMap((key)=>optional(body[key])?[[key,optional(body[key])]]:[])) as Partial<Record<K[number],string>>;}
