import {createHash,generateKeyPairSync,sign,verify} from "node:crypto";
import {PUBLICATION_ARTIFACT_MEDIA_TYPE_V1,PUBLICATION_ARTIFACT_SCHEMA_V1} from "@athyper/server-contract-publication";
import {describe,expect,it} from "vitest";
import {createBusinessPartnerFoundationDefinition,parseBusinessPartnerDefinitionBundle,VerifiedPublicationArtifactLoader} from "../index.js";

const hashes={request:"1".repeat(64),eligibility:"2".repeat(64),meshProfile:"3".repeat(64),meshMatch:"4".repeat(64)} as const;
describe("WP12 Business Partner definitions",()=>{
 it("provides versioned internal and MESH onboarding definitions without instance data",()=>{const bundle=createBusinessPartnerFoundationDefinition(hashes);expect(parseBusinessPartnerDefinitionBundle(bundle)).toEqual(bundle);expect(bundle.requestSchemas).toHaveProperty("internal");expect(bundle.requestSchemas).toHaveProperty("mesh");expect(JSON.stringify(bundle)).not.toMatch(/bankAccount|accountNumber/);});
 it("rejects sensitive instance fields from a definition",()=>{const bundle={...createBusinessPartnerFoundationDefinition(hashes),formDescriptors:{bankAccount:{value:"x"}}};expect(()=>parseBusinessPartnerDefinitionBundle(bundle)).toThrowError(/INSTANCE_DATA_FORBIDDEN/);});
 it("verifies an Ed25519-signed definition and emits bundle-specific evidence",async()=>{const bundle=createBusinessPartnerFoundationDefinition(hashes),canonicalBytes=(value:unknown)=>new TextEncoder().encode(JSON.stringify(value)),sha256=(value:Uint8Array)=>createHash("sha256").update(value).digest("hex"),payload={id:"12000000-0000-4000-8000-000000000001",tenantId:"12000000-0000-4000-8000-000000000002",revisionId:"12000000-0000-4000-8000-000000000003",releaseId:"12000000-0000-4000-8000-000000000004",releaseNo:1,publicationKey:"studio.business_partner.definition.business_partner.onboarding",plane:"neon" as const,bundleCode:bundle.bundleCode,semanticVersion:bundle.semanticVersion,bundleSchemaVersion:"1.0.0",bundleHash:sha256(canonicalBytes(bundle)),bundle,generatedAt:"2026-08-28T00:00:00.000Z"},envelope={schema:PUBLICATION_ARTIFACT_SCHEMA_V1,publicationKey:payload.publicationKey,releaseId:payload.releaseId,releaseNo:1,releaseKind:"publish" as const,targetPlane:"neon" as const,artifactKind:"business_partner_definition_bundle" as const,generatedAt:payload.generatedAt,compatibilityLevel:"backward_compatible" as const,payload},manifest={artifactSchema:PUBLICATION_ARTIFACT_SCHEMA_V1,mediaType:PUBLICATION_ARTIFACT_MEDIA_TYPE_V1,publicationKey:payload.publicationKey,releaseId:payload.releaseId,releaseNo:1,targetPlane:"neon" as const,artifactKind:"business_partner_definition_bundle" as const,payloadSha256:sha256(canonicalBytes(payload)),compiler:{name:"test",version:"1.0.0"},contractSchemaVersion:"1.0.0",descriptorSchemaVersion:"1.0.0",signatureAlgorithm:"Ed25519",signingKeyId:"wp12-test",createdAt:payload.generatedAt},{privateKey,publicKey}=generateKeyPairSync("ed25519"),signature=sign(null,canonicalBytes({envelope,manifest}),privateKey).toString("base64"),document={envelope,manifest,signature},bytes=canonicalBytes(document),artifactHash=sha256(bytes),loader=new VerifiedPublicationArtifactLoader({store:{get:async()=>bytes} as any,verifier:{verify:async input=>verify(null,input.bytes,publicKey,Buffer.from(input.signature,"base64"))},canonicalizer:{canonicalBytes,sha256},runtimeVersion:"1.0.0"});const loaded=await loader.load({deploymentId:"12000000-0000-4000-8000-000000000005",deploymentStatus:"dispatched",targetPlane:"neon",targetEnvironment:"test",targetInstance:"*",publicationKey:payload.publicationKey,sourceReleaseId:payload.releaseId,sourceReleaseNo:1,artifactUri:"s3://test/wp12.json",artifactHash,signatureAlgorithm:"Ed25519",signingKeyId:"wp12-test",signature});expect(loaded.verification).toMatchObject({signatureVerified:true,definitionBundleHash:payload.bundleHash,definitionBundleSchemaVersion:"1.0.0"});});
});
