import { FinanceContractError, financePermissions, type FinanceActor, type FinancePermissionChecker, type PlanningOutput, type PlanningOutputQuery, type PlanningRepository, type PlanningRun, type PlanningRunStatus } from "@athyper/server-contract-finance";
import type { FinanceAuditRecorder,FinanceOutboxWriter } from "../shared/evidence.js";

interface TransactionRunner<Transaction>{run<T>(actor:FinanceActor,work:(transaction:Transaction)=>Promise<T>):Promise<T>}

export class PlanningRunService<Transaction> {
  constructor(private readonly options:{readonly transactions:TransactionRunner<Transaction>;readonly repository:PlanningRepository<Transaction>;readonly permissions:FinancePermissionChecker;readonly audit:FinanceAuditRecorder<Transaction>;readonly outbox:FinanceOutboxWriter<Transaction>}){}
  async create(actor:FinanceActor,run:PlanningRun):Promise<{readonly run:PlanningRun;readonly replayed:boolean}>{requireNeon(actor);await requirePermission(this.options.permissions,actor,financePermissions.planningRun);validateRun(run);return this.options.transactions.run(actor,async tx=>{if(run.retryOfRunId){const prior=await this.options.repository.getRun(actor,run.retryOfRunId,tx);if(!prior||!(["failed","cancelled"] as const).includes(prior.status as "failed"|"cancelled")||prior.planningModelId!==run.planningModelId||prior.planningScenarioId!==run.planningScenarioId||prior.companyCodeId!==run.companyCodeId||prior.ledgerBookId!==run.ledgerBookId)throw new FinanceContractError("FINANCE_INVALID_COMMAND","Planning retry must reference a compatible failed or cancelled run");}const result=await this.options.repository.createRun(actor,{...run,status:"pending",metadata:immutableObject(run.metadata)},tx);if(!result.replayed)await evidence(this.options,actor,tx,"finance.planning.created",result.run.id,{planningModelId:result.run.planningModelId,inputHash:result.run.inputHash,retryOfRunId:result.run.retryOfRunId});return result;});}
  async transition(actor:FinanceActor,runId:string,expected:PlanningRunStatus,target:PlanningRunStatus,errorMessage?:string):Promise<PlanningRun>{requireNeon(actor);await requirePermission(this.options.permissions,actor,target==="approved"?financePermissions.planningApprove:financePermissions.planningRun);if(!allowed(expected,target))throw new FinanceContractError("FINANCE_INVALID_STATE_TRANSITION");if(target==="failed"&&!errorMessage?.trim())throw new FinanceContractError("FINANCE_INVALID_COMMAND","Failure requires a message");return this.options.transactions.run(actor,async tx=>{const current=await this.options.repository.getRun(actor,runId,tx);if(!current)throw new FinanceContractError("FINANCE_NOT_FOUND");if(current.status===target)return current;if(current.status!==expected)throw new FinanceContractError("FINANCE_EXPECTED_VERSION_CONFLICT","Planning run status changed",{expectedStatus:expected,actualStatus:current.status});const updated=await this.options.repository.transitionRun(actor,runId,expected,target,errorMessage?{errorMessage:errorMessage.trim()}:undefined,tx);if(!updated)throw new FinanceContractError("FINANCE_EXPECTED_VERSION_CONFLICT");await evidence(this.options,actor,tx,`finance.planning.${target}`,runId,{fromStatus:expected,toStatus:target,errorCode:target==="failed"?"PLANNING_EXECUTION_FAILED":undefined});return updated;});}
}

export class PlanningOutputService<Transaction>{
  constructor(private readonly options:{readonly transactions:TransactionRunner<Transaction>;readonly repository:PlanningRepository<Transaction>;readonly permissions:FinancePermissionChecker;readonly audit:FinanceAuditRecorder<Transaction>;readonly outbox:FinanceOutboxWriter<Transaction>}){}
  async append(actor:FinanceActor,output:PlanningOutput):Promise<{readonly output:PlanningOutput;readonly replayed:boolean}>{requireNeon(actor);await requirePermission(this.options.permissions,actor,financePermissions.planningRun);validateOutput(output);return this.options.transactions.run(actor,async tx=>{const run=await this.options.repository.getRun(actor,output.planningRunId,tx);if(!run)throw new FinanceContractError("FINANCE_NOT_FOUND");if(run.status!=="running")throw new FinanceContractError("FINANCE_INVALID_STATE_TRANSITION","Planning output may only be appended while the run is active");if(run.planningModelId!==output.planningModelId||run.ledgerBookId!==output.ledgerBookId)throw new FinanceContractError("FINANCE_INVALID_COMMAND","Output coordinates do not match the run");const result=await this.options.repository.appendOutput(actor,{...output,driverValues:immutableObject(output.driverValues),metadata:immutableObject(output.metadata)},tx);if(!result.replayed)await evidence(this.options,actor,tx,"finance.planning.output_appended",result.output.id,{planningRunId:result.output.planningRunId,fiscalYear:result.output.fiscalYear,periodNumber:result.output.periodNumber});return result;});}
  async list(actor:FinanceActor,input:PlanningOutputQuery){requireNeon(actor);await requirePermission(this.options.permissions,actor,financePermissions.planningRead);return this.options.repository.listOutput(actor,input);}
}

function validateRun(run:PlanningRun):void{if(run.status!=="pending"||run.modelVersionNumber<1||!/^[a-f0-9]{64}$/.test(run.inputHash))throw new FinanceContractError("FINANCE_IMMUTABLE_EVIDENCE","Planning identity evidence is invalid");if(run.startedAt||run.completedAt||run.approvedAt||run.approvedBy||run.errorMessage)throw new FinanceContractError("FINANCE_INVALID_COMMAND","New planning runs cannot contain lifecycle evidence");}
function validateOutput(output:PlanningOutput):void{assertDecimal(output.plannedAmount,"plannedAmount");if(output.baselineAmount!==undefined)assertDecimal(output.baselineAmount,"baselineAmount");if(output.fiscalYear<1900||output.fiscalYear>9999||output.periodNumber<1||output.periodNumber>16||output.currencyCode.length!==3||Boolean(output.projectWbsId&&!output.projectId))throw new FinanceContractError("FINANCE_INVALID_COMMAND");}
function assertDecimal(value:string,field:string):void{if(!/^-?(?:0|[1-9]\d*)(?:\.\d{1,4})?$/.test(value))throw new FinanceContractError("FINANCE_INVALID_COMMAND",`${field} must be a canonical numeric(18,4) value`);const digits=value.replace(/[-.]/g,"");if(digits.length>18)throw new FinanceContractError("FINANCE_INVALID_COMMAND",`${field} exceeds numeric(18,4)`);}
function allowed(from:PlanningRunStatus,to:PlanningRunStatus):boolean{return(from==="pending"&&(to==="running"||to==="cancelled"))||(from==="running"&&(to==="completed"||to==="failed"||to==="cancelled"))||(from==="completed"&&to==="approved");}
function immutableObject(value:Readonly<Record<string,unknown>>):Readonly<Record<string,unknown>>{if(!value||Array.isArray(value))throw new FinanceContractError("FINANCE_INVALID_COMMAND");return Object.freeze(structuredClone(value));}
function requireNeon(actor:FinanceActor):void{if(actor.planeKey!=="neon")throw new FinanceContractError("FINANCE_INVALID_COMMAND");}
async function requirePermission(checker:FinancePermissionChecker,actor:FinanceActor,code:string):Promise<void>{if(!await checker.isAllowed(actor,code))throw new FinanceContractError("FINANCE_PERMISSION_DENIED");}
async function evidence<Transaction>(options:{readonly audit:FinanceAuditRecorder<Transaction>;readonly outbox:FinanceOutboxWriter<Transaction>},actor:FinanceActor,transaction:Transaction,eventCode:string,entityId:string,metadata:Readonly<Record<string,unknown>>):Promise<void>{await options.outbox.append({tenantId:actor.tenantId,topic:"finance",eventType:eventCode,eventKey:entityId,aggregateType:"ledger.planning_run",aggregateId:entityId,actorId:actor.principalId,correlationId:actor.correlationId,payload:metadata},transaction);await options.audit.record({eventCode,action:eventCode.split(".").at(-1)??eventCode,outcome:"success",actor:{kind:"user",principalId:actor.principalId},tenantId:actor.tenantId,entityType:"ledger.planning_run",entityId,requestId:actor.correlationId,correlationId:actor.correlationId,metadata},transaction);}
