/** BP2-09A acceptance: disposable database only; all fixture changes roll back. */
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {KyselyBusinessPartnerAccountBankRepository,createBusinessPartnerAccountBankLinkageService} from '../../../server/packages/planes/neon/src/business-partner-account-bank-linkage.ts';
import {readBusinessPartner360CommercialControlSection} from '../../../server/packages/services/master-data/src/business-partner/banking/controls-reader';
const {Pool}=createRequire(new URL('../../../server/db/package.json',import.meta.url))('pg');
const {Kysely,PostgresDialect,sql}=createRequire(new URL('../../../server/packages/services/master-data/package.json',import.meta.url))('kysely');
const container=JSON.parse(execFileSync('docker',['inspect','athyper-bp2-acceptance-20260923'],{encoding:'utf8'}))[0];
assert.equal(container.Config.Labels['athyper.environment'],'disposable_local');
assert.equal(container.Config.Labels['athyper.purpose'],'bp2-acceptance');
const port=container.NetworkSettings.Ports['5432/tcp'][0];assert.equal(port.HostIp,'127.0.0.1');
const password=container.Config.Env.find((x:string)=>x.startsWith('POSTGRES_PASSWORD='))?.slice('POSTGRES_PASSWORD='.length);
const db=new Kysely({dialect:new PostgresDialect({pool:new Pool({host:'127.0.0.1',port:Number(port.HostPort),database:'athyper_neon',user:'postgres',password})})});
const rollback=Error('intentional rollback'),checks:string[]=[];
try {
 await db.transaction().execute(async(tx:any)=>{
  const tenant='44444444-4444-4444-8444-444444444444';
  const principal=(await sql`SELECT id FROM master.principal WHERE tenant_id=${tenant}::uuid AND code='catl.admin'`.execute(tx)).rows[0]?.id;assert.ok(principal);
  const bp=randomUUID();
  await sql`SELECT set_config('app.current_tenant_id',${tenant},true),set_config('app.current_principal_id',${principal},true),set_config('app.current_actor_type','user',true)`.execute(tx);
  await sql`INSERT INTO master.business_partner(id,tenant_id,code,name,status,category_locked_by,created_by) VALUES(${bp}::uuid,${tenant}::uuid,${'BP209A.'+bp.slice(0,8)},'Synthetic company-independent banking','active',${principal}::uuid,${principal}::uuid)`.execute(tx);
  const directoryBefore=(await sql`SELECT count(*)::int n FROM shared.bank_institution`.execute(tx)).rows[0].n;
  const auditSeed=readFileSync(new URL('../../../server/db/ddl/common/audit/12_reference_seed.sql',import.meta.url),'utf8');
  const bankAudit=auditSeed.split('-- BEGIN protected bank audit contracts')[1]?.split('-- END protected bank audit contracts')[0];assert.ok(bankAudit);
  await sql.raw(bankAudit).execute(tx);
  await sql`GRANT UPDATE(status,resolved_institution_id,resolved_branch_id) ON master.bank_provisional_reference TO athyperapp`.execute(tx);
  await sql`SET LOCAL ROLE athyperapp`.execute(tx);
  const repository=new KyselyBusinessPartnerAccountBankRepository();
  const source=await repository.protectedRegistrationSource(tenant,bp,undefined,tx);assert.ok(source);
  const registration=await repository.createProtectedRegistration({tenantId:tenant,principalId:principal,businessPartnerId:bp,accountHolderName:'Synthetic partner',accountIdType:'iban',accountFingerprint:'a'.repeat(64),accountLast4:'5432',currencyCode:'GBP',bankName:'Synthetic provisional bank',bankCountryCode:'GB',protectedValueToken:'bank:'+randomUUID(),idempotencyKey:'bp209a-'+bp,source},tx);
  assert.equal(registration.company_code_id,null);
  const link=registration.bank_account_link_id,account=registration.bank_account_id;
  assert.equal((await sql`SELECT count(*)::int n FROM master.bank_account_company_usage WHERE tenant_id=${tenant}::uuid AND bank_account_link_id=${link}::uuid`.execute(tx)).rows[0].n,0);
  assert.equal((await sql`SELECT count(*)::int n FROM master.supplier WHERE tenant_id=${tenant}::uuid AND business_partner_id=${bp}::uuid`.execute(tx)).rows[0].n,0);
  checks.push('app-role registration succeeds for a partner without supplier/company membership and creates no company usage');
  const provisional=(await sql`SELECT p.status FROM master.bank_account a JOIN master.bank_provisional_reference p ON p.tenant_id=a.tenant_id AND p.id=a.provisional_bank_reference_id WHERE a.id=${account}::uuid`.execute(tx)).rows[0];
  assert.equal(provisional.status,'unresolved');assert.equal((await sql`SELECT count(*)::int n FROM shared.bank_institution`.execute(tx)).rows[0].n,directoryBefore);
  checks.push('reference miss creates only a tenant-local unresolved provisional reference, never a global institution');
  const input={tenantId:tenant,businessPartnerId:bp,principalId:principal,sectionCode:'banking' as const,asOf:new Date().toISOString().slice(0,10),historical:false,authorizeCompany:async()=>false};
  const masked=await readBusinessPartner360CommercialControlSection(input,tx);
  assert.ok((masked.data as any).accounts.some((row:any)=>row.linkId===link&&row.lastFour==='5432'));
  assert.ok((masked.data as any).collections.bank_accounts.some((row:any)=>row.id===account&&row.account_last4==='5432'));
  assert.ok((masked.data as any).collections.bank_account_links.some((row:any)=>row.id===link&&row.owner_id===bp));
  assert.ok((masked.data as any).collections.bank_provisional_references.some((row:any)=>row.status==='unresolved'));
  assert.ok(!JSON.stringify(masked).includes('bank:'));assert.ok(!JSON.stringify(masked).includes('a'.repeat(64)));
  const company=(await sql`SELECT id FROM master.company_code WHERE tenant_id=${tenant}::uuid LIMIT 1`.execute(tx)).rows[0].id;
  const legacyLink=randomUUID();
  await sql`INSERT INTO master.bank_account_link(id,tenant_id,owner_type_id,owner_type,owner_id,relationship_role,bank_account_id,company_code_id,created_by) VALUES(${legacyLink}::uuid,${tenant}::uuid,${String(source.owner_type_id)}::uuid,'business_partner',${bp}::uuid,'beneficiary',${account}::uuid,${company}::uuid,${principal}::uuid)`.execute(tx);
  const legacy=await readBusinessPartner360CommercialControlSection({...input,companyCodeId:company},tx);
  assert.ok((legacy.data as any).accounts.some((row:any)=>row.linkId===legacyLink));assert.equal((legacy.data as any).supplierCompanyProfileId,undefined);
  assert.equal((legacy.data as any).collections.bank_accounts.filter((row:any)=>row.id===account).length,1);
  assert.equal((legacy.data as any).collections.bank_account_links.length,2);
  checks.push('masked reads include legacy company-tagged links even when no company is authorized; usage remains separate');
  assert.equal(await repository.protectedRegistration(tenant,randomUUID(),tx),null);
  assert.equal(await repository.protectedRegistration('11111111-1111-4111-8111-111111111111',link,tx),null);
  checks.push('inaccessible and cross-tenant registration links return no record');
  for(const event of ['business_partner.bank_registration.protected','business_partner.bank_registration.verified','business_partner.bank_registration.rejected','business_partner.bank_account.revealed','business_partner.bank_provisional.resolved']){
   const audit=(await sql`SELECT audit.append_event(p_event_code:=${event},p_operation:='execute',p_entity_type:='bank_account_link',p_entity_id:=${link}::uuid,p_outcome:='success',p_context:='{"synthetic":true}'::jsonb) id`.execute(tx)).rows[0];assert.ok(audit.id);
  }
  await sql`SAVEPOINT unknown_bank_audit`.execute(tx);
  await assert.rejects(()=>sql`SELECT audit.append_event(p_event_code:='business_partner.bank_registration.unregistered',p_operation:='execute',p_entity_type:='bank_account_link',p_outcome:='success')`.execute(tx),(error:any)=>error.code==='23503');
  await sql`ROLLBACK TO SAVEPOINT unknown_bank_audit`.execute(tx);
  checks.push('app-role audit contracts admit only the exact registration decisions/reveal events; unknown bank event denied');
  await sql`RESET ROLE`.execute(tx);
  await sql`SAVEPOINT normalizer_drift`.execute(tx);
  const functions=readFileSync(new URL('../../../server/db/ddl/planes/neon/master/07_functions.sql',import.meta.url),'utf8');
  const normalizer=functions.match(/CREATE OR REPLACE FUNCTION master\.trg_normalize_bank_account\(\)[\s\S]*?\n\$\$;/)?.[0];assert.ok(normalizer);
  await sql.raw(normalizer.replace("IF nullif(btrim(NEW.metadata->>'protectedValueToken'), '') IS NOT NULL THEN","IF false THEN")).execute(tx);
  await sql`SET LOCAL ROLE athyperapp`.execute(tx);
  await assert.rejects(()=>repository.createProtectedRegistration({tenantId:tenant,principalId:principal,businessPartnerId:bp,accountHolderName:'Synthetic drift',accountIdType:'iban',accountFingerprint:'b'.repeat(64),accountLast4:'5432',currencyCode:'GBP',bankName:'Synthetic drift bank',bankCountryCode:'GB',protectedValueToken:'bank:'+randomUUID(),idempotencyKey:'bp209a-drift-'+bp,source},tx),(error:any)=>error.code==='NEON_BANK_REGISTRATION_MASK_MISMATCH');
  await sql`ROLLBACK TO SAVEPOINT normalizer_drift`.execute(tx);
  checks.push('native repository refuses a deployed normalizer that substitutes fingerprint suffix for protected account suffix');
  const i1=randomUUID(),i2=randomUUID(),branch=randomUUID();
  await sql`INSERT INTO shared.bank_institution(id,name,country_code) VALUES(${i1}::uuid,'Synthetic bank one','GB'),(${i2}::uuid,'Synthetic bank two','GB')`.execute(tx);
  await sql`INSERT INTO shared.bank_branch(id,institution_id,name,country_code) VALUES(${branch}::uuid,${i2}::uuid,'Synthetic branch','GB')`.execute(tx);
  await sql`SAVEPOINT mismatch`.execute(tx);
  await assert.rejects(()=>sql`INSERT INTO master.bank_account(tenant_id,bank_institution_id,bank_branch_id,account_holder_name,account_id_type,account_id_value,account_last4,currency_code,created_by) VALUES(${tenant}::uuid,${i1}::uuid,${branch}::uuid,'Synthetic mismatch','iban',${'B'.repeat(64)},'1234','GBP',${principal}::uuid)`.execute(tx),(e:any)=>e.code==='23503');
  await sql`ROLLBACK TO SAVEPOINT mismatch`.execute(tx);checks.push('canonical composite constraint rejects a branch from a different institution');
  const checker=(await sql`SELECT id FROM master.principal WHERE tenant_id=${tenant}::uuid AND code='catl.owner'`.execute(tx)).rows[0].id;
  await sql`SELECT set_config('app.current_principal_id',${checker},true)`.execute(tx);
  await sql`SET LOCAL ROLE athyperapp`.execute(tx);
  const ctx:any={planeKey:'neon',tenantId:tenant,principalId:checker,permissions:{tenantId:tenant,principalId:checker,planeKey:'neon',allowed:[],denied:[],planLocked:[],planeExcluded:[],authorizationScopes:[]}};
  const commands=(failAudit=false)=>createBusinessPartnerAccountBankLinkageService({repository,authorizer:{authorize:async()=>({allowed:true})},transactions:{run:async(_p:any,_a:any,work:any)=>{await sql`SAVEPOINT resolution_command`.execute(tx);try{return await work(tx);}catch(error){await sql`ROLLBACK TO SAVEPOINT resolution_command`.execute(tx);throw error;}}},audit:{record:async(event:any)=>{if(failAudit)throw Error('synthetic audit failure');await sql`SELECT audit.append_event(p_event_code:=${event.eventCode},p_operation:='execute',p_entity_type:=${event.entityType},p_entity_id:=${event.entityId}::uuid,p_outcome:='success',p_context:=${JSON.stringify(event.metadata)}::jsonb)`.execute(tx);}}} as any);
  const native=commands();
  const verified=await native.decideProtectedBankRegistration({context:ctx,bankAccountLinkId:link,decision:'verify',verificationMethod:'manual_review',evidence:{synthetic:true}});assert.equal(verified.is_verified,true);
  const resolution={context:ctx,bankAccountLinkId:link,institutionId:i1,branchId:branch,evidenceReference:'synthetic-independent-directory-review'};
  await assert.rejects(()=>native.resolveProvisionalBankReference(resolution),(e:any)=>e.code==='NEON_ACCOUNT_BANK_INVALID');
  await assert.rejects(()=>commands(true).resolveProvisionalBankReference({...resolution,institutionId:i2}),/synthetic audit failure/);
  assert.equal((await repository.provisionalForRegistration(tenant,link,tx))?.status,'unresolved');
  checks.push('resolution and transactional audit fail atomically; failed capture leaves the provisional reference unresolved');
  await sql`RESET ROLE`.execute(tx);
  const before=(await sql`SELECT to_jsonb(a) account FROM master.bank_account a WHERE a.id=${account}::uuid`.execute(tx)).rows[0].account;
  await sql`SET LOCAL ROLE athyperapp`.execute(tx);
  const resolved=await native.resolveProvisionalBankReference({...resolution,institutionId:i2});assert.equal(resolved.replayed,false);
  assert.equal((await native.resolveProvisionalBankReference({...resolution,institutionId:i2})).replayed,true);
  await assert.rejects(()=>native.resolveProvisionalBankReference({...resolution,branchId:undefined}),(e:any)=>e.code==='NEON_BANK_PROVISIONAL_NOT_UNRESOLVED');
  await sql`RESET ROLE`.execute(tx);
  assert.deepEqual((await sql`SELECT to_jsonb(a) account FROM master.bank_account a WHERE a.id=${account}::uuid`.execute(tx)).rows[0].account,before);
  await sql`SET LOCAL ROLE athyperapp`.execute(tx);
  const refreshed=await readBusinessPartner360CommercialControlSection(input,tx);
  assert.ok((refreshed.data as any).collections.bank_provisional_references.some((r:any)=>r.status==='resolved'&&r.resolved_institution_id===i2&&r.resolved_branch_id===branch));
  assert.equal((await sql`SELECT count(*)::int n FROM shared.bank_institution`.execute(tx)).rows[0].n,directoryBefore+2);
  assert.equal(await repository.provisionalForRegistration('11111111-1111-4111-8111-111111111111',link,tx),null);
  checks.push('native checker resolution rejects branch mismatch, resolves existing directory references, retries safely, preserves the whole account, and refreshes the masked projection; cross-tenant handoff hidden');
  throw rollback;
 });
} catch(error){if(error!==rollback)throw error;} finally{await db.destroy();}
console.log(JSON.stringify({passed:true,rolledBack:true,checks},null,2));
