import type { FinanceActor, GlBalance, GlBalanceQuery, GlBalanceRepository, GlCoordinate } from "@athyper/server-contract-finance";
import { FinanceContractError } from "@athyper/server-contract-finance";
import { sql, type Transaction } from "kysely";

type Database = Record<string, never>; type Tx = Transaction<Database>; type Row = Record<string, unknown>;

export class KyselyGlBalanceRepository implements GlBalanceRepository<Tx> {
  async applyAggregate(input: { readonly actor: FinanceActor; readonly coordinate: GlCoordinate; readonly debit: string; readonly credit: string; readonly postingSequence: number; readonly idempotencyKey: string; readonly journalEntryId: string; readonly postedAt: string }, transaction: Tx): Promise<{ readonly balance: GlBalance; readonly replayed: boolean }> {
    const a=input.actor,c=input.coordinate;
    await sql`INSERT INTO ledger.gl_balance(tenant_id,company_code_id,ledger_book_id,fiscal_period_id,gl_account_id,currency_code,cost_center_id,profit_center_id,project_id,dimension_set_id,period_debit,period_credit,last_applied_sequence,last_idempotency_key,last_journal_entry_id,last_posted_at,created_by) VALUES(${a.tenantId}::uuid,${c.companyCodeId}::uuid,${c.ledgerBookId}::uuid,${c.fiscalPeriodId}::uuid,${c.glAccountId}::uuid,${c.currencyCode},${c.costCenterId??null}::uuid,${c.profitCenterId??null}::uuid,${c.projectId??null}::uuid,${c.dimensionSetId??null}::uuid,${input.debit}::numeric,${input.credit}::numeric,${input.postingSequence},${input.idempotencyKey},${input.journalEntryId}::uuid,${input.postedAt}::timestamptz,${a.principalId}::uuid) ON CONFLICT ON CONSTRAINT gl_balance_coordinate_uq DO NOTHING`.execute(transaction);
    let row=(await selectForUpdate(a,c,transaction)).rows[0]; if(!row)throw new Error("FINANCE_GL_BALANCE_LOCK_FAILED");
    if(String(row["last_idempotency_key"])===input.idempotencyKey)return{balance:map(row),replayed:true};
    const expected=Number(row["version_number"]), sequence=Math.max(Number(row["last_applied_sequence"])+1,input.postingSequence);
    row=(await sql<Row>`UPDATE ledger.gl_balance SET period_debit=period_debit+${input.debit}::numeric,period_credit=period_credit+${input.credit}::numeric,last_applied_sequence=${sequence},last_idempotency_key=${input.idempotencyKey},last_journal_entry_id=${input.journalEntryId}::uuid,last_posted_at=GREATEST(last_posted_at,${input.postedAt}::timestamptz),version_number=version_number+1,updated_by=${a.principalId}::uuid WHERE tenant_id=${a.tenantId}::uuid AND id=${String(row["id"])}::uuid AND version_number=${expected} RETURNING *`.execute(transaction)).rows[0];
    if(!row)throw new FinanceContractError("FINANCE_EXPECTED_VERSION_CONFLICT","Concurrent GL projection update"); return{balance:map(row),replayed:false};
  }
  async list(actor:FinanceActor,q:GlBalanceQuery,tx:Tx):Promise<readonly GlBalance[]>{return(await sql<Row>`SELECT * FROM ledger.gl_balance WHERE tenant_id=${actor.tenantId}::uuid AND company_code_id=${q.companyCodeId}::uuid AND ledger_book_id=${q.ledgerBookId}::uuid AND fiscal_period_id=${q.fiscalPeriodId}::uuid AND (${q.glAccountId??null}::uuid IS NULL OR gl_account_id=${q.glAccountId??null}::uuid) AND (${q.currencyCode??null}::text IS NULL OR currency_code=${q.currencyCode??null}) ORDER BY gl_account_id,currency_code,id`.execute(tx)).rows.map(map);}
}

function selectForUpdate(actor:FinanceActor,c:GlCoordinate,tx:Tx){return sql<Row>`SELECT * FROM ledger.gl_balance WHERE tenant_id=${actor.tenantId}::uuid AND company_code_id=${c.companyCodeId}::uuid AND ledger_book_id=${c.ledgerBookId}::uuid AND fiscal_period_id=${c.fiscalPeriodId}::uuid AND gl_account_id=${c.glAccountId}::uuid AND currency_code=${c.currencyCode} AND cost_center_id IS NOT DISTINCT FROM ${c.costCenterId??null}::uuid AND profit_center_id IS NOT DISTINCT FROM ${c.profitCenterId??null}::uuid AND project_id IS NOT DISTINCT FROM ${c.projectId??null}::uuid AND dimension_set_id IS NOT DISTINCT FROM ${c.dimensionSetId??null}::uuid FOR UPDATE`.execute(tx);}
function map(r:Row):GlBalance{return{id:String(r["id"]),companyCodeId:String(r["company_code_id"]),ledgerBookId:String(r["ledger_book_id"]),fiscalPeriodId:String(r["fiscal_period_id"]),glAccountId:String(r["gl_account_id"]),currencyCode:String(r["currency_code"]).trim(),...(r["cost_center_id"]?{costCenterId:String(r["cost_center_id"])}:{}),...(r["profit_center_id"]?{profitCenterId:String(r["profit_center_id"])}:{}),...(r["project_id"]?{projectId:String(r["project_id"])}:{}),...(r["dimension_set_id"]?{dimensionSetId:String(r["dimension_set_id"])}:{}),openingDebit:String(r["opening_debit"]),openingCredit:String(r["opening_credit"]),periodDebit:String(r["period_debit"]),periodCredit:String(r["period_credit"]),closingDebit:String(r["closing_debit"]),closingCredit:String(r["closing_credit"]),lastAppliedSequence:Number(r["last_applied_sequence"]),lastIdempotencyKey:String(r["last_idempotency_key"]),lastJournalEntryId:String(r["last_journal_entry_id"]),lastPostedAt:date(r["last_posted_at"]),versionNumber:Number(r["version_number"])};}
function date(v:unknown):string{return v instanceof Date?v.toISOString():String(v);}
