import type { CommitmentFulfillment,CommitmentFulfillmentCommand,CommitmentRepository,FinanceActor } from "@athyper/server-contract-finance";import{sql,type Transaction}from"kysely";
type DB=Record<string,never>;type Tx=Transaction<DB>;type Row=Record<string,unknown>;
export class KyselyCommitmentRepository implements CommitmentRepository<Tx>{
 async append(c:CommitmentFulfillmentCommand,tx:Tx){const p=c.payload,row=(await sql<Row>`INSERT INTO ledger.commitment_fulfillment(id,tenant_id,company_code_id,commitment_id,commitment_line_id,fulfillment_type,fulfillment_date,fiscal_period_id,quantity,uom_code,amount,currency_code,base_amount,base_currency_code,exchange_rate,source_entity_type,source_entity_id,source_line_id,reverses_fulfillment_id,idempotency_key,notes,metadata,created_by) VALUES(${c.commandId}::uuid,${c.actor.tenantId}::uuid,${p.companyCodeId}::uuid,${p.commitmentId}::uuid,${p.commitmentLineId}::uuid,${p.fulfillmentType},${p.fulfillmentDate}::date,${p.fiscalPeriodId}::uuid,${p.quantity??null}::numeric,${p.uomCode??null},${p.amount}::numeric,${p.currencyCode},${p.baseAmount}::numeric,${p.baseCurrencyCode},${p.exchangeRate}::numeric,${p.source.sourceType},${p.source.sourceId}::uuid,${p.source.sourceLineId??null}::uuid,${p.reversesFulfillmentId??null}::uuid,${c.idempotencyKey},${null},${JSON.stringify({...p.metadata,sourceVersion:p.source.version,sourceHash:p.source.hash,commitmentVersion:p.sourceSnapshot.version,commitmentHash:p.sourceSnapshot.hash,postingCoordinates:p.postingCoordinates})}::jsonb,${c.actor.principalId}::uuid) RETURNING *`.execute(tx)).rows[0];if(!row)throw new Error("FINANCE_COMMITMENT_APPEND_FAILED");return map(row);}
 async get(a:FinanceActor,id:string,tx:Tx){const row=(await sql<Row>`SELECT * FROM ledger.commitment_fulfillment WHERE tenant_id=${a.tenantId}::uuid AND id=${id}::uuid`.execute(tx)).rows[0];return row?map(row):undefined;}
 async list(a:FinanceActor,commitmentId:string,lineId:string,tx?:Tx){if(!tx)throw new Error("Commitment reads require a plane-local transaction");await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`${a.tenantId}:${commitmentId}:${lineId}`},0))`.execute(tx);return(await sql<Row>`SELECT * FROM ledger.commitment_fulfillment WHERE tenant_id=${a.tenantId}::uuid AND commitment_id=${commitmentId}::uuid AND commitment_line_id=${lineId}::uuid ORDER BY created_at,id`.execute(tx)).rows.map(map);}
}
function map(r:Row):CommitmentFulfillment{const m=obj(r["metadata"]);return{id:String(r["id"]),companyCodeId:String(r["company_code_id"]),commitmentId:String(r["commitment_id"]),commitmentLineId:String(r["commitment_line_id"]),fulfillmentType:String(r["fulfillment_type"]) as CommitmentFulfillment["fulfillmentType"],fulfillmentDate:date(r["fulfillment_date"]).slice(0,10),fiscalPeriodId:String(r["fiscal_period_id"]),...(r["quantity"]!==null?{quantity:String(r["quantity"])}:{}),...(r["uom_code"]?{uomCode:String(r["uom_code"])}:{}),amount:String(r["amount"]),currencyCode:String(r["currency_code"]).trim(),baseAmount:String(r["base_amount"]),baseCurrencyCode:String(r["base_currency_code"]).trim(),exchangeRate:String(r["exchange_rate"]),source:{sourceType:String(r["source_entity_type"]),sourceId:String(r["source_entity_id"]),version:Number(m["sourceVersion"]),hash:String(m["sourceHash"]),...(r["source_line_id"]?{sourceLineId:String(r["source_line_id"])}:{})},...(r["reverses_fulfillment_id"]?{reversesFulfillmentId:String(r["reverses_fulfillment_id"])}:{}),idempotencyKey:String(r["idempotency_key"]),metadata:m};}
function obj(v:unknown):Record<string,unknown>{if(typeof v==="string")try{return JSON.parse(v)as Record<string,unknown>;}catch{return{};}return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}function date(v:unknown){return v instanceof Date?v.toISOString():String(v);}
