import { FinanceContractError, type CrossBookExecutionRepository, type CrossBookPostingCommand, type CrossBookPostingExecution, type FinanceActor } from "@athyper/server-contract-finance";
import { sql, type Transaction } from "kysely";
type Database=Record<string,never>;type Tx=Transaction<Database>;type Row=Record<string,unknown>;
export class KyselyCrossBookExecutionRepository implements CrossBookExecutionRepository<Tx>{
 async create(command:CrossBookPostingCommand,input:{readonly destinationCommandId:string;readonly evidencePayload:Readonly<Record<string,unknown>>},tx:Tx){const p=command.payload;const inserted=await sql<Row>`INSERT INTO ledger.cross_book_posting_execution(id,tenant_id,company_code_id,source_journal_entry_id,cross_book_posting_policy_id,posting_policy_effective_from,idempotency_key,evidence_payload,correlation_id,created_by) VALUES(${command.commandId}::uuid,${command.actor.tenantId}::uuid,${p.policy.companyCodeId}::uuid,${p.sourceJournal.sourceId}::uuid,${p.policy.policyId}::uuid,${p.policy.effectiveFrom}::date,${command.idempotencyKey},${JSON.stringify(input.evidencePayload)}::jsonb,${command.actor.correlationId}::uuid,${command.actor.principalId}::uuid) ON CONFLICT DO NOTHING RETURNING *,xmin::text::bigint AS version_number`.execute(tx);let row=inserted.rows[0];if(!row)row=(await sql<Row>`SELECT *,xmin::text::bigint AS version_number FROM ledger.cross_book_posting_execution WHERE tenant_id=${command.actor.tenantId}::uuid AND source_journal_entry_id=${p.sourceJournal.sourceId}::uuid AND cross_book_posting_policy_id=${p.policy.policyId}::uuid AND posting_policy_effective_from=${p.policy.effectiveFrom}::date FOR UPDATE`.execute(tx)).rows[0];if(!row)throw new FinanceContractError("FINANCE_IDEMPOTENCY_CONFLICT","Cross-book idempotency key is already used by another source");const existing=map(row);if(existing.destinationCommandId!==input.destinationCommandId)throw new FinanceContractError("FINANCE_IDEMPOTENCY_CONFLICT","Cross-book source/policy identity has different immutable evidence");return{execution:existing,replayed:!inserted.rows[0]};}
 async claim(actor:FinanceActor,id:string,tx:Tx){const current=(await sql<Row>`SELECT *,xmin::text::bigint AS version_number FROM ledger.cross_book_posting_execution WHERE tenant_id=${actor.tenantId}::uuid AND id=${id}::uuid FOR UPDATE`.execute(tx)).rows[0];if(!current)return undefined;if(current["status"]==="succeeded"||current["status"]==="cancelled")return map(current);const row=(await sql<Row>`UPDATE ledger.cross_book_posting_execution SET status='processing',attempt_count=attempt_count+1,last_attempt_at=now(),completed_at=NULL,error_code=NULL,error_detail=NULL,status_changed_by=${actor.principalId}::uuid,updated_by=${actor.principalId}::uuid WHERE tenant_id=${actor.tenantId}::uuid AND id=${id}::uuid RETURNING *,xmin::text::bigint AS version_number`.execute(tx)).rows[0];if(!row)throw new Error("FINANCE_CROSS_BOOK_CLAIM_FAILED");return map(row);}
 async succeed(actor:FinanceActor,id:string,target:string,evidence:Readonly<Record<string,unknown>>,tx:Tx){const row=(await sql<Row>`UPDATE ledger.cross_book_posting_execution SET status='succeeded',target_journal_entry_id=${target}::uuid,completed_at=now(),evidence_payload=evidence_payload||${JSON.stringify({completion:evidence})}::jsonb,status_changed_by=${actor.principalId}::uuid,updated_by=${actor.principalId}::uuid WHERE tenant_id=${actor.tenantId}::uuid AND id=${id}::uuid AND status='processing' RETURNING *,xmin::text::bigint AS version_number`.execute(tx)).rows[0];if(!row){const existing=await this.get(actor,id,tx);if(existing?.status==="succeeded"&&existing.targetJournalEntryId===target)return existing;throw new FinanceContractError("FINANCE_INVALID_STATE_TRANSITION","Cross-book execution is not processing");}return map(row);}
 async fail(actor:FinanceActor,id:string,code:string,detail:Readonly<Record<string,unknown>>,tx:Tx){const row=(await sql<Row>`UPDATE ledger.cross_book_posting_execution SET status='failed',completed_at=now(),error_code=${code},error_detail=${JSON.stringify(detail)}::jsonb,evidence_payload=evidence_payload||${JSON.stringify({lastFailure:{code,detail}})}::jsonb,status_changed_by=${actor.principalId}::uuid,updated_by=${actor.principalId}::uuid WHERE tenant_id=${actor.tenantId}::uuid AND id=${id}::uuid AND status='processing' RETURNING *,xmin::text::bigint AS version_number`.execute(tx)).rows[0];if(!row)throw new FinanceContractError("FINANCE_INVALID_STATE_TRANSITION","Cross-book execution is not processing");return map(row);}
 async get(actor:FinanceActor,id:string,tx?:Tx){if(!tx)throw new Error("Cross-book reads require a plane-local transaction");const row=(await sql<Row>`SELECT *,xmin::text::bigint AS version_number FROM ledger.cross_book_posting_execution WHERE tenant_id=${actor.tenantId}::uuid AND id=${id}::uuid`.execute(tx)).rows[0];return row?map(row):undefined;}
}
function map(r:Row):CrossBookPostingExecution{const evidence=object(r["evidence_payload"]);return{id:String(r["id"]),tenantId:String(r["tenant_id"]),companyCodeId:String(r["company_code_id"]),sourceJournalEntryId:String(r["source_journal_entry_id"]),crossBookPostingPolicyId:String(r["cross_book_posting_policy_id"]),postingPolicyEffectiveFrom:date(r["posting_policy_effective_from"]).slice(0,10),destinationCommandId:String(evidence["destinationCommandId"]),idempotencyKey:String(r["idempotency_key"]),status:String(r["status"]) as CrossBookPostingExecution["status"],attemptCount:Number(r["attempt_count"]),...(r["target_journal_entry_id"]?{targetJournalEntryId:String(r["target_journal_entry_id"])}:{}),...(r["error_code"]?{errorCode:String(r["error_code"])}:{}),...(r["error_detail"]?{errorDetail:object(r["error_detail"])}:{}),evidencePayload:evidence,versionNumber:Number(r["version_number"])};}
function object(v:unknown):Record<string,unknown>{if(typeof v==="string")try{return JSON.parse(v) as Record<string,unknown>;}catch{return{};}return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};}function date(v:unknown){return v instanceof Date?v.toISOString():String(v);}
