import { sql, type Kysely } from "kysely";
import { loadPostingRoleCoverage } from "./posting-role.service.js";
import { writeFinanceSetupAudit } from "./finance-setup-audit.service.js";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyDb=Kysely<any>;
export class FinanceTaxError extends Error { constructor(public code:string,public status:number,message:string,public details?:Record<string,unknown>){super(message);} }
const today=()=>new Date().toISOString().slice(0,10);
const TAX_ROLES=["input_tax_recoverable","output_tax_payable","input_tax_nonrecoverable","reverse_charge_input","reverse_charge_output","wht_payable","wht_receivable","tax_rounding_variance","tax_suspense"];
interface TaxComponentView {id:string;taxGroupId:string;taxGroupVersionId:string|null;taxRateScheduleId:string;calculationSeq:number;rateOverride:string|null;taxDirection:string;recoverabilityMode:string;reverseChargeMode:string;whtBasis:string|null;componentCode:string|null;rateValue:string;rateKind:string;taxTypeId:string;jurisdictionId:string;[key:string]:unknown;}
interface TaxGroupRow {id:string;code:string;name:string;description:string|null;jurisdictionId:string|null;jurisdictionCode:string|null;status:string;versionId:string|null;versionNo:number|null;effectiveFrom:string|null;effectiveTo:string|null;isCompound:boolean;roundingRuleId:string|null;versionStatus:string|null;}
interface TaxGroupView extends TaxGroupRow {components:TaxComponentView[];}

async function companyContext(db:AnyDb,tenantId:string,companyCode:string){
 const {rows}=await sql<{id:string;code:string;name:string;functional_currency:string;legal_entity_id:string;legal_entity_code:string;legal_entity_name:string;country_code:string|null;regulatory_framework:string|null;tenant_code:string;legacy_registration:string|null;legacy_jurisdiction_id:string|null}>`
 SELECT cc.id,cc.code,cc.name,trim(cc.functional_currency) AS functional_currency,cc.legal_entity_id,
   le.code AS legal_entity_code,le.name AS legal_entity_name,cc.country_code,cc.regulatory_framework,t.code AS tenant_code,
   cc.tax_registration_number AS legacy_registration,cc.tax_jurisdiction_id AS legacy_jurisdiction_id
 FROM master.company_code cc JOIN master.legal_entity le ON le.tenant_id=cc.tenant_id AND le.id=cc.legal_entity_id
 JOIN master.tenant t ON t.id=cc.tenant_id WHERE cc.tenant_id=${tenantId}::uuid AND cc.code=${companyCode} LIMIT 1`.execute(db);
 if(!rows[0])throw new FinanceTaxError("COMPANY_NOT_FOUND",404,`No Company ${companyCode} in the active Tenant.`);return rows[0];
}

export async function loadCompanyTaxSetup(db:AnyDb,tenantId:string,companyCode:string,asOfDate=today()){
 const company=await companyContext(db,tenantId,companyCode);
 const [registrations,groups,rounding,jurisdictions,wht,rules,posting]=await Promise.all([
  sql<Record<string,unknown>>`SELECT r.id,r.registration_type AS "registrationType",r.registration_number AS "registrationNumber",r.company_code_id AS "companyCodeId",r.jurisdiction_id AS "jurisdictionId",j.code AS "jurisdictionCode",j.name AS "jurisdictionName",r.filing_frequency AS "filingFrequency",r.effective_from::text AS "effectiveFrom",r.effective_to::text AS "effectiveTo",r.is_primary AS "isPrimary",r.status
   FROM master.organization_tax_registration r JOIN master.tax_jurisdiction j ON j.tenant_id=r.tenant_id AND j.id=r.jurisdiction_id
   WHERE r.tenant_id=${tenantId}::uuid AND r.legal_entity_id=${company.legal_entity_id}::uuid AND (r.company_code_id IS NULL OR r.company_code_id=${company.id}::uuid)
   ORDER BY r.is_primary DESC,r.effective_from DESC`.execute(db).then(x=>x.rows),
  listTaxGroups(db,tenantId,asOfDate),
  sql<Record<string,unknown>>`SELECT id,code,name,method,precision_digits AS "precisionDigits",minimum_unit::text AS "minimumUnit",status FROM control.rounding_rule WHERE tenant_id=${tenantId}::uuid AND status='active' ORDER BY code`.execute(db).then(x=>x.rows),
  sql<Record<string,unknown>>`SELECT id,code,name,country_code AS "countryCode",jurisdiction_type AS "jurisdictionType" FROM master.tax_jurisdiction WHERE tenant_id=${tenantId}::uuid AND status='active' ORDER BY code`.execute(db).then(x=>x.rows),
  sql<Record<string,unknown>>`SELECT w.id,w.jurisdiction_id AS "jurisdictionId",j.code AS "jurisdictionCode",w.tax_type_id AS "taxTypeId",tt.code AS "taxTypeCode",w.section_code AS "sectionCode",w.threshold_amount::text AS "thresholdAmount",trim(w.threshold_currency) AS "thresholdCurrency",w.reset_period AS "resetPeriod",w.per_transaction AS "perTransaction",w.effective_from::text AS "effectiveFrom",w.effective_to::text AS "effectiveTo",w.is_active AS "isActive" FROM control.wht_threshold_config w JOIN master.tax_jurisdiction j ON j.tenant_id=w.tenant_id AND j.id=w.jurisdiction_id JOIN master.tax_type tt ON tt.tenant_id=w.tenant_id AND tt.id=w.tax_type_id WHERE w.tenant_id=${tenantId}::uuid ORDER BY j.code,tt.code,w.section_code`.execute(db).then(x=>x.rows),
  sql<{active:number}>`SELECT count(*)::int AS active FROM control.tax_resolution_rule WHERE tenant_id=${tenantId}::uuid AND status='active' AND effective_from<=${asOfDate}::date AND(effective_to IS NULL OR effective_to>=${asOfDate}::date)`.execute(db).then(x=>x.rows[0]?.active??0),
  loadPostingRoleCoverage(db,tenantId,companyCode,asOfDate),
 ]);
 const activeRegistrations=registrations.filter(r=>r.status==="active"&&String(r.effectiveFrom)<=asOfDate&&(!r.effectiveTo||String(r.effectiveTo)>=asOfDate));
 const activeGroups=groups.groups.filter(g=>g.status==="active");
 const requiredRoles=new Set<string>();
 for(const group of activeGroups)for(const component of group.components){const d=String(component.taxDirection),whtFlag=Boolean(component.whtBasis);if(whtFlag){requiredRoles.add("wht_payable");requiredRoles.add("wht_receivable");}else if(["SALE","EXPORT"].includes(d))requiredRoles.add("output_tax_payable");else {requiredRoles.add("input_tax_recoverable");if(component.recoverabilityMode!=="FULL")requiredRoles.add("input_tax_nonrecoverable");}if(component.reverseChargeMode!=="NONE"){requiredRoles.add("reverse_charge_input");requiredRoles.add("reverse_charge_output");}}
 if(activeGroups.length)requiredRoles.add("tax_rounding_variance");
 const taxRows=posting.rows.filter(row=>TAX_ROLES.includes(row.roleCode));
 const postingReady=[...requiredRoles].every(role=>taxRows.some(row=>row.roleCode===role&&row.cells.length>0&&row.cells.every(cell=>cell.status==="resolved")));
 const readiness={registrationReady:activeRegistrations.length>0,groupsReady:activeGroups.length>0&&activeGroups.every(g=>g.components.length>0&&Boolean(g.roundingRuleId)),rulesReady:rules>0,postingRolesReady:postingReady,ready:false};
 readiness.ready=readiness.registrationReady&&readiness.groupsReady&&readiness.rulesReady&&readiness.postingRolesReady;
 return {company:{id:company.id,code:company.code,name:company.name,functionalCurrency:company.functional_currency,countryCode:company.country_code,regulatoryFramework:company.regulatory_framework,tenantCode:company.tenant_code,legalEntity:{id:company.legal_entity_id,code:company.legal_entity_code,name:company.legal_entity_name},legacyRegistration:{number:company.legacy_registration,jurisdictionId:company.legacy_jurisdiction_id}},asOfDate,registrations,groups:groups.groups,rateSchedules:groups.rateSchedules,roundingRules:rounding,jurisdictions,whtThresholds:wht,resolutionRuleCount:rules,postingRoleCoverage:{requiredRoles:[...requiredRoles],rows:taxRows,summary:posting.summary},readiness};
}

export async function listTaxGroups(db:AnyDb,tenantId:string,asOfDate=today(),includeDraft=false){
 const [{rows:groupRows},{rows:scheduleRows}]=await Promise.all([
 sql<TaxGroupRow>`SELECT g.id,g.code,g.name,g.description,g.jurisdiction_id AS "jurisdictionId",j.code AS "jurisdictionCode",g.status,
 v.id AS "versionId",v.version_no AS "versionNo",v.effective_from::text AS "effectiveFrom",v.effective_to::text AS "effectiveTo",COALESCE(v.is_compound,g.is_compound) AS "isCompound",COALESCE(v.rounding_rule_id,g.rounding_rule_id) AS "roundingRuleId",v.status AS "versionStatus"
 FROM control.tax_group g LEFT JOIN master.tax_jurisdiction j ON j.tenant_id=g.tenant_id AND j.id=g.jurisdiction_id
 LEFT JOIN LATERAL(SELECT * FROM control.tax_group_version x WHERE x.tenant_id=g.tenant_id AND x.tax_group_id=g.id AND x.status IN('active','draft') AND (${includeDraft} OR x.status='active') ORDER BY (x.status='draft') DESC,(x.status='active' AND x.effective_from<=${asOfDate}::date AND(x.effective_to IS NULL OR x.effective_to>=${asOfDate}::date)) DESC,x.version_no DESC LIMIT 1)v ON true
 WHERE g.tenant_id=${tenantId}::uuid ORDER BY g.code`.execute(db),
 sql<Record<string,unknown>>`SELECT s.id,s.jurisdiction_id AS "jurisdictionId",j.code AS "jurisdictionCode",s.tax_type_id AS "taxTypeId",tt.code AS "taxTypeCode",s.tax_direction AS "taxDirection",s.component_code AS "componentCode",s.rate_kind AS "rateKind",s.rate_value::text AS "rateValue",s.recoverability_mode AS "recoverabilityMode",s.recoverability_percent::text AS "recoverabilityPercent",s.reverse_charge_mode AS "reverseChargeMode",s.calculation_basis AS "calculationBasis",s.wht_basis AS "whtBasis",s.effective_from::text AS "effectiveFrom",s.effective_to::text AS "effectiveTo",s.status FROM control.tax_rate_schedule s JOIN master.tax_jurisdiction j ON j.tenant_id=s.tenant_id AND j.id=s.jurisdiction_id JOIN master.tax_type tt ON tt.tenant_id=s.tenant_id AND tt.id=s.tax_type_id WHERE s.tenant_id=${tenantId}::uuid ORDER BY j.code,tt.code,s.effective_from DESC`.execute(db)
 ]);
 const components=await sql<TaxComponentView>`SELECT c.id,c.tax_group_id AS "taxGroupId",c.tax_group_version_id AS "taxGroupVersionId",c.tax_rate_schedule_id AS "taxRateScheduleId",c.calculation_seq AS "calculationSeq",c.rate_override::text AS "rateOverride",s.tax_direction AS "taxDirection",s.recoverability_mode AS "recoverabilityMode",s.reverse_charge_mode AS "reverseChargeMode",s.wht_basis AS "whtBasis",s.component_code AS "componentCode",s.rate_value::text AS "rateValue",s.rate_kind AS "rateKind",s.tax_type_id AS "taxTypeId",s.jurisdiction_id AS "jurisdictionId" FROM control.tax_group_component c JOIN control.tax_rate_schedule s ON s.tenant_id=c.tenant_id AND s.id=c.tax_rate_schedule_id WHERE c.tenant_id=${tenantId}::uuid AND c.status='active' ORDER BY c.calculation_seq`.execute(db).then(x=>x.rows);
 const mappedGroups:TaxGroupView[]=groupRows.map(group=>({...group,components:components.filter(c=>c.taxGroupId===group.id&&((group.versionId&&c.taxGroupVersionId===group.versionId)||(!group.versionId&&!c.taxGroupVersionId)))}));
 return {groups:mappedGroups,rateSchedules:scheduleRows};
}

export async function loadTaxDefinitions(db:AnyDb,tenantId:string,asOfDate=today()){
 const [groups,roundingRules,jurisdictions,taxTypes,whtThresholds]=await Promise.all([
  listTaxGroups(db,tenantId,asOfDate,true),
  sql<Record<string,unknown>>`SELECT id,code,name,method,precision_digits AS "precisionDigits",minimum_unit::text AS "minimumUnit" FROM control.rounding_rule WHERE tenant_id=${tenantId}::uuid AND status='active' ORDER BY code`.execute(db).then(x=>x.rows),
  sql<Record<string,unknown>>`SELECT id,code,name,country_code AS "countryCode" FROM master.tax_jurisdiction WHERE tenant_id=${tenantId}::uuid AND status='active' ORDER BY code`.execute(db).then(x=>x.rows),
  sql<Record<string,unknown>>`SELECT id,code,name FROM master.tax_type WHERE tenant_id=${tenantId}::uuid AND status='active' ORDER BY code`.execute(db).then(x=>x.rows),
  sql<Record<string,unknown>>`SELECT id,jurisdiction_id AS "jurisdictionId",tax_type_id AS "taxTypeId",section_code AS "sectionCode",threshold_amount::text AS "thresholdAmount",trim(threshold_currency) AS "thresholdCurrency",reset_period AS "resetPeriod",per_transaction AS "perTransaction",effective_from::text AS "effectiveFrom",effective_to::text AS "effectiveTo",is_active AS "isActive" FROM control.wht_threshold_config WHERE tenant_id=${tenantId}::uuid ORDER BY effective_from DESC`.execute(db).then(x=>x.rows),
 ]);return {...groups,roundingRules,jurisdictions,taxTypes,whtThresholds};
}

export async function saveTaxGroupVersion(db:AnyDb,input:{tenantId:string;actorId:string;body:Record<string,unknown>}){
 const b=input.body,code=String(b.code??"").trim().toUpperCase(),name=String(b.name??"").trim(),components=Array.isArray(b.components)?b.components as Record<string,unknown>[]:[];
 if(!code||!name)throw new FinanceTaxError("INVALID_TAX_GROUP",400,"Tax Group code and name are required.");
 if(!b.roundingRuleId)throw new FinanceTaxError("ROUNDING_REQUIRED",400,"A Tax Group Version requires an explicit rounding rule.");
 if(!components.length)throw new FinanceTaxError("COMPONENT_REQUIRED",400,"A Tax Group Version requires at least one component.");
 const scheduleIds=components.map(c=>String(c.taxRateScheduleId??""));if(new Set(scheduleIds).size!==scheduleIds.length)throw new FinanceTaxError("DUPLICATE_COMPONENT",400,"A rate schedule may appear only once in a version.");
 const effectiveFrom=String(b.effectiveFrom??today()),effectiveTo=b.effectiveTo?String(b.effectiveTo):null,status=String(b.status??"draft");
 if(!["draft","active"].includes(status))throw new FinanceTaxError("INVALID_VERSION_STATUS",400,"Version status must be draft or active.");
 let result:{groupId:string;versionId:string;versionNo:number}|null=null;
 await db.transaction().execute(async trx=>{
  let groupId=typeof b.groupId==="string"?b.groupId:"";
  if(groupId){const updated=await sql<{id:string}>`UPDATE control.tax_group SET code=${code},name=${name},description=${b.description?String(b.description):null},jurisdiction_id=${b.jurisdictionId?String(b.jurisdictionId):null}::uuid,updated_at=now(),updated_by=${input.actorId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND id=${groupId}::uuid RETURNING id`.execute(trx);if(!updated.rows[0])throw new FinanceTaxError("TAX_GROUP_NOT_FOUND",404,"Tax Group not found.");}
  else {const inserted=await sql<{id:string}>`INSERT INTO control.tax_group(tenant_id,code,name,description,jurisdiction_id,is_compound,status,created_by)VALUES(${input.tenantId}::uuid,${code},${name},${b.description?String(b.description):null},${b.jurisdictionId?String(b.jurisdictionId):null}::uuid,${Boolean(b.isCompound)},'active',${input.actorId}::uuid)RETURNING id`.execute(trx);groupId=inserted.rows[0]!.id;}
  const versionId=typeof b.versionId==="string"?b.versionId:"";let versionNo=1,actualVersionId=versionId;
  if(versionId){const version=await sql<{version_no:number;status:string}>`SELECT version_no,status FROM control.tax_group_version WHERE tenant_id=${input.tenantId}::uuid AND id=${versionId}::uuid AND tax_group_id=${groupId}::uuid`.execute(trx);if(!version.rows[0])throw new FinanceTaxError("VERSION_NOT_FOUND",404,"Tax Group Version not found.");if(version.rows[0].status!=="draft")throw new FinanceTaxError("VERSION_IMMUTABLE",409,"Create a successor instead of editing an approved version.");versionNo=version.rows[0].version_no;await sql`UPDATE control.tax_group_version SET effective_from=${effectiveFrom}::date,effective_to=${effectiveTo}::date,is_compound=${Boolean(b.isCompound)},rounding_rule_id=${String(b.roundingRuleId)}::uuid,description=${b.description?String(b.description):null},updated_at=now(),updated_by=${input.actorId}::uuid WHERE id=${versionId}::uuid`.execute(trx);await sql`UPDATE control.tax_group_component SET status='inactive',updated_at=now(),updated_by=${input.actorId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND tax_group_version_id=${versionId}::uuid AND status='active'`.execute(trx);}
  else {const max=await sql<{next_no:number}>`SELECT COALESCE(max(version_no),0)::int+1 AS next_no FROM control.tax_group_version WHERE tenant_id=${input.tenantId}::uuid AND tax_group_id=${groupId}::uuid`.execute(trx);versionNo=max.rows[0]!.next_no;const created=await sql<{id:string}>`INSERT INTO control.tax_group_version(tenant_id,tax_group_id,version_no,effective_from,effective_to,is_compound,rounding_rule_id,description,status,created_by)VALUES(${input.tenantId}::uuid,${groupId}::uuid,${versionNo},${effectiveFrom}::date,${effectiveTo}::date,${Boolean(b.isCompound)},${String(b.roundingRuleId)}::uuid,${b.description?String(b.description):null},'draft',${input.actorId}::uuid)RETURNING id`.execute(trx);actualVersionId=created.rows[0]!.id;}
  for(const [index,component] of components.entries())await sql`INSERT INTO control.tax_group_component(tenant_id,tax_group_id,tax_group_version_id,tax_rate_schedule_id,calculation_seq,rate_override,status,created_by)VALUES(${input.tenantId}::uuid,${groupId}::uuid,${actualVersionId}::uuid,${String(component.taxRateScheduleId)}::uuid,${index+1},${component.rateOverride==null||component.rateOverride===""?null:Number(component.rateOverride)},'active',${input.actorId}::uuid)`.execute(trx);
  if(status==="active"){
    const conflicting=await sql<{id:string;effective_from:string}>`SELECT id,effective_from::text FROM control.tax_group_version WHERE tenant_id=${input.tenantId}::uuid AND tax_group_id=${groupId}::uuid AND id<>${actualVersionId}::uuid AND status='active' AND daterange(effective_from,COALESCE(effective_to,'9999-12-31'::date),'[]')&&daterange(${effectiveFrom}::date,COALESCE(${effectiveTo}::date,'9999-12-31'::date),'[]') ORDER BY effective_from`.execute(trx);
    if(conflicting.rows.some(row=>row.effective_from>=effectiveFrom))throw new FinanceTaxError("VERSION_EFFECTIVITY_CONFLICT",409,"A same-day or future approved version overlaps this effective period.");
    await sql`UPDATE control.tax_group_version SET status='superseded',effective_to=${effectiveFrom}::date-1,status_changed_at=now(),status_changed_by=${input.actorId}::uuid,updated_at=now(),updated_by=${input.actorId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND tax_group_id=${groupId}::uuid AND id=ANY(${conflicting.rows.map(row=>row.id)}::uuid[])`.execute(trx);
    await sql`UPDATE control.tax_group_version SET status='active',status_changed_at=now(),status_changed_by=${input.actorId}::uuid WHERE id=${actualVersionId}::uuid`.execute(trx);
  }
  result={groupId,versionId:actualVersionId,versionNo};
 });
 await writeFinanceSetupAudit(db,{tenantId:input.tenantId,actorId:input.actorId,activityType:"finance_setup.tax_group_version_saved",entityType:"tax_group_version",entityId:result!.versionId,detail:{groupId:result!.groupId,versionNo:result!.versionNo,status,componentCount:components.length}});
 return result!;
}

export async function saveOrganizationTaxRegistration(db:AnyDb,input:{tenantId:string;companyCode:string;actorId:string;body:Record<string,unknown>}){
 const company=await companyContext(db,input.tenantId,input.companyCode),b=input.body,id=typeof b.id==="string"?b.id:null;
 if(!b.jurisdictionId||!String(b.registrationNumber??"").trim())throw new FinanceTaxError("INVALID_REGISTRATION",400,"Jurisdiction and registration number are required.");
 const values={type:String(b.registrationType??"TAX_ID"),number:String(b.registrationNumber).trim(),from:String(b.effectiveFrom??today()),to:b.effectiveTo?String(b.effectiveTo):null,frequency:b.filingFrequency?String(b.filingFrequency):null,primary:Boolean(b.isPrimary),scope:b.companySpecific===false?null:company.id,status:String(b.status??"active")};
 const {rows}=id?await sql<{id:string}>`UPDATE master.organization_tax_registration SET jurisdiction_id=${String(b.jurisdictionId)}::uuid,registration_type=${values.type},registration_number=${values.number},filing_frequency=${values.frequency},effective_from=${values.from}::date,effective_to=${values.to}::date,is_primary=${values.primary},company_code_id=${values.scope}::uuid,status=${values.status},updated_at=now(),updated_by=${input.actorId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND id=${id}::uuid AND legal_entity_id=${company.legal_entity_id}::uuid RETURNING id`.execute(db):await sql<{id:string}>`INSERT INTO master.organization_tax_registration(tenant_id,legal_entity_id,company_code_id,jurisdiction_id,registration_type,registration_number,filing_frequency,effective_from,effective_to,is_primary,status,created_by)VALUES(${input.tenantId}::uuid,${company.legal_entity_id}::uuid,${values.scope}::uuid,${String(b.jurisdictionId)}::uuid,${values.type},${values.number},${values.frequency},${values.from}::date,${values.to}::date,${values.primary},${values.status},${input.actorId}::uuid)RETURNING id`.execute(db);
 if(!rows[0])throw new FinanceTaxError("REGISTRATION_NOT_FOUND",404,"Registration not found.");
 await writeFinanceSetupAudit(db,{tenantId:input.tenantId,actorId:input.actorId,companyCodeId:company.id,activityType:"finance_setup.tax_registration_saved",entityType:"organization_tax_registration",entityId:rows[0].id,detail:{registrationType:values.type,jurisdictionId:b.jurisdictionId,companySpecific:Boolean(values.scope)}});return {id:rows[0].id};
}

export async function saveWhtThreshold(db:AnyDb,input:{tenantId:string;actorId:string;body:Record<string,unknown>}){
 const b=input.body,id=typeof b.id==="string"?b.id:null,amount=Number(b.thresholdAmount);
 if(!b.jurisdictionId||!b.taxTypeId||!b.thresholdCurrency||!Number.isFinite(amount)||amount<=0)throw new FinanceTaxError("INVALID_WHT_THRESHOLD",400,"Jurisdiction, Tax Type, positive threshold and currency are required.");
 const values={section:b.sectionCode?String(b.sectionCode).trim():null,currency:String(b.thresholdCurrency).toUpperCase(),reset:String(b.resetPeriod??"fiscal_year"),perTransaction:Boolean(b.perTransaction),from:String(b.effectiveFrom??today()),to:b.effectiveTo?String(b.effectiveTo):null,active:b.isActive!==false};
 const {rows}=id?await sql<{id:string}>`UPDATE control.wht_threshold_config SET jurisdiction_id=${String(b.jurisdictionId)}::uuid,tax_type_id=${String(b.taxTypeId)}::uuid,section_code=${values.section},threshold_amount=${amount},threshold_currency=${values.currency},reset_period=${values.reset},per_transaction=${values.perTransaction},effective_from=${values.from}::date,effective_to=${values.to}::date,is_active=${values.active},updated_at=now(),updated_by=${input.actorId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND id=${id}::uuid RETURNING id`.execute(db):await sql<{id:string}>`INSERT INTO control.wht_threshold_config(tenant_id,jurisdiction_id,tax_type_id,section_code,threshold_amount,threshold_currency,reset_period,per_transaction,effective_from,effective_to,is_active,created_by)VALUES(${input.tenantId}::uuid,${String(b.jurisdictionId)}::uuid,${String(b.taxTypeId)}::uuid,${values.section},${amount},${values.currency},${values.reset},${values.perTransaction},${values.from}::date,${values.to}::date,${values.active},${input.actorId}::uuid)RETURNING id`.execute(db);
 if(!rows[0])throw new FinanceTaxError("WHT_THRESHOLD_NOT_FOUND",404,"WHT threshold not found.");await writeFinanceSetupAudit(db,{tenantId:input.tenantId,actorId:input.actorId,activityType:"finance_setup.wht_threshold_saved",entityType:"wht_threshold_config",entityId:rows[0].id,detail:{jurisdictionId:b.jurisdictionId,taxTypeId:b.taxTypeId,thresholdAmount:amount,currency:values.currency}});return {id:rows[0].id};
}

type RuleRow={id:string;code:string;name:string;resolved_tax_group_id:string;priority:number;scope_doc_entity_codes:string[]|null;billto:string|null;shipto:string|null;billfrom:string|null;shipfrom:string|null;tax_status:string|null;commodity:string|null;industry:string|null;requires_match:boolean;requires_mismatch:boolean};
export async function simulateTaxResolution(db:AnyDb,tenantId:string,companyCode:string,body:Record<string,unknown>){
 const company=await companyContext(db,tenantId,companyCode),date=String(body.documentDate??today()),amount=Math.abs(Number(body.amount??0)),currency=String(body.currency??company.functional_currency).toUpperCase();if(!Number.isFinite(amount))throw new FinanceTaxError("INVALID_AMOUNT",400,"Amount must be numeric.");
 const ctx={doc:String(body.documentType??"purchase_invoice"),billto:nullable(body.billToJurisdictionId),shipto:nullable(body.shipToJurisdictionId),billfrom:nullable(body.billFromJurisdictionId),shipfrom:nullable(body.shipFromJurisdictionId),status:nullable(body.counterpartyTaxStatus),commodity:nullable(body.commodityCategoryId),industry:nullable(body.supplierIndustryCode)};
 const {rows}=await sql<RuleRow>`SELECT id,code,name,resolved_tax_group_id,priority,scope_doc_entity_codes,scope_billto_jurisdiction_id::text AS billto,scope_shipto_jurisdiction_id::text AS shipto,scope_billfrom_jurisdiction_id::text AS billfrom,scope_shipfrom_jurisdiction_id::text AS shipfrom,scope_counterparty_tax_status AS tax_status,scope_commodity_category_id::text AS commodity,scope_supplier_industry_code AS industry,requires_shipto_shipfrom_match AS requires_match,requires_shipto_shipfrom_mismatch AS requires_mismatch FROM control.tax_resolution_rule WHERE tenant_id=${tenantId}::uuid AND status='active' AND effective_from<=${date}::date AND(effective_to IS NULL OR effective_to>=${date}::date)ORDER BY priority DESC,effective_from DESC,id`.execute(db);
 const candidates=rows.map(rule=>{const reasons:string[]=[];const reject=(message:string)=>reasons.push(message);if(rule.scope_doc_entity_codes&&!rule.scope_doc_entity_codes.includes(ctx.doc))reject("Document type not in rule scope.");for(const [label,expected,actual]of [["Bill-to",rule.billto,ctx.billto],["Ship-to",rule.shipto,ctx.shipto],["Bill-from",rule.billfrom,ctx.billfrom],["Ship-from",rule.shipfrom,ctx.shipfrom],["Tax status",rule.tax_status,ctx.status],["Commodity",rule.commodity,ctx.commodity],["Industry",rule.industry,ctx.industry]] as const)if(expected&&expected!==actual)reject(`${label} does not match.`);if(rule.requires_match&&(!ctx.shipto||!ctx.shipfrom||ctx.shipto!==ctx.shipfrom))reject("Ship-to/ship-from match required.");if(rule.requires_mismatch&&(!ctx.shipto||!ctx.shipfrom||ctx.shipto===ctx.shipfrom))reject("Ship-to/ship-from mismatch required.");return {ruleId:rule.id,ruleCode:rule.code,ruleName:rule.name,taxGroupId:rule.resolved_tax_group_id,priority:rule.priority,matched:reasons.length===0,reasons};});
 const matched=candidates.filter(x=>x.matched),topPriority=matched[0]?.priority,top=matched.filter(x=>x.priority===topPriority),ambiguous=top.length>1,winner=ambiguous?null:top[0]??null;
 if(!winner)return {request:{...ctx,date,amount,currency},winner:null,ambiguous,candidates,components:[],totals:{taxAmount:0,whtAmount:0,roundingAdjustment:0},requiredPostingRoles:[]};
 const groupData=await listTaxGroups(db,tenantId,date),group=groupData.groups.find(g=>g.id===winner.taxGroupId);if(!group)throw new FinanceTaxError("TAX_GROUP_NOT_FOUND",422,"Resolved Tax Group is unavailable.");if(!group.roundingRuleId)throw new FinanceTaxError("ROUNDING_UNRESOLVED",422,"Resolved Tax Group has no explicit rounding rule.");
 const rounding=(await sql<{method:string;precision_digits:number|null;minimum_unit:string|null}>`SELECT method,precision_digits,minimum_unit::text FROM control.rounding_rule WHERE tenant_id=${tenantId}::uuid AND id=${String(group.roundingRuleId)}::uuid AND status='active'`.execute(db)).rows[0];const minor=(await sql<{minor_units:number|null}>`SELECT minor_units FROM shared.currency WHERE code=${currency} AND status='active'`.execute(db)).rows[0]?.minor_units;if(!rounding||rounding.precision_digits==null&&minor==null)throw new FinanceTaxError("ROUNDING_UNRESOLVED",422,"Rounding precision cannot be resolved for the simulation currency.");
 let compoundBase=amount,taxAmount=0,whtAmount=0,roundingAdjustment=0;const roles=new Set<string>();const components=[];
 for(const component of group.components){const rate=Number(component.rateOverride??component.rateValue),base=group.isCompound?compoundBase:amount,exact=component.rateKind==="PERCENT"?base*rate/100:rate;const rounded=roundTax(exact,rounding.method,rounding.precision_digits??minor!,rounding.minimum_unit==null?null:Number(rounding.minimum_unit)),isWht=Boolean(component.whtBasis);let threshold:null|Record<string,unknown>=null,applies=true;if(isWht){const t=(await sql<Record<string,unknown>>`SELECT id,threshold_amount::text AS amount,trim(threshold_currency) AS currency,per_transaction,reset_period FROM control.wht_threshold_config WHERE tenant_id=${tenantId}::uuid AND jurisdiction_id=${String(component.jurisdictionId)}::uuid AND tax_type_id=${String(component.taxTypeId)}::uuid AND is_active=true AND effective_from<=${date}::date AND(effective_to IS NULL OR effective_to>=${date}::date)ORDER BY effective_from DESC LIMIT 1`.execute(db)).rows[0];if(t){const accumulated=Number(body.accumulatedAmount??0),thresholdAmount=Number(t.amount);applies=Boolean(t.per_transaction)?amount>=thresholdAmount:accumulated+amount>=thresholdAmount;threshold={...t,accumulatedAmount:accumulated,projectedAmount:accumulated+amount,applies};}roles.add("wht_payable");roles.add("wht_receivable");}else if(["SALE","EXPORT"].includes(String(component.taxDirection)))roles.add("output_tax_payable");else{roles.add("input_tax_recoverable");if(component.recoverabilityMode!=="FULL")roles.add("input_tax_nonrecoverable");}if(component.reverseChargeMode!=="NONE"){roles.add("reverse_charge_input");roles.add("reverse_charge_output");}const applied=applies?rounded.amount:0;if(isWht)whtAmount+=applied;else taxAmount+=applied;roundingAdjustment+=applies?rounded.adjustment:0;if(group.isCompound&&!isWht)compoundBase+=applied;components.push({...component,baseAmount:base,effectiveRate:rate,exactAmount:exact,taxAmount:applied,roundingAdjustment:applies?rounded.adjustment:0,whtThreshold:threshold});}
 if(roundingAdjustment!==0)roles.add("tax_rounding_variance");const posting=await loadPostingRoleCoverage(db,tenantId,companyCode,date),roleCoverage=[...roles].map(role=>({roleCode:role,ready:posting.rows.some(row=>row.roleCode===role&&row.cells.length>0&&row.cells.every(cell=>cell.status==="resolved"))}));return {request:{...ctx,date,amount,currency},winner,ambiguous,candidates,group:{id:group.id,code:group.code,name:group.name,versionId:group.versionId,versionNo:group.versionNo,isCompound:group.isCompound},rounding:{...rounding,precisionUsed:rounding.precision_digits??minor},components,totals:{taxAmount,whtAmount,roundingAdjustment,grossAmount:amount+taxAmount-whtAmount},requiredPostingRoles:roleCoverage};
}
function nullable(value:unknown){const text=String(value??"").trim();return text||null;}
export function calculateTaxRounding(value:number,method:string,precision:number,minimumUnit:number|null){return roundTax(value,method,precision,minimumUnit);}
function roundTax(value:number,method:string,precision:number,minimumUnit:number|null){const scale=10**precision,scaled=value*scale;let rounded=method==="ROUND_DOWN"?Math.trunc(scaled)/scale:method==="ROUND_UP"?(value>=0?Math.ceil(scaled):Math.floor(scaled))/scale:method==="ROUND_HALF_EVEN"?halfEven(scaled)/scale:Math.sign(value)*Math.floor(Math.abs(scaled)+.5)/scale;if(minimumUnit)rounded=method==="ROUND_DOWN"?Math.trunc(rounded/minimumUnit)*minimumUnit:method==="ROUND_UP"?(rounded>=0?Math.ceil(rounded/minimumUnit):Math.floor(rounded/minimumUnit))*minimumUnit:method==="ROUND_HALF_EVEN"?halfEven(rounded/minimumUnit)*minimumUnit:Math.sign(rounded)*Math.floor(Math.abs(rounded/minimumUnit)+.5)*minimumUnit;return {amount:rounded,adjustment:rounded-value};}
function halfEven(value:number){const floor=Math.floor(value),fraction=value-floor;if(Math.abs(fraction-.5)<1e-10)return floor%2===0?floor:floor+1;return Math.round(value);}
