BEGIN;

DO $guard$ BEGIN
  IF current_database() <> 'athyper_neon' OR current_setting('app.database_plane', true) <> 'neon' THEN
    RAISE EXCEPTION 'NEON MESH Business Partner profile projection migration requires the NEON plane';
  END IF;
END $guard$;

CREATE FUNCTION snapshot.mesh_business_partner_profile_payload_is_safe(p_payload jsonb)
RETURNS boolean LANGUAGE plpgsql IMMUTABLE SET search_path=pg_catalog,snapshot AS $$
DECLARE v_key text;v_value jsonb;
BEGIN
 IF jsonb_typeof(p_payload)='object' THEN FOR v_key,v_value IN SELECT key,value FROM jsonb_each(p_payload) LOOP IF lower(v_key)~'(bank|iban|swift|bic|routing|account.?number|tax|registration.?number|metadata|contact|email|phone|address|identifier)' THEN RETURN false;END IF;IF NOT snapshot.mesh_business_partner_profile_payload_is_safe(v_value) THEN RETURN false;END IF;END LOOP;
 ELSIF jsonb_typeof(p_payload)='array' THEN FOR v_value IN SELECT value FROM jsonb_array_elements(p_payload) LOOP IF NOT snapshot.mesh_business_partner_profile_payload_is_safe(v_value) THEN RETURN false;END IF;END LOOP;END IF;
 RETURN true;
END $$;
CREATE FUNCTION snapshot.trg_guard_mesh_business_partner_profile_received() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,snapshot AS $$ BEGIN IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'snapshot.mesh_business_partner_profile_received is immutable' USING ERRCODE='integrity_constraint_violation';END IF;IF NOT snapshot.mesh_business_partner_profile_payload_is_safe(NEW.payload_json) THEN RAISE EXCEPTION 'MESH Business Partner profile contains a prohibited key family' USING ERRCODE='check_violation';END IF;RETURN NEW;END $$;
CREATE FUNCTION control.trg_guard_mesh_business_partner_profile_evidence() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN RAISE EXCEPTION 'NEON MESH Business Partner inbox and processing evidence are immutable' USING ERRCODE='integrity_constraint_violation';END $$;
CREATE FUNCTION control.trg_guard_mesh_business_partner_profile_projection() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN IF TG_OP='DELETE' THEN RAISE EXCEPTION 'NEON MESH Business Partner projections are withdrawn, not deleted' USING ERRCODE='restrict_violation';END IF;IF ROW(OLD.id,OLD.tenant_id,OLD.source_tenant_id,OLD.source_network_account_id,OLD.recipient_network_account_id,OLD.network_relationship_id) IS DISTINCT FROM ROW(NEW.id,NEW.tenant_id,NEW.source_tenant_id,NEW.source_network_account_id,NEW.recipient_network_account_id,NEW.network_relationship_id) THEN RAISE EXCEPTION 'NEON MESH Business Partner projection coordinates are immutable' USING ERRCODE='integrity_constraint_violation';END IF;NEW.updated_at:=clock_timestamp();RETURN NEW;END $$;

CREATE TABLE control.mesh_business_partner_profile_inbox(
 id uuid NOT NULL DEFAULT shared.uuidv7(),tenant_id uuid NOT NULL,event_id uuid NOT NULL,event_type text NOT NULL,source_tenant_id uuid NOT NULL,source_network_account_id uuid NOT NULL,recipient_network_account_id uuid NOT NULL,network_relationship_id uuid NOT NULL,publication_id uuid NOT NULL,publication_version integer NOT NULL,lifecycle_version integer NOT NULL,schema_code text NOT NULL,schema_version integer NOT NULL,field_set_code text NOT NULL,payload_hash text NOT NULL,envelope_json jsonb NOT NULL,envelope_hash text NOT NULL,occurred_at timestamptz NOT NULL,received_at timestamptz NOT NULL DEFAULT clock_timestamp(),received_by uuid NOT NULL,
 CONSTRAINT mesh_bp_profile_inbox_pkey PRIMARY KEY(id),CONSTRAINT mesh_bp_profile_inbox_tenant_id_uq UNIQUE(tenant_id,id),CONSTRAINT mesh_bp_profile_inbox_event_uq UNIQUE(tenant_id,event_id),CONSTRAINT mesh_bp_profile_inbox_participants_chk CHECK(tenant_id<>source_tenant_id),CONSTRAINT mesh_bp_profile_inbox_event_type_chk CHECK(event_type IN('business_partner.profile_publication.published','business_partner.profile_publication.withdrawn')),CONSTRAINT mesh_bp_profile_inbox_version_chk CHECK(publication_version>=1 AND lifecycle_version>=1 AND schema_version>=1),CONSTRAINT mesh_bp_profile_inbox_field_set_chk CHECK(field_set_code~'^[a-z][a-z0-9_.-]{1,62}$'),CONSTRAINT mesh_bp_profile_inbox_payload_hash_chk CHECK(payload_hash~'^[a-f0-9]{64}$'),CONSTRAINT mesh_bp_profile_inbox_envelope_chk CHECK(jsonb_typeof(envelope_json)='object' AND pg_column_size(envelope_json)<=524288),CONSTRAINT mesh_bp_profile_inbox_envelope_hash_chk CHECK(envelope_hash~'^[a-f0-9]{64}$'),CONSTRAINT mesh_bp_profile_inbox_tenant_fk FOREIGN KEY(tenant_id) REFERENCES master.tenant(id) ON DELETE RESTRICT,CONSTRAINT mesh_bp_profile_inbox_received_by_fk FOREIGN KEY(tenant_id,received_by) REFERENCES master.principal(tenant_id,id) ON DELETE RESTRICT
);
CREATE TABLE control.mesh_business_partner_profile_processing_attempt(
 id uuid NOT NULL DEFAULT shared.uuidv7(),tenant_id uuid NOT NULL,inbox_event_id uuid NOT NULL,attempt_no integer NOT NULL,trigger_kind text NOT NULL,disposition text NOT NULL,reason_code text,details jsonb NOT NULL DEFAULT '{}'::jsonb,processed_at timestamptz NOT NULL DEFAULT clock_timestamp(),processed_by uuid NOT NULL,
 CONSTRAINT mesh_bp_profile_attempt_pkey PRIMARY KEY(id),CONSTRAINT mesh_bp_profile_attempt_tenant_id_uq UNIQUE(tenant_id,id),CONSTRAINT mesh_bp_profile_attempt_number_uq UNIQUE(tenant_id,inbox_event_id,attempt_no),CONSTRAINT mesh_bp_profile_attempt_number_chk CHECK(attempt_no>=1),CONSTRAINT mesh_bp_profile_attempt_trigger_chk CHECK(trigger_kind IN('delivery','replay')),CONSTRAINT mesh_bp_profile_attempt_disposition_chk CHECK(disposition IN('applied','duplicate','stale','quarantined')),CONSTRAINT mesh_bp_profile_attempt_reason_chk CHECK((disposition='applied' AND reason_code IS NULL)OR(disposition<>'applied' AND reason_code~'^[A-Z][A-Z0-9_]{2,95}$')),CONSTRAINT mesh_bp_profile_attempt_details_chk CHECK(jsonb_typeof(details)='object' AND pg_column_size(details)<=32768),CONSTRAINT mesh_bp_profile_attempt_inbox_fk FOREIGN KEY(tenant_id,inbox_event_id) REFERENCES control.mesh_business_partner_profile_inbox(tenant_id,id) ON DELETE RESTRICT,CONSTRAINT mesh_bp_profile_attempt_processed_by_fk FOREIGN KEY(tenant_id,processed_by) REFERENCES master.principal(tenant_id,id) ON DELETE RESTRICT
);
CREATE TABLE snapshot.mesh_business_partner_profile_received(
 id uuid NOT NULL DEFAULT shared.uuidv7(),tenant_id uuid NOT NULL,inbox_event_id uuid NOT NULL,source_tenant_id uuid NOT NULL,source_network_account_id uuid NOT NULL,recipient_network_account_id uuid NOT NULL,network_relationship_id uuid NOT NULL,publication_id uuid NOT NULL,publication_version integer NOT NULL,schema_code text NOT NULL,schema_version integer NOT NULL,field_set_code text NOT NULL,payload_json jsonb NOT NULL,payload_hash text NOT NULL,received_at timestamptz NOT NULL DEFAULT clock_timestamp(),received_by uuid NOT NULL,
 CONSTRAINT mesh_bp_profile_received_pkey PRIMARY KEY(id),CONSTRAINT mesh_bp_profile_received_tenant_id_uq UNIQUE(tenant_id,id),CONSTRAINT mesh_bp_profile_received_inbox_uq UNIQUE(tenant_id,inbox_event_id),CONSTRAINT mesh_bp_profile_received_publication_uq UNIQUE(tenant_id,publication_id),CONSTRAINT mesh_bp_profile_received_participants_chk CHECK(tenant_id<>source_tenant_id),CONSTRAINT mesh_bp_profile_received_version_chk CHECK(publication_version>=1 AND schema_version=1),CONSTRAINT mesh_bp_profile_received_schema_chk CHECK(schema_code='mesh.business_partner_profile' AND field_set_code='recipient_safe_v1'),CONSTRAINT mesh_bp_profile_received_payload_chk CHECK(jsonb_typeof(payload_json)='object' AND pg_column_size(payload_json)<=262144),CONSTRAINT mesh_bp_profile_received_safe_chk CHECK(snapshot.mesh_business_partner_profile_payload_is_safe(payload_json)),CONSTRAINT mesh_bp_profile_received_hash_chk CHECK(payload_hash~'^[a-f0-9]{64}$'),CONSTRAINT mesh_bp_profile_received_tenant_fk FOREIGN KEY(tenant_id) REFERENCES master.tenant(id) ON DELETE RESTRICT,CONSTRAINT mesh_bp_profile_received_inbox_fk FOREIGN KEY(tenant_id,inbox_event_id) REFERENCES control.mesh_business_partner_profile_inbox(tenant_id,id) ON DELETE RESTRICT,CONSTRAINT mesh_bp_profile_received_by_fk FOREIGN KEY(tenant_id,received_by) REFERENCES master.principal(tenant_id,id) ON DELETE RESTRICT
);
CREATE TABLE control.mesh_business_partner_profile_projection(
 id uuid NOT NULL DEFAULT shared.uuidv7(),tenant_id uuid NOT NULL,source_tenant_id uuid NOT NULL,source_network_account_id uuid NOT NULL,recipient_network_account_id uuid NOT NULL,network_relationship_id uuid NOT NULL,current_publication_id uuid NOT NULL,current_publication_version integer NOT NULL,current_lifecycle_version integer NOT NULL,current_snapshot_id uuid NOT NULL,last_inbox_event_id uuid NOT NULL,projection_status text NOT NULL,updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),updated_by uuid NOT NULL,
 CONSTRAINT mesh_bp_profile_projection_pkey PRIMARY KEY(id),CONSTRAINT mesh_bp_profile_projection_tenant_id_uq UNIQUE(tenant_id,id),CONSTRAINT mesh_bp_profile_projection_relationship_uq UNIQUE(tenant_id,network_relationship_id),CONSTRAINT mesh_bp_profile_projection_participants_chk CHECK(tenant_id<>source_tenant_id),CONSTRAINT mesh_bp_profile_projection_version_chk CHECK(current_publication_version>=1 AND current_lifecycle_version>=1),CONSTRAINT mesh_bp_profile_projection_status_chk CHECK(projection_status IN('active','withdrawn')),CONSTRAINT mesh_bp_profile_projection_snapshot_fk FOREIGN KEY(tenant_id,current_snapshot_id) REFERENCES snapshot.mesh_business_partner_profile_received(tenant_id,id) ON DELETE RESTRICT,CONSTRAINT mesh_bp_profile_projection_event_fk FOREIGN KEY(tenant_id,last_inbox_event_id) REFERENCES control.mesh_business_partner_profile_inbox(tenant_id,id) ON DELETE RESTRICT,CONSTRAINT mesh_bp_profile_projection_updated_by_fk FOREIGN KEY(tenant_id,updated_by) REFERENCES master.principal(tenant_id,id) ON DELETE RESTRICT
);

CREATE INDEX mesh_bp_profile_inbox_coordinate_idx ON control.mesh_business_partner_profile_inbox(tenant_id,network_relationship_id,publication_version DESC,lifecycle_version DESC);CREATE INDEX mesh_bp_profile_inbox_publication_idx ON control.mesh_business_partner_profile_inbox(tenant_id,publication_id,lifecycle_version DESC);CREATE INDEX mesh_bp_profile_attempt_quarantine_idx ON control.mesh_business_partner_profile_processing_attempt(tenant_id,processed_at DESC,inbox_event_id) WHERE disposition='quarantined';CREATE INDEX mesh_bp_profile_projection_source_idx ON control.mesh_business_partner_profile_projection(tenant_id,source_tenant_id,source_network_account_id,projection_status);CREATE INDEX mesh_bp_profile_received_relationship_idx ON snapshot.mesh_business_partner_profile_received(tenant_id,network_relationship_id,publication_version DESC);
CREATE TRIGGER trg_mesh_bp_profile_inbox_immutable BEFORE UPDATE OR DELETE ON control.mesh_business_partner_profile_inbox FOR EACH ROW EXECUTE FUNCTION control.trg_guard_mesh_business_partner_profile_evidence();CREATE TRIGGER trg_mesh_bp_profile_attempt_immutable BEFORE UPDATE OR DELETE ON control.mesh_business_partner_profile_processing_attempt FOR EACH ROW EXECUTE FUNCTION control.trg_guard_mesh_business_partner_profile_evidence();CREATE TRIGGER trg_mesh_bp_profile_projection_guard BEFORE UPDATE OR DELETE ON control.mesh_business_partner_profile_projection FOR EACH ROW EXECUTE FUNCTION control.trg_guard_mesh_business_partner_profile_projection();CREATE TRIGGER trg_mesh_bp_profile_received_validate BEFORE INSERT ON snapshot.mesh_business_partner_profile_received FOR EACH ROW EXECUTE FUNCTION snapshot.trg_guard_mesh_business_partner_profile_received();CREATE TRIGGER trg_mesh_bp_profile_received_immutable BEFORE UPDATE OR DELETE ON snapshot.mesh_business_partner_profile_received FOR EACH ROW EXECUTE FUNCTION snapshot.trg_guard_mesh_business_partner_profile_received();

ALTER TABLE control.mesh_business_partner_profile_inbox ENABLE ROW LEVEL SECURITY;ALTER TABLE control.mesh_business_partner_profile_inbox FORCE ROW LEVEL SECURITY;ALTER TABLE control.mesh_business_partner_profile_processing_attempt ENABLE ROW LEVEL SECURITY;ALTER TABLE control.mesh_business_partner_profile_processing_attempt FORCE ROW LEVEL SECURITY;ALTER TABLE control.mesh_business_partner_profile_projection ENABLE ROW LEVEL SECURITY;ALTER TABLE control.mesh_business_partner_profile_projection FORCE ROW LEVEL SECURITY;ALTER TABLE snapshot.mesh_business_partner_profile_received ENABLE ROW LEVEL SECURITY;ALTER TABLE snapshot.mesh_business_partner_profile_received FORCE ROW LEVEL SECURITY;
CREATE POLICY mesh_bp_profile_inbox_tenant_access ON control.mesh_business_partner_profile_inbox FOR ALL USING(tenant_id=shared.current_tenant_id_soft()) WITH CHECK(tenant_id=shared.current_tenant_id());CREATE POLICY mesh_bp_profile_inbox_owner_access ON control.mesh_business_partner_profile_inbox FOR ALL TO CURRENT_USER USING(true) WITH CHECK(true);CREATE POLICY mesh_bp_profile_attempt_tenant_access ON control.mesh_business_partner_profile_processing_attempt FOR ALL USING(tenant_id=shared.current_tenant_id_soft()) WITH CHECK(tenant_id=shared.current_tenant_id());CREATE POLICY mesh_bp_profile_attempt_owner_access ON control.mesh_business_partner_profile_processing_attempt FOR ALL TO CURRENT_USER USING(true) WITH CHECK(true);CREATE POLICY mesh_bp_profile_projection_tenant_access ON control.mesh_business_partner_profile_projection FOR ALL USING(tenant_id=shared.current_tenant_id_soft()) WITH CHECK(tenant_id=shared.current_tenant_id());CREATE POLICY mesh_bp_profile_projection_owner_access ON control.mesh_business_partner_profile_projection FOR ALL TO CURRENT_USER USING(true) WITH CHECK(true);CREATE POLICY mesh_bp_profile_received_tenant_read ON snapshot.mesh_business_partner_profile_received FOR SELECT USING(tenant_id=shared.current_tenant_id_soft());CREATE POLICY mesh_bp_profile_received_tenant_insert ON snapshot.mesh_business_partner_profile_received FOR INSERT WITH CHECK(tenant_id=shared.current_tenant_id());CREATE POLICY mesh_bp_profile_received_owner_access ON snapshot.mesh_business_partner_profile_received FOR ALL TO CURRENT_USER USING(true) WITH CHECK(true);

REVOKE ALL ON control.mesh_business_partner_profile_inbox,control.mesh_business_partner_profile_processing_attempt,control.mesh_business_partner_profile_projection,snapshot.mesh_business_partner_profile_received FROM PUBLIC;REVOKE ALL ON FUNCTION snapshot.mesh_business_partner_profile_payload_is_safe(jsonb),snapshot.trg_guard_mesh_business_partner_profile_received(),control.trg_guard_mesh_business_partner_profile_evidence(),control.trg_guard_mesh_business_partner_profile_projection() FROM PUBLIC;
DO $roles$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='athyperapp') THEN GRANT SELECT,INSERT ON control.mesh_business_partner_profile_inbox,control.mesh_business_partner_profile_processing_attempt,snapshot.mesh_business_partner_profile_received TO athyperapp;GRANT SELECT,INSERT,UPDATE ON control.mesh_business_partner_profile_projection TO athyperapp;GRANT EXECUTE ON FUNCTION snapshot.mesh_business_partner_profile_payload_is_safe(jsonb) TO athyperapp;END IF;IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='athyperadmin') THEN GRANT ALL PRIVILEGES ON control.mesh_business_partner_profile_inbox,control.mesh_business_partner_profile_processing_attempt,control.mesh_business_partner_profile_projection,snapshot.mesh_business_partner_profile_received TO athyperadmin;END IF;END $roles$;

INSERT INTO authz.permission(id,canonical_code,permission_kind,module_id,risk_tier,requires_mfa,requires_sod,is_shareable,is_delegable,is_overridable,metadata,status,created_by)
SELECT permission.id,permission.code,'entity_operation',module.id,permission.risk::authz.risk_tier_d,permission.mfa,false,false,false,false,'{"_seed":{"pack":"neon.business-partner-profile-projection","version":"1.0.0"}}'::jsonb,'published','00000000-0000-0000-0000-000000000000'::uuid FROM control.module module CROSS JOIN(VALUES
('c8fc15f7-82fc-5d55-9c9a-1fa67680c4c1'::uuid,'neon.business_partner_profile_projection.receive','medium',false),('b9663a43-b8aa-506f-882d-5210e861cfbd'::uuid,'neon.business_partner_profile_projection.read','low',false),('1af763bc-5615-51da-93ba-b339e065af44'::uuid,'neon.business_partner_profile_projection.replay','high',true))permission(id,code,risk,mfa) WHERE module.code='fnd' AND module.status='active' ON CONFLICT(canonical_code) DO UPDATE SET risk_tier=EXCLUDED.risk_tier,requires_mfa=EXCLUDED.requires_mfa,metadata=authz.permission.metadata||EXCLUDED.metadata,status='published';
INSERT INTO authz.permission_scope_kind(permission_id,scope_kind,propagation_mode,status,created_by) SELECT id,'tenant','exact','active','00000000-0000-0000-0000-000000000000'::uuid FROM authz.permission WHERE canonical_code IN('neon.business_partner_profile_projection.receive','neon.business_partner_profile_projection.read','neon.business_partner_profile_projection.replay') ON CONFLICT(permission_id,scope_kind,propagation_mode) DO UPDATE SET status='active';

DO $assertions$ BEGIN IF to_regclass('control.mesh_business_partner_profile_inbox') IS NULL OR to_regclass('snapshot.mesh_business_partner_profile_received') IS NULL OR to_regclass('control.mesh_business_partner_profile_projection') IS NULL THEN RAISE EXCEPTION 'NEON MESH Business Partner profile projection tables were not installed';END IF;IF(SELECT count(*) FROM authz.permission WHERE canonical_code LIKE 'neon.business_partner_profile_projection.%' AND status='published')<>3 THEN RAISE EXCEPTION 'NEON MESH Business Partner profile projection permissions were not installed';END IF;END $assertions$;

COMMIT;
