BEGIN;
SET LOCAL lock_timeout='5s';
-- Match typed command and SQL final-graph semantics; preserve the earlier applied member migration.
CREATE OR REPLACE FUNCTION metadata.validate_reference_members(draft uuid) RETURNS void LANGUAGE plpgsql SET search_path=pg_catalog,metadata AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM metadata.entity_field_choice c JOIN metadata.entity_field f ON f.id=c.entity_field_id AND f.change_set_id=draft WHERE c.change_set_id=draft AND f.data_type::text<>'enum') THEN RAISE EXCEPTION 'Choices require an enum field'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_surface_navigation_group g JOIN metadata.entity_surface s ON s.id=g.entity_surface_id WHERE g.change_set_id=draft AND s.surface_kind::text<>'detail') THEN RAISE EXCEPTION 'Navigation groups require detail surfaces'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_surface_section s JOIN metadata.entity_surface_navigation_group g ON g.id=s.navigation_group_id WHERE s.change_set_id=draft AND s.entity_surface_id<>g.entity_surface_id) THEN RAISE EXCEPTION 'Section navigation scope mismatch'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_surface_view v JOIN metadata.entity_surface s ON s.id=v.entity_surface_id WHERE v.change_set_id=draft AND s.surface_kind::text NOT IN ('list','embedded')) THEN RAISE EXCEPTION 'View surface is incompatible'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_surface_view_field v JOIN metadata.entity_surface_view view ON view.id=v.view_id JOIN metadata.entity_surface_field_binding b ON b.id=v.field_binding_id JOIN metadata.entity_field f ON f.id=b.entity_field_id WHERE v.change_set_id=draft AND (b.entity_surface_id<>view.entity_surface_id OR (v.visible_position IS NOT NULL AND f.data_type::text='uuid'))) THEN RAISE EXCEPTION 'View field scope/readable presentation is invalid'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_field_access f WHERE f.change_set_id=draft AND (NOT EXISTS(SELECT 1 FROM metadata.entity_target t WHERE t.change_set_id=draft AND t.target_plane=f.target_plane) OR cardinality(f.query_uses)<>(SELECT count(DISTINCT x) FROM unnest(f.query_uses) x))) THEN RAISE EXCEPTION 'Field access target/query use invalid'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_access_permission p WHERE p.change_set_id=draft AND NOT EXISTS(SELECT 1 FROM metadata.entity_target t WHERE t.change_set_id=draft AND t.target_plane=p.target_plane)) OR EXISTS(SELECT 1 FROM metadata.entity_authorization_profile p WHERE p.change_set_id=draft AND NOT EXISTS(SELECT 1 FROM metadata.entity_target t WHERE t.change_set_id=draft AND t.target_plane=p.target_plane)) THEN RAISE EXCEPTION 'Access plane is undeclared'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_field_access f WHERE f.change_set_id=draft AND f.representation<>'omitted' AND (f.read_operation_id IS NULL OR f.read_operation_change_set_id IS DISTINCT FROM draft)) THEN RAISE EXCEPTION 'Field access operation source invalid'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_field_access f JOIN metadata.entity_operation o ON o.id=f.read_operation_id WHERE f.change_set_id=draft AND o.operation_kind::text NOT IN ('read','list')) THEN RAISE EXCEPTION 'Field read operation is incompatible'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_operation_field f JOIN metadata.entity_operation o ON o.id=f.entity_operation_id WHERE f.change_set_id=draft AND o.operation_kind::text IN ('read','list')) THEN RAISE EXCEPTION 'Read operations cannot enroll write fields'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_predicate p WHERE p.change_set_id=draft AND ((p.parent_predicate_id IS NULL AND ((p.purpose='list_filter' AND p.view_id IS NULL) OR (p.purpose='record_lock' AND p.authorization_profile_id IS NULL) OR (p.purpose='editability' AND p.field_binding_id IS NULL) OR (p.purpose='visibility' AND num_nonnulls(p.field_binding_id,p.surface_operation_id,p.surface_section_id,p.navigation_group_id)<>1))) OR (p.node_kind='group' AND (p.conjunction IS NULL OR num_nonnulls(p.entity_field_id,p.operator,p.value_kind,p.value_text,p.value_numeric,p.value_boolean,p.value_date,p.value_datetime,p.value_uuid,p.value_text_set,p.value_numeric_set,p.value_uuid_set,p.value_date_set,p.value_datetime_set,p.context_key,p.context_version)<>0)) OR (p.node_kind='condition' AND (p.conjunction IS NOT NULL OR p.entity_field_id IS NULL OR p.operator IS NULL OR p.value_kind IS NULL)))) THEN RAISE EXCEPTION 'Predicate owner/node shape invalid'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_predicate p WHERE p.change_set_id=draft AND p.node_kind='condition' AND (
  (p.operator IN ('is_null','is_not_null')) IS DISTINCT FROM (p.value_kind='none') OR
  CASE p.value_kind
   WHEN 'none' THEN num_nonnulls(p.value_text,p.value_numeric,p.value_boolean,p.value_date,p.value_datetime,p.value_uuid,p.value_text_set,p.value_numeric_set,p.value_uuid_set,p.value_date_set,p.value_datetime_set,p.context_key,p.context_version)<>0
   WHEN 'context' THEN num_nonnulls(p.value_text,p.value_numeric,p.value_boolean,p.value_date,p.value_datetime,p.value_uuid,p.value_text_set,p.value_numeric_set,p.value_uuid_set,p.value_date_set,p.value_datetime_set)<>0 OR p.context_key IS NULL OR p.context_version IS NULL
   ELSE num_nonnulls(p.value_text,p.value_numeric,p.value_boolean,p.value_date,p.value_datetime,p.value_uuid,p.value_text_set,p.value_numeric_set,p.value_uuid_set,p.value_date_set,p.value_datetime_set)<>1 OR p.context_key IS NOT NULL OR p.context_version IS NOT NULL OR
    CASE p.value_kind WHEN 'text' THEN p.value_text IS NULL WHEN 'numeric' THEN p.value_numeric IS NULL WHEN 'boolean' THEN p.value_boolean IS NULL WHEN 'date' THEN p.value_date IS NULL WHEN 'datetime' THEN p.value_datetime IS NULL WHEN 'uuid' THEN p.value_uuid IS NULL
     WHEN 'text_set' THEN coalesce(cardinality(p.value_text_set),0)=0 WHEN 'numeric_set' THEN coalesce(cardinality(p.value_numeric_set),0)=0 WHEN 'uuid_set' THEN coalesce(cardinality(p.value_uuid_set),0)=0 WHEN 'date_set' THEN coalesce(cardinality(p.value_date_set),0)=0 WHEN 'datetime_set' THEN coalesce(cardinality(p.value_datetime_set),0)=0 ELSE true END OR
    (p.value_kind LIKE '%\_set' ESCAPE '\') IS DISTINCT FROM (p.operator IN ('in','not_in')) END
 )) THEN RAISE EXCEPTION 'Predicate payload/operator mismatch'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_predicate p JOIN metadata.entity_field f ON f.id=p.entity_field_id AND f.change_set_id=draft WHERE p.change_set_id=draft AND p.node_kind='condition' AND p.operator NOT IN ('is_null','is_not_null') AND p.value_kind<>'context' AND (
   regexp_replace(p.value_kind,'_set$','') IS DISTINCT FROM CASE f.data_type::text WHEN 'text' THEN 'text' WHEN 'enum' THEN 'text' WHEN 'integer' THEN 'numeric' WHEN 'decimal' THEN 'numeric' WHEN 'money' THEN 'numeric' WHEN 'boolean' THEN 'boolean' WHEN 'date' THEN 'date' WHEN 'datetime' THEN 'datetime' WHEN 'uuid' THEN 'uuid' END
   OR (p.operator IN ('gt','gte','lt','lte') AND f.data_type::text NOT IN ('integer','decimal','money','date','datetime'))
 )) THEN RAISE EXCEPTION 'Predicate field/value type invalid'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_authorization_profile p JOIN metadata.entity_operation r ON r.id=p.record_read_operation_id JOIN metadata.entity_operation d ON d.id=p.directory_operation_id WHERE p.change_set_id=draft AND (r.operation_kind::text<>'read' OR d.operation_kind::text<>'read')) THEN RAISE EXCEPTION 'Authorization profile read operation invalid'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_predicate p WHERE p.change_set_id=draft AND (
   p.value_numeric::text IN ('NaN','Infinity','-Infinity') OR EXISTS(SELECT 1 FROM unnest(p.value_numeric_set) n WHERE n::text IN ('NaN','Infinity','-Infinity')) OR
   EXISTS(SELECT 1 FROM unnest(p.value_text_set) t WHERE length(t) NOT BETWEEN 1 AND 4000 OR t !~ '[^[:space:]]')
 )) THEN RAISE EXCEPTION 'Predicate scalar/set payload invalid'; END IF;
 IF EXISTS(SELECT 1 FROM metadata.entity_predicate p JOIN metadata.entity_predicate parent ON parent.id=p.parent_predicate_id WHERE p.change_set_id=draft AND (p.purpose<>parent.purpose OR parent.node_kind<>'group')) THEN RAISE EXCEPTION 'Predicate purpose/parent mismatch'; END IF;
 IF EXISTS(WITH RECURSIVE tree AS (SELECT id,parent_predicate_id,ARRAY[id] path,false cycle,1 depth FROM metadata.entity_predicate WHERE change_set_id=draft UNION ALL SELECT p.id,p.parent_predicate_id,t.path||p.id,p.id=ANY(t.path),t.depth+1 FROM tree t JOIN metadata.entity_predicate p ON p.id=t.parent_predicate_id WHERE NOT t.cycle AND t.depth<=32) SELECT 1 FROM tree WHERE cycle OR depth>32) THEN RAISE EXCEPTION 'Predicate cycle/depth limit'; END IF;
END $$;
COMMIT;
