BEGIN;
DO $$ BEGIN IF current_database()<>'athyper_studio' THEN RAISE EXCEPTION 'WP12 definition authority must run only in athyper_studio';END IF;END $$;
CREATE TABLE snapshot.business_partner_definition_revision(
 id uuid PRIMARY KEY DEFAULT shared.uuidv7(),tenant_id uuid NOT NULL,bundle_code text NOT NULL,semantic_version text NOT NULL,bundle_schema_version text NOT NULL DEFAULT '1.0.0',bundle_json jsonb NOT NULL,bundle_hash text NOT NULL,target_planes text[] NOT NULL,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),created_by uuid NOT NULL,
 CONSTRAINT business_partner_definition_revision_tenant_id_uq UNIQUE(tenant_id,id),CONSTRAINT business_partner_definition_revision_version_uq UNIQUE(tenant_id,bundle_code,semantic_version),CONSTRAINT business_partner_definition_revision_idempotency_uq UNIQUE(tenant_id,idempotency_key),
 CONSTRAINT business_partner_definition_revision_tenant_fk FOREIGN KEY(tenant_id) REFERENCES master.tenant(id) ON DELETE RESTRICT,
 CONSTRAINT business_partner_definition_revision_chk CHECK(bundle_code ~ '^[a-z][a-z0-9_.-]{1,126}$' AND semantic_version ~ '^[0-9]+\.[0-9]+\.[0-9]+([+-][A-Za-z0-9.-]+)?$' AND bundle_schema_version ~ '^[0-9]+\.[0-9]+\.[0-9]+$' AND bundle_hash ~ '^[a-f0-9]{64}$' AND jsonb_typeof(bundle_json)='object' AND bundle_json->>'schema'='athyper.business-partner-definition-bundle.v1' AND bundle_json->>'bundleCode'=bundle_code AND bundle_json->>'semanticVersion'=semantic_version AND bundle_json?&ARRAY['requestSchemas','validationDeclarations','formDescriptors','viewDescriptors','mappingContracts','workflowDefinitions','compatibilityRules','sourceContractHashes'] AND cardinality(target_planes)>0 AND target_planes<@ARRAY['studio','neon','mesh']::text[] AND btrim(idempotency_key)<>'')
);
CREATE INDEX business_partner_definition_revision_created_idx ON snapshot.business_partner_definition_revision(tenant_id,bundle_code,created_at DESC);
CREATE TABLE publication.business_partner_definition_release_link(
 publication_release_id uuid PRIMARY KEY,definition_revision_id uuid NOT NULL UNIQUE,publish_idempotency_key text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),created_by uuid NOT NULL,
 CONSTRAINT publication_bp_definition_release_link_release_fk FOREIGN KEY(publication_release_id) REFERENCES publication.release(id) ON DELETE RESTRICT,
 CONSTRAINT publication_bp_definition_release_link_revision_fk FOREIGN KEY(definition_revision_id) REFERENCES snapshot.business_partner_definition_revision(id) ON DELETE RESTRICT,
 CONSTRAINT publication_bp_definition_release_link_key_chk CHECK(btrim(publish_idempotency_key)<>'')
);
CREATE FUNCTION snapshot.trg_guard_business_partner_definition_revision() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$ BEGIN RAISE EXCEPTION 'business_partner_definition_revision is immutable' USING ERRCODE='integrity_constraint_violation';END $$;
CREATE TRIGGER business_partner_definition_revision_immutable BEFORE UPDATE OR DELETE ON snapshot.business_partner_definition_revision FOR EACH ROW EXECUTE FUNCTION snapshot.trg_guard_business_partner_definition_revision();
CREATE FUNCTION publication.trg_validate_business_partner_definition_release_link() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,publication,snapshot AS $$ DECLARE p publication.release%ROWTYPE;r snapshot.business_partner_definition_revision%ROWTYPE;BEGIN SELECT * INTO STRICT p FROM publication.release WHERE id=NEW.publication_release_id;SELECT * INTO STRICT r FROM snapshot.business_partner_definition_revision WHERE id=NEW.definition_revision_id;IF p.tenant_id IS DISTINCT FROM r.tenant_id OR p.release_hash IS DISTINCT FROM r.bundle_hash OR p.release_key IS DISTINCT FROM('studio.business_partner.definition.'||r.bundle_code) THEN RAISE EXCEPTION 'BUSINESS_PARTNER_DEFINITION_PUBLICATION_COORDINATE_MISMATCH' USING ERRCODE='foreign_key_violation';END IF;RETURN NEW;END $$;
CREATE TRIGGER publication_bp_definition_release_link_immutable BEFORE UPDATE OR DELETE ON publication.business_partner_definition_release_link FOR EACH ROW EXECUTE FUNCTION publication.trg_guard_ledger_mutation();
CREATE TRIGGER publication_bp_definition_release_link_validate BEFORE INSERT ON publication.business_partner_definition_release_link FOR EACH ROW EXECUTE FUNCTION publication.trg_validate_business_partner_definition_release_link();
ALTER TABLE snapshot.business_partner_definition_revision ENABLE ROW LEVEL SECURITY;ALTER TABLE snapshot.business_partner_definition_revision FORCE ROW LEVEL SECURITY;
CREATE POLICY business_partner_definition_revision_tenant_read ON snapshot.business_partner_definition_revision FOR SELECT USING(tenant_id=shared.current_tenant_id_soft());CREATE POLICY business_partner_definition_revision_service_write ON snapshot.business_partner_definition_revision FOR INSERT WITH CHECK(tenant_id=shared.current_tenant_id());CREATE POLICY business_partner_definition_revision_seed_owner ON snapshot.business_partner_definition_revision FOR ALL TO CURRENT_USER USING(true) WITH CHECK(true);
REVOKE ALL ON snapshot.business_partner_definition_revision,publication.business_partner_definition_release_link FROM PUBLIC;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='athyper_publication_service') THEN GRANT SELECT,INSERT ON snapshot.business_partner_definition_revision,publication.business_partner_definition_release_link TO athyper_publication_service;END IF;END $$;
COMMIT;
