CREATE TABLE snapshot.entity_contract_test_run (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    source_tenant_id uuid,
    entity_id uuid NOT NULL,
    change_set_id uuid NOT NULL,
    revision_id uuid,
    source_lock_version bigint NOT NULL,
    contract_schema_code text NOT NULL,
    contract_schema_version text NOT NULL,
    source_contract_json jsonb NOT NULL,
    source_contract_hash text NOT NULL,
    runner_code text NOT NULL,
    runner_version text NOT NULL,
    status snapshot.entity_contract_test_run_status_d NOT NULL,
    total_count integer NOT NULL,
    passed_count integer NOT NULL,
    failed_count integer NOT NULL,
    error_count integer NOT NULL,
    duration_ms integer NOT NULL,
    run_hash text NOT NULL,
    audit_event_id uuid,
    correlation_id uuid,
    executed_at timestamptz NOT NULL DEFAULT now(),
    executed_by uuid NOT NULL,
    CONSTRAINT entity_contract_test_run_pkey PRIMARY KEY (id),
    CONSTRAINT entity_contract_test_run_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT entity_contract_test_run_schema_code_chk CHECK (contract_schema_code ~ '^[a-z][a-z0-9_.-]{1,126}$'),
    CONSTRAINT entity_contract_test_run_schema_version_chk CHECK (contract_schema_version ~ '^[0-9]+\.[0-9]+(?:\.[0-9]+)?$'),
    CONSTRAINT entity_contract_test_run_source_chk CHECK (jsonb_typeof(source_contract_json) = 'object'),
    CONSTRAINT entity_contract_test_run_source_hash_chk CHECK (source_contract_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT entity_contract_test_run_runner_code_chk CHECK (runner_code ~ '^[a-z][a-z0-9_.-]{1,126}$'),
    CONSTRAINT entity_contract_test_run_runner_version_chk CHECK (runner_version ~ '^[0-9]+\.[0-9]+(?:\.[0-9]+)?$'),
    CONSTRAINT entity_contract_test_run_counts_chk CHECK (
        total_count >= 0 AND passed_count >= 0 AND failed_count >= 0 AND error_count >= 0
        AND total_count = passed_count + failed_count + error_count
    ),
    CONSTRAINT entity_contract_test_run_duration_chk CHECK (duration_ms >= 0),
    CONSTRAINT entity_contract_test_run_hash_chk CHECK (run_hash ~ '^[a-f0-9]{64}$')
);

CREATE TABLE snapshot.entity_contract_test_result (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    test_run_id uuid NOT NULL,
    ordinal integer NOT NULL,
    test_case_id uuid NOT NULL,
    test_key text NOT NULL,
    test_kind metadata.entity_contract_test_kind_d NOT NULL,
    target_plane text,
    definition_json jsonb NOT NULL,
    definition_hash text NOT NULL,
    expected_outcome metadata.entity_contract_test_outcome_d NOT NULL,
    actual_outcome snapshot.entity_contract_test_actual_outcome_d NOT NULL,
    assertion_passed boolean NOT NULL,
    diagnostic_codes text[] NOT NULL DEFAULT ARRAY[]::text[],
    diagnostics jsonb NOT NULL DEFAULT '[]'::jsonb,
    actual_output jsonb NOT NULL DEFAULT '{}'::jsonb,
    duration_ms integer NOT NULL,
    result_hash text NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT entity_contract_test_result_pkey PRIMARY KEY (id),
    CONSTRAINT entity_contract_test_result_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT entity_contract_test_result_coordinate_uq UNIQUE (tenant_id, test_run_id, ordinal),
    CONSTRAINT entity_contract_test_result_case_uq UNIQUE (tenant_id, test_run_id, test_case_id),
    CONSTRAINT entity_contract_test_result_ordinal_chk CHECK (ordinal >= 0),
    CONSTRAINT entity_contract_test_result_key_chk CHECK (test_key ~ '^[a-z][a-z0-9_.-]{1,126}$'),
    CONSTRAINT entity_contract_test_result_plane_chk CHECK (target_plane IS NULL OR target_plane IN ('athyper', 'neon', 'mesh')),
    CONSTRAINT entity_contract_test_result_definition_chk CHECK (jsonb_typeof(definition_json) = 'object'),
    CONSTRAINT entity_contract_test_result_definition_hash_chk CHECK (definition_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT entity_contract_test_result_diagnostics_chk CHECK (jsonb_typeof(diagnostics) = 'array' AND array_position(diagnostic_codes, NULL) IS NULL),
    CONSTRAINT entity_contract_test_result_output_chk CHECK (jsonb_typeof(actual_output) = 'object'),
    CONSTRAINT entity_contract_test_result_duration_chk CHECK (duration_ms >= 0),
    CONSTRAINT entity_contract_test_result_hash_chk CHECK (result_hash ~ '^[a-f0-9]{64}$')
);

COMMENT ON TABLE snapshot.entity_contract_test_run IS 'Immutable execution envelope containing the exact canonical Entity contract evaluated by the contract-test runner.';
COMMENT ON TABLE snapshot.entity_contract_test_result IS 'Immutable per-case assertion evidence; it preserves the test definition and output independently of mutable metadata fixtures.';
