-- Table-owned seed for control.entity_flow_step.
-- Rows are emitted by compound entity-flow blocks in 046_entity_flow.sql so
-- flow_id resolution stays local to each flow definition.
-- Lookup domain/value seeds remain under 000_lookups by design.
