-- ============================================================================
-- Parameter definitions — Finance, Collaboration, Notifications, API, Governance, UX
-- Tier 1: tenant_configurable / configurable — tenants can view and override these.
-- ============================================================================

INSERT INTO control.parameter_definition (
    code,
    namespace,
    display_name,
    description,
    owner_model,
    control_level,
    tenant_visibility,
    data_type,
    unit,
    default_value,
    product_value,
    min_value,
    max_value,
    allowed_values,
    runtime_reload,
    cache_ttl_seconds,
    is_security_sensitive,
    is_runtime_reloadable,
    sort_order,
    metadata,
    created_by
)
SELECT
    v.code,
    v.namespace,
    v.display_name,
    v.description,
    'product',
    v.control_level,
    v.tenant_visibility,
    v.data_type,
    v.unit,
    v.default_value::jsonb,
    NULLIF(v.product_value, '')::jsonb,
    NULLIF(v.min_value, '')::jsonb,
    NULLIF(v.max_value, '')::jsonb,
    NULLIF(v.allowed_values, '')::jsonb,
    v.runtime_reload,
    v.cache_ttl_seconds,
    v.is_security_sensitive,
    v.is_runtime_reloadable,
    v.sort_order,
    v.metadata::jsonb,
    '00000000-0000-0000-0000-000000000000'::uuid
FROM (VALUES
    -- ── Finance: AP ───────────────────────────────────────────────────────────
    ('finance.ap.payment_terms_days',    'finance.ap',
     'Default AP payment terms (days)',
     'Default net-payment days applied to AP invoices when no supplier-specific terms are set.',
     'tenant_configurable', 'configurable', 'integer', 'days',
     '30', '30', '0', '365', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/workspace/finance/ap/ap.service.ts","fallback_constant":"DEFAULT_PAYMENT_TERMS_DAYS"}'),

    ('finance.ap.tolerance_amount',      'finance.ap',
     'AP matching absolute tolerance',
     'Maximum absolute currency difference allowed when matching a purchase invoice line to a GR.',
     'tenant_configurable', 'configurable', 'number', 'currency_units',
     '5', '5', '0', '10000', NULL,
     'next_request', 300, false, true, 20,
     '{"source":"server/workspace/finance/ap/matching.service.ts"}'),

    ('finance.ap.default_procurement_line_type', 'finance.ap',
     'Default procurement line type',
     'Default Procurement Type applied when a user adds a new procurement line to a purchase invoice.',
     'tenant_configurable', 'configurable', 'enum', NULL,
     '"goods"', '"goods"', NULL, NULL,
     '["goods","services","mixed","freight","misc"]',
     'immediate', 300, false, true, 40,
     '{"source":"packages/shared/runtime/document-runtime/src/items/ProcureLineComposerSheet.tsx","lookup_domain":"document.procurement_type","fallback_constant":"goods"}'),

    ('finance.ap.default_procurement_line_uom', 'finance.ap',
     'Default procurement line UoM',
     'Default unit of measure applied when a user adds a standalone procurement line without a source document or item.',
     'tenant_configurable', 'configurable', 'string', NULL,
     '"EA"', '"EA"', NULL, NULL, NULL,
     'immediate', 300, false, true, 45,
     '{"source":"packages/shared/runtime/document-runtime/src/items/ProcureLineComposerSheet.tsx","fallback_constant":"EA","meaning":"Each"}'),

    ('finance.ap.tolerance_percent',     'finance.ap',
     'AP matching percentage tolerance',
     'Maximum percentage difference allowed when matching invoice value to GR/PO value.',
     'tenant_configurable', 'configurable', 'number', 'percent',
     '2', '2', '0', '20', NULL,
     'next_request', 300, false, true, 30,
     '{"source":"server/workspace/finance/ap/matching.service.ts"}'),

    -- ── Finance: AR ───────────────────────────────────────────────────────────
    ('finance.ar.credit_days',           'finance.ar',
     'Standard AR credit days',
     'Default credit period (days) given to customers on AR invoices.',
     'tenant_configurable', 'configurable', 'integer', 'days',
     '30', '30', '0', '365', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/workspace/finance/ar/ar.service.ts"}'),

    ('finance.ar.late_payment_grace_days', 'finance.ar',
     'Late payment grace period (days)',
     'Days after invoice due date before a receivable is classified as overdue in aging reports.',
     'tenant_configurable', 'configurable', 'integer', 'days',
     '0', '0', '0', '30', NULL,
     'next_request', 300, false, true, 20,
     '{"source":"packages/domain/finance/finance-workbench/src/reports/ArAging"}'),

    -- ── Finance: GL ───────────────────────────────────────────────────────────
    ('finance.gl.period_close_lock_days', 'finance.gl',
     'Period close lock buffer (days)',
     'How many days after a period ends before it is automatically locked to new postings.',
     'tenant_configurable', 'configurable', 'integer', 'days',
     '5', '5', '0', '30', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/db/sql/master/06_triggers.sql"}'),

    -- ── Finance: Reporting ────────────────────────────────────────────────────
    ('finance.reporting.default_report', 'finance.reporting',
     'Default financial report view',
     'Which report tab opens by default when a user lands on the Finance > Reports page.',
     'tenant_configurable', 'configurable', 'enum', NULL,
     '"profit-loss"', '"profit-loss"', NULL, NULL,
     '["profit-loss","balance-sheet","trial-balance","cash-flow","ap-aging","ar-aging"]',
     'next_request', 300, false, true, 10,
     '{"source":"packages/domain/finance/finance-workbench/src/lib/reportRegistry.ts:107","fallback_constant":"DEFAULT_REPORT"}'),

    -- Workbench: Supply Chain
    ('workbench.supply_chain.commodity_category_tree_batch_size', 'workbench.supply_chain',
     'Commodity category tree batch size',
     'Maximum number of commodity-category hierarchy rows loaded per tree request in the supply-chain workbench Explorer.',
     'tenant_configurable', 'configurable', 'integer', 'rows',
     '500', '500', '50', '1000', NULL,
     'immediate', 300, false, true, 10,
     '{"source":"packages/domain/finance/finance-workbench/src/hooks/useTaxonomyWorkbenches.ts","scope":"hierarchy_tree_only","fallback_constant":"DEFAULT_COMMODITY_CATEGORY_TREE_BATCH_SIZE","legacy_code":"workbench.supply_chain.spend_category_tree_batch_size"}'),

    -- ── Finance: Numbering ────────────────────────────────────────────────────
    ('finance.numbering.je_prefix',      'finance.numbering',
     'Journal entry number prefix',
     'Prefix prepended to auto-generated journal entry document numbers.',
     'tenant_configurable', 'configurable', 'string', NULL,
     '"JE"', '"JE"', NULL, NULL, NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/db/seed/entity_numbering_config seed"}'),

    ('finance.numbering.ap_invoice_prefix', 'finance.numbering',
     'AP invoice number prefix',
     'Prefix prepended to auto-generated AP invoice document numbers.',
     'tenant_configurable', 'configurable', 'string', NULL,
     '"API"', '"API"', NULL, NULL, NULL,
     'next_request', 300, false, true, 20,
     '{"source":"server/db/seed/entity_numbering_config seed"}'),

    ('finance.numbering.ar_invoice_prefix', 'finance.numbering',
     'AR invoice number prefix',
     'Prefix prepended to auto-generated AR invoice document numbers.',
     'tenant_configurable', 'configurable', 'string', NULL,
     '"ARI"', '"ARI"', NULL, NULL, NULL,
     'next_request', 300, false, true, 30,
     '{"source":"server/db/seed/entity_numbering_config seed"}'),

    -- ── Collaboration: Attachments ────────────────────────────────────────────
    ('collab.attachments.max_file_bytes', 'collab.attachments',
     'Maximum attachment file size',
     'Largest single file that can be uploaded to a comment or document attachment.',
     'tenant_configurable', 'configurable', 'integer', 'bytes',
     '104857600', '104857600', '1048576', '524288000', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"apps/web/app/api/collab/attachments/route.ts:17","fallback_constant":"MAX_BYTES"}'),

    ('collab.attachments.max_files_per_batch', 'collab.attachments',
     'Maximum files per upload batch',
     'Number of files that can be attached in a single upload action.',
     'tenant_configurable', 'configurable', 'integer', 'files',
     '10', '10', '1', '50', NULL,
     'next_request', 300, false, true, 20,
     '{"source":"packages/shared/runtime/collaboration-ui/src/hooks/attachments.ts:46","fallback_constant":"MAX_FILES"}'),

    -- ── Notifications ─────────────────────────────────────────────────────────
    ('notifications.dedup_window_ms',    'notifications',
     'Notification deduplication window',
     'Time window within which identical notifications are suppressed to prevent alert storms.',
     'tenant_configurable', 'configurable', 'integer', 'milliseconds',
     '300000', '300000', '0', '3600000', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/framework/runtime/services/jobs/workers/notification.worker.ts:105","fallback_constant":"DEFAULT_DEDUP_WINDOW_MS"}'),

    ('notifications.webhook.rate_limit_rpm', 'notifications.webhook',
     'Inbound webhook rate limit (RPM)',
     'Maximum inbound webhook events accepted per minute per integration endpoint.',
     'tenant_configurable', 'configurable', 'integer', 'requests_per_minute',
     '120', '120', '10', '1200', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/framework/runtime/services/integration/routes/webhook-receiver.route.ts:54","fallback_constant":"RATE_LIMIT_RPM"}'),

    -- ── API Defaults ──────────────────────────────────────────────────────────
    ('api.pagination.default_page_size', 'api.pagination',
     'Default list page size',
     'Number of records returned per page on entity list views when no page_size is specified.',
     'tenant_configurable', 'configurable', 'integer', 'rows',
     '20', '20', '10', '200', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/framework/runtime/services/records/routes/records.route.ts:363"}'),

    ('api.pagination.max_page_size',     'api.pagination',
     'Maximum list page size',
     'Hard upper bound on page_size query parameter across all entity list views. Values above 500 must use page navigation.',
     'system_controlled', 'readonly', 'integer', 'rows',
     '500', '500', '20', '500', NULL,
     'next_request', 300, false, true, 20,
     '{"source":"server/framework/runtime/services/records/routes/records.route.ts:363"}'),

    ('api.pagination.load_more_increment', 'api.pagination',
     'Load more increment',
     'Number of additional records requested when the entity list Load More control is used.',
     'tenant_configurable', 'configurable', 'integer', 'rows',
     '50', '50', '1', '500', NULL,
     'next_request', 300, false, true, 25,
     '{"source":"packages/shared/runtime/entity-runtime/src/list/EntityListPage.tsx","fallback_constant":"DEFAULT_LOAD_MORE_SIZE"}'),

    ('api.pagination.picker_tree_min_page_size', 'api.pagination',
     'Picker tree minimum page size',
     'Minimum page-size ceiling allowed when an advanced entity picker requests tree mode.',
     'system_controlled', 'readonly', 'integer', 'rows',
     '500', '500', '500', '1000', NULL,
     'next_request', 300, false, true, 30,
     '{"source":"packages/shared/runtime/runtime-shared/src/entity-search/EntityPicker.tsx","query_param":"picker_tree"}'),

    ('api.export.records_max_rows',      'api.export',
     'Maximum export rows (records)',
     'Row limit enforced on CSV/XLSX entity record exports.',
     'tenant_configurable', 'configurable', 'integer', 'rows',
     '10000', '10000', '1000', '500000', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/framework/runtime/services/records/routes/export.route.ts:52","fallback_constant":"EXPORT_MAX_ROWS"}'),

    ('api.export.audit_max_rows',        'api.export',
     'Maximum export rows (audit log)',
     'Row limit enforced on audit event exports. Compliance tenants may require higher limits.',
     'tenant_configurable', 'configurable', 'integer', 'rows',
     '50000', '50000', '1000', '1000000', NULL,
     'next_request', 300, false, true, 20,
     '{"source":"server/framework/runtime/services/audit/routes/audit.route.ts:121","fallback_constant":"EXPORT_MAX_ROWS"}'),

    ('api.audit.default_window_days',    'api.audit',
     'Default audit query window (days)',
     'Default date range applied to audit event queries when no from/to is specified.',
     'tenant_configurable', 'configurable', 'integer', 'days',
     '7', '7', '1', '90', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/framework/runtime/services/audit/routes/audit.route.ts:48","fallback_constant":"DEFAULT_WINDOW_DAYS"}'),

    ('api.audit.max_window_days',        'api.audit',
     'Maximum audit query window (days)',
     'Hard upper bound on audit query date ranges. Increase for compliance/legal hold tenants.',
     'tenant_configurable', 'configurable', 'integer', 'days',
     '90', '90', '30', '2557', NULL,
     'next_request', 300, false, true, 20,
     '{"source":"server/framework/runtime/services/audit/routes/audit.route.ts:49","fallback_constant":"MAX_WINDOW_DAYS"}'),

    -- ── Governance ────────────────────────────────────────────────────────────
    ('governance.cert.expiring_soon_days', 'governance.cert',
     'Certificate expiry warning threshold (days)',
     'Number of days before certification expiry that the "expiring soon" badge appears.',
     'tenant_configurable', 'configurable', 'integer', 'days',
     '90', '90', '7', '365', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"packages/shared/runtime/entity-runtime/src/detail/ChildSummaryCardsPanel.tsx:388","fallback_constant":"CERT_EXPIRING_SOON_DAYS"}'),

    -- ── Jobs: SLA & Edit Locks ────────────────────────────────────────────────
    ('jobs.sla.stuck_threshold_hours',   'jobs.sla',
     'Workflow stuck-item threshold (hours)',
     'A workflow item is flagged as stuck if it has not progressed within this many hours.',
     'tenant_configurable', 'configurable', 'integer', 'hours',
     '24', '24', '1', '168', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/framework/runtime/services/jobs/workers/sla-check.worker.ts:431","fallback_constant":"STUCK_THRESHOLD_HOURS"}'),

    ('jobs.editlock.default_ttl_seconds', 'jobs.editlock',
     'Collaborative edit-lock TTL (seconds)',
     'How long an edit lock held by a user persists before expiring if no heartbeat is received.',
     'tenant_configurable', 'configurable', 'integer', 'seconds',
     '300', '300', '60', '1800', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"server/framework/runtime/services/shared/edit-lock.service.ts:25","fallback_constant":"DEFAULT_LOCK_TTL_SECONDS"}'),

    -- ── UX ────────────────────────────────────────────────────────────────────
    ('ux.recents.max_nav_items',         'ux.recents',
     'Recent navigation items limit',
     'Maximum number of recently visited pages kept in the sidebar navigation history.',
     'tenant_configurable', 'configurable', 'integer', 'items',
     '20', '20', '5', '100', NULL,
     'next_request', 300, false, true, 10,
     '{"source":"apps/web/lib/recent-items.ts:40","fallback_constant":"MAX_ITEMS"}'),

    ('ux.recents.max_record_items',      'ux.recents',
     'Recently viewed records limit',
     'Maximum number of recently opened entity records shown in the entity list "Recent" panel.',
     'tenant_configurable', 'configurable', 'integer', 'items',
     '12', '12', '5', '50', NULL,
     'next_request', 300, false, true, 20,
     '{"source":"apps/web/lib/recently-viewed.ts:19","fallback_constant":"MAX"}')

) AS v(
    code,
    namespace,
    display_name,
    description,
    control_level,
    tenant_visibility,
    data_type,
    unit,
    default_value,
    product_value,
    min_value,
    max_value,
    allowed_values,
    runtime_reload,
    cache_ttl_seconds,
    is_security_sensitive,
    is_runtime_reloadable,
    sort_order,
    metadata
)
ON CONFLICT (code) DO UPDATE SET
    namespace             = EXCLUDED.namespace,
    display_name          = EXCLUDED.display_name,
    description           = EXCLUDED.description,
    control_level         = EXCLUDED.control_level,
    tenant_visibility     = EXCLUDED.tenant_visibility,
    data_type             = EXCLUDED.data_type,
    unit                  = EXCLUDED.unit,
    default_value         = EXCLUDED.default_value,
    product_value         = EXCLUDED.product_value,
    min_value             = EXCLUDED.min_value,
    max_value             = EXCLUDED.max_value,
    allowed_values        = EXCLUDED.allowed_values,
    runtime_reload        = EXCLUDED.runtime_reload,
    cache_ttl_seconds     = EXCLUDED.cache_ttl_seconds,
    is_security_sensitive = EXCLUDED.is_security_sensitive,
    is_runtime_reloadable = EXCLUDED.is_runtime_reloadable,
    sort_order            = EXCLUDED.sort_order,
    metadata              = EXCLUDED.metadata,
    status                = 'active',
    updated_at            = now(),
    updated_by            = EXCLUDED.created_by;
