"use client";

import * as React from "react";
import { useState, type HTMLAttributes, type ReactNode } from "react";
import { PanelsTopLeftIcon, UserIcon } from "@athyper/platform-icons";
import { Button, Card, Dialog, DialogClose, DialogContent, Drawer as FrameworkDrawer, Skeleton } from "@athyper/platform-ui";
export * from "./stack-rules";

export function PageSurface({ title, description, actions, children, className, contentOnly = false, ...props }: HTMLAttributes<HTMLElement> & { readonly title: string; readonly description?: string; readonly actions?: ReactNode; readonly contentOnly?: boolean }) { return contentOnly ? <section className={className} {...props}>{children}</section> : <main className={["a-page-surface", className].filter(Boolean).join(" ")} {...props}><header className="a-page-surface__header"><div><h1>{title}</h1>{description ? <p>{description}</p> : null}</div>{actions ? <div className="a-page-surface__actions">{actions}</div> : null}</header>{children}</main>; }

function LegacyDrawerAdapter({ kind, open, title, onClose, children }: { readonly kind: "form" | "context"; readonly open: boolean; readonly title: string; readonly onClose: () => void; readonly children: ReactNode }) { return <FrameworkDrawer.Root open={open} onOpenChange={(next) => { if (!next) onClose(); }}><FrameworkDrawer.Panel size={kind === "form" ? "standard" : "compact"} variant={kind === "form" ? "task" : "navigation"} mobilePresentation="fullscreen"><FrameworkDrawer.Header title={title} closeLabel={`Close ${title}`}/><FrameworkDrawer.Body>{children}</FrameworkDrawer.Body></FrameworkDrawer.Panel></FrameworkDrawer.Root>; }
export function FormDrawer(props: Omit<Parameters<typeof LegacyDrawerAdapter>[0], "kind">) { return <LegacyDrawerAdapter kind="form" {...props} />; }
export function ContextDrawer(props: Omit<Parameters<typeof LegacyDrawerAdapter>[0], "kind">) { return <LegacyDrawerAdapter kind="context" {...props} />; }

export function ConfirmDialog({ open, title, description, confirmLabel = "Confirm", cancelLabel = "Cancel", destructive = false, onConfirm, onOpenChange }: { readonly open: boolean; readonly title: string; readonly description: string; readonly confirmLabel?: string; readonly cancelLabel?: string; readonly destructive?: boolean; readonly onConfirm: () => void; readonly onOpenChange: (open: boolean) => void }) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title={title} description={description}><div className="a-confirm-actions"><DialogClose className="a-button a-button--secondary">{cancelLabel}</DialogClose><Button variant={destructive ? "danger" : "primary"} onClick={onConfirm}>{confirmLabel}</Button></div></DialogContent></Dialog>; }

export function Popover({ trigger, children, label, open, defaultOpen = false, onOpenChange }: { readonly trigger: ReactNode; readonly children: ReactNode; readonly label: string; readonly open?: boolean; readonly defaultOpen?: boolean; readonly onOpenChange?: (open: boolean) => void }) { const [local, setLocal] = useState(defaultOpen); const shown = open ?? local; const set = (next: boolean) => { if (open === undefined) setLocal(next); onOpenChange?.(next); }; return <span className="a-popover"><button type="button" className="a-popover__trigger" aria-haspopup="dialog" aria-expanded={shown} onClick={() => set(!shown)}>{trigger}</button>{shown ? <span role="dialog" aria-label={label} className="a-popover__content">{children}</span> : null}</span>; }

export function Overlay({ open, label, onClose, children }: { readonly open: boolean; readonly label: string; readonly onClose: () => void; readonly children: ReactNode }) { if (!open) return null; return <div className="a-overlay" role="dialog" aria-modal="true" aria-label={label}><button type="button" className="a-overlay__close" onClick={onClose}>Close</button>{children}</div>; }

export function LoginSkeleton({ applicationName }: { readonly applicationName: string }) { return <main className="a-centered-page" aria-label={`${applicationName} sign in loading`}><Card className="a-login-card"><Skeleton className="a-login-skeleton__brand" label="Loading brand" /><Skeleton className="a-login-skeleton__field" label="Loading identity field" /><Skeleton className="a-login-skeleton__field" label="Loading sign in action" /></Card></main>; }
export function ErrorPage({ title = "Something went wrong", description, onRetry }: { readonly title?: string; readonly description: string; readonly onRetry?: () => void }) { return <PageSurface title={title} description={description}>{onRetry ? <Button onClick={onRetry}>Try again</Button> : null}</PageSurface>; }
export function EmptyShellFrame({ applicationName, children }: { readonly applicationName: string; readonly children?: ReactNode }) { return <div className="a-shell-frame"><a className="a-skip-link" href="#main-content">Skip to content</a><header className="a-shell-frame__topbar"><strong>{applicationName}</strong><Button variant="ghost" size="icon" aria-label="Open account menu"><UserIcon/></Button></header><aside className="a-shell-frame__rail" aria-label="Primary navigation"><span aria-hidden="true"><PanelsTopLeftIcon/></span></aside><main id="main-content" tabIndex={-1} className="a-shell-frame__content">{children ?? <p>No workspace selected.</p>}</main></div>; }
