import {it,expect,vi,beforeEach} from 'vitest';import {createHash} from 'node:crypto';
const m=vi.hoisted(()=>({owner:vi.fn(async()=>true),search:vi.fn(async()=>({citations:[{citation:{sourceId:'fc668e33-9d67-4015-83ba-8be70dfbb2c6'}}]}))}));
vi.mock('@athyper/server-service-attachments',()=>({createAttachmentRetrievalAdmission:()=>({authorize:m.owner})}));vi.mock('../atlas-attachment-knowledge.js',()=>({createAtlasAttachmentKnowledge:()=>({execute:m.search})}));
import {createAtlasDocumentGrounding,atlasDocumentSearchTerms} from '../atlas-document-grounding.js';
const id='fc668e33-9d67-4015-83ba-8be70dfbb2c6',parent='f7688c3d-8c92-5651-a469-da3f4f786375',text='Synthetic Indigo Lantern, 17 days.';
const page={schemaVersion:1,kind:'record',entityCode:'business_partner',recordId:parent,dirty:false,generationId:'g',locale:'en',workContext:{operatingOrganizationId:'org'}} as const;
const context={planeKey:'neon',tenantId:'tenant',principalId:'actor'} as never;
function setup({allowed=true,changed=false,pii=false,prefix="",semantic=false}={}){let queries=0;const query=vi.fn(async()=>({rows:++queries===1?[{revision_id:'revision',source_version_id:id+':hash',chunk_id:'chunk',checksum:createHash('sha256').update(text).digest('hex'),character_start:prefix.length,character_end:prefix.length+text.length}]:[{file_name:'synthetic.txt',content_type:'text/plain',sha256:'hash',extracted_text:changed?'changed':prefix+text,pii_detected:pii}]}));const db={getExecutor:()=>({transformQuery:(q:unknown)=>q,compileQuery:(q:unknown)=>q,executeQuery:query})};const refresh=vi.fn(async(c:unknown)=>c),list=vi.fn(async()=>({data:[{id:parent}]}));const grounding=createAtlasDocumentGrounding({...(semantic?{semantic:{model:"test"}}:{}),refresh,transactions:{run:async(_p:unknown,_a:unknown,f:Function)=>f(db)},metadata:{getEntityDescriptor:async()=>({ai:{enabled:true},operations:{read:{}},storage:{idField:'id'}})},records:{list},authorizer:{authorize:async()=>({allowed})}} as never);return {grounding,refresh,list,query};}
const input={context,businessContext:page,attachmentContextId:parent,attachmentIds:[id],dataClass:'synthetic' as const};beforeEach(()=>{vi.clearAllMocks();m.owner.mockResolvedValue(true);});
it('loads bounded, canonical text with provenance after refreshed owner checks',async()=>{const s=setup();const rows=await s.grounding.attachments.resolve(input);expect(rows[0]).toMatchObject({text,provenance:{chunkId:'chunk',revisionId:'revision'}});expect(s.refresh).toHaveBeenCalledOnce();expect(m.owner).toHaveBeenCalledTimes(2);expect(s.list).toHaveBeenCalledWith(expect.objectContaining({scopeCoordinate:page.workContext,recordIds:[parent]}));});
it('does not read document metadata or text after a permission revocation',async()=>{const s=setup({allowed:false});await expect(s.grounding.attachments.resolve(input)).rejects.toThrow();expect(s.query).not.toHaveBeenCalled();});
it('does not read text when owner admission denies the canonical locator',async()=>{m.owner.mockResolvedValue(false);const s=setup();await expect(s.grounding.attachments.resolve(input)).rejects.toThrow();expect(s.query).toHaveBeenCalledTimes(1);});
it('rejects changed extraction under the same scanned file hash',async()=>{const s=setup({changed:true});await expect(s.grounding.attachments.resolve(input)).rejects.toThrow();});
it('rejects detected personal data in public mode',async()=>{const s=setup({pii:true});await expect(s.grounding.attachments.resolve({...input,dataClass:'public'})).rejects.toThrow();});
it('cannot substitute a different parent context',async()=>{const s=setup();await expect(s.grounding.attachments.resolve({...input,attachmentContextId:'other'})).rejects.toThrow();expect(s.query).not.toHaveBeenCalled();});
it('does not retrieve current document context for a historical record',async()=>{const s=setup();expect(await s.grounding.select(context,{...page,asOf:'2020-01-01'},'document')).toBeUndefined();expect(m.search).not.toHaveBeenCalled();});
it('selects only authorized citations within the explicit record scope',async()=>{const s=setup();expect(await s.grounding.select(context,page,'Indigo Lantern')).toEqual({attachmentContextId:parent,attachmentIds:[id]});expect(m.search).toHaveBeenCalledWith(context,expect.objectContaining({recordId:parent,scopeCoordinate:page.workContext,query:'indigo lantern'}),false,undefined);});

it("normalizes natural questions without changing evidence or inserting facts",()=>{expect(atlasDocumentSearchTerms("According to the synthetic document attached to this partner, what is the fictional project name and its review interval? Cite the document and identify the facts as synthetic.")).toBe("synthetic fictional project review interval");});

it('loads the selected later passage with exact offsets and checksum',async()=>{const s=setup({prefix:'Unrelated introduction. '.repeat(150)});const rows=await s.grounding.attachments.resolve({...input,attachmentChunkIds:['01a08997-0f2d-7238-a99a-f75c3a224e0b']});expect(rows[0].text).toBe(text);expect(rows[0].provenance?.characterStart).toBeGreaterThan(2000);});
it('retains semantic passage coordinates and original question through selection',async()=>{const chunkId='01a08997-0f2d-7238-a99a-f75c3a224e0b';m.search.mockResolvedValueOnce({citations:[{citation:{sourceId:id,chunkId,characterStart:2000,characterEnd:3000}}]} as never);const s=setup({semantic:true});expect(await s.grounding.select(context,page,'How often should we reassess?')).toEqual({attachmentContextId:parent,attachmentIds:[id],attachmentChunkIds:[chunkId]});expect(m.search).toHaveBeenLastCalledWith(context,expect.objectContaining({query:'How often should we reassess?'}),false,undefined);});
it('rejects mismatched selected passage coordinates before any document read',async()=>{const s=setup();await expect(s.grounding.attachments.resolve({...input,attachmentChunkIds:[]})).rejects.toThrow();expect(s.query).not.toHaveBeenCalled();});

it('propagates the cancellation signal into document retrieval',async()=>{const s=setup(),controller=new AbortController();await s.grounding.select(context,page,'Synthetic',controller.signal);expect(m.search).toHaveBeenLastCalledWith(context,expect.anything(),false,controller.signal);});
