import type { BudgetBalance, BudgetCoordinate, BudgetMutationCommand, BudgetRepository, BudgetState, BudgetTransaction, FinanceActor } from "@athyper/server-contract-finance";
import { sql, type Transaction } from "kysely";

type Database = Record<string, never>;
type Tx = Transaction<Database>;
type Row = Record<string, unknown>;

export class KyselyBudgetRepository implements BudgetRepository<Tx> {
  async getBalance(actor:FinanceActor,coordinate:BudgetCoordinate,transaction:Tx):Promise<BudgetBalance|undefined>{const row=(await sql<Row>`SELECT * FROM ledger.budget_balance WHERE tenant_id=${actor.tenantId}::uuid AND budget_allocation_id=${coordinate.budgetAllocationId}::uuid AND fiscal_year=${coordinate.fiscalYear} AND period_number=${coordinate.periodNumber}`.execute(transaction)).rows[0];return row?mapBalance(row):undefined;}
  async getOrCreateBalanceForUpdate(actor: FinanceActor, coordinate: BudgetCoordinate, transaction: Tx): Promise<BudgetBalance> {
    await sql`INSERT INTO ledger.budget_balance(tenant_id,budget_allocation_id,fiscal_year,period_number,created_by) VALUES(${actor.tenantId}::uuid,${coordinate.budgetAllocationId}::uuid,${coordinate.fiscalYear},${coordinate.periodNumber},${actor.principalId}::uuid) ON CONFLICT(tenant_id,budget_allocation_id,fiscal_year,period_number) DO NOTHING`.execute(transaction);
    const row=(await sql<Row>`SELECT * FROM ledger.budget_balance WHERE tenant_id=${actor.tenantId}::uuid AND budget_allocation_id=${coordinate.budgetAllocationId}::uuid AND fiscal_year=${coordinate.fiscalYear} AND period_number=${coordinate.periodNumber} FOR UPDATE`.execute(transaction)).rows[0];
    if(!row)throw new Error("FINANCE_BUDGET_BALANCE_LOCK_FAILED");return mapBalance(row);
  }
  async getTransaction(actor: FinanceActor, transactionId: string, transaction: Tx): Promise<BudgetTransaction|undefined>{const row=(await sql<Row>`SELECT * FROM ledger.budget_transaction WHERE tenant_id=${actor.tenantId}::uuid AND id=${transactionId}::uuid`.execute(transaction)).rows[0];return row?mapTransaction(row):undefined;}
  async findReversal(actor: FinanceActor, originalTransactionId: string, transaction: Tx): Promise<BudgetTransaction|undefined>{const row=(await sql<Row>`SELECT * FROM ledger.budget_transaction WHERE tenant_id=${actor.tenantId}::uuid AND reversal_of_transaction_id=${originalTransactionId}::uuid LIMIT 1`.execute(transaction)).rows[0];return row?mapTransaction(row):undefined;}
  async append(command: BudgetMutationCommand, transaction: Tx, states: {readonly previous:BudgetState;readonly resulting:BudgetState}):Promise<BudgetTransaction>{const p=command.payload,row=(await sql<Row>`INSERT INTO ledger.budget_transaction(id,tenant_id,budget_profile_id,budget_allocation_id,project_id,project_wbs_id,transaction_type,direction,amount,currency_code,fiscal_year,period_number,effective_date,source_document_type,source_document_id,reversal_of_transaction_id,idempotency_key,previous_state,resulting_state,reason,performed_by,metadata,created_by) VALUES(${command.commandId}::uuid,${command.actor.tenantId}::uuid,${p.budgetProfileId}::uuid,${p.budgetAllocationId}::uuid,${p.projectId}::uuid,${p.projectWbsId}::uuid,${p.transactionType},${p.direction},${p.amount}::numeric,${p.currencyCode},${p.fiscalYear},${p.periodNumber},${p.effectiveDate}::date,${p.sourceDocumentType},${p.sourceDocumentId}::uuid,${p.reversalOfTransactionId??null}::uuid,${command.idempotencyKey},${JSON.stringify(states.previous)}::jsonb,${JSON.stringify(states.resulting)}::jsonb,${p.reason??null},${command.actor.principalId}::uuid,${JSON.stringify({...p.metadata,postingCoordinates:p.postingCoordinates})}::jsonb,${command.actor.principalId}::uuid) RETURNING *`.execute(transaction)).rows[0];if(!row)throw new Error("FINANCE_BUDGET_APPEND_FAILED");return mapTransaction(row);}
  async compareAndSwapBalance(actor:FinanceActor,balance:BudgetBalance,expectedVersion:number,transaction:Tx):Promise<BudgetBalance|undefined>{const row=(await sql<Row>`UPDATE ledger.budget_balance SET opening_amount=${balance.openingAmount}::numeric,reserved_amount=${balance.reservedAmount}::numeric,consumed_amount=${balance.consumedAmount}::numeric,released_amount=${balance.releasedAmount}::numeric,adjusted_amount=${balance.adjustedAmount}::numeric,version_number=version_number+1,updated_by=${actor.principalId}::uuid WHERE tenant_id=${actor.tenantId}::uuid AND id=${balance.id}::uuid AND version_number=${expectedVersion} RETURNING *`.execute(transaction)).rows[0];return row?mapBalance(row):undefined;}
  async listTransactions(actor:FinanceActor,coordinate:BudgetCoordinate,transaction?:Tx):Promise<readonly BudgetTransaction[]>{if(!transaction)throw new Error("Budget transaction queries require a plane-local transaction");return (await sql<Row>`SELECT * FROM ledger.budget_transaction WHERE tenant_id=${actor.tenantId}::uuid AND budget_allocation_id=${coordinate.budgetAllocationId}::uuid AND fiscal_year=${coordinate.fiscalYear} AND period_number=${coordinate.periodNumber} ORDER BY performed_at,created_at,id`.execute(transaction)).rows.map(mapTransaction);}
}

function mapBalance(row:Row):BudgetBalance{return{id:String(row["id"]),budgetAllocationId:String(row["budget_allocation_id"]),fiscalYear:Number(row["fiscal_year"]),periodNumber:Number(row["period_number"]),openingAmount:String(row["opening_amount"]),reservedAmount:String(row["reserved_amount"]),consumedAmount:String(row["consumed_amount"]),releasedAmount:String(row["released_amount"]),adjustedAmount:String(row["adjusted_amount"]),availableAmount:String(row["available_amount"]),versionNumber:Number(row["version_number"])};}
function mapTransaction(row:Row):BudgetTransaction{return{id:String(row["id"]),budgetProfileId:String(row["budget_profile_id"]),budgetAllocationId:String(row["budget_allocation_id"]),projectId:String(row["project_id"]),projectWbsId:String(row["project_wbs_id"]),transactionType:String(row["transaction_type"]) as BudgetTransaction["transactionType"],direction:String(row["direction"]) as BudgetTransaction["direction"],amount:String(row["amount"]),currencyCode:String(row["currency_code"]),fiscalYear:Number(row["fiscal_year"]),periodNumber:Number(row["period_number"]),effectiveDate:date(row["effective_date"]),sourceDocumentType:String(row["source_document_type"]),sourceDocumentId:String(row["source_document_id"]),idempotencyKey:String(row["idempotency_key"]),previousState:object(row["previous_state"]) as unknown as BudgetState,resultingState:object(row["resulting_state"]) as unknown as BudgetState,...(row["reversal_of_transaction_id"]?{reversalOfTransactionId:String(row["reversal_of_transaction_id"])}:{}),...(row["reason"]?{reason:String(row["reason"])}:{}),performedAt:date(row["performed_at"]),performedBy:String(row["performed_by"]),metadata:object(row["metadata"])};}
function object(value:unknown):Readonly<Record<string,unknown>>{if(typeof value==="string")try{return JSON.parse(value) as Record<string,unknown>;}catch{return{};}return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function date(value:unknown):string{return value instanceof Date?value.toISOString():String(value);}
