user default on #__APP_HASH__ ~* &* +@read +@write +@connection +@fast +ping +auth +quit +reset +keys +scan +del +expire +pexpire +ttl +pttl +type +unlink +exists +@sortedset +@hash +@list +@set +@string +xadd +xtrim +xread +xreadgroup +xlen +xrange +xrevrange +xack +xgroup|create +xgroup|setid +xdel +object|encoding -@admin -config -debug -shutdown -flushall -flushdb -@geo -@hyperloglog -acl|setuser -acl|deluser -acl|save -acl|load +info +eval +evalsha +subscribe +psubscribe +unsubscribe +punsubscribe +publish +ssubscribe +sunsubscribe

user app on #__APP_HASH__ ~session:* ~athyper:session:* ~principal_sessions:* ~bootstrap:* ~bootstrap_keys:* ~sess:* ~user_sessions:* ~refresh_lock:* ~sid_rotation:* ~ratelimit:* ~pkce_state:* ~iam:presentation:v1:* ~jwks:* ~kc_session:* ~bull:jobs-* ~mfa_elevation:* ~wa_assert:* ~ff:* ~oauth2:token:* ~ai:* ~desc:* ~desc:v4:* ~descriptor-runtime:* ~execdesc:* ~listpage:v2:* ~entityquery-count:v1:* ~outbox:processed:v1:* ~kc_admin_token ~__health_probe__ &activity:* &desc:* &descriptor-runtime:* &execdesc:* &record:* +@read +@write +@set +@connection +@fast +ping +auth +quit +reset +get +set +del +ttl +pttl +expire +pexpire +exists +type +unlink +sadd +srem +smembers +scard +sismember +scan +keys +client|setname +client|getname +eval +evalsha +@sortedset +@hash +@list +xadd +xtrim +xread +xreadgroup +xlen +xrange +xrevrange +xack +xgroup|create +xgroup|setid +xdel +object|encoding +publish +subscribe +unsubscribe -@admin -@dangerous -config -debug -shutdown -flushall -flushdb -@geo -@hyperloglog +info +getdel

user exporter on #__EXPORTER_HASH__ +@connection +ping +auth +quit +reset +config|get +client|list +client|info +slowlog|get +slowlog|len +latency|history +latency|latest +latency|reset +dbsize +object|encoding +object|freq +object|help +object|idletime +object|refcount +memory|usage +memory|doctor +memory|stats -@write -@admin -@dangerous -config|set -config|rewrite -config|resetstat -debug -shutdown -flushall -flushdb -@scripting -@pubsub +info

user glitchtip on #__GLITCHTIP_HASH__ ~* &* +@connection +ping +auth +quit +reset +@fast +@read +@write +@string +@hash +@list +@set +@sortedset +@keyspace +@pubsub -@admin -@dangerous -@scripting -@stream -@geo -@hyperloglog -config -debug -shutdown -flushall -flushdb -cluster -wait -waitaof -sort -object

user infisical on #__INFISICAL_HASH__ ~* &* +@connection +ping +auth +quit +reset +@fast +@read +@write +@string +@hash +@list +@set +@sortedset +@keyspace +xadd +xtrim +xread +xreadgroup +xlen +xrange +xrevrange +xack +xgroup|create +xgroup|setid +xdel +object|encoding -@admin -@dangerous -@scripting -config -debug -shutdown -flushall -flushdb -cluster -wait -waitaof -sort +info +eval +evalsha +subscribe +psubscribe +unsubscribe +punsubscribe +publish +ssubscribe +sunsubscribe

user admin on #__ADMIN_HASH__ ~* &* +@all

user bullboard on #__BULLBOARD_HASH__ ~bull:* &* +@read +@connection +ping +auth +quit +reset +scan +keys +info +client|getname +client|setname +eval +evalsha -@write -@admin -@dangerous -publish -subscribe -psubscribe
