CREATE TABLE control.cron_schedule (
    id                uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id         uuid,
    code              text        NOT NULL,
    name              text        NOT NULL,
    description       text,
    handler_type      text        NOT NULL,
    cron_expression   text        NOT NULL,
    timezone          text        NOT NULL DEFAULT 'UTC',
    target_queue      text        NOT NULL,
    payload_template  jsonb       NOT NULL DEFAULT '{}'::jsonb,
    priority          smallint    NOT NULL DEFAULT 0,
    max_retries       smallint    NOT NULL DEFAULT 3,
    concurrency_limit smallint,
    effective_from    timestamptz,
    effective_until   timestamptz,
    is_enabled        boolean     NOT NULL DEFAULT true,
    lock_key          text,
    last_run_at       timestamptz,
    next_run_at       timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        uuid        NOT NULL,
    updated_at        timestamptz,
    updated_by        uuid,
    CONSTRAINT cron_schedule_pkey PRIMARY KEY (id),
    CONSTRAINT cron_schedule_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT cron_schedule_code_uq UNIQUE NULLS NOT DISTINCT (tenant_id, code),
    CONSTRAINT cron_schedule_code_chk CHECK (code ~ '^[a-z][a-z0-9_.-]{1,126}$'),
    CONSTRAINT cron_schedule_text_chk CHECK (btrim(name) <> '' AND btrim(handler_type) <> '' AND btrim(cron_expression) <> '' AND btrim(target_queue) <> ''),
    CONSTRAINT cron_schedule_retry_chk CHECK (max_retries >= 0 AND (concurrency_limit IS NULL OR concurrency_limit > 0)),
    CONSTRAINT cron_schedule_window_chk CHECK (effective_until IS NULL OR effective_from IS NULL OR effective_until > effective_from),
    CONSTRAINT cron_schedule_json_chk CHECK (jsonb_typeof(payload_template) = 'object'),
    CONSTRAINT cron_schedule_audit_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

COMMENT ON TABLE control.cron_schedule IS 'Physical-plane BullMQ schedules. tenant_id NULL rows are plane-global; code-owned registry entries win at runtime.';
