-- Canonical notification configuration shared by all three physical planes.
-- Provider credentials remain in the external secret provider. config may only
-- contain non-secret adapter settings; credential_ref is an opaque reference.
CREATE TABLE control.notification_provider (
    id                    uuid        NOT NULL DEFAULT shared.uuidv7(),
    channel               text        NOT NULL,
    code                  text        NOT NULL,
    name                  text        NOT NULL,
    adapter_key           text        NOT NULL,
    credential_ref        text,
    priority              smallint    NOT NULL DEFAULT 1,
    is_enabled            boolean     NOT NULL DEFAULT true,
    config                jsonb       NOT NULL DEFAULT '{}'::jsonb,
    rate_limit            jsonb,
    health                control.notification_provider_health_d NOT NULL DEFAULT 'unknown',
    last_health_check_at  timestamptz,
    last_error_code       text,
    last_error_message    text,
    created_at            timestamptz NOT NULL DEFAULT now(),
    created_by            uuid        NOT NULL,
    updated_at            timestamptz,
    updated_by            uuid,
    CONSTRAINT notification_provider_pkey PRIMARY KEY (id),
    CONSTRAINT notification_provider_code_uq UNIQUE (channel, code),
    CONSTRAINT notification_provider_channel_chk CHECK (channel IN ('in_app','email','sms','whatsapp','push','webhook')),
    CONSTRAINT notification_provider_code_chk CHECK (code ~ '^[a-z][a-z0-9_.-]{1,62}$'),
    CONSTRAINT notification_provider_name_chk CHECK (btrim(name) <> ''),
    CONSTRAINT notification_provider_adapter_chk CHECK (adapter_key ~ '^[a-z][a-z0-9_.-]{1,126}$'),
    CONSTRAINT notification_provider_credential_chk CHECK (credential_ref IS NULL OR btrim(credential_ref) <> ''),
    CONSTRAINT notification_provider_json_chk CHECK (jsonb_typeof(config) = 'object' AND (rate_limit IS NULL OR jsonb_typeof(rate_limit) = 'object')),
    CONSTRAINT notification_provider_priority_chk CHECK (priority BETWEEN 1 AND 32767),
    CONSTRAINT notification_provider_audit_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE control.notification_template (
    id               uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id        uuid,
    template_key     text        NOT NULL,
    channel          text        NOT NULL,
    locale           text        NOT NULL DEFAULT 'en',
    version          smallint    NOT NULL DEFAULT 1,
    status           control.notification_template_status_d NOT NULL DEFAULT 'draft',
    subject          text,
    body_text        text,
    body_html        text,
    body_json        jsonb,
    variables_schema jsonb,
    metadata         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       uuid        NOT NULL,
    updated_at       timestamptz,
    updated_by       uuid,
    CONSTRAINT notification_template_pkey PRIMARY KEY (id),
    CONSTRAINT notification_template_coordinate_uq UNIQUE NULLS NOT DISTINCT (tenant_id, template_key, channel, locale, version),
    CONSTRAINT notification_template_key_chk CHECK (template_key ~ '^[a-z][a-z0-9_.-]{1,126}$'),
    CONSTRAINT notification_template_channel_chk CHECK (channel IN ('in_app','email','sms','whatsapp','push','webhook')),
    CONSTRAINT notification_template_locale_chk CHECK (locale ~ '^[a-z]{2,3}(-[A-Z]{2})?$'),
    CONSTRAINT notification_template_version_chk CHECK (version > 0),
    CONSTRAINT notification_template_body_chk CHECK (subject IS NOT NULL OR body_text IS NOT NULL OR body_html IS NOT NULL OR body_json IS NOT NULL),
    CONSTRAINT notification_template_json_chk CHECK ((variables_schema IS NULL OR jsonb_typeof(variables_schema) = 'object') AND jsonb_typeof(metadata) = 'object' AND (body_json IS NULL OR jsonb_typeof(body_json) = 'object')),
    CONSTRAINT notification_template_audit_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE control.notification_routing_rule (
    id               uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id        uuid,
    code             text        NOT NULL,
    name             text        NOT NULL,
    description      text,
    event_type       text        NOT NULL,
    entity_type      text,
    lifecycle_state  text,
    workflow_phase   text,
    condition_expr   jsonb,
    template_key     text        NOT NULL,
    channels         text[]      NOT NULL,
    priority         text        NOT NULL DEFAULT 'normal',
    recipient_rules  jsonb       NOT NULL DEFAULT '{}'::jsonb,
    digest_frequency text,
    sla_minutes      integer,
    dedup_window_ms  integer     NOT NULL DEFAULT 300000,
    is_enabled       boolean     NOT NULL DEFAULT true,
    sort_order       smallint    NOT NULL DEFAULT 0,
    metadata         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at       timestamptz NOT NULL DEFAULT now(),
    created_by       uuid        NOT NULL,
    updated_at       timestamptz,
    updated_by       uuid,
    CONSTRAINT notification_routing_rule_pkey PRIMARY KEY (id),
    CONSTRAINT notification_routing_rule_code_uq UNIQUE NULLS NOT DISTINCT (tenant_id, code),
    CONSTRAINT notification_routing_rule_code_chk CHECK (code ~ '^[a-z][a-z0-9_.-]{1,126}$' AND event_type ~ '^[a-z][a-z0-9_.:-]{1,126}$' AND template_key ~ '^[a-z][a-z0-9_.-]{1,126}$'),
    CONSTRAINT notification_routing_rule_name_chk CHECK (btrim(name) <> ''),
    CONSTRAINT notification_routing_rule_channels_chk CHECK (cardinality(channels) > 0 AND channels <@ ARRAY['in_app','email','sms','whatsapp','push','webhook']::text[] AND array_position(channels, NULL) IS NULL),
    CONSTRAINT notification_routing_rule_priority_chk CHECK (priority IN ('low','normal','high','urgent')),
    CONSTRAINT notification_routing_rule_digest_chk CHECK (digest_frequency IS NULL OR digest_frequency IN ('hourly_digest','daily_digest','weekly_digest')),
    CONSTRAINT notification_routing_rule_json_chk CHECK ((condition_expr IS NULL OR jsonb_typeof(condition_expr) = 'object') AND jsonb_typeof(recipient_rules) = 'object' AND jsonb_typeof(metadata) = 'object'),
    CONSTRAINT notification_routing_rule_limits_chk CHECK (dedup_window_ms >= 0 AND (sla_minutes IS NULL OR sla_minutes > 0)),
    CONSTRAINT notification_routing_rule_audit_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

COMMENT ON TABLE control.notification_provider IS 'Physical-plane provider binding and health metadata. Secrets are externally referenced by credential_ref.';
COMMENT ON TABLE control.notification_template IS 'Physical-plane platform defaults and tenant overrides. Product defaults belong in plane seed overlays.';
COMMENT ON TABLE control.notification_routing_rule IS 'Physical-plane event routing rules. tenant_id NULL rows are platform defaults.';
