"use client";
import { useMemo, useState } from "react";
import { ManagementToolbar } from "@athyper/platform-shell";
import { StickyListTable } from "@athyper/platform-entity-list-view";
import { Button, Input } from "@athyper/platform-ui";
import { SearchIcon, FilterIcon, SlidersHorizontalIcon } from "@athyper/platform-icons";
export interface DirectoryInstitution {id:string;name:string;countryCode:string;institutionType:string;status:string;}
export interface PublishedDirectory {id:string;version:number;payload:{institutions:DirectoryInstitution[];branches:{id:string;institutionId:string;name:string;status:string}[];identifiers:{id:string;institutionId?:string;branchId?:string;scheme:string;value:string}[]};}
const countryName=(code:string)=>{try{return new Intl.DisplayNames(undefined,{type:"region"}).of(code)??code;}catch{return code;}};
const columns=[['name','Bank name'],['country','Country'],['type','Institution type'],['bic','BIC'],['branches','Branches'],['status','Status']] as const;
export function BankDirectoryManage({directory,loading,onImport,canAuthor}:{readonly directory:PublishedDirectory|null;readonly loading:boolean;readonly onImport:()=>void;readonly canAuthor:boolean}) {
 const [query,setQuery]=useState(''),[view,setView]=useState('all'),[country,setCountry]=useState(''),[filters,setFilters]=useState(false),[controls,setControls]=useState(false),[compact,setCompact]=useState(false),[visible,setVisible]=useState<string[]>(columns.map(c=>c[0])),[sort,setSort]=useState<{key:string;descending:boolean}>({key:'name',descending:false}),[page,setPage]=useState(0),[selected,setSelected]=useState<string>();
 const rows=useMemo(()=> (directory?.payload.institutions??[]).map(bank=>({...bank,country:countryName(bank.countryCode),type:bank.institutionType.replaceAll('_',' '),bic:directory!.payload.identifiers.filter(i=>i.institutionId===bank.id&&i.scheme==='bic').map(i=>i.value).join(', '),branches:directory!.payload.branches.filter(b=>b.institutionId===bank.id).length})),[directory]);
 const filtered=rows.filter(r=>(view==='all'||r.status===view)&&(!country||r.countryCode===country)&&[r.name,r.country,r.bic].join(' ').toLowerCase().includes(query.toLowerCase()));
 filtered.sort((a,b)=>{const x=a[sort.key as keyof typeof a],y=b[sort.key as keyof typeof b];return (typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y)))*(sort.descending?-1:1)});
 const current=Math.min(page,Math.max(0,Math.ceil(filtered.length/20)-1)),selectedBank=rows.find(r=>r.id===selected);
 return <div className={`a-entity-list a-entity-list--${compact?'compact':'comfortable'}`}>
  <div className="a-entity-list__panel">
   <ManagementToolbar>
    <label className="bank-directory-list__view">View: <select aria-label="Directory view" value={view} onChange={e=>{setView(e.target.value);setPage(0)}}><option value="all">All banks</option><option value="active">Active banks</option><option value="retired">Retired banks</option></select></label>
    <div data-slot="search" className="bank-directory-list__search"><SearchIcon size={16}/><Input aria-label="Search banks" type="search" placeholder="Search by bank name, country or BIC…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></div>
    <div data-slot="actions"><Button variant="secondary" onClick={()=>setFilters(v=>!v)} aria-expanded={filters}><FilterIcon size={16}/> Filters{country?' (1)':''}</Button><Button variant="secondary" onClick={()=>setControls(v=>!v)} aria-expanded={controls}><SlidersHorizontalIcon size={16}/> Controls</Button></div>
   </ManagementToolbar>
   {filters?<div className="bank-directory-list__options"><label>Country <select value={country} onChange={e=>{setCountry(e.target.value);setPage(0)}}><option value="">All countries</option>{[...new Set(rows.map(r=>r.countryCode))].sort().map(code=><option key={code} value={code}>{countryName(code)}</option>)}</select></label><Button variant="secondary" onClick={()=>{setCountry('');setView('all');setQuery('');setPage(0)}}>Clear filters</Button></div>:null}
   {controls?<fieldset className="bank-directory-list__options"><legend>Display controls</legend>{columns.map(([key,label])=><label key={key}><input type="checkbox" checked={visible.includes(key)} disabled={key==='name'} onChange={e=>setVisible(v=>e.target.checked?[...v,key]:v.filter(k=>k!==key))}/>{label}</label>)}<label><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/>Compact rows</label></fieldset>:null}
   <StickyListTable><table className="a-entity-list__table" aria-label="Published banks"><thead><tr>{columns.filter(([key])=>visible.includes(key)).map(([key,label])=><th key={key} className={key==='branches'?'bank-directory-list__number':undefined} aria-sort={sort.key===key?(sort.descending?'descending':'ascending'):'none'}><button type="button" onClick={()=>setSort({key,descending:sort.key===key?!sort.descending:false})}>{label}{sort.key===key?(sort.descending?' ↓':' ↑'):''}</button></th>)}</tr></thead><tbody>{filtered.slice(current*20,current*20+20).map(row=><tr key={row.id}>{columns.filter(([key])=>visible.includes(key)).map(([key,label])=><td key={key} data-label={label} className={key==='branches'?'bank-directory-list__number':undefined}>{key==='name'?<button className="bank-directory-list__link" onClick={()=>setSelected(row.id)}>{row.name}</button>:key==='status'?<span className={`bank-directory-list__status bank-directory-list__status--${row.status}`}>{row.status==='active'?'Active':'Retired'}</span>:key==='branches'?row.branches:row[key as keyof typeof row]||'—'}</td>)}</tr>)}</tbody></table></StickyListTable>
   {!filtered.length?<div className="bank-directory-list__empty" role="status">{loading?'Loading published banks…':!directory?'No published directory yet. Approved releases appear here after activation.':'No banks match your search or filters.'}{canAuthor&&!directory?<Button onClick={onImport}>Import bank data</Button>:null}</div>:null}
   <div className="a-entity-list__pagination"><span>{filtered.length?`${current*20+1}–${Math.min((current+1)*20,filtered.length)} of ${filtered.length} banks`:'0 banks'}</span><div><Button variant="secondary" disabled={!current} onClick={()=>setPage(current-1)}>Previous</Button><Button variant="secondary" disabled={(current+1)*20>=filtered.length} onClick={()=>setPage(current+1)}>Next</Button></div></div>
  </div>
  {selectedBank?<section className="bank-directory-list__detail" aria-label={`${selectedBank.name} details`}><div className="bank-directory-list__detail-heading"><h2>{selectedBank.name}</h2><Button variant="secondary" onClick={()=>setSelected(undefined)}>Close details</Button></div><p>{selectedBank.country} · {selectedBank.type} · {selectedBank.status}</p><p>Published in release {directory?.version}. Changes require a new reviewed revision.</p><h3>Routing identifiers</h3><ul>{directory?.payload.identifiers.filter(i=>i.institutionId===selectedBank.id||directory.payload.branches.some(b=>b.id===i.branchId&&b.institutionId===selectedBank.id)).map(i=><li key={i.id}>{i.scheme.toUpperCase()}: {i.value}</li>)}</ul><h3>Branches</h3>{selectedBank.branches?<ul>{directory?.payload.branches.filter(b=>b.institutionId===selectedBank.id).map(b=><li key={b.id}>{b.name} · {b.status}</li>)}</ul>:<p>No branches published for this institution.</p>}<details><summary>Technical identity</summary><p>{selectedBank.id}</p></details></section>:null}
 </div>;
}
