"use client";
import * as React from "react";

type Json=Record<string,unknown>;
const journeys=["supplier","customer","workforce","governance"] as const;
export function BusinessPartnerWorkflowDesigner({value,onChange}:{readonly value:unknown;readonly onChange:(value:Json)=>void}){const definitions=record(value);return <section aria-labelledby="bp-workflow-designer"><h3 id="bp-workflow-designer">Workflow administration</h3><p>Configure pinned stage order, conditional routes, parallel quorum, SLA reminders and escalation. Notification delivery uses each recipient&apos;s enabled communication channels.</p>{journeys.map(journey=>{const workflow=record(definitions[journey]),stages=array(workflow.stages);const change=(next:unknown[])=>onChange({...definitions,[journey]:{...workflow,version:String(workflow.version??"3.0.0"),stages:next}});return <fieldset key={journey}><legend>{title(journey)} workflow</legend>{stages.map((candidate,index)=><StageEditor key={`${journey}-${index}`} value={record(candidate)} index={index} onChange={stage=>change(stages.map((item,itemIndex)=>itemIndex===index?stage:item))} remove={()=>change(stages.filter((_,itemIndex)=>itemIndex!==index))}/>) }<button type="button" onClick={()=>change([...stages,newStage(stages.length)])}>Add stage</button></fieldset>})}</section>}
function StageEditor({value,index,onChange,remove}:{value:Json;index:number;onChange:(value:Json)=>void;remove:()=>void}){const quorum=record(value.quorum),when=record(value.when),set=(patch:Json)=>onChange({...value,...patch});return <fieldset><legend>Stage {index+1}: {title(String(value.code??"new_stage"))}</legend><div className="athyper-form-grid"><Text label="Code" value={String(value.code??"")} onChange={code=>set({code})}/><Text label="Name" value={String(value.name??"")} onChange={name=>set({name})}/><label>Execution mode<select value={value.mode==="serial"?"serial":"parallel"} onChange={event=>set({mode:event.currentTarget.value})}><option value="serial">Serial</option><option value="parallel">Parallel</option></select></label><label>Quorum<select value={String(quorum.kind??"any")} onChange={event=>set({quorum:{...quorum,kind:event.currentTarget.value}})}><option value="any">Any approver</option><option value="all">All approvers</option><option value="count">Fixed count</option><option value="percentage">Percentage</option></select></label><Text label="Quorum value" type="number" value={quorum.value===undefined?"":String(quorum.value)} onChange={raw=>set({quorum:{...quorum,...(raw?{value:Number(raw)}:{value:undefined})}})}/><Text label="SLA minutes" type="number" value={String(value.slaMinutes??"")} onChange={raw=>set({slaMinutes:raw?Number(raw):undefined})}/><Text label="Reminder minutes" value={array(value.remindersAtMinutes).join(", ")} onChange={raw=>set({remindersAtMinutes:numbers(raw)})}/><Text label="Escalate after minutes" type="number" value={String(value.escalateAtMinutes??"")} onChange={raw=>set({escalateAtMinutes:raw?Number(raw):undefined})}/></div><details><summary>Conditional route</summary><div className="athyper-form-grid"><Text label="Payload path" value={String(when.path??"")} onChange={path=>set({when:{...when,path}})}/><label>Operator<select value={String(when.operator??"equals")} onChange={event=>set({when:{...when,operator:event.currentTarget.value}})}><option value="equals">Equals</option><option value="not_equals">Does not equal</option><option value="in">In list</option><option value="exists">Exists</option></select></label><Text label="Expected value" value={when.value===undefined?"":String(when.value)} onChange={expected=>set({when:{...when,value:expected}})}/><button type="button" onClick={()=>{const next={...value};delete next.when;onChange(next)}}>Clear condition</button></div></details><button type="button" onClick={remove}>Remove stage</button></fieldset>}
function Text({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label>{label}<input type={type} value={value} onChange={event=>onChange(event.currentTarget.value)}/></label>}
function newStage(index:number){return{code:`review_${index+1}`,name:`Review ${index+1}`,mode:"parallel",quorum:{kind:"any"},slaMinutes:240,remindersAtMinutes:[120,192],escalateAtMinutes:240,noSelfApproval:true};}
function record(value:unknown):Json{return value&&typeof value==="object"&&!Array.isArray(value)?value as Json:{}}
function array(value:unknown):unknown[]{return Array.isArray(value)?value:[]}
function numbers(value:string){return [...new Set(value.split(",").map(item=>Number(item.trim())).filter(item=>Number.isFinite(item)&&item>0))].sort((a,b)=>a-b)}
function title(value:string){return value.replaceAll(/[._-]+/g," ").replace(/\b\w/g,letter=>letter.toUpperCase())}
