import type { Request,RequestHandler,Router } from "express";
import { resolvePrincipalIdWithJit,resolveTenantId,verifyBearer } from "@athyper/svc-shared";
import type { FinanceRouteDeps } from "./finance.route.js";
import { FinancePaymentsError,loadCompanyPaymentsSetup,loadPaymentTermDefinitions,saveInterfaceBinding,savePaymentPolicy,savePaymentTerm,saveSettlementRule,tracePaymentInterfaceRouting } from "../services/finance-payments-setup.service.js";

type Context={tenantId:string;principalId:string|null;req:Request};type Runner=(context:Context)=>Promise<unknown>;
function paymentsHandler(deps:FinanceRouteDeps,mutation:boolean,runner:Runner):RequestHandler{return async(req,res,next)=>{try{const claims=await verifyBearer(req.headers.authorization??"",deps.auth,res);if(!claims)return;const realm=String(req.headers["x-realm"]??"athyper"),tenantId=await resolveTenantId(deps.db,String(req.headers["x-org"]??""),realm);if(!tenantId){res.status(400).json({error:"MISSING_TENANT"});return;}const tenantCode=String(req.params.tenantCode??"");if(tenantCode&&!await deps.db.selectFrom("master.tenant").select("id").where("id","=",tenantId).where("code","=",tenantCode).executeTakeFirst()){res.status(404).json({error:"TENANT_NOT_FOUND"});return;}const companyCode=String(req.params.companyCode??"");if(companyCode&&!await deps.db.selectFrom("master.company_code").select("id").where("tenant_id","=",tenantId).where("code","=",companyCode).executeTakeFirst()){res.status(404).json({error:"COMPANY_NOT_FOUND"});return;}let principalId:string|null=null;if(mutation){const sub=typeof claims.sub==="string"?claims.sub:"";principalId=sub?await resolvePrincipalIdWithJit(deps.db,sub,tenantId,realm,claims):null;if(!principalId){res.status(403).json({error:"PRINCIPAL_NOT_RESOLVED"});return;}}res.json(await runner({tenantId,principalId,req}));}catch(error){const e=error as Error&{status?:number;code?:string;details?:unknown};if(e instanceof FinancePaymentsError||typeof e.status==="number"){res.status(e.status??400).json({error:e.code??"PAYMENTS_SETUP_FAILED",message:e.message,details:e.details});return;}deps.logger?.error("finance_payments_setup_error",{err:String(error)});next(error);}};}

export function createFinancePaymentsSetupRoutes(router:Router,deps:FinanceRouteDeps){
 router.get("/finance/setup/tenant/:tenantCode/payment-terms",paymentsHandler(deps,false,({tenantId})=>loadPaymentTermDefinitions(deps.db,tenantId)));
 router.post("/finance/setup/tenant/:tenantCode/payment-terms",paymentsHandler(deps,true,({tenantId,principalId,req})=>savePaymentTerm(deps.db,{tenantId,actorId:principalId!,body:(req.body??{}) as Record<string,unknown>})));
 router.get("/finance/setup/company/:companyCode/payments",paymentsHandler(deps,false,({tenantId,req})=>loadCompanyPaymentsSetup(deps.db,tenantId,String(req.params.companyCode),typeof req.query.asOfDate==="string"?req.query.asOfDate:undefined)));
 router.post("/finance/setup/company/:companyCode/payments/policies",paymentsHandler(deps,true,({tenantId,principalId,req})=>savePaymentPolicy(deps.db,{tenantId,companyCode:String(req.params.companyCode),actorId:principalId!,body:(req.body??{}) as Record<string,unknown>})));
 router.post("/finance/setup/company/:companyCode/payments/interface-bindings",paymentsHandler(deps,true,({tenantId,principalId,req})=>saveInterfaceBinding(deps.db,{tenantId,companyCode:String(req.params.companyCode),actorId:principalId!,body:(req.body??{}) as Record<string,unknown>})));
 router.post("/finance/setup/company/:companyCode/payments/interface-trace",paymentsHandler(deps,false,async({tenantId,req})=>{const company=await deps.db.selectFrom("master.company_code").select("id").where("tenant_id","=",tenantId).where("code","=",String(req.params.companyCode)).executeTakeFirstOrThrow();const b=(req.body??{}) as Record<string,unknown>;return tracePaymentInterfaceRouting(deps.db,tenantId,{paymentMethodId:String(b.paymentMethodId),direction:String(b.direction??"OUTBOUND"),companyCodeId:company.id,bankAccountLinkId:typeof b.bankAccountLinkId==="string"?b.bankAccountLinkId:null,currencyCode:typeof b.currencyCode==="string"?b.currencyCode.toUpperCase():null,counterpartyCountryCode:typeof b.counterpartyCountryCode==="string"?b.counterpartyCountryCode.toUpperCase():null,paymentNetwork:typeof b.paymentNetwork==="string"?b.paymentNetwork:null,asOfDate:String(b.asOfDate??new Date().toISOString().slice(0,10))});}));
 router.post("/finance/setup/company/:companyCode/payments/settlement-rules",paymentsHandler(deps,true,({tenantId,principalId,req})=>saveSettlementRule(deps.db,{tenantId,companyCode:String(req.params.companyCode),actorId:principalId!,body:(req.body??{}) as Record<string,unknown>})));
}
