import type { Request,RequestHandler,Router } from "express";
import { resolvePrincipalIdWithJit,resolveTenantId,verifyBearer } from "@athyper/svc-shared";
import type { FinanceRouteDeps } from "./finance.route.js";
import { FinanceTaxError,loadCompanyTaxSetup,loadTaxDefinitions,saveOrganizationTaxRegistration,saveTaxGroupVersion,saveWhtThreshold,simulateTaxResolution } from "../services/finance-tax-setup.service.js";

type Context={tenantId:string;principalId:string|null;req:Request};type Runner=(context:Context)=>Promise<unknown>;
function taxHandler(deps:FinanceRouteDeps,mutation:boolean,runner:Runner):RequestHandler{return async(req,res,next)=>{try{const claims=await verifyBearer(req.headers.authorization??"",deps.auth,res);if(!claims)return;const realm=String(req.headers["x-realm"]??"athyper"),tenantId=await resolveTenantId(deps.db,String(req.headers["x-org"]??""),realm);if(!tenantId){res.status(400).json({error:"MISSING_TENANT"});return;}const tenantCode=String(req.params.tenantCode??"");if(tenantCode&&!await deps.db.selectFrom("master.tenant").select("id").where("id","=",tenantId).where("code","=",tenantCode).executeTakeFirst()){res.status(404).json({error:"TENANT_NOT_FOUND"});return;}const companyCode=String(req.params.companyCode??"");if(companyCode){const le=String(req.headers["x-legal-entity-id"]??"");const company=await deps.db.selectFrom("master.company_code").select("id").where("tenant_id","=",tenantId).where("code","=",companyCode).$if(Boolean(le),q=>q.where("legal_entity_id","=",le)).executeTakeFirst();if(!company){res.status(404).json({error:"COMPANY_NOT_FOUND"});return;}}let principalId:string|null=null;if(mutation){const sub=typeof claims.sub==="string"?claims.sub:"";principalId=sub?await resolvePrincipalIdWithJit(deps.db,sub,tenantId,realm,claims):null;if(!principalId){res.status(403).json({error:"PRINCIPAL_NOT_RESOLVED"});return;}}res.json(await runner({tenantId,principalId,req}));}catch(error){const e=error as Error&{status?:number;code?:string;details?:unknown};if(e instanceof FinanceTaxError||typeof e.status==="number"){res.status(e.status??400).json({error:e.code??"TAX_SETUP_FAILED",message:e.message,details:e.details});return;}deps.logger?.error("finance_tax_setup_error",{err:String(error)});next(error);}};}
export function createFinanceTaxSetupRoutes(router:Router,deps:FinanceRouteDeps){
 router.get("/finance/setup/company/:companyCode/tax",taxHandler(deps,false,({tenantId,req})=>loadCompanyTaxSetup(deps.db,tenantId,String(req.params.companyCode),typeof req.query.asOfDate==="string"?req.query.asOfDate:undefined)));
 router.post("/finance/setup/company/:companyCode/tax/simulate",taxHandler(deps,false,({tenantId,req})=>simulateTaxResolution(deps.db,tenantId,String(req.params.companyCode),(req.body??{}) as Record<string,unknown>)));
 router.post("/finance/setup/company/:companyCode/tax/registrations",taxHandler(deps,true,({tenantId,principalId,req})=>saveOrganizationTaxRegistration(deps.db,{tenantId,companyCode:String(req.params.companyCode),actorId:principalId!,body:(req.body??{}) as Record<string,unknown>})));
 router.get("/finance/setup/tenant/:tenantCode/tax/groups",taxHandler(deps,false,({tenantId,req})=>loadTaxDefinitions(deps.db,tenantId,typeof req.query.asOfDate==="string"?req.query.asOfDate:undefined)));
 router.post("/finance/setup/tenant/:tenantCode/tax/groups/versions",taxHandler(deps,true,({tenantId,principalId,req})=>saveTaxGroupVersion(deps.db,{tenantId,actorId:principalId!,body:(req.body??{}) as Record<string,unknown>})));
 router.post("/finance/setup/tenant/:tenantCode/tax/wht-thresholds",taxHandler(deps,true,({tenantId,principalId,req})=>saveWhtThreshold(deps.db,{tenantId,actorId:principalId!,body:(req.body??{}) as Record<string,unknown>})));
}
