import type {VerifiedRequestContext} from "@athyper/server-contract-auth";
import type {BusinessPartner360Section,BusinessPartner360SourceFreshness} from "./business-partner-360.js";

export interface BusinessPartner360Page<T>{readonly items:readonly T[];readonly nextCursor?:string;}
export interface BusinessPartner360IdentityItem{readonly kind:"canonical"|"classification"|"external_reference";readonly id:string;readonly code?:string;readonly displayName?:string;readonly legalName?:string;readonly aliases?:readonly string[];readonly category?:"organization"|"person";readonly ownershipClass?:string;readonly legalClassification?:string;readonly legalForm?:string;readonly registrationCountryCode?:string;readonly incorporationDate?:string;readonly websiteUrl?:string;readonly parent?:Readonly<{id:string;code:string;displayName:string}>;readonly lifecycleStatus?:string;readonly industryDomainCode?:string;readonly industryCodeId?:string;readonly assignmentKind?:string;readonly primary?:boolean;readonly verified?:boolean;readonly effectiveFrom?:string;readonly effectiveUntil?:string;readonly sourceSystemCode?:string;readonly externalEntityCode?:string;readonly externalId?:string;readonly externalCode?:string;}
export interface BusinessPartner360ContactItem{readonly id:string;readonly displayName:string;readonly businessTitle?:string;readonly departmentName?:string;readonly primary:boolean;readonly roles:readonly Readonly<{code:string;primary:boolean;effectiveFrom:string;effectiveUntil?:string}>[];readonly channels:readonly Readonly<{id:string;type:"email"|"phone"|"fax"|"sms"|"whatsapp"|"website";value:string;purpose:string;primary:boolean;verified:boolean;effectiveFrom:string;effectiveUntil?:string;quality?:string}>[];}
export interface BusinessPartner360AddressEventItem{readonly id:string;readonly eventType:string;readonly occurredAt:string;readonly resultStatus?:string;readonly confidence?:number;readonly reasonCode?:string;}
export interface BusinessPartner360AddressItem{readonly id:string;readonly purpose:string;readonly addressKind:string;readonly lines:readonly string[];readonly locality?:string;readonly region?:string;readonly postalCode?:string;readonly countryCode:string;readonly formattedAddress?:string;readonly primary:boolean;readonly validationStatus:string;readonly validationProvider?:string;readonly validationConfidence?:number;readonly validatedAt?:string;readonly effectiveFrom:string;readonly effectiveUntil?:string;readonly events:readonly BusinessPartner360AddressEventItem[];}
export interface BusinessPartner360IdentifierItem{readonly kind:"identifier"|"tax"|"external_reference";readonly id:string;readonly schemeCode?:string;readonly registrationTypeCode?:string;readonly issuingAuthority?:string;readonly issuingCountryCode?:string;readonly jurisdictionCode?:string;readonly sourceSystemCode?:string;readonly externalEntityCode?:string;readonly externalId?:string;readonly externalCode?:string;readonly maskedValue?:string;readonly primary:boolean;readonly verified:boolean;readonly effectiveFrom?:string;readonly effectiveUntil?:string;readonly revealable:boolean;}

export type BusinessPartner360IdentitySection=BusinessPartner360Section<BusinessPartner360Page<BusinessPartner360IdentityItem>>;
export type BusinessPartner360ContactsSection=BusinessPartner360Section<BusinessPartner360Page<BusinessPartner360ContactItem>>;
export type BusinessPartner360AddressesSection=BusinessPartner360Section<BusinessPartner360Page<BusinessPartner360AddressItem>>;
export type BusinessPartner360IdentifiersSection=BusinessPartner360Section<BusinessPartner360Page<BusinessPartner360IdentifierItem>>;

export interface BusinessPartner360TaxRevealCommand{readonly context:VerifiedRequestContext;readonly businessPartnerId:string;readonly taxRegistrationId:string;readonly purpose:string;readonly revealId:string;readonly purposeExpiresAt:string;}
export interface BusinessPartner360TaxRevealResult{readonly taxRegistrationId:string;readonly value:string;readonly expiresAt:string;readonly provenance:readonly BusinessPartner360SourceFreshness[];}
