import type{BusinessPartner360Section}from"./business-partner-360.js";
export interface BusinessPartner360EvidenceManifestItem{readonly id:string;readonly kind:string;readonly classification:string;readonly verificationStatus:string;readonly attachmentId?:string;readonly snapshotId?:string;readonly sourceReference?:string;readonly createdAt:string;readonly href:string;}
export interface BusinessPartner360MaterializationLink{readonly id:string;readonly childKind:string;readonly definitionFieldCode:string;readonly targetType:string;readonly targetId:string;readonly appliedAt:string;readonly href:string;}
export interface BusinessPartner360RequestHistoryItem{readonly id:string;readonly requestNo:string;readonly requestKind:string;readonly sourceKind:string;readonly requestedRole?:string;readonly status:string;readonly workflowRequestId?:string;readonly createdAt:string;readonly createdBy:string;readonly submittedAt?:string;readonly submittedBy?:string;readonly approvedAt?:string;readonly approvedBy?:string;readonly appliedAt?:string;readonly appliedBy?:string;readonly applicationResultKind?:string;readonly applicationReasonCode?:string;readonly evidence:readonly BusinessPartner360EvidenceManifestItem[];readonly materialization:readonly BusinessPartner360MaterializationLink[];readonly href:string;}
export interface BusinessPartner360RequestsData{readonly openWork:Readonly<{active:number;returned:number;pendingApproval:number;approved:number;failed:number}>;readonly items:readonly BusinessPartner360RequestHistoryItem[];readonly nextCursor?:string;}
export type BusinessPartner360ActivitySource="audit"|"request"|"lifecycle"|"address"|"bank"|"qualification"|"certification"|"workforce"|"mesh";
export interface BusinessPartner360GovernanceActivityItem{readonly id:string;readonly eventCode:string;readonly title:string;readonly occurredAt:string;readonly actorId?:string;readonly source:BusinessPartner360ActivitySource;readonly sourceService:string;readonly requestId?:string;readonly entityType:string;readonly entityId?:string;readonly outcome?:string;readonly changedFields:readonly string[];readonly evidenceHref?:string;}
export interface BusinessPartner360GovernanceActivityData{readonly items:readonly BusinessPartner360GovernanceActivityItem[];readonly nextCursor?:string;}
export type BusinessPartner360BusinessActivityProvider="procurement"|"finance"|"sales"|"projects"|"contracts";
export interface BusinessPartner360BusinessActivitySummary{readonly provider:BusinessPartner360BusinessActivityProvider;readonly state:"ready"|"empty"|"unavailable";readonly metrics:readonly Readonly<{code:string;label:string;value:number;unit?:string}>[];readonly href?:string;readonly reasonCode?:string;readonly observedAt:string;}
export interface BusinessPartner360BusinessActivityData{readonly providers:readonly BusinessPartner360BusinessActivitySummary[];}
export type BusinessPartner360RequestsSection=BusinessPartner360Section<BusinessPartner360RequestsData>;export type BusinessPartner360GovernanceActivitySection=BusinessPartner360Section<BusinessPartner360GovernanceActivityData>;export type BusinessPartner360BusinessActivitySection=BusinessPartner360Section<BusinessPartner360BusinessActivityData>;
