import type {BusinessPartner360Section} from "./business-partner-360.js";
export type BusinessPartner360ScopeState="global"|"missing_scope"|"scoped"|"historical";
export interface BusinessPartner360RoleSummaryItem{readonly id:string;readonly role:"supplier"|"customer";readonly roleCode?:string;readonly status:string;}
export interface BusinessPartner360OrganizationAssignmentItem{readonly displayValues?:Readonly<Record<string,string>>;readonly id:string;readonly operatingOrganizationId:string;readonly partnerRole:"supplier"|"customer";readonly status:string;readonly effectiveFrom:string;readonly effectiveUntil?:string;}
export interface BusinessPartner360LegalEntityAssignmentItem{readonly id:string;readonly legalEntityId:string;readonly effectiveFrom:string;readonly effectiveUntil?:string;}
export interface BusinessPartner360WorkAssignmentItem{readonly id:string;readonly employmentId?:string;readonly legalEntityId?:string;readonly companyCodeId:string;readonly orgUnitId?:string;readonly positionId?:string;readonly assignmentType:string;readonly fte:number;readonly effectiveFrom:string;readonly effectiveUntil?:string;}
export interface BusinessPartner360RolesScopeData{readonly scopeState:BusinessPartner360ScopeState;readonly readOnly:boolean;readonly roles:readonly BusinessPartner360RoleSummaryItem[];readonly organizationAssignments:readonly BusinessPartner360OrganizationAssignmentItem[];readonly legalEntityAssignments:readonly BusinessPartner360LegalEntityAssignmentItem[];}
export interface BusinessPartner360SupplierCompanyData{readonly scopeState:BusinessPartner360ScopeState;readonly readOnly:boolean;readonly supplier?:Readonly<{id:string;code:string;type:string;status:string}>;readonly organizationAssignment?:BusinessPartner360OrganizationAssignmentItem;readonly profile?:Readonly<{id:string;companyCodeId:string;currencyCode?:string;paymentTermId?:string;defaultAccountingProfileId?:string;defaultDimensionSetId?:string;preferredRemittanceBankLinkId?:string;status:string}>;}
export interface BusinessPartner360CustomerCompanyData{readonly scopeState:BusinessPartner360ScopeState;readonly readOnly:boolean;readonly customer?:Readonly<{id:string;code:string;type:string;status:string;designations:readonly Readonly<{id:string;type:string;priorityTier?:number;effectiveFrom:string;effectiveUntil?:string}>[]}>;readonly organizationAssignment?:BusinessPartner360OrganizationAssignmentItem;readonly profile?:Readonly<{id:string;companyCodeId:string;currencyCode?:string;paymentTermId?:string;defaultAccountingProfileId?:string;defaultDimensionSetId?:string;statementCycleCode?:string;status:string}>;}
export type BusinessPartner360RolesScopeSection=BusinessPartner360Section<BusinessPartner360RolesScopeData>;
export type BusinessPartner360SupplierCompanySection=BusinessPartner360Section<BusinessPartner360SupplierCompanyData>;
export type BusinessPartner360CustomerCompanySection=BusinessPartner360Section<BusinessPartner360CustomerCompanyData>;
