import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import { defineRouteContract, HttpError, registerContractRoute } from "@athyper/server-runtime-http";
import type { Application, RequestHandler, Response } from "express";
import { RecordServiceError } from "../errors.js";
import { parseEntityListScopeCoordinate } from "../entity-list-routes.js";
import type { RecordBookmarkService } from "./record-bookmark-service.js";

export function registerRecordBookmarkRoutes(application: Application, options: { readonly authenticate: RequestHandler; readonly readContext: (response: Response) => VerifiedRequestContext; readonly bookmarks: RecordBookmarkService }): void {
  registerContractRoute(application, contracts.list, options.authenticate, async (_request, response, next) => { try { noStore(response); response.json({ items: await options.bookmarks.list(options.readContext(response)) }); } catch (error) { next(asHttpError(error)); } });
  registerContractRoute(application, contracts.membership, options.authenticate, async (request, response, next) => { try { noStore(response); const ids = queryIds(request.query["recordId"]); const bookmarked = await options.bookmarks.membership(options.readContext(response), entityCode(request.params["entityCode"]), ids); response.json({ entityCode: entityCode(request.params["entityCode"]), bookmarkedRecordIds: [...bookmarked] }); } catch (error) { next(asHttpError(error)); } });
  registerContractRoute(application, contracts.add, options.authenticate, async (request, response, next) => { try { noStore(response); const body = request.body as Readonly<Record<string, unknown>>; const records = bodyRecords(body); const scope = parseEntityListScopeCoordinate(body); const changed = await options.bookmarks.add(options.readContext(response), entityCode(request.params["entityCode"]), records, scope); response.json({ operation: "add", recordIds: [...changed] }); } catch (error) { next(asHttpError(error)); } });
  registerContractRoute(application, contracts.remove, options.authenticate, async (request, response, next) => { try { noStore(response); const changed = await options.bookmarks.remove(options.readContext(response), entityCode(request.params["entityCode"]), bodyRecords(request.body as Readonly<Record<string, unknown>>).map((record) => record.id)); response.json({ operation: "remove", recordIds: [...changed] }); } catch (error) { next(asHttpError(error)); } });
}

const responseBody = { type: "object", additionalProperties: true } as const;
const record = { type: "object", additionalProperties: false, required: ["id"], properties: { id: { type: "string", format: "uuid" }, label: { type: "string", minLength: 1, maxLength: 240 } } } as const;
const scope = { companyCodeId: { type: "string", format: "uuid" }, legalEntityId: { type: "string", format: "uuid" }, operatingOrganizationId: { type: "string", format: "uuid" }, networkAccountId: { type: "string", format: "uuid" } } as const;
const mutationBody = { type: "object", additionalProperties: false, required: ["records"], properties: { records: { type: "array", minItems: 1, maxItems: 100, items: record }, ...scope } } as const;
const contracts = {
  list: defineRouteContract({ method: "get", path: "/api/record-bookmarks", operationId: "recordBookmarks.list", summary: "List the authenticated principal's record favourites", tags: ["Record favourites"], authenticated: true, responses: { 200: { description: "Record favourites", body: responseBody } } }),
  membership: defineRouteContract({ method: "get", path: "/api/record-bookmarks/:entityCode/membership", operationId: "recordBookmarks.membership", summary: "Resolve favourite membership for a visible page", tags: ["Record favourites"], authenticated: true, request: { query: { type: "object", additionalProperties: false, required: ["recordId"], properties: { recordId: { oneOf: [{ type: "string", format: "uuid" }, { type: "array", minItems: 1, maxItems: 100, items: { type: "string", format: "uuid" } }] } } } }, responses: { 200: { description: "Membership", body: responseBody } } }),
  add: defineRouteContract({ method: "put", path: "/api/record-bookmarks/:entityCode", operationId: "recordBookmarks.add", summary: "Idempotently add explicit record favourites", tags: ["Record favourites"], authenticated: true, request: { body: mutationBody }, responses: { 200: { description: "Added favourites", body: responseBody } } }),
  remove: defineRouteContract({ method: "delete", path: "/api/record-bookmarks/:entityCode", operationId: "recordBookmarks.remove", summary: "Idempotently remove explicit record favourites", tags: ["Record favourites"], authenticated: true, request: { body: mutationBody }, responses: { 200: { description: "Removed favourites", body: responseBody } } }),
} as const;
function noStore(response: Response) { response.setHeader("Cache-Control", "private, no-store"); }
function entityCode(value: string | string[] | undefined): string { const code = Array.isArray(value) ? value[0] : value; if (!code || !/^[a-z][a-z0-9_.-]{0,126}$/u.test(code)) throw new RecordServiceError(400, "INVALID_ENTITY_CODE", "entityCode must be a catalog code"); return code; }
function queryIds(value: unknown): readonly string[] { if (typeof value === "string") return [value]; if (Array.isArray(value) && value.every((id) => typeof id === "string")) return value; throw new RecordServiceError(400, "INVALID_BOOKMARK_RECORDS", "recordId is required"); }
function bodyRecords(body: Readonly<Record<string, unknown>>): readonly { readonly id: string; readonly label?: string }[] { if (!Array.isArray(body["records"])) throw new RecordServiceError(400, "INVALID_BOOKMARK_RECORDS", "records are required"); return body["records"].map((value) => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new RecordServiceError(400, "INVALID_BOOKMARK_RECORDS", "records are invalid"); const item = value as Record<string, unknown>; if (typeof item["id"] !== "string") throw new RecordServiceError(400, "INVALID_BOOKMARK_RECORDS", "record id is required"); return { id: item["id"], ...(typeof item["label"] === "string" ? { label: item["label"] } : {}) }; }); }
function asHttpError(error: unknown): unknown { return error instanceof RecordServiceError ? new HttpError(error.statusCode, error.code, error.message) : error; }
