import { describe, expect, it, vi } from "vitest";
import type { AtlasExperienceConfigurationRepository, AtlasExperienceDefinition, AtlasExperienceRelease } from "@athyper/server-contract-ai";
import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import { AtlasExperienceConfigurationService, validateAtlasExperienceDefinition } from "../experience-configuration.js";

const definition:AtlasExperienceDefinition={schema:"atlas-experience-definition/1",scope:"home",widgets:[{code:"home.recent",kind:"recent",title:"Recent",enabled:true,planes:["neon"],order:10},{code:"home.workspaces",kind:"workspaces",title:"Workspaces",enabled:true,planes:["studio"],order:20}],searchSources:[{code:"bp.records",kind:"record",label:"Partners",enabled:true,planes:["neon"],permissionCode:"records.business_partner.read",entityCode:"business_partner"}],prompts:[{code:"bp.find",label:"Find partner",prompt:"Find this business partner",enabled:true,planes:["neon"],agentCode:"bp-guide"}],agents:[{code:"bp-guide",name:"BP Guide",description:"Grounded Business Partner help",enabled:true,planes:["neon"],publicModelId:"atlas-fast",dataClass:"internal",promptRevision:"prompt-r1",toolCodes:["records_query"]}]};
const release:AtlasExperienceRelease={releaseId:"release-1",tenantId:"tenant-1",revision:3,status:"published",definition,contentHash:"a".repeat(64),createdAt:"2026-08-29T00:00:00.000Z",createdBy:"principal-1",publishedAt:"2026-08-29T01:00:00.000Z",publishedBy:"principal-1"};
const context:VerifiedRequestContext={planeKey:"neon",realmKey:"neon",tenantId:"tenant-1",principalId:"principal-1",authEpoch:1,requestId:"request-1",profileHash:"profile-1",permissions:{planeKey:"neon",tenantId:"tenant-1",principalId:"principal-1",principalFingerprint:"p",profileHash:"profile-1",schemaHash:"s",resolvedAt:1,allowed:["records.business_partner.read"],denied:[],planLocked:[],planeExcluded:[],entries:[],authorizationScopes:[]}};

describe("Atlas Studio experience configuration",()=>{
  it("returns only the current plane and permission-filtered published projection",async()=>{const repository={getPublished:vi.fn(async()=>release)} as unknown as AtlasExperienceConfigurationRepository;const result=await new AtlasExperienceConfigurationService(repository).resolve(context);expect(result).toMatchObject({schema:"atlas-experience-projection/1",revision:3,widgets:[{code:"home.recent"}],searchSources:[{code:"bp.records"}],agents:[{code:"bp-guide"}]});expect(result?.widgets).toHaveLength(1);});
  it("keeps authoring in Studio and rejects invalid agent references",async()=>{const repository={saveDraft:vi.fn()} as unknown as AtlasExperienceConfigurationRepository;const service=new AtlasExperienceConfigurationService(repository);await expect(service.saveDraft(context,definition)).rejects.toThrow(/owned by Studio/i);expect(()=>validateAtlasExperienceDefinition({...definition,prompts:[{...definition.prompts[0]!,agentCode:"missing"}]})).toThrow(/unknown agent/i);});
});
