import {describe,expect,it}from"vitest";
import type{AtlasBeginRunInput,AtlasModelBinding,AtlasModelProvider,AtlasRun,AtlasRunRepository,AtlasThread,AtlasThreadRepository,AtlasUsageLedgerEntry}from"@athyper/server-contract-ai";
import type{VerifiedRequestContext}from"@athyper/server-contract-auth";
import{AtlasAgentRuntime,AtlasBindingRegistry,AtlasProviderRegistry,AtlasThreadService}from"../index.js";

const context={planeKey:"neon",realmKey:"neon",tenantId:"tenant-1",principalId:"principal-1",authEpoch:1,requestId:"request-1",profileHash:"p",permissions:{planeKey:"neon",tenantId:"tenant-1",principalId:"principal-1",principalFingerprint:"f",profileHash:"p",schemaHash:"s",resolvedAt:1,allowed:[],denied:[],planLocked:[],planeExcluded:[],entries:[],authorizationScopes:[]}}as VerifiedRequestContext;
const thread={threadId:"thread-1",tenantId:"tenant-1",planeKey:"neon",ownerPrincipalId:"principal-1",title:null,status:"active",participants:[],rowVersion:1,lastMessageSequence:0,retention:{policyId:"r",expiresAt:null,purgeAfter:null,legalHold:false},createdAt:"2026-08-12T00:00:00Z",updatedAt:"2026-08-12T00:00:00Z"}as AtlasThread;
const primary={bindingId:"primary",bindingRevision:"1",publicModelId:"atlas-fast",providerId:"openai",upstreamModelId:"primary-model",adapterId:"primary-adapter",adapterVersion:"1",displayTier:"fast",exposure:"product",status:"available",capabilities:{streaming:true,tools:false,vision:false,structuredOutput:true,maxContextTokens:1000,maxOutputTokens:100},credentialPolicy:"platform",credentialOwnerId:"primary-owner",providerRegion:"global",dataHandlingProfileId:"safe",routingPolicyId:"ordered-failover-v1",fallbackBindingIds:["fallback"],allowedDataClasses:["internal"],priceVersion:"1",inputPricePerMtokUsd:1,outputPricePerMtokUsd:1}as AtlasModelBinding;
const fallback={...primary,bindingId:"fallback",providerId:"anthropic",upstreamModelId:"fallback-model",adapterId:"fallback-adapter",credentialOwnerId:"fallback-owner",exposure:"internal_evaluation",routingPolicyId:"no-fallback-v1",fallbackBindingIds:undefined}as AtlasModelBinding;

describe("Atlas provider failover",()=>{it("uses the ordered fallback only for a retryable pre-content failure and meters both calls",async()=>{
  const calls:string[]=[];const failed:AtlasModelProvider={providerId:"openai",adapterId:"primary-adapter",adapterVersion:"1",async*invoke(){calls.push("primary");yield{kind:"failed",error:{errorClass:"overloaded",code:"busy",safeMessage:"busy",retryable:true}};}};const succeeded:AtlasModelProvider={providerId:"anthropic",adapterId:"fallback-adapter",adapterVersion:"1",async*invoke(){calls.push("fallback");yield{kind:"response_started",providerRequestId:"p2",actualModelId:"fallback-model"};yield{kind:"text_delta",text:"ok"};yield{kind:"usage",mode:"snapshot",final:true,usage:{inputTokens:2,outputTokens:1}};yield{kind:"completed",reason:"stop"};}};
  const repository:AtlasThreadRepository={create:async()=>thread,list:async()=>({items:[thread],nextCursor:null}),get:async()=>thread,listMessages:async()=>({items:[],nextCursor:null}),rename:async()=>thread,archive:async()=>thread,softDelete:async()=>true,putParticipant:async()=>thread,revokeParticipant:async()=>thread};const threads=new AtlasThreadService({repository,authorizer:{authorize:async()=>true},retention:{resolve:async()=>({policyId:"r",retentionDays:1,displayText:"1 day"})},maxHistoryMessages:5,maxHistoryBytes:1000,maxExportMessages:10});
  let stored:AtlasRun|null=null;const runs:AtlasRunRepository={begin:async(input:AtlasBeginRunInput)=>{stored={runId:input.runId,threadId:input.threadId,tenantId:input.context.tenantId,planeKey:input.context.planeKey,principalId:input.context.principalId,clientRequestId:input.clientRequestId,inputMessageId:input.inputMessageId,outputMessageId:input.outputMessageId,status:"started",publicModelId:input.publicModelId,bindingId:input.bindingId,bindingRevision:input.bindingRevision,policyRevision:input.policyRevision,promptRevision:input.promptRevision,startedAt:input.startedAt,terminalAt:null,terminalErrorClass:null};return{replayed:false,run:stored};},get:async()=>stored,complete:async input=>{stored=stored?{...stored,status:"completed",terminalAt:input.completedAt}:null;return stored;},fail:async()=>stored,cancel:async()=>stored};
  const ledger:AtlasUsageLedgerEntry[]=[];let id=0;const runtime=new AtlasAgentRuntime({admission:{resolve:async()=>({schema:"atlas-plane-admission/1",planeKey:"neon",chatAllowed:true,persistenceAllowed:true,readToolsAllowed:false,mutationToolsAllowed:false,invoiceExtractionAllowed:false,allowedPublicModelIds:["atlas-fast"],allowedDataClasses:["internal"],policyRevision:"admit"})},modelPolicy:{evaluate:async()=>({allowed:true,policyRevision:"policy",promptRevision:"prompt"})},bindings:new AtlasBindingRegistry([primary,fallback]),providers:new AtlasProviderRegistry([failed,succeeded]),credentials:{resolve:async({binding})=>({secret:"secret",credentialId:`c-${binding.bindingId}`,credentialRevision:"1",ownerId:binding.credentialOwnerId})},threads,runs,ledger:{append:async value=>{ledger.push(value);}},prompts:{resolve:async()=>({revision:"prompt",systemText:"system"})},maxInputCharacters:100,maxToolRounds:0,createId:()=>`id-${++id}`,now:()=>new Date("2026-08-12T00:00:00Z")});
  const events=[];for await(const event of runtime.run({context,threadId:"thread-1",clientRequestId:"client-1",publicModelId:"atlas-fast",dataClass:"internal",userText:"question",catalogPolicyRevision:"admit"}))events.push(event);
  expect(calls).toEqual(["primary","fallback"]);expect(events.at(-1)?.event.type).toBe("run.completed");expect(ledger.map(value=>value.bindingId)).toEqual(["primary","fallback"]);expect(stored).toMatchObject({status:"completed"});
});});
