CREATE TRIGGER authorization_parity_certification_immutable
BEFORE UPDATE OR DELETE ON ops.authorization_parity_certification
FOR EACH ROW EXECUTE FUNCTION ops.trg_guard_authorization_parity_certification();

CREATE TRIGGER authorization_operation_rollout_guard
BEFORE INSERT OR UPDATE OR DELETE ON ops.authorization_operation_rollout
FOR EACH ROW EXECUTE FUNCTION ops.trg_guard_authorization_rollout_write();

CREATE TRIGGER authorization_operation_cutover_drill_immutable
BEFORE UPDATE OR DELETE ON ops.authorization_operation_cutover_drill
FOR EACH ROW EXECUTE FUNCTION ops.trg_guard_authorization_operation_cutover_drill();
CREATE TRIGGER authorization_legacy_retirement_approval_immutable
BEFORE UPDATE OR DELETE ON ops.authorization_legacy_retirement_approval
FOR EACH ROW EXECUTE FUNCTION ops.trg_guard_authorization_operation_cutover_drill();
