import {ContentExtractionError,type ContentExtractionInput,type ContentExtractionResult,type ContentExtractor} from "@athyper/server-contract-content-extraction";

export interface TikaContentExtractorConfig {readonly baseUrl:string;readonly timeoutMs?:number;readonly maxInputBytes?:number;readonly maxTextChars?:number;readonly fetch?:typeof globalThis.fetch;}
export interface TikaHealth {readonly status:"healthy"|"unhealthy";readonly message?:string;}
export interface TikaContentExtractor extends ContentExtractor {health():Promise<TikaHealth>;close():void;}

export function createTikaContentExtractor(config:TikaContentExtractorConfig):TikaContentExtractor{
  if(!/^https?:\/\//.test(config.baseUrl))throw new Error("Tika baseUrl must be HTTP(S)");
  const baseUrl=config.baseUrl.replace(/\/+$/g,"");const timeoutMs=positive(config.timeoutMs,120_000,"timeoutMs");const maxInputBytes=positive(config.maxInputBytes,50*1_024*1_024,"maxInputBytes");const maxTextChars=positive(config.maxTextChars,5_000_000,"maxTextChars");const request=config.fetch??globalThis.fetch;const active=new Set<AbortController>();
  async function call(path:string,init:RequestInit,outer?:AbortSignal):Promise<Response>{const controller=new AbortController();active.add(controller);const onAbort=()=>controller.abort();outer?.addEventListener("abort",onAbort,{once:true});const timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await request(`${baseUrl}${path}`,{...init,signal:controller.signal});}catch(error){if(controller.signal.aborted)throw new ContentExtractionError("EXTRACTION_TIMEOUT",`Tika request exceeded ${timeoutMs} ms`,{cause:error});throw new ContentExtractionError("EXTRACTION_UNAVAILABLE","Tika request failed",{cause:error});}finally{clearTimeout(timer);outer?.removeEventListener("abort",onAbort);active.delete(controller);}}
  return {async extract(input:ContentExtractionInput):Promise<ContentExtractionResult>{if(input.content.byteLength>maxInputBytes)throw new ContentExtractionError("EXTRACTION_SIZE_LIMIT",`Content exceeds ${maxInputBytes} bytes`);const started=Date.now();const response=await call("/tika",{method:"PUT",headers:{accept:"text/plain; charset=UTF-8","content-type":input.contentType,...(input.fileName?{"content-disposition":`attachment; filename*=UTF-8''${encodeURIComponent(input.fileName)}`}:{})},body:Uint8Array.from(input.content).buffer},input.signal);if(!response.ok){const detail=(await response.text().catch(()=>"")).slice(0,300);throw new ContentExtractionError("EXTRACTION_FAILED",`Tika returned ${response.status}${detail?`: ${detail}`:""}`);}const raw=await response.text();const text=raw.replace(/\u0000/g,"").trim().slice(0,maxTextChars);const metadata:Record<string,string>={};response.headers.forEach((value,key)=>{if(key.startsWith("x-tika-")||key==="content-type")metadata[key]=value;});return {text,metadata,provider:"apache-tika",durationMs:Date.now()-started,...(metadata["content-type"]?{detectedContentType:metadata["content-type"]}:{})};},async health(){try{const response=await call("/",{method:"GET"});return response.ok?{status:"healthy"}:{status:"unhealthy",message:`Tika health returned ${response.status}`};}catch(error){return {status:"unhealthy",message:error instanceof Error?error.message:String(error)};}},close(){for(const controller of active)controller.abort();active.clear();}};
}
function positive(value:number|undefined,fallback:number,name:string){const resolved=value??fallback;if(!Number.isInteger(resolved)||resolved<1)throw new Error(`Tika ${name} must be a positive integer`);return resolved;}
