-- First desired-state movement wave from the legacy Neon document catalogue.

CREATE TABLE document.asset_transaction (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    code text NOT NULL DEFAULT '', name text NOT NULL DEFAULT '', company_code_id uuid NOT NULL,
    asset_id uuid NOT NULL, asset_book_id uuid, book_type text,
    txn_type document.asset_transaction_type_d NOT NULL,
    amount numeric(18,4) NOT NULL, currency_code character(3) NOT NULL DEFAULT 'USD',
    effective_date date NOT NULL, fiscal_year smallint NOT NULL, period_number smallint NOT NULL,
    from_values jsonb, to_values jsonb, reference_je_id uuid,
    depreciation_run_id uuid, depreciation_run_line_id uuid,
    reversal_of_id uuid, is_reversal boolean NOT NULL DEFAULT false,
    performed_by uuid NOT NULL, performed_at timestamptz NOT NULL DEFAULT now(), notes text,
    posted_at timestamptz, posted_by uuid, tags jsonb NOT NULL DEFAULT '[]'::jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.asset_transaction_status_d NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft','posted')) STORED,
    status_changed_at timestamptz, status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT asset_transaction_pkey PRIMARY KEY(id),
    CONSTRAINT asset_transaction_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT asset_transaction_amount_chk CHECK(amount >= 0),
    CONSTRAINT asset_transaction_period_chk CHECK(period_number BETWEEN 1 AND 16),
    CONSTRAINT asset_transaction_reversal_chk CHECK((NOT is_reversal AND reversal_of_id IS NULL) OR (is_reversal AND reversal_of_id IS NOT NULL)),
    CONSTRAINT asset_transaction_self_chk CHECK(reversal_of_id IS DISTINCT FROM id),
    CONSTRAINT asset_transaction_json_chk CHECK((from_values IS NULL OR jsonb_typeof(from_values)='object') AND (to_values IS NULL OR jsonb_typeof(to_values)='object') AND jsonb_typeof(tags)='array' AND jsonb_typeof(metadata)='object'),
    CONSTRAINT asset_transaction_post_pair_chk CHECK((posted_at IS NULL)=(posted_by IS NULL)),
    CONSTRAINT asset_transaction_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT asset_transaction_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

COMMENT ON COLUMN document.asset_transaction.book_type IS
  'Compatibility cache of master.ledger_book.category. asset_book_id remains authoritative.';

CREATE TABLE document.fx_revaluation_run (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    company_code_id uuid NOT NULL, book_id uuid NOT NULL,
    fiscal_year smallint NOT NULL, period_number smallint NOT NULL,
    revaluation_date date NOT NULL, posting_date date,
    rate_type_used text NOT NULL DEFAULT 'PERIOD_END', rate_source document.fx_rate_source_d NOT NULL DEFAULT 'MANUAL',
    functional_currency character(3) NOT NULL,
    total_unrealized_gain numeric(18,4) NOT NULL DEFAULT 0, total_unrealized_loss numeric(18,4) NOT NULL DEFAULT 0,
    net_amount numeric(18,4) GENERATED ALWAYS AS (total_unrealized_gain-total_unrealized_loss) STORED,
    line_count integer NOT NULL DEFAULT 0, revaluation_je_id uuid, reversal_je_id uuid,
    is_auto_reversed boolean NOT NULL DEFAULT true, auto_reverse_date date, idempotency_key text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.fx_revaluation_run_status_d NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft','calculated','posted')) STORED,
    status_changed_at timestamptz, status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT fx_revaluation_run_pkey PRIMARY KEY(id),
    CONSTRAINT fx_revaluation_run_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT fx_revaluation_run_gain_chk CHECK(total_unrealized_gain>=0),
    CONSTRAINT fx_revaluation_run_loss_chk CHECK(total_unrealized_loss>=0),
    CONSTRAINT fx_revaluation_run_line_count_chk CHECK(line_count>=0),
    CONSTRAINT fx_revaluation_run_period_chk CHECK(period_number BETWEEN 1 AND 16),
    CONSTRAINT fx_revaluation_run_reverse_chk CHECK(NOT is_auto_reversed OR auto_reverse_date IS NOT NULL),
    CONSTRAINT fx_revaluation_run_je_chk CHECK(revaluation_je_id IS DISTINCT FROM reversal_je_id),
    CONSTRAINT fx_revaluation_run_metadata_chk CHECK(jsonb_typeof(metadata)='object'),
    CONSTRAINT fx_revaluation_run_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT fx_revaluation_run_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.intercompany_agreement (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    code text NOT NULL DEFAULT '', name text NOT NULL DEFAULT '', company_code_id uuid NOT NULL,
    agreement_number text NOT NULL, source_company_code_id uuid NOT NULL, dest_company_code_id uuid NOT NULL,
    agreement_type document.intercompany_agreement_type_d NOT NULL, description text,
    transfer_pricing_method document.transfer_pricing_method_d NOT NULL,
    markup_pct numeric(7,4), arm_length_basis text, currency_code character(3) NOT NULL,
    base_currency_code character(3), annual_value numeric(18,4), total_value numeric(18,4),
    effective_from date NOT NULL, effective_to date, priority smallint NOT NULL DEFAULT 0,
    conflict_strategy document.intercompany_conflict_strategy_d NOT NULL DEFAULT 'HIGHEST_PRIORITY',
    version smallint NOT NULL DEFAULT 1, supersedes_id uuid,
    cost_center_id uuid, profit_center_id uuid, project_id uuid, site_id uuid, dimension_set_id uuid,
    agreement_owner_id uuid, approved_at timestamptz, approved_by uuid, workflow_request_id uuid,
    tags jsonb NOT NULL DEFAULT '[]'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.intercompany_agreement_status_d NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft','active')) STORED,
    status_changed_at timestamptz, status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT intercompany_agreement_pkey PRIMARY KEY(id),
    CONSTRAINT intercompany_agreement_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT intercompany_agreement_number_uq UNIQUE(tenant_id,company_code_id,agreement_number),
    CONSTRAINT intercompany_agreement_number_chk CHECK(btrim(agreement_number)<>''),
    CONSTRAINT intercompany_agreement_company_chk CHECK(source_company_code_id<>dest_company_code_id),
    CONSTRAINT intercompany_agreement_dates_chk CHECK(effective_to IS NULL OR effective_to>=effective_from),
    CONSTRAINT intercompany_agreement_markup_chk CHECK(markup_pct IS NULL OR markup_pct BETWEEN -100 AND 1000),
    CONSTRAINT intercompany_agreement_priority_chk CHECK(priority>=0),
    CONSTRAINT intercompany_agreement_version_chk CHECK(version>=1),
    CONSTRAINT intercompany_agreement_self_chk CHECK(supersedes_id IS DISTINCT FROM id),
    CONSTRAINT intercompany_agreement_json_chk CHECK(jsonb_typeof(tags)='array' AND jsonb_typeof(metadata)='object'),
    CONSTRAINT intercompany_agreement_approval_pair_chk CHECK((approved_at IS NULL)=(approved_by IS NULL)),
    CONSTRAINT intercompany_agreement_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT intercompany_agreement_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.intercompany_transaction (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    code text NOT NULL DEFAULT '', name text NOT NULL DEFAULT '', company_code_id uuid NOT NULL,
    ic_txn_number text NOT NULL, source_company_code_id uuid NOT NULL, dest_company_code_id uuid NOT NULL,
    txn_type document.intercompany_transaction_type_d NOT NULL,
    document_date date NOT NULL, posting_date date NOT NULL, currency_code character(3) NOT NULL,
    amount numeric(18,4) NOT NULL, agreement_id uuid, transfer_price numeric(18,4), arm_length_price numeric(18,4),
    pricing_variance numeric(18,4) GENERATED ALWAYS AS (transfer_price-arm_length_price) STORED,
    base_currency_code character(3) NOT NULL, exchange_rate numeric(18,10), base_amount numeric(18,4),
    source_je_id uuid, dest_je_id uuid, mirror_txn_id uuid, is_mirror boolean NOT NULL DEFAULT false,
    match_status document.intercompany_match_status_d NOT NULL DEFAULT 'UNMATCHED',
    matched_at timestamptz, discrepancy_amount numeric(18,4), discrepancy_reason text,
    netting_batch_id uuid, fiscal_year smallint NOT NULL, period_number smallint,
    cost_center_id uuid, profit_center_id uuid, project_id uuid, site_id uuid, dimension_set_id uuid,
    description text, tags jsonb NOT NULL DEFAULT '[]'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.intercompany_transaction_status_d NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft','created','posted','netted')) STORED,
    status_changed_at timestamptz, status_changed_by uuid, posted_at timestamptz, posted_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT intercompany_transaction_pkey PRIMARY KEY(id),
    CONSTRAINT intercompany_transaction_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT intercompany_transaction_number_uq UNIQUE(tenant_id,company_code_id,ic_txn_number),
    CONSTRAINT intercompany_transaction_number_chk CHECK(btrim(ic_txn_number)<>''),
    CONSTRAINT intercompany_transaction_amount_chk CHECK(amount>0),
    CONSTRAINT intercompany_transaction_dates_chk CHECK(document_date<=posting_date),
    CONSTRAINT intercompany_transaction_company_chk CHECK(source_company_code_id<>dest_company_code_id),
    CONSTRAINT intercompany_transaction_fx_chk CHECK(currency_code=base_currency_code OR exchange_rate>0),
    CONSTRAINT intercompany_transaction_period_chk CHECK(period_number IS NULL OR period_number BETWEEN 1 AND 16),
    CONSTRAINT intercompany_transaction_mirror_chk CHECK(mirror_txn_id IS DISTINCT FROM id),
    CONSTRAINT intercompany_transaction_json_chk CHECK(jsonb_typeof(tags)='array' AND jsonb_typeof(metadata)='object'),
    CONSTRAINT intercompany_transaction_post_pair_chk CHECK((posted_at IS NULL)=(posted_by IS NULL)),
    CONSTRAINT intercompany_transaction_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT intercompany_transaction_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.ic_elimination (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    code text NOT NULL DEFAULT '', name text NOT NULL DEFAULT '', company_code_id uuid NOT NULL,
    elimination_code text NOT NULL, source_company_code_id uuid NOT NULL, counterparty_company_code_id uuid NOT NULL,
    elimination_type document.ic_elimination_type_d NOT NULL, consolidation_group text NOT NULL,
    book_id uuid NOT NULL, fiscal_year smallint NOT NULL, period_number smallint NOT NULL,
    elimination_date date NOT NULL, posting_date date NOT NULL, elimination_amount numeric(18,4) NOT NULL,
    currency_code character(3) NOT NULL, functional_currency_code character(3) NOT NULL,
    exchange_rate numeric(18,10), functional_amount numeric(18,4), line_count smallint NOT NULL DEFAULT 0,
    ic_transaction_id uuid, je_id uuid, reversal_je_id uuid,
    decision_score numeric(5,4), approval_route document.ic_approval_route_d NOT NULL DEFAULT 'STANDARD',
    tags jsonb NOT NULL DEFAULT '[]'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.ic_elimination_status_d NOT NULL DEFAULT 'calculated',
    is_active boolean GENERATED ALWAYS AS (status IN ('calculated','approved','posted')) STORED,
    status_changed_at timestamptz, status_changed_by uuid,
    approved_at timestamptz, approved_by uuid, posted_at timestamptz, posted_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT ic_elimination_pkey PRIMARY KEY(id),
    CONSTRAINT ic_elimination_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT ic_elimination_code_uq UNIQUE(tenant_id,company_code_id,elimination_code),
    CONSTRAINT ic_elimination_code_chk CHECK(btrim(elimination_code)<>''),
    CONSTRAINT ic_elimination_amount_chk CHECK(elimination_amount>0),
    CONSTRAINT ic_elimination_company_chk CHECK(source_company_code_id<>counterparty_company_code_id),
    CONSTRAINT ic_elimination_dates_chk CHECK(elimination_date<=posting_date),
    CONSTRAINT ic_elimination_fx_chk CHECK(currency_code=functional_currency_code OR exchange_rate>0),
    CONSTRAINT ic_elimination_period_chk CHECK(period_number BETWEEN 1 AND 16),
    CONSTRAINT ic_elimination_score_chk CHECK(decision_score IS NULL OR decision_score BETWEEN 0 AND 1),
    CONSTRAINT ic_elimination_je_chk CHECK(je_id IS DISTINCT FROM reversal_je_id),
    CONSTRAINT ic_elimination_json_chk CHECK(jsonb_typeof(tags)='array' AND jsonb_typeof(metadata)='object'),
    CONSTRAINT ic_elimination_approval_pair_chk CHECK((approved_at IS NULL)=(approved_by IS NULL)),
    CONSTRAINT ic_elimination_post_pair_chk CHECK((posted_at IS NULL)=(posted_by IS NULL)),
    CONSTRAINT ic_elimination_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT ic_elimination_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.match_exception (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    invoice_match_case_id uuid NOT NULL, invoice_line_id uuid NOT NULL,
    exception_type document.match_exception_type_d NOT NULL, exception_subtype text,
    expected_value numeric(18,4), actual_value numeric(18,4), variance_amount numeric(18,4) NOT NULL,
    variance_pct numeric(7,4), currency_code character(3) NOT NULL,
    tolerance_pct numeric(5,2), tolerance_amount numeric(18,4), is_within_tolerance boolean NOT NULL DEFAULT false,
    resolution_type document.match_exception_resolution_d, resolution_notes text,
    resolved_by uuid, resolved_at timestamptz, workflow_request_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.match_exception_status_d NOT NULL DEFAULT 'open',
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT match_exception_pkey PRIMARY KEY(id),
    CONSTRAINT match_exception_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT match_exception_resolved_pair_chk CHECK((resolved_by IS NULL)=(resolved_at IS NULL)),
    CONSTRAINT match_exception_tolerance_chk CHECK((tolerance_pct IS NULL OR tolerance_pct BETWEEN 0 AND 100) AND (tolerance_amount IS NULL OR tolerance_amount>=0)),
    CONSTRAINT match_exception_metadata_chk CHECK(jsonb_typeof(metadata)='object'),
    CONSTRAINT match_exception_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.netting_batch (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    code text NOT NULL DEFAULT '', name text NOT NULL DEFAULT '', company_code_id uuid NOT NULL,
    batch_number text NOT NULL, company_code_a_id uuid NOT NULL, company_code_b_id uuid NOT NULL,
    batch_date date NOT NULL, cut_off_date date NOT NULL, settlement_date date,
    currency_code character(3) NOT NULL,
    gross_amount_a_to_b numeric(18,4) NOT NULL DEFAULT 0, gross_amount_b_to_a numeric(18,4) NOT NULL DEFAULT 0,
    gross_amount numeric(18,4) GENERATED ALWAYS AS (gross_amount_a_to_b+gross_amount_b_to_a) STORED,
    net_amount numeric(18,4) NOT NULL DEFAULT 0, net_direction document.netting_direction_d NOT NULL DEFAULT 'ZERO',
    txn_count integer NOT NULL DEFAULT 0, settlement_je_id uuid,
    fiscal_year smallint NOT NULL, period_number smallint, idempotency_key text,
    tags jsonb NOT NULL DEFAULT '[]'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.netting_batch_status_d NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft','calculated','approved')) STORED,
    status_changed_at timestamptz, status_changed_by uuid,
    settled_at timestamptz, settled_by uuid, approved_at timestamptz, approved_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT netting_batch_pkey PRIMARY KEY(id),
    CONSTRAINT netting_batch_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT netting_batch_number_uq UNIQUE(tenant_id,company_code_id,batch_number),
    CONSTRAINT netting_batch_number_chk CHECK(btrim(batch_number)<>''),
    CONSTRAINT netting_batch_company_chk CHECK(company_code_a_id<>company_code_b_id),
    CONSTRAINT netting_batch_cutoff_chk CHECK(cut_off_date<=batch_date),
    CONSTRAINT netting_batch_settlement_chk CHECK(settlement_date IS NULL OR settlement_date>=batch_date),
    CONSTRAINT netting_batch_amount_chk CHECK(gross_amount_a_to_b>=0 AND gross_amount_b_to_a>=0 AND net_amount>=0),
    CONSTRAINT netting_batch_count_chk CHECK(txn_count>=0),
    CONSTRAINT netting_batch_period_chk CHECK(period_number IS NULL OR period_number BETWEEN 1 AND 16),
    CONSTRAINT netting_batch_json_chk CHECK(jsonb_typeof(tags)='array' AND jsonb_typeof(metadata)='object'),
    CONSTRAINT netting_batch_settled_pair_chk CHECK((settled_at IS NULL)=(settled_by IS NULL)),
    CONSTRAINT netting_batch_approved_pair_chk CHECK((approved_at IS NULL)=(approved_by IS NULL)),
    CONSTRAINT netting_batch_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT netting_batch_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.obligation_horizon (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    commitment_id uuid NOT NULL, schedule_id uuid, fiscal_year smallint NOT NULL,
    period_from smallint NOT NULL DEFAULT 1, period_to smallint NOT NULL DEFAULT 12,
    obligation_tier document.obligation_tier_d NOT NULL DEFAULT 'PLANNED',
    amount numeric(18,4) NOT NULL, original_amount numeric(18,4), currency_code character(3) NOT NULL,
    fp_id uuid, intent_id uuid, company_code_id uuid,
    spread_method document.obligation_spread_method_d NOT NULL DEFAULT 'EVEN', period_amounts jsonb,
    confidence numeric(3,2) NOT NULL DEFAULT 1.00,
    source_type document.obligation_source_type_d NOT NULL DEFAULT 'CONTRACT',
    escalation_formula jsonb, escalation_applied_at timestamptz,
    contract_currency_code character(3), contract_amount numeric(18,4), exchange_rate numeric(12,6), rate_type text,
    retention_pct numeric(5,2), retention_release_date date, amendment_count smallint NOT NULL DEFAULT 0,
    variance_to_original numeric(18,4) GENERATED ALWAYS AS (amount-original_amount) STORED,
    promoted_at timestamptz, reserved_at timestamptz, funding_txn_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.obligation_horizon_status_d NOT NULL DEFAULT 'active',
    is_active boolean GENERATED ALWAYS AS (status='active') STORED,
    status_changed_at timestamptz, status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT obligation_horizon_pkey PRIMARY KEY(id),
    CONSTRAINT obligation_horizon_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT obligation_horizon_amount_chk CHECK(amount>=0),
    CONSTRAINT obligation_horizon_original_chk CHECK(original_amount IS NULL OR original_amount>=0),
    CONSTRAINT obligation_horizon_period_chk CHECK(period_from BETWEEN 1 AND 12 AND period_to BETWEEN period_from AND 12),
    CONSTRAINT obligation_horizon_confidence_chk CHECK(confidence BETWEEN 0 AND 1),
    CONSTRAINT obligation_horizon_retention_chk CHECK(retention_pct IS NULL OR retention_pct BETWEEN 0 AND 100),
    CONSTRAINT obligation_horizon_amendment_chk CHECK(amendment_count>=0),
    CONSTRAINT obligation_horizon_period_amounts_chk CHECK(period_amounts IS NULL OR jsonb_typeof(period_amounts)='object'),
    CONSTRAINT obligation_horizon_escalation_chk CHECK(escalation_formula IS NULL OR jsonb_typeof(escalation_formula)='object'),
    CONSTRAINT obligation_horizon_metadata_chk CHECK(jsonb_typeof(metadata)='object'),
    CONSTRAINT obligation_horizon_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT obligation_horizon_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.payment_remittance_output (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL, company_code_id uuid NOT NULL,
    remittance_number text NOT NULL, payment_entry_id uuid NOT NULL, supplier_id uuid NOT NULL,
    currency_code character(3) NOT NULL, total_amount numeric(18,4) NOT NULL, net_remitted numeric(18,4) NOT NULL,
    delivery_method document.remittance_delivery_method_d NOT NULL DEFAULT 'EMAIL',
    delivered_at timestamptz, delivery_status document.remittance_delivery_status_d NOT NULL DEFAULT 'pending',
    render_output_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status document.payment_remittance_status_d NOT NULL DEFAULT 'draft',
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT payment_remittance_output_pkey PRIMARY KEY(id),
    CONSTRAINT payment_remittance_output_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT payment_remittance_output_number_uq UNIQUE(tenant_id,company_code_id,remittance_number),
    CONSTRAINT payment_remittance_output_number_chk CHECK(btrim(remittance_number)<>''),
    CONSTRAINT payment_remittance_output_amount_chk CHECK(total_amount>=0 AND net_remitted>=0 AND net_remitted<=total_amount),
    CONSTRAINT payment_remittance_output_delivery_chk CHECK(delivery_status<>'delivered' OR delivered_at IS NOT NULL),
    CONSTRAINT payment_remittance_output_metadata_chk CHECK(jsonb_typeof(metadata)='object'),
    CONSTRAINT payment_remittance_output_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.payment_term_discount_result (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    payment_id uuid NOT NULL, invoice_id uuid NOT NULL, commitment_id uuid,
    payment_term_id uuid, discount_tier_id uuid,
    allocated_payment_amount numeric(18,4) NOT NULL, qualification_date date NOT NULL,
    qualified_tier_no smallint, qualified_days_actual smallint NOT NULL,
    discount_basis_amount numeric(18,4) NOT NULL, discount_pct numeric(5,2), discount_amount numeric(18,4) NOT NULL,
    application_status document.payment_discount_application_status_d NOT NULL,
    is_reversal boolean NOT NULL DEFAULT false, reverses_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    CONSTRAINT payment_term_discount_result_pkey PRIMARY KEY(id),
    CONSTRAINT payment_term_discount_result_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT payment_term_discount_result_amount_chk CHECK(allocated_payment_amount>=0 AND discount_basis_amount>=0 AND discount_amount>=0),
    CONSTRAINT payment_term_discount_result_days_chk CHECK(qualified_days_actual>=0),
    CONSTRAINT payment_term_discount_result_pct_chk CHECK(discount_pct IS NULL OR discount_pct BETWEEN 0 AND 100),
    CONSTRAINT payment_term_discount_result_term_chk CHECK(commitment_id IS NOT NULL OR payment_term_id IS NOT NULL),
    CONSTRAINT payment_term_discount_result_reverse_chk CHECK((NOT is_reversal) OR reverses_id IS NOT NULL),
    CONSTRAINT payment_term_discount_result_self_chk CHECK(reverses_id IS DISTINCT FROM id),
    CONSTRAINT payment_term_discount_result_metadata_chk CHECK(jsonb_typeof(metadata)='object')
);

CREATE TABLE document.wht_certificate (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    code text NOT NULL DEFAULT '', name text NOT NULL DEFAULT '', company_code_id uuid NOT NULL,
    counterparty_id uuid NOT NULL, tax_type_id uuid NOT NULL, section_code text,
    certificate_no text NOT NULL, certificate_series text, period_from date NOT NULL, period_to date NOT NULL,
    gross_amount numeric(18,4) NOT NULL, wht_amount numeric(18,4) NOT NULL, currency_code character(3) NOT NULL,
    source_transaction_ids uuid[] NOT NULL DEFAULT '{}'::uuid[],
    status document.wht_certificate_status_d NOT NULL DEFAULT 'draft',
    issued_at timestamptz, issued_by uuid, voided_at timestamptz, voided_by uuid, void_reason text,
    superseded_by_id uuid, created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT wht_certificate_pkey PRIMARY KEY(id),
    CONSTRAINT wht_certificate_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT wht_certificate_number_uq UNIQUE(tenant_id,company_code_id,certificate_no),
    CONSTRAINT wht_certificate_number_chk CHECK(btrim(certificate_no)<>''),
    CONSTRAINT wht_certificate_period_chk CHECK(period_to>=period_from),
    CONSTRAINT wht_certificate_amount_chk CHECK(gross_amount>=0 AND wht_amount>=0 AND wht_amount<=gross_amount),
    CONSTRAINT wht_certificate_issued_chk CHECK(status<>'issued' OR issued_at IS NOT NULL),
    CONSTRAINT wht_certificate_voided_chk CHECK(status<>'voided' OR (voided_at IS NOT NULL AND void_reason IS NOT NULL)),
    CONSTRAINT wht_certificate_issue_pair_chk CHECK((issued_at IS NULL)=(issued_by IS NULL)),
    CONSTRAINT wht_certificate_void_pair_chk CHECK((voided_at IS NULL)=(voided_by IS NULL)),
    CONSTRAINT wht_certificate_self_chk CHECK(superseded_by_id IS DISTINCT FROM id),
    CONSTRAINT wht_certificate_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.import_request (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    entity_name text NOT NULL, file_ref text NOT NULL, file_name text NOT NULL, file_size_bytes bigint,
    file_format document.import_file_format_d NOT NULL DEFAULT 'csv', mapping_config jsonb NOT NULL DEFAULT '[]'::jsonb,
    import_mode document.import_mode_d NOT NULL DEFAULT 'create', options jsonb NOT NULL DEFAULT '{}'::jsonb,
    total_rows integer, processed_rows integer NOT NULL DEFAULT 0, success_count integer NOT NULL DEFAULT 0, error_count integer NOT NULL DEFAULT 0,
    status document.import_request_status_d NOT NULL DEFAULT 'uploaded', error_summary jsonb,
    started_at timestamptz, completed_at timestamptz, submitted_by uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT import_request_pkey PRIMARY KEY(id),
    CONSTRAINT import_request_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT import_request_entity_chk CHECK(btrim(entity_name)<>''),
    CONSTRAINT import_request_file_chk CHECK(btrim(file_ref)<>'' AND btrim(file_name)<>'' AND (file_size_bytes IS NULL OR file_size_bytes>=0)),
    CONSTRAINT import_request_json_chk CHECK(jsonb_typeof(mapping_config)='array' AND jsonb_typeof(options)='object' AND (error_summary IS NULL OR jsonb_typeof(error_summary)='object')),
    CONSTRAINT import_request_count_chk CHECK((total_rows IS NULL OR total_rows>=0) AND processed_rows>=0 AND success_count>=0 AND error_count>=0),
    CONSTRAINT import_request_dates_chk CHECK(completed_at IS NULL OR (started_at IS NOT NULL AND completed_at>=started_at)),
    CONSTRAINT import_request_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.import_request_chunk (
    id                 uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id          uuid        NOT NULL,
    import_request_id  uuid        NOT NULL,
    chunk_index        integer     NOT NULL,
    row_start          integer     NOT NULL,
    row_end            integer     NOT NULL,
    status             document.import_chunk_status_d NOT NULL DEFAULT 'pending',
    success_count      integer     NOT NULL DEFAULT 0,
    error_count        integer     NOT NULL DEFAULT 0,
    errors             jsonb       NOT NULL DEFAULT '[]'::jsonb,
    job_id             text,
    attempt_count      integer     NOT NULL DEFAULT 0,
    max_attempts       integer     NOT NULL DEFAULT 3,
    started_at         timestamptz,
    completed_at       timestamptz,
    status_changed_at  timestamptz,
    status_changed_by  uuid,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         uuid        NOT NULL,
    updated_at         timestamptz,
    updated_by         uuid,

    CONSTRAINT import_request_chunk_pkey PRIMARY KEY(id),
    CONSTRAINT import_request_chunk_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT import_request_chunk_index_uq UNIQUE(tenant_id,import_request_id,chunk_index),
    CONSTRAINT import_request_chunk_index_chk CHECK(chunk_index>=0),
    CONSTRAINT import_request_chunk_range_chk CHECK(row_start>=1 AND row_end>=row_start),
    CONSTRAINT import_request_chunk_counts_chk CHECK(
        success_count>=0 AND error_count>=0
        AND success_count+error_count<=row_end-row_start+1
    ),
    CONSTRAINT import_request_chunk_errors_chk CHECK(jsonb_typeof(errors)='array'),
    CONSTRAINT import_request_chunk_attempt_chk CHECK(
        attempt_count>=0 AND max_attempts>0 AND attempt_count<=max_attempts
    ),
    CONSTRAINT import_request_chunk_job_chk CHECK(job_id IS NULL OR btrim(job_id)<>''),
    CONSTRAINT import_request_chunk_timeline_chk CHECK(
        (started_at IS NULL OR started_at>=created_at)
        AND (completed_at IS NULL OR (started_at IS NOT NULL AND completed_at>=started_at))
    ),
    CONSTRAINT import_request_chunk_terminal_chk CHECK(
        (status IN ('completed','failed','cancelled'))=(completed_at IS NOT NULL)
    ),
    CONSTRAINT import_request_chunk_status_pair_chk CHECK(
        (status_changed_at IS NULL)=(status_changed_by IS NULL)
    ),
    CONSTRAINT import_request_chunk_audit_pair_chk CHECK(
        (updated_at IS NULL)=(updated_by IS NULL)
    )
);

COMMENT ON TABLE document.import_request_chunk IS
  'Independently retryable, tenant-scoped row range within an import request. Chunk state is mutable; lifecycle evidence is also appended to audit.audit_log.';

CREATE TABLE document.render_output (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    template_version_id uuid, letterhead_id uuid, brand_profile_id uuid,
    entity_name text NOT NULL, entity_id text NOT NULL, operation text NOT NULL,
    variant text NOT NULL DEFAULT 'default', locale text NOT NULL DEFAULT 'en', timezone text NOT NULL DEFAULT 'UTC',
    status document.render_output_status_d NOT NULL DEFAULT 'QUEUED',
    job_queue_id text, attempt_count integer NOT NULL DEFAULT 0, max_attempts integer NOT NULL DEFAULT 3,
    last_attempt_at timestamptz, trace_id char(32),
    storage_bucket text, storage_key text, storage_version_id text, mime_type text DEFAULT 'application/pdf',
    size_bytes bigint, checksum text, manifest_json jsonb NOT NULL DEFAULT '{}'::jsonb, manifest_version integer NOT NULL DEFAULT 1,
    input_payload_hash text, replaces_output_id uuid,
    error_code text, error_message text, failure_category document.render_failure_category_d,
    replay_count integer NOT NULL DEFAULT 0, last_replayed_at timestamptz, last_replayed_by uuid,
    rendered_at timestamptz, delivered_at timestamptz, archived_at timestamptz,
    revoked_at timestamptz, revoked_by uuid, revoke_reason text,
    status_changed_at timestamptz, status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(), created_by uuid NOT NULL,
    updated_at timestamptz, updated_by uuid,
    CONSTRAINT render_output_pkey PRIMARY KEY(id),
    CONSTRAINT render_output_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT render_output_entity_chk CHECK(btrim(entity_name)<>'' AND btrim(entity_id)<>''),
    CONSTRAINT render_output_operation_chk CHECK(btrim(operation)<>''),
    CONSTRAINT render_output_size_chk CHECK(size_bytes IS NULL OR size_bytes>=0),
    CONSTRAINT render_output_attempt_chk CHECK(attempt_count>=0 AND max_attempts>0 AND attempt_count<=max_attempts),
    CONSTRAINT render_output_replay_chk CHECK(replay_count>=0),
    CONSTRAINT render_output_attempt_time_chk CHECK(last_attempt_at IS NULL OR last_attempt_at>=created_at),
    CONSTRAINT render_output_trace_chk CHECK(trace_id IS NULL OR trace_id~'^[0-9a-f]{32}$'),
    CONSTRAINT render_output_manifest_chk CHECK(manifest_version>=1 AND jsonb_typeof(manifest_json)='object' AND manifest_json ? 'entity_name'),
    CONSTRAINT render_output_storage_chk CHECK((storage_bucket IS NULL)=(storage_key IS NULL)),
    CONSTRAINT render_output_revoke_pair_chk CHECK((revoked_at IS NULL)=(revoked_by IS NULL)),
    CONSTRAINT render_output_replayed_pair_chk CHECK((last_replayed_at IS NULL)=(last_replayed_by IS NULL)),
    CONSTRAINT render_output_failed_chk CHECK(status<>'FAILED' OR (error_code IS NOT NULL AND failure_category IS NOT NULL)),
    CONSTRAINT render_output_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT render_output_self_chk CHECK(replaces_output_id IS DISTINCT FROM id),
    CONSTRAINT render_output_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);

CREATE TABLE document.user_profile_update_request (
    id uuid NOT NULL DEFAULT shared.uuidv7(), tenant_id uuid NOT NULL,
    code text NOT NULL, name text NOT NULL, created_by uuid NOT NULL,
    requested_by uuid NOT NULL, principal_id uuid NOT NULL, principal_snapshot jsonb,
    request_scope text[] NOT NULL DEFAULT '{}'::text[], priority document.profile_update_priority_d NOT NULL DEFAULT 'normal',
    change_reason text, requested_changes jsonb NOT NULL DEFAULT '{}'::jsonb, workflow_request_id uuid,
    status document.profile_update_request_status_d NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft','submitted','awaiting_approval','revision_requested')) STORED,
    status_changed_at timestamptz, status_changed_by uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, updated_by uuid,
    CONSTRAINT user_profile_update_request_pkey PRIMARY KEY(id),
    CONSTRAINT user_profile_update_request_tenant_id_uq UNIQUE(tenant_id,id),
    CONSTRAINT user_profile_update_request_code_uq UNIQUE(tenant_id,code),
    CONSTRAINT user_profile_update_request_code_chk CHECK(code~'^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$'),
    CONSTRAINT user_profile_update_request_name_chk CHECK(btrim(name)<>''),
    CONSTRAINT user_profile_update_request_self_service_chk CHECK(requested_by=created_by AND principal_id=created_by),
    CONSTRAINT user_profile_update_request_json_chk CHECK((principal_snapshot IS NULL OR jsonb_typeof(principal_snapshot)='object') AND jsonb_typeof(requested_changes)='object' AND jsonb_typeof(metadata)='object'),
    CONSTRAINT user_profile_update_request_status_pair_chk CHECK((status_changed_at IS NULL)=(status_changed_by IS NULL)),
    CONSTRAINT user_profile_update_request_audit_pair_chk CHECK((updated_at IS NULL)=(updated_by IS NULL))
);
