-- Authoring documents, supplier evidence, and fulfillment documents.
-- Version history belongs to snapshot.entity_snapshot, not local version chains.

CREATE TABLE document.purchase_requisition (
    id                           uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                    uuid        NOT NULL,
    company_code_id              uuid        NOT NULL,
    code                         text        NOT NULL,
    name                         text        NOT NULL,
    description                  text,
    requisition_type             document.requisition_type_d NOT NULL DEFAULT 'standard',
    priority                     document.requisition_priority_d NOT NULL DEFAULT 'normal',
    requested_by                 uuid        NOT NULL,
    responsible_principal_id     uuid,
    document_date                date        NOT NULL DEFAULT CURRENT_DATE,
    required_by_date             date,
    currency_code                character(3) NOT NULL,
    base_currency_code           character(3) NOT NULL,
    exchange_rate                numeric(18,10),
    fx_rate_snapshot             jsonb       NOT NULL DEFAULT '{}'::jsonb,
    total_amount                 numeric(18,4) NOT NULL DEFAULT 0,
    budget_check_result          document.budget_check_result_d,
    fiscal_period_id             uuid,
    encumbrance_journal_entry_id uuid,
    workflow_request_id          uuid,
    approved_at                  timestamptz,
    approved_by                  uuid,
    row_version                  bigint      NOT NULL DEFAULT 1,
    tags                         jsonb       NOT NULL DEFAULT '[]'::jsonb,
    metadata                     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    status                       document.requisition_status_d NOT NULL DEFAULT 'draft',
    status_changed_at            timestamptz,
    status_changed_by            uuid,
    created_at                   timestamptz NOT NULL DEFAULT now(),
    created_by                   uuid        NOT NULL,
    updated_at                   timestamptz,
    updated_by                   uuid,
    CONSTRAINT purchase_requisition_pkey PRIMARY KEY (id),
    CONSTRAINT purchase_requisition_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT purchase_requisition_code_uq UNIQUE (tenant_id, company_code_id, code),
    CONSTRAINT purchase_requisition_code_chk CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$'),
    CONSTRAINT purchase_requisition_name_chk CHECK (btrim(name) <> ''),
    CONSTRAINT purchase_requisition_dates_chk CHECK (required_by_date IS NULL OR required_by_date >= document_date),
    CONSTRAINT purchase_requisition_currency_chk CHECK (
        (currency_code = base_currency_code AND COALESCE(exchange_rate, 1) = 1)
        OR (currency_code <> base_currency_code AND exchange_rate > 0)
    ),
    CONSTRAINT purchase_requisition_amount_chk CHECK (total_amount >= 0),
    CONSTRAINT purchase_requisition_approval_pair_chk CHECK ((approved_at IS NULL) = (approved_by IS NULL)),
    CONSTRAINT purchase_requisition_approval_state_chk CHECK (
        status NOT IN ('approved','partially_converted','fully_converted','closed') OR approved_at IS NOT NULL
    ),
    CONSTRAINT purchase_requisition_row_version_chk CHECK (row_version >= 1),
    CONSTRAINT purchase_requisition_json_chk CHECK (
        jsonb_typeof(fx_rate_snapshot) = 'object' AND jsonb_typeof(tags) = 'array' AND jsonb_typeof(metadata) = 'object'
    ),
    CONSTRAINT purchase_requisition_status_pair_chk CHECK ((status_changed_at IS NULL) = (status_changed_by IS NULL)),
    CONSTRAINT purchase_requisition_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE document.purchase_requisition_line (
    id                       uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                uuid        NOT NULL,
    company_code_id          uuid        NOT NULL,
    purchase_requisition_id  uuid        NOT NULL,
    line_no                  smallint    NOT NULL,
    item_id                  uuid,
    item_description         text        NOT NULL,
    procurement_type         document.procurement_type_d NOT NULL DEFAULT 'goods',
    line_type                document.commercial_line_type_d NOT NULL DEFAULT 'noncatalog',
    commodity_category_id    uuid,
    business_intent_id       uuid,
    classification_decision  jsonb       NOT NULL DEFAULT '{}'::jsonb,
    asset_class_id           uuid,
    uom_code                 text        NOT NULL,
    quantity                 numeric(18,4) NOT NULL,
    unit_price               numeric(18,4) NOT NULL DEFAULT 0,
    price_unit               numeric(18,4) NOT NULL DEFAULT 1,
    currency_code            character(3) NOT NULL,
    net_amount               numeric(18,4) GENERATED ALWAYS AS (quantity * unit_price / price_unit) STORED,
    tax_amount               numeric(18,4) NOT NULL DEFAULT 0,
    withholding_tax_amount   numeric(18,4) NOT NULL DEFAULT 0,
    gross_amount             numeric(18,4) GENERATED ALWAYS AS (quantity * unit_price / price_unit + tax_amount - withholding_tax_amount) STORED,
    tax_group_id             uuid,
    withholding_tax_group_id uuid,
    to_tax_jurisdiction_id   uuid,
    from_tax_jurisdiction_id uuid,
    required_by_date         date,
    site_id                  uuid,
    warehouse_id             uuid,
    storage_location_code    text,
    ship_to_address_id       uuid,
    bill_to_address_id       uuid,
    bill_from_address_id     uuid,
    suggested_supplier_id    uuid,
    ship_from_address_id     uuid,
    remit_to_address_id      uuid,
    over_delivery_tolerance  numeric(7,4) NOT NULL DEFAULT 0,
    under_delivery_tolerance numeric(7,4) NOT NULL DEFAULT 0,
    committed_quantity       numeric(18,4) NOT NULL DEFAULT 0,
    metadata                 jsonb       NOT NULL DEFAULT '{}'::jsonb,
    status                   document.requisition_line_status_d NOT NULL DEFAULT 'open',
    status_changed_at        timestamptz,
    status_changed_by        uuid,
    created_at               timestamptz NOT NULL DEFAULT now(),
    created_by               uuid        NOT NULL,
    updated_at               timestamptz,
    updated_by               uuid,
    CONSTRAINT purchase_requisition_line_pkey PRIMARY KEY (id),
    CONSTRAINT purchase_requisition_line_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT purchase_requisition_line_parent_no_uq UNIQUE (tenant_id, purchase_requisition_id, line_no),
    CONSTRAINT purchase_requisition_line_no_chk CHECK (line_no > 0),
    CONSTRAINT purchase_requisition_line_description_chk CHECK (btrim(item_description) <> ''),
    CONSTRAINT purchase_requisition_line_quantity_chk CHECK (quantity > 0 AND committed_quantity BETWEEN 0 AND quantity),
    CONSTRAINT purchase_requisition_line_price_chk CHECK (unit_price >= 0 AND price_unit > 0),
    CONSTRAINT purchase_requisition_line_tax_chk CHECK (tax_amount >= 0 AND withholding_tax_amount >= 0),
    CONSTRAINT purchase_requisition_line_tolerance_chk CHECK (
        over_delivery_tolerance BETWEEN 0 AND 100 AND under_delivery_tolerance BETWEEN 0 AND 100
    ),
    CONSTRAINT purchase_requisition_line_warehouse_chk CHECK (warehouse_id IS NULL OR site_id IS NOT NULL),
    CONSTRAINT purchase_requisition_line_json_chk CHECK (
        jsonb_typeof(classification_decision) = 'object' AND jsonb_typeof(metadata) = 'object'
    ),
    CONSTRAINT purchase_requisition_line_status_pair_chk CHECK ((status_changed_at IS NULL) = (status_changed_by IS NULL)),
    CONSTRAINT purchase_requisition_line_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE document.purchase_order_confirmation (
    id                          uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                   uuid        NOT NULL,
    company_code_id             uuid        NOT NULL,
    code                        text        NOT NULL,
    name                        text        NOT NULL,
    commitment_id               uuid        NOT NULL,
    supplier_id                 uuid        NOT NULL,
    supplier_reference_number   text,
    supplier_confirmation_date  date,
    confirmation_type           document.confirmation_type_d NOT NULL DEFAULT 'FULL_CONFIRM',
    document_date               date        NOT NULL DEFAULT CURRENT_DATE,
    currency_code               character(3) NOT NULL,
    confirmed_total_amount      numeric(18,4) NOT NULL DEFAULT 0,
    amendment_commitment_id     uuid,
    notes                       text,
    source_summary              jsonb       NOT NULL DEFAULT '{}'::jsonb,
    metadata                    jsonb       NOT NULL DEFAULT '{}'::jsonb,
    row_version                 bigint      NOT NULL DEFAULT 1,
    status                      document.confirmation_status_d NOT NULL DEFAULT 'received',
    status_changed_at           timestamptz,
    status_changed_by           uuid,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    created_by                  uuid        NOT NULL,
    updated_at                  timestamptz,
    updated_by                  uuid,
    CONSTRAINT purchase_order_confirmation_pkey PRIMARY KEY (id),
    CONSTRAINT purchase_order_confirmation_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT purchase_order_confirmation_code_uq UNIQUE (tenant_id, company_code_id, code),
    CONSTRAINT purchase_order_confirmation_code_chk CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$'),
    CONSTRAINT purchase_order_confirmation_name_chk CHECK (btrim(name) <> ''),
    CONSTRAINT purchase_order_confirmation_amount_chk CHECK (confirmed_total_amount >= 0),
    CONSTRAINT purchase_order_confirmation_amendment_chk CHECK (amendment_commitment_id IS DISTINCT FROM commitment_id),
    CONSTRAINT purchase_order_confirmation_row_version_chk CHECK (row_version >= 1),
    CONSTRAINT purchase_order_confirmation_json_chk CHECK (
        jsonb_typeof(source_summary) = 'object' AND jsonb_typeof(metadata) = 'object'
    ),
    CONSTRAINT purchase_order_confirmation_status_pair_chk CHECK ((status_changed_at IS NULL) = (status_changed_by IS NULL)),
    CONSTRAINT purchase_order_confirmation_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE document.purchase_order_confirmation_line (
    id                       uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                uuid        NOT NULL,
    confirmation_id          uuid        NOT NULL,
    line_no                  smallint    NOT NULL,
    commitment_line_id       uuid        NOT NULL,
    procurement_type         document.procurement_type_d NOT NULL DEFAULT 'goods',
    line_type                document.commercial_line_type_d NOT NULL DEFAULT 'noncatalog',
    confirmed_quantity       numeric(18,4) NOT NULL,
    confirmed_unit_price     numeric(18,4) NOT NULL,
    confirmed_delivery_date  date,
    quantity_variance        numeric(18,4) NOT NULL DEFAULT 0,
    price_variance           numeric(18,4) NOT NULL DEFAULT 0,
    line_status              document.confirmation_line_status_d NOT NULL DEFAULT 'confirmed',
    supplier_notes           text,
    metadata                 jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at               timestamptz NOT NULL DEFAULT now(),
    created_by               uuid        NOT NULL,
    CONSTRAINT purchase_order_confirmation_line_pkey PRIMARY KEY (id),
    CONSTRAINT purchase_order_confirmation_line_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT purchase_order_confirmation_line_parent_no_uq UNIQUE (tenant_id, confirmation_id, line_no),
    CONSTRAINT purchase_order_confirmation_line_no_chk CHECK (line_no > 0),
    CONSTRAINT purchase_order_confirmation_line_quantity_chk CHECK (confirmed_quantity > 0),
    CONSTRAINT purchase_order_confirmation_line_price_chk CHECK (confirmed_unit_price >= 0),
    CONSTRAINT purchase_order_confirmation_line_json_chk CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE TABLE document.delivery_note (
    id                         uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                  uuid        NOT NULL,
    company_code_id            uuid        NOT NULL,
    code                       text        NOT NULL,
    name                       text        NOT NULL,
    commitment_id              uuid        NOT NULL,
    supplier_id                uuid        NOT NULL,
    supplier_delivery_note_no  text,
    supplier_dispatch_date     date,
    bill_of_lading_no          text,
    tracking_number            text,
    delivery_date              date        NOT NULL DEFAULT CURRENT_DATE,
    expected_arrival_date      date,
    actual_arrival_date        date,
    delivery_site_id           uuid        NOT NULL,
    delivery_warehouse_id      uuid,
    carrier_name               text,
    transport_mode             text,
    requires_inspection        boolean     NOT NULL DEFAULT false,
    inspection_status          document.inspection_status_d,
    is_fully_receipted         boolean     NOT NULL DEFAULT false,
    currency_code              character(3) NOT NULL,
    total_amount               numeric(18,4) NOT NULL DEFAULT 0,
    notes                      text,
    metadata                   jsonb       NOT NULL DEFAULT '{}'::jsonb,
    row_version                bigint      NOT NULL DEFAULT 1,
    status                     document.delivery_note_status_d NOT NULL DEFAULT 'draft',
    status_changed_at          timestamptz,
    status_changed_by          uuid,
    created_at                 timestamptz NOT NULL DEFAULT now(),
    created_by                 uuid        NOT NULL,
    updated_at                 timestamptz,
    updated_by                 uuid,
    CONSTRAINT delivery_note_pkey PRIMARY KEY (id),
    CONSTRAINT delivery_note_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT delivery_note_code_uq UNIQUE (tenant_id, company_code_id, code),
    CONSTRAINT delivery_note_code_chk CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$'),
    CONSTRAINT delivery_note_name_chk CHECK (btrim(name) <> ''),
    CONSTRAINT delivery_note_dates_chk CHECK (
        (expected_arrival_date IS NULL OR expected_arrival_date >= supplier_dispatch_date)
        AND (actual_arrival_date IS NULL OR actual_arrival_date >= supplier_dispatch_date)
    ),
    CONSTRAINT delivery_note_inspection_chk CHECK (
        (requires_inspection AND inspection_status IS NOT NULL)
        OR (NOT requires_inspection AND inspection_status IS NULL)
    ),
    CONSTRAINT delivery_note_amount_chk CHECK (total_amount >= 0),
    CONSTRAINT delivery_note_row_version_chk CHECK (row_version >= 1),
    CONSTRAINT delivery_note_json_chk CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT delivery_note_status_pair_chk CHECK ((status_changed_at IS NULL) = (status_changed_by IS NULL)),
    CONSTRAINT delivery_note_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE document.delivery_note_line (
    id                    uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id             uuid        NOT NULL,
    company_code_id       uuid        NOT NULL,
    delivery_note_id      uuid        NOT NULL,
    line_no               smallint    NOT NULL,
    commitment_line_id    uuid        NOT NULL,
    item_id               uuid,
    item_description      text        NOT NULL,
    procurement_type      document.procurement_type_d NOT NULL DEFAULT 'goods',
    line_type             document.commercial_line_type_d NOT NULL DEFAULT 'noncatalog',
    uom_code              text        NOT NULL,
    shipped_quantity      numeric(18,4) NOT NULL,
    received_quantity     numeric(18,4) NOT NULL DEFAULT 0,
    damaged_quantity      numeric(18,4) NOT NULL DEFAULT 0,
    rejected_quantity     numeric(18,4) NOT NULL DEFAULT 0,
    accepted_quantity     numeric(18,4) GENERATED ALWAYS AS (received_quantity - damaged_quantity - rejected_quantity) STORED,
    lot_number            text,
    serial_numbers        text[],
    batch_number          text,
    expiry_date           date,
    metadata              jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at            timestamptz NOT NULL DEFAULT now(),
    created_by            uuid        NOT NULL,
    updated_at            timestamptz,
    updated_by            uuid,
    CONSTRAINT delivery_note_line_pkey PRIMARY KEY (id),
    CONSTRAINT delivery_note_line_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT delivery_note_line_parent_no_uq UNIQUE (tenant_id, delivery_note_id, line_no),
    CONSTRAINT delivery_note_line_no_chk CHECK (line_no > 0),
    CONSTRAINT delivery_note_line_description_chk CHECK (btrim(item_description) <> ''),
    CONSTRAINT delivery_note_line_quantity_chk CHECK (
        shipped_quantity > 0 AND received_quantity BETWEEN 0 AND shipped_quantity
        AND damaged_quantity >= 0 AND rejected_quantity >= 0
        AND damaged_quantity + rejected_quantity <= received_quantity
    ),
    CONSTRAINT delivery_note_line_serials_chk CHECK (serial_numbers IS NULL OR array_position(serial_numbers, NULL) IS NULL),
    CONSTRAINT delivery_note_line_json_chk CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT delivery_note_line_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE document.receipt (
    id                       uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                uuid        NOT NULL,
    company_code_id          uuid        NOT NULL,
    code                     text        NOT NULL,
    name                     text        NOT NULL,
    requested_by             uuid        NOT NULL,
    commitment_id            uuid,
    delivery_note_id         uuid,
    supplier_id              uuid        NOT NULL,
    received_date            date        NOT NULL DEFAULT CURRENT_DATE,
    posting_date             date        NOT NULL DEFAULT CURRENT_DATE,
    receiving_site_id        uuid,
    receiving_warehouse_id   uuid,
    currency_code            character(3) NOT NULL,
    base_currency_code       character(3) NOT NULL,
    exchange_rate            numeric(18,10),
    fx_rate_snapshot         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    total_amount             numeric(18,4) NOT NULL DEFAULT 0,
    fiscal_period_id         uuid        NOT NULL,
    accrual_journal_entry_id uuid,
    workflow_request_id      uuid,
    approved_at              timestamptz,
    approved_by              uuid,
    source_summary           jsonb       NOT NULL DEFAULT '{}'::jsonb,
    metadata                 jsonb       NOT NULL DEFAULT '{}'::jsonb,
    row_version              bigint      NOT NULL DEFAULT 1,
    status                   document.receipt_status_d NOT NULL DEFAULT 'draft',
    status_changed_at        timestamptz,
    status_changed_by        uuid,
    created_at               timestamptz NOT NULL DEFAULT now(),
    created_by               uuid        NOT NULL,
    updated_at               timestamptz,
    updated_by               uuid,
    CONSTRAINT receipt_pkey PRIMARY KEY (id),
    CONSTRAINT receipt_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT receipt_code_uq UNIQUE (tenant_id, company_code_id, code),
    CONSTRAINT receipt_code_chk CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$'),
    CONSTRAINT receipt_name_chk CHECK (btrim(name) <> ''),
    CONSTRAINT receipt_source_chk CHECK (commitment_id IS NOT NULL OR delivery_note_id IS NOT NULL),
    CONSTRAINT receipt_location_chk CHECK (receiving_warehouse_id IS NULL OR receiving_site_id IS NOT NULL),
    CONSTRAINT receipt_currency_chk CHECK (
        (currency_code = base_currency_code AND COALESCE(exchange_rate, 1) = 1)
        OR (currency_code <> base_currency_code AND exchange_rate > 0)
    ),
    CONSTRAINT receipt_amount_chk CHECK (total_amount >= 0),
    CONSTRAINT receipt_approval_pair_chk CHECK ((approved_at IS NULL) = (approved_by IS NULL)),
    CONSTRAINT receipt_approval_state_chk CHECK (status NOT IN ('approved','posted','reversed') OR approved_at IS NOT NULL),
    CONSTRAINT receipt_row_version_chk CHECK (row_version >= 1),
    CONSTRAINT receipt_json_chk CHECK (
        jsonb_typeof(fx_rate_snapshot) = 'object' AND jsonb_typeof(source_summary) = 'object' AND jsonb_typeof(metadata) = 'object'
    ),
    CONSTRAINT receipt_status_pair_chk CHECK ((status_changed_at IS NULL) = (status_changed_by IS NULL)),
    CONSTRAINT receipt_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE document.receipt_line (
    id                       uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                uuid        NOT NULL,
    company_code_id          uuid        NOT NULL,
    receipt_id               uuid        NOT NULL,
    line_no                  smallint    NOT NULL,
    commitment_line_id       uuid        NOT NULL,
    delivery_note_line_id    uuid,
    source_schedule_id       uuid,
    source_line_version      bigint,
    item_id                  uuid        NOT NULL,
    item_description         text        NOT NULL,
    procurement_type         document.procurement_type_d NOT NULL DEFAULT 'goods',
    line_type                document.commercial_line_type_d NOT NULL DEFAULT 'noncatalog',
    uom_code                 text        NOT NULL,
    received_quantity        numeric(18,4) NOT NULL,
    accepted_quantity        numeric(18,4) NOT NULL,
    rejected_quantity        numeric(18,4) NOT NULL DEFAULT 0,
    unit_price               numeric(18,4) NOT NULL,
    price_unit               numeric(18,4) NOT NULL DEFAULT 1,
    currency_code            character(3) NOT NULL,
    net_amount               numeric(18,4) GENERATED ALWAYS AS (accepted_quantity * unit_price / price_unit) STORED,
    tax_amount               numeric(18,4) NOT NULL DEFAULT 0,
    withholding_tax_amount   numeric(18,4) NOT NULL DEFAULT 0,
    gross_amount             numeric(18,4) GENERATED ALWAYS AS (accepted_quantity * unit_price / price_unit + tax_amount - withholding_tax_amount) STORED,
    tax_group_id             uuid,
    withholding_tax_group_id uuid,
    to_tax_jurisdiction_id   uuid,
    from_tax_jurisdiction_id uuid,
    site_id                  uuid        NOT NULL,
    warehouse_id             uuid        NOT NULL,
    storage_location_code    text,
    ship_to_address_id       uuid,
    bill_to_address_id       uuid,
    bill_from_address_id     uuid,
    supplier_id              uuid,
    ship_from_address_id     uuid,
    remit_to_address_id      uuid,
    lot_number               text,
    serial_numbers           jsonb,
    batch_number             text,
    expiry_date              date,
    inventory_movement_id    uuid,
    asset_class_id           uuid,
    metadata                 jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at               timestamptz NOT NULL DEFAULT now(),
    created_by               uuid        NOT NULL,
    updated_at               timestamptz,
    updated_by               uuid,
    CONSTRAINT receipt_line_pkey PRIMARY KEY (id),
    CONSTRAINT receipt_line_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT receipt_line_parent_no_uq UNIQUE (tenant_id, receipt_id, line_no),
    CONSTRAINT receipt_line_no_chk CHECK (line_no > 0),
    CONSTRAINT receipt_line_description_chk CHECK (btrim(item_description) <> ''),
    CONSTRAINT receipt_line_quantity_chk CHECK (
        received_quantity > 0 AND accepted_quantity >= 0 AND rejected_quantity >= 0
        AND accepted_quantity + rejected_quantity = received_quantity
    ),
    CONSTRAINT receipt_line_price_chk CHECK (unit_price >= 0 AND price_unit > 0),
    CONSTRAINT receipt_line_tax_chk CHECK (tax_amount >= 0 AND withholding_tax_amount >= 0),
    CONSTRAINT receipt_line_source_version_chk CHECK (source_line_version IS NULL OR source_line_version >= 1),
    CONSTRAINT receipt_line_serials_chk CHECK (serial_numbers IS NULL OR jsonb_typeof(serial_numbers) = 'array'),
    CONSTRAINT receipt_line_json_chk CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT receipt_line_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE document.service_sheet (
    id                       uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                uuid        NOT NULL,
    company_code_id          uuid        NOT NULL,
    code                     text        NOT NULL,
    name                     text        NOT NULL,
    requested_by             uuid        NOT NULL,
    commitment_id            uuid        NOT NULL,
    supplier_id              uuid        NOT NULL,
    service_date             date        NOT NULL DEFAULT CURRENT_DATE,
    posting_date             date        NOT NULL DEFAULT CURRENT_DATE,
    service_period_from      date        NOT NULL,
    service_period_to        date        NOT NULL,
    currency_code            character(3) NOT NULL,
    base_currency_code       character(3) NOT NULL,
    exchange_rate            numeric(18,10),
    fx_rate_snapshot         jsonb       NOT NULL DEFAULT '{}'::jsonb,
    total_amount             numeric(18,4) NOT NULL DEFAULT 0,
    fiscal_period_id         uuid        NOT NULL,
    accrual_journal_entry_id uuid,
    accepted_by              uuid,
    accepted_at              timestamptz,
    workflow_request_id      uuid,
    approved_at              timestamptz,
    approved_by              uuid,
    metadata                 jsonb       NOT NULL DEFAULT '{}'::jsonb,
    row_version              bigint      NOT NULL DEFAULT 1,
    status                   document.service_sheet_status_d NOT NULL DEFAULT 'draft',
    status_changed_at        timestamptz,
    status_changed_by        uuid,
    created_at               timestamptz NOT NULL DEFAULT now(),
    created_by               uuid        NOT NULL,
    updated_at               timestamptz,
    updated_by               uuid,
    CONSTRAINT service_sheet_pkey PRIMARY KEY (id),
    CONSTRAINT service_sheet_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT service_sheet_code_uq UNIQUE (tenant_id, company_code_id, code),
    CONSTRAINT service_sheet_code_chk CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9_.-]{0,62}$'),
    CONSTRAINT service_sheet_name_chk CHECK (btrim(name) <> ''),
    CONSTRAINT service_sheet_period_chk CHECK (service_period_to >= service_period_from),
    CONSTRAINT service_sheet_currency_chk CHECK (
        (currency_code = base_currency_code AND COALESCE(exchange_rate, 1) = 1)
        OR (currency_code <> base_currency_code AND exchange_rate > 0)
    ),
    CONSTRAINT service_sheet_amount_chk CHECK (total_amount >= 0),
    CONSTRAINT service_sheet_acceptance_pair_chk CHECK ((accepted_at IS NULL) = (accepted_by IS NULL)),
    CONSTRAINT service_sheet_acceptance_state_chk CHECK (
        status NOT IN ('accepted','pending_approval','approved','posted','reversed') OR accepted_at IS NOT NULL
    ),
    CONSTRAINT service_sheet_approval_pair_chk CHECK ((approved_at IS NULL) = (approved_by IS NULL)),
    CONSTRAINT service_sheet_approval_state_chk CHECK (status NOT IN ('approved','posted','reversed') OR approved_at IS NOT NULL),
    CONSTRAINT service_sheet_row_version_chk CHECK (row_version >= 1),
    CONSTRAINT service_sheet_json_chk CHECK (jsonb_typeof(fx_rate_snapshot) = 'object' AND jsonb_typeof(metadata) = 'object'),
    CONSTRAINT service_sheet_status_pair_chk CHECK ((status_changed_at IS NULL) = (status_changed_by IS NULL)),
    CONSTRAINT service_sheet_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);

CREATE TABLE document.service_sheet_line (
    id                       uuid        NOT NULL DEFAULT shared.uuidv7(),
    tenant_id                uuid        NOT NULL,
    company_code_id          uuid        NOT NULL,
    service_sheet_id         uuid        NOT NULL,
    line_no                  smallint    NOT NULL,
    commitment_line_id       uuid        NOT NULL,
    source_schedule_id       uuid,
    item_id                  uuid,
    item_description         text        NOT NULL,
    procurement_type         document.procurement_type_d NOT NULL DEFAULT 'services',
    line_type                document.commercial_line_type_d NOT NULL DEFAULT 'noncatalog',
    uom_code                 text        NOT NULL,
    quantity                 numeric(18,4) NOT NULL,
    unit_price               numeric(18,4) NOT NULL,
    price_unit               numeric(18,4) NOT NULL DEFAULT 1,
    currency_code            character(3) NOT NULL,
    net_amount               numeric(18,4) GENERATED ALWAYS AS (quantity * unit_price / price_unit) STORED,
    service_period_start     date,
    service_period_end       date,
    completion_pct           numeric(7,4),
    milestone_name           text,
    tax_group_id             uuid,
    tax_amount               numeric(18,4) NOT NULL DEFAULT 0,
    withholding_tax_group_id uuid,
    withholding_tax_amount   numeric(18,4) NOT NULL DEFAULT 0,
    to_tax_jurisdiction_id   uuid,
    from_tax_jurisdiction_id uuid,
    gross_amount             numeric(18,4) GENERATED ALWAYS AS (quantity * unit_price / price_unit + tax_amount - withholding_tax_amount) STORED,
    site_id                  uuid,
    warehouse_id             uuid,
    storage_location_code    text,
    ship_to_address_id       uuid,
    bill_to_address_id       uuid,
    bill_from_address_id     uuid,
    supplier_id              uuid,
    ship_from_address_id     uuid,
    remit_to_address_id      uuid,
    metadata                 jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at               timestamptz NOT NULL DEFAULT now(),
    created_by               uuid        NOT NULL,
    updated_at               timestamptz,
    updated_by               uuid,
    CONSTRAINT service_sheet_line_pkey PRIMARY KEY (id),
    CONSTRAINT service_sheet_line_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT service_sheet_line_parent_no_uq UNIQUE (tenant_id, service_sheet_id, line_no),
    CONSTRAINT service_sheet_line_no_chk CHECK (line_no > 0),
    CONSTRAINT service_sheet_line_description_chk CHECK (btrim(item_description) <> ''),
    CONSTRAINT service_sheet_line_quantity_chk CHECK (quantity > 0),
    CONSTRAINT service_sheet_line_price_chk CHECK (unit_price >= 0 AND price_unit > 0),
    CONSTRAINT service_sheet_line_period_chk CHECK (
        (service_period_start IS NULL) = (service_period_end IS NULL)
        AND (service_period_end IS NULL OR service_period_end >= service_period_start)
    ),
    CONSTRAINT service_sheet_line_completion_chk CHECK (completion_pct IS NULL OR completion_pct BETWEEN 0 AND 100),
    CONSTRAINT service_sheet_line_tax_chk CHECK (tax_amount >= 0 AND withholding_tax_amount >= 0),
    CONSTRAINT service_sheet_line_warehouse_chk CHECK (warehouse_id IS NULL OR site_id IS NOT NULL),
    CONSTRAINT service_sheet_line_json_chk CHECK (jsonb_typeof(metadata) = 'object'),
    CONSTRAINT service_sheet_line_audit_pair_chk CHECK ((updated_at IS NULL) = (updated_by IS NULL))
);
