ALTER TABLE document.purchase_requisition
    ADD CONSTRAINT pr_tenant_fk FOREIGN KEY (tenant_id) REFERENCES master.tenant(id),
    ADD CONSTRAINT pr_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT pr_requested_by_fk FOREIGN KEY (tenant_id, requested_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT pr_responsible_fk FOREIGN KEY (tenant_id, responsible_principal_id) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT pr_currency_fk FOREIGN KEY (currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT pr_base_currency_fk FOREIGN KEY (base_currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT pr_period_fk FOREIGN KEY (tenant_id, fiscal_period_id) REFERENCES master.fiscal_period(tenant_id, id),
    ADD CONSTRAINT pr_journal_fk FOREIGN KEY (tenant_id, encumbrance_journal_entry_id) REFERENCES document.journal_entry(tenant_id, id),
    ADD CONSTRAINT pr_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request(tenant_id, id),
    ADD CONSTRAINT pr_approved_by_fk FOREIGN KEY (tenant_id, approved_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT pr_status_by_fk FOREIGN KEY (tenant_id, status_changed_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT pr_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT pr_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.purchase_requisition_line
    ADD CONSTRAINT prl_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT prl_header_fk FOREIGN KEY (tenant_id, purchase_requisition_id) REFERENCES document.purchase_requisition(tenant_id, id) ON DELETE CASCADE,
    ADD CONSTRAINT prl_item_fk FOREIGN KEY (tenant_id, item_id) REFERENCES master.item(tenant_id, id),
    ADD CONSTRAINT prl_commodity_fk FOREIGN KEY (tenant_id, commodity_category_id) REFERENCES master.commodity_category(tenant_id, id),
    ADD CONSTRAINT prl_intent_fk FOREIGN KEY (tenant_id, business_intent_id) REFERENCES master.business_intent(tenant_id, id),
    ADD CONSTRAINT prl_asset_class_fk FOREIGN KEY (tenant_id, asset_class_id) REFERENCES master.asset_class(tenant_id, id),
    ADD CONSTRAINT prl_uom_fk FOREIGN KEY (uom_code) REFERENCES shared.uom(code),
    ADD CONSTRAINT prl_currency_fk FOREIGN KEY (currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT prl_tax_group_fk FOREIGN KEY (tenant_id, tax_group_id) REFERENCES control.tax_group(tenant_id, id),
    ADD CONSTRAINT prl_wht_group_fk FOREIGN KEY (tenant_id, withholding_tax_group_id) REFERENCES control.tax_group(tenant_id, id),
    ADD CONSTRAINT prl_to_jurisdiction_fk FOREIGN KEY (tenant_id, to_tax_jurisdiction_id) REFERENCES master.tax_jurisdiction(tenant_id, id),
    ADD CONSTRAINT prl_from_jurisdiction_fk FOREIGN KEY (tenant_id, from_tax_jurisdiction_id) REFERENCES master.tax_jurisdiction(tenant_id, id),
    ADD CONSTRAINT prl_site_fk FOREIGN KEY (tenant_id, site_id) REFERENCES master.site(tenant_id, id),
    ADD CONSTRAINT prl_warehouse_fk FOREIGN KEY (tenant_id, site_id, warehouse_id) REFERENCES master.warehouse(tenant_id, site_id, id),
    ADD CONSTRAINT prl_suggested_supplier_fk FOREIGN KEY (tenant_id, suggested_supplier_id) REFERENCES master.supplier(tenant_id, id),
    ADD CONSTRAINT prl_ship_to_fk FOREIGN KEY (tenant_id, ship_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT prl_bill_to_fk FOREIGN KEY (tenant_id, bill_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT prl_bill_from_fk FOREIGN KEY (tenant_id, bill_from_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT prl_ship_from_fk FOREIGN KEY (tenant_id, ship_from_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT prl_remit_to_fk FOREIGN KEY (tenant_id, remit_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT prl_status_by_fk FOREIGN KEY (tenant_id, status_changed_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT prl_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT prl_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.purchase_order_confirmation
    ADD CONSTRAINT poc_tenant_fk FOREIGN KEY (tenant_id) REFERENCES master.tenant(id),
    ADD CONSTRAINT poc_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT poc_commitment_fk FOREIGN KEY (tenant_id, commitment_id) REFERENCES document.commitment(tenant_id, id),
    ADD CONSTRAINT poc_supplier_fk FOREIGN KEY (tenant_id, supplier_id) REFERENCES master.supplier(tenant_id, id),
    ADD CONSTRAINT poc_amendment_fk FOREIGN KEY (tenant_id, amendment_commitment_id) REFERENCES document.commitment(tenant_id, id),
    ADD CONSTRAINT poc_currency_fk FOREIGN KEY (currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT poc_status_by_fk FOREIGN KEY (tenant_id, status_changed_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT poc_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT poc_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.purchase_order_confirmation_line
    ADD CONSTRAINT pocl_header_fk FOREIGN KEY (tenant_id, confirmation_id) REFERENCES document.purchase_order_confirmation(tenant_id, id) ON DELETE CASCADE,
    ADD CONSTRAINT pocl_commitment_line_fk FOREIGN KEY (tenant_id, commitment_line_id) REFERENCES document.commitment_line(tenant_id, id),
    ADD CONSTRAINT pocl_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.delivery_note
    ADD CONSTRAINT dn_tenant_fk FOREIGN KEY (tenant_id) REFERENCES master.tenant(id),
    ADD CONSTRAINT dn_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT dn_commitment_fk FOREIGN KEY (tenant_id, commitment_id) REFERENCES document.commitment(tenant_id, id),
    ADD CONSTRAINT dn_supplier_fk FOREIGN KEY (tenant_id, supplier_id) REFERENCES master.supplier(tenant_id, id),
    ADD CONSTRAINT dn_site_fk FOREIGN KEY (tenant_id, delivery_site_id) REFERENCES master.site(tenant_id, id),
    ADD CONSTRAINT dn_warehouse_fk FOREIGN KEY (tenant_id, delivery_site_id, delivery_warehouse_id) REFERENCES master.warehouse(tenant_id, site_id, id),
    ADD CONSTRAINT dn_currency_fk FOREIGN KEY (currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT dn_status_by_fk FOREIGN KEY (tenant_id, status_changed_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT dn_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT dn_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.delivery_note_line
    ADD CONSTRAINT dnl_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT dnl_header_fk FOREIGN KEY (tenant_id, delivery_note_id) REFERENCES document.delivery_note(tenant_id, id) ON DELETE CASCADE,
    ADD CONSTRAINT dnl_commitment_line_fk FOREIGN KEY (tenant_id, commitment_line_id) REFERENCES document.commitment_line(tenant_id, id),
    ADD CONSTRAINT dnl_item_fk FOREIGN KEY (tenant_id, item_id) REFERENCES master.item(tenant_id, id),
    ADD CONSTRAINT dnl_uom_fk FOREIGN KEY (uom_code) REFERENCES shared.uom(code),
    ADD CONSTRAINT dnl_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT dnl_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.receipt
    ADD CONSTRAINT receipt_tenant_fk FOREIGN KEY (tenant_id) REFERENCES master.tenant(id),
    ADD CONSTRAINT receipt_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT receipt_requested_by_fk FOREIGN KEY (tenant_id, requested_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT receipt_commitment_fk FOREIGN KEY (tenant_id, commitment_id) REFERENCES document.commitment(tenant_id, id),
    ADD CONSTRAINT receipt_delivery_note_fk FOREIGN KEY (tenant_id, delivery_note_id) REFERENCES document.delivery_note(tenant_id, id),
    ADD CONSTRAINT receipt_supplier_fk FOREIGN KEY (tenant_id, supplier_id) REFERENCES master.supplier(tenant_id, id),
    ADD CONSTRAINT receipt_site_fk FOREIGN KEY (tenant_id, receiving_site_id) REFERENCES master.site(tenant_id, id),
    ADD CONSTRAINT receipt_warehouse_fk FOREIGN KEY (tenant_id, receiving_site_id, receiving_warehouse_id) REFERENCES master.warehouse(tenant_id, site_id, id),
    ADD CONSTRAINT receipt_currency_fk FOREIGN KEY (currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT receipt_base_currency_fk FOREIGN KEY (base_currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT receipt_period_fk FOREIGN KEY (tenant_id, fiscal_period_id) REFERENCES master.fiscal_period(tenant_id, id),
    ADD CONSTRAINT receipt_journal_fk FOREIGN KEY (tenant_id, accrual_journal_entry_id) REFERENCES document.journal_entry(tenant_id, id),
    ADD CONSTRAINT receipt_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request(tenant_id, id),
    ADD CONSTRAINT receipt_approved_by_fk FOREIGN KEY (tenant_id, approved_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT receipt_status_by_fk FOREIGN KEY (tenant_id, status_changed_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT receipt_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT receipt_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.receipt_line
    ADD CONSTRAINT receipt_line_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT receipt_line_header_fk FOREIGN KEY (tenant_id, receipt_id) REFERENCES document.receipt(tenant_id, id) ON DELETE CASCADE,
    ADD CONSTRAINT receipt_line_commitment_fk FOREIGN KEY (tenant_id, commitment_line_id) REFERENCES document.commitment_line(tenant_id, id),
    ADD CONSTRAINT receipt_line_delivery_fk FOREIGN KEY (tenant_id, delivery_note_line_id) REFERENCES document.delivery_note_line(tenant_id, id),
    ADD CONSTRAINT receipt_line_schedule_fk FOREIGN KEY (tenant_id, source_schedule_id) REFERENCES document.schedule_line(tenant_id, id),
    ADD CONSTRAINT receipt_line_item_fk FOREIGN KEY (tenant_id, item_id) REFERENCES master.item(tenant_id, id),
    ADD CONSTRAINT receipt_line_uom_fk FOREIGN KEY (uom_code) REFERENCES shared.uom(code),
    ADD CONSTRAINT receipt_line_currency_fk FOREIGN KEY (currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT receipt_line_tax_group_fk FOREIGN KEY (tenant_id, tax_group_id) REFERENCES control.tax_group(tenant_id, id),
    ADD CONSTRAINT receipt_line_wht_group_fk FOREIGN KEY (tenant_id, withholding_tax_group_id) REFERENCES control.tax_group(tenant_id, id),
    ADD CONSTRAINT receipt_line_to_jur_fk FOREIGN KEY (tenant_id, to_tax_jurisdiction_id) REFERENCES master.tax_jurisdiction(tenant_id, id),
    ADD CONSTRAINT receipt_line_from_jur_fk FOREIGN KEY (tenant_id, from_tax_jurisdiction_id) REFERENCES master.tax_jurisdiction(tenant_id, id),
    ADD CONSTRAINT receipt_line_site_fk FOREIGN KEY (tenant_id, site_id) REFERENCES master.site(tenant_id, id),
    ADD CONSTRAINT receipt_line_warehouse_fk FOREIGN KEY (tenant_id, site_id, warehouse_id) REFERENCES master.warehouse(tenant_id, site_id, id),
    ADD CONSTRAINT receipt_line_supplier_fk FOREIGN KEY (tenant_id, supplier_id) REFERENCES master.supplier(tenant_id, id),
    ADD CONSTRAINT receipt_line_ship_to_fk FOREIGN KEY (tenant_id, ship_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT receipt_line_bill_to_fk FOREIGN KEY (tenant_id, bill_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT receipt_line_bill_from_fk FOREIGN KEY (tenant_id, bill_from_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT receipt_line_ship_from_fk FOREIGN KEY (tenant_id, ship_from_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT receipt_line_remit_to_fk FOREIGN KEY (tenant_id, remit_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT receipt_line_asset_class_fk FOREIGN KEY (tenant_id, asset_class_id) REFERENCES master.asset_class(tenant_id, id),
    ADD CONSTRAINT receipt_line_movement_fk FOREIGN KEY (tenant_id, inventory_movement_id) REFERENCES ledger.inventory_movement(tenant_id, id),
    ADD CONSTRAINT receipt_line_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT receipt_line_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.service_sheet
    ADD CONSTRAINT service_sheet_tenant_fk FOREIGN KEY (tenant_id) REFERENCES master.tenant(id),
    ADD CONSTRAINT service_sheet_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT service_sheet_requested_by_fk FOREIGN KEY (tenant_id, requested_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT service_sheet_commitment_fk FOREIGN KEY (tenant_id, commitment_id) REFERENCES document.commitment(tenant_id, id),
    ADD CONSTRAINT service_sheet_supplier_fk FOREIGN KEY (tenant_id, supplier_id) REFERENCES master.supplier(tenant_id, id),
    ADD CONSTRAINT service_sheet_currency_fk FOREIGN KEY (currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT service_sheet_base_currency_fk FOREIGN KEY (base_currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT service_sheet_period_fk FOREIGN KEY (tenant_id, fiscal_period_id) REFERENCES master.fiscal_period(tenant_id, id),
    ADD CONSTRAINT service_sheet_journal_fk FOREIGN KEY (tenant_id, accrual_journal_entry_id) REFERENCES document.journal_entry(tenant_id, id),
    ADD CONSTRAINT service_sheet_accepted_by_fk FOREIGN KEY (tenant_id, accepted_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT service_sheet_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request(tenant_id, id),
    ADD CONSTRAINT service_sheet_approved_by_fk FOREIGN KEY (tenant_id, approved_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT service_sheet_status_by_fk FOREIGN KEY (tenant_id, status_changed_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT service_sheet_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT service_sheet_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);

ALTER TABLE document.service_sheet_line
    ADD CONSTRAINT service_sheet_line_company_fk FOREIGN KEY (tenant_id, company_code_id) REFERENCES master.company_code(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_header_fk FOREIGN KEY (tenant_id, service_sheet_id) REFERENCES document.service_sheet(tenant_id, id) ON DELETE CASCADE,
    ADD CONSTRAINT service_sheet_line_commitment_fk FOREIGN KEY (tenant_id, commitment_line_id) REFERENCES document.commitment_line(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_schedule_fk FOREIGN KEY (tenant_id, source_schedule_id) REFERENCES document.schedule_line(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_item_fk FOREIGN KEY (tenant_id, item_id) REFERENCES master.item(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_uom_fk FOREIGN KEY (uom_code) REFERENCES shared.uom(code),
    ADD CONSTRAINT service_sheet_line_currency_fk FOREIGN KEY (currency_code) REFERENCES shared.currency(code),
    ADD CONSTRAINT service_sheet_line_tax_group_fk FOREIGN KEY (tenant_id, tax_group_id) REFERENCES control.tax_group(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_wht_group_fk FOREIGN KEY (tenant_id, withholding_tax_group_id) REFERENCES control.tax_group(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_to_jur_fk FOREIGN KEY (tenant_id, to_tax_jurisdiction_id) REFERENCES master.tax_jurisdiction(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_from_jur_fk FOREIGN KEY (tenant_id, from_tax_jurisdiction_id) REFERENCES master.tax_jurisdiction(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_site_fk FOREIGN KEY (tenant_id, site_id) REFERENCES master.site(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_warehouse_fk FOREIGN KEY (tenant_id, site_id, warehouse_id) REFERENCES master.warehouse(tenant_id, site_id, id),
    ADD CONSTRAINT service_sheet_line_supplier_fk FOREIGN KEY (tenant_id, supplier_id) REFERENCES master.supplier(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_ship_to_fk FOREIGN KEY (tenant_id, ship_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_bill_to_fk FOREIGN KEY (tenant_id, bill_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_bill_from_fk FOREIGN KEY (tenant_id, bill_from_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_ship_from_fk FOREIGN KEY (tenant_id, ship_from_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_remit_to_fk FOREIGN KEY (tenant_id, remit_to_address_id) REFERENCES master.address(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_created_by_fk FOREIGN KEY (tenant_id, created_by) REFERENCES master.principal(tenant_id, id),
    ADD CONSTRAINT service_sheet_line_updated_by_fk FOREIGN KEY (tenant_id, updated_by) REFERENCES master.principal(tenant_id, id);
