import {createHash} from "node:crypto";
import {BUSINESS_PARTNER_360_COMPLETENESS_PACK_CODES,type BusinessPartner360CompletenessActionCode,type BusinessPartner360CompletenessPackCode,type BusinessPartner360CompletenessSummary,type BusinessPartner360GovernedAction,type BusinessPartner360RequirementDefinition,type BusinessPartner360RequirementPackDefinition,type BusinessPartner360RequirementResult,type BusinessPartner360RoleLens} from "@athyper/server-contract-master-data";

export type BusinessPartner360EvidenceState="missing"|"present"|"verified"|"restricted_verified";
export type BusinessPartner360CompletenessEvidence=Readonly<Record<string,Readonly<{state:BusinessPartner360EvidenceState;fingerprint:string}>>>;
export interface BusinessPartner360ResolvedDefinition{readonly code:"business_partner.onboarding";readonly version:string;readonly hash:string;readonly packs:readonly BusinessPartner360RequirementPackDefinition[];}

export function parseBusinessPartner360Definition(input:{readonly version:string;readonly hash:string;readonly view:unknown}):BusinessPartner360ResolvedDefinition{
 const view=record(input.view),raw=view["completenessPacks"];
 if(view["schemaVersion"]!==1||!Array.isArray(raw)||!Array.isArray(view["excludedCapabilities"])||!view["excludedCapabilities"].includes("risk"))throw new Error("BP_360_DEFINITION_INCOMPATIBLE");
 const serialized=JSON.stringify(raw);if(/risk/i.test(serialized))throw new Error("BP_360_DEFINITION_RISK_PROHIBITED");
 const packs=raw.map(parsePack),codes=new Set(packs.map(pack=>pack.code));
 if(BUSINESS_PARTNER_360_COMPLETENESS_PACK_CODES.some(code=>!codes.has(code))||codes.size!==BUSINESS_PARTNER_360_COMPLETENESS_PACK_CODES.length)throw new Error("BP_360_DEFINITION_INCOMPATIBLE");
 return{code:"business_partner.onboarding",version:input.version,hash:input.hash,packs};
}

export function evaluateBusinessPartner360Completeness(input:{readonly definition:BusinessPartner360ResolvedDefinition;readonly category:"organization";readonly roles:readonly ("supplier"|"customer"|"workforce")[];readonly roleLens:BusinessPartner360RoleLens;readonly hasOrganizationScope:boolean;readonly hasCompanyScope:boolean;readonly hasWorkforceScope:boolean;readonly asOf:string;readonly historical:boolean;readonly businessPartnerVersion:number;readonly policyFingerprint:string;readonly evidence:BusinessPartner360CompletenessEvidence;readonly actions:Readonly<Partial<Record<BusinessPartner360CompletenessActionCode,BusinessPartner360GovernedAction>>>;readonly evaluatedAt:string;}):BusinessPartner360CompletenessSummary{
 const roles=input.roleLens==="all"?input.roles:input.roles.filter(role=>role===input.roleLens);
 const packs=input.definition.packs.filter(pack=>pack.category===input.category&&(!pack.role||roles.includes(pack.role))&&scopeApplies(pack,input));
 const required:BusinessPartner360RequirementResult[]=[],recommended:BusinessPartner360RequirementResult[]=[];
 for(const pack of packs)for(const requirement of pack.requirements){const fact=input.evidence[requirement.fieldCode],satisfied=Boolean(fact&&fact.state!=="missing"&&(!requirement.requiresVerified||fact.state==="verified"||fact.state==="restricted_verified")),state=satisfied?(fact?.state==="restricted_verified"?"restricted_satisfied":"satisfied"):"missing",result:BusinessPartner360RequirementResult={code:requirement.code,label:requirement.label,fieldCode:requirement.fieldCode,sectionCode:requirement.sectionCode,state,...(state==="missing"&&!input.historical&&input.actions[requirement.actionCode]?{action:input.actions[requirement.actionCode]}:{})};(requirement.severity==="required"?required:recommended).push(result);}
 const completeCount=required.filter(item=>item.state!=="missing").length,restrictedCount=[...required,...recommended].filter(item=>item.state==="restricted_satisfied").length,missing=[...required.map(item=>({item,severity:"required" as const})),...recommended.map(item=>({item,severity:"recommended" as const}))].filter(({item})=>item.state==="missing").map(({item,severity})=>({code:item.code,sectionCode:item.sectionCode,severity,...(item.action?{action:item.action}:{})}));
 const fingerprint=hash({definition:input.definition.hash,packs:packs.map(pack=>[pack.code,pack.version]),category:input.category,roles,scope:{organization:input.hasOrganizationScope,company:input.hasCompanyScope,workforce:input.hasWorkforceScope},asOf:input.asOf,policy:input.policyFingerprint,evidence:Object.fromEntries([...required,...recommended].map(item=>[item.fieldCode,input.evidence[item.fieldCode]??{state:"missing",fingerprint:"missing"}]))});
 return{status:required.length===0?"not_applicable":completeCount===required.length?"complete":"incomplete",percent:required.length?Math.round(completeCount/required.length*100):100,requiredCount:required.length,completeCount,restrictedCount,required,recommended,packs:packs.map(pack=>({code:pack.code,version:pack.version})),readOnly:input.historical,missing,evaluatedAt:input.evaluatedAt,definitionVersion:input.definition.version,definitionHash:input.definition.hash,fingerprint};
}

export function unavailableBusinessPartner360Completeness(evaluatedAt:string,historical:boolean):BusinessPartner360CompletenessSummary{return{status:"definition_unavailable",percent:0,requiredCount:0,completeCount:0,restrictedCount:0,required:[],recommended:[],packs:[],readOnly:historical,missing:[],evaluatedAt,definitionVersion:"unavailable",definitionHash:"0".repeat(64),fingerprint:hash({status:"definition_unavailable"})};}

function scopeApplies(pack:BusinessPartner360RequirementPackDefinition,input:{hasOrganizationScope:boolean;hasCompanyScope:boolean;hasWorkforceScope:boolean}){return pack.scope==="global"||pack.scope==="organization"||pack.scope==="workforce"||(pack.scope==="company"&&(input.hasOrganizationScope||input.hasCompanyScope));}
function parsePack(value:unknown):BusinessPartner360RequirementPackDefinition{const pack=record(value),code=String(pack["code"]) as BusinessPartner360CompletenessPackCode;if(!BUSINESS_PARTNER_360_COMPLETENESS_PACK_CODES.includes(code)||!Number.isSafeInteger(pack["version"])||!Array.isArray(pack["requirements"])||!(["organization"] as const).includes(pack["category"] as never)||!(["global","organization","company","workforce"] as const).includes(pack["scope"] as never))throw new Error("BP_360_DEFINITION_INCOMPATIBLE");return{code,version:Number(pack["version"]),category:pack["category"] as "organization",...(pack["role"]?{role:String(pack["role"]) as "supplier"|"customer"|"workforce"}:{}),scope:pack["scope"] as BusinessPartner360RequirementPackDefinition["scope"],requirements:pack["requirements"].map(parseRequirement)};}
function parseRequirement(value:unknown):BusinessPartner360RequirementDefinition{const item=record(value),actionCode=String(item["actionCode"]) as BusinessPartner360CompletenessActionCode;if(!/^[a-z][a-z0-9_.-]+$/.test(String(item["code"]))||!/^[a-z][A-Za-z0-9_.-]+$/.test(String(item["fieldCode"]))||!(item["severity"]==="required"||item["severity"]==="recommended")||!(["amend_partner","add_role","assign_organization","configure_company","change_bank","lifecycle","qualification","certification"] as const).includes(actionCode))throw new Error("BP_360_DEFINITION_INCOMPATIBLE");return{code:String(item["code"]),fieldCode:String(item["fieldCode"]),sectionCode:String(item["sectionCode"]) as BusinessPartner360RequirementDefinition["sectionCode"],severity:item["severity"],requiresVerified:item["requiresVerified"]===true,actionCode,label:String(item["label"])};}
function record(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("BP_360_DEFINITION_INCOMPATIBLE");return value as Record<string,unknown>;}
function hash(value:unknown){return createHash("sha256").update(JSON.stringify(value)).digest("hex");}
