// Generated by pnpm openapi:bp360:generate from the shared response interfaces. Do not edit.
export const bp360ResponseSchemas = {
  "BusinessPartner360Summary": {
    "type": "object",
    "properties": {
      "collaboration": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "canComment": {
                "type": "boolean"
              }
            },
            "required": [
              "canComment"
            ],
            "additionalProperties": true
          }
        ]
      },
      "directoryScope": {
        "anyOf": [
          {
            "const": "company",
            "type": "string"
          },
          {
            "const": "organization",
            "type": "string"
          },
          {
            "const": "organization_company",
            "type": "string"
          },
          {
            "const": "tenant",
            "type": "string"
          }
        ]
      },
      "recordHeader": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "relatedActions": {
                "anyOf": [
                  {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "operationKey": {
                          "type": "string"
                        },
                        "href": {
                          "type": "string"
                        },
                        "decision": {
                          "anyOf": [
                            {
                              "type": "object",
                              "properties": {
                                "schemaVersion": {
                                  "const": 1,
                                  "type": "number"
                                },
                                "state": {
                                  "anyOf": [
                                    {
                                      "const": "allowed",
                                      "type": "string"
                                    },
                                    {
                                      "const": "context_required",
                                      "type": "string"
                                    },
                                    {
                                      "const": "denied",
                                      "type": "string"
                                    },
                                    {
                                      "const": "not_applicable",
                                      "type": "string"
                                    },
                                    {
                                      "const": "preflight_required",
                                      "type": "string"
                                    },
                                    {
                                      "const": "unavailable",
                                      "type": "string"
                                    },
                                    {
                                      "const": "verification_required",
                                      "type": "string"
                                    },
                                    {
                                      "const": "workflow_blocked",
                                      "type": "string"
                                    }
                                  ]
                                },
                                "reasonCode": {
                                  "anyOf": [
                                    {
                                      "const": "ACCESS_DENIED",
                                      "type": "string"
                                    },
                                    {
                                      "const": "AUTHORIZED",
                                      "type": "string"
                                    },
                                    {
                                      "const": "CONTEXT_REQUIRED",
                                      "type": "string"
                                    },
                                    {
                                      "const": "NOT_APPLICABLE",
                                      "type": "string"
                                    },
                                    {
                                      "const": "POLICY_UNAVAILABLE",
                                      "type": "string"
                                    },
                                    {
                                      "const": "PREFLIGHT_REQUIRED",
                                      "type": "string"
                                    },
                                    {
                                      "const": "VERIFICATION_REQUIRED",
                                      "type": "string"
                                    },
                                    {
                                      "const": "WORKFLOW_BLOCKED",
                                      "type": "string"
                                    }
                                  ]
                                },
                                "operationKey": {
                                  "type": "string"
                                },
                                "authorityRevision": {
                                  "type": "string"
                                },
                                "decisionRef": {
                                  "type": "string"
                                },
                                "missingCoordinates": {
                                  "anyOf": [
                                    {
                                      "type": "array",
                                      "items": {
                                        "type": "string"
                                      }
                                    }
                                  ]
                                }
                              },
                              "required": [
                                "schemaVersion",
                                "state",
                                "reasonCode",
                                "operationKey",
                                "authorityRevision",
                                "decisionRef"
                              ],
                              "additionalProperties": true
                            }
                          ]
                        }
                      },
                      "required": [
                        "operationKey",
                        "href"
                      ],
                      "additionalProperties": true
                    }
                  }
                ]
              },
              "related": {
                "anyOf": [
                  {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "schemaVersion": {
                          "const": 1,
                          "type": "number"
                        },
                        "key": {
                          "type": "string"
                        },
                        "sectionKey": {
                          "type": "string"
                        },
                        "source": {
                          "anyOf": [
                            {
                              "const": "address-link.v1",
                              "type": "string"
                            },
                            {
                              "const": "contact-person.v1",
                              "type": "string"
                            },
                            {
                              "const": "external-reference.v1",
                              "type": "string"
                            }
                          ]
                        },
                        "titleField": {
                          "type": "string"
                        },
                        "titleLabel": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "emptyLabel": {
                          "type": "string"
                        },
                        "compactEmptyLabel": {
                          "type": "string"
                        },
                        "viewAllLabel": {
                          "type": "string"
                        },
                        "scopeLabel": {
                          "type": "string"
                        },
                        "collectionOrder": {
                          "anyOf": [
                            {
                              "const": "newest-first",
                              "type": "string"
                            },
                            {
                              "const": "primary-first",
                              "type": "string"
                            }
                          ]
                        },
                        "emptyFields": {
                          "anyOf": [
                            {
                              "const": "disclose",
                              "type": "string"
                            },
                            {
                              "const": "hide",
                              "type": "string"
                            }
                          ]
                        },
                        "summary": {
                          "anyOf": [
                            {
                              "type": "object",
                              "properties": {
                                "layout": {
                                  "anyOf": [
                                    {
                                      "const": "contact-summary",
                                      "type": "string"
                                    },
                                    {
                                      "const": "postal-summary",
                                      "type": "string"
                                    }
                                  ]
                                },
                                "fields": {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                },
                                "copyLabel": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "layout",
                                "fields",
                                "copyLabel"
                              ],
                              "additionalProperties": true
                            }
                          ]
                        },
                        "detail": {
                          "anyOf": [
                            {
                              "type": "object",
                              "properties": {
                                "layout": {
                                  "anyOf": [
                                    {
                                      "const": "contact-detail",
                                      "type": "string"
                                    },
                                    {
                                      "const": "postal-detail",
                                      "type": "string"
                                    },
                                    {
                                      "const": "reference-detail",
                                      "type": "string"
                                    }
                                  ]
                                },
                                "headerFields": {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                },
                                "copyLabel": {
                                  "type": "string"
                                },
                                "additionalFieldsLabel": {
                                  "type": "string"
                                }
                              },
                              "required": [
                                "layout",
                                "headerFields",
                                "copyLabel",
                                "additionalFieldsLabel"
                              ],
                              "additionalProperties": true
                            }
                          ]
                        },
                        "groups": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "key": {
                                "type": "string"
                              },
                              "label": {
                                "type": "string"
                              },
                              "compact": {
                                "type": "boolean"
                              },
                              "collapsed": {
                                "type": "boolean"
                              },
                              "renderer": {
                                "anyOf": [
                                  {
                                    "const": "channels",
                                    "type": "string"
                                  },
                                  {
                                    "const": "fields",
                                    "type": "string"
                                  },
                                  {
                                    "const": "postal-address",
                                    "type": "string"
                                  },
                                  {
                                    "const": "timeline",
                                    "type": "string"
                                  }
                                ]
                              },
                              "fields": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "key": {
                                      "type": "string"
                                    },
                                    "field": {
                                      "type": "string"
                                    },
                                    "label": {
                                      "type": "string"
                                    },
                                    "renderer": {
                                      "anyOf": [
                                        {
                                          "const": "badge",
                                          "type": "string"
                                        },
                                        {
                                          "const": "boolean",
                                          "type": "string"
                                        },
                                        {
                                          "const": "country",
                                          "type": "string"
                                        },
                                        {
                                          "const": "date",
                                          "type": "string"
                                        },
                                        {
                                          "const": "datetime",
                                          "type": "string"
                                        },
                                        {
                                          "const": "lookup",
                                          "type": "string"
                                        },
                                        {
                                          "const": "text",
                                          "type": "string"
                                        }
                                      ]
                                    },
                                    "lookup": {
                                      "anyOf": [
                                        {
                                          "type": "object",
                                          "properties": {
                                            "scopeField": {
                                              "type": "string"
                                            },
                                            "values": {
                                              "type": "object",
                                              "properties": {},
                                              "additionalProperties": {
                                                "type": "object",
                                                "properties": {},
                                                "additionalProperties": {
                                                  "type": "string"
                                                }
                                              }
                                            }
                                          },
                                          "required": [
                                            "scopeField",
                                            "values"
                                          ],
                                          "additionalProperties": true
                                        }
                                      ]
                                    },
                                    "values": {
                                      "anyOf": [
                                        {
                                          "type": "object",
                                          "properties": {},
                                          "additionalProperties": {
                                            "type": "object",
                                            "properties": {
                                              "label": {
                                                "type": "string"
                                              },
                                              "tone": {
                                                "anyOf": [
                                                  {
                                                    "const": "danger",
                                                    "type": "string"
                                                  },
                                                  {
                                                    "const": "neutral",
                                                    "type": "string"
                                                  },
                                                  {
                                                    "const": "success",
                                                    "type": "string"
                                                  },
                                                  {
                                                    "const": "warning",
                                                    "type": "string"
                                                  }
                                                ]
                                              }
                                            },
                                            "required": [
                                              "label"
                                            ],
                                            "additionalProperties": true
                                          }
                                        }
                                      ]
                                    }
                                  },
                                  "required": [
                                    "key",
                                    "field",
                                    "label",
                                    "renderer"
                                  ],
                                  "additionalProperties": true
                                }
                              },
                              "detail": {
                                "anyOf": [
                                  {
                                    "type": "object",
                                    "properties": {
                                      "placement": {
                                        "anyOf": [
                                          {
                                            "const": "aside",
                                            "type": "string"
                                          },
                                          {
                                            "const": "footer",
                                            "type": "string"
                                          },
                                          {
                                            "const": "main",
                                            "type": "string"
                                          }
                                        ]
                                      },
                                      "showLabel": {
                                        "type": "boolean"
                                      },
                                      "omitFields": {
                                        "type": "array",
                                        "items": {
                                          "type": "string"
                                        }
                                      },
                                      "columnWeights": {
                                        "type": "array",
                                        "items": {
                                          "type": "number"
                                        }
                                      }
                                    },
                                    "required": [
                                      "placement",
                                      "showLabel",
                                      "omitFields",
                                      "columnWeights"
                                    ],
                                    "additionalProperties": true
                                  }
                                ]
                              }
                            },
                            "required": [
                              "key",
                              "label",
                              "compact",
                              "collapsed",
                              "renderer",
                              "fields"
                            ],
                            "additionalProperties": true
                          }
                        },
                        "actions": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "key": {
                                "type": "string"
                              },
                              "label": {
                                "type": "string"
                              },
                              "operationKey": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "key",
                              "label",
                              "operationKey"
                            ],
                            "additionalProperties": true
                          }
                        }
                      },
                      "required": [
                        "schemaVersion",
                        "key",
                        "sectionKey",
                        "source",
                        "titleField",
                        "emptyLabel",
                        "compactEmptyLabel",
                        "viewAllLabel",
                        "scopeLabel",
                        "emptyFields",
                        "groups",
                        "actions"
                      ],
                      "additionalProperties": true
                    }
                  }
                ]
              },
              "panel": {
                "anyOf": [
                  {
                    "type": "object",
                    "properties": {
                      "schemaVersion": {
                        "const": 1,
                        "type": "number"
                      },
                      "kind": {
                        "const": "360",
                        "type": "string"
                      },
                      "sections": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      },
                      "tabs": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "key": {
                              "type": "string"
                            },
                            "label": {
                              "type": "string"
                            },
                            "provider": {
                              "anyOf": [
                                {
                                  "const": "360",
                                  "type": "string"
                                },
                                {
                                  "const": "section",
                                  "type": "string"
                                }
                              ]
                            },
                            "sectionKey": {
                              "anyOf": [
                                {
                                  "type": "string"
                                }
                              ]
                            }
                          },
                          "required": [
                            "key",
                            "label",
                            "provider"
                          ],
                          "additionalProperties": true
                        }
                      },
                      "sidebar": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "key": {
                              "type": "string"
                            },
                            "label": {
                              "type": "string"
                            },
                            "provider": {
                              "anyOf": [
                                {
                                  "const": "primary-address",
                                  "type": "string"
                                },
                                {
                                  "const": "primary-contact",
                                  "type": "string"
                                }
                              ]
                            }
                          },
                          "required": [
                            "key",
                            "label",
                            "provider"
                          ],
                          "additionalProperties": true
                        }
                      }
                    },
                    "required": [
                      "schemaVersion",
                      "kind",
                      "sections",
                      "tabs",
                      "sidebar"
                    ],
                    "additionalProperties": true
                  }
                ]
              },
              "title": {
                "type": "string"
              },
              "entityLabel": {
                "type": "string"
              },
              "iconKey": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "code": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "description": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "badges": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "label": {
                      "type": "string"
                    },
                    "tone": {
                      "anyOf": [
                        {
                          "const": "danger",
                          "type": "string"
                        },
                        {
                          "const": "neutral",
                          "type": "string"
                        },
                        {
                          "const": "success",
                          "type": "string"
                        },
                        {
                          "const": "warning",
                          "type": "string"
                        }
                      ]
                    }
                  },
                  "required": [
                    "label",
                    "tone"
                  ],
                  "additionalProperties": true
                }
              },
              "context": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "label": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "key",
                    "label",
                    "value"
                  ],
                  "additionalProperties": true
                }
              },
              "actions": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "label": {
                      "type": "string"
                    },
                    "href": {
                      "anyOf": [
                        {
                          "type": "string"
                        }
                      ]
                    },
                    "placement": {
                      "anyOf": [
                        {
                          "const": "overflow",
                          "type": "string"
                        },
                        {
                          "const": "primary",
                          "type": "string"
                        },
                        {
                          "const": "secondary",
                          "type": "string"
                        }
                      ]
                    },
                    "disabledReason": {
                      "anyOf": [
                        {
                          "type": "string"
                        }
                      ]
                    },
                    "operationKey": {
                      "anyOf": [
                        {
                          "type": "string"
                        }
                      ]
                    },
                    "decision": {
                      "anyOf": [
                        {
                          "type": "object",
                          "properties": {
                            "schemaVersion": {
                              "const": 1,
                              "type": "number"
                            },
                            "state": {
                              "anyOf": [
                                {
                                  "const": "allowed",
                                  "type": "string"
                                },
                                {
                                  "const": "context_required",
                                  "type": "string"
                                },
                                {
                                  "const": "denied",
                                  "type": "string"
                                },
                                {
                                  "const": "not_applicable",
                                  "type": "string"
                                },
                                {
                                  "const": "preflight_required",
                                  "type": "string"
                                },
                                {
                                  "const": "unavailable",
                                  "type": "string"
                                },
                                {
                                  "const": "verification_required",
                                  "type": "string"
                                },
                                {
                                  "const": "workflow_blocked",
                                  "type": "string"
                                }
                              ]
                            },
                            "reasonCode": {
                              "anyOf": [
                                {
                                  "const": "ACCESS_DENIED",
                                  "type": "string"
                                },
                                {
                                  "const": "AUTHORIZED",
                                  "type": "string"
                                },
                                {
                                  "const": "CONTEXT_REQUIRED",
                                  "type": "string"
                                },
                                {
                                  "const": "NOT_APPLICABLE",
                                  "type": "string"
                                },
                                {
                                  "const": "POLICY_UNAVAILABLE",
                                  "type": "string"
                                },
                                {
                                  "const": "PREFLIGHT_REQUIRED",
                                  "type": "string"
                                },
                                {
                                  "const": "VERIFICATION_REQUIRED",
                                  "type": "string"
                                },
                                {
                                  "const": "WORKFLOW_BLOCKED",
                                  "type": "string"
                                }
                              ]
                            },
                            "operationKey": {
                              "type": "string"
                            },
                            "authorityRevision": {
                              "type": "string"
                            },
                            "decisionRef": {
                              "type": "string"
                            },
                            "missingCoordinates": {
                              "anyOf": [
                                {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                }
                              ]
                            }
                          },
                          "required": [
                            "schemaVersion",
                            "state",
                            "reasonCode",
                            "operationKey",
                            "authorityRevision",
                            "decisionRef"
                          ],
                          "additionalProperties": true
                        }
                      ]
                    }
                  },
                  "required": [
                    "key",
                    "label",
                    "placement"
                  ],
                  "additionalProperties": true
                }
              },
              "sections": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "label": {
                      "type": "string"
                    },
                    "placement": {
                      "anyOf": [
                        {
                          "const": "direct",
                          "type": "string"
                        },
                        {
                          "const": "overflow",
                          "type": "string"
                        }
                      ]
                    },
                    "scopePrompt": {
                      "anyOf": [
                        {
                          "type": "string"
                        }
                      ]
                    },
                    "count": {
                      "anyOf": [
                        {
                          "type": "number"
                        }
                      ]
                    }
                  },
                  "required": [
                    "key",
                    "label",
                    "placement"
                  ],
                  "additionalProperties": true
                }
              },
              "readOnly": {
                "anyOf": [
                  {
                    "const": false,
                    "type": "boolean"
                  },
                  {
                    "const": true,
                    "type": "boolean"
                  }
                ]
              }
            },
            "required": [
              "title",
              "entityLabel",
              "badges",
              "context",
              "actions",
              "sections"
            ],
            "additionalProperties": true
          }
        ]
      },
      "schemaVersion": {
        "const": 1,
        "type": "number"
      },
      "asOf": {
        "type": "string"
      },
      "generatedAt": {
        "type": "string"
      },
      "businessPartnerVersion": {
        "type": "number"
      },
      "definition": {
        "type": "object",
        "properties": {
          "code": {
            "const": "business_partner.onboarding",
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "hash": {
            "type": "string"
          }
        },
        "required": [
          "code",
          "version",
          "hash"
        ],
        "additionalProperties": true
      },
      "scope": {
        "type": "object",
        "properties": {
          "businessPartnerId": {
            "type": "string"
          },
          "operatingOrganizationId": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          },
          "companyCodeId": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          },
          "legalEntityId": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          },
          "roleLens": {
            "anyOf": [
              {
                "const": "all",
                "type": "string"
              },
              {
                "const": "customer",
                "type": "string"
              },
              {
                "const": "supplier",
                "type": "string"
              }
            ]
          },
          "asOf": {
            "type": "string"
          }
        },
        "required": [
          "businessPartnerId",
          "asOf"
        ],
        "additionalProperties": true
      },
      "identity": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "code": {
            "type": "string"
          },
          "category": {
            "const": "organization",
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "lifecycleStatus": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "code",
          "category",
          "name",
          "lifecycleStatus"
        ],
        "additionalProperties": true
      },
      "roles": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "code": {
              "anyOf": [
                {
                  "const": "customer",
                  "type": "string"
                },
                {
                  "const": "supplier",
                  "type": "string"
                }
              ]
            },
            "roleCode": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "status": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "code",
            "status"
          ],
          "additionalProperties": true
        }
      },
      "primaryAddress": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "lines": {
                "anyOf": [
                  {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                ]
              },
              "id": {
                "type": "string"
              },
              "purpose": {
                "type": "string"
              },
              "line1": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "locality": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "region": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "postalCode": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "countryCode": {
                "type": "string"
              },
              "primary": {
                "type": "boolean"
              },
              "verified": {
                "type": "boolean"
              },
              "effectiveFrom": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "effectiveUntil": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "required": [
              "id",
              "purpose",
              "countryCode",
              "primary",
              "verified"
            ],
            "additionalProperties": true
          }
        ]
      },
      "primaryContact": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "displayName": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "purpose": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "email": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "phone": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "primary": {
                "type": "boolean"
              },
              "verified": {
                "type": "boolean"
              },
              "effectiveFrom": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "effectiveUntil": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "required": [
              "id",
              "primary",
              "verified"
            ],
            "additionalProperties": true
          }
        ]
      },
      "identifiers": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "schemeCode": {
              "type": "string"
            },
            "jurisdictionCode": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "maskedValue": {
              "type": "string"
            },
            "primary": {
              "type": "boolean"
            },
            "verified": {
              "type": "boolean"
            }
          },
          "required": [
            "id",
            "schemeCode",
            "maskedValue",
            "primary",
            "verified"
          ],
          "additionalProperties": true
        }
      },
      "completeness": {
        "type": "object",
        "properties": {
          "status": {
            "anyOf": [
              {
                "const": "complete",
                "type": "string"
              },
              {
                "const": "definition_unavailable",
                "type": "string"
              },
              {
                "const": "incomplete",
                "type": "string"
              },
              {
                "const": "not_applicable",
                "type": "string"
              }
            ]
          },
          "percent": {
            "type": "number"
          },
          "requiredCount": {
            "type": "number"
          },
          "completeCount": {
            "type": "number"
          },
          "restrictedCount": {
            "type": "number"
          },
          "required": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "label": {
                  "anyOf": [
                    {
                      "type": "string"
                    }
                  ]
                },
                "code": {
                  "type": "string"
                },
                "fieldCode": {
                  "type": "string"
                },
                "sectionCode": {
                  "anyOf": [
                    {
                      "const": "activity",
                      "type": "string"
                    },
                    {
                      "const": "addresses",
                      "type": "string"
                    },
                    {
                      "const": "attachments",
                      "type": "string"
                    },
                    {
                      "const": "banking",
                      "type": "string"
                    },
                    {
                      "const": "business-activity",
                      "type": "string"
                    },
                    {
                      "const": "comments",
                      "type": "string"
                    },
                    {
                      "const": "contacts",
                      "type": "string"
                    },
                    {
                      "const": "credit",
                      "type": "string"
                    },
                    {
                      "const": "customer-company",
                      "type": "string"
                    },
                    {
                      "const": "governance",
                      "type": "string"
                    },
                    {
                      "const": "identifiers-tax",
                      "type": "string"
                    },
                    {
                      "const": "identity",
                      "type": "string"
                    },
                    {
                      "const": "network",
                      "type": "string"
                    },
                    {
                      "const": "overview",
                      "type": "string"
                    },
                    {
                      "const": "qualifications-certificates",
                      "type": "string"
                    },
                    {
                      "const": "requests",
                      "type": "string"
                    },
                    {
                      "const": "roles-scope",
                      "type": "string"
                    },
                    {
                      "const": "supplier-company",
                      "type": "string"
                    }
                  ]
                },
                "state": {
                  "anyOf": [
                    {
                      "const": "missing",
                      "type": "string"
                    },
                    {
                      "const": "restricted_satisfied",
                      "type": "string"
                    },
                    {
                      "const": "satisfied",
                      "type": "string"
                    }
                  ]
                },
                "action": {
                  "anyOf": [
                    {
                      "type": "object",
                      "properties": {
                        "code": {
                          "anyOf": [
                            {
                              "const": "add_role",
                              "type": "string"
                            },
                            {
                              "const": "amend_partner",
                              "type": "string"
                            },
                            {
                              "const": "assign_organization",
                              "type": "string"
                            },
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "change_bank",
                              "type": "string"
                            },
                            {
                              "const": "configure_company",
                              "type": "string"
                            },
                            {
                              "const": "lifecycle",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "label": {
                          "type": "string"
                        },
                        "href": {
                          "type": "string"
                        },
                        "authority": {
                          "anyOf": [
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "entity_case",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "requestKind": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "permission": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "code",
                        "label",
                        "href",
                        "authority",
                        "permission"
                      ],
                      "additionalProperties": true
                    }
                  ]
                }
              },
              "required": [
                "code",
                "fieldCode",
                "sectionCode",
                "state"
              ],
              "additionalProperties": true
            }
          },
          "recommended": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "label": {
                  "anyOf": [
                    {
                      "type": "string"
                    }
                  ]
                },
                "code": {
                  "type": "string"
                },
                "fieldCode": {
                  "type": "string"
                },
                "sectionCode": {
                  "anyOf": [
                    {
                      "const": "activity",
                      "type": "string"
                    },
                    {
                      "const": "addresses",
                      "type": "string"
                    },
                    {
                      "const": "attachments",
                      "type": "string"
                    },
                    {
                      "const": "banking",
                      "type": "string"
                    },
                    {
                      "const": "business-activity",
                      "type": "string"
                    },
                    {
                      "const": "comments",
                      "type": "string"
                    },
                    {
                      "const": "contacts",
                      "type": "string"
                    },
                    {
                      "const": "credit",
                      "type": "string"
                    },
                    {
                      "const": "customer-company",
                      "type": "string"
                    },
                    {
                      "const": "governance",
                      "type": "string"
                    },
                    {
                      "const": "identifiers-tax",
                      "type": "string"
                    },
                    {
                      "const": "identity",
                      "type": "string"
                    },
                    {
                      "const": "network",
                      "type": "string"
                    },
                    {
                      "const": "overview",
                      "type": "string"
                    },
                    {
                      "const": "qualifications-certificates",
                      "type": "string"
                    },
                    {
                      "const": "requests",
                      "type": "string"
                    },
                    {
                      "const": "roles-scope",
                      "type": "string"
                    },
                    {
                      "const": "supplier-company",
                      "type": "string"
                    }
                  ]
                },
                "state": {
                  "anyOf": [
                    {
                      "const": "missing",
                      "type": "string"
                    },
                    {
                      "const": "restricted_satisfied",
                      "type": "string"
                    },
                    {
                      "const": "satisfied",
                      "type": "string"
                    }
                  ]
                },
                "action": {
                  "anyOf": [
                    {
                      "type": "object",
                      "properties": {
                        "code": {
                          "anyOf": [
                            {
                              "const": "add_role",
                              "type": "string"
                            },
                            {
                              "const": "amend_partner",
                              "type": "string"
                            },
                            {
                              "const": "assign_organization",
                              "type": "string"
                            },
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "change_bank",
                              "type": "string"
                            },
                            {
                              "const": "configure_company",
                              "type": "string"
                            },
                            {
                              "const": "lifecycle",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "label": {
                          "type": "string"
                        },
                        "href": {
                          "type": "string"
                        },
                        "authority": {
                          "anyOf": [
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "entity_case",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "requestKind": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "permission": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "code",
                        "label",
                        "href",
                        "authority",
                        "permission"
                      ],
                      "additionalProperties": true
                    }
                  ]
                }
              },
              "required": [
                "code",
                "fieldCode",
                "sectionCode",
                "state"
              ],
              "additionalProperties": true
            }
          },
          "packs": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "anyOf": [
                    {
                      "const": "customer_credit",
                      "type": "string"
                    },
                    {
                      "const": "customer_scope",
                      "type": "string"
                    },
                    {
                      "const": "organization_base",
                      "type": "string"
                    },
                    {
                      "const": "supplier_payable",
                      "type": "string"
                    },
                    {
                      "const": "supplier_scope",
                      "type": "string"
                    }
                  ]
                },
                "version": {
                  "type": "number"
                }
              },
              "required": [
                "code",
                "version"
              ],
              "additionalProperties": true
            }
          },
          "readOnly": {
            "type": "boolean"
          },
          "missing": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "sectionCode": {
                  "anyOf": [
                    {
                      "const": "activity",
                      "type": "string"
                    },
                    {
                      "const": "addresses",
                      "type": "string"
                    },
                    {
                      "const": "attachments",
                      "type": "string"
                    },
                    {
                      "const": "banking",
                      "type": "string"
                    },
                    {
                      "const": "business-activity",
                      "type": "string"
                    },
                    {
                      "const": "comments",
                      "type": "string"
                    },
                    {
                      "const": "contacts",
                      "type": "string"
                    },
                    {
                      "const": "credit",
                      "type": "string"
                    },
                    {
                      "const": "customer-company",
                      "type": "string"
                    },
                    {
                      "const": "governance",
                      "type": "string"
                    },
                    {
                      "const": "identifiers-tax",
                      "type": "string"
                    },
                    {
                      "const": "identity",
                      "type": "string"
                    },
                    {
                      "const": "network",
                      "type": "string"
                    },
                    {
                      "const": "overview",
                      "type": "string"
                    },
                    {
                      "const": "qualifications-certificates",
                      "type": "string"
                    },
                    {
                      "const": "requests",
                      "type": "string"
                    },
                    {
                      "const": "roles-scope",
                      "type": "string"
                    },
                    {
                      "const": "supplier-company",
                      "type": "string"
                    }
                  ]
                },
                "severity": {
                  "anyOf": [
                    {
                      "const": "recommended",
                      "type": "string"
                    },
                    {
                      "const": "required",
                      "type": "string"
                    }
                  ]
                },
                "action": {
                  "anyOf": [
                    {
                      "type": "object",
                      "properties": {
                        "code": {
                          "anyOf": [
                            {
                              "const": "add_role",
                              "type": "string"
                            },
                            {
                              "const": "amend_partner",
                              "type": "string"
                            },
                            {
                              "const": "assign_organization",
                              "type": "string"
                            },
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "change_bank",
                              "type": "string"
                            },
                            {
                              "const": "configure_company",
                              "type": "string"
                            },
                            {
                              "const": "lifecycle",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "label": {
                          "type": "string"
                        },
                        "href": {
                          "type": "string"
                        },
                        "authority": {
                          "anyOf": [
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "entity_case",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "requestKind": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "permission": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "code",
                        "label",
                        "href",
                        "authority",
                        "permission"
                      ],
                      "additionalProperties": true
                    }
                  ]
                }
              },
              "required": [
                "code",
                "sectionCode",
                "severity"
              ],
              "additionalProperties": true
            }
          },
          "evaluatedAt": {
            "type": "string"
          },
          "definitionVersion": {
            "type": "string"
          },
          "definitionHash": {
            "type": "string"
          },
          "fingerprint": {
            "type": "string"
          }
        },
        "required": [
          "status",
          "percent",
          "requiredCount",
          "completeCount",
          "restrictedCount",
          "required",
          "recommended",
          "packs",
          "readOnly",
          "missing",
          "evaluatedAt",
          "definitionVersion",
          "definitionHash",
          "fingerprint"
        ],
        "additionalProperties": true
      },
      "openWork": {
        "type": "object",
        "properties": {
          "activeRequestCount": {
            "anyOf": [
              {
                "type": "number"
              }
            ]
          },
          "returnedRequestCount": {
            "anyOf": [
              {
                "type": "number"
              }
            ]
          },
          "expiringQualificationCount": {
            "type": "number"
          },
          "expiringCertificateCount": {
            "type": "number"
          },
          "pendingBankVerificationCount": {
            "type": "number"
          }
        },
        "required": [
          "expiringQualificationCount",
          "expiringCertificateCount",
          "pendingBankVerificationCount"
        ],
        "additionalProperties": true
      },
      "recentActivity": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "occurredAt": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "eventCode": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "source": {
              "type": "object",
              "properties": {
                "plane": {
                  "anyOf": [
                    {
                      "const": "mesh",
                      "type": "string"
                    },
                    {
                      "const": "neon",
                      "type": "string"
                    },
                    {
                      "const": "studio",
                      "type": "string"
                    }
                  ]
                },
                "service": {
                  "type": "string"
                }
              },
              "required": [
                "plane",
                "service"
              ],
              "additionalProperties": true
            }
          },
          "required": [
            "id",
            "occurredAt",
            "category",
            "eventCode",
            "title",
            "source"
          ],
          "additionalProperties": true
        }
      },
      "sections": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "code": {
              "anyOf": [
                {
                  "const": "activity",
                  "type": "string"
                },
                {
                  "const": "addresses",
                  "type": "string"
                },
                {
                  "const": "attachments",
                  "type": "string"
                },
                {
                  "const": "banking",
                  "type": "string"
                },
                {
                  "const": "business-activity",
                  "type": "string"
                },
                {
                  "const": "comments",
                  "type": "string"
                },
                {
                  "const": "contacts",
                  "type": "string"
                },
                {
                  "const": "credit",
                  "type": "string"
                },
                {
                  "const": "customer-company",
                  "type": "string"
                },
                {
                  "const": "governance",
                  "type": "string"
                },
                {
                  "const": "identifiers-tax",
                  "type": "string"
                },
                {
                  "const": "identity",
                  "type": "string"
                },
                {
                  "const": "network",
                  "type": "string"
                },
                {
                  "const": "overview",
                  "type": "string"
                },
                {
                  "const": "qualifications-certificates",
                  "type": "string"
                },
                {
                  "const": "requests",
                  "type": "string"
                },
                {
                  "const": "roles-scope",
                  "type": "string"
                },
                {
                  "const": "supplier-company",
                  "type": "string"
                }
              ]
            },
            "applicable": {
              "type": "boolean"
            },
            "authorization": {
              "anyOf": [
                {
                  "const": "granted",
                  "type": "string"
                },
                {
                  "const": "restricted",
                  "type": "string"
                }
              ]
            },
            "state": {
              "anyOf": [
                {
                  "const": "empty",
                  "type": "string"
                },
                {
                  "const": "partial",
                  "type": "string"
                },
                {
                  "const": "ready",
                  "type": "string"
                },
                {
                  "const": "stale",
                  "type": "string"
                },
                {
                  "const": "unavailable",
                  "type": "string"
                }
              ]
            },
            "count": {
              "anyOf": [
                {
                  "type": "number"
                }
              ]
            },
            "href": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "reasonCode": {
              "anyOf": [
                {
                  "const": "BP_360_CURSOR_STALE",
                  "type": "string"
                },
                {
                  "const": "BP_360_DEFINITION_INCOMPATIBLE",
                  "type": "string"
                },
                {
                  "const": "BP_360_DEFINITION_UNAVAILABLE",
                  "type": "string"
                },
                {
                  "const": "BP_360_NOT_FOUND",
                  "type": "string"
                },
                {
                  "const": "BP_360_PROVIDER_STALE",
                  "type": "string"
                },
                {
                  "const": "BP_360_PROVIDER_UNAVAILABLE",
                  "type": "string"
                },
                {
                  "const": "BP_360_SCOPE_INVALID",
                  "type": "string"
                },
                {
                  "const": "BP_360_SCOPE_REQUIRED",
                  "type": "string"
                },
                {
                  "const": "BP_360_SECTION_FORBIDDEN",
                  "type": "string"
                },
                {
                  "const": "BP_360_SECTION_NOT_APPLICABLE",
                  "type": "string"
                }
              ]
            },
            "lastChangedAt": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "redactionClass": {
              "anyOf": [
                {
                  "const": "masked",
                  "type": "string"
                },
                {
                  "const": "none",
                  "type": "string"
                },
                {
                  "const": "presence_only",
                  "type": "string"
                }
              ]
            },
            "actions": {
              "anyOf": [
                {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "string"
                      },
                      "href": {
                        "type": "string"
                      },
                      "permission": {
                        "anyOf": [
                          {
                            "const": "collaboration.comment.read",
                            "type": "string"
                          },
                          {
                            "const": "document.attachment.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_activity.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_address.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_amend.create",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_bank.read_masked",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_bank.reveal",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_certificate.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_contact.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_credit.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_identifier.read_masked",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_identity.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_network.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_person.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_person_sensitive.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_qualification.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_tax.read_masked",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_tax.reveal",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_workforce.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.entity_case.read",
                            "type": "string"
                          }
                        ]
                      }
                    },
                    "required": [
                      "code",
                      "href",
                      "permission"
                    ],
                    "additionalProperties": true
                  }
                }
              ]
            }
          },
          "required": [
            "code",
            "applicable",
            "authorization",
            "state"
          ],
          "additionalProperties": true
        }
      },
      "provenance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "plane": {
              "anyOf": [
                {
                  "const": "mesh",
                  "type": "string"
                },
                {
                  "const": "neon",
                  "type": "string"
                },
                {
                  "const": "studio",
                  "type": "string"
                }
              ]
            },
            "service": {
              "type": "string"
            },
            "sourceObject": {
              "type": "string"
            },
            "observedAt": {
              "type": "string"
            },
            "schemaVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "projectionVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "plane",
            "service",
            "sourceObject",
            "observedAt"
          ],
          "additionalProperties": true
        }
      }
    },
    "required": [
      "schemaVersion",
      "asOf",
      "generatedAt",
      "businessPartnerVersion",
      "definition",
      "scope",
      "identity",
      "roles",
      "identifiers",
      "completeness",
      "openWork",
      "recentActivity",
      "sections",
      "provenance"
    ],
    "additionalProperties": true
  },
  "BusinessPartner360Section": {
    "type": "object",
    "properties": {
      "schemaVersion": {
        "const": 1,
        "type": "number"
      },
      "sectionCode": {
        "anyOf": [
          {
            "const": "activity",
            "type": "string"
          },
          {
            "const": "addresses",
            "type": "string"
          },
          {
            "const": "attachments",
            "type": "string"
          },
          {
            "const": "banking",
            "type": "string"
          },
          {
            "const": "business-activity",
            "type": "string"
          },
          {
            "const": "comments",
            "type": "string"
          },
          {
            "const": "contacts",
            "type": "string"
          },
          {
            "const": "credit",
            "type": "string"
          },
          {
            "const": "customer-company",
            "type": "string"
          },
          {
            "const": "governance",
            "type": "string"
          },
          {
            "const": "identifiers-tax",
            "type": "string"
          },
          {
            "const": "identity",
            "type": "string"
          },
          {
            "const": "network",
            "type": "string"
          },
          {
            "const": "overview",
            "type": "string"
          },
          {
            "const": "qualifications-certificates",
            "type": "string"
          },
          {
            "const": "requests",
            "type": "string"
          },
          {
            "const": "roles-scope",
            "type": "string"
          },
          {
            "const": "supplier-company",
            "type": "string"
          }
        ]
      },
      "asOf": {
        "type": "string"
      },
      "generatedAt": {
        "type": "string"
      },
      "businessPartnerVersion": {
        "type": "number"
      },
      "definitionHash": {
        "type": "string"
      },
      "state": {
        "anyOf": [
          {
            "const": "empty",
            "type": "string"
          },
          {
            "const": "partial",
            "type": "string"
          },
          {
            "const": "ready",
            "type": "string"
          },
          {
            "const": "stale",
            "type": "string"
          },
          {
            "const": "unavailable",
            "type": "string"
          }
        ]
      },
      "data": {},
      "page": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "nextCursor": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "limit": {
                "type": "number"
              }
            },
            "required": [
              "limit"
            ],
            "additionalProperties": true
          }
        ]
      },
      "provenance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "plane": {
              "anyOf": [
                {
                  "const": "mesh",
                  "type": "string"
                },
                {
                  "const": "neon",
                  "type": "string"
                },
                {
                  "const": "studio",
                  "type": "string"
                }
              ]
            },
            "service": {
              "type": "string"
            },
            "sourceObject": {
              "type": "string"
            },
            "observedAt": {
              "type": "string"
            },
            "schemaVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "projectionVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "plane",
            "service",
            "sourceObject",
            "observedAt"
          ],
          "additionalProperties": true
        }
      },
      "redactions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "fieldCode": {
              "type": "string"
            },
            "classification": {
              "anyOf": [
                {
                  "const": "confidential",
                  "type": "string"
                },
                {
                  "const": "highly_restricted",
                  "type": "string"
                },
                {
                  "const": "restricted",
                  "type": "string"
                }
              ]
            },
            "behavior": {
              "anyOf": [
                {
                  "const": "masked",
                  "type": "string"
                },
                {
                  "const": "omitted",
                  "type": "string"
                },
                {
                  "const": "presence_only",
                  "type": "string"
                }
              ]
            },
            "reasonCode": {
              "type": "string"
            }
          },
          "required": [
            "fieldCode",
            "classification",
            "behavior",
            "reasonCode"
          ],
          "additionalProperties": true
        }
      }
    },
    "required": [
      "schemaVersion",
      "sectionCode",
      "asOf",
      "generatedAt",
      "businessPartnerVersion",
      "definitionHash",
      "state",
      "data",
      "provenance",
      "redactions"
    ],
    "additionalProperties": true
  },
  "BusinessPartner360TaxRevealResult": {
    "type": "object",
    "properties": {
      "taxRegistrationId": {
        "type": "string"
      },
      "value": {
        "type": "string"
      },
      "expiresAt": {
        "type": "string"
      },
      "provenance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "plane": {
              "anyOf": [
                {
                  "const": "mesh",
                  "type": "string"
                },
                {
                  "const": "neon",
                  "type": "string"
                },
                {
                  "const": "studio",
                  "type": "string"
                }
              ]
            },
            "service": {
              "type": "string"
            },
            "sourceObject": {
              "type": "string"
            },
            "observedAt": {
              "type": "string"
            },
            "schemaVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "projectionVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "plane",
            "service",
            "sourceObject",
            "observedAt"
          ],
          "additionalProperties": true
        }
      }
    },
    "required": [
      "taxRegistrationId",
      "value",
      "expiresAt",
      "provenance"
    ],
    "additionalProperties": true
  },
  "BusinessPartner360BankRevealResult": {
    "type": "object",
    "properties": {
      "bankAccountLinkId": {
        "type": "string"
      },
      "value": {
        "type": "string"
      },
      "expiresAt": {
        "type": "string"
      },
      "provenance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "plane": {
              "anyOf": [
                {
                  "const": "mesh",
                  "type": "string"
                },
                {
                  "const": "neon",
                  "type": "string"
                },
                {
                  "const": "studio",
                  "type": "string"
                }
              ]
            },
            "service": {
              "type": "string"
            },
            "sourceObject": {
              "type": "string"
            },
            "observedAt": {
              "type": "string"
            },
            "schemaVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "projectionVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "plane",
            "service",
            "sourceObject",
            "observedAt"
          ],
          "additionalProperties": true
        }
      }
    },
    "required": [
      "bankAccountLinkId",
      "value",
      "expiresAt",
      "provenance"
    ],
    "additionalProperties": true
  }
} as const;
