// Generated by pnpm openapi:bp360:generate from the shared response interfaces. Do not edit.
export const bp360ResponseSchemas = {
  "BusinessPartner360Summary": {
    "type": "object",
    "properties": {
      "schemaVersion": {
        "const": 1,
        "type": "number"
      },
      "asOf": {
        "type": "string"
      },
      "generatedAt": {
        "type": "string"
      },
      "businessPartnerVersion": {
        "type": "number"
      },
      "definition": {
        "type": "object",
        "properties": {
          "code": {
            "const": "business_partner.onboarding",
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "hash": {
            "type": "string"
          }
        },
        "required": [
          "code",
          "version",
          "hash"
        ],
        "additionalProperties": true
      },
      "scope": {
        "type": "object",
        "properties": {
          "businessPartnerId": {
            "type": "string"
          },
          "operatingOrganizationId": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          },
          "companyCodeId": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          },
          "legalEntityId": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          },
          "roleLens": {
            "anyOf": [
              {
                "const": "all",
                "type": "string"
              },
              {
                "const": "customer",
                "type": "string"
              },
              {
                "const": "supplier",
                "type": "string"
              }
            ]
          },
          "asOf": {
            "type": "string"
          }
        },
        "required": [
          "businessPartnerId",
          "asOf"
        ],
        "additionalProperties": true
      },
      "identity": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "code": {
            "type": "string"
          },
          "category": {
            "anyOf": [
              {
                "const": "organization",
                "type": "string"
              },
              {
                "const": "person",
                "type": "string"
              }
            ]
          },
          "displayName": {
            "type": "string"
          },
          "legalName": {
            "anyOf": [
              {
                "type": "string"
              }
            ]
          },
          "lifecycleStatus": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "code",
          "category",
          "displayName",
          "lifecycleStatus"
        ],
        "additionalProperties": true
      },
      "roles": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "code": {
              "anyOf": [
                {
                  "const": "customer",
                  "type": "string"
                },
                {
                  "const": "supplier",
                  "type": "string"
                }
              ]
            },
            "roleCode": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "status": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "code",
            "status"
          ],
          "additionalProperties": true
        }
      },
      "primaryAddress": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "purpose": {
                "type": "string"
              },
              "line1": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "locality": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "region": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "postalCode": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "countryCode": {
                "type": "string"
              },
              "primary": {
                "type": "boolean"
              },
              "verified": {
                "type": "boolean"
              },
              "effectiveFrom": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "effectiveUntil": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "required": [
              "id",
              "purpose",
              "countryCode",
              "primary",
              "verified"
            ],
            "additionalProperties": true
          }
        ]
      },
      "primaryContact": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "displayName": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "purpose": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "email": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "phone": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "primary": {
                "type": "boolean"
              },
              "verified": {
                "type": "boolean"
              },
              "effectiveFrom": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "effectiveUntil": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              }
            },
            "required": [
              "id",
              "primary",
              "verified"
            ],
            "additionalProperties": true
          }
        ]
      },
      "identifiers": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "schemeCode": {
              "type": "string"
            },
            "jurisdictionCode": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "maskedValue": {
              "type": "string"
            },
            "primary": {
              "type": "boolean"
            },
            "verified": {
              "type": "boolean"
            }
          },
          "required": [
            "id",
            "schemeCode",
            "maskedValue",
            "primary",
            "verified"
          ],
          "additionalProperties": true
        }
      },
      "completeness": {
        "type": "object",
        "properties": {
          "status": {
            "anyOf": [
              {
                "const": "complete",
                "type": "string"
              },
              {
                "const": "definition_unavailable",
                "type": "string"
              },
              {
                "const": "incomplete",
                "type": "string"
              },
              {
                "const": "not_applicable",
                "type": "string"
              }
            ]
          },
          "percent": {
            "type": "number"
          },
          "requiredCount": {
            "type": "number"
          },
          "completeCount": {
            "type": "number"
          },
          "restrictedCount": {
            "type": "number"
          },
          "required": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "fieldCode": {
                  "type": "string"
                },
                "sectionCode": {
                  "anyOf": [
                    {
                      "const": "activity",
                      "type": "string"
                    },
                    {
                      "const": "addresses",
                      "type": "string"
                    },
                    {
                      "const": "banking",
                      "type": "string"
                    },
                    {
                      "const": "business-activity",
                      "type": "string"
                    },
                    {
                      "const": "contacts",
                      "type": "string"
                    },
                    {
                      "const": "credit",
                      "type": "string"
                    },
                    {
                      "const": "customer-company",
                      "type": "string"
                    },
                    {
                      "const": "governance",
                      "type": "string"
                    },
                    {
                      "const": "identifiers-tax",
                      "type": "string"
                    },
                    {
                      "const": "identity",
                      "type": "string"
                    },
                    {
                      "const": "network",
                      "type": "string"
                    },
                    {
                      "const": "overview",
                      "type": "string"
                    },
                    {
                      "const": "qualifications-certificates",
                      "type": "string"
                    },
                    {
                      "const": "requests",
                      "type": "string"
                    },
                    {
                      "const": "roles-scope",
                      "type": "string"
                    },
                    {
                      "const": "supplier-company",
                      "type": "string"
                    }
                  ]
                },
                "state": {
                  "anyOf": [
                    {
                      "const": "missing",
                      "type": "string"
                    },
                    {
                      "const": "restricted_satisfied",
                      "type": "string"
                    },
                    {
                      "const": "satisfied",
                      "type": "string"
                    }
                  ]
                },
                "action": {
                  "anyOf": [
                    {
                      "type": "object",
                      "properties": {
                        "code": {
                          "anyOf": [
                            {
                              "const": "add_role",
                              "type": "string"
                            },
                            {
                              "const": "amend_partner",
                              "type": "string"
                            },
                            {
                              "const": "assign_organization",
                              "type": "string"
                            },
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "change_bank",
                              "type": "string"
                            },
                            {
                              "const": "configure_company",
                              "type": "string"
                            },
                            {
                              "const": "lifecycle",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "label": {
                          "type": "string"
                        },
                        "href": {
                          "type": "string"
                        },
                        "authority": {
                          "anyOf": [
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "entity_case",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "requestKind": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "permission": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "code",
                        "label",
                        "href",
                        "authority",
                        "permission"
                      ],
                      "additionalProperties": true
                    }
                  ]
                }
              },
              "required": [
                "code",
                "fieldCode",
                "sectionCode",
                "state"
              ],
              "additionalProperties": true
            }
          },
          "recommended": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "fieldCode": {
                  "type": "string"
                },
                "sectionCode": {
                  "anyOf": [
                    {
                      "const": "activity",
                      "type": "string"
                    },
                    {
                      "const": "addresses",
                      "type": "string"
                    },
                    {
                      "const": "banking",
                      "type": "string"
                    },
                    {
                      "const": "business-activity",
                      "type": "string"
                    },
                    {
                      "const": "contacts",
                      "type": "string"
                    },
                    {
                      "const": "credit",
                      "type": "string"
                    },
                    {
                      "const": "customer-company",
                      "type": "string"
                    },
                    {
                      "const": "governance",
                      "type": "string"
                    },
                    {
                      "const": "identifiers-tax",
                      "type": "string"
                    },
                    {
                      "const": "identity",
                      "type": "string"
                    },
                    {
                      "const": "network",
                      "type": "string"
                    },
                    {
                      "const": "overview",
                      "type": "string"
                    },
                    {
                      "const": "qualifications-certificates",
                      "type": "string"
                    },
                    {
                      "const": "requests",
                      "type": "string"
                    },
                    {
                      "const": "roles-scope",
                      "type": "string"
                    },
                    {
                      "const": "supplier-company",
                      "type": "string"
                    }
                  ]
                },
                "state": {
                  "anyOf": [
                    {
                      "const": "missing",
                      "type": "string"
                    },
                    {
                      "const": "restricted_satisfied",
                      "type": "string"
                    },
                    {
                      "const": "satisfied",
                      "type": "string"
                    }
                  ]
                },
                "action": {
                  "anyOf": [
                    {
                      "type": "object",
                      "properties": {
                        "code": {
                          "anyOf": [
                            {
                              "const": "add_role",
                              "type": "string"
                            },
                            {
                              "const": "amend_partner",
                              "type": "string"
                            },
                            {
                              "const": "assign_organization",
                              "type": "string"
                            },
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "change_bank",
                              "type": "string"
                            },
                            {
                              "const": "configure_company",
                              "type": "string"
                            },
                            {
                              "const": "lifecycle",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "label": {
                          "type": "string"
                        },
                        "href": {
                          "type": "string"
                        },
                        "authority": {
                          "anyOf": [
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "entity_case",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "requestKind": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "permission": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "code",
                        "label",
                        "href",
                        "authority",
                        "permission"
                      ],
                      "additionalProperties": true
                    }
                  ]
                }
              },
              "required": [
                "code",
                "fieldCode",
                "sectionCode",
                "state"
              ],
              "additionalProperties": true
            }
          },
          "packs": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "anyOf": [
                    {
                      "const": "customer_credit",
                      "type": "string"
                    },
                    {
                      "const": "customer_scope",
                      "type": "string"
                    },
                    {
                      "const": "organization_base",
                      "type": "string"
                    },
                    {
                      "const": "person_base",
                      "type": "string"
                    },
                    {
                      "const": "supplier_payable",
                      "type": "string"
                    },
                    {
                      "const": "supplier_scope",
                      "type": "string"
                    },
                    {
                      "const": "workforce_active",
                      "type": "string"
                    }
                  ]
                },
                "version": {
                  "type": "number"
                }
              },
              "required": [
                "code",
                "version"
              ],
              "additionalProperties": true
            }
          },
          "readOnly": {
            "type": "boolean"
          },
          "missing": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "sectionCode": {
                  "anyOf": [
                    {
                      "const": "activity",
                      "type": "string"
                    },
                    {
                      "const": "addresses",
                      "type": "string"
                    },
                    {
                      "const": "banking",
                      "type": "string"
                    },
                    {
                      "const": "business-activity",
                      "type": "string"
                    },
                    {
                      "const": "contacts",
                      "type": "string"
                    },
                    {
                      "const": "credit",
                      "type": "string"
                    },
                    {
                      "const": "customer-company",
                      "type": "string"
                    },
                    {
                      "const": "governance",
                      "type": "string"
                    },
                    {
                      "const": "identifiers-tax",
                      "type": "string"
                    },
                    {
                      "const": "identity",
                      "type": "string"
                    },
                    {
                      "const": "network",
                      "type": "string"
                    },
                    {
                      "const": "overview",
                      "type": "string"
                    },
                    {
                      "const": "qualifications-certificates",
                      "type": "string"
                    },
                    {
                      "const": "requests",
                      "type": "string"
                    },
                    {
                      "const": "roles-scope",
                      "type": "string"
                    },
                    {
                      "const": "supplier-company",
                      "type": "string"
                    }
                  ]
                },
                "severity": {
                  "anyOf": [
                    {
                      "const": "recommended",
                      "type": "string"
                    },
                    {
                      "const": "required",
                      "type": "string"
                    }
                  ]
                },
                "action": {
                  "anyOf": [
                    {
                      "type": "object",
                      "properties": {
                        "code": {
                          "anyOf": [
                            {
                              "const": "add_role",
                              "type": "string"
                            },
                            {
                              "const": "amend_partner",
                              "type": "string"
                            },
                            {
                              "const": "assign_organization",
                              "type": "string"
                            },
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "change_bank",
                              "type": "string"
                            },
                            {
                              "const": "configure_company",
                              "type": "string"
                            },
                            {
                              "const": "lifecycle",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "label": {
                          "type": "string"
                        },
                        "href": {
                          "type": "string"
                        },
                        "authority": {
                          "anyOf": [
                            {
                              "const": "certification",
                              "type": "string"
                            },
                            {
                              "const": "entity_case",
                              "type": "string"
                            },
                            {
                              "const": "qualification",
                              "type": "string"
                            }
                          ]
                        },
                        "requestKind": {
                          "anyOf": [
                            {
                              "type": "string"
                            }
                          ]
                        },
                        "permission": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "code",
                        "label",
                        "href",
                        "authority",
                        "permission"
                      ],
                      "additionalProperties": true
                    }
                  ]
                }
              },
              "required": [
                "code",
                "sectionCode",
                "severity"
              ],
              "additionalProperties": true
            }
          },
          "evaluatedAt": {
            "type": "string"
          },
          "definitionVersion": {
            "type": "string"
          },
          "definitionHash": {
            "type": "string"
          },
          "fingerprint": {
            "type": "string"
          }
        },
        "required": [
          "status",
          "percent",
          "requiredCount",
          "completeCount",
          "restrictedCount",
          "required",
          "recommended",
          "packs",
          "readOnly",
          "missing",
          "evaluatedAt",
          "definitionVersion",
          "definitionHash",
          "fingerprint"
        ],
        "additionalProperties": true
      },
      "openWork": {
        "type": "object",
        "properties": {
          "activeRequestCount": {
            "type": "number"
          },
          "returnedRequestCount": {
            "type": "number"
          },
          "expiringQualificationCount": {
            "type": "number"
          },
          "expiringCertificateCount": {
            "type": "number"
          },
          "pendingBankVerificationCount": {
            "type": "number"
          }
        },
        "required": [
          "activeRequestCount",
          "returnedRequestCount",
          "expiringQualificationCount",
          "expiringCertificateCount",
          "pendingBankVerificationCount"
        ],
        "additionalProperties": true
      },
      "recentActivity": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "occurredAt": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "eventCode": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "source": {
              "type": "object",
              "properties": {
                "plane": {
                  "anyOf": [
                    {
                      "const": "mesh",
                      "type": "string"
                    },
                    {
                      "const": "neon",
                      "type": "string"
                    },
                    {
                      "const": "studio",
                      "type": "string"
                    }
                  ]
                },
                "service": {
                  "type": "string"
                }
              },
              "required": [
                "plane",
                "service"
              ],
              "additionalProperties": true
            }
          },
          "required": [
            "id",
            "occurredAt",
            "category",
            "eventCode",
            "title",
            "source"
          ],
          "additionalProperties": true
        }
      },
      "sections": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "code": {
              "anyOf": [
                {
                  "const": "activity",
                  "type": "string"
                },
                {
                  "const": "addresses",
                  "type": "string"
                },
                {
                  "const": "banking",
                  "type": "string"
                },
                {
                  "const": "business-activity",
                  "type": "string"
                },
                {
                  "const": "contacts",
                  "type": "string"
                },
                {
                  "const": "credit",
                  "type": "string"
                },
                {
                  "const": "customer-company",
                  "type": "string"
                },
                {
                  "const": "governance",
                  "type": "string"
                },
                {
                  "const": "identifiers-tax",
                  "type": "string"
                },
                {
                  "const": "identity",
                  "type": "string"
                },
                {
                  "const": "network",
                  "type": "string"
                },
                {
                  "const": "overview",
                  "type": "string"
                },
                {
                  "const": "qualifications-certificates",
                  "type": "string"
                },
                {
                  "const": "requests",
                  "type": "string"
                },
                {
                  "const": "roles-scope",
                  "type": "string"
                },
                {
                  "const": "supplier-company",
                  "type": "string"
                }
              ]
            },
            "applicable": {
              "type": "boolean"
            },
            "authorization": {
              "anyOf": [
                {
                  "const": "granted",
                  "type": "string"
                },
                {
                  "const": "restricted",
                  "type": "string"
                }
              ]
            },
            "state": {
              "anyOf": [
                {
                  "const": "empty",
                  "type": "string"
                },
                {
                  "const": "partial",
                  "type": "string"
                },
                {
                  "const": "ready",
                  "type": "string"
                },
                {
                  "const": "stale",
                  "type": "string"
                },
                {
                  "const": "unavailable",
                  "type": "string"
                }
              ]
            },
            "count": {
              "anyOf": [
                {
                  "type": "number"
                }
              ]
            },
            "href": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "reasonCode": {
              "anyOf": [
                {
                  "const": "BP_360_CURSOR_STALE",
                  "type": "string"
                },
                {
                  "const": "BP_360_DEFINITION_INCOMPATIBLE",
                  "type": "string"
                },
                {
                  "const": "BP_360_DEFINITION_UNAVAILABLE",
                  "type": "string"
                },
                {
                  "const": "BP_360_NOT_FOUND",
                  "type": "string"
                },
                {
                  "const": "BP_360_PROVIDER_STALE",
                  "type": "string"
                },
                {
                  "const": "BP_360_PROVIDER_UNAVAILABLE",
                  "type": "string"
                },
                {
                  "const": "BP_360_SCOPE_INVALID",
                  "type": "string"
                },
                {
                  "const": "BP_360_SCOPE_REQUIRED",
                  "type": "string"
                },
                {
                  "const": "BP_360_SECTION_FORBIDDEN",
                  "type": "string"
                },
                {
                  "const": "BP_360_SECTION_NOT_APPLICABLE",
                  "type": "string"
                }
              ]
            },
            "lastChangedAt": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "redactionClass": {
              "anyOf": [
                {
                  "const": "masked",
                  "type": "string"
                },
                {
                  "const": "none",
                  "type": "string"
                },
                {
                  "const": "presence_only",
                  "type": "string"
                }
              ]
            },
            "actions": {
              "anyOf": [
                {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "code": {
                        "type": "string"
                      },
                      "href": {
                        "type": "string"
                      },
                      "permission": {
                        "anyOf": [
                          {
                            "const": "neon.relationship.business_partner.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_activity.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_address.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_amend.create",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_bank.read_masked",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_bank.reveal",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_certificate.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_contact.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_credit.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_identifier.read_masked",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_identity.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_network.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_person.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_person_sensitive.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_qualification.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_tax.read_masked",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_tax.reveal",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.business_partner_workforce.read",
                            "type": "string"
                          },
                          {
                            "const": "neon.relationship.entity_case.read",
                            "type": "string"
                          }
                        ]
                      }
                    },
                    "required": [
                      "code",
                      "href",
                      "permission"
                    ],
                    "additionalProperties": true
                  }
                }
              ]
            }
          },
          "required": [
            "code",
            "applicable",
            "authorization",
            "state"
          ],
          "additionalProperties": true
        }
      },
      "provenance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "plane": {
              "anyOf": [
                {
                  "const": "mesh",
                  "type": "string"
                },
                {
                  "const": "neon",
                  "type": "string"
                },
                {
                  "const": "studio",
                  "type": "string"
                }
              ]
            },
            "service": {
              "type": "string"
            },
            "sourceObject": {
              "type": "string"
            },
            "observedAt": {
              "type": "string"
            },
            "schemaVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "projectionVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "plane",
            "service",
            "sourceObject",
            "observedAt"
          ],
          "additionalProperties": true
        }
      }
    },
    "required": [
      "schemaVersion",
      "asOf",
      "generatedAt",
      "businessPartnerVersion",
      "definition",
      "scope",
      "identity",
      "roles",
      "identifiers",
      "completeness",
      "openWork",
      "recentActivity",
      "sections",
      "provenance"
    ],
    "additionalProperties": true
  },
  "BusinessPartner360Section": {
    "type": "object",
    "properties": {
      "schemaVersion": {
        "const": 1,
        "type": "number"
      },
      "sectionCode": {
        "anyOf": [
          {
            "const": "activity",
            "type": "string"
          },
          {
            "const": "addresses",
            "type": "string"
          },
          {
            "const": "banking",
            "type": "string"
          },
          {
            "const": "business-activity",
            "type": "string"
          },
          {
            "const": "contacts",
            "type": "string"
          },
          {
            "const": "credit",
            "type": "string"
          },
          {
            "const": "customer-company",
            "type": "string"
          },
          {
            "const": "governance",
            "type": "string"
          },
          {
            "const": "identifiers-tax",
            "type": "string"
          },
          {
            "const": "identity",
            "type": "string"
          },
          {
            "const": "network",
            "type": "string"
          },
          {
            "const": "overview",
            "type": "string"
          },
          {
            "const": "qualifications-certificates",
            "type": "string"
          },
          {
            "const": "requests",
            "type": "string"
          },
          {
            "const": "roles-scope",
            "type": "string"
          },
          {
            "const": "supplier-company",
            "type": "string"
          }
        ]
      },
      "asOf": {
        "type": "string"
      },
      "generatedAt": {
        "type": "string"
      },
      "businessPartnerVersion": {
        "type": "number"
      },
      "definitionHash": {
        "type": "string"
      },
      "state": {
        "anyOf": [
          {
            "const": "empty",
            "type": "string"
          },
          {
            "const": "partial",
            "type": "string"
          },
          {
            "const": "ready",
            "type": "string"
          },
          {
            "const": "stale",
            "type": "string"
          },
          {
            "const": "unavailable",
            "type": "string"
          }
        ]
      },
      "data": {},
      "page": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "nextCursor": {
                "anyOf": [
                  {
                    "type": "string"
                  }
                ]
              },
              "limit": {
                "type": "number"
              }
            },
            "required": [
              "limit"
            ],
            "additionalProperties": true
          }
        ]
      },
      "provenance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "plane": {
              "anyOf": [
                {
                  "const": "mesh",
                  "type": "string"
                },
                {
                  "const": "neon",
                  "type": "string"
                },
                {
                  "const": "studio",
                  "type": "string"
                }
              ]
            },
            "service": {
              "type": "string"
            },
            "sourceObject": {
              "type": "string"
            },
            "observedAt": {
              "type": "string"
            },
            "schemaVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "projectionVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "plane",
            "service",
            "sourceObject",
            "observedAt"
          ],
          "additionalProperties": true
        }
      },
      "redactions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "fieldCode": {
              "type": "string"
            },
            "classification": {
              "anyOf": [
                {
                  "const": "confidential",
                  "type": "string"
                },
                {
                  "const": "highly_restricted",
                  "type": "string"
                },
                {
                  "const": "restricted",
                  "type": "string"
                }
              ]
            },
            "behavior": {
              "anyOf": [
                {
                  "const": "masked",
                  "type": "string"
                },
                {
                  "const": "omitted",
                  "type": "string"
                },
                {
                  "const": "presence_only",
                  "type": "string"
                }
              ]
            },
            "reasonCode": {
              "type": "string"
            }
          },
          "required": [
            "fieldCode",
            "classification",
            "behavior",
            "reasonCode"
          ],
          "additionalProperties": true
        }
      }
    },
    "required": [
      "schemaVersion",
      "sectionCode",
      "asOf",
      "generatedAt",
      "businessPartnerVersion",
      "definitionHash",
      "state",
      "data",
      "provenance",
      "redactions"
    ],
    "additionalProperties": true
  },
  "BusinessPartner360TaxRevealResult": {
    "type": "object",
    "properties": {
      "taxRegistrationId": {
        "type": "string"
      },
      "value": {
        "type": "string"
      },
      "expiresAt": {
        "type": "string"
      },
      "provenance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "plane": {
              "anyOf": [
                {
                  "const": "mesh",
                  "type": "string"
                },
                {
                  "const": "neon",
                  "type": "string"
                },
                {
                  "const": "studio",
                  "type": "string"
                }
              ]
            },
            "service": {
              "type": "string"
            },
            "sourceObject": {
              "type": "string"
            },
            "observedAt": {
              "type": "string"
            },
            "schemaVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "projectionVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "plane",
            "service",
            "sourceObject",
            "observedAt"
          ],
          "additionalProperties": true
        }
      }
    },
    "required": [
      "taxRegistrationId",
      "value",
      "expiresAt",
      "provenance"
    ],
    "additionalProperties": true
  },
  "BusinessPartner360BankRevealResult": {
    "type": "object",
    "properties": {
      "bankAccountLinkId": {
        "type": "string"
      },
      "value": {
        "type": "string"
      },
      "expiresAt": {
        "type": "string"
      },
      "provenance": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "plane": {
              "anyOf": [
                {
                  "const": "mesh",
                  "type": "string"
                },
                {
                  "const": "neon",
                  "type": "string"
                },
                {
                  "const": "studio",
                  "type": "string"
                }
              ]
            },
            "service": {
              "type": "string"
            },
            "sourceObject": {
              "type": "string"
            },
            "observedAt": {
              "type": "string"
            },
            "schemaVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "projectionVersion": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": [
            "plane",
            "service",
            "sourceObject",
            "observedAt"
          ],
          "additionalProperties": true
        }
      }
    },
    "required": [
      "bankAccountLinkId",
      "value",
      "expiresAt",
      "provenance"
    ],
    "additionalProperties": true
  }
} as const;
