import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { Application, Request, RequestHandler, Response } from "express";
import { MasterDataError } from "./errors.js";
import type { createHrStage2Service } from "./hr-stage2-service.js";
import type { DraftSetupInput } from "./hr-stage2-setup-service.js";

export function registerHrStage2Routes(app:Application,options:{
  authenticate:RequestHandler;
  readContext:(response:Response)=>VerifiedRequestContext;
  service:ReturnType<typeof createHrStage2Service>;
}){
  const route=(work:(request:Request,context:VerifiedRequestContext)=>Promise<unknown>):RequestHandler=>async(request,response,next)=>{
    response.setHeader("Cache-Control","private, no-store");
    try{response.json(await work(request,options.readContext(response)));}
    catch(error){if(error instanceof MasterDataError)response.status(error.status).json({code:error.code,message:error.message});else next(error);}
  };
  const body=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new MasterDataError(400,"HR_STAGE2_INVALID","JSON object is required");return value as Record<string,unknown>;};
  const required=(value:unknown,key:string):string=>{if(typeof value!=="string"||!value.trim())throw new MasterDataError(400,"HR_STAGE2_INVALID",`${key} is required`);return value;};
  const optional=(value:unknown):string|undefined=>typeof value==="string"&&value.trim()?value:undefined;
  app.get("/api/neon/hr-setup/catalog",options.authenticate,route((request,context)=>options.service.catalog(context,required(request.query["companyCodeId"],"companyCodeId"))));
  app.post("/api/neon/hr-setup/positions",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.createDraftPosition(context,{companyCodeId:required(value["companyCodeId"],"companyCodeId"),code:required(value["code"],"code"),name:required(value["name"],"name"),validFrom:required(value["validFrom"],"validFrom"),...(optional(value["jobId"])?{jobId:optional(value["jobId"])}:{}),...(optional(value["orgUnitId"])?{orgUnitId:optional(value["orgUnitId"])}:{}),...(optional(value["siteId"])?{siteId:optional(value["siteId"])}:{})});}));
  app.get("/api/neon/hr-setup/drafts",options.authenticate,route((request,context)=>options.service.setupDrafts(context,required(request.query["companyCodeId"],"companyCodeId"))));
  app.post("/api/neon/hr-setup/drafts",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.draftSetup(context,{kind:required(value["kind"],"kind") as DraftSetupInput["kind"],code:required(value["code"],"code"),name:required(value["name"],"name"),...Object.fromEntries(["companyCodeId","jobFamilyId","jobFunctionId","payGradeId","jobId","orgUnitId","siteId","siteType","weekendPattern","currencyCode","gradeSet","validFrom"].filter(key=>optional(value[key])).map(key=>[key,optional(value[key])]))});}));
  app.post("/api/neon/hr-setup/drafts/:approvalId/publish",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.publishSetup(context,required(request.params["approvalId"],"approvalId"),Number(value["expectedVersion"]));}));
  app.get("/api/neon/hr-setup/org-company-assignments",options.authenticate,route((request,context)=>options.service.orgCompanyAssignments(context,required(request.query["companyCodeId"],"companyCodeId"))));
  app.get("/api/neon/hr-setup/org-candidates",options.authenticate,route((request,context)=>options.service.orgCandidates(context,required(request.query["companyCodeId"],"companyCodeId"))));
  app.post("/api/neon/hr-setup/org-company-assignments",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.draftOrgCompanyAssignment(context,{companyCodeId:required(value["companyCodeId"],"companyCodeId"),orgUnitId:required(value["orgUnitId"],"orgUnitId"),effectiveFrom:required(value["effectiveFrom"],"effectiveFrom"),...(optional(value["effectiveUntil"])?{effectiveUntil:optional(value["effectiveUntil"])}:{})});}));
  app.post("/api/neon/hr-setup/org-company-assignments/:assignmentId/publish",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.publishOrgCompanyAssignment(context,required(request.params["assignmentId"],"assignmentId"),Number(value["expectedVersion"]));}));
  app.get("/api/neon/hr-setup/calendar-day-changes",options.authenticate,route((request,context)=>options.service.calendarDayChanges(context,required(request.query["companyCodeId"],"companyCodeId"))));
  app.post("/api/neon/hr-setup/calendar-day-changes",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.draftCalendarDay(context,{companyCodeId:required(value["companyCodeId"],"companyCodeId"),calendarId:required(value["calendarId"],"calendarId"),holidayDate:required(value["holidayDate"],"holidayDate"),name:required(value["name"],"name"),...(optional(value["dayType"])?{dayType:optional(value["dayType"])}:{}),...(optional(value["observanceType"])?{observanceType:optional(value["observanceType"])}:{}),isHalfDay:value["isHalfDay"]===true});}));
  app.post("/api/neon/hr-setup/calendar-day-changes/:changeId/publish",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.publishCalendarDay(context,required(request.params["changeId"],"changeId"),Number(value["expectedVersion"]));}));
  app.get("/api/neon/hr-setup/policy-assignments",options.authenticate,route((request,context)=>options.service.policyAssignments(context,required(request.query["companyCodeId"],"companyCodeId"))));
  app.get("/api/neon/hr-setup/policy-effective",options.authenticate,route((request,context)=>options.service.resolvePolicy(context,{companyCodeId:required(request.query["companyCodeId"],"companyCodeId"),asOf:required(request.query["asOf"],"asOf"),...(optional(request.query["siteId"])?{siteId:optional(request.query["siteId"])}:{})})));
  app.post("/api/neon/hr-setup/policy-assignments",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.createPolicyAssignment(context,{idempotencyKey:required(value["idempotencyKey"],"idempotencyKey"),policyDefinitionId:required(value["policyDefinitionId"],"policyDefinitionId"),scopeKind:required(value["scopeKind"],"scopeKind") as "country"|"company"|"site",countryCode:required(value["countryCode"],"countryCode"),effectiveFrom:required(value["effectiveFrom"],"effectiveFrom"),...(optional(value["effectiveUntil"])?{effectiveUntil:optional(value["effectiveUntil"])}:{}),...(optional(value["companyCodeId"])?{companyCodeId:optional(value["companyCodeId"])}:{}),...(optional(value["siteId"])?{siteId:optional(value["siteId"])}:{})});}));
  app.post("/api/neon/hr-setup/policy-assignments/:assignmentId/publish",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.publishPolicyAssignment(context,required(request.params["assignmentId"],"assignmentId"),Number(value["expectedVersion"]));}));
  app.get("/api/neon/users",options.authenticate,route((request,context)=>options.service.users(context,optional(request.query["search"])??"",Number(request.query["limit"]??50))));
  app.get("/api/neon/users/me/profile-change",options.authenticate,route((_request,context)=>options.service.ownProfileRequest(context)));
  app.post("/api/neon/users/me/profile-change",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.requestOwnProfileChange(context,{idempotencyKey:required(value["idempotencyKey"],"idempotencyKey"),...(optional(value["preferredName"])?{preferredName:optional(value["preferredName"])}:{}),...(optional(value["displayName"])?{displayName:optional(value["displayName"])}:{})});}));
  app.post("/api/neon/users/me/profile-change/:requestId/submit",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.submitOwnProfileRequest(context,required(request.params["requestId"],"requestId"),Number(value["expectedVersion"]));}));
  app.get("/api/neon/users/profile-changes/review",options.authenticate,route((_request,context)=>options.service.profileReviewQueue(context)));
  app.post("/api/neon/users/profile-changes/:requestId/decision",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.decideProfileRequest(context,{requestId:required(request.params["requestId"],"requestId"),expectedVersion:Number(value["expectedVersion"]),decision:required(value["decision"],"decision") as "apply"|"reject",...(optional(value["reason"])?{reason:optional(value["reason"])}:{})});}));
  app.patch("/api/neon/users/:principalId/profile",options.authenticate,route((request,context)=>{const value=body(request.body);return options.service.adminUpdateProfile(context,{principalId:required(request.params["principalId"],"principalId"),...(value["expectedUpdatedAt"]===null?{expectedUpdatedAt:null}:optional(value["expectedUpdatedAt"])?{expectedUpdatedAt:optional(value["expectedUpdatedAt"])}:{}),...(optional(value["preferredName"])?{preferredName:optional(value["preferredName"])}:{}),...(optional(value["displayName"])?{displayName:optional(value["displayName"])}:{})});}));
  app.get("/api/neon/users/:principalId",options.authenticate,route((request,context)=>options.service.user(context,required(request.params["principalId"],"principalId"))));
  app.get("/api/neon/workforce/:employeeId/authority",options.authenticate,route((request,context)=>options.service.employeeAuthority(context,required(request.params["employeeId"],"employeeId"),required(request.query["companyCodeId"],"companyCodeId"))));
}
