import {sql,type Transaction} from "kysely";
import type {BusinessPartner360NetworkLocalData,BusinessPartner360NetworkProvenance} from "@athyper/server-contract-master-data";
import type {BusinessPartner360NetworkRead,BusinessPartner360Repository} from "./business-partner-360-service.js";

type Tx=Transaction<Record<string,never>>;type Row=Record<string,unknown>;type Input=Parameters<BusinessPartner360Repository<Tx>["readNetworkSection"]>[0];
const safePaths=["partner.accountCode","partner.displayName","partner.legalName","partner.legalForm","partner.countryCode","partner.incorporationDate","partner.websiteUrl","partner.description"];

export async function readBusinessPartner360NetworkSection(input:Input,transaction:Tx):Promise<BusinessPartner360NetworkRead>{
  const row=(await sql<Row>`SELECT link.id::text link_id,link.source_tenant_id::text,link.source_network_account_id::text,link.recipient_network_account_id::text,link.network_relationship_id::text,link.proposed_role::text,link.status::text link_status,link.approved_at,link.terminated_at,
    projection.current_publication_id::text publication_id,projection.current_publication_version publication_version,projection.current_lifecycle_version lifecycle_version,projection.projection_status,projection.updated_at projection_observed_at,
    snapshot.id::text snapshot_id,snapshot.schema_code,snapshot.schema_version,snapshot.field_set_code,snapshot.payload_hash,snapshot.received_at,
    matched.id::text match_id,matched.algorithm_code,matched.algorithm_version,matched.diff_hash,matched.created_at matched_at,
    ARRAY(SELECT item->>'path' FROM jsonb_array_elements(COALESCE(matched.field_diff,'[]'::jsonb)) item WHERE item->>'path'=ANY(${safePaths}::text[]) ORDER BY item->>'path') diff_paths,
    acceptance.id::text acceptance_id,acceptance.accepted_field_paths,acceptance.acceptance_hash,acceptance.created_at acceptance_created_at,
    acceptance_event.event_kind acceptance_event_kind,acceptance_event.business_partner_request_id::text,acceptance_event.recorded_at acceptance_recorded_at,
    bank.projection_status bank_status,bank.current_disclosure_version bank_disclosure_version,bank.current_lifecycle_version bank_lifecycle_version,bank.updated_at bank_observed_at,bank_snapshot.payload_hash bank_payload_hash
    ,link.tenant_id::text authority_tenant_id FROM control.mesh_business_partner_account_link link
    JOIN control.mesh_business_partner_profile_projection projection ON projection.tenant_id=link.tenant_id AND projection.id=link.profile_projection_id AND projection.network_relationship_id=link.network_relationship_id
    JOIN snapshot.mesh_business_partner_profile_received snapshot ON snapshot.tenant_id=projection.tenant_id AND snapshot.id=projection.current_snapshot_id
    LEFT JOIN LATERAL(SELECT value.* FROM document.mesh_business_partner_match value WHERE value.tenant_id=link.tenant_id AND value.projection_id=projection.id AND value.candidate_business_partner_id=link.business_partner_id ORDER BY value.created_at DESC,value.id DESC LIMIT 1) matched ON true
    LEFT JOIN LATERAL(SELECT value.* FROM document.mesh_business_partner_acceptance value WHERE value.tenant_id=link.tenant_id AND value.match_id=matched.id ORDER BY value.created_at DESC,value.id DESC LIMIT 1) acceptance ON true
    LEFT JOIN LATERAL(SELECT value.* FROM document.mesh_business_partner_acceptance_event value WHERE value.tenant_id=link.tenant_id AND value.acceptance_id=acceptance.id ORDER BY value.lifecycle_version DESC,value.id DESC LIMIT 1) acceptance_event ON true
    LEFT JOIN control.mesh_bank_account_projection bank ON bank.tenant_id=link.tenant_id AND bank.account_link_id=link.id AND bank.network_relationship_id=link.network_relationship_id
    LEFT JOIN snapshot.mesh_bank_account_disclosure_received bank_snapshot ON bank_snapshot.tenant_id=bank.tenant_id AND bank_snapshot.id=bank.current_snapshot_id
    WHERE link.tenant_id=${input.tenantId}::uuid AND link.business_partner_id=${input.businessPartnerId}::uuid AND (${input.roleLens}='all' OR link.proposed_role::text=${input.roleLens})
    ORDER BY link.status='active' DESC,COALESCE(link.approved_at,link.created_at) DESC,link.id DESC LIMIT 1`.execute(transaction)).rows[0];
  if(!row)return{state:"empty",provenance:[]};
  const observed=iso(row["received_at"]),freshness=observed>=input.freshAfter?"fresh" as const:"stale" as const,payloadHash=text(row,"payload_hash"),accepted=strings(row["accepted_field_paths"]).filter(path=>safePaths.includes(path)),fieldPaths=strings(row["diff_paths"]).filter(path=>safePaths.includes(path)),ignored=fieldPaths.filter(path=>!accepted.includes(path));
  const provenance:BusinessPartner360NetworkProvenance[]=[
    source(row,"control.mesh_business_partner_account_link",iso(row["approved_at"]??row["projection_observed_at"]),payloadHash,freshness,"neon.mesh_account_link","coordinate_status_v1"),
    source(row,"snapshot.mesh_business_partner_profile_received",observed,payloadHash,freshness),
    source(row,"control.mesh_business_partner_profile_projection",iso(row["projection_observed_at"]),payloadHash,freshness),
    ...(row["match_id"]?[source(row,"document.mesh_business_partner_match",iso(row["matched_at"]),text(row,"diff_hash"),freshness,"neon.mesh_business_partner_match","safe_field_paths_v1")]:[]),
    ...(row["acceptance_id"]?[source(row,"document.mesh_business_partner_acceptance",iso(row["acceptance_created_at"]),text(row,"acceptance_hash"),freshness,"neon.mesh_business_partner_acceptance","safe_field_paths_v1")]:[]),
    ...(row["bank_status"]&&row["bank_payload_hash"]?[source(row,"control.mesh_bank_account_projection",iso(row["bank_observed_at"]),text(row,"bank_payload_hash"),freshness,"mesh.bank_account_disclosure","presence_status_v1")]:[]),
  ];
  const data:BusinessPartner360NetworkLocalData={accountLink:{id:text(row,"link_id"),networkRelationshipId:text(row,"network_relationship_id"),sourceTenantId:text(row,"source_tenant_id"),sourceNetworkAccountId:text(row,"source_network_account_id"),recipientNetworkAccountId:text(row,"recipient_network_account_id"),proposedRole:text(row,"proposed_role")as"supplier"|"customer",status:text(row,"link_status"),...(row["approved_at"]?{approvedAt:iso(row["approved_at"])}:{}),...(row["terminated_at"]?{terminatedAt:iso(row["terminated_at"])}:{})},received:{snapshotId:text(row,"snapshot_id"),publicationId:text(row,"publication_id"),publicationVersion:Number(row["publication_version"]),lifecycleVersion:Number(row["lifecycle_version"]),state:row["projection_status"]==="withdrawn"?"withdrawn":"received",receivedAt:observed},...(row["match_id"]?{match:{id:text(row,"match_id"),state:"matched",algorithmCode:text(row,"algorithm_code"),algorithmVersion:Number(row["algorithm_version"]),matchedAt:iso(row["matched_at"]),diffHash:text(row,"diff_hash"),fieldPaths}}:{}),...(row["acceptance_id"]?{acceptance:{id:text(row,"acceptance_id"),state:row["acceptance_event_kind"]==="request_created"?"request_created":"prepared",acceptedFields:accepted,ignoredFields:ignored,acceptanceHash:text(row,"acceptance_hash"),preparedAt:iso(row["acceptance_created_at"]),...(row["business_partner_request_id"]?{businessPartnerRequestId:text(row,"business_partner_request_id")} : {}),...(row["acceptance_recorded_at"]?{recordedAt:iso(row["acceptance_recorded_at"])}:{})}}:{}),bankDisclosure:row["bank_status"]?{present:true,status:text(row,"bank_status"),disclosureVersion:Number(row["bank_disclosure_version"]),lifecycleVersion:Number(row["bank_lifecycle_version"]),observedAt:iso(row["bank_observed_at"])}:{present:false},provenance};
  return{state:freshness==="stale"?"stale":"ready",data,provenance:provenance.map(item=>({plane:"neon" as const,service:"master-data",sourceObject:item.sourceObject,observedAt:item.observedAt,schemaVersion:String(item.schemaVersion)}))};
}

function source(row:Row,sourceObject:string,observedAt:string,hash:string,freshness:"fresh"|"stale",schemaCode=text(row,"schema_code"),fieldSetCode=text(row,"field_set_code")):BusinessPartner360NetworkProvenance{return{authority:"neon",authorityTenantId:text(row,"authority_tenant_id"),sourceObject,observedAt,schemaCode,schemaVersion:Number(row["schema_version"]),fieldSetCode,hash,freshness};}function text(row:Row,key:string){const value=row[key];if(value===null||value===undefined)throw new Error(`BP_360_NETWORK_FIELD_MISSING:${key}`);return String(value);}function iso(value:unknown){return(value instanceof Date?value:new Date(String(value))).toISOString();}function strings(value:unknown):string[]{if(Array.isArray(value))return value.filter((item):item is string=>typeof item==="string");if(typeof value==="string"&&value.startsWith("{")&&value.endsWith("}"))return value.slice(1,-1).split(",").filter(Boolean);return[];}
