import type { SupplierRegistrationInvitation, SupplierRegistrationInvitationRepository } from "@athyper/server-contract-master-data";
import {sql,type Transaction}from"kysely";
import {MasterDataError}from"./errors.js";
import {KyselyBusinessPartnerRequestRepository}from"./kysely-business-partner-request-repository.js";

type Database=Record<string,never>;type Tx=Transaction<Database>;type Row=Record<string,unknown>;

export class KyselySupplierRegistrationInvitationRepository implements SupplierRegistrationInvitationRepository<Tx>{
  private readonly requests=new KyselyBusinessPartnerRequestRepository();

  async findByIdempotencyKey(tenantId:string,idempotencyKey:string,transaction:Tx){
    await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`${tenantId}:supplier_registration_invitation:${idempotencyKey}`},0))`.execute(transaction);
    const row=(await sql<Row>`SELECT * FROM document.supplier_registration_invitation WHERE tenant_id=${tenantId}::uuid AND idempotency_key=${idempotencyKey} LIMIT 1`.execute(transaction)).rows[0];return row?{invitation:map(row),inviteeEmailHash:text(row,"invitee_email_hash")}:null;
  }
  async create(input:Parameters<SupplierRegistrationInvitationRepository<Tx>["create"]>[0],transaction:Tx){
    const row=(await sql<Row>`INSERT INTO document.supplier_registration_invitation(tenant_id,invitation_no,registration_role,requested_operating_organization_id,optional_company_code_id,intended_supplier_name,invitee_email_hash,token_hash,expires_at,idempotency_key,created_by)
      VALUES(${input.tenantId}::uuid,${input.invitationNo},${input.command.requestedRole??"supplier"}::master.partner_role_d,${input.command.operatingOrganizationId}::uuid,${input.command.companyCodeId??null}::uuid,${input.command.intendedSupplierName},${input.inviteeEmailHash},${input.tokenHash},${input.command.expiresAt}::timestamptz,${input.command.idempotencyKey},${input.createdBy}::uuid) RETURNING *`.execute(transaction)).rows[0];
    if(!row)throw new Error("SUPPLIER_REGISTRATION_INVITATION_CREATE_FAILED");return map(row);
  }
  async get(tenantId:string,invitationId:string,transaction:Tx){const row=(await sql<Row>`SELECT * FROM document.supplier_registration_invitation WHERE tenant_id=${tenantId}::uuid AND id=${invitationId}::uuid LIMIT 1`.execute(transaction)).rows[0];return row?map(row):null;}
  async accept(input:Parameters<SupplierRegistrationInvitationRepository<Tx>["accept"]>[0],transaction:Tx){
    const raw=(await sql<Row>`SELECT invitation.*,invitation.expires_at<=statement_timestamp() AS is_expired FROM document.supplier_registration_invitation invitation WHERE tenant_id=${input.tenantId}::uuid AND token_hash=${input.tokenHash} FOR UPDATE`.execute(transaction)).rows[0];if(!raw)return null;
    const invitation=map(raw);if(String(raw["invitee_email_hash"])!==input.inviteeEmailHash||(input.expectedRole&&invitation.requestedRole!==input.expectedRole))throw new MasterDataError(404,"SUPPLIER_REGISTRATION_INVITATION_NOT_FOUND","Registration invitation was not found");
    if(invitation.status==="accepted"){
      if(invitation.applicantPrincipalId!==input.applicantPrincipalId||!invitation.businessPartnerRequestId)throw new MasterDataError(409,"SUPPLIER_REGISTRATION_INVITATION_ALREADY_USED","Supplier registration invitation was already used");
      const request=await this.requests.get(input.tenantId,invitation.businessPartnerRequestId,transaction);if(!request||request.idempotencyKey!==input.requestIdempotencyKey)throw new MasterDataError(409,"SUPPLIER_REGISTRATION_INVITATION_ALREADY_USED","Supplier registration invitation was already used with different request evidence");return{invitation,request,replayed:true};
    }
    if(invitation.status!=="pending")throw new MasterDataError(409,"SUPPLIER_REGISTRATION_INVITATION_NOT_ACTIVE","Supplier registration invitation is no longer active");
    if(raw["is_expired"]===true)throw new MasterDataError(410,"SUPPLIER_REGISTRATION_INVITATION_EXPIRED","Supplier registration invitation has expired");
    const existing=await this.requests.findByIdempotencyKey(input.tenantId,input.requestIdempotencyKey,transaction);if(existing)throw new MasterDataError(409,"BUSINESS_PARTNER_REQUEST_IDEMPOTENCY_CONFLICT","Request idempotency key is already in use");
    const request=await this.requests.create({tenantId:input.tenantId,requestNo:input.requestNo,createdBy:input.applicantPrincipalId,schema:input.schema,command:{idempotencyKey:input.requestIdempotencyKey,kind:"new_partner",source:{kind:"portal"},registrationMode:"self_service",invitationId:invitation.id,applicantPrincipalId:input.applicantPrincipalId,requestedRole:invitation.requestedRole,operatingOrganizationId:invitation.requestedOperatingOrganizationId,...(invitation.optionalCompanyCodeId?{companyCodeId:invitation.optionalCompanyCodeId}:{}),proposedPayload:input.proposedPayload}},transaction);
    const accepted=(await sql<Row>`UPDATE document.supplier_registration_invitation SET status='accepted',applicant_principal_id=${input.applicantPrincipalId}::uuid,business_partner_request_id=${request.id}::uuid,accepted_at=statement_timestamp(),updated_by=${input.applicantPrincipalId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND id=${invitation.id}::uuid AND status='pending' RETURNING *`.execute(transaction)).rows[0];
    if(!accepted)throw new MasterDataError(409,"SUPPLIER_REGISTRATION_INVITATION_CONFLICT","Supplier registration invitation changed during acceptance");return{invitation:map(accepted),request,replayed:false};
  }
  async cancel(input:Parameters<SupplierRegistrationInvitationRepository<Tx>["cancel"]>[0],transaction:Tx){const row=(await sql<Row>`UPDATE document.supplier_registration_invitation SET status='cancelled',cancelled_at=statement_timestamp(),updated_by=${input.cancelledBy}::uuid WHERE tenant_id=${input.tenantId}::uuid AND id=${input.invitationId}::uuid AND status='pending' AND row_version=${input.expectedVersion} RETURNING *`.execute(transaction)).rows[0];return row?map(row):null;}
  async expireDue(input:Parameters<SupplierRegistrationInvitationRepository<Tx>["expireDue"]>[0],transaction:Tx){const rows=(await sql<Row>`WITH due AS(SELECT id FROM document.supplier_registration_invitation WHERE tenant_id=${input.tenantId}::uuid AND status='pending' AND expires_at<=${input.now}::timestamptz ORDER BY expires_at,id FOR UPDATE SKIP LOCKED LIMIT ${input.limit}) UPDATE document.supplier_registration_invitation invitation SET status='expired',updated_by=${input.actorId}::uuid FROM due WHERE invitation.tenant_id=${input.tenantId}::uuid AND invitation.id=due.id RETURNING invitation.*`.execute(transaction)).rows;return rows.map(map);}
  async getOwnedRequest(tenantId:string,requestId:string,applicantPrincipalId:string,transaction:Tx){const owned=(await sql<{owned:boolean}>`SELECT EXISTS(SELECT 1 FROM document.business_partner_request WHERE tenant_id=${tenantId}::uuid AND id=${requestId}::uuid AND source_kind='portal' AND registration_mode IN('self_service','on_behalf') AND applicant_principal_id=${applicantPrincipalId}::uuid) owned`.execute(transaction)).rows[0]?.owned===true;return owned?this.requests.get(tenantId,requestId,transaction):null;}
  async correctOwnedRequest(input:Parameters<SupplierRegistrationInvitationRepository<Tx>["correctOwnedRequest"]>[0],transaction:Tx){const row=(await sql<{id:string}>`UPDATE document.business_partner_request SET proposed_payload=${JSON.stringify(input.proposedPayload)}::jsonb,validation_summary='{}'::jsonb,duplicate_summary='{}'::jsonb,change_impact='{}'::jsonb,status='draft',updated_by=${input.applicantPrincipalId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND id=${input.requestId}::uuid AND applicant_principal_id=${input.applicantPrincipalId}::uuid AND source_kind='portal' AND status='returned' AND row_version=${input.expectedVersion} RETURNING id::text`.execute(transaction)).rows[0];return row?this.requests.get(input.tenantId,input.requestId,transaction):null;}
  async attachOwnedEvidence(input:Parameters<SupplierRegistrationInvitationRepository<Tx>["attachOwnedEvidence"]>[0],transaction:Tx){return (await sql<{id:string}>`INSERT INTO document.business_partner_request_evidence(tenant_id,request_id,evidence_kind,attachment_id,content_hash,classification_code,metadata,created_by) SELECT request.tenant_id,request.id,${input.evidenceKind},${input.attachmentId}::uuid,${input.contentHash},${input.classificationCode},${JSON.stringify({source:"supplier_external_facade"})}::jsonb,${input.applicantPrincipalId}::uuid FROM document.business_partner_request request WHERE request.tenant_id=${input.tenantId}::uuid AND request.id=${input.requestId}::uuid AND request.applicant_principal_id=${input.applicantPrincipalId}::uuid AND request.source_kind='portal' AND request.status IN('draft','validation_failed','returned') RETURNING id::text`.execute(transaction)).rows[0]?.id??null;}
  async recoverApplicant(input:Parameters<SupplierRegistrationInvitationRepository<Tx>["recoverApplicant"]>[0],transaction:Tx){const row=(await sql<Row>`SELECT invitation.* FROM document.supplier_registration_invitation invitation JOIN document.business_partner_request request ON request.tenant_id=invitation.tenant_id AND request.id=invitation.business_partner_request_id WHERE invitation.tenant_id=${input.tenantId}::uuid AND invitation.id=${input.invitationId}::uuid AND invitation.status='accepted' AND request.status IN('draft','validation_failed','returned') FOR UPDATE OF invitation`.execute(transaction)).rows[0];if(!row)return null;await sql`INSERT INTO document.supplier_registration_recovery(tenant_id,invitation_id,request_id,prior_applicant_principal_id,requested_applicant_principal_id,reason,requested_by) VALUES(${input.tenantId}::uuid,${input.invitationId}::uuid,${text(row,"business_partner_request_id")}::uuid,${text(row,"applicant_principal_id")}::uuid,${input.newApplicantPrincipalId}::uuid,${input.reason},${input.recoveredBy}::uuid)`.execute(transaction);return map(row);}
}

function map(row:Row):SupplierRegistrationInvitation{return{id:text(row,"id"),tenantId:text(row,"tenant_id"),invitationNo:text(row,"invitation_no"),requestedRole:text(row,"registration_role") as "supplier"|"customer",requestedOperatingOrganizationId:text(row,"requested_operating_organization_id"),...(optional(row,"optional_company_code_id")?{optionalCompanyCodeId:optional(row,"optional_company_code_id")} : {}),intendedSupplierName:text(row,"intended_supplier_name"),expiresAt:date(row["expires_at"]),status:text(row,"status") as SupplierRegistrationInvitation["status"],...(optional(row,"applicant_principal_id")?{applicantPrincipalId:optional(row,"applicant_principal_id")} : {}),...(optional(row,"business_partner_request_id")?{businessPartnerRequestId:optional(row,"business_partner_request_id")} : {}),...(row["accepted_at"]?{acceptedAt:date(row["accepted_at"])}:{}),...(row["cancelled_at"]?{cancelledAt:date(row["cancelled_at"])}:{}),idempotencyKey:text(row,"idempotency_key"),rowVersion:Number(row["row_version"]),createdAt:date(row["created_at"]),createdBy:text(row,"created_by"),...(row["updated_at"]?{updatedAt:date(row["updated_at"])}:{}),...(optional(row,"updated_by")?{updatedBy:optional(row,"updated_by")}:{})};}
function text(row:Row,key:string){const value=row[key];if(value==null)throw new Error(`SUPPLIER_REGISTRATION_INVITATION_ROW_INVALID:${key}`);return String(value);}function optional(row:Row,key:string){const value=row[key];return value==null?undefined:String(value);}function date(value:unknown){const parsed=value instanceof Date?value:new Date(String(value));if(Number.isNaN(parsed.valueOf()))throw new Error("SUPPLIER_REGISTRATION_INVITATION_ROW_INVALID:date");return parsed.toISOString();}
