import{createHash,randomBytes,randomUUID}from"node:crypto";
import type{AuditRecorder}from"@athyper/server-contract-audit";
import type{Authorizer,VerifiedRequestContext}from"@athyper/server-contract-auth";
import type{OutboxWriter}from"@athyper/server-contract-events";
import{supplierRegistrationPermissions,type BusinessPartnerRequestSchemaResolver,type CreateSupplierRegistrationInvitationCommand,type SupplierRegistrationInvitation,type SupplierRegistrationInvitationRepository,type SupplierRegistrationInvitationService,type SupplierRegistrationInvitationTransactionCoordinator}from"@athyper/server-contract-master-data";
import{MasterDataError}from"./errors.js";

export interface SupplierRegistrationInvitationServiceOptions<Transaction>{readonly authorizer:Authorizer;readonly repository:SupplierRegistrationInvitationRepository<Transaction>;readonly transactions:SupplierRegistrationInvitationTransactionCoordinator<Transaction>;readonly schemas:BusinessPartnerRequestSchemaResolver;readonly audit:AuditRecorder<Transaction>;readonly outbox:OutboxWriter<Transaction>;readonly createInvitationNo?:()=>string;readonly createRequestNo?:()=>string;readonly createToken?:()=>string;readonly now?:()=>Date;}

export function createSupplierRegistrationInvitationService<Transaction>(options:SupplierRegistrationInvitationServiceOptions<Transaction>):SupplierRegistrationInvitationService{
 const invitationNo=options.createInvitationNo??(()=>`SRI-${randomUUID().replaceAll("-","").toUpperCase()}`),requestNo=options.createRequestNo??(()=>`BPR-${randomUUID().replaceAll("-","").toUpperCase()}`),token=options.createToken??(()=>randomBytes(32).toString("base64url")),now=options.now??(()=>new Date());
 return{
  async create(command){assertNeon(command.context);validateCreate(command,now());await authorize(options.authorizer,command.context,supplierRegistrationPermissions.invitationCreate,scope(command.operatingOrganizationId,command.companyCodeId));const emailHash=digest(normalizeEmail(command.inviteeEmail));return options.transactions.run("neon",actor(command.context),async transaction=>{const existing=await options.repository.findByIdempotencyKey(command.context.tenantId,command.idempotencyKey,transaction);if(existing){if(existing.inviteeEmailHash!==emailHash||creationFingerprint(existing.invitation)!==creationCommandFingerprint(command))throw new MasterDataError(409,"SUPPLIER_REGISTRATION_INVITATION_IDEMPOTENCY_CONFLICT","Idempotency key was reused with different invitation content");return{invitation:existing.invitation,replayed:true};}const rawToken=token();if(rawToken.length<32)throw new MasterDataError(503,"SUPPLIER_REGISTRATION_TOKEN_GENERATOR_INVALID","Invitation token generator returned insufficient entropy");const invitation=await options.repository.create({tenantId:command.context.tenantId,invitationNo:invitationNo(),command:withoutCreateSecrets(command),inviteeEmailHash:emailHash,tokenHash:digest(rawToken),createdBy:command.context.principalId},transaction);await effects(options,transaction,command.context,"supplier_registration.invitation.created",invitation,{operatingOrganizationId:invitation.requestedOperatingOrganizationId});return{invitation,token:rawToken,replayed:false};});},
  async get(query){assertNeon(query.context);return options.transactions.run("neon",actor(query.context),async transaction=>{const invitation=await options.repository.get(query.context.tenantId,query.invitationId,transaction);if(!invitation)throw notFound();await authorize(options.authorizer,query.context,supplierRegistrationPermissions.invitationRead,scope(invitation.requestedOperatingOrganizationId,invitation.optionalCompanyCodeId));return invitation;});},
  async accept(command){assertNeon(command.context);validateAccept(command);await authorize(options.authorizer,command.context,supplierRegistrationPermissions.externalRespond,{tenantId:command.context.tenantId,externalApplicant:true});const schema=await options.schemas.resolve({context:command.context,kind:"new_partner",sourceKind:"portal"});validateSchema(schema);return options.transactions.run("neon",actor(command.context),async transaction=>{const result=await options.repository.accept({tenantId:command.context.tenantId,tokenHash:digest(command.token),inviteeEmailHash:digest(normalizeEmail(command.inviteeEmail)),applicantPrincipalId:command.context.principalId,requestIdempotencyKey:command.requestIdempotencyKey,requestNo:requestNo(),schema,proposedPayload:command.proposedPayload},transaction);if(!result)throw notFound();if(!result.replayed)await effects(options,transaction,command.context,"supplier_registration.invitation.accepted",result.invitation,{businessPartnerRequestId:result.request.id});return result;});},
  async cancel(command){assertNeon(command.context);if(!Number.isSafeInteger(command.expectedVersion)||command.expectedVersion<1)throw invalid("expectedVersion must be a positive integer");return options.transactions.run("neon",actor(command.context),async transaction=>{const current=await options.repository.get(command.context.tenantId,command.invitationId,transaction);if(!current)throw notFound();await authorize(options.authorizer,command.context,supplierRegistrationPermissions.invitationCancel,scope(current.requestedOperatingOrganizationId,current.optionalCompanyCodeId));if(current.status!=="pending")throw new MasterDataError(409,"SUPPLIER_REGISTRATION_INVITATION_NOT_CANCELLABLE","Only a pending invitation can be cancelled");const cancelled=await options.repository.cancel({tenantId:command.context.tenantId,invitationId:command.invitationId,expectedVersion:command.expectedVersion,cancelledBy:command.context.principalId},transaction);if(!cancelled)throw new MasterDataError(409,"SUPPLIER_REGISTRATION_INVITATION_VERSION_CONFLICT","Invitation version or state changed");await effects(options,transaction,command.context,"supplier_registration.invitation.cancelled",cancelled,{});return cancelled;});},
  async expireDue(input){const limit=input.limit??500,at=input.now??now().toISOString();if(!input.tenantId||!input.actorId||!Number.isSafeInteger(limit)||limit<1||limit>5000||Number.isNaN(Date.parse(at)))throw invalid("Expiry input requires tenant, actor, valid timestamp, and limit from 1 to 5000");return options.transactions.run("neon",{tenantId:input.tenantId,principalId:input.actorId},async transaction=>{const expired=await options.repository.expireDue({tenantId:input.tenantId,actorId:input.actorId,now:at,limit},transaction);for(const invitation of expired)await effects(options,transaction,systemContext(input.tenantId,input.actorId),"supplier_registration.invitation.expired",invitation,{});return expired;});}
 };
}

function validateCreate(command:CreateSupplierRegistrationInvitationCommand,now:Date){if(!validKey(command.idempotencyKey))throw invalid("idempotencyKey must contain 8 to 200 trimmed characters");if(!command.operatingOrganizationId||!command.intendedSupplierName.trim()||command.intendedSupplierName.trim()!==command.intendedSupplierName||command.intendedSupplierName.length>512)throw invalid("Operating organization and a trimmed supplier name are required");normalizeEmail(command.inviteeEmail);const expiry=Date.parse(command.expiresAt),minimum=now.valueOf()+5*60_000,maximum=now.valueOf()+30*24*60*60_000;if(Number.isNaN(expiry)||expiry<minimum||expiry>maximum)throw invalid("expiresAt must be between 5 minutes and 30 days in the future");}
function validateAccept(command:Parameters<SupplierRegistrationInvitationService["accept"]>[0]){if(command.token.trim()!==command.token||command.token.length<32||command.token.length>512)throw invalid("A valid invitation token is required");normalizeEmail(command.inviteeEmail);if(!validKey(command.requestIdempotencyKey))throw invalid("requestIdempotencyKey must contain 8 to 200 trimmed characters");const bytes=Buffer.byteLength(JSON.stringify(command.proposedPayload),"utf8");if(!command.proposedPayload||Array.isArray(command.proposedPayload)||typeof command.proposedPayload!=="object"||bytes>1_048_576)throw invalid("proposedPayload must be an object no larger than 1 MiB");}
function normalizeEmail(value:string){const normalized=value.trim().toLowerCase();if(normalized.length>320||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized))throw invalid("A valid invitee email is required");return normalized;}
function validateSchema(schema:{code:string;version:number;hash:string}){if(!/^[a-z][a-z0-9_.-]{1,126}$/.test(schema.code)||!Number.isSafeInteger(schema.version)||schema.version<1||!/^[a-f0-9]{64}$/.test(schema.hash))throw new MasterDataError(503,"BUSINESS_PARTNER_REQUEST_SCHEMA_INVALID","Published request schema coordinates are invalid");}
function creationFingerprint(value:SupplierRegistrationInvitation){return digest(stable({operatingOrganizationId:value.requestedOperatingOrganizationId,companyCodeId:value.optionalCompanyCodeId,intendedSupplierName:value.intendedSupplierName,expiresAt:value.expiresAt}));}function creationCommandFingerprint(value:CreateSupplierRegistrationInvitationCommand){return digest(stable({operatingOrganizationId:value.operatingOrganizationId,companyCodeId:value.companyCodeId,intendedSupplierName:value.intendedSupplierName,expiresAt:new Date(value.expiresAt).toISOString()}));}
function withoutCreateSecrets(command:CreateSupplierRegistrationInvitationCommand){return{idempotencyKey:command.idempotencyKey,operatingOrganizationId:command.operatingOrganizationId,...(command.companyCodeId?{companyCodeId:command.companyCodeId}:{}),intendedSupplierName:command.intendedSupplierName,expiresAt:new Date(command.expiresAt).toISOString()};}
function stable(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).filter(([,item])=>item!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`;}
function digest(value:string){return createHash("sha256").update(value).digest("hex");}function validKey(value:string){return value.trim()===value&&value.length>=8&&value.length<=200;}function assertNeon(context:VerifiedRequestContext){if(context.planeKey!=="neon")throw invalid("Supplier registration executes only in NEON");}function actor(context:VerifiedRequestContext){return{tenantId:context.tenantId,principalId:context.principalId};}function scope(operatingOrganizationId:string,companyCodeId?:string){return{operatingOrganizationId,...(companyCodeId?{companyCodeId}:{})};}function systemContext(tenantId:string,principalId:string):VerifiedRequestContext{return{tenantId,principalId,planeKey:"neon",requestId:`supplier-registration-expiry:${tenantId}`,assurance:"elevated"} as VerifiedRequestContext;}function invalid(message:string){return new MasterDataError(400,"SUPPLIER_REGISTRATION_INVITATION_INVALID",message);}function notFound(){return new MasterDataError(404,"SUPPLIER_REGISTRATION_INVITATION_NOT_FOUND","Supplier registration invitation was not found");}async function authorize(authorizer:Authorizer,context:VerifiedRequestContext,permissionCode:string,resource:Readonly<Record<string,unknown>>){const decision=await authorizer.authorize({context,permissionCode,resource});if(!decision.allowed)throw new MasterDataError(403,"FORBIDDEN",`Permission denied: ${permissionCode}`);}
async function effects<Transaction>(options:SupplierRegistrationInvitationServiceOptions<Transaction>,transaction:Transaction,context:VerifiedRequestContext,eventCode:string,invitation:SupplierRegistrationInvitation,metadata:Readonly<Record<string,unknown>>){await options.outbox.append({tenantId:invitation.tenantId,topic:"supplier-registration",eventType:eventCode,entityType:"supplier_registration_invitation",entityId:invitation.id,actorId:context.principalId,correlationId:context.correlationId,payload:{invitationId:invitation.id,invitationNo:invitation.invitationNo,status:invitation.status,rowVersion:invitation.rowVersion,...metadata}},transaction);await options.audit.record({eventCode,action:eventCode.endsWith("created")?"create":eventCode.endsWith("cancelled")?"cancel":"update",outcome:"success",actor:{kind:eventCode.endsWith("expired")?"system":"user",principalId:context.principalId},tenantId:invitation.tenantId,entityType:"supplier_registration_invitation",entityId:invitation.id,requestId:context.requestId,...(context.correlationId?{correlationId:context.correlationId}:{}),metadata},transaction);}
