import type{VerifiedRequestContext}from"@athyper/server-contract-auth";
import type{SupplierRegistrationInvitationService}from"@athyper/server-contract-master-data";
import type{Application,NextFunction,Request,RequestHandler,Response}from"express";
import{MasterDataError}from"./errors.js";

export interface SupplierRegistrationInvitationRouteOptions{readonly authenticateInternal:RequestHandler;readonly authenticateExternal:RequestHandler;readonly readContext:(response:Response)=>VerifiedRequestContext;readonly service:SupplierRegistrationInvitationService;}

export function registerSupplierRegistrationInvitationRoutes(app:Application,options:SupplierRegistrationInvitationRouteOptions){
 const route=(work:(request:Request,context:VerifiedRequestContext,response:Response)=>Promise<unknown>):RequestHandler=>async(request,response,next)=>{try{const result=await work(request,options.readContext(response),response);if(!response.headersSent)response.json(result);}catch(error){handle(error,response,next);}};
 app.post("/api/neon/supplier-registration-invitations",options.authenticateInternal,route(async(request,context,response)=>{const body=object(request.body),result=await options.service.create({context,idempotencyKey:required(body,"idempotencyKey"),operatingOrganizationId:uuid(body["operatingOrganizationId"],"operatingOrganizationId"),companyCodeId:uuidOptional(body["companyCodeId"],"companyCodeId"),intendedSupplierName:required(body,"intendedSupplierName"),inviteeEmail:required(body,"inviteeEmail"),expiresAt:required(body,"expiresAt")});response.status(result.replayed?200:201);return result;}));
 app.get("/api/neon/supplier-registration-invitations/:invitationId",options.authenticateInternal,route((request,context)=>options.service.get({context,invitationId:uuid(request.params["invitationId"],"invitationId")})));
 app.post("/api/neon/supplier-registration-invitations/:invitationId/cancel",options.authenticateInternal,route((request,context)=>{const body=object(request.body);return options.service.cancel({context,invitationId:uuid(request.params["invitationId"],"invitationId"),expectedVersion:integer(body["expectedVersion"],"expectedVersion")});}));
 app.post("/api/neon/external/supplier-registrations/accept",options.authenticateExternal,route(async(request,context,response)=>{const body=object(request.body),result=await options.service.accept({context,token:required(body,"token"),inviteeEmail:required(body,"inviteeEmail"),requestIdempotencyKey:required(body,"requestIdempotencyKey"),proposedPayload:object(body["proposedPayload"])});response.status(result.replayed?200:201);return result;}));
}
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw invalid("JSON object required");return value as Record<string,unknown>;}function required(value:Record<string,unknown>,key:string){const result=typeof value[key]==="string"?value[key].trim():"";if(!result)throw invalid(`${key} is required`);return result;}function uuid(value:unknown,name:string){if(typeof value!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw invalid(`${name} must be a UUID`);return value;}function uuidOptional(value:unknown,name:string){return value==null||value===""?undefined:uuid(value,name);}function integer(value:unknown,name:string){if(!Number.isSafeInteger(value)||Number(value)<1)throw invalid(`${name} must be a positive integer`);return Number(value);}function invalid(message:string){return new MasterDataError(400,"SUPPLIER_REGISTRATION_INVITATION_INVALID",message);}function handle(error:unknown,response:Response,next:NextFunction){if(!(error instanceof MasterDataError)){next(error);return;}response.status(error.status).type("application/problem+json").json({type:`https://athyper.dev/problems/${error.code.toLowerCase()}`,title:error.code,status:error.status,detail:error.message,code:error.code});}
