import type {Authorizer,VerifiedRequestContext} from "@athyper/server-contract-auth";
import type {SupplierWorkforceDistributionEligibility,SupplierWorkforcePolicyCoordinates,SupplierWorkforcePolicyReadiness,WorkforceRequisition,WorkforceRequisitionDistributionProof} from "@athyper/server-contract-master-data";
import {evaluateSupplierWorkforceGate,getSupplierWorkforcePolicyReadiness} from "@athyper/server-contract-master-data";
import {MasterDataError} from "./errors.js";

export const supplierWorkforceRequisitionPermissions=Object.freeze({read:"neon.workforce.request.read",publish:"neon.workforce.request.decide"} as const);
export interface SupplierWorkforceRequisitionRepository<Tx>{list(input:{tenantId:string;companyCodeId?:string},tx:Tx):Promise<readonly WorkforceRequisition[]>;get(input:{tenantId:string;requisitionId:string},tx:Tx):Promise<WorkforceRequisition|null>;findPublication(input:{tenantId:string;idempotencyKey:string},tx:Tx):Promise<Readonly<{requisition:WorkforceRequisition;distributionIds:readonly string[];outboxId:string;replayed:true;expectedVersion:number;actorId:string;supplierTargets:readonly Readonly<{supplierId:string;responseDueAt?:string}>[]}>|null>;publish(input:{tenantId:string;requisitionId:string;expectedVersion:number;distributions:readonly WorkforceRequisitionDistributionProof[];idempotencyKey:string;actorId:string},tx:Tx):Promise<Readonly<{requisition:WorkforceRequisition;distributionIds:readonly string[];outboxId:string;replayed:boolean}>|null>;}
export interface SupplierWorkforceRequisitionService{list(input:{context:VerifiedRequestContext;companyCodeId?:string}):Promise<readonly WorkforceRequisition[]>;policyReadiness(input:{context:VerifiedRequestContext}):Promise<SupplierWorkforcePolicyReadiness>;publish(input:{context:VerifiedRequestContext;requisitionId:string;expectedVersion:number;suppliers:readonly Readonly<{supplierId:string;responseDueAt?:string}>[];idempotencyKey:string}):Promise<Readonly<{requisition:WorkforceRequisition;distributionIds:readonly string[];outboxId:string;replayed:boolean}>>;}
export function createSupplierWorkforceRequisitionService<Tx>(options:{authorizer:Authorizer;repository:SupplierWorkforceRequisitionRepository<Tx>;eligibility:SupplierWorkforceDistributionEligibility;policies?:SupplierWorkforcePolicyCoordinates;transactions:{run<T>(plane:"neon",actor:{tenantId:string;principalId:string;requestId:string;correlationId?:string},work:(tx:Tx)=>Promise<T>):Promise<T>}}):SupplierWorkforceRequisitionService{
 const run=<T>(context:VerifiedRequestContext,work:(tx:Tx)=>Promise<T>)=>options.transactions.run("neon",actor(context),work);
 return{
  async list({context,companyCodeId}){contextGuard(context);await permit(options.authorizer,context,supplierWorkforceRequisitionPermissions.read,{...(companyCodeId?{companyCodeId}:{})});return run(context,tx=>options.repository.list({tenantId:context.tenantId,...(companyCodeId?{companyCodeId}:{})},tx));},
  async policyReadiness({context}){contextGuard(context);await permit(options.authorizer,context,supplierWorkforceRequisitionPermissions.read,{});return getSupplierWorkforcePolicyReadiness(options.policies??{});},
  async publish(input){contextGuard(input.context);key(input.idempotencyKey);if(!Number.isSafeInteger(input.expectedVersion)||input.expectedVersion<1)throw invalid("expectedVersion must be positive");if(input.suppliers.length<1||input.suppliers.length>100||new Set(input.suppliers.map(item=>item.supplierId)).size!==input.suppliers.length)throw invalid("suppliers must contain 1 to 100 distinct entries");await permit(options.authorizer,input.context,supplierWorkforceRequisitionPermissions.publish,{requisitionId:input.requisitionId});const prior=await run(input.context,tx=>options.repository.findPublication({tenantId:input.context.tenantId,idempotencyKey:input.idempotencyKey},tx));if(prior){if(prior.requisition.id!==input.requisitionId||prior.expectedVersion!==input.expectedVersion||prior.actorId!==input.context.principalId||canonicalTargets(prior.supplierTargets)!==canonicalTargets(input.suppliers))throw new MasterDataError(409,"WORKFORCE_REQUISITION_IDEMPOTENCY_CONFLICT","Idempotency key was reused with different publication coordinates");return prior;}const requisition=await run(input.context,tx=>options.repository.get({tenantId:input.context.tenantId,requisitionId:input.requisitionId},tx));if(!requisition)throw new MasterDataError(404,"WORKFORCE_REQUISITION_NOT_FOUND","Workforce requisition was not found");if(requisition.status!=="approved")throw new MasterDataError(409,"WORKFORCE_REQUISITION_NOT_APPROVED","Only an approved requisition can be published");if(requisition.rowVersion!==input.expectedVersion)throw new MasterDataError(409,"WORKFORCE_REQUISITION_VERSION_CONFLICT","Workforce requisition version changed");const boundary=evaluateSupplierWorkforceGate("requisition_publish",{});if(!boundary.allowed)throw new MasterDataError(409,"WORKFORCE_POLICY_REQUIRED",boundary.reasonCodes.join(", "));const decisions=await Promise.all(input.suppliers.map(item=>options.eligibility.evaluate({context:input.context,requisition,supplierId:item.supplierId,...(item.responseDueAt?{responseDueAt:item.responseDueAt}:{})})));const denied=decisions.flatMap(item=>item.allowed?[]:item.reasonCodes);if(denied.length)throw new MasterDataError(409,"WORKFORCE_REQUISITION_SUPPLIER_INELIGIBLE",[...new Set(denied)].join(", "));const proofs=decisions.map(item=>item.proof).filter((item):item is WorkforceRequisitionDistributionProof=>Boolean(item));if(proofs.length!==input.suppliers.length)throw new MasterDataError(503,"WORKFORCE_DISTRIBUTION_EVIDENCE_UNAVAILABLE","Eligibility authority did not return complete proof");const result=await run(input.context,tx=>options.repository.publish({tenantId:input.context.tenantId,requisitionId:input.requisitionId,expectedVersion:input.expectedVersion,distributions:proofs,idempotencyKey:input.idempotencyKey,actorId:input.context.principalId},tx));if(!result)throw new MasterDataError(409,"WORKFORCE_REQUISITION_VERSION_CONFLICT","Publish command did not produce a result");return result;}
 };
}
function contextGuard(context:VerifiedRequestContext){if(context.planeKey!=="neon")throw invalid("NEON context is required");}
async function permit(authorizer:Authorizer,context:VerifiedRequestContext,permissionCode:string,resource:Readonly<Record<string,unknown>>){if(!(await authorizer.authorize({context,permissionCode,resource:{tenantId:context.tenantId,...resource}})).allowed)throw new MasterDataError(403,"FORBIDDEN",`Permission denied: ${permissionCode}`);}
function key(value:string){if(value.trim()!==value||value.length<8||value.length>200)throw invalid("idempotencyKey must contain 8 to 200 trimmed characters");}
function invalid(message:string){return new MasterDataError(400,"WORKFORCE_REQUISITION_INVALID",message);}
function actor(context:VerifiedRequestContext){return{tenantId:context.tenantId,principalId:context.principalId,requestId:context.requestId,...(context.correlationId?{correlationId:context.correlationId}:{})};}
function canonicalTargets(value:readonly Readonly<{supplierId:string;responseDueAt?:string}>[]){return JSON.stringify([...value].map(item=>[item.supplierId,item.responseDueAt??null]).sort(([left],[right])=>String(left).localeCompare(String(right))));}
