import { sql, type Transaction } from "kysely";
import type { ImportValidationRow, ImportValidationSummary, RecordImportSession } from "@athyper/server-contract-records";
import type { ImportStagingStore, StoredImport } from "./transfer-service.js";

export type RecordTransferTransaction = Transaction<Record<string, never>>;
type Row = Readonly<Record<string, unknown>>;
interface SessionRow { id:string;tenant_id:string;entity_code:string;status:RecordImportSession["status"];staged_row_count:number|string;valid_row_count:number|string;invalid_row_count:number|string;checksum:string;next_chunk_index:number|string;validation_rows:unknown;validation_summary:unknown;error_report_key:string|null;created_at:Date|string;created_by:string;cancelled_at:Date|string|null; }

export class KyselyRecordTransferStore implements ImportStagingStore<RecordTransferTransaction> {
  async create(session: RecordImportSession, rows: readonly Row[], tx?: RecordTransferTransaction): Promise<void> {
    if (!tx) throw new Error("Record transfer creation requires a transaction");
    const inserted=await sql<{id:string}>`INSERT INTO ops.record_import_session(id,tenant_id,entity_code,status,staged_row_count,valid_row_count,invalid_row_count,checksum,next_chunk_index,created_at,created_by) VALUES(${session.id}::uuid,${session.tenantId}::uuid,${session.entityCode},${session.status},${session.stagedRowCount},${session.validRowCount},${session.invalidRowCount},${session.checksum},${session.nextChunkIndex??0},${session.createdAt}::timestamptz,master.current_principal_id()) ON CONFLICT(tenant_id,id) DO NOTHING RETURNING id`.execute(tx);
    if (!inserted.rows[0]) { const current=await this.get(session.tenantId,session.id,tx); if(!current||stable(current.session)!==stable(session)||stable(current.rows)!==stable(rows))throw new Error("Import session idempotency conflict"); return; }
    if(rows.length)await sql`INSERT INTO ops.record_import_chunk(tenant_id,session_id,chunk_index,row_count,rows,chunk_checksum,cumulative_checksum) VALUES(${session.tenantId}::uuid,${session.id}::uuid,0,${rows.length},${JSON.stringify(rows)}::jsonb,${session.checksum},${session.checksum})`.execute(tx);
  }

  async get(tenantId:string,sessionId:string,tx?:RecordTransferTransaction):Promise<StoredImport|null>{if(!tx)throw new Error("Record transfer reads require a transaction");const result=await sql<SessionRow>`SELECT * FROM ops.record_import_session WHERE tenant_id=${tenantId}::uuid AND id=${sessionId}::uuid LIMIT 1`.execute(tx),row=result.rows[0];if(!row)return null;const chunks=await sql<{rows:unknown}>`SELECT rows FROM ops.record_import_chunk WHERE tenant_id=${tenantId}::uuid AND session_id=${sessionId}::uuid ORDER BY chunk_index`.execute(tx);return{session:mapSession(row),rows:chunks.rows.flatMap(chunk=>json<Row[]>(chunk.rows)),...(row.validation_rows?{validation:json<ImportValidationRow[]>(row.validation_rows)}:{}),...(row.validation_summary?{summary:json<ImportValidationSummary>(row.validation_summary)}:{})};}

  async getChunk(tenantId:string,sessionId:string,chunkIndex:number,tx:RecordTransferTransaction){const row=(await sql<{chunk_checksum:string;cumulative_checksum:string;row_count:number|string}>`SELECT chunk_checksum,cumulative_checksum,row_count FROM ops.record_import_chunk WHERE tenant_id=${tenantId}::uuid AND session_id=${sessionId}::uuid AND chunk_index=${chunkIndex}`.execute(tx)).rows[0];return row?{chunkChecksum:row.chunk_checksum,cumulativeChecksum:row.cumulative_checksum,rowCount:Number(row.row_count)}:null;}

  async appendChunk(input:{tenantId:string;sessionId:string;chunkIndex:number;rows:readonly Row[];chunkChecksum:string;cumulativeChecksum:string},tx:RecordTransferTransaction):Promise<"created"|"replayed">{
    const locked=await sql<{status:string;next_chunk_index:number|string}>`SELECT status,next_chunk_index FROM ops.record_import_session WHERE tenant_id=${input.tenantId}::uuid AND id=${input.sessionId}::uuid FOR UPDATE`.execute(tx),session=locked.rows[0];if(!session||session.status!=="uploading")throw new Error("Import upload session is unavailable");
    const existing=await sql<{chunk_checksum:string;cumulative_checksum:string;rows:unknown}>`SELECT chunk_checksum,cumulative_checksum,rows FROM ops.record_import_chunk WHERE tenant_id=${input.tenantId}::uuid AND session_id=${input.sessionId}::uuid AND chunk_index=${input.chunkIndex}`.execute(tx),chunk=existing.rows[0];if(chunk){if(chunk.chunk_checksum!==input.chunkChecksum||chunk.cumulative_checksum!==input.cumulativeChecksum||stable(json(chunk.rows))!==stable(input.rows))throw new Error("Import chunk idempotency conflict");return"replayed";}
    if(Number(session.next_chunk_index)!==input.chunkIndex)throw new Error(`Expected import chunk ${session.next_chunk_index}`);
    await sql`INSERT INTO ops.record_import_chunk(tenant_id,session_id,chunk_index,row_count,rows,chunk_checksum,cumulative_checksum) VALUES(${input.tenantId}::uuid,${input.sessionId}::uuid,${input.chunkIndex},${input.rows.length},${JSON.stringify(input.rows)}::jsonb,${input.chunkChecksum},${input.cumulativeChecksum})`.execute(tx);
    await sql`UPDATE ops.record_import_session SET staged_row_count=staged_row_count+${input.rows.length},checksum=${input.cumulativeChecksum},next_chunk_index=next_chunk_index+1,updated_at=clock_timestamp() WHERE tenant_id=${input.tenantId}::uuid AND id=${input.sessionId}::uuid`.execute(tx);return"created";
  }

  async seal(input:{tenantId:string;sessionId:string;expectedChunkCount:number;checksum:string},tx:RecordTransferTransaction){const result=await sql`UPDATE ops.record_import_session SET status='staged',updated_at=clock_timestamp() WHERE tenant_id=${input.tenantId}::uuid AND id=${input.sessionId}::uuid AND status='uploading' AND next_chunk_index=${input.expectedChunkCount} AND checksum=${input.checksum}`.execute(tx);if(Number(result.numAffectedRows)!==1)throw new Error("Import upload seal mismatch");}
  async saveValidation(sessionId:string,rows:readonly ImportValidationRow[],tx?:RecordTransferTransaction,summary?:ImportValidationSummary,errorReportKey?:string){if(!tx)throw new Error("Validation persistence requires a transaction");const valid=rows.filter(row=>row.valid).length;await sql`UPDATE ops.record_import_session SET validation_rows=${JSON.stringify(rows)}::jsonb,validation_summary=${summary?JSON.stringify(summary):null}::jsonb,error_report_key=${errorReportKey??null},valid_row_count=${valid},invalid_row_count=${rows.length-valid},updated_at=clock_timestamp() WHERE id=${sessionId}::uuid`.execute(tx);}
  async setStatus(sessionId:string,status:RecordImportSession["status"],tx?:RecordTransferTransaction){if(!tx)throw new Error("Status changes require a transaction");const completed=["committed","failed"].includes(status);await sql`UPDATE ops.record_import_session SET status=${status},completed_at=CASE WHEN ${completed} THEN clock_timestamp() ELSE completed_at END,updated_at=clock_timestamp() WHERE id=${sessionId}::uuid`.execute(tx);}
  async cancelImport(tenantId:string,sessionId:string,cancelledAt:string,tx:RecordTransferTransaction){const found=await sql<{status:string}>`SELECT status FROM ops.record_import_session WHERE tenant_id=${tenantId}::uuid AND id=${sessionId}::uuid FOR UPDATE`.execute(tx),row=found.rows[0];if(!row)return"not_found"as const;if(["committed","cancelled","failed"].includes(row.status))return"already_terminal"as const;await sql`UPDATE ops.record_import_session SET status='cancelled',cancelled_at=${cancelledAt}::timestamptz,updated_at=clock_timestamp() WHERE tenant_id=${tenantId}::uuid AND id=${sessionId}::uuid`.execute(tx);return"cancelled"as const;}
  async saveExportRequest(input:{id:string;tenantId:string;entityCode:string;exactFilter:Readonly<Record<string,unknown>>;actorPrincipalId:string;status:"queued"},tx:RecordTransferTransaction){const result=await sql<{id:string}>`INSERT INTO ops.record_export_request(id,tenant_id,entity_code,exact_filter,actor_principal_id,status) VALUES(${input.id}::uuid,${input.tenantId}::uuid,${input.entityCode},${JSON.stringify(input.exactFilter)}::jsonb,${input.actorPrincipalId}::uuid,${input.status}) ON CONFLICT(tenant_id,id) DO NOTHING RETURNING id`.execute(tx);if(result.rows[0])return"created"as const;const existing=await sql<{entity_code:string;exact_filter:unknown;actor_principal_id:string}>`SELECT entity_code,exact_filter,actor_principal_id FROM ops.record_export_request WHERE tenant_id=${input.tenantId}::uuid AND id=${input.id}::uuid`.execute(tx),row=existing.rows[0];if(!row||row.entity_code!==input.entityCode||row.actor_principal_id!==input.actorPrincipalId||stable(json(row.exact_filter))!==stable(input.exactFilter))throw new Error("Export request idempotency conflict");return"replayed"as const;}
  async cancelExport(tenantId:string,requestId:string,cancelledAt:string,tx:RecordTransferTransaction){const found=await sql<{status:string}>`SELECT status FROM ops.record_export_request WHERE tenant_id=${tenantId}::uuid AND id=${requestId}::uuid FOR UPDATE`.execute(tx),row=found.rows[0];if(!row)return"not_found"as const;if(row.status!=="queued"&&row.status!=="running")return"already_terminal"as const;await sql`UPDATE ops.record_export_request SET status='cancelled',cancelled_at=${cancelledAt}::timestamptz WHERE tenant_id=${tenantId}::uuid AND id=${requestId}::uuid`.execute(tx);return"cancelled"as const;}
  async getExport(tenantId:string,requestId:string,tx:RecordTransferTransaction){const result=await sql<{entity_code:string;actor_principal_id:string;status:"queued"|"running"|"completed"|"cancelled"|"failed";artifact_key:string|null;row_count:number|string|null}>`SELECT entity_code,actor_principal_id,status,artifact_key,row_count FROM ops.record_export_request WHERE tenant_id=${tenantId}::uuid AND id=${requestId}::uuid`.execute(tx),row=result.rows[0];return row?{entityCode:row.entity_code,actorPrincipalId:row.actor_principal_id,status:row.status,...(row.artifact_key?{artifactKey:row.artifact_key}:{}),...(row.row_count!==null?{rowCount:Number(row.row_count)}:{})}:null;}
  async claimImport(tenantId:string,sessionId:string,checksum:string,tx:RecordTransferTransaction){const changed=await sql`UPDATE ops.record_import_session SET status='running',updated_at=clock_timestamp() WHERE tenant_id=${tenantId}::uuid AND id=${sessionId}::uuid AND status='commit_queued' AND checksum=${checksum}`.execute(tx);if(Number(changed.numAffectedRows)!==1)return null;return this.get(tenantId,sessionId,tx);}
  async completeImport(tenantId:string,sessionId:string,tx:RecordTransferTransaction){await sql`UPDATE ops.record_import_session SET status='committed',completed_at=clock_timestamp(),updated_at=clock_timestamp() WHERE tenant_id=${tenantId}::uuid AND id=${sessionId}::uuid AND status='running'`.execute(tx);}
  async releaseImport(tenantId:string,sessionId:string,tx:RecordTransferTransaction){await sql`UPDATE ops.record_import_session SET status='commit_queued',updated_at=clock_timestamp() WHERE tenant_id=${tenantId}::uuid AND id=${sessionId}::uuid AND status='running'`.execute(tx);}
  async failImport(tenantId:string,sessionId:string,tx:RecordTransferTransaction){await sql`UPDATE ops.record_import_session SET status='failed',completed_at=clock_timestamp(),updated_at=clock_timestamp() WHERE tenant_id=${tenantId}::uuid AND id=${sessionId}::uuid AND status='running'`.execute(tx);}
  async claimExport(tenantId:string,requestId:string,tx:RecordTransferTransaction){const result=await sql<{entity_code:string;exact_filter:unknown;actor_principal_id:string}>`UPDATE ops.record_export_request SET status='running',started_at=COALESCE(started_at,clock_timestamp()) WHERE tenant_id=${tenantId}::uuid AND id=${requestId}::uuid AND status='queued' RETURNING entity_code,exact_filter,actor_principal_id`.execute(tx),row=result.rows[0];return row?{entityCode:row.entity_code,exactFilter:json<Readonly<Record<string,unknown>>>(row.exact_filter),actorPrincipalId:row.actor_principal_id}:null;}
  async completeExport(tenantId:string,requestId:string,artifactKey:string,rowCount:number,tx:RecordTransferTransaction){await sql`UPDATE ops.record_export_request SET status='completed',artifact_key=${artifactKey},row_count=${rowCount},completed_at=clock_timestamp() WHERE tenant_id=${tenantId}::uuid AND id=${requestId}::uuid AND status='running'`.execute(tx);}
  async failExport(tenantId:string,requestId:string,errorCode:string,tx:RecordTransferTransaction){await sql`UPDATE ops.record_export_request SET status='failed',error_code=${errorCode.slice(0,200)},completed_at=clock_timestamp() WHERE tenant_id=${tenantId}::uuid AND id=${requestId}::uuid AND status='running'`.execute(tx);}
  async releaseExport(tenantId:string,requestId:string,tx:RecordTransferTransaction){await sql`UPDATE ops.record_export_request SET status='queued',started_at=NULL WHERE tenant_id=${tenantId}::uuid AND id=${requestId}::uuid AND status='running'`.execute(tx);}
}

function mapSession(row:SessionRow):RecordImportSession{return{id:row.id,tenantId:row.tenant_id,entityCode:row.entity_code,status:row.status,stagedRowCount:Number(row.staged_row_count),validRowCount:Number(row.valid_row_count),invalidRowCount:Number(row.invalid_row_count),checksum:row.checksum,nextChunkIndex:Number(row.next_chunk_index),createdAt:iso(row.created_at),createdBy:row.created_by,...(row.error_report_key?{errorReportKey:row.error_report_key}:{}),...(row.cancelled_at?{cancelledAt:iso(row.cancelled_at)}:{})};}
function json<T>(value:unknown):T{return(typeof value==="string"?JSON.parse(value):value)as T;}
function iso(value:Date|string){return value instanceof Date?value.toISOString():new Date(value).toISOString();}
function stable(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`;}
