import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { Application, NextFunction, Request, RequestHandler, Response } from "express";
import { defineRouteContract, HttpError, registerContractRoute, type HttpMethod, type RouteContract } from "@athyper/server-runtime-http";
import { RecordServiceError } from "../errors.js";
import type { RecordTransferService } from "./transfer-service.js";
import { UnsafeStructuredImportError } from "./structured-import-file-codec.js";
import { UnsafeWorkbookError } from "./xlsx-workbook-codec.js";

const objectSchema = { type: "object", additionalProperties: true } as const;

export function registerRecordTransferRoutes(application:Application,options:{authenticate:RequestHandler;readContext:(response:Response)=>VerifiedRequestContext;transfers:RecordTransferService}):void{
  registerTransferRoutes(application,options,{pathPrefix:"/api/records",operationPrefix:"records",tag:"Records Transfer"});
}

/** Versioned bearer-authenticated contract for external clients. It delegates to
 * the same authorization, staging, validation, worker, and receipt service as UI
 * traffic; no alternate write path is introduced. */
export function registerPublicRecordTransferRoutes(application:Application,options:{authenticate:RequestHandler;readContext:(response:Response)=>VerifiedRequestContext;transfers:RecordTransferService}):void{
  registerTransferRoutes(application,options,{pathPrefix:"/api/v1/records",operationPrefix:"public.v1.records",tag:"Public Records Transfer V1"});
}

function registerTransferRoutes(application:Application,options:{authenticate:RequestHandler;readContext:(response:Response)=>VerifiedRequestContext;transfers:RecordTransferService},contractOptions:{pathPrefix:string;operationPrefix:string;tag:string}):void{
  const api=(suffix:string)=>`${contractOptions.pathPrefix}${suffix}`,operation=(suffix:string)=>`${contractOptions.operationPrefix}.${suffix}`;
  const route=(handler:(request:Request,context:VerifiedRequestContext)=>Promise<{status?:number;body?:unknown}>)=>async(request:Request,response:Response,next:NextFunction)=>{try{const result=await handler(request,options.readContext(response));response.status(result.status??200).json(result.body);}catch(error){next(asHttpError(error));}};
  registerContractRoute(application,contract("post",api("/:entityCode/imports"),operation("beginImport"),"records.import",201,true,contractOptions.tag),options.authenticate,route(async(request,context)=>{const input=body(request);return{status:201,body:await options.transfers.beginImport(context,param(request,"entityCode"),optionalUuid(input["sessionId"]),importOperation(input["operation"]),{scopeCoordinate:stringRecord(input["scopeCoordinate"]),conflictPolicy:conflictPolicy(input["conflictPolicy"]),atomicity:atomicity(input["atomicity"])})};}));
  registerContractRoute(application,contract("put",api("/imports/:sessionId/chunks/:chunkIndex"),operation("appendImportChunk"),"records.import",200,true,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.appendImportChunk(context,uuidParam(request,"sessionId"),integerParam(request,"chunkIndex"),rows(body(request)["rows"]))})));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/complete"),operation("completeImportUpload"),"records.import",200,true,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.completeImportUpload(context,uuidParam(request,"sessionId"),integer(body(request)["expectedChunkCount"],"expectedChunkCount"))})));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/workbook-upload"),operation("prepareWorkbookUpload"),"records.import",200,true,contractOptions.tag),options.authenticate,route(async(request,context)=>{const input=body(request);return{body:await options.transfers.prepareWorkbookUpload(context,uuidParam(request,"sessionId"),text(input["fileName"],"fileName"),positiveInteger(input["sizeBytes"],"sizeBytes"))};}));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/workbook-complete"),operation("completeWorkbookUpload"),"records.import",200,true,contractOptions.tag),options.authenticate,route(async(request,context)=>{const input=body(request);return{body:await options.transfers.completeWorkbookUpload(context,uuidParam(request,"sessionId"),text(input["fileName"],"fileName"),positiveInteger(input["sizeBytes"],"sizeBytes"))};}));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/file-upload"),operation("prepareFileUpload"),"records.import",200,true,contractOptions.tag),options.authenticate,route(async(request,context)=>{const input=body(request);return{body:await options.transfers.prepareWorkbookUpload(context,uuidParam(request,"sessionId"),text(input["fileName"],"fileName"),positiveInteger(input["sizeBytes"],"sizeBytes"))};}));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/file-complete"),operation("completeFileUpload"),"records.import",200,true,contractOptions.tag),options.authenticate,route(async(request,context)=>{const input=body(request);return{body:await options.transfers.completeWorkbookUpload(context,uuidParam(request,"sessionId"),text(input["fileName"],"fileName"),positiveInteger(input["sizeBytes"],"sizeBytes"))};}));
  registerContractRoute(application,contract("get",api("/:entityCode/import-template.xlsx"),operation("createWorkbookTemplate"),"records.import",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.createWorkbookTemplate(context,param(request,"entityCode"))})));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/validate"),operation("validateImport"),"records.import",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.validate(context,uuidParam(request,"sessionId"))})));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/preview"),operation("previewImport"),"records.import",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.preview(context,uuidParam(request,"sessionId"))})));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/commit"),operation("commitImport"),"records.import",202,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({status:202,body:await options.transfers.commit(context,uuidParam(request,"sessionId"))})));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/cancel"),operation("cancelImport"),"records.import",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.cancelImport(context,uuidParam(request,"sessionId"))})));
  registerContractRoute(application,contract("post",api("/imports/:sessionId/restart"),operation("restartImport"),"records.import",202,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({status:202,body:await options.transfers.restartImport(context,uuidParam(request,"sessionId"))})));
  registerContractRoute(application,contract("get",api("/imports/:sessionId/error-report"),operation("getImportErrorReport"),"records.import",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.downloadErrorReport(context,uuidParam(request,"sessionId"),optionalInteger(request.query["expirySeconds"]))})));
  registerContractRoute(application,contract("get",api("/imports/:sessionId"),operation("getImport"),"records.import",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.getImport(context,uuidParam(request,"sessionId"))})));
  registerContractRoute(application,contract("post",api("/:entityCode/exports"),operation("requestExport"),"records.export",202,true,contractOptions.tag),options.authenticate,route(async(request,context)=>({status:202,body:await options.transfers.requestExport(context,param(request,"entityCode"),record(body(request)["filter"]),optionalUuid(body(request)["requestId"]))})));
  registerContractRoute(application,contract("post",api("/exports/:exportRequestId/cancel"),operation("cancelExport"),"records.export",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.cancelExport(context,uuidParam(request,"exportRequestId"))})));
  registerContractRoute(application,contract("post",api("/exports/:exportRequestId/restart"),operation("restartExport"),"records.export",202,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({status:202,body:await options.transfers.restartExport(context,uuidParam(request,"exportRequestId"))})));
  registerContractRoute(application,contract("get",api("/exports/:exportRequestId/download"),operation("downloadExport"),"records.export",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.downloadExport(context,uuidParam(request,"exportRequestId"),optionalInteger(request.query["expirySeconds"]))})));
  registerContractRoute(application,contract("get",api("/transfers"),operation("listOwnTransfers"),"records.transfer.read_own",200,false,contractOptions.tag),options.authenticate,route(async(request,context)=>({body:await options.transfers.listTransfers(context,optionalInteger(request.query["limit"]))})));
}

function contract(method:HttpMethod,path:string,operationId:string,permission:string,successStatus=200,requestBody=false,tag="Records Transfer"):RouteContract{return defineRouteContract({method,path,operationId,summary:operationId,tags:[tag],authenticated:true,permission,...(requestBody?{request:{body:objectSchema}}:{}),responses:{[successStatus]:{description:"Record transfer result",body:objectSchema},400:{description:"Invalid transfer request"},401:{description:"Authentication required"},403:{description:"Forbidden"},404:{description:"Transfer not found"},409:{description:"Transfer state conflict"},413:{description:"Transfer limit exceeded"},422:{description:"Transfer content rejected"},429:{description:"Rate limit exceeded"}}});}

function body(request:Request):Record<string,unknown>{return request.body&&typeof request.body==="object"&&!Array.isArray(request.body)?request.body as Record<string,unknown>:{};}
function param(request:Request,key:string):string{const value=request.params[key];if(typeof value!=="string"||!value.trim())throw bad(`Missing ${key}`);return value;}
function uuidParam(request:Request,key:string):string{return uuid(param(request,key),key);}
function optionalUuid(value:unknown):string|undefined{return value===undefined?undefined:uuid(value,"id");}
function importOperation(value:unknown):"create"|"update"|"upsert"|"delete"|"replace"{if(value===undefined)return"create";if(value!=="create"&&value!=="update"&&value!=="upsert"&&value!=="delete"&&value!=="replace")throw bad("operation must be create, update, upsert, delete, or replace");return value;}
function conflictPolicy(value:unknown):"reject"|"skip"|undefined{if(value===undefined)return undefined;if(value!=="reject"&&value!=="skip")throw bad("conflictPolicy must be reject or skip");return value;}
function atomicity(value:unknown):"all_or_nothing"|"valid_rows"|undefined{if(value===undefined)return undefined;if(value!=="all_or_nothing"&&value!=="valid_rows")throw bad("atomicity must be all_or_nothing or valid_rows");return value;}
function stringRecord(value:unknown):Readonly<Record<string,string>>|undefined{if(value===undefined)return undefined;if(!value||typeof value!=="object"||Array.isArray(value)||Object.values(value).some(item=>typeof item!=="string"))throw bad("scopeCoordinate must be an object of strings");return value as Readonly<Record<string,string>>;}
function uuid(value:unknown,key:string):string{if(typeof value!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw bad(`${key} must be a UUID`);return value;}
function integerParam(request:Request,key:string):number{return integer(Number(param(request,key)),key);}
function integer(value:unknown,key:string):number{if(typeof value!=="number"||!Number.isSafeInteger(value)||value<0)throw bad(`${key} must be a non-negative integer`);return value;}
function positiveInteger(value:unknown,key:string):number{const parsed=integer(value,key);if(parsed===0)throw bad(`${key} must be greater than zero`);return parsed;}
function text(value:unknown,key:string):string{if(typeof value!=="string"||!value.trim())throw bad(`${key} is required`);return value.trim();}
function optionalInteger(value:unknown):number|undefined{if(value===undefined)return undefined;const parsed=Number(Array.isArray(value)?value[0]:value);return integer(parsed,"expirySeconds");}
function rows(value:unknown):readonly Readonly<Record<string,unknown>>[]{if(!Array.isArray(value)||!value.length||value.some(item=>!item||typeof item!=="object"||Array.isArray(item)))throw bad("rows must be a non-empty array of objects");return value as readonly Readonly<Record<string,unknown>>[];}
function record(value:unknown):Readonly<Record<string,unknown>>{if(value===undefined)return{};if(!value||typeof value!=="object"||Array.isArray(value))throw bad("filter must be an object");return value as Readonly<Record<string,unknown>>;}
function bad(message:string){return Object.assign(new TypeError(message),{status:400,code:"INVALID_RECORD_TRANSFER_REQUEST"});}
function asHttpError(error:unknown):unknown{if(error instanceof RecordServiceError)return new HttpError(error.statusCode,error.code,error.message);if(error instanceof UnsafeStructuredImportError||error instanceof UnsafeWorkbookError)return new HttpError(422,error.code,error.message);if(error&&typeof error==="object"){const item=error as Record<string,unknown>,status=item["statusCode"];if(typeof status==="number"&&typeof item["code"]==="string"&&error instanceof Error)return new HttpError(status,item["code"],error.message);}return error;}
