import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { AuditRecorder } from "@athyper/server-contract-audit";
import type { OutboxWriter } from "@athyper/server-contract-events";
import type { JobExecutionResult, JobHandler, JobPublisher, JobTransportControl } from "@athyper/server-contract-jobs";
import type { MetadataReader } from "@athyper/server-contract-metadata";
import type { RecordFilter, RecordQueryService, RecordRepository, RecordSort } from "@athyper/server-contract-records";
import type { PlaneTransactionCoordinator } from "@athyper/server-foundation/transaction";
import { descriptorFor } from "../query-service.js";
import type { CancellableRecordJobDispatcher, ImportErrorReportStore } from "./transfer-service.js";
import type { KyselyRecordTransferStore, RecordTransferTransaction } from "./kysely-transfer-store.js";

export const RECORD_TRANSFER_QUEUE="records.transfer";
export const EXECUTE_RECORD_IMPORT_JOB="records.import.execute";
export const EXECUTE_RECORD_EXPORT_JOB="records.export.execute";
interface ImportPayload{readonly planeKey:"studio"|"neon"|"mesh";readonly tenantId:string;readonly sessionId:string;readonly checksum:string;readonly actorPrincipalId:string;readonly context:VerifiedRequestContext;}
interface ExportPayload{readonly planeKey:"studio"|"neon"|"mesh";readonly tenantId:string;readonly entityCode:string;readonly exactFilter:Readonly<Record<string,unknown>>;readonly actorPrincipalId:string;readonly exportRequestId:string;readonly context:VerifiedRequestContext;}
export interface RecordExportArtifactStore extends ImportErrorReportStore { writeExport(input:{tenantId:string;exportRequestId:string;content:AsyncIterable<Uint8Array>;contentType:"application/x-ndjson"}):Promise<string>; }

export function createRecordTransferJobDispatcher(jobs:JobPublisher&Partial<JobTransportControl>):CancellableRecordJobDispatcher{return{
  enqueue:async(kind,payload,options)=>{if(kind==="bulk")throw new Error("Bulk jobs use the bulk dispatcher");return jobs.enqueue(RECORD_TRANSFER_QUEUE,kind==="import"?EXECUTE_RECORD_IMPORT_JOB:EXECUTE_RECORD_EXPORT_JOB,payload,{jobId:options?.jobId,maxAttempts:5,execution:coordinate(payload),payloadSchema:{name:kind==="import"?EXECUTE_RECORD_IMPORT_JOB:EXECUTE_RECORD_EXPORT_JOB,version:1}});},
  ...(jobs.cancel?{cancel:(jobId:string)=>jobs.cancel!(RECORD_TRANSFER_QUEUE,jobId)}:{}),
};}

export function createRecordImportHandler(options:{store:KyselyRecordTransferStore;metadata:MetadataReader;repository:RecordRepository<RecordTransferTransaction>;transactions:PlaneTransactionCoordinator<RecordTransferTransaction>;audit:AuditRecorder<RecordTransferTransaction>;outbox:OutboxWriter<RecordTransferTransaction>}):JobHandler<typeof EXECUTE_RECORD_IMPORT_JOB,ImportPayload>{return{async handle(job,execution):Promise<JobExecutionResult>{const input=validImport(job.data);execution.signal.throwIfAborted();const staged=await options.transactions.run(input.planeKey,input.context,tx=>options.store.claimImport(input.tenantId,input.sessionId,input.checksum,tx));if(!staged)return{status:"discarded",reason:"session_unavailable"};const descriptor=await descriptorFor(options.metadata,input.context,staged.session.entityCode);try{await options.transactions.run(input.planeKey,input.context,async tx=>{let completed=0;for(const row of staged.rows){execution.signal.throwIfAborted();await options.repository.create(descriptor,input.tenantId,row,tx);completed++;if(completed%100===0)await execution.reportProgress({stage:"import",completed,total:staged.rows.length});}await options.store.completeImport(input.tenantId,input.sessionId,tx);await options.audit.record({eventCode:"records.import.committed",action:"import",outcome:"success",actor:{kind:"user",principalId:input.actorPrincipalId},tenantId:input.tenantId,entityType:staged.session.entityCode,requestId:input.context.requestId,metadata:{sessionId:input.sessionId,rowCount:staged.rows.length,checksum:input.checksum}},tx);await options.outbox.append({tenantId:input.tenantId,topic:"records.transfer",eventType:"records.import.committed",eventKey:`records:import:${input.sessionId}:committed`,entityType:staged.session.entityCode,entityId:input.sessionId,aggregateType:"records.import_session",aggregateId:input.sessionId,actorId:input.actorPrincipalId,payload:{sessionId:input.sessionId,rowCount:staged.rows.length,checksum:input.checksum}},tx);});return{status:"completed",output:{sessionId:input.sessionId,rowCount:staged.rows.length}};}catch(error){await options.transactions.run(input.planeKey,input.context,tx=>job.attempt>=job.maxAttempts?options.store.failImport(input.tenantId,input.sessionId,tx):options.store.releaseImport(input.tenantId,input.sessionId,tx)).catch(()=>undefined);throw error;}}};}

export function createRecordExportHandler(options:{store:KyselyRecordTransferStore;queries:RecordQueryService;transactions:PlaneTransactionCoordinator<RecordTransferTransaction>;artifacts:RecordExportArtifactStore;audit:AuditRecorder<RecordTransferTransaction>;outbox:OutboxWriter<RecordTransferTransaction>}):JobHandler<typeof EXECUTE_RECORD_EXPORT_JOB,ExportPayload>{return{async handle(job,execution):Promise<JobExecutionResult>{const input=validExport(job.data);const request=await options.transactions.run(input.planeKey,input.context,tx=>options.store.claimExport(input.tenantId,input.exportRequestId,tx));if(!request)return{status:"discarded",reason:"request_unavailable"};let rowCount=0;const content=(async function*(){const encoder=new TextEncoder();let cursor:string|undefined;do{execution.signal.throwIfAborted();const page=await options.queries.list({context:input.context,entityCode:request.entityCode,limit:100,...filters(request.exactFilter),...(cursor?{cursor}:{})});for(const row of page.data){rowCount++;yield encoder.encode(`${JSON.stringify(row)}\n`);}cursor=page.pagination.nextCursor;await execution.reportProgress({stage:"export",rowCount});}while(cursor);})();try{const artifactKey=await options.artifacts.writeExport({tenantId:input.tenantId,exportRequestId:input.exportRequestId,content,contentType:"application/x-ndjson"});await options.transactions.run(input.planeKey,input.context,async tx=>{await options.store.completeExport(input.tenantId,input.exportRequestId,artifactKey,rowCount,tx);await options.audit.record({eventCode:"records.export.completed",action:"export",outcome:"success",actor:{kind:"user",principalId:input.actorPrincipalId},tenantId:input.tenantId,entityType:request.entityCode,requestId:input.context.requestId,metadata:{exportRequestId:input.exportRequestId,rowCount,artifactKey}},tx);await options.outbox.append({tenantId:input.tenantId,topic:"records.transfer",eventType:"records.export.completed",eventKey:`records:export:${input.exportRequestId}:completed`,entityType:request.entityCode,entityId:input.exportRequestId,aggregateType:"records.export_request",aggregateId:input.exportRequestId,actorId:input.actorPrincipalId,payload:{exportRequestId:input.exportRequestId,rowCount,artifactKey}},tx);});return{status:"completed",output:{exportRequestId:input.exportRequestId,rowCount,artifactKey}};}catch(error){await options.transactions.run(input.planeKey,input.context,tx=>job.attempt>=job.maxAttempts?options.store.failExport(input.tenantId,input.exportRequestId,error instanceof Error?error.name:"export_failed",tx):options.store.releaseExport(input.tenantId,input.exportRequestId,tx)).catch(()=>undefined);throw error;}}};}

function coordinate(payload:Readonly<Record<string,unknown>>){const planeKey=payload["planeKey"],tenantId=payload["tenantId"],principalId=payload["actorPrincipalId"];if(!["studio","neon","mesh"].includes(String(planeKey))||typeof tenantId!=="string"||typeof principalId!=="string")throw new TypeError("Record transfer job coordinates are invalid");return{planeKey:planeKey as "studio"|"neon"|"mesh",scope:"tenant"as const,tenantId,principalId};}
function validImport(value:ImportPayload){if(value.context.planeKey!==value.planeKey||value.context.tenantId!==value.tenantId||value.context.principalId!==value.actorPrincipalId)throw new Error("Import job context mismatch");return value;}
function validExport(value:ExportPayload){if(value.context.planeKey!==value.planeKey||value.context.tenantId!==value.tenantId||value.context.principalId!==value.actorPrincipalId)throw new Error("Export job context mismatch");return value;}
function filters(value:Readonly<Record<string,unknown>>){const rawFilters=value["filters"],rawSort=value["sort"],search=value["search"];return{...(Array.isArray(rawFilters)?{filters:rawFilters as readonly RecordFilter[]}:{}),...(Array.isArray(rawSort)?{sort:rawSort as readonly RecordSort[]}:{}),...(typeof search==="string"&&search?{search}:{})};}
