import { readFileSync } from "node:fs";
import { build } from "esbuild";
import { test, expect } from "@playwright/test";
const styles = ["packages/platform/foundation/theme/src/styles.css", "packages/platform/foundation/ui/src/styles.css", "packages/platform/entity/runtime/list-view/src/styles.css", "packages/platform/shell/shell/src/styles.css", "packages/planes/neon/shell/src/styles.css"].map(p => readFileSync(p,"utf8").replace(/@import[^;]+;/g,"")).join("\n");
const script=build({stdin:{resolveDir:process.cwd(),loader:"tsx",contents:`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{CompanyGroups}from'./packages/platform/foundation/ui/src/company-groups';import{ShellContextSelector,ShellContextPickerPanel}from'./packages/platform/shell/shell/src/client';import{DirectoryFilterEditor}from'./packages/platform/entity/runtime/list-view/src/directory-filters';const companies=['Germany','Canada'].flatMap((country,i)=>[0,1].map(n=>({companyCodeId:country+n,code:(i?'ACFB':'ADPM')+(n?'.OPS':''),displayName:'Athyper '+country+(n?' Operations':' Manufacturing'),legalEntityId:country,legalEntityName:'Athyper '+country+' Manufacturing',legalEntityCode:'LE-'+(i?'ACFB':'ADPM'),countryCode:i?'CA':'DE',functionalCurrency:i?'CAD':'EUR'})));function App(){const[value,setValue]=useState({});const[selected,setSelected]=useState("Germany0");const[query,setQuery]=useState("");return <main><h2>Filters</h2><nav>Quick filters　　All filters　　<strong>Organization & company</strong></nav><DirectoryFilterEditor adapter={{value,companies,organizations:[{id:'org',displayName:'Europe Operations',companyAssignments:[{companyCodeId:'Germany0'}]}],apply:()=>{}}} value={value} onChange={setValue} kinds={['company']}/><div className="athyper-shell__business-context"><ShellContextSelector ariaLabel="Working company" name={selected} interactive><ShellContextPickerPanel className="neon-company-picker__panel" title="Choose company" description="Choose your working company"><CompanyGroups closeOnSelect companies={companies} selectedId={selected} onSelect={setSelected} query={query} onQueryChange={setQuery}/></ShellContextPickerPanel></ShellContextSelector></div><footer>Changes ready to apply　　<button>Cancel</button>　<button>Apply filters</button></footer></main>}createRoot(document.getElementById('root')).render(<App/>);`},bundle:true,write:false,format:"iife",platform:"browser",jsx:"automatic"});
for(const width of [1100,430])test(`company groups are readable and searchable at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.setContent(`<style>${styles}body{margin:0;padding:16px;background:#f5f7fa}main{padding:24px;background:white;border:1px solid #d4deec;border-radius:16px}nav{padding:20px 0;border-bottom:1px solid #d4deec}footer{padding:24px 0;border-top:1px solid #d4deec}</style><div id="root"></div>`);await page.addScriptTag({content:(await script).outputFiles[0]!.text});
 await expect(page.locator('.a-company-groups__group:visible')).toHaveCount(2);
 await page.getByRole('checkbox').nth(1).check();await expect(page.getByRole('checkbox').nth(1)).toBeChecked();await page.getByRole('checkbox').nth(2).check();await expect(page.getByRole('checkbox').nth(2)).toBeChecked();await expect(page.getByRole('checkbox').nth(1)).toBeChecked();
 await page.getByLabel('Search company name or code').first().fill('ACFB');await expect(page.locator('.a-company-groups__group:visible')).toHaveCount(1);await expect(page.locator('.a-company-groups__heading:visible')).toContainText('Canada');
 await page.getByLabel('Search company name or code').first().fill('');await page.locator('.a-company-groups__heading').first().click();await expect(page.locator('.a-company-groups__heading').first()).toHaveAttribute('aria-expanded','false');
 await page.locator('.a-company-groups__heading').first().click();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 const toolbar=page.locator('.a-scope-picker-toolbar').first();
 const boxes=await toolbar.locator(':scope > *').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().y));
 expect(Math.max(...boxes)-Math.min(...boxes)).toBeLessThan(20);
 await page.getByLabel('Working company',{exact:true}).click();
 const panel=page.locator('.neon-company-picker__panel');
 await expect(panel).toBeVisible();
 const row=panel.locator('.a-company-groups__row').first();
 const aligned=await row.evaluate(n=>{const a=n.querySelector('input').getBoundingClientRect(),b=n.querySelector('span').getBoundingClientRect();return Math.abs(a.y+a.height/2-b.y-b.height/2)<2});
 expect(aligned).toBe(true);
 await panel.getByRole('radio').first().check();
 await expect(panel).not.toBeVisible();
 await page.getByLabel('Working company',{exact:true}).click();
 await expect(panel.locator('input:checked')).toHaveCount(1);
 await page.keyboard.press('Escape');
 await page.screenshot({path:test.info().outputPath('company-filter.png'),fullPage:true});
});
