import { buildSync } from "esbuild";
import { readFileSync } from "node:fs";
import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
const css = readFileSync("packages/platform/shell/shell/src/styles.css", "utf8");
const bundle = buildSync({ entryPoints: ["scripts/verification/shell-browser-entry.tsx"], bundle: true, write: false, format: "iife", platform: "browser", jsx: "automatic", nodePaths: ["apps/neon/node_modules"] }).outputFiles[0]!.text;
async function mount(page: import("@playwright/test").Page, width = 900, empty = false, path = "/", query = "") { const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message)); await page.setViewportSize({ width, height: 700 }); await page.route("https://shell.test/**", (route) => route.request().url().endsWith("/api/auth/session/context") ? route.fallback() : route.fulfill({ contentType: "text/html", body: `<!doctype html><html lang="en"><head><style>${css}</style></head><body><div id="root"></div></body></html>` })); await page.goto(`https://shell.test${path}${empty ? "?empty" : query}`); await page.evaluate(bundle); if (empty) await expect(page.getByRole("heading", { name: "No applications available" })).toBeVisible(); else if (path === "/forbidden") await expect(page.getByRole("heading", { name: "Access denied" })).toBeVisible(); else await expect(page.getByRole("heading", { name: "Dashboard" })).toBeVisible(); expect(errors).toEqual([]); }

test("desktop shell exposes landmarks, skip navigation, slots, context, and logout", async ({ page }) => { await mount(page); await expect(page.getByRole("complementary", { name: "Application navigation" })).toBeVisible(); await expect(page.getByRole("navigation", { name: "Workspaces and modules" })).toBeVisible(); await expect(page.getByRole("main")).toBeVisible(); await page.keyboard.press("Tab"); await expect(page.getByRole("link", { name: "Skip to main content" })).toBeFocused(); await expect(page.locator("[data-slot]" )).toHaveCount(4); await expect(page.getByRole("link", { name: /Context Tenant Alpha/ })).toHaveAttribute("href", "/select-context"); await page.getByText("User One", { exact: true }).first().click(); await expect(page.getByRole("button", { name: "Log out" })).toBeVisible(); const results = await new AxeBuilder({ page }).analyze(); expect(results.violations.filter((item) => item.impact === "critical")).toEqual([]); });
test("mobile drawer traps initial intent and restores focus after Escape", async ({ page }) => { await mount(page, 390); const trigger = page.getByRole("button", { name: "Open navigation" }); await trigger.click(); await expect(page.getByRole("link", { name: "General Ledger" })).toBeFocused(); await page.keyboard.press("Escape"); await expect(trigger).toBeFocused(); await expect(page.locator(".athyper-shell")).toHaveAttribute("data-drawer-open", "false"); });
test("collapse preference survives a remount without storing principal data", async ({ page }) => { await mount(page); await page.getByRole("button", { name: "Collapse navigation" }).click(); await expect(page.locator(".athyper-shell")).toHaveAttribute("data-collapsed", "true"); expect(await page.evaluate(() => localStorage.getItem("athyper.shell.collapsed"))).toBe("true"); expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain("User One"); });
test("empty entitlements render a stable accessible recovery state", async ({ page }) => { await mount(page, 900, true); await expect(page.getByRole("heading", { name: "No applications available" })).toBeVisible(); await expect(page.getByRole("link", { name: "Switch context" })).toHaveAttribute("href", "/select-context"); });
test("a directly requested forbidden route never renders protected page content", async ({ page }) => { await mount(page, 900, false, "/forbidden"); await expect(page.getByRole("heading", { name: "Access denied" })).toBeVisible(); await expect(page.getByRole("heading", { name: "Dashboard" })).toHaveCount(0); });
test("context switch posts only the selected tenant to the same-origin session route", async ({ page }) => { let body = ""; await page.route("https://shell.test/api/auth/session/context", async (route) => { body = route.request().postData() ?? ""; await route.fulfill({ status: 204 }); }); await mount(page, 900, false, "/", "?multi"); await page.getByRole("combobox", { name: "Tenant context" }).selectOption("tenant-beta"); await expect.poll(() => body).toBe('{"tenantId":"tenant-beta"}'); });
