"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, RefreshCw, Search } from "lucide-react";
import { Button, Input, Label, Skeleton } from "@athyper/ui/primitives";
import { PageFrame } from "@athyper/ui/layout";
import { useCurrencyFxSetup, useFxResolutionTrace, useSaveFxPolicy, type FxPolicy } from "../../hooks/useCurrencyFxSetup";

export function CurrencyFxSetupView({companyCode}:{companyCode:string}){
 const setup=useCurrencyFxSetup(companyCode),save=useSaveFxPolicy(companyCode),[form,setForm]=useState<Partial<FxPolicy>>({}),[pair,setPair]=useState({fromCurrency:"USD",toCurrency:"MYR",rateType:"SPOT"}),[run,setRun]=useState(false);
 const trace=useFxResolutionTrace(companyCode,pair,run); useEffect(()=>{const selected=setup.data?.policyResolution.selected;if(selected)setForm(selected.companyCodeId?selected:{...selected,id:undefined});},[setup.data]);
 if(setup.isLoading)return <PageFrame><Skeleton className="h-[560px] rounded-xl"/></PageFrame>;
 if(!setup.data)return <PageFrame><div className="rounded-xl border p-8">Currency & FX setup is unavailable. <Button className="ml-2" onClick={()=>setup.refetch()}>Retry</Button></div></PageFrame>;
 const d=setup.data,p=form;
 return <PageFrame><div className="flex flex-col gap-5 pb-10">
  <header className="flex flex-col gap-3 rounded-xl border bg-card p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Finance Setup · Currency & FX</p><h1 className="mt-1 text-xl font-semibold">{d.company.name} ({d.company.code})</h1><p className="text-sm text-muted-foreground">Functional currency {d.company.functionalCurrency} · policy, coverage and revaluation readiness</p></div><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>setup.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button><Button asChild variant="outline"><Link href={`/finance/setup/tenant/${encodeURIComponent(d.company.tenantCode)}/currency-fx`}>Rate Workbench</Link></Button><Button asChild variant="outline"><Link href="/finance/setup">Setup home</Link></Button></div></header>
  <section className="grid gap-3 md:grid-cols-4">{Object.entries({"Approved policy":d.readiness.policyApproved,"Required pairs":d.readiness.requiredPairCoverage,"FX posting roles":d.readiness.postingRolesReady,"Revaluation ready":d.readiness.revaluationReady}).map(([label,ok])=><div key={label} className="rounded-xl border bg-card p-4"><div className="flex items-center gap-2">{ok?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:<CircleAlert className="h-5 w-5 text-amber-600"/>}<span className="font-medium">{label}</span></div><p className="mt-2 text-xs text-muted-foreground">{ok?"Ready":"Action required"}</p></div>)}</section>
  <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
   <section className="rounded-xl border bg-card"><div className="border-b p-5"><h2 className="font-semibold">Approved resolution policy</h2><p className="text-sm text-muted-foreground">Company policy; a book-specific policy wins when configured.</p></div><div className="grid gap-4 p-5 sm:grid-cols-2">
    <Field label="Transaction context"><Input value={p.transactionContext??"general"} onChange={e=>setForm({...p,transactionContext:e.target.value})}/></Field><Field label="Effective from"><Input type="date" value={p.effectiveFrom??new Date().toISOString().slice(0,10)} onChange={e=>setForm({...p,effectiveFrom:e.target.value})}/></Field>
    <SelectField label="Default rate type" value={p.defaultRateType??"SPOT"} onChange={v=>setForm({...p,defaultRateType:v})}/><SelectField label="Revaluation rate type" value={p.revaluationRateType??"PERIOD_END"} onChange={v=>setForm({...p,revaluationRateType:v})}/>
    <Field label="Preferred sources (ordered)"><Input value={(p.preferredSources??[]).join(", ")} placeholder="ECB, CENTRAL_BANK, MANUAL" onChange={e=>setForm({...p,preferredSources:e.target.value.split(",").map(x=>x.trim().toUpperCase()).filter(Boolean)})}/></Field><Field label="Maximum age (days)"><Input type="number" min="0" value={p.maximumRateAgeDays??""} onChange={e=>setForm({...p,maximumRateAgeDays:e.target.value===""?null:Number(e.target.value)})}/></Field>
    <Field label="Explicit pivot"><Input maxLength={3} value={p.pivotCurrencyCode??""} placeholder="Required for triangulation" onChange={e=>setForm({...p,pivotCurrencyCode:e.target.value.toUpperCase()||null})}/></Field><div className="flex flex-col gap-2 pt-6"><Check label="Allow inverse" checked={p.allowInverse!==false} onChange={v=>setForm({...p,allowInverse:v})}/><Check label="Allow triangulation" checked={Boolean(p.allowTriangulation)} onChange={v=>setForm({...p,allowTriangulation:v})}/><Check label="Auto-reverse revaluation" checked={p.autoReverseRevaluation!==false} onChange={v=>setForm({...p,autoReverseRevaluation:v})}/></div>
   </div><div className="flex justify-end border-t p-4"><Button disabled={save.isPending} onClick={()=>save.mutate({...p,status:"active"})}>{save.isPending?"Saving…":"Save & approve policy"}</Button></div>{save.error&&<p className="px-5 pb-4 text-sm text-destructive">{String(save.error)}</p>}</section>
   <section className="rounded-xl border bg-card"><div className="border-b p-5"><h2 className="font-semibold">Required-pair coverage</h2><p className="text-sm text-muted-foreground">Derived from assigned books and linked bank accounts.</p></div><div className="divide-y">{d.requiredPairs.length===0?<p className="p-5 text-sm text-muted-foreground">No foreign-currency exposure discovered.</p>:d.requiredPairs.map(r=><div key={`${r.fromCurrency}-${r.toCurrency}`} className="p-4"><div className="flex items-center justify-between"><span className="font-medium">{r.fromCurrency} <ArrowRight className="inline h-3.5 w-3.5"/> {r.toCurrency} · {r.rateType}</span><span className={r.covered?"text-sm text-emerald-700":"text-sm text-amber-700"}>{r.covered?"Covered":"Missing"}</span></div><p className="mt-1 text-xs text-muted-foreground">{r.reasons.join(" · ")}{r.selectedRate?` · ${r.selectedRate.source} ${r.selectedRate.effectiveDate}`:""}</p></div>)}</div></section>
  </div>
  <section className="rounded-xl border bg-card"><div className="border-b p-5"><h2 className="font-semibold">Resolution trace</h2><p className="text-sm text-muted-foreground">Explain policy selection, inverse use, source preference, age rejection and pivot legs.</p></div><div className="flex flex-wrap gap-3 p-5"><Input className="w-24" maxLength={3} value={pair.fromCurrency} onChange={e=>{setRun(false);setPair({...pair,fromCurrency:e.target.value.toUpperCase()})}}/><Input className="w-24" maxLength={3} value={pair.toCurrency} onChange={e=>{setRun(false);setPair({...pair,toCurrency:e.target.value.toUpperCase()})}}/><select className="h-10 rounded-md border bg-background px-3 text-sm" value={pair.rateType} onChange={e=>{setRun(false);setPair({...pair,rateType:e.target.value})}}>{RATE_TYPES.map(x=><option key={x}>{x}</option>)}</select><Button onClick={()=>setRun(true)}><Search className="mr-2 h-4 w-4"/>Resolve</Button></div>{run&&<div className="border-t p-5">{trace.isLoading?<Skeleton className="h-24"/>:<><p className="font-medium">{trace.data?.selected?`${trace.data.selected.rate} via ${trace.data.selected.path.join(" → ")} (${trace.data.selected.method})`:"No eligible rate"}</p><ol className="mt-3 space-y-2">{trace.data?.attempts.map((a,i)=><li key={i} className="text-sm"><span className={a.accepted?"text-emerald-700":"text-muted-foreground"}>{a.accepted?"Accepted":"Skipped"}</span> · {a.method} · {a.reason}</li>)}</ol></>}</div>}</section>
 </div></PageFrame>;
}
const RATE_TYPES=["SPOT","PERIOD_AVG","PERIOD_END","BUDGET","CONTRACTED","HISTORICAL"];
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-1.5"><Label>{label}</Label>{children}</div>}
function SelectField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <Field label={label}><select className="h-10 rounded-md border bg-background px-3 text-sm" value={value} onChange={e=>onChange(e.target.value)}>{RATE_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
