"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, CircleAlert, RefreshCw, Upload } from "lucide-react";
import { Button, Skeleton, Textarea } from "@athyper/ui/primitives";
import { PageFrame } from "@athyper/ui/layout";
import { useFxRates, useImportFxRates, useValidateFxImport } from "../../hooks/useCurrencyFxSetup";

const sample=`fromCurrency,toCurrency,rate,rateType,effectiveDate,effectiveTime,source,sourceReference
USD,MYR,4.7200000000,SPOT,2026-07-20,09:00,MANUAL,TREASURY-20260720`;
function parseCsv(text:string){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(lines.length<2)return [];const headers=lines[0]!.split(",").map(x=>x.trim());return lines.slice(1).map(line=>Object.fromEntries(line.split(",").map((value,i)=>[headers[i],value.trim()])));}

export function FxRateWorkbench({tenantCode}:{tenantCode:string}){
 const rates=useFxRates(tenantCode),validate=useValidateFxImport(tenantCode),post=useImportFxRates(tenantCode),[csv,setCsv]=useState(sample);const rows=useMemo(()=>parseCsv(csv),[csv]);
 return <PageFrame><div className="flex flex-col gap-5 pb-10"><header className="flex flex-col gap-3 rounded-xl border bg-card p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Finance Setup · Tenant definitions</p><h1 className="mt-1 text-xl font-semibold">FX Rate Workbench</h1><p className="text-sm text-muted-foreground">Validate before posting; matching active keys are superseded with full history retained.</p></div><div className="flex gap-2"><Button variant="ghost" onClick={()=>rates.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button><Button asChild variant="outline"><Link href={`/finance/setup/tenant/${encodeURIComponent(tenantCode)}`}>Tenant setup</Link></Button></div></header>
 <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><section className="rounded-xl border bg-card"><div className="border-b p-5"><h2 className="font-semibold">Import rates</h2><p className="text-sm text-muted-foreground">CSV columns use ISO currency, date and time values.</p></div><div className="p-5"><Textarea className="min-h-56 font-mono text-xs" value={csv} onChange={e=>setCsv(e.target.value)}/><div className="mt-3 flex gap-2"><Button variant="outline" disabled={!rows.length||validate.isPending} onClick={()=>validate.mutate(rows)}>{validate.isPending?"Validating…":"Validate"}</Button><Button disabled={!validate.data||validate.data.summary.invalid>0||post.isPending} onClick={()=>post.mutate(rows)}><Upload className="mr-2 h-4 w-4"/>{post.isPending?"Posting…":"Post validated rates"}</Button></div>{validate.data&&<div className="mt-4 rounded-lg border p-3"><p className="text-sm font-medium">{validate.data.summary.valid} valid · {validate.data.summary.invalid} invalid · {validate.data.summary.warnings} warnings</p><div className="mt-2 max-h-44 space-y-1 overflow-auto">{validate.data.rows.map(r=><div key={r.rowNumber} className="flex gap-2 text-xs">{r.valid?<CheckCircle2 className="h-4 w-4 text-emerald-600"/>:<CircleAlert className="h-4 w-4 text-red-600"/>}<span>Row {r.rowNumber}: {[...r.errors,...r.warnings].join(" · ")||"Ready"}</span></div>)}</div></div>}{(validate.error||post.error)&&<p className="mt-3 text-sm text-destructive">{String(validate.error??post.error)}</p>}{post.isSuccess&&<p className="mt-3 text-sm text-emerald-700">Rates posted successfully.</p>}</div></section>
 <section className="rounded-xl border bg-card"><div className="border-b p-5"><h2 className="font-semibold">Rate history</h2><p className="text-sm text-muted-foreground">Latest 100 active and superseded records.</p></div>{rates.isLoading?<Skeleton className="m-5 h-64"/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/40 text-left text-xs text-muted-foreground"><tr>{["Pair","Rate","Type","Effective","Source","Status"].map(h=><th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y">{rates.data?.rates.map(r=><tr key={r.id}><td className="px-4 py-3 font-medium">{r.fromCurrency}/{r.toCurrency}</td><td className="px-4 py-3 font-mono">{r.rate}</td><td className="px-4 py-3">{r.rateType}</td><td className="px-4 py-3">{r.effectiveDate}{r.effectiveTime?` ${r.effectiveTime}`:""}</td><td className="px-4 py-3">{r.source}</td><td className="px-4 py-3 capitalize">{r.status}</td></tr>)}</tbody></table>{!rates.data?.rates.length&&<p className="p-8 text-center text-sm text-muted-foreground">No FX rates have been loaded.</p>}</div>}</section></div></div></PageFrame>;
}
