"use client";
import { PlatformHome } from "@athyper/platform-shell";
import { useExperienceNavigation } from "@athyper/platform-shell-app-foundation";
import { type ExperienceRuntimeRegistry } from "@athyper/platform-shell-dashboard";
import { PlaneExperienceSurface, safeExperiencePath } from "@athyper/platform-shell-dashboard/plane-experience-runtime";
import { SEMANTIC_ICONS } from "@athyper/platform-icons";
import { useMemo } from "react";
import { meshCatalogRoutes } from "@/lib/catalog-routes";
function AtlasWelcome(){const navigation=useExperienceNavigation(),props=useMemo(()=>homeProps(navigation),[navigation]);return <PlatformHome {...props}/>;}
const registry:ExperienceRuntimeRegistry={dataSources:{"catalog.summary":context=>({value:Number(context.entityCount??context.moduleCount??0),items:[]})},actions:{"catalog.navigate":input=>safeExperiencePath(input.path)},extensions:{"mesh.atlas-welcome":AtlasWelcome,"mesh.network-overview":()=> <p>Network overview</p>},icons:SEMANTIC_ICONS,assets:{"brand:mesh/network":"/brand/mesh-network.webp"}};
const config={plane:"mesh",displayName:"Mesh",catalogRoutes:meshCatalogRoutes,registry} as const;
export function MeshExperienceSurface({surfaceKey,workspaceCode,moduleCode,context}:Readonly<{surfaceKey:string;workspaceCode?:string;moduleCode?:string;context?:Readonly<Record<string,string>>}>){return <PlaneExperienceSurface config={config} surfaceKey={surfaceKey} workspaceCode={workspaceCode} moduleCode={moduleCode} context={context}/>;}
function homeProps(navigation:ReturnType<typeof useExperienceNavigation>){const entitled=new Map(navigation.map(item=>[item.code,item])),routes=meshCatalogRoutes.flatMap(workspace=>{const access=entitled.get(workspace.code);return access?[{workspace,access}]:[];});return {suggestions:["Review my priorities","Plan today’s work","Review pending approvals"],workspaces:routes.map(({workspace,access})=>({name:access.name,description:`Connect to ${access.modules.length} authorized collaboration modules.`,href:`/${workspace.routeSlug}`,status:"Available workspace",modules:access.modules.map(item=>item.name)})),quickActions:routes.flatMap(({workspace,access})=>access.modules.slice(0,1).flatMap(module=>{const route=workspace.modules.find(item=>item.code===module.code);return route?[{label:`Open ${module.name}`,description:`Continue work in ${access.name}`,href:`/${workspace.routeSlug}/${route.routeSlug}`}]:[];})).slice(0,4),searchItems:routes.flatMap(({workspace,access})=>[{title:access.name,description:"Open workspace overview",href:`/${workspace.routeSlug}`,category:"Workspace",keywords:[workspace.code]},...access.modules.flatMap(module=>{const route=workspace.modules.find(item=>item.code===module.code);return route?[{title:module.name,description:`Open ${access.name}`,href:`/${workspace.routeSlug}/${route.routeSlug}`,category:"Module",keywords:[module.code]}]:[];})]),citationRoutes:{}} as const;}
