#!/usr/bin/env tsx
import{readFile}from"node:fs/promises";import{resolve}from"node:path";import pg from"pg";
import{compileEntityPlaneArtifact}from"../../../packages/services/meta-entity-authoring/src/entity-plane-artifact-compiler.js";
function argument(name:string){return process.argv.find(value=>value.startsWith(`${name}=`))?.slice(name.length+1)}
const adminUrl=argument("--admin-url"),adminDatabase=argument("--admin-database"),neonUrl=argument("--neon-url"),neonDatabase=argument("--neon-database");if(!adminUrl||!adminDatabase||!neonUrl||!neonDatabase)throw new Error("Explicit Admin/Neon URLs and database guards required");
const config=JSON.parse(await readFile(resolve(import.meta.dirname,"config/p5-g-neon-consumer-certification.v1.json"),"utf8")) as {contractVersion:string;entityCode:string;expectedOperations:string[];currentReleaseHash:string;currentArtifactHash:string;requiredRolloutMode:string};
const[runtimeSource,permissionSource,auditSinkSource]=await Promise.all([
 readFile(resolve(import.meta.dirname,"../../../src/runtimes/api.ts"),"utf8"),
 readFile(resolve(import.meta.dirname,"../../../packages/services/iam/permission/permission.service.ts"),"utf8"),
 readFile(resolve(import.meta.dirname,"../../../packages/services/iam/authorization-runtime/sql-audit-sink.ts"),"utf8"),
]);
const admin=new pg.Client({connectionString:adminUrl}),neon=new pg.Client({connectionString:neonUrl});await Promise.all([admin.connect(),neon.connect()]);
try{
 const[adminIdentity,neonIdentity]=await Promise.all([admin.query<{database_name:string}>("select current_database() database_name"),neon.query<{database_name:string}>("select current_database() database_name")]);if(adminIdentity.rows[0]?.database_name!==adminDatabase||neonIdentity.rows[0]?.database_name!==neonDatabase)throw new Error("P5-G database guard rejected target");
 const source=(await admin.query<{entity_id:string;release_id:string;release_hash:string;revision_id:string;revision_hash:string;contract_hash:string;contract_json:Record<string,unknown>}>(`select e.id::text entity_id,r.id::text release_id,r.release_hash,r.revision_id::text,s.revision_hash,r.contract_hash,s.contract_json from metadata.entity e join metadata.entity_release r on r.entity_id=e.id join snapshot.entity_contract_revision s on s.id=r.revision_id where e.tenant_id is null and e.entity_code=$1 order by r.release_no desc limit 1`,[config.entityCode])).rows[0];if(!source)throw new Error("P5-G source release missing");
 const candidate=compileEntityPlaneArtifact({plane:"neon",entityId:source.entity_id,entityCode:config.entityCode,releaseId:source.release_id,releaseHash:source.release_hash,revisionId:source.revision_id,revisionHash:source.revision_hash,contractHash:source.contract_hash,contract:source.contract_json});
 const candidateHash=(await admin.query<{hash:string}>("select snapshot.fn_compute_entity_release_artifact_hash($1::uuid,$2::uuid,$3::uuid,'neon',$4,$5,$6::jsonb) hash",[source.release_id,source.revision_id,source.entity_id,source.release_hash,source.contract_hash,JSON.stringify(candidate)])).rows[0]!.hash;
 const bindings=await neon.query<{operation_key:string;source_release_hash:string;source_compiled_hash:string;permission_status:string}>(`select b.operation_key,b.source_release_hash,b.source_compiled_hash,p.status::text permission_status from authz.entity_operation_binding b join authz.permission p on p.id=b.permission_id where b.plane_code='neon' and b.entity_code=$1 and b.tenant_id is null and b.status='published' order by b.operation_key`,[config.entityCode]);
 const rollout=await neon.query<{operation_key:string;mode:string;certification_status:string|null}>(`select b.operation_key,r.mode,c.status certification_status from authz.entity_operation_binding b left join ops.authorization_operation_rollout r on r.plane_code=b.plane_code and r.source_entity_operation_id=b.source_entity_operation_id left join ops.authorization_parity_certification c on c.id=r.certification_id where b.plane_code='neon' and b.entity_code=$1 and b.tenant_id is null and b.status='published' order by b.operation_key`,[config.entityCode]);
 const qualification=await neon.query<{operation_key:string;sample_count:string;mismatch_count:string;candidate_error_count:string;required_cohort_count:number;covered_cohort_count:number;qualifies_default:boolean}>(`select b.operation_key,q.sample_count::text,q.mismatch_count::text,q.candidate_error_count::text,q.required_cohort_count,q.covered_cohort_count,q.qualifies_default from authz.entity_operation_binding b join ops.authorization_shadow_qualification_v q on q.plane_code=b.plane_code and q.entity_code=b.entity_code and q.source_entity_operation_id=b.source_entity_operation_id and q.source_release_hash=b.source_release_hash and q.source_artifact_hash=b.source_compiled_hash where b.plane_code='neon' and b.entity_code=$1 and b.tenant_id is null and b.status='published' order by b.operation_key`,[config.entityCode]);
 const protections=await neon.query<{schemaname:string;tablename:string;rowsecurity:boolean;forcerowsecurity:boolean}>(`select n.nspname schemaname,c.relname tablename,c.relrowsecurity rowsecurity,c.relforcerowsecurity forcerowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where(n.nspname,c.relname)in(('authz','entity_operation_binding'),('authz','entity_operation_scope_binding'),('ops','authorization_operation_rollout'),('ops','authorization_shadow_comparison'),('audit','authorization_decision_evidence')) order by 1,2`);
 const operations=bindings.rows.map(row=>row.operation_key),bindingCoverage=config.expectedOperations.every(key=>operations.includes(key))&&operations.length===config.expectedOperations.length;
 const permissionReady=bindings.rows.every(row=>row.permission_status==="published"),rolloutShadow=rollout.rows.length===config.expectedOperations.length&&rollout.rows.every(row=>row.mode===config.requiredRolloutMode),rlsReady=protections.rows.length===5&&protections.rows.every(row=>row.rowsecurity&&row.forcerowsecurity);
 const parityClean=qualification.rows.length===config.expectedOperations.length&&qualification.rows.every(row=>Number(row.mismatch_count)===0&&Number(row.candidate_error_count)===0&&row.covered_cohort_count===row.required_cohort_count),activationQualified=qualification.rows.length===config.expectedOperations.length&&qualification.rows.every(row=>row.qualifies_default);
 const currentCoordinate=bindings.rows.every(row=>row.source_release_hash===config.currentReleaseHash&&row.source_compiled_hash===config.currentArtifactHash),successorImportPending=candidateHash!==config.currentArtifactHash;
 const runtimeWiring=[runtimeSource,permissionSource].every(source=>source.includes("withNormalizedOperationScopeRollout")&&source.includes("SqlNormalizedEntitlementResolver")&&source.includes("SqlOperationScopeRolloutResolver"));
 const canonicalAuditWiring=auditSinkSource.includes("INSERT INTO audit.authorization_decision_evidence")&&!auditSinkSource.includes('this.plane === "neon"\n      ? "log.auth_decision_evidence_v2"');
 const integrationPassed=bindingCoverage&&permissionReady&&rolloutShadow&&rlsReady&&parityClean&&currentCoordinate&&runtimeWiring&&canonicalAuditWiring;
 process.stdout.write(JSON.stringify({contractVersion:config.contractVersion,status:integrationPassed?(activationQualified?"certified":"integration_certified_activation_pending"):"failed",integrationPassed,activationQualified,successorImportPending,current:{releaseHash:config.currentReleaseHash,artifactHash:config.currentArtifactHash},approvedCandidate:{schema:`${candidate.artifact_schema_code}@${candidate.artifact_schema_version}`,compiledHash:candidateHash},checks:{bindingCoverage,permissionReady,rolloutShadow,rlsReady,parityClean,currentCoordinate,runtimeWiring,canonicalAuditWiring},protections:protections.rows,qualification:qualification.rows},null,2)+"\n");if(!integrationPassed)process.exitCode=2;
}finally{await Promise.all([admin.end(),neon.end()])}
