import type { LegalHold, LegalHoldRepository, LegalHoldResource, ReportPack, ReportPackRepository } from "@athyper/server-contract-governance";
import { sql, type Kysely, type Transaction } from "kysely";

type Database = Record<string, never>;
type Executor = Kysely<Database> | Transaction<Database>;
type Row = Record<string, unknown>;

export class KyselyLegalHoldRepository implements LegalHoldRepository {
  constructor(private readonly db: Kysely<Database>) {}
  async withHoldLock<T>(tenantId: string, holdId: string, work: (repository: LegalHoldRepository) => Promise<T>): Promise<T> {
    return this.db.transaction().execute(async (transaction) => {
      await sql`SELECT id FROM governance.legal_hold WHERE tenant_id=${tenantId}::uuid AND id=${holdId}::uuid FOR UPDATE`.execute(transaction);
      return work(new KyselyLegalHoldRepository(transaction));
    });
  }
  async createDraft(input: Omit<LegalHold, "resources">): Promise<LegalHold> {
    await sql`INSERT INTO governance.legal_hold(id,tenant_id,code,name,description,legal_authority,issued_at,owner_principal_id,status,created_at,created_by) VALUES(${input.id}::uuid,${input.tenantId}::uuid,${input.code},${input.name},${input.description ?? null},${input.legalAuthority ?? null},${input.issuedAt ?? null}::timestamptz,${input.ownerPrincipalId ?? null}::uuid,'draft',${input.createdAt}::timestamptz,${input.createdBy}::uuid)`.execute(this.db);
    return (await this.get(input.tenantId, input.id))!;
  }
  async get(tenantId: string, holdId: string): Promise<LegalHold | undefined> { return this.read(tenantId, holdId, this.db); }
  async addResource(tenantId: string, holdId: string, resource: LegalHoldResource, principalId: string): Promise<LegalHoldResource> {
    const row = (await sql<Row>`INSERT INTO governance.legal_hold_manifest(id,tenant_id,legal_hold_id,resource_kind,resource_schema,resource_entity,resource_id,resource_uri,content_hash,captured_at,created_at,created_by) SELECT ${resource.id}::uuid,tenant_id,id,${resource.kind},${resource.schema ?? null},${resource.entity ?? null},${resource.resourceId ?? null}::uuid,${resource.uri ?? null},${resource.contentHash ?? null},${resource.capturedAt}::timestamptz,clock_timestamp(),${principalId}::uuid FROM governance.legal_hold WHERE tenant_id=${tenantId}::uuid AND id=${holdId}::uuid AND status IN ('draft','active') RETURNING *`.execute(this.db)).rows[0];
    if (!row) throw coded("GOVERNANCE_INVALID_TRANSITION"); return resourceRow(row);
  }
  async removeDraftResource(tenantId: string, holdId: string, resourceId: string): Promise<boolean> { const result = await sql`DELETE FROM governance.legal_hold_manifest manifest USING governance.legal_hold hold WHERE manifest.tenant_id=${tenantId}::uuid AND manifest.id=${resourceId}::uuid AND manifest.legal_hold_id=${holdId}::uuid AND hold.tenant_id=manifest.tenant_id AND hold.id=manifest.legal_hold_id AND hold.status='draft'`.execute(this.db); return Number(result.numAffectedRows ?? 0) === 1; }
  async activate(tenantId: string, holdId: string, principalId: string, effectiveAt: string): Promise<LegalHold | undefined> { const result = await sql`UPDATE governance.legal_hold SET status='active',effective_at=${effectiveAt}::timestamptz,updated_by=${principalId}::uuid WHERE tenant_id=${tenantId}::uuid AND id=${holdId}::uuid AND status='draft'`.execute(this.db); return Number(result.numAffectedRows ?? 0) === 1 ? this.read(tenantId, holdId, this.db) : undefined; }
  async release(tenantId: string, holdId: string, principalId: string, releasedAt: string): Promise<LegalHold | undefined> {
    const work = async (transaction: Executor) => { const result = await sql`UPDATE governance.legal_hold SET status='released',released_at=${releasedAt}::timestamptz,updated_by=${principalId}::uuid WHERE tenant_id=${tenantId}::uuid AND id=${holdId}::uuid AND status='active'`.execute(transaction); if (Number(result.numAffectedRows ?? 0) !== 1) return undefined; await sql`UPDATE governance.legal_hold_manifest SET released_at=${releasedAt}::timestamptz WHERE tenant_id=${tenantId}::uuid AND legal_hold_id=${holdId}::uuid AND released_at IS NULL`.execute(transaction); return this.read(tenantId, holdId, transaction); };
    return this.db.isTransaction ? work(this.db) : this.db.transaction().execute(work);
  }
  private async read(tenantId: string, holdId: string, executor: Executor): Promise<LegalHold | undefined> { const hold = (await sql<Row>`SELECT * FROM governance.legal_hold WHERE tenant_id=${tenantId}::uuid AND id=${holdId}::uuid`.execute(executor)).rows[0]; if (!hold) return undefined; const resources = (await sql<Row>`SELECT * FROM governance.legal_hold_manifest WHERE tenant_id=${tenantId}::uuid AND legal_hold_id=${holdId}::uuid ORDER BY captured_at,id`.execute(executor)).rows.map(resourceRow); return holdRow(hold, resources); }
}

export class KyselyReportPackRepository implements ReportPackRepository {
  constructor(private readonly db: Kysely<Database>) {}
  async createGenerating(pack: ReportPack): Promise<ReportPack> { return this.db.transaction().execute(async (transaction) => {
    if (pack.supersedesReportPackId) { const previous = (await sql<Row>`SELECT status FROM governance.report_pack WHERE tenant_id=${pack.tenantId}::uuid AND id=${pack.supersedesReportPackId}::uuid FOR UPDATE`.execute(transaction)).rows[0]; if (previous?.["status"] !== "ready") throw coded("GOVERNANCE_INVALID_TRANSITION"); }
    await sql`INSERT INTO governance.report_pack(id,tenant_id,report_type_code,code,name,source_entity_code,source_entity_id,source_revision,parameters,supersedes_report_pack_id,job_id,status,evidence,created_at,created_by) VALUES(${pack.id}::uuid,${pack.tenantId}::uuid,${pack.reportTypeCode},${pack.code},${pack.name},${pack.source?.entityCode ?? null},${pack.source?.entityId ?? null}::uuid,${pack.source ? JSON.stringify({ revision: pack.source.revision, contentHash: pack.source.contentHash ?? null }) : null}::jsonb,${JSON.stringify(pack.parameters)}::jsonb,${pack.supersedesReportPackId ?? null}::uuid,${pack.jobId},'generating',${JSON.stringify(pack.evidence)}::jsonb,${pack.createdAt}::timestamptz,${pack.createdBy}::uuid)`.execute(transaction);
    return pack;
  }); }
  async get(tenantId: string, reportPackId: string): Promise<ReportPack | undefined> { const row = (await sql<Row>`SELECT * FROM governance.report_pack WHERE tenant_id=${tenantId}::uuid AND id=${reportPackId}::uuid`.execute(this.db)).rows[0]; return row ? reportRow(row) : undefined; }
  async complete(tenantId: string, reportPackId: string, input: { readonly artifactUri: string; readonly artifactHash: string; readonly generatedAt: string; readonly expiresAt?: string; readonly evidence: Readonly<Record<string, unknown>> }): Promise<ReportPack> { return this.db.transaction().execute(async (transaction) => { const row = (await sql<Row>`UPDATE governance.report_pack SET artifact_uri=${input.artifactUri},artifact_hash=${input.artifactHash},generated_at=${input.generatedAt}::timestamptz,expires_at=${input.expiresAt ?? null}::timestamptz,status='ready',evidence=evidence||${JSON.stringify(input.evidence)}::jsonb WHERE tenant_id=${tenantId}::uuid AND id=${reportPackId}::uuid AND status='generating' RETURNING *`.execute(transaction)).rows[0]; if (!row) throw coded("GOVERNANCE_INVALID_TRANSITION"); if(row["supersedes_report_pack_id"]){const previous=await sql`UPDATE governance.report_pack SET status='superseded',updated_by=${row["created_by"]}::uuid WHERE tenant_id=${tenantId}::uuid AND id=${String(row["supersedes_report_pack_id"])}::uuid AND status='ready'`.execute(transaction);if(Number(previous.numAffectedRows??0)!==1)throw coded("GOVERNANCE_INVALID_TRANSITION");} return reportRow(row); }); }
  async appendEvidence(tenantId: string, reportPackId: string, evidence: Readonly<Record<string, unknown>>): Promise<void> { await sql`UPDATE governance.report_pack SET evidence=evidence||${JSON.stringify(evidence)}::jsonb WHERE tenant_id=${tenantId}::uuid AND id=${reportPackId}::uuid AND status='generating'`.execute(this.db); }
  async fail(tenantId: string, reportPackId: string, evidence: Readonly<Record<string, unknown>>): Promise<void> { await sql`UPDATE governance.report_pack SET status='failed',evidence=evidence||${JSON.stringify(evidence)}::jsonb WHERE tenant_id=${tenantId}::uuid AND id=${reportPackId}::uuid AND status='generating'`.execute(this.db); }
  async listRecoverable(before: string, limit: number): Promise<readonly ReportPack[]> { const result=await sql<Row>`SELECT * FROM governance.report_pack WHERE status='generating' AND created_at<=${before}::timestamptz ORDER BY created_at,id LIMIT ${limit}`.execute(this.db); return result.rows.map(reportRow); }
}

function holdRow(row: Row, resources: readonly LegalHoldResource[]): LegalHold { return { id: text(row,"id"), tenantId:text(row,"tenant_id"), code:text(row,"code"), name:text(row,"name"), ...(row["description"]?{description:text(row,"description")}:{}), ...(row["legal_authority"]?{legalAuthority:text(row,"legal_authority")}:{}), ...(row["issued_at"]?{issuedAt:iso(row["issued_at"])}:{}), ...(row["effective_at"]?{effectiveAt:iso(row["effective_at"])}:{}), ...(row["released_at"]?{releasedAt:iso(row["released_at"])}:{}), ...(row["owner_principal_id"]?{ownerPrincipalId:text(row,"owner_principal_id")}:{}), status:text(row,"status") as LegalHold["status"], resources, createdAt:iso(row["created_at"]), createdBy:text(row,"created_by") }; }
function resourceRow(row: Row): LegalHoldResource { return { id:text(row,"id"), kind:text(row,"resource_kind") as LegalHoldResource["kind"], ...(row["resource_schema"]?{schema:text(row,"resource_schema")}:{}), ...(row["resource_entity"]?{entity:text(row,"resource_entity")}:{}), ...(row["resource_id"]?{resourceId:text(row,"resource_id")}:{}), ...(row["resource_uri"]?{uri:text(row,"resource_uri")}:{}), ...(row["content_hash"]?{contentHash:text(row,"content_hash")}:{}), capturedAt:iso(row["captured_at"]), ...(row["released_at"]?{releasedAt:iso(row["released_at"])}:{}) }; }
function reportRow(row: Row): ReportPack { const revision = object(row["source_revision"]); return { id:text(row,"id"),tenantId:text(row,"tenant_id"),reportTypeCode:text(row,"report_type_code"),code:text(row,"code"),name:text(row,"name"),...(row["source_entity_code"]&&row["source_entity_id"]?{source:{entityCode:text(row,"source_entity_code"),entityId:text(row,"source_entity_id"),revision:String(revision["revision"]),...(revision["contentHash"]?{contentHash:String(revision["contentHash"])}:{})}}:{}),parameters:object(row["parameters"]),...(row["artifact_uri"]?{artifactUri:text(row,"artifact_uri")}:{}),...(row["artifact_hash"]?{artifactHash:text(row,"artifact_hash")}:{}),...(row["generated_at"]?{generatedAt:iso(row["generated_at"])}:{}),...(row["expires_at"]?{expiresAt:iso(row["expires_at"])}:{}),...(row["supersedes_report_pack_id"]?{supersedesReportPackId:text(row,"supersedes_report_pack_id")}:{}),jobId:text(row,"job_id"),status:text(row,"status") as ReportPack["status"],evidence:object(row["evidence"]),createdAt:iso(row["created_at"]),createdBy:text(row,"created_by")}; }
function text(row: Row,key:string):string{return String(row[key]);} function iso(value:unknown):string{return new Date(String(value)).toISOString();} function object(value:unknown):Readonly<Record<string,unknown>>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};} function coded(code:string):Error{return Object.assign(new Error(code),{code});}
