import {readFileSync}from"node:fs";
import type{VerifiedRequestContext}from"@athyper/server-contract-auth";
import{BUSINESS_PARTNER_360_PERMISSIONS}from"@athyper/server-contract-master-data";
import{describe,expect,it}from"vitest";
import{createBusinessPartner360Service,type BusinessPartner360Repository}from"../index.js";

const context={planeKey:"neon",tenantId:"11111111-1111-4111-8111-111111111111",principalId:"22222222-2222-4222-8222-222222222222",requestId:"request",authEpoch:7}as unknown as VerifiedRequestContext,bp="33333333-3333-4333-8333-333333333333",org="44444444-4444-4444-8444-444444444444",company="55555555-5555-4555-8555-555555555555",link="66666666-6666-4666-8666-666666666666";
class Repository implements BusinessPartner360Repository<object>{readonly claims=new Set<string>();async resolveCore(){return{id:bp,code:"BP.DUAL",category:"organization"as const,displayName:"Dual role",status:"active",version:1,changedAt:"2026-08-30T00:00:00.000Z",businessDate:"2026-08-30",roles:[{id:"s",code:"supplier"as const,status:"active"},{id:"c",code:"customer"as const,status:"active"}],scopeValid:true,scopeResolved:true};}async readFragments(){return{identifiers:[],openWork:{activeRequestCount:0,returnedRequestCount:0,expiringQualificationCount:0,expiringCertificateCount:0,pendingBankVerificationCount:0},recentActivity:[],counts:{},provenance:[]};}async readCommonSection(){return{items:[],provenance:[],redactions:[]};}async readRoleCompanySection(){return{data:{},state:"empty"as const,provenance:[]};}async readCommercialControlSection(input:Parameters<BusinessPartner360Repository<object>["readCommercialControlSection"]>[0]){return{data:input.sectionCode==="banking"?{accounts:[{linkId:link,maskedAccount:"•••• 1234",lastFour:"1234"}]}:input.sectionCode==="credit"?{title:"Credit review",reviews:[{decision:"approved",requestedCreditLimit:1000}]}:{qualifications:[{decision:"approved"}],preferences:[],blocks:[],certifications:[]},state:"ready"as const,provenance:[]};}async claimRestrictedReveal(input:Parameters<NonNullable<BusinessPartner360Repository<object>["claimRestrictedReveal"]>>[0]){if(this.claims.has(input.revealId))return false;this.claims.add(input.revealId);return true;}async readRestrictedTaxValue(){return null;}async readRestrictedBankValue(){return{tokenOrValue:"DE12500105170648489890",protected:false};}async legacyAggregate(){return null;}}
function service(events:unknown[]=[]){return createBusinessPartner360Service({authorizer:{async authorize(input:{permissionCode:string}){return{allowed:Object.values(BUSINESS_PARTNER_360_PERMISSIONS).includes(input.permissionCode as never)}}}as never,repository:new Repository(),transactions:{async run(_p,_a,work){return work({});}},definitions:{async resolve(){return{code:"business_partner.onboarding"as const,version:"1",hash:"a".repeat(64)}}},audit:{async record(input){events.push(input);return{...input,id:"audit",occurredAt:"2026-08-30T00:00:00.000Z",severity:"info"as const};}},now:()=>new Date("2026-08-30T01:00:00.000Z")});}
const reveal={revealId:"77777777-7777-4777-8777-777777777777",purposeExpiresAt:"2026-08-30T01:00:30.000Z"};

describe("Business Partner 360 commercial controls",()=>{
  it("keeps banking masked and customer credit labeled without classification fields",async()=>{const api=service(),bank=await api.section<Record<string,unknown>>({context,businessPartnerId:bp,operatingOrganizationId:org,companyCodeId:company,sectionCode:"banking"}),credit=await api.section<Record<string,unknown>>({context,businessPartnerId:bp,operatingOrganizationId:org,companyCodeId:company,sectionCode:"credit"});expect(JSON.stringify(bank)).toContain("•••• 1234");expect(JSON.stringify(bank)).not.toContain("DE1250");expect(credit.data).toMatchObject({title:"Credit review"});expect(JSON.stringify(credit)).not.toMatch(/riskClass|riskBand|riskScore/i);});
  it("reveals bank data only through a one-time purpose-bound audited command",async()=>{const events:unknown[]=[],api=service(events),command={context,businessPartnerId:bp,bankAccountLinkId:link,purpose:"payment_verification",...reveal};const result=await api.revealBankAccount(command);expect(result).toMatchObject({value:"DE12500105170648489890",expiresAt:"2026-08-30T01:01:00.000Z"});await expect(api.revealBankAccount(command)).rejects.toMatchObject({code:"BP_360_REVEAL_REPLAYED"});expect(JSON.stringify(events)).not.toContain("DE12500105170648489890");});
  it("rejects expired purpose grants before resolving a restricted value",async()=>{await expect(service().revealBankAccount({context,businessPartnerId:bp,bankAccountLinkId:link,purpose:"payment_verification",revealId:"88888888-8888-4888-8888-888888888888",purposeExpiresAt:"2026-08-30T00:59:59.000Z"})).rejects.toMatchObject({code:"BP_360_REVEAL_PURPOSE_EXPIRED"});});
  it("keeps every SQL reader free of raw account selection and Phase 1 credit classification",()=>{const normal=readFileSync(new URL("../kysely-business-partner-360-commercial-controls.ts",import.meta.url),"utf8"),restricted=readFileSync(new URL("../kysely-business-partner-360-bank-reveal.ts",import.meta.url),"utf8");expect(normal).not.toMatch(/account_id_value|risk_class_code/i);expect(restricted).not.toMatch(/account_id_value/);expect(restricted).toMatch(/protectedValueToken/);expect(normal).toMatch(/is_virus_scanned/);});
  it("resolves every supplier commodity scope without duplicating summary records",()=>{const reader=readFileSync(new URL("../kysely-business-partner-360-commercial-controls.ts",import.meta.url),"utf8");expect(reader).toContain("master.business_partner_commodity_capability");expect(reader).toContain("master.commodity_category");expect(reader).toContain("master.commodity_code_assignment");expect(reader).toContain("shared.commodity_code");expect(reader).toContain("commodityCapabilityIds");expect(reader).toContain("commodityCategoryIds");expect(reader).toContain("jsonb_agg(DISTINCT capability.id::text");expect(reader).not.toContain("DISTINCT ON(qualification.id)");});
});
