import {describe,expect,it} from "vitest";
import type {BusinessPartner360RequirementPackDefinition} from "@athyper/server-contract-master-data";
import {evaluateBusinessPartner360Completeness,parseBusinessPartner360Definition,type BusinessPartner360ResolvedDefinition} from "../business-partner-360-completeness.js";

const packs:readonly BusinessPartner360RequirementPackDefinition[]=[
 {code:"organization_base",version:1,category:"organization",scope:"global",requirements:[{code:"organization.name",fieldCode:"partner.legalName",sectionCode:"identity",severity:"required",actionCode:"amend_partner",label:"Add legal name"},{code:"organization.tax",fieldCode:"identifier.primary",sectionCode:"identifiers-tax",severity:"recommended",requiresVerified:true,actionCode:"amend_partner",label:"Add identifier"}]},
 {code:"supplier_scope",version:1,category:"organization",role:"supplier",scope:"organization",requirements:[{code:"supplier.organization",fieldCode:"scope.supplier.organization",sectionCode:"roles-scope",severity:"required",actionCode:"assign_organization",label:"Assign organization"}]},{code:"supplier_payable",version:1,category:"organization",role:"supplier",scope:"company",requirements:[]},{code:"customer_scope",version:1,category:"organization",role:"customer",scope:"organization",requirements:[]},{code:"customer_credit",version:1,category:"organization",role:"customer",scope:"company",requirements:[]},{code:"person_base",version:1,category:"person",scope:"global",requirements:[]},{code:"workforce_active",version:1,category:"person",role:"workforce",scope:"workforce",requirements:[]},
],definition:BusinessPartner360ResolvedDefinition={code:"business_partner.onboarding",version:"1.0.0",hash:"a".repeat(64),packs};

describe("Business Partner 360 completeness",()=>{
 it("counts a verified restricted presence without disclosing a value",()=>{const result=evaluateBusinessPartner360Completeness({...base(),evidence:{"partner.legalName":{state:"present",fingerprint:"name-present"},"identifier.primary":{state:"restricted_verified",fingerprint:"verified-presence"}}});expect(result).toMatchObject({status:"complete",requiredCount:1,completeCount:1,restrictedCount:1});expect(result.recommended[0]).toMatchObject({state:"restricted_satisfied"});expect(JSON.stringify(result)).not.toContain("verified-presence-value");});
 it("fingerprints only applicable coordinates, policy, definition and requirement evidence",()=>{const first=evaluateBusinessPartner360Completeness({...base(),evidence:{"partner.legalName":{state:"present",fingerprint:"one"},"unrelated.field":{state:"verified",fingerprint:"x"}}}),unrelated=evaluateBusinessPartner360Completeness({...base(),businessPartnerVersion:99,evidence:{"partner.legalName":{state:"present",fingerprint:"one"},"unrelated.field":{state:"missing",fingerprint:"y"}}}),changed=evaluateBusinessPartner360Completeness({...base(),evidence:{"partner.legalName":{state:"present",fingerprint:"two"}}});expect(unrelated.fingerprint).toBe(first.fingerprint);expect(changed.fingerprint).not.toBe(first.fingerprint);});
 it("suppresses governed actions in historical mode",()=>{const result=evaluateBusinessPartner360Completeness({...base(),historical:true,evidence:{},actions:{amend_partner:{code:"amend_partner",label:"Propose change",href:"/governed",authority:"business_partner_request",requestKind:"amend_partner",permission:"bp.amend"}}});expect(result.readOnly).toBe(true);expect(result.missing[0]?.action).toBeUndefined();});
 it("keeps a role scope pack active when its scope is missing so a governed assignment can be offered",()=>{const action={code:"assign_organization" as const,label:"Assign organization",href:"/governed-scope",authority:"business_partner_request" as const,requestKind:"assign_organization",permission:"bp.request.create"},result=evaluateBusinessPartner360Completeness({...base(),roles:["supplier"],evidence:{"partner.legalName":{state:"present",fingerprint:"name"}},actions:{assign_organization:action}});expect(result.packs.map(item=>item.code)).toContain("supplier_scope");expect(result.required.find(item=>item.code==="supplier.organization")?.action).toEqual(action);});
 it("rejects incompatible and prohibited requirement definitions",()=>{const view={schemaVersion:1,excludedCapabilities:["risk"],completenessPacks:packs.map(pack=>({...pack,requirements:pack.code==="organization_base"?[{...pack.requirements[0],fieldCode:"risk.score"}]:pack.requirements}))};expect(()=>parseBusinessPartner360Definition({version:"1",hash:"a".repeat(64),view})).toThrow(/PROHIBITED/);expect(()=>parseBusinessPartner360Definition({version:"1",hash:"a".repeat(64),view:{...view,completenessPacks:[]}})).toThrow(/INCOMPATIBLE/);});
});
function base(){return{definition,category:"organization" as const,roles:[] as const,roleLens:"all" as const,hasOrganizationScope:false,hasCompanyScope:false,hasWorkforceScope:false,asOf:"2026-08-30",historical:false,businessPartnerVersion:1,policyFingerprint:"policy",evidence:{},actions:{},evaluatedAt:"2026-08-30T00:00:00.000Z"};}
