import{createHash}from"node:crypto";
import type{VerifiedRequestContext}from"@athyper/server-contract-auth";
import type{BusinessPartnerRequest,SupplierRegistrationInvitation,SupplierRegistrationInvitationRepository}from"@athyper/server-contract-master-data";
import{describe,expect,it}from"vitest";
import{createSupplierRegistrationInvitationExpiryHandler,createSupplierRegistrationInvitationService}from"../index.js";

const context={tenantId:"11111111-1111-4111-8111-111111111111",principalId:"22222222-2222-4222-8222-222222222222",planeKey:"neon",requestId:"request-1",assurance:"elevated"}as VerifiedRequestContext;
class MemoryRepository implements SupplierRegistrationInvitationRepository<object>{rows=new Map<string,{invitation:SupplierRegistrationInvitation;emailHash:string;tokenHash:string}>();requests=new Map<string,BusinessPartnerRequest>();
 async findByIdempotencyKey(tenantId:string,key:string){const value=[...this.rows.values()].find(row=>row.invitation.tenantId===tenantId&&row.invitation.idempotencyKey===key);return value?{invitation:value.invitation,inviteeEmailHash:value.emailHash}:null;}
 async create(input:Parameters<SupplierRegistrationInvitationRepository<object>["create"]>[0]){const invitation:SupplierRegistrationInvitation={id:"33333333-3333-4333-8333-333333333333",tenantId:input.tenantId,invitationNo:input.invitationNo,requestedRole:input.command.requestedRole??"supplier",requestedOperatingOrganizationId:input.command.operatingOrganizationId,...(input.command.companyCodeId?{optionalCompanyCodeId:input.command.companyCodeId}:{}),intendedSupplierName:input.command.intendedSupplierName,expiresAt:input.command.expiresAt,status:"pending",idempotencyKey:input.command.idempotencyKey,rowVersion:1,createdAt:"2026-08-29T00:00:00.000Z",createdBy:input.createdBy};this.rows.set(invitation.id,{invitation,emailHash:input.inviteeEmailHash,tokenHash:input.tokenHash});return invitation;}
 async get(tenantId:string,id:string){const value=this.rows.get(id);return value?.invitation.tenantId===tenantId?value.invitation:null;}
 async accept(input:Parameters<SupplierRegistrationInvitationRepository<object>["accept"]>[0]){const value=[...this.rows.values()].find(row=>row.invitation.tenantId===input.tenantId&&row.tokenHash===input.tokenHash);if(!value||value.emailHash!==input.inviteeEmailHash||(input.expectedRole&&value.invitation.requestedRole!==input.expectedRole))return null;if(value.invitation.status==="accepted"){const request=this.requests.get(value.invitation.businessPartnerRequestId!);return request?{invitation:value.invitation,request,replayed:true}:null;}if(value.invitation.status!=="pending")return null;const request:BusinessPartnerRequest={id:"44444444-4444-4444-8444-444444444444",tenantId:input.tenantId,requestNo:input.requestNo,kind:"new_partner",source:{kind:"portal"},registrationMode:"self_service",invitationId:value.invitation.id,applicantPrincipalId:input.applicantPrincipalId,requestedRole:value.invitation.requestedRole,operatingOrganizationId:value.invitation.requestedOperatingOrganizationId,schema:input.schema,proposedPayload:input.proposedPayload,validationSummary:{},duplicateSummary:{},changeImpact:{},idempotencyKey:input.requestIdempotencyKey,status:"draft",rowVersion:1,createdAt:"2026-08-29T00:01:00.000Z",createdBy:input.applicantPrincipalId};const invitation={...value.invitation,status:"accepted" as const,applicantPrincipalId:input.applicantPrincipalId,businessPartnerRequestId:request.id,acceptedAt:"2026-08-29T00:01:00.000Z",rowVersion:2};value.invitation=invitation;this.requests.set(request.id,request);return{invitation,request,replayed:false};}
 async cancel(input:Parameters<SupplierRegistrationInvitationRepository<object>["cancel"]>[0]){const value=this.rows.get(input.invitationId);if(!value||value.invitation.tenantId!==input.tenantId||value.invitation.status!=="pending"||value.invitation.rowVersion!==input.expectedVersion)return null;value.invitation={...value.invitation,status:"cancelled",cancelledAt:"2026-08-29T00:02:00.000Z",rowVersion:value.invitation.rowVersion+1,updatedBy:input.cancelledBy};return value.invitation;}
 async expireDue(input:Parameters<SupplierRegistrationInvitationRepository<object>["expireDue"]>[0]){const expired:SupplierRegistrationInvitation[]=[];for(const value of this.rows.values())if(value.invitation.tenantId===input.tenantId&&value.invitation.status==="pending"&&value.invitation.expiresAt<=input.now&&expired.length<input.limit){value.invitation={...value.invitation,status:"expired",rowVersion:value.invitation.rowVersion+1,updatedBy:input.actorId};expired.push(value.invitation);}return expired;}}
function fixture(){const repository=new MemoryRepository(),permissions:string[]=[],effects:string[]=[];const service=createSupplierRegistrationInvitationService({repository,authorizer:{async authorize(input){permissions.push(input.permissionCode);return{allowed:true};}},transactions:{async run(_plane,_actor,work){return work({});}},schemas:{async resolve(){return{code:"neon.business_partner_request",version:1,hash:"a".repeat(64)};}},audit:{async record(input){effects.push(input.eventCode);return{} as never;}},outbox:{async append(input){effects.push(input.eventType);}},createInvitationNo:()=>"SRI-TEST-001",createRequestNo:()=>"BPR-PORTAL-001",createToken:()=>"secure-invitation-token-with-at-least-32-characters",now:()=>new Date("2026-08-29T00:00:00.000Z")});return{service,repository,permissions,effects};}
function create(service:ReturnType<typeof fixture>["service"],overrides:Record<string,unknown>={}){return service.create({context,idempotencyKey:"invitation-key-001",operatingOrganizationId:"55555555-5555-4555-8555-555555555555",intendedSupplierName:"Acme Supplier",inviteeEmail:"Supplier@Example.com",expiresAt:"2026-08-30T00:00:00.000Z",...overrides});}
describe("supplier registration invitation service",()=>{
 it("returns the raw token once and persists only hashes",async()=>{const value=fixture(),first=await create(value.service),second=await create(value.service);expect(first).toMatchObject({replayed:false,token:"secure-invitation-token-with-at-least-32-characters"});expect(second).toMatchObject({replayed:true,invitation:{id:first.invitation.id}});expect(second.token).toBeUndefined();const stored=value.repository.rows.get(first.invitation.id)!;expect(stored.tokenHash).toBe(createHash("sha256").update(first.token!).digest("hex"));expect(JSON.stringify(stored)).not.toContain(first.token!);});
 it("atomically accepts and replays one portal request",async()=>{const value=fixture(),created=await create(value.service),applicant={...context,principalId:"66666666-6666-4666-8666-666666666666"}as VerifiedRequestContext;const command={context:applicant,token:created.token!,inviteeEmail:"supplier@example.com",requestIdempotencyKey:"portal-request-001",proposedPayload:{legalName:"Acme Supplier"}};const first=await value.service.accept(command),second=await value.service.accept(command);expect(first).toMatchObject({replayed:false,invitation:{status:"accepted",applicantPrincipalId:applicant.principalId},request:{source:{kind:"portal"},registrationMode:"self_service",requestedRole:"supplier"}});expect(second).toMatchObject({replayed:true,request:{id:first.request.id}});expect(value.repository.requests.size).toBe(1);});
 it("creates a role-bound customer self-service request and rejects the token on the supplier facade",async()=>{const value=fixture(),created=await create(value.service,{requestedRole:"customer",intendedSupplierName:"Acme Buyer"});await expect(value.service.accept({context,expectedRole:"supplier",token:created.token!,inviteeEmail:"supplier@example.com",requestIdempotencyKey:"portal-customer-wrong-role",proposedPayload:{legalName:"Acme Buyer"}})).rejects.toMatchObject({code:"SUPPLIER_REGISTRATION_INVITATION_NOT_FOUND"});const accepted=await value.service.accept({context,expectedRole:"customer",token:created.token!,inviteeEmail:"supplier@example.com",requestIdempotencyKey:"portal-customer-001",proposedPayload:{legalName:"Acme Buyer",customerType:"corporate"}});expect(accepted).toMatchObject({invitation:{requestedRole:"customer",status:"accepted"},request:{requestedRole:"customer",source:{kind:"portal"},registrationMode:"self_service"}});expect(value.permissions).toContain("neon.customer_registration.external.respond");});
 it("fails closed for a mismatched invitee and prevents cancelling accepted invitations",async()=>{const value=fixture(),created=await create(value.service);await expect(value.service.accept({context,token:created.token!,inviteeEmail:"attacker@example.com",requestIdempotencyKey:"portal-request-002",proposedPayload:{legalName:"Acme"}})).rejects.toMatchObject({code:"SUPPLIER_REGISTRATION_INVITATION_NOT_FOUND"});await value.service.accept({context,token:created.token!,inviteeEmail:"supplier@example.com",requestIdempotencyKey:"portal-request-003",proposedPayload:{legalName:"Acme"}});await expect(value.service.cancel({context,invitationId:created.invitation.id,expectedVersion:2})).rejects.toMatchObject({code:"SUPPLIER_REGISTRATION_INVITATION_NOT_CANCELLABLE"});});
 it("cancels pending invitations with OCC and expires due invitations through the job handler",async()=>{const cancelledValue=fixture(),created=await create(cancelledValue.service),cancelled=await cancelledValue.service.cancel({context,invitationId:created.invitation.id,expectedVersion:1});expect(cancelled.status).toBe("cancelled");const expiryValue=fixture();await create(expiryValue.service,{expiresAt:"2026-08-29T00:06:00.000Z"});const handler=createSupplierRegistrationInvitationExpiryHandler(expiryValue.service),progress:unknown[]=[];const result=await handler.handle({id:"job-1",name:"supplier-registration-invitations-expire",queue:"neon-supplier-registration-maintenance",data:{tenantId:context.tenantId,actorId:context.principalId,now:"2026-08-29T00:07:00.000Z"},attempt:1,maxAttempts:5,enqueuedAt:"2026-08-29T00:07:00.000Z"},{signal:new AbortController().signal,attempt:1,async reportProgress(value){progress.push(value);}});expect(result).toEqual({status:"completed",output:{expired:1}});expect(progress).toEqual([{expired:1}]);});
});
