import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { BusinessPartnerRequestService, PersonEvidenceView, WorkforceDetail, WorkforceRepository } from "@athyper/server-contract-master-data";
import { describe,expect,it } from "vitest";
import { createWorkforceService } from "../workforce-service.js";

const context={planeKey:"neon",tenantId:"11111111-1111-4111-8111-111111111111",principalId:"22222222-2222-4222-8222-222222222222",requestId:"33333333-3333-4333-8333-333333333333",permissions:{allowed:[]}} as unknown as VerifiedRequestContext;
const workforce:WorkforceDetail={businessPartnerId:"44444444-4444-4444-8444-444444444444",personId:"55555555-5555-4555-8555-555555555555",employeeId:"66666666-6666-4666-8666-666666666666",employeeNumber:"E001",displayName:"Ada Lovelace",firstName:"Ada",lastName:"Lovelace",readiness:{eligible:false,reasons:["ONBOARDING_INCOMPLETE"],evidenceVersion:1}};
class Repository implements WorkforceRepository<object>{
  async list(){return[workforce];}async get(){return workforce;}async completeChecklistItem(){return workforce;}
  async offboard(){return{caseId:"77777777-7777-4777-8777-777777777777",replayed:false,workforce};}
  async completeOffboardingResource(){return{caseId:"77777777-7777-4777-8777-777777777777",completed:true};}
  async requestIamProjection(){return{projectionId:"88888888-8888-4888-8888-888888888888",replayed:false};}
  async readPersonEvidence(input:Parameters<WorkforceRepository<object>["readPersonEvidence"]>[0]):Promise<PersonEvidenceView>{return{personId:input.personId,purpose:input.purpose,expiresAt:input.expiresAt,fields:{dateOfBirth:"tokenized"},redactedFields:["protectedAttributes"]};}
}
function fixture(){const repository=new Repository(),permissions:string[]=[],effects:string[]=[],requests:unknown[]=[];const service=createWorkforceService({repository,authorizer:{async authorize(input){permissions.push(input.permissionCode);return{allowed:true};}},transactions:{async run(_plane,_actor,work){return work({});}},requests:{async create(command:unknown){requests.push(command);return{request:{id:"99999999-9999-4999-8999-999999999999"},replayed:false};}} as BusinessPartnerRequestService,audit:{async record(input){effects.push(input.eventCode);return{} as never;}},outbox:{async append(input){effects.push(input.eventType);}},now:()=>new Date("2026-08-29T00:00:00.000Z")});return{service,permissions,effects,requests};}

describe("workforce lifecycle service",()=>{
  it("uses the governed request boundary for HR import and approved API records",async()=>{const value=fixture();const result=await value.service.ingest({context,source:"import",systemCode:"approved_hris",records:[{externalId:"worker-1",idempotencyKey:"hris-worker-1",legalEntityId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",companyCodeId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",orgUnitId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc",payload:{firstName:"Ada",lastName:"Lovelace"}}]});expect(result).toEqual([{externalId:"worker-1",requestId:"99999999-9999-4999-8999-999999999999",replayed:false}]);expect(value.requests[0]).toMatchObject({kind:"new_partner",requestedRole:"workforce",registrationMode:"integration",source:{kind:"import",systemCode:"approved_hris",entityId:"worker-1"}});});
  it("binds restricted evidence to purpose, fields, expiry, and audit",async()=>{const value=fixture();const result=await value.service.readPersonEvidence({context,personId:workforce.personId,purpose:"employment",fields:["dateOfBirth","protectedAttributes"]});expect(result).toMatchObject({purpose:"employment",fields:{dateOfBirth:"tokenized"},redactedFields:["protectedAttributes"],expiresAt:"2026-08-29T00:15:00.000Z"});expect(value.permissions).toEqual(["neon.workforce.pii.read"]);expect(value.effects).toEqual(["workforce.person_evidence.accessed"]);});
  it("publishes only an IAM saga intent and leaves the workforce aggregate untouched",async()=>{const value=fixture();const result=await value.service.retryIam({context,employeeId:workforce.employeeId,employerOrganizationId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",createPrincipal:true,idempotencyKey:"iam-worker-001"});expect(result).toMatchObject({replayed:false});expect(value.effects).toEqual(["workforce.iam.projection_requested","workforce.iam.projection_requested"]);expect(await value.service.get({context,employeeId:workforce.employeeId})).toEqual(workforce);});
});
