import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { PersonEvidenceView, WorkforceDetail, WorkforceRepository, WorkforceRequest, WorkforceRequestRepository } from "@athyper/server-contract-master-data";
import { describe,expect,it } from "vitest";
import { createWorkforceService } from "../workforce-service.js";

const context={planeKey:"neon",tenantId:"11111111-1111-4111-8111-111111111111",principalId:"22222222-2222-4222-8222-222222222222",requestId:"33333333-3333-4333-8333-333333333333",assurance:"elevated",permissions:{allowed:[]}} as unknown as VerifiedRequestContext;
const workforce:WorkforceDetail={personId:"55555555-5555-4555-8555-555555555555",employeeId:"66666666-6666-4666-8666-666666666666",employeeNumber:"E001",displayName:"Ada Lovelace",firstName:"Ada",lastName:"Lovelace",asOfDate:"2026-08-29",employments:[],assignments:[],readiness:{eligible:false,reasons:["ONBOARDING_INCOMPLETE"],evidenceVersion:1}};
class Repository implements WorkforceRepository<object>{
  scopes=[{legalEntityId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",companyCodeId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"}];getCalls=0;
  async resolveScopes(){return this.scopes;}async list(){return[workforce];}async get(){this.getCalls++;return workforce;}async completeChecklistItem(){return workforce;}
  async getSection(input:Parameters<WorkforceRepository<object>["getSection"]>[0]){return{section:input.section,items:[{id:"section-1",kind:input.section,title:"Result"}]};}
  async mutateProfile(){return{id:"99999999-9999-4999-8999-999999999999",rowVersion:1,archived:false};}
  async offboard(){return{caseId:"77777777-7777-4777-8777-777777777777",replayed:false,workforce};}
  async completeOffboardingResource(){return{caseId:"77777777-7777-4777-8777-777777777777",completed:true};}
  async requestIamProjection(){return{projectionId:"88888888-8888-4888-8888-888888888888",replayed:false};}
  async readPersonEvidence(input:Parameters<WorkforceRepository<object>["readPersonEvidence"]>[0]):Promise<PersonEvidenceView>{return{personId:input.personId,purpose:input.purpose,expiresAt:input.expiresAt,fields:{dateOfBirth:"tokenized"},redactedFields:["protectedAttributes"]};}
}
class RequestRepository implements WorkforceRequestRepository<object>{requests:WorkforceRequest[]=[];async findByIdempotencyKey(_tenantId:string,key:string){return this.requests.find(value=>value.idempotencyKey===key)??null;}async create(input:Parameters<WorkforceRequestRepository<object>["create"]>[0]){const request={id:"99999999-9999-4999-8999-999999999999",tenantId:input.tenantId,requestNo:input.requestNo,kind:input.command.kind,sourceKind:input.command.sourceKind,legalEntityId:input.command.legalEntityId,...(input.command.companyCodeId?{companyCodeId:input.command.companyCodeId}:{}),...(input.command.orgUnitId?{orgUnitId:input.command.orgUnitId}:{}),...(input.command.positionId?{positionId:input.command.positionId}:{}),...(input.command.protectedProfileContentItemId?{protectedProfileContentItemId:input.command.protectedProfileContentItemId}:{}),schema:input.command.schema!,requestedChanges:input.command.requestedChanges,idempotencyKey:input.command.idempotencyKey,status:"draft",rowVersion:1,createdAt:"2026-08-29T00:00:00.000Z",createdBy:input.createdBy} as WorkforceRequest;this.requests.push(request);return request;}async get(_tenantId:string,id:string){return this.requests.find(value=>value.id===id)??null;}async list(){return this.requests;}async recordValidation(){return null;}async submit(){return null;}async decide(){return null;}async apply(){return null;}}
function fixture(isAllowed:((resource:Readonly<Record<string,unknown>>)=>boolean)=()=>true,protectedValues?:{reveal(input:{readonly token:string;readonly purpose:string;readonly tenantId:string}):Promise<string>}){const repository=new Repository(),requestRepository=new RequestRepository(),permissions:string[]=[],resources:Readonly<Record<string,unknown>>[]=[],effects:string[]=[];const service=createWorkforceService({repository,requestRepository,requestValidator:{async validate(){return{evaluationId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",evaluatedAt:"2026-08-29T00:00:00.000Z",ruleset:{code:"workforce.validation",version:1,hash:"a".repeat(64)},valid:true,findings:[{ruleCode:"workforce.scope",severity:"error",fieldPath:"$",outcome:"passed",messageCode:"WORKFORCE_VALID",evidenceReference:{}}]};}},requestWorkflows:{async resolve(){return{code:"WorkforceReview",version:1,hash:"b".repeat(64),stageCode:"people_review",stageName:"People review",approverPrincipalIds:["44444444-4444-4444-8444-444444444444"]};}},authorizer:{async authorize(input){permissions.push(input.permissionCode);resources.push(input.resource);return{allowed:isAllowed(input.resource)};}},transactions:{async run(_plane,_actor,work){return work({});}},audit:{async record(input){effects.push(input.eventCode);return{} as never;}},outbox:{async append(input){effects.push(input.eventType);}},...(protectedValues?{protectedValues}:{}),now:()=>new Date("2026-08-29T00:00:00.000Z"),createRequestNo:()=>"WFR-TEST001"});return{service,repository,permissions,resources,effects,requests:requestRepository.requests};}

describe("workforce lifecycle service",()=>{
  it("requires every employment scope and records a profile mutation without field values",async()=>{const value=fixture();const result=await value.service.mutateProfile({context,employeeId:workforce.employeeId,kind:"education",data:{institutionName:"Demo University",qualificationName:"BSc",completionYear:2010}});expect(result.rowVersion).toBe(1);expect(value.permissions).toEqual(["neon.workforce.profile.write"]);expect(value.effects).toEqual(["workforce.profile.created","workforce.profile.created"]);});
  it("fails closed when one represented employment company denies profile editing",async()=>{const value=fixture(resource=>resource.companyCodeId!=="cccccccc-cccc-4ccc-8ccc-cccccccccccc");value.repository.scopes.push({legalEntityId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",companyCodeId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc"});await expect(value.service.mutateProfile({context,employeeId:workforce.employeeId,kind:"education",data:{institutionName:"Demo University",qualificationName:"BSc"}})).rejects.toMatchObject({status:403});expect(value.effects).toEqual([]);});
  it("rejects unsupported or malformed profile fields before authorization",async()=>{const value=fixture();await expect(value.service.mutateProfile({context,employeeId:workforce.employeeId,kind:"education",data:{institutionName:"Demo",qualificationName:"BSc",healthNotes:"private"}})).rejects.toMatchObject({status:400});expect(value.permissions).toEqual([]);});
  it("uses the People-owned request boundary for HR imports",async()=>{const value=fixture();const result=await value.service.ingest({context,source:"import",systemCode:"approved_hris",records:[{externalId:"worker-1",idempotencyKey:"hris-worker-1",protectedProfileContentItemId:"dddddddd-dddd-4ddd-8ddd-dddddddddddd",legalEntityId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",companyCodeId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",orgUnitId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc",payload:{employeeNumber:"E001",hireDate:"2026-09-01"}}]});expect(result).toEqual([{externalId:"worker-1",requestId:"99999999-9999-4999-8999-999999999999",replayed:false}]);expect(value.requests[0]).toMatchObject({kind:"onboard_person",sourceKind:"import",protectedProfileContentItemId:"dddddddd-dddd-4ddd-8ddd-dddddddddddd",requestedChanges:{sourceSystemCode:"approved_hris",sourceExternalId:"worker-1"}});});
  it("rejects restricted identity fields before persistence",async()=>{const value=fixture();await expect(value.service.createRequest({context,idempotencyKey:"manual-worker-1",kind:"onboard_person",sourceKind:"manual",protectedProfileContentItemId:"dddddddd-dddd-4ddd-8ddd-dddddddddddd",legalEntityId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",companyCodeId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",orgUnitId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc",requestedChanges:{firstName:"Ada"}})).rejects.toMatchObject({status:400,code:"WORKFORCE_INVALID"});expect(value.requests).toEqual([]);});
  it("binds restricted evidence to purpose, fields, expiry, and audit",async()=>{const value=fixture();const result=await value.service.readPersonEvidence({context,personId:workforce.personId,purpose:"employment",fields:["dateOfBirth","protectedAttributes"]});expect(result).toMatchObject({purpose:"employment",fields:{dateOfBirth:"tokenized"},redactedFields:["protectedAttributes"],expiresAt:"2026-08-29T00:15:00.000Z"});expect(value.permissions).toEqual(["neon.workforce.pii.read"]);expect(value.effects).toEqual(["workforce.person_evidence.accessed"]);});
  it("requires step-up before authorization, persistence, or audit",async()=>{const value=fixture();await expect(value.service.readPersonEvidence({context:{...context,assurance:"baseline"},personId:workforce.personId,purpose:"employment",fields:["dateOfBirth"]})).rejects.toMatchObject({status:403,code:"WORKFORCE_STEP_UP_REQUIRED"});expect(value.permissions).toEqual([]);expect(value.effects).toEqual([]);});
  it("uses a separate health permission for health-profile reveal",async()=>{const value=fixture();value.repository.readPersonEvidence=async input=>({personId:input.personId,purpose:input.purpose,expiresAt:input.expiresAt,fields:{healthProfile:{bloodGroupCode:"O+"}},redactedFields:[]});const result=await value.service.readPersonEvidence({context,personId:workforce.personId,purpose:"health",fields:["healthProfile"]});expect(result.fields).toEqual({healthProfile:{bloodGroupCode:"O+"}});expect(value.permissions).toEqual(["neon.workforce.health.read"]);expect(value.effects).toEqual(["workforce.person_evidence.accessed"]);});
  it("resolves nested identity and emergency-contact tokens only during reveal",async()=>{const calls:string[]=[];const value=fixture(()=>true,{async reveal(input){calls.push(`${input.purpose}:${input.token}`);return `revealed:${input.token}`;}});value.repository.readPersonEvidence=async input=>({personId:input.personId,purpose:input.purpose,expiresAt:input.expiresAt,fields:{identityDocuments:[{documentType:"passport",valueToken:"token:passport"}],emergencyContacts:[{nameToken:"token:name"}]},redactedFields:[]});const result=await value.service.readPersonEvidence({context,personId:workforce.personId,purpose:"compliance",fields:["identityDocuments","emergencyContacts"]});expect(result.fields).toEqual({identityDocuments:[{documentType:"passport",valueToken:"revealed:token:passport"}],emergencyContacts:[{nameToken:"revealed:token:name"}]});expect(calls).toEqual(["workforce.compliance.valueToken:token:passport","workforce.compliance.nameToken:token:name"]);});
  it("publishes only an IAM saga intent and leaves the workforce aggregate untouched",async()=>{const value=fixture();const result=await value.service.retryIam({context,employeeId:workforce.employeeId,employerOrganizationId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",createPrincipal:true,idempotencyKey:"iam-worker-001"});expect(result).toMatchObject({replayed:false});expect(value.effects).toEqual(["workforce.iam.projection_requested","workforce.iam.projection_requested"]);expect(await value.service.get({context,employeeId:workforce.employeeId})).toEqual(workforce);});
  it("authorizes employee detail with the stored employment scope",async()=>{const value=fixture();await value.service.get({context,employeeId:workforce.employeeId});expect(value.resources.at(-1)).toEqual({employeeId:workforce.employeeId,legalEntityId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",companyCodeId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"});});
  it("does not fetch detail when any employment company scope is denied",async()=>{const value=fixture(resource=>resource["companyCodeId"]!=="cccccccc-cccc-4ccc-8ccc-cccccccccccc");value.repository.scopes.push({legalEntityId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",companyCodeId:"cccccccc-cccc-4ccc-8ccc-cccccccccccc"});await expect(value.service.get({context,employeeId:workforce.employeeId})).rejects.toMatchObject({status:403,code:"FORBIDDEN"});expect(value.repository.getCalls).toBe(0);});
  it("rejects an unknown directory lifecycle before repository access",async()=>{const value=fixture();await expect(value.service.list({context,companyCodeId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",status:"invented"})).rejects.toMatchObject({status:400,code:"WORKFORCE_INVALID"});expect(value.permissions).toEqual([]);});
  it("paginates sections only after every stored employment scope is authorized",async()=>{const value=fixture();const page=await value.service.getSection({context,employeeId:workforce.employeeId,section:"team",limit:1});expect(page).toMatchObject({section:"team",items:[{title:"Result"}]});expect(value.resources).toEqual([{employeeId:workforce.employeeId,legalEntityId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",companyCodeId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"}]);});
  it("requires the section-specific permission before querying restricted resources",async()=>{const value=fixture(resource=>resource["section"]!=="audit");await expect(value.service.getSection({context,employeeId:workforce.employeeId,section:"audit"})).rejects.toMatchObject({status:403,code:"FORBIDDEN"});expect(value.permissions).toEqual(["neon.workforce.read","neon.workforce.review"]);});
  it("does not query a section when an employment scope is denied",async()=>{const value=fixture(resource=>resource["companyCodeId"]!=="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb");await expect(value.service.getSection({context,employeeId:workforce.employeeId,section:"documents"})).rejects.toMatchObject({status:403,code:"FORBIDDEN"});});
});
