"use client";
import { useEntityNavigate } from "./entity-navigation";

import type { EntityListDescriptorV1, EntityListResultV1, EntityListRowV1, EntityListScopeCoordinateV1, ListLocationStateV1, RecordExportFormat, RecordImportFormat } from "@athyper/contract-platform-entity-list";
import { beginRecordImportOperation, commitRecordImportOperation, completeRecordImportFileOperation,downloadRecordImportWorkbookTemplateOperation,prepareRecordImportFileOperation, previewRecordImportOperation, requestRecordExportOperation, validateRecordImportOperation, type HttpClient, type RecordImportPreviewReceipt } from "@athyper/platform-api-client";
import { DownloadIcon } from "@athyper/platform-icons";
import { Button, Checkbox, ChoiceSelect, Dialog, DialogClose, DialogContent, Input, Label } from "@athyper/platform-ui";
import React, { useState, type ChangeEvent } from "react";
import { useEntityI18n } from "@athyper/platform-i18n/entity-react";
import { localizedEntityError } from "@athyper/platform-i18n/entity-errors";

export type DataOperationLaunch = "picker" | "selected" | "filtered" | "page" | "all";
type Scope = Exclude<DataOperationLaunch, "picker">;
type ImportStep = "prepare" | "upload" | "map" | "validate" | "review" | "import" | "results";
type ImportOperation = "create" | "update" | "upsert" | "delete" | "replace";
const importSteps: readonly ImportStep[] = ["prepare", "upload", "map", "validate", "review", "import", "results"];


export interface DataOperationsControlProps { readonly client: HttpClient; readonly descriptor: EntityListDescriptorV1; readonly state: ListLocationStateV1; readonly page?: EntityListResultV1; readonly selectedRows: readonly EntityListRowV1[]; readonly scopeCoordinate?: EntityListScopeCoordinateV1; readonly activeViewName?: string; readonly onStatus: (status: string) => void; readonly open: boolean; readonly launch: DataOperationLaunch; readonly onOpenChange: (open: boolean) => void; }

export function DataOperationsControl(props: DataOperationsControlProps) {
  const navigate = useEntityNavigate();
  const intl = useEntityI18n();
  const policy = props.descriptor.dataOperations;
  const transferActivityHref = policy?.workspaceHref;
  const [requestedExportScope, setRequestedExportScope] = useState<Scope>();
  if (!policy || !hasVisibleOperation(policy)) return null;
  const total = props.page?.pagination.total, pageCount = props.page?.rows.length ?? 0, selectedCount = props.selectedRows.length;
  const directExportScope = props.launch === "picker" ? undefined : props.launch;
  const exportScope = directExportScope ?? requestedExportScope;
  const pickerOpen = props.open && !exportScope;
  const close = () => { setRequestedExportScope(undefined); props.onOpenChange(false); };
  return <>
    <Dialog open={pickerOpen} onOpenChange={(open) => { if (!open) close(); }}><DialogContent title={intl.message("transfer.dataOperations")} description={intl.message("transfer.dataOperationsDescription")} size="wide" className="a-entity-list__data-dialog"><div className="a-entity-list__dialog-body a-entity-list__data-options">
      <section><h3>{intl.message("transfer.exportRecords")}</h3><OperationButton label={intl.message("transfer.scope.selected")} count={selectedCount} operation={policy.export.selected} disabled={!selectedCount} onClick={() => setRequestedExportScope("selected")}/><OperationButton label={intl.message("transfer.scope.filteredShort")} count={total} operation={policy.export.filtered} onClick={() => setRequestedExportScope("filtered")}/><OperationButton label={intl.message("transfer.scope.page")} count={pageCount} operation={policy.export.currentPage} disabled={!pageCount} onClick={() => setRequestedExportScope("page")}/>{policy.export.all.state !== "hidden" ? <OperationButton label={intl.message("transfer.scope.all")} operation={policy.export.all} onClick={() => setRequestedExportScope("all")}/> : null}</section>
      {hasVisibleImport(policy) ? <section><h3>{intl.message("transfer.importRecords")}</h3>{transferActivityHref ? <OperationButton label={intl.message("transfer.importFromFile")} operation={effectiveImportLaunch(policy)} onClick={() => navigate(guidedImportHref(transferActivityHref, props.descriptor.entity.code, props.scopeCoordinate))}/> : null}<OperationButton label={intl.message("transfer.downloadImportTemplate")} operation={policy.import.downloadTemplate} onClick={() => void downloadTemplate(props.client,props.descriptor, policy.import.defaultFormat).catch(cause=>props.onStatus(cause instanceof Error?cause.message:intl.message("transfer.templateFailed")))}/></section> : null}
      {transferActivityHref ? <section><h3>{intl.message("transfer.recentJobs")}</h3><Button variant="secondary" size="small" onClick={() => navigate(transferActivityHref)}>{intl.message("transfer.viewTransfers")}</Button></section> : null}
    </div><div className="a-entity-list__dialog-actions"><DialogClose className="a-button a-button--secondary a-button--small">{intl.message("transfer.close")}</DialogClose></div></DialogContent></Dialog>
    <ExportDialog {...props} open={props.open && Boolean(exportScope)} onOpenChange={(open) => { if (!open) close(); }} initialScope={exportScope ?? "filtered"}/>
  </>;
}

function OperationButton({ label, count, operation, disabled, onClick }: { readonly label: string; readonly count?: number; readonly operation: { readonly state: string; readonly disabledReason?: { readonly message: string } }; readonly disabled?: boolean; readonly onClick: () => void }) {
  if (operation.state === "hidden") return null;
  return <Button variant="secondary" size="small" disabled={disabled || operation.state !== "enabled"} title={operation.disabledReason?.message} onClick={onClick}><DownloadIcon size={16}/><span>{label}</span>{count !== undefined ? <small>{new Intl.NumberFormat().format(count)}</small> : null}</Button>;
}

function ExportDialog(props: DataOperationsControlProps & { readonly initialScope: Scope }) {
  const intl = useEntityI18n();
  const policy = props.descriptor.dataOperations!.export;
  const [scope, setScope] = useState<Scope>(props.initialScope), [format, setFormat] = useState<RecordExportFormat>(policy.defaultFormat), [fields, setFields] = useState<readonly string[]>(props.state.columns.filter((key) => policy.exportableFields.includes(key)));
  const [fieldMode, setFieldMode] = useState<"visible" | "all" | "custom">("visible"), [headings, setHeadings] = useState(true), [rawCodes, setRawCodes] = useState(false), [isoDates, setIsoDates] = useState(true), [informationSheet, setInformationSheet] = useState(true), [fileName, setFileName] = useState(safeFileName(props.descriptor.surface.title)), [busy, setBusy] = useState(false), [error, setError] = useState("");
  React.useEffect(() => { if (props.open) setScope(props.initialScope); }, [props.open, props.initialScope]);
  const selectedFields = fieldMode === "visible" ? props.state.columns.filter((key) => policy.exportableFields.includes(key)) : fieldMode === "all" ? policy.exportableFields : fields;
  const count = scope === "selected" ? props.selectedRows.length : scope === "page" ? props.page?.rows.length ?? 0 : props.page?.pagination.total;
  const start = async () => {
    setError(""); if (!selectedFields.length) { setError(intl.message("transfer.chooseField")); return; }
    if ((scope === "selected" && !props.selectedRows.length) ||
      (scope === "page" && !props.page?.rows.length)) {
      setError(intl.message(scope === "selected" ? "transfer.selectRecord" : "transfer.emptyPage"));
      return;
    }
    setBusy(true);
    try {
      const requestId = crypto.randomUUID();
      const scopedRows=scope==="selected"?props.selectedRows:scope==="page"?props.page?.rows??[]:[];
      const filter = { filters: scope === "filtered" ? props.state.filters : [], sort: props.state.sort, ...(scope === "filtered" && props.state.query ? { search: props.state.query } : {}), ...(scope === "filtered" && props.state.standardViewKey ? { standardViewKey: props.state.standardViewKey } : {}), ...(scopedRows.length ? { recordIds: scopedRows.map(row=>row.id) } : {}), ...(props.scopeCoordinate ? { scopeCoordinate: props.scopeCoordinate } : {}), _transfer: { scope, format, fields: selectedFields, headings, rawCodes, isoDates, informationSheet:format!=="csv"&&informationSheet, fileName, activeViewName:props.activeViewName, descriptorHash: props.descriptor.revision.descriptorHash, scopeFingerprint: props.descriptor.scope.fingerprint, queryHash: props.page?.queryHash } };
      const receipt = await props.client.request(requestRecordExportOperation, { params: { entityCode: props.descriptor.entity.code }, body: { requestId, filter }, idempotencyKey: `export:${requestId}` });
      props.onStatus(intl.message("transfer.exportQueued", {jobId: receipt.jobId}));
      props.onOpenChange(false);
    } catch (cause) { setError(localizedEntityError(cause, intl)); } finally { setBusy(false); }
  };
  return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent title={intl.message("transfer.exportTitle", { list: props.descriptor.surface.title })} description={intl.message("transfer.exportDescription")} size="full" className="a-entity-list__transfer-dialog">
    <div className="a-entity-list__dialog-body a-entity-list__export-grid">
      <fieldset><legend>{intl.message("transfer.step.scope")}</legend>{scopeChoices(policy, props, intl).map((choice) => <Label key={choice.value} className="a-entity-list__radio"><input type="radio" name="export-scope" value={choice.value} checked={scope === choice.value} disabled={choice.disabled} onChange={() => setScope(choice.value)}/><span>{choice.label}</span><small>{choice.count === undefined ? "" : new Intl.NumberFormat().format(choice.count)}</small></Label>)}</fieldset>
      <fieldset><legend>{intl.message("transfer.step.fields")}</legend><Label className="a-entity-list__radio"><input type="radio" checked={fieldMode === "visible"} onChange={() => setFieldMode("visible")}/><span>{intl.message("transfer.fields.visible")}</span></Label><Label className="a-entity-list__radio"><input type="radio" checked={fieldMode === "all"} onChange={() => setFieldMode("all")}/><span>{intl.message("transfer.fields.all")}</span></Label><Label className="a-entity-list__radio"><input type="radio" checked={fieldMode === "custom"} onChange={() => setFieldMode("custom")}/><span>{intl.message("transfer.fields.custom")}</span></Label>{fieldMode === "custom" ? <div className="a-entity-list__field-picker">{props.descriptor.fields.filter((field) => policy.exportableFields.includes(field.key)).map((field) => <Label key={field.key}><Checkbox checked={fields.includes(field.key)} onChange={(event) => setFields(event.currentTarget.checked ? [...fields, field.key] : fields.filter((key) => key !== field.key))}/>{field.label}</Label>)}</div> : null}</fieldset>
      <fieldset><legend>{intl.message("transfer.step.format")}</legend><ChoiceSelect label={intl.message("transfer.exportFormat")} value={format} onChange={setFormat} options={policy.formats.map((value) => ({ value, label: formatLabel(value) }))}/></fieldset>
      <fieldset><legend>{intl.message("transfer.step.options")}</legend><Label>{intl.message("transfer.fileName")}<Input value={fileName} maxLength={120} onChange={(event) => setFileName(safeFileName(event.currentTarget.value))}/></Label><Label><Checkbox checked={headings} disabled={format==="json"||format==="ndjson"} onChange={(event) => setHeadings(event.currentTarget.checked)}/> {intl.message("transfer.option.headings")}</Label><Label><Checkbox checked={rawCodes} onChange={(event) => setRawCodes(event.currentTarget.checked)}/> {intl.message("transfer.option.rawCodes")}</Label><Label><Checkbox checked={isoDates} onChange={(event) => setIsoDates(event.currentTarget.checked)}/> {intl.message("transfer.option.isoDates")}</Label><Label><Checkbox checked={informationSheet} disabled={format==="csv"} onChange={(event) => setInformationSheet(event.currentTarget.checked)}/> {intl.message("transfer.option.information")}{format==="csv"?<small>{intl.message("transfer.option.informationFormats")}</small>:null}</Label></fieldset>
      <div className="a-entity-list__transfer-summary"><strong>{intl.message("transfer.readyToExport")}</strong><span>{count === undefined ? intl.message("transfer.summary.scopeName", { scope: intl.message(`transfer.scopeName.${scope}`) }) : intl.message("transfer.summary.scope", { count })}</span><span>{intl.message("transfer.summary.format", { format: formatLabel(format) })}</span><span>{intl.message("transfer.summary.fields", { count: selectedFields.length })}</span>{props.activeViewName ? <span>{intl.message("transfer.summary.view", { view: props.activeViewName })}</span> : null}{props.descriptor.scope.labels.map((label) => <span key={label.key}>{intl.message("list.text.labelled", { label: label.label, value: label.value })}</span>)}</div>
      {error ? <p role="alert" className="a-entity-list__transfer-error">{error}</p> : null}
    </div><div className="a-entity-list__dialog-actions"><DialogClose className="a-button a-button--secondary a-button--small">{intl.message("transfer.cancel")}</DialogClose><Button size="small" loading={busy} onClick={start}>{intl.message("transfer.startExport")}</Button></div>
  </DialogContent></Dialog>;
}

function scopeChoices(policy: EntityListDescriptorV1["dataOperations"] extends infer _ ? NonNullable<EntityListDescriptorV1["dataOperations"]>["export"] : never, props: Parameters<typeof DataOperationsControl>[0], intl: ReturnType<typeof useEntityI18n>) {
  const values: readonly { value: Scope; label: string; count?: number; state: string }[] = [{ value: "selected", label: intl.message("transfer.scope.selected"), count: props.selectedRows.length, state: policy.selected.state }, { value: "filtered", label: intl.message("transfer.scope.filtered"), count: props.page?.pagination.total, state: policy.filtered.state }, { value: "page", label: intl.message("transfer.scope.page"), count: props.page?.rows.length ?? 0, state: policy.currentPage.state }, { value: "all", label: intl.message("transfer.scope.all"), state: policy.all.state }];
  return values.filter((item) => item.state !== "hidden").map((item) => ({ ...item, disabled: item.state !== "enabled" || ((item.value === "selected" || item.value === "page") && !item.count) }));
}

export function ImportWizard({ client, descriptor, scopeCoordinate, open, onOpenChange, onStatus }: { readonly client: HttpClient; readonly descriptor: EntityListDescriptorV1; readonly scopeCoordinate?: EntityListScopeCoordinateV1; readonly open: boolean; readonly onOpenChange: (value: boolean) => void; readonly onStatus: (value: string) => void }) {
  const navigate = useEntityNavigate();
  const intl = useEntityI18n();
  const policy = descriptor.dataOperations!.import;
  const operationPolicy=(value:ImportOperation)=>policy[value]??{state:"hidden"as const,requiresPreflight:false,requiresApproval:false};
  const operations = (["create", "update", "upsert","delete","replace"] as const).filter((value) => operationPolicy(value).state !== "hidden"), initialOperation = operations.find((value) => operationPolicy(value).state === "enabled") ?? "create";
  const [step, setStep] = useState<ImportStep>("prepare"), [operation, setOperation] = useState<ImportOperation>(initialOperation), [format, setFormat] = useState<RecordImportFormat>(policy.defaultFormat), [file, setFile] = useState<File>(), [preview, setPreview] = useState<RecordImportPreviewReceipt>(), [sessionId, setSessionId] = useState<string>(), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const selectFile = (next?:File) => { if (!next) return; setError(""); if (next.size > policy.maxFileBytes) { setError(intl.message("transfer.fileTooLarge", { limit: formatBytes(policy.maxFileBytes) })); return; } const expected=accept(format).split(",")[0]!.slice(1);if(next.name.split(".").pop()?.toLowerCase()!==expected){setError(intl.message("transfer.fileWrongType", { extension: expected }));return;}setFile(next);setStep("map"); };
  const chooseFile = (event: ChangeEvent<HTMLInputElement>) => selectFile(event.currentTarget.files?.[0]);
  const validate = async () => { setBusy(true); setError(""); try { const id = crypto.randomUUID(); if(!file)throw new Error(intl.message("transfer.chooseFile"));await client.request(beginRecordImportOperation, { params: { entityCode: descriptor.entity.code }, body: { sessionId: id, operation, ...(scopeCoordinate ? { scopeCoordinate } : {}), conflictPolicy: "reject", atomicity: "all_or_nothing" }, idempotencyKey: `import:${id}:begin` });const reservation=await client.request(prepareRecordImportFileOperation,{params:{sessionId:id},body:{fileName:file.name,sizeBytes:file.size}}),uploaded=await fetch(reservation.uploadUrl,{method:"PUT",headers:{"content-type":file.type||importContentType(format)},body:file});if(!uploaded.ok)throw new Error(intl.message("transfer.uploadFailed", { status: uploaded.status }));await client.request(completeRecordImportFileOperation,{params:{sessionId:id},body:{fileName:file.name,sizeBytes:file.size},idempotencyKey:`import:${id}:file-complete`});const result = await client.request(validateRecordImportOperation, { params: { sessionId: id }, idempotencyKey: `import:${id}:validate` }); setSessionId(id); setPreview(result); setStep("validate"); } catch (cause) { setError(cause instanceof Error ? cause.message : intl.message("transfer.validationFailed")); } finally { setBusy(false); } };
  const review = async () => { if (!sessionId) return; setBusy(true); try { setPreview(await client.request(previewRecordImportOperation, { params: { sessionId }, idempotencyKey: `import:${sessionId}:preview` })); setStep("review"); } catch (cause) { setError(cause instanceof Error ? cause.message : intl.message("transfer.previewFailed")); } finally { setBusy(false); } };
  const commit = async () => { if (!sessionId) return; setBusy(true); try { const result = await client.request(commitRecordImportOperation, { params: { sessionId }, idempotencyKey: `import:${sessionId}:commit` }); setStep("results"); onStatus(intl.message("transfer.importQueuedStatus", { jobId: result.jobId })); } catch (cause) { setError(cause instanceof Error ? cause.message : intl.message("transfer.importNotStarted")); } finally { setBusy(false); } };
  const reset = () => { setStep("prepare"); setOperation(initialOperation); setFile(undefined); setPreview(undefined); setSessionId(undefined); setError(""); };
  return <Dialog open={open} onOpenChange={(value) => { onOpenChange(value); if (!value) reset(); }}><DialogContent title={intl.message("transfer.importListTitle", { list: descriptor.surface.title })} description={intl.message("transfer.importListDescription")} size="full" className="a-entity-list__transfer-dialog"><ol className="a-entity-list__wizard-steps">{importSteps.map((value, index) => <li key={value} aria-current={step === value ? "step" : undefined} data-complete={importSteps.indexOf(step) > index || undefined}>{intl.message("transfer.wizardStep", { number: index + 1, step: intl.message(`transfer.importStep.${value}`) })}</li>)}</ol><div className="a-entity-list__dialog-body">
    {step === "prepare" ? <><Label>{intl.message("transfer.operation")}<ChoiceSelect value={operation} onChange={setOperation} options={operations.map((value) => ({ value, label: operationPolicy(value).state === "disabled" ? intl.message("transfer.operationUnavailable", { operation: intl.message(`transfer.importOperation.${value}`), reason: operationPolicy(value).disabledReason?.message ?? intl.message("transfer.unavailable") }) : intl.message(`transfer.importOperation.${value}`), disabled: operationPolicy(value).state !== "enabled" }))}/></Label><Label>{intl.message("transfer.templateFormat")}<ChoiceSelect value={format} onChange={setFormat} options={policy.formats.map((value) => ({ value, label: formatLabel(value) }))}/></Label><p>{intl.message(policy.draftOnly ? "transfer.importLimitsDrafts" : "transfer.importLimits", { fields: policy.importableFields.length, rows: policy.maxRows })}</p><Button variant="secondary" size="small" onClick={() => void downloadTemplate(client,descriptor, format).catch(cause=>setError(cause instanceof Error?cause.message:intl.message("transfer.templateFailed")))}>{intl.message("transfer.downloadTemplate")}</Button><Button size="small" disabled={operationPolicy(operation).state !== "enabled"} title={operationPolicy(operation).disabledReason?.message} onClick={() => setStep("upload")}>{intl.message("transfer.continueToUpload")}</Button></> : null}
    {step === "upload" ? <Label className="a-entity-list__dropzone" onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="copy";}} onDrop={event=>{event.preventDefault();selectFile(event.dataTransfer.files?.[0]);}}>{intl.message("transfer.chooseOrDrop", { format: format.toUpperCase() })}<Input type="file" accept={accept(format)} onChange={chooseFile}/><small>{intl.message("transfer.maximumUntrusted", { limit: formatBytes(policy.maxFileBytes) })}</small></Label> : null}
    {step === "map" ? <><p>{intl.message("transfer.inspectedOnServer", { file: file?.name ?? "" })}</p><div className="a-entity-list__transfer-summary"><strong>{intl.message("transfer.governedIntake")}</strong><span>{intl.message(format==="xlsx" ? "transfer.keysWorksheet" : "transfer.keysHeaders")}</span><span>{intl.message("transfer.intakeChecks")}</span>{policy.draftOnly?<span>{intl.message("transfer.draftInput")}</span>:null}</div><Button size="small" loading={busy} disabled={!file} onClick={validate}>{intl.message("transfer.uploadAndValidate", { format: formatLabel(format) })}</Button></> : null}
    {step === "validate" ? <ValidationSummary preview={preview}/>: null}
    {step === "review" ? <><ValidationSummary preview={preview}/><div className="a-entity-list__transfer-summary"><strong>{intl.message("transfer.dryRun")}</strong><span>{intl.message(operation === "create" ? "transfer.dryRun.creates" : operation === "update" ? "transfer.dryRun.updates" : "transfer.dryRun.upserts", { count: preview?.validCount ?? 0 })}</span><span>{intl.message("transfer.dryRun.skipped", { count: 0 })}</span><span>{intl.message("transfer.dryRun.errors", { count: preview?.invalidCount ?? 0 })}</span></div></> : null}
    {step === "results" ? <div className="a-entity-list__transfer-summary"><strong>{intl.message("transfer.importQueued")}</strong><span>{intl.message("transfer.importQueuedDetail")}</span>{descriptor.dataOperations?.workspaceHref ? <Button variant="secondary" size="small" onClick={() => navigate(descriptor.dataOperations!.workspaceHref!)}>{intl.message("transfer.viewTransfers")}</Button> : null}</div> : null}
    {error ? <p role="alert" className="a-entity-list__transfer-error">{error}</p> : null}
  </div><div className="a-entity-list__dialog-actions"><DialogClose className="a-button a-button--secondary a-button--small">{intl.message(step === "results" ? "transfer.close" : "transfer.cancel")}</DialogClose>{step === "validate" ? <Button size="small" loading={busy} disabled={Boolean(preview?.invalidCount)} onClick={review}>{intl.message("transfer.reviewImport")}</Button> : null}{step === "review" ? <Button size="small" loading={busy} disabled={Boolean(preview?.invalidCount)} onClick={commit}>{intl.message("transfer.startImport")}</Button> : null}</div></DialogContent></Dialog>;
}

function ValidationSummary({ preview }: { readonly preview?: RecordImportPreviewReceipt }) { const intl = useEntityI18n(); return <div className="a-entity-list__validation-summary"><strong>{intl.message("transfer.rowsChecked", { count: (preview?.validCount ?? 0) + (preview?.invalidCount ?? 0) })}</strong><span className="a-entity-list__valid">{intl.message("transfer.rowsValid", { count: preview?.validCount ?? 0 })}</span><span className="a-entity-list__invalid">{intl.message("transfer.rowsInvalid", { count: preview?.invalidCount ?? 0 })}</span>{preview?.rows.filter((row) => !row.valid).slice(0, 10).map((row) => <small key={row.rowNumber}>{intl.message("transfer.rowErrors", { row: row.rowNumber, errors: row.errors.join("; ") })}</small>)}</div>; }

function hasVisibleOperation(policy: NonNullable<EntityListDescriptorV1["dataOperations"]>) { return [policy.export.currentPage, policy.export.selected, policy.export.filtered, policy.export.all].some((item) => item.state !== "hidden") || hasVisibleImport(policy); }
export function hasVisibleDataOperations(descriptor: EntityListDescriptorV1): boolean { return Boolean(descriptor.dataOperations && hasVisibleOperation(descriptor.dataOperations)); }
function hasVisibleImport(policy: NonNullable<EntityListDescriptorV1["dataOperations"]>) { return [policy.import.create, policy.import.update, policy.import.upsert,policy.import.delete,policy.import.replace, policy.import.downloadTemplate].some((item) => item&&item.state !== "hidden"); }
function hasEnabledImport(policy: NonNullable<EntityListDescriptorV1["dataOperations"]>) { return [policy.import.create, policy.import.update, policy.import.upsert,policy.import.delete,policy.import.replace].some((item) => item?.state === "enabled"); }
function effectiveImportLaunch(policy:NonNullable<EntityListDescriptorV1["dataOperations"]>){if(hasEnabledImport(policy))return{state:"enabled"};const operation=[policy.import.create,policy.import.update,policy.import.upsert,policy.import.delete,policy.import.replace].find(item=>item?.state==="disabled");return{state:"disabled",...(operation?.disabledReason?{disabledReason:operation.disabledReason}:{})};}
function formatLabel(format: RecordExportFormat | RecordImportFormat) { return ({ xlsx: "Excel (.xlsx)", csv: "CSV (.csv)", json: "JSON (.json)", ndjson: "NDJSON (.ndjson)" })[format]; }
function safeFileName(value: string) { return value.replace(/[\\/:*?"<>|\u0000-\u001f]+/g, "-").trim().slice(0, 120) || "records"; }
function formatBytes(value: number) { return value >= 1024 * 1024 ? `${Math.floor(value / 1024 / 1024)} MB` : `${Math.floor(value / 1024)} KB`; }
function accept(format: RecordImportFormat) { return format === "csv" ? ".csv,text/csv" : format === "json" ? ".json,application/json" : ".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"; }
function importContentType(format:RecordImportFormat){return format==="csv"?"text/csv":format==="json"?"application/json":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";}
function guidedImportHref(workspaceHref:string,entityCode:string,scope?:EntityListScopeCoordinateV1){const query=new URLSearchParams({entity:entityCode});if(scope?.companyCodeId)query.set("companyCodeId",scope.companyCodeId);if(scope?.legalEntityId)query.set("legalEntityId",scope.legalEntityId);if(scope?.operatingOrganizationId)query.set("operatingOrganizationId",scope.operatingOrganizationId);if(scope?.networkAccountId)query.set("networkAccountId",scope.networkAccountId);for(const key of ["parentEntityCode","parentRecordId","relationshipKey"] as const)if(scope?.[key])query.set(key,scope[key]);return `${workspaceHref}/new?${query.toString()}`;}
async function downloadTemplate(client:HttpClient,descriptor: EntityListDescriptorV1, format: RecordImportFormat) { const policy = descriptor.dataOperations!.import,fields = descriptor.fields.filter((field) => policy.importableFields.includes(field.key));if(format==="xlsx"){const result=await client.request(downloadRecordImportWorkbookTemplateOperation,{params:{entityCode:descriptor.entity.code}});window.location.assign(result.url);return;}if(policy.draftOnly){const draft={entity_id:"018f6d2a-aaaa-7aaa-8aaa-aaaaaaaaaaaa",entity_code:"example_entity",branch_code:"import",title:"Imported example contract",graph:{contractSchema:"athyper.meta-entity-contract/2.1",entity:{entityCode:"example_entity"},runtimeProfiles:[{profileKey:"default",backingKind:"virtual",apiExposure:"catalog_only",readMode:"none",writeMode:"none"}],fields:[{fieldKey:"id",dataType:"uuid",typeConfig:{kind:"uuid"}}],operations:[{operationKey:"read",operationKind:"read",label:"Read",auditEventCode:"example_entity.read",fieldKeys:["id"]}]}};downloadBlob(`${safeFileName(descriptor.entity.code)}-draft-import-template.json`,"application/json",JSON.stringify([draft],null,2));return;} if (format === "json") downloadBlob(`${safeFileName(descriptor.entity.code)}-import-template.json`, "application/json", JSON.stringify([Object.fromEntries(fields.map((field) => [field.key, example(field.valueKind)]))], null, 2)); else downloadBlob(`${safeFileName(descriptor.entity.code)}-import-template.csv`, "text/csv;charset=utf-8", `${fields.map((field) => csvCell(field.key)).join(",")}\r\n${fields.map((field) => csvCell(String(example(field.valueKind)))).join(",")}\r\n`); }
function example(kind: string): string | number | boolean { return kind === "integer" || kind === "decimal" || kind === "money" ? 0 : kind === "boolean" ? false : kind === "date" ? "2026-01-31" : kind === "datetime" ? "2026-01-31T12:00:00Z" : ""; }
function csvCell(value: string) { const safe = /^[=+@-]/.test(value.trimStart()) ? `'${value}` : value; return `"${safe.replaceAll('"', '""')}"`; }
function downloadBlob(name: string, type: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type })), link = document.createElement("a"); link.href = url; link.download = name; link.hidden = true; document.body.append(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }
