"use client";

import type { ListFieldDescriptorV1 } from "@athyper/contract-platform-entity-list";
import { CheckIcon, ChevronDownIcon, SearchIcon } from "@athyper/platform-icons";
import { Button, Input, Label } from "@athyper/platform-ui";
import React, { useEffect, useId, useRef, useState, type KeyboardEvent as ReactKeyboardEvent } from "react";
import { fieldTypeLabel, matchesColumnSearch } from "./columns";

const MAX_CATALOGUE_RESULTS = 20;

export function FieldSearchInput({ id, value, count, placeholder, autoFocus, onChange, onArrowDown }: { readonly id: string; readonly value: string; readonly count: number; readonly placeholder: string; readonly autoFocus?: boolean; readonly onChange: (value: string) => void; readonly onArrowDown?: () => void }) {
  return <div className="a-entity-list__field-search"><SearchIcon size={17}/><Label htmlFor={id} className="a-visually-hidden">{placeholder}</Label><Input id={id} type="search" value={value} onChange={(event) => onChange(event.currentTarget.value)} onKeyDown={(event) => { if (event.key === "ArrowDown" && onArrowDown) { event.preventDefault(); onArrowDown(); } }} placeholder={placeholder} autoComplete="off" autoFocus={autoFocus}/><span>{count}</span></div>;
}

export function FieldCataloguePicker({ heading, fields, placeholder, onSelect, onClose }: { readonly heading: string; readonly fields: readonly ListFieldDescriptorV1[]; readonly placeholder: string; readonly onSelect: (field: ListFieldDescriptorV1) => void; readonly onClose: () => void }) {
  const [search, setSearch] = useState(""), searchId = useId(), options = useRef<HTMLDivElement>(null), matching = fields.filter((field) => matchesColumnSearch(field, search)), shown = matching.slice(0, MAX_CATALOGUE_RESULTS);
  const focusOption = (index: number) => options.current?.querySelectorAll<HTMLButtonElement>("[data-field-option]")[index]?.focus();
  const optionKeyDown = (event: ReactKeyboardEvent<HTMLButtonElement>, index: number) => { if (!['ArrowDown', 'ArrowUp', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const target = event.key === "Home" ? 0 : event.key === "End" ? shown.length - 1 : Math.max(0, Math.min(shown.length - 1, index + (event.key === "ArrowDown" ? 1 : -1))); focusOption(target); };
  return <section className="a-entity-list__field-catalogue" aria-labelledby={`${searchId}-heading`}><div className="a-entity-list__field-catalogue-heading"><h3 id={`${searchId}-heading`}>{heading}</h3><Button variant="ghost" size="small" onClick={onClose}>Close</Button></div><FieldSearchInput id={searchId} value={search} count={matching.length} placeholder={placeholder} onChange={setSearch} onArrowDown={() => focusOption(0)}/><div ref={options} className="a-entity-list__field-options">{shown.map((field, index) => <button type="button" data-field-option key={field.key} onKeyDown={(event) => optionKeyDown(event, index)} onClick={() => onSelect(field)}><span><strong>{field.label}</strong><small>{field.key} · {fieldTypeLabel(field.valueKind)}</small></span><span aria-hidden="true">＋</span></button>)}</div>{matching.length > shown.length ? <p className="a-entity-list__field-catalogue-hint">Showing the first {shown.length} of {matching.length} fields. Refine your search to find another field.</p> : null}{!matching.length ? <div className="a-entity-list__field-catalogue-empty"><p>No matching fields.</p>{search ? <Button variant="ghost" size="small" onClick={() => setSearch("")}>Clear search</Button> : null}</div> : null}</section>;
}

export function SearchableFieldSelect({ fields, value, label, onChange }: { readonly fields: readonly ListFieldDescriptorV1[]; readonly value: string; readonly label: string; readonly onChange: (field: ListFieldDescriptorV1) => void }) {
  const root = useRef<HTMLDivElement>(null), input = useRef<HTMLInputElement>(null), [open, setOpen] = useState(false), [search, setSearch] = useState(""), listId = useId(), selected = fields.find((field) => field.key === value), matching = fields.filter((field) => matchesColumnSearch(field, search)).slice(0, MAX_CATALOGUE_RESULTS);
  useEffect(() => { if (!open) return; input.current?.focus(); const outside = (event: PointerEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("pointerdown", outside); document.addEventListener("keydown", escape); return () => { document.removeEventListener("pointerdown", outside); document.removeEventListener("keydown", escape); }; }, [open]);
  const select = (field: ListFieldDescriptorV1) => { onChange(field); setSearch(""); setOpen(false); };
  return <div ref={root} className="a-entity-list__field-select"><button type="button" className="a-entity-list__field-select-trigger" role="combobox" aria-label={label} aria-expanded={open} aria-controls={listId} onClick={() => setOpen(!open)}><span>{selected?.label ?? value}</span><ChevronDownIcon size={16}/></button>{open ? <div className="a-entity-list__field-select-popover"><div className="a-entity-list__field-select-search"><SearchIcon size={16}/><Input ref={input} type="search" value={search} onChange={(event) => setSearch(event.currentTarget.value)} placeholder="Search fields…" aria-label={`Search ${label.toLocaleLowerCase()}`}/></div><div id={listId} role="listbox" className="a-entity-list__field-select-options">{matching.map((field) => <button type="button" role="option" aria-selected={field.key === value} key={field.key} onClick={() => select(field)}><span aria-hidden="true">{field.key === value ? <CheckIcon size={15}/> : null}</span><span><strong>{field.label}</strong><small>{field.key} · {fieldTypeLabel(field.valueKind)}</small></span></button>)}</div>{!matching.length ? <p>No matching fields.</p> : null}</div> : null}</div>;
}
