"use client";

import { decodeListLocationState, encodeListLocationState, type EntityListDescriptorV1, type EntityListResultV1, type EntityListRowV1, type EntityListScopeCoordinateV1, type JsonValue, type ListFieldDescriptorV1, type ListFilterOperator, type ListFilterV1, type ListLocationStateV1, type ListSortV1 } from "@athyper/contract-platform-entity-list";
import { addRecordBookmarksOperation, ApiTransportError, entityListDescriptorOperation, entityListOperation, entityListQuery, entityListScopeQuery, recordBookmarkMembershipOperation, removeRecordBookmarksOperation, type HttpClient, type RecordBookmarkMutationV1 } from "@athyper/platform-api-client";
import { ArrowDownIcon, ArrowUpDownIcon, ArrowUpIcon, ChevronDownIcon, ColumnsIcon, DownloadIcon, FilterIcon, GripVerticalIcon, GroupIcon, LayoutIcon, LinkIcon, MoreHorizontalIcon, MoreVerticalIcon, RefreshCwIcon, ResetIcon, SearchIcon, SortIcon, StarIcon, TrashIcon } from "@athyper/platform-icons";
import { ContentHeader } from "@athyper/platform-shell";
import { Badge, Button, Card, Checkbox, Dialog, DialogClose, DialogContent, DrawerContent, Input, Label, Menu, MenuContent, MenuItem, MenuTrigger, Select, Skeleton } from "@athyper/platform-ui";
import React, { useCallback, useEffect, useRef, useState, type DragEvent as ReactDragEvent, type FormEvent, type ReactNode } from "react";
import { clearDisplayPreferences, readDisplayPreferences, readSavedViews, saveableViewState, savedViewStorageKey, writeDisplayPreferences, writeSavedViews, type DisplayPreferences, type SavedListView } from "./preferences";
import { describeFilter, filterInputValue, filterValueFromInput, nextPrimarySort, visibleListFields, withoutNavigation } from "./state";
import { DataOperationsControl, hasVisibleDataOperations, type DataOperationLaunch } from "./data-operations";
import { fieldTypeLabel, groupAvailableColumns, matchesColumnSearch, reorderColumn } from "./columns";

export function EntityListRuntime({ client, entityCode, scopeCoordinate, scopeControl }: { readonly client: HttpClient; readonly entityCode: string; readonly scopeCoordinate?: EntityListScopeCoordinateV1; readonly scopeControl?: ReactNode }) {
  const [descriptor, setDescriptor] = useState<EntityListDescriptorV1>();
  const [state, setState] = useState<ListLocationStateV1>();
  const [page, setPage] = useState<EntityListResultV1>();
  const [error, setError] = useState<ApiTransportError>();
  const [loading, setLoading] = useState(true);
  const [attempt, setAttempt] = useState(0);
  const [refreshAttempt, setRefreshAttempt] = useState(0);
  const [cursorHistory, setCursorHistory] = useState<readonly (string | undefined)[]>([]);
  const scopeKey = JSON.stringify(scopeCoordinate ?? {}), authorityKey = `${entityCode}:${scopeKey}`;
  const serverQueryKey = JSON.stringify(state ? { query: state.query ?? null, filters: state.filters, sort: state.sort, group: state.group ?? null, columns: state.columns, cursor: state.cursor ?? null, pageSize: state.pageSize ?? null } : null);
  const previousAuthorityKey = useRef<string | undefined>(undefined);
  const [loadedAuthorityKey, setLoadedAuthorityKey] = useState<string>();
  const [selectedIds, setSelectedIds] = useState<ReadonlySet<string>>(() => new Set());
  const [allMatchingSelected, setAllMatchingSelected] = useState(false);
  const [dataOperationsLaunch, setDataOperationsLaunch] = useState<DataOperationLaunch>();
  const [actionStatus, setActionStatus] = useState("");
  const [bookmarkedIds, setBookmarkedIds] = useState<ReadonlySet<string>>(() => new Set());
  const [pendingBookmarkIds, setPendingBookmarkIds] = useState<ReadonlySet<string>>(() => new Set());

  useEffect(() => {
    const controller = new AbortController(), authorityChanged = previousAuthorityKey.current !== undefined && previousAuthorityKey.current !== authorityKey;
    previousAuthorityKey.current = authorityKey;
    setLoading(true); setError(undefined); setDescriptor(undefined); setPage(undefined); setCursorHistory([]); setLoadedAuthorityKey(undefined); setSelectedIds(new Set()); setAllMatchingSelected(false); setDataOperationsLaunch(undefined); setActionStatus(""); setBookmarkedIds(new Set()); setPendingBookmarkIds(new Set());
    client.request(entityListDescriptorOperation, { params: { entityCode }, query: entityListScopeQuery(scopeCoordinate), signal: controller.signal }).then((next) => {
      if (controller.signal.aborted) return;
      let nextState = decodeListLocationState(window.location.search, next);
      const parameters = new URLSearchParams(window.location.search), preferences = readDisplayPreferences(next.plane);
      if (!parameters.has("density") && preferences?.density) nextState = { ...nextState, density: preferences.density };
      if (!parameters.has("view") && preferences?.mode && next.surface.supportedModes.includes(preferences.mode)) nextState = { ...nextState, mode: preferences.mode };
      if (authorityChanged && (nextState.cursor || nextState.pageIndex)) { nextState = withoutNavigation(nextState); writeLocation(nextState, next, "replace"); }
      setDescriptor(next); setState(nextState); setLoadedAuthorityKey(authorityKey);
    }).catch((cause) => { if (!controller.signal.aborted) setError(asTransportError(cause)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [client, entityCode, scopeKey, attempt]);

  useEffect(() => {
    if (!descriptor || !state || descriptor.scope.status !== "ready" || loadedAuthorityKey !== authorityKey) return;
    const controller = new AbortController(); setLoading(true); setError(undefined);
    client.request(entityListOperation, { params: { entityCode }, query: entityListQuery(state, descriptor, scopeCoordinate), signal: controller.signal }).then((next) => {
      if (controller.signal.aborted) return;
      if (next.descriptorHash !== descriptor.revision.descriptorHash || next.scopeFingerprint !== descriptor.scope.fingerprint) throw new TypeError("List response authority no longer matches its descriptor");
      setPage(next);
    }).catch((cause) => { if (!controller.signal.aborted) setError(asTransportError(cause)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [client, descriptor, entityCode, serverQueryKey, scopeKey, loadedAuthorityKey, attempt, refreshAttempt]);

  const pageIdentityKey = page?.rows.map((row) => row.id).join(",") ?? "";
  useEffect(() => {
    if (!page?.rows.length) { setBookmarkedIds(new Set()); return; }
    const controller = new AbortController();
    client.request(recordBookmarkMembershipOperation, { params: { entityCode }, query: { recordId: page.rows.map((row) => row.id) }, signal: controller.signal })
      .then((ids) => { if (!controller.signal.aborted) { setBookmarkedIds(ids); setPage((current) => current ? ({ ...current, rows: current.rows.map((row) => ({ ...row, decoration: { ...row.decoration, bookmarked: ids.has(row.id) } })) }) : current); } })
      .catch(() => { if (!controller.signal.aborted) setActionStatus("Favourites could not be loaded. List records remain available."); });
    return () => controller.abort();
  }, [client, entityCode, pageIdentityKey]);

  const update = useCallback((next: ListLocationStateV1, history: "replace" | "push" = "replace") => { if (descriptor) { setState(next); writeLocation(next, descriptor, history); } }, [descriptor]);
  useEffect(() => { if (!descriptor) return; const restore = () => { setCursorHistory([]); setState(decodeListLocationState(window.location.search, descriptor)); }; window.addEventListener("popstate", restore); return () => window.removeEventListener("popstate", restore); }, [descriptor]);

  if (!descriptor) return <ListFrame title="Loading list" loading={loading} error={error} retry={() => setAttempt((value) => value + 1)} />;
  if (descriptor.scope.status === "context_required") return <section className="a-entity-list" aria-labelledby="page-title"><ContentHeader eyebrow="Read-only list" title={descriptor.surface.title} description={descriptor.surface.description}/>{scopeControl}<Card className="a-entity-list__state"><Badge tone="warning">Context required</Badge><h2>Select a validated work context</h2><p>This entity is governed by a narrower authorization scope. Rows stay unavailable until the server accepts and applies an explicit work-context coordinate.</p></Card></section>;
  if (!state) return <ListFrame title={descriptor.surface.title} loading error={error} retry={() => setAttempt((value) => value + 1)} />;
  const fields = visibleListFields(descriptor, state);
  const resetAndUpdate = (patch: Partial<ListLocationStateV1>, history: "replace" | "push" = "replace") => { setCursorHistory([]); update(withoutNavigation({ ...state, ...patch }), history); };
  const selectionEnabled = true;
  const selectedRows = page?.rows.filter((row) => selectedIds.has(row.id)) ?? [];
  const mutateBookmarks = async (operation: "add" | "remove", rows: readonly EntityListRowV1[]) => {
    if (!rows.length || allMatchingSelected) return;
    const ids = rows.map((row) => row.id), previous = new Set(bookmarkedIds), pending = new Set(pendingBookmarkIds);
    for (const id of ids) pending.add(id);
    setPendingBookmarkIds(pending); setBookmarkedIds((current) => { const next = new Set(current); for (const id of ids) operation === "add" ? next.add(id) : next.delete(id); return next; }); setPage((current) => current ? ({ ...current, rows: current.rows.map((row) => ids.includes(row.id) ? ({ ...row, decoration: { ...row.decoration, bookmarked: operation === "add" } }) : row) }) : current);
    const scope = entityListScopeQuery(scopeCoordinate);
    const body: RecordBookmarkMutationV1 = { records: rows.map((row) => ({ id: row.id, label: formatFieldValue(row.values[descriptor.entity.identityField], descriptor.fields.find((field) => field.key === descriptor.entity.identityField)) })), ...scope };
    try {
      await client.request(operation === "add" ? addRecordBookmarksOperation : removeRecordBookmarksOperation, { params: { entityCode }, body, idempotencyKey: `record-bookmark:${operation}:${crypto.randomUUID()}` });
      setActionStatus(`${ids.length} ${ids.length === 1 ? "record" : "records"} ${operation === "add" ? "added to" : "removed from"} favourites.`);
      window.dispatchEvent(new CustomEvent("athyper:record-bookmarks-changed", { detail: { entityCode, operation, recordIds: ids } }));
    } catch (cause) {
      setBookmarkedIds(previous); setPage((current) => current ? ({ ...current, rows: current.rows.map((row) => ids.includes(row.id) ? ({ ...row, decoration: { ...row.decoration, bookmarked: previous.has(row.id) } }) : row) }) : current); setActionStatus(cause instanceof Error ? cause.message : "Favourites could not be updated.");
    } finally { setPendingBookmarkIds((current) => { const next = new Set(current); for (const id of ids) next.delete(id); return next; }); }
  };
  return <section className={`a-entity-list a-entity-list--${state.density}`} aria-labelledby="page-title">
    <ListChrome descriptor={descriptor} state={state} page={page} scopeControl={scopeControl} loading={loading} actionStatus={actionStatus} onActionStatus={setActionStatus} onOpenDataOperations={() => setDataOperationsLaunch("picker")} onRefresh={() => setRefreshAttempt((value) => value + 1)} onChange={resetAndUpdate}/>
    {selectionEnabled && selectedIds.size ? <SelectionBar descriptor={descriptor} page={page} selectedRows={selectedRows} bookmarkedIds={bookmarkedIds} selectedCount={selectedIds.size} allMatching={allMatchingSelected} onBookmarks={(operation) => void mutateBookmarks(operation, selectedRows)} onSelectAllMatching={() => setAllMatchingSelected(true)} onExport={descriptor.dataOperations?.export.selected.state === "enabled" ? () => setDataOperationsLaunch(allMatchingSelected ? "filtered" : "selected") : undefined} onClear={() => { setSelectedIds(new Set()); setAllMatchingSelected(false); }}/>: null}
    {dataOperationsLaunch ? <DataOperationsControl client={client} descriptor={descriptor} state={state} page={page} selectedRows={selectedRows} scopeCoordinate={scopeCoordinate} activeViewName={readSavedViews(savedViewStorageKey(descriptor), descriptor).find((view) => view.id === state.savedViewId)?.name ?? "Default view"} onStatus={setActionStatus} open launch={dataOperationsLaunch} onOpenChange={(open) => { if (!open) setDataOperationsLaunch(undefined); }}/>: null}
    {error ? <ErrorState error={error} retry={() => setAttempt((value) => value + 1)} compact={Boolean(page)}/> : null}
    {loading && !page ? <LoadingTable columns={fields.length} /> : page ? <>
      <EntityRows descriptor={descriptor} page={page} fields={fields} mode={state.mode} sort={state.sort} group={state.group} query={state.query} loading={loading} selectionEnabled={selectionEnabled} selectedIds={selectedIds} bookmarkedIds={bookmarkedIds} pendingBookmarkIds={pendingBookmarkIds} onBookmark={(row, favourite) => void mutateBookmarks(favourite ? "add" : "remove", [row])} onSelectionChange={(next) => { setSelectedIds(next); setAllMatchingSelected(false); }} onSort={(field, additive) => resetAndUpdate({ sort: nextSort(state.sort, field, descriptor.limits.maxSortLevels, additive) }, "push")}/>
      <ListFooter
        descriptor={descriptor} state={state} page={page} loading={loading} cursorHistory={cursorHistory}
        onPrevious={() => {
          const cursor = cursorHistory.at(-1);
          setCursorHistory(cursorHistory.slice(0, -1));
          update({ ...state, cursor, pageIndex: Math.max(0, (state.pageIndex ?? cursorHistory.length) - 1) }, "push");
        }}
        onNext={() => {
          setCursorHistory([...cursorHistory, state.cursor]);
          update({ ...state, cursor: page.pagination.nextCursor, pageIndex: (state.pageIndex ?? 0) + 1 }, "push");
        }}
        onPageSize={(pageSize) => resetAndUpdate({ pageSize }, "push")}
      />
    </> : null}
  </section>;
}

function ListChrome({ descriptor, state, page, scopeControl, loading, actionStatus, onActionStatus, onOpenDataOperations, onRefresh, onChange }: { readonly descriptor: EntityListDescriptorV1; readonly state: ListLocationStateV1; readonly page?: EntityListResultV1; readonly scopeControl?: ReactNode; readonly loading: boolean; readonly actionStatus: string; readonly onActionStatus: (status: string) => void; readonly onOpenDataOperations: () => void; readonly onRefresh: () => void; readonly onChange: (patch: Partial<ListLocationStateV1>, history?: "replace" | "push") => void }) {
  const [query, setQuery] = useState(state.query ?? ""), [filtersOpen, setFiltersOpen] = useState(false), [sortOpen, setSortOpen] = useState(false), [columnsOpen, setColumnsOpen] = useState(false), [savedViewsOpen, setSavedViewsOpen] = useState(false), [settingsOpen, setSettingsOpen] = useState(false), [groupOpen, setGroupOpen] = useState(false), [resetOpen, setResetOpen] = useState(false), [views, setViews] = useState<readonly SavedListView[]>([]);
  const [refreshRequested, setRefreshRequested] = useState(false);
  const search = useRef<HTMLInputElement>(null);
  const refreshStarted = useRef(false);
  const viewKey = savedViewStorageKey(descriptor), activeView = views.find((view) => view.id === state.savedViewId), dirty = Boolean(activeView && JSON.stringify(saveableViewState(state)) !== JSON.stringify(activeView.state)), searchBehavior = readDisplayPreferences(descriptor.plane)?.searchBehavior ?? "instant";
  useEffect(() => setQuery(state.query ?? ""), [state.query]);
  useEffect(() => setViews(readSavedViews(viewKey, descriptor)), [viewKey, descriptor]);
  useEffect(() => { if (!refreshRequested) return; if (loading) { refreshStarted.current = true; onActionStatus("Refreshing list"); return; } if (refreshStarted.current) { refreshStarted.current = false; setRefreshRequested(false); onActionStatus("List refreshed"); } }, [loading, refreshRequested, onActionStatus]);
  useEffect(() => { const normalized = query.trim(); if (searchBehavior !== "instant" || normalized === (state.query ?? "") || (normalized.length > 0 && normalized.length < descriptor.surface.search.minimumQueryLength)) return; const timer = window.setTimeout(() => onChange({ query: normalized || undefined }), 350); return () => window.clearTimeout(timer); }, [query, state.query, searchBehavior, descriptor.surface.search.minimumQueryLength, onChange]);
  useEffect(() => { const focusSearch = (event: KeyboardEvent) => { const target = event.target, editing = target instanceof HTMLElement && target.matches("input, textarea, select, [contenteditable=true]"); if ((event.key === "/" && !editing) || ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k")) { event.preventDefault(); search.current?.focus(); } }; window.addEventListener("keydown", focusSearch); return () => window.removeEventListener("keydown", focusSearch); }, []);
  const submit = (event: FormEvent) => { event.preventDefault(); const normalized = query.trim(); if (normalized && normalized.length < descriptor.surface.search.minimumQueryLength) { onActionStatus(`Enter at least ${descriptor.surface.search.minimumQueryLength} characters to search`); return; } onChange({ query: normalized || undefined }, "push"); };
  const count = page?.pagination.total;
  const countLabel = count === undefined ? undefined : `${page?.pagination.countMode === "approximate" ? "≈" : ""}${new Intl.NumberFormat().format(count)}`;
  const groupLabel = state.group ? descriptor.fields.find((field) => field.key === state.group)?.label ?? state.group : "None";
  const customized = Boolean(state.savedViewId) || JSON.stringify(saveableViewState(state)) !== JSON.stringify(saveableViewState(descriptor.surface.defaultState));
  const reset = () => onChange({ ...descriptor.surface.defaultState, query: state.query, savedViewId: undefined }, "push");
  const copyViewLink = () => { void copyText(window.location.href).then((copied) => onActionStatus(copied ? "Link copied" : "Unable to copy link")); };
  return <div className="a-entity-list__chrome">
    <div className="a-entity-list__context-row">
      <div className="a-entity-list__identity"><h1 id="page-title">{descriptor.surface.title}</h1>{countLabel ? <span className="a-entity-list__count" aria-live="polite" title={page?.pagination.countMode === "cached" ? "Recently calculated result count" : undefined}>{countLabel}</span> : page ? <span className="a-entity-list__count" aria-live="polite" title={page.pagination.hasNext ? `At least ${page.rows.length} records` : `${page.rows.length} records`}>{new Intl.NumberFormat().format(page.rows.length)}{page.pagination.hasNext ? "+" : ""}</span> : null}<Badge tone="neutral">Read-only</Badge></div>
      <div className="a-entity-list__context-actions">{scopeControl}<Menu><MenuTrigger className="a-entity-list__view-trigger"><span>{activeView?.name ?? "Default view"}{dirty ? " •" : ""}</span><ChevronDownIcon size={16}/></MenuTrigger><MenuContent className="a-entity-list__view-menu"><MenuItem aria-current={!activeView ? "true" : undefined} onClick={() => onChange({ ...descriptor.surface.defaultState, query: state.query, savedViewId: undefined }, "push")}>Default view</MenuItem>{views.map((view) => <MenuItem key={view.id} aria-current={activeView?.id === view.id ? "true" : undefined} onClick={() => onChange({ ...view.state, query: state.query, savedViewId: view.id }, "push")}>{view.name}</MenuItem>)}<div className="a-entity-list__menu-separator" role="separator"/><MenuItem onClick={() => setSavedViewsOpen(true)}>＋ Save or manage views…</MenuItem></MenuContent></Menu><Button className="a-entity-list__refresh-button" variant="secondary" size="icon" aria-label={refreshRequested ? "Refreshing list" : "Refresh list"} title="Refresh list" aria-busy={refreshRequested || undefined} disabled={loading} onClick={() => { setRefreshRequested(true); onActionStatus("Refreshing list"); onRefresh(); }}><RefreshCwIcon size={18}/></Button></div>
    </div>
    <span className="a-visually-hidden" role="status" aria-live="polite">{actionStatus}</span>
    <div className="a-entity-list__query-row">
      <form className="a-entity-list__search" role="search" onSubmit={submit}><Label htmlFor="entity-list-search" className="a-visually-hidden">Search {descriptor.entity.pluralLabel}</Label><span className="a-entity-list__search-icon" aria-hidden="true"><SearchIcon size={16}/></span><Input ref={search} id="entity-list-search" type="search" value={query} onChange={(event) => setQuery(event.currentTarget.value)} placeholder={`Search by ${searchHint(descriptor)}…`} autoComplete="off" enterKeyHint="search"/><kbd title="Focus search">/</kbd></form>
      <div className="a-entity-list__toolbar-actions">
        <Button className="a-entity-list__toolbar-action" variant={state.filters.length ? "primary" : "secondary"} size="small" aria-label={state.filters.length ? `Filters, ${state.filters.length} active` : "Filters"} onClick={() => setFiltersOpen(true)}><FilterIcon size={16}/><span>Filters</span>{state.filters.length ? <span className="a-entity-list__action-count" aria-hidden="true">{state.filters.length}</span> : null}</Button>
        <Button className="a-entity-list__toolbar-action" variant={state.sort.length > 1 ? "primary" : "secondary"} size="small" aria-label={state.sort.length > 1 ? `Sort, ${state.sort.length} rules` : "Sort"} onClick={() => setSortOpen(true)}><SortIcon size={16}/><span>Sort</span>{state.sort.length > 1 ? <span className="a-entity-list__action-count" aria-hidden="true">{state.sort.length}</span> : null}</Button>
        <Button className="a-entity-list__toolbar-action" variant="secondary" size="small" aria-label={`${state.columns.length} visible fields`} onClick={() => setColumnsOpen(true)}><ColumnsIcon size={16}/><span className="a-entity-list__columns-label">Columns</span><span className="a-entity-list__fields-label">Fields</span><span className="a-entity-list__action-count" aria-hidden="true">{state.columns.length}</span></Button>
        <Menu><MenuTrigger className="a-entity-list__more-trigger" aria-label="More list options" title="More list options"><MoreHorizontalIcon size={17}/><span className="a-entity-list__more-label">More</span></MenuTrigger><MenuContent className="a-entity-list__more-menu"><ListMenuItem icon={<GroupIcon size={16}/>} label="Group by" value={groupLabel} onClick={() => setGroupOpen(true)}/><ListMenuItem icon={<LayoutIcon size={16}/>} label="Display settings" value={`${titleCase(state.mode)} · ${titleCase(state.density)}`} onClick={() => setSettingsOpen(true)}/>{hasVisibleDataOperations(descriptor) ? <><div className="a-entity-list__menu-separator" role="separator"/><ListMenuItem icon={<DownloadIcon size={16}/>} label="Data operations…" onClick={onOpenDataOperations}/></> : null}<ListMenuItem icon={<LinkIcon size={16}/>} label="Copy link to this view" onClick={copyViewLink}/><div className="a-entity-list__menu-separator" role="separator"/><ListMenuItem className="a-entity-list__reset-item" icon={<ResetIcon size={16}/>} label="Reset list settings" onClick={() => customized ? setResetOpen(true) : reset()}/></MenuContent></Menu>
      </div>
      <ActiveState descriptor={descriptor} state={state} onChange={onChange}/>
    </div>
    <FilterDialog open={filtersOpen} onOpenChange={setFiltersOpen} descriptor={descriptor} filters={state.filters} onApply={(filters) => onChange({ filters }, "push")}/>
    <SortDialog open={sortOpen} onOpenChange={setSortOpen} descriptor={descriptor} sort={state.sort} onApply={(sort) => onChange({ sort }, "push")}/>
    <ColumnsDialog open={columnsOpen} onOpenChange={setColumnsOpen} descriptor={descriptor} state={state} onApply={(columns) => onChange({ columns }, "push")}/>
    <GroupDialog open={groupOpen} onOpenChange={setGroupOpen} descriptor={descriptor} group={state.group} onApply={(group) => onChange({ group }, "push")}/>
    <DisplaySettingsDialog open={settingsOpen} onOpenChange={setSettingsOpen} descriptor={descriptor} state={state} onApply={(patch) => onChange(patch, "push")}/>
    <ResetConfigurationDialog open={resetOpen} onOpenChange={setResetOpen} onReset={reset}/>
    <SavedViewsDialog open={savedViewsOpen} onOpenChange={setSavedViewsOpen} descriptor={descriptor} state={state} views={views} onViewsChange={setViews} onApply={(patch) => onChange(patch, "push")}/>
  </div>;
}

function ListMenuItem({ icon, label, value, className, disabled, onClick }: { readonly icon: ReactNode; readonly label: string; readonly value?: string; readonly className?: string; readonly disabled?: boolean; readonly onClick: () => void }) {
  return <MenuItem className={className} disabled={disabled} onClick={onClick}><span className="a-entity-list__menu-icon" aria-hidden="true">{icon}</span><span>{label}</span>{value ? <small>{value}</small> : null}</MenuItem>;
}

function ResetConfigurationDialog({ open, onOpenChange, onReset }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly onReset: () => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title="Reset list settings?" description="This will discard the current filters, sorting, grouping, columns, layout, and density. Your saved views will not be deleted."><div className="a-entity-list__dialog-actions"><DialogClose className="a-button a-button--secondary a-button--small">Cancel</DialogClose><Button variant="danger" size="small" onClick={() => { onReset(); onOpenChange(false); }}>Reset list settings</Button></div></DialogContent></Dialog>;
}

interface DraftFilter { readonly id: string; readonly field: string; readonly operator: ListFilterOperator; readonly value: string; }
function FilterDialog({ open, onOpenChange, descriptor, filters, onApply }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly descriptor: EntityListDescriptorV1; readonly filters: readonly ListFilterV1[]; readonly onApply: (filters: readonly ListFilterV1[]) => void }) {
  const sequence = useRef(0), filterable = descriptor.fields.filter((field) => field.filterOperators.length).sort((left, right) => filterPriority(left) - filterPriority(right));
  const nextId = () => `filter-${++sequence.current}`;
  const makeDraft = () => filters.map((filter) => ({ id: nextId(), field: filter.field, operator: filter.operator, value: filterInputValue(filter) }));
  const [draft, setDraft] = useState<readonly DraftFilter[]>(makeDraft);
  useEffect(() => { if (open) setDraft(makeDraft()); }, [open, filters]);
  const add = () => { const field = filterable.find((candidate) => !draft.some((item) => item.field === candidate.key)); if (field) setDraft([...draft, { id: nextId(), field: field.key, operator: field.filterOperators[0]!, value: "" }]); };
  const apply = () => { const normalized = draft.flatMap((item) => { const value = filterValueFromInput(item.operator, item.value, filterable.find((field) => field.key === item.field)?.valueKind); if (value === "" || (typeof value === "number" && !Number.isFinite(value)) || (Array.isArray(value) && (!value.length || value.some((entry) => typeof entry === "number" && !Number.isFinite(entry))))) return []; return [{ field: item.field, operator: item.operator, ...(value !== undefined ? { value } : {}) } satisfies ListFilterV1]; }); onApply(Object.freeze(normalized)); onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DrawerContent title="Filters" description="Filters apply to the complete authorized result set." className="a-entity-list__filter-drawer"><div className="a-entity-list__dialog-body">{draft.length ? <div className="a-entity-list__filter-list"><div className="a-entity-list__filter-header" aria-hidden="true"><span>Field</span><span>Operator</span><span>Value</span><span>Action</span></div>{draft.map((item, index) => { const field = filterable.find((candidate) => candidate.key === item.field) ?? filterable[0], operators = field?.filterOperators ?? [], availableFields = filterable.filter((candidate) => candidate.key === item.field || !draft.some((active) => active.field === candidate.key)), replace = (next: DraftFilter) => setDraft(draft.map((candidate) => candidate.id === item.id ? next : candidate)); return <div className="a-entity-list__filter-row" key={item.id}><div className="a-entity-list__filter-control"><span className="a-entity-list__filter-label">Field</span><Select aria-label={`Field for filter ${index + 1}`} value={item.field} onChange={(event) => { const selected = filterable.find((candidate) => candidate.key === event.currentTarget.value)!; replace({ ...item, field: selected.key, operator: selected.filterOperators[0]!, value: "" }); }}>{availableFields.map((candidate) => <option value={candidate.key} key={candidate.key}>{candidate.label}</option>)}</Select></div><div className="a-entity-list__filter-control"><span className="a-entity-list__filter-label">Operator</span><Select aria-label={`Operator for ${field?.label ?? `filter ${index + 1}`}`} value={item.operator} onChange={(event) => replace({ ...item, operator: event.currentTarget.value as ListFilterOperator, value: "" })}>{operators.map((operator) => <option value={operator} key={operator}>{operatorLabel(operator)}</option>)}</Select></div>{field ? <FilterValueEditor field={field} operator={item.operator} value={item.value} filterNumber={index + 1} onChange={(value) => replace({ ...item, value })}/> : <span/>}<Button className="a-entity-list__filter-remove" variant="ghost" size="icon" aria-label={`Remove ${field?.label ?? "filter"}`} title={`Remove ${field?.label ?? "filter"}`} onClick={() => setDraft(draft.filter((candidate) => candidate.id !== item.id))}><TrashIcon size={17}/></Button></div>; })}</div> : <p className="a-entity-list__dialog-empty">No filters selected.</p>}<Button variant="secondary" size="small" onClick={add} disabled={!filterable.length || draft.length >= filterable.length}>Add filter</Button></div><div className="a-entity-list__dialog-actions"><Button variant="ghost" size="small" onClick={() => setDraft([])}>Reset filters</Button><DialogClose className="a-button a-button--secondary a-button--small">Cancel</DialogClose><Button size="small" onClick={apply}>Apply filters</Button></div></DrawerContent></Dialog>;
}

function FilterValueEditor({ field, operator, value, filterNumber, onChange }: { readonly field: ListFieldDescriptorV1; readonly operator: ListFilterOperator; readonly value: string; readonly filterNumber: number; readonly onChange: (value: string) => void }) {
  const label = `Value for ${field.label} filter ${filterNumber}`;
  if (operator === "is_null" || operator === "is_not_null") return <span className="a-entity-list__filter-no-value">No value required</span>;
  if (operator === "relative") return <div className="a-entity-list__filter-control"><span className="a-entity-list__filter-label">Value</span><Select aria-label={label} value={value} onChange={(event) => onChange(event.currentTarget.value)}><option value="">Select a relative date</option><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="tomorrow">Tomorrow</option><option value="last_7_days">Last 7 days</option><option value="last_30_days">Last 30 days</option><option value="next_7_days">Next 7 days</option><option value="next_30_days">Next 30 days</option><option value="this_week">This week</option><option value="this_month">This month</option></Select></div>;
  if (operator === "between") {
    const [from = "", to = ""] = value.split(",", 2), type = field.valueKind === "date" ? "date" : field.valueKind === "datetime" ? "datetime-local" : "number";
    return <div className="a-entity-list__filter-control a-entity-list__filter-range"><span className="a-entity-list__filter-label">Value</span><Input type={type} value={from.trim()} aria-label={`From ${label}`} onChange={(event) => onChange(`${event.currentTarget.value},${to.trim()}`)}/><span aria-hidden="true">–</span><Input type={type} value={to.trim()} aria-label={`To ${label}`} onChange={(event) => onChange(`${from.trim()},${event.currentTarget.value}`)}/></div>;
  }
  if (field.filterOptions?.length) {
    if (operator === "in") return <div className="a-entity-list__filter-control"><span className="a-entity-list__filter-label">Value</span><Select multiple size={Math.min(4, field.filterOptions.length)} aria-label={label} value={value.split(",").map((item) => item.trim()).filter(Boolean)} onChange={(event) => onChange([...event.currentTarget.selectedOptions].map((option) => option.value).join(","))}>{field.filterOptions.map((option) => <option key={String(option.value)} value={String(option.value)}>{option.label}</option>)}</Select></div>;
    return <div className="a-entity-list__filter-control"><span className="a-entity-list__filter-label">Value</span><Select aria-label={label} value={value} onChange={(event) => onChange(event.currentTarget.value)}><option value="">Select a value</option>{field.filterOptions.map((option) => <option key={String(option.value)} value={String(option.value)}>{option.label}</option>)}</Select></div>;
  }
  if (field.valueKind === "boolean") return <div className="a-entity-list__filter-control"><span className="a-entity-list__filter-label">Value</span><Select aria-label={label} value={value} onChange={(event) => onChange(event.currentTarget.value)}><option value="">Select a value</option><option value="true">Yes</option><option value="false">No</option></Select></div>;
  const type = field.valueKind === "date" ? "date" : field.valueKind === "datetime" ? "datetime-local" : ["integer", "decimal", "money"].includes(field.valueKind) ? "number" : field.valueKind === "reference" ? "search" : "text";
  const placeholder = field.valueKind === "reference" ? "Search by name or code" : operator === "in" ? "Enter values separated by commas" : "Enter a value";
  return <div className="a-entity-list__filter-control"><span className="a-entity-list__filter-label">Value</span><Input type={type} step={field.valueKind === "integer" ? 1 : ["decimal", "money"].includes(field.valueKind) ? "any" : undefined} inputMode={["integer", "decimal", "money"].includes(field.valueKind) ? "decimal" : undefined} aria-label={label} value={value} onChange={(event) => onChange(event.currentTarget.value)} placeholder={placeholder}/></div>;
}

function SortDialog({ open, onOpenChange, descriptor, sort, onApply }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly descriptor: EntityListDescriptorV1; readonly sort: readonly ListSortV1[]; readonly onApply: (sort: readonly ListSortV1[]) => void }) {
  const fields = descriptor.fields.filter((field) => field.sortable), [draft, setDraft] = useState<readonly ListSortV1[]>(sort);
  useEffect(() => { if (open) setDraft(sort); }, [open, sort]);
  const add = () => { const field = fields.find((candidate) => !draft.some((item) => item.field === candidate.key)); if (field && draft.length < descriptor.limits.maxSortLevels) setDraft([...draft, { field: field.key, direction: "asc" }]); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DrawerContent title="Sort" description="Sort by one or more fields in priority order." className="a-entity-list__sort-drawer"><div className="a-entity-list__dialog-body">{draft.length ? <div className="a-entity-list__sort-list">{draft.map((item, index) => <div key={`${item.field}-${index}`}><span className="a-entity-list__sort-order">{index + 1}</span><Label><span>Field</span><Select value={item.field} onChange={(event) => setDraft(draft.map((candidate, itemIndex) => itemIndex === index ? { ...candidate, field: event.currentTarget.value } : candidate))}>{fields.map((field) => <option value={field.key} key={field.key}>{field.label}</option>)}</Select></Label><Label><span>Direction</span><Select value={item.direction} onChange={(event) => setDraft(draft.map((candidate, itemIndex) => itemIndex === index ? { ...candidate, direction: event.currentTarget.value as "asc" | "desc" } : candidate))}><option value="asc">Ascending</option><option value="desc">Descending</option></Select></Label><div className="a-entity-list__sort-actions"><Button variant="ghost" size="small" disabled={index === 0} aria-label={`Move sort ${index + 1} up`} onClick={() => setDraft(moveItem(draft, index, index - 1))}>↑</Button><Button variant="ghost" size="small" disabled={index === draft.length - 1} aria-label={`Move sort ${index + 1} down`} onClick={() => setDraft(moveItem(draft, index, index + 1))}>↓</Button><Button variant="ghost" size="small" aria-label={`Remove sort ${index + 1}`} onClick={() => setDraft(draft.filter((_candidate, itemIndex) => itemIndex !== index))}>Remove</Button></div></div>)}</div> : <p className="a-entity-list__dialog-empty">No sorting selected.</p>}<Button variant="secondary" size="small" disabled={draft.length >= descriptor.limits.maxSortLevels || draft.length >= fields.length} onClick={add}>Add sort</Button></div><div className="a-entity-list__dialog-actions"><Button variant="ghost" size="small" onClick={() => setDraft(descriptor.surface.defaultState.sort)}>Reset sort</Button><DialogClose className="a-button a-button--secondary a-button--small">Cancel</DialogClose><Button size="small" onClick={() => { onApply(draft); onOpenChange(false); }}>Apply sort</Button></div></DrawerContent></Dialog>;
}

function ColumnsDialog({ open, onOpenChange, descriptor, state, onApply }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly descriptor: EntityListDescriptorV1; readonly state: ListLocationStateV1; readonly onApply: (columns: readonly string[]) => void }) {
  const defaults = descriptor.surface.defaultState.columns;
  const [columns, setColumns] = useState<readonly string[]>(state.columns);
  const [search, setSearch] = useState("");
  const [announcement, setAnnouncement] = useState("");
  const [drag, setDrag] = useState<{ readonly source: string; readonly target?: string; readonly edge?: "before" | "after" }>();
  useEffect(() => { if (open) { setColumns(state.columns); setSearch(""); setAnnouncement(""); setDrag(undefined); } }, [open, state.columns]);
  const fieldsByKey = new Map(descriptor.fields.map((field) => [field.key, field]));
  const normalizedSearch = search.trim();
  const matches = (field: ListFieldDescriptorV1) => matchesColumnSearch(field, search);
  const visibleFields = columns.map((key) => fieldsByKey.get(key)).filter((field): field is ListFieldDescriptorV1 => Boolean(field));
  const matchingVisibleFields = visibleFields.filter(matches);
  const availableFields = descriptor.fields.filter((field) => !columns.includes(field.key) && matches(field)).sort((left, right) => left.defaultOrder - right.defaultOrder || left.label.localeCompare(right.label));
  const availableGroups = groupAvailableColumns(availableFields);
  const move = (key: string, target: number) => {
    const current = columns.indexOf(key);
    if (current < 0 || target < 0 || target >= columns.length || current === target) return;
    const next = moveItem(columns, current, target);
    setColumns(next);
    setAnnouncement(`${fieldsByKey.get(key)?.label ?? key} moved to position ${target + 1}.`);
  };
  const remove = (field: ListFieldDescriptorV1) => { if (field.key !== descriptor.entity.identityField) { setColumns(columns.filter((key) => key !== field.key)); setAnnouncement(`${field.label} hidden.`); } };
  const add = (field: ListFieldDescriptorV1) => { setColumns([...columns, field.key]); setAnnouncement(`${field.label} added as column ${columns.length + 1}.`); };
  const dragStart = (event: ReactDragEvent<HTMLButtonElement>, key: string) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", key); setDrag({ source: key }); };
  const dragOver = (event: ReactDragEvent<HTMLDivElement>, target: string) => {
    if (!drag || drag.source === target) return;
    event.preventDefault();
    event.dataTransfer.dropEffect = "move";
    const bounds = event.currentTarget.getBoundingClientRect(), edge = event.clientY < bounds.top + bounds.height / 2 ? "before" : "after";
    if (drag.target !== target || drag.edge !== edge) setDrag({ source: drag.source, target, edge });
  };
  const drop = (event: ReactDragEvent<HTMLDivElement>, target: string) => {
    event.preventDefault();
    const source = drag?.source ?? event.dataTransfer.getData("text/plain"), edge = drag?.edge ?? "before";
    if (source && source !== target) { const next = reorderColumn(columns, source, target, edge); setColumns(next); setAnnouncement(`${fieldsByKey.get(source)?.label ?? source} moved to position ${next.indexOf(source) + 1}.`); }
    setDrag(undefined);
  };
  return <Dialog open={open} onOpenChange={onOpenChange}><DrawerContent title="Columns" description="Choose fields, search the catalogue, and arrange visible columns." className="a-entity-list__columns-drawer">
    <div className="a-entity-list__column-search"><SearchIcon size={17}/><Label htmlFor="entity-list-column-search" className="a-visually-hidden">Search fields</Label><Input id="entity-list-column-search" type="search" value={search} onChange={(event) => setSearch(event.currentTarget.value)} placeholder="Search fields by name or code…" autoComplete="off"/><span>{descriptor.fields.length} fields</span></div>
    <div className="a-entity-list__dialog-body a-entity-list__column-browser">
      <section aria-labelledby="visible-columns-heading"><div className="a-entity-list__column-section-heading"><h3 id="visible-columns-heading">Visible columns</h3><span>{columns.length} selected</span></div>
        {columns.length > 20 ? <p className="a-entity-list__column-warning">More than 20 visible columns may require horizontal scrolling.</p> : null}
        <div className="a-entity-list__column-list a-entity-list__column-list--visible">{matchingVisibleFields.map((field) => { const identity = field.key === descriptor.entity.identityField, index = columns.indexOf(field.key), dropEdge = drag?.target === field.key ? drag.edge : undefined; return <div key={field.key} data-dragging={drag?.source === field.key || undefined} data-drop-edge={dropEdge} onDragOver={(event) => dragOver(event, field.key)} onDrop={(event) => drop(event, field.key)}>
          <button type="button" className="a-entity-list__column-grip" draggable aria-label={`Drag ${field.label} to reorder`} title="Drag to reorder" onDragStart={(event) => dragStart(event, field.key)} onDragEnd={() => setDrag(undefined)}><GripVerticalIcon size={18}/></button>
          <Checkbox aria-label={`Show ${field.label}`} checked disabled={identity} onChange={() => remove(field)}/>
          <span className="a-entity-list__column-name"><strong>{field.label}</strong><small>{field.key}{identity ? " · Identity field" : ""}</small></span>
          <Button variant="ghost" size="icon" disabled={index <= 0} aria-label={`Move ${field.label} up`} title="Move up" onClick={() => move(field.key, index - 1)}><ArrowUpIcon size={16}/></Button>
          <Button variant="ghost" size="icon" disabled={index === columns.length - 1} aria-label={`Move ${field.label} down`} title="Move down" onClick={() => move(field.key, index + 1)}><ArrowDownIcon size={16}/></Button>
        </div>; })}</div>
        {!matchingVisibleFields.length ? <ColumnSearchEmpty search={search} section="visible columns" onClear={() => setSearch("")}/> : null}
      </section>
      <section aria-labelledby="available-columns-heading"><div className="a-entity-list__column-section-heading"><h3 id="available-columns-heading">Available fields</h3><span>{availableFields.length}{normalizedSearch ? ` of ${descriptor.fields.length - columns.length}` : ""}</span></div>
        {availableGroups.map((group) => <div className="a-entity-list__column-group" key={group.label}><h4>{group.label}<span>{group.fields.length}</span></h4><div className="a-entity-list__column-list a-entity-list__column-list--available">{group.fields.map((field) => <label key={field.key}><Checkbox aria-label={`Show ${field.label}`} checked={false} onChange={() => add(field)}/><span className="a-entity-list__column-name"><strong>{field.label}</strong><small>{field.key} · {fieldTypeLabel(field.valueKind)}</small></span></label>)}</div></div>)}
        {!availableGroups.length ? <ColumnSearchEmpty search={search} section="available fields" onClear={() => setSearch("")}/> : null}
      </section>
      <span className="a-visually-hidden" role="status" aria-live="polite">{announcement}</span>
    </div>
    <div className="a-entity-list__dialog-actions"><Button variant="ghost" size="small" onClick={() => { setColumns(defaults); setAnnouncement("Default columns restored."); }}>Reset columns</Button><DialogClose className="a-button a-button--secondary a-button--small">Cancel</DialogClose><Button size="small" onClick={() => { onApply(columns); onOpenChange(false); }}>Apply columns</Button></div>
  </DrawerContent></Dialog>;
}

function ColumnSearchEmpty({ search, section, onClear }: { readonly search: string; readonly section: string; readonly onClear: () => void }) { return <div className="a-entity-list__column-empty"><p>{search.trim() ? `No matching ${section}.` : `No ${section}.`}</p>{search.trim() ? <Button variant="ghost" size="small" onClick={onClear}>Clear search</Button> : null}</div>; }

function SavedViewsDialog({ open, onOpenChange, descriptor, state, views, onViewsChange, onApply }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly descriptor: EntityListDescriptorV1; readonly state: ListLocationStateV1; readonly views: readonly SavedListView[]; readonly onViewsChange: (views: readonly SavedListView[]) => void; readonly onApply: (patch: Partial<ListLocationStateV1>) => void }) {
  const [name, setName] = useState("");
  useEffect(() => { if (open) setName(""); }, [open]);
  const save = () => { const viewName = name.trim(); if (!viewName) return; const saved: SavedListView = Object.freeze({ id: globalThis.crypto?.randomUUID?.() ?? `${Date.now()}`, name: viewName, state: saveableViewState(state) }), next = Object.freeze([...views.filter((view) => view.name.toLocaleLowerCase() !== viewName.toLocaleLowerCase()), saved]); writeSavedViews(savedViewStorageKey(descriptor), next); onViewsChange(next); onApply({ ...saved.state, query: state.query, savedViewId: saved.id }); onOpenChange(false); };
  const remove = (id: string) => { const next = views.filter((view) => view.id !== id); writeSavedViews(savedViewStorageKey(descriptor), next); onViewsChange(next); if (state.savedViewId === id) onApply({ savedViewId: undefined }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title="Manage views" description="Save the current configuration or manage views for this list. Search text and organization scope are not saved." className="a-entity-list__manage-views-dialog"><div className="a-entity-list__dialog-body a-entity-list__view-dialog"><section><h3>Save current configuration</h3><div className="a-entity-list__save-view"><Label htmlFor="entity-list-view-name" className="a-visually-hidden">View name</Label><Input id="entity-list-view-name" value={name} onChange={(event) => setName(event.currentTarget.value)} placeholder="For example, Active UK suppliers"/><Button variant="secondary" size="small" disabled={!name.trim()} onClick={save}>Save view</Button></div><p className="a-entity-list__view-summary">Includes filters, sorting, grouping, columns, layout, and density.</p></section>{views.length ? <section><h3>Saved views</h3><div className="a-entity-list__saved-views">{views.map((view) => <div key={view.id}><button type="button" onClick={() => { onApply({ ...view.state, query: state.query, savedViewId: view.id }); onOpenChange(false); }}><strong>{view.name}</strong><small>{view.state.columns.length} columns · {view.state.filters.length} filters · {view.state.density}</small></button><Button variant="ghost" size="small" aria-label={`Delete ${view.name}`} onClick={() => remove(view.id)}>Delete</Button></div>)}</div></section> : null}</div><div className="a-entity-list__dialog-actions"><DialogClose className="a-button a-button--secondary a-button--small">Close</DialogClose></div></DialogContent></Dialog>;
}

function DisplaySettingsDialog({ open, onOpenChange, descriptor, state, onApply }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly descriptor: EntityListDescriptorV1; readonly state: ListLocationStateV1; readonly onApply: (patch: Partial<ListLocationStateV1>) => void }) {
  const preferences = readDisplayPreferences(descriptor.plane), [density, setDensity] = useState(state.density), [mode, setMode] = useState(state.mode), [searchBehavior, setSearchBehavior] = useState<DisplayPreferences["searchBehavior"]>(preferences?.searchBehavior ?? "instant");
  useEffect(() => { if (open) { const saved = readDisplayPreferences(descriptor.plane); setDensity(saved?.density ?? state.density); setMode(saved?.mode ?? state.mode); setSearchBehavior(saved?.searchBehavior ?? "instant"); } }, [open, descriptor.plane, state.density, state.mode]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title="Display settings" description={`Applies to all ${titleCase(descriptor.plane)} lists on this device.`}><div className="a-entity-list__dialog-body"><div className="a-entity-list__view-options"><Label><span>Layout</span><Select value={mode} onChange={(event) => setMode(event.currentTarget.value as ListLocationStateV1["mode"])}>{descriptor.surface.supportedModes.map((item) => <option value={item} key={item}>{titleCase(item)}</option>)}</Select></Label><Label><span>Density</span><Select value={density} onChange={(event) => setDensity(event.currentTarget.value as ListLocationStateV1["density"])}><option value="compact">Compact</option><option value="comfortable">Comfortable</option><option value="spacious">Spacious</option></Select></Label><Label><span>Search behavior</span><Select value={searchBehavior} onChange={(event) => setSearchBehavior(event.currentTarget.value as DisplayPreferences["searchBehavior"])}><option value="instant">Search as I type</option><option value="submit">Search when I press Enter</option></Select></Label></div></div><div className="a-entity-list__dialog-actions"><Button variant="ghost" size="small" onClick={() => { clearDisplayPreferences(descriptor.plane); setDensity(descriptor.surface.defaultState.density); setMode(descriptor.surface.defaultState.mode); setSearchBehavior("instant"); }}>Reset settings</Button><DialogClose className="a-button a-button--secondary a-button--small">Cancel</DialogClose><Button size="small" onClick={() => { writeDisplayPreferences(descriptor.plane, { density, mode, searchBehavior }); onApply({ density, mode }); onOpenChange(false); }}>Save settings</Button></div></DialogContent></Dialog>;
}

function GroupDialog({ open, onOpenChange, descriptor, group, onApply }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly descriptor: EntityListDescriptorV1; readonly group?: string; readonly onApply: (group?: string) => void }) {
  const [draft, setDraft] = useState(group ?? ""), fields = descriptor.fields.filter((field) => field.groupable);
  useEffect(() => { if (open) setDraft(group ?? ""); }, [open, group]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent title="Group by" description="Organize the current results into sections using one field."><div className="a-entity-list__dialog-body"><Label><span>Grouping field</span><Select value={draft} onChange={(event) => setDraft(event.currentTarget.value)}><option value="">No grouping</option>{fields.map((field) => <option value={field.key} key={field.key}>{field.label}</option>)}</Select></Label></div><div className="a-entity-list__dialog-actions"><Button variant="ghost" size="small" onClick={() => setDraft("")}>Clear grouping</Button><DialogClose className="a-button a-button--secondary a-button--small">Cancel</DialogClose><Button size="small" onClick={() => { onApply(draft || undefined); onOpenChange(false); }}>Apply grouping</Button></div></DialogContent></Dialog>;
}

function ActiveState({ descriptor, state, onChange }: { readonly descriptor: EntityListDescriptorV1; readonly state: ListLocationStateV1; readonly onChange: (patch: Partial<ListLocationStateV1>, history?: "replace" | "push") => void }) { const sortChanged = JSON.stringify(state.sort) !== JSON.stringify(descriptor.surface.defaultState.sort); if (!state.filters.length && !sortChanged && !state.group) return null; return <div className="a-entity-list__chips" aria-label="Active list state">{state.filters.map((filter, index) => <button type="button" key={`${filter.field}-${index}`} onClick={() => onChange({ filters: state.filters.filter((_item, itemIndex) => itemIndex !== index) }, "push")}>{describeFilter(filter, descriptor)} ×</button>)}{sortChanged ? state.sort.map((sort) => <button type="button" key={sort.field} onClick={() => onChange({ sort: state.sort.filter((item) => item.field !== sort.field) }, "push")}>Sort: {descriptor.fields.find((field) => field.key === sort.field)?.label ?? sort.field} {sort.direction === "asc" ? "↑" : "↓"} ×</button>) : null}{state.group ? <button type="button" onClick={() => onChange({ group: undefined }, "push")}>Group: {descriptor.fields.find((field) => field.key === state.group)?.label ?? state.group} ×</button> : null}{state.filters.length ? <Button variant="ghost" size="small" onClick={() => onChange({ filters: [] }, "push")}>Reset filters</Button> : null}</div>; }

function EntityRows({ descriptor, page, fields, mode, sort, group, query, loading, selectionEnabled, selectedIds, bookmarkedIds, pendingBookmarkIds, onBookmark, onSelectionChange, onSort }: { readonly descriptor: EntityListDescriptorV1; readonly page: EntityListResultV1; readonly fields: readonly ListFieldDescriptorV1[]; readonly mode: ListLocationStateV1["mode"]; readonly sort: readonly ListSortV1[]; readonly group?: string; readonly query?: string; readonly loading: boolean; readonly selectionEnabled: boolean; readonly selectedIds: ReadonlySet<string>; readonly bookmarkedIds: ReadonlySet<string>; readonly pendingBookmarkIds: ReadonlySet<string>; readonly onBookmark: (row: EntityListRowV1, favourite: boolean) => void; readonly onSelectionChange: (ids: ReadonlySet<string>) => void; readonly onSort: (field: string, additive: boolean) => void }) {
  if (!page.rows.length) return <Card className="a-entity-list__state"><h2>{query ? `No results for “${query}”` : "No matching records"}</h2><p>{query ? "Try a different name, code, or remove a filter." : "Try changing the filters. The selected work context remains authorized."}</p></Card>;
  const toggle = (id: string, checked: boolean) => { const next = new Set(selectedIds); if (checked) next.add(id); else next.delete(id); onSelectionChange(next); };
  const pageSelected = page.rows.length > 0 && page.rows.every((row) => selectedIds.has(row.id));
  const groups = groupedRows(page, group, descriptor), cards = (rows: readonly EntityListRowV1[]) => <div className="a-entity-list__cards" aria-busy={loading}>{rows.map((row) => { const identity = formatFieldValue(row.values[descriptor.entity.identityField], descriptor.fields.find((field) => field.key === descriptor.entity.identityField)), href = recordHref(descriptor, row); return <Card key={row.id} className="a-entity-list__card"><div className="a-entity-list__card-header">{selectionEnabled ? <Label className="a-entity-list__card-select"><Checkbox checked={selectedIds.has(row.id)} onChange={(event) => toggle(row.id, event.currentTarget.checked)}/> Select record</Label> : null}<BookmarkButton identity={identity} favourite={bookmarkedIds.has(row.id)} pending={pendingBookmarkIds.has(row.id)} onChange={(favourite) => onBookmark(row, favourite)}/></div><h2>{href ? <a className="a-entity-list__record-link" href={href}>{highlightText(identity, query)}</a> : highlightText(identity, query)}</h2><dl>{fields.filter((field) => field.key !== descriptor.entity.identityField).map((field) => <div key={field.key}><dt>{field.label}</dt><dd>{href && isRecordLinkField(field, descriptor) ? <a className="a-entity-list__record-link" href={href}>{renderFieldValue(row.values[field.key], field, query)}</a> : renderFieldValue(row.values[field.key], field, query)}</dd></div>)}</dl></Card>; })}</div>;
  if (mode === "compact") return group ? <div className="a-entity-list__groups">{groups.map((item) => <section key={item.label}><h2>{item.label} <small>{item.count}</small></h2>{cards(item.rows)}</section>)}</div> : cards(page.rows);
  const openRecord = (row: EntityListRowV1) => { const href = recordHref(descriptor, row); if (href) window.location.assign(href); };
  const tableRows = (rows: readonly EntityListRowV1[]) => rows.map((row) => { const href = recordHref(descriptor, row), identity = formatFieldValue(row.values[descriptor.entity.identityField]); return <tr key={row.id} tabIndex={href ? 0 : undefined} onKeyDown={(event) => { if (event.key === "Enter" && !(event.target instanceof HTMLInputElement || event.target instanceof HTMLButtonElement || event.target instanceof HTMLAnchorElement)) openRecord(row); if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); const sibling = event.key === "ArrowDown" ? event.currentTarget.nextElementSibling : event.currentTarget.previousElementSibling; (sibling as HTMLElement | null)?.focus(); } }}>{selectionEnabled ? <td className="a-entity-list__selection-cell" data-label="Select"><Checkbox aria-label={`Select ${identity}`} checked={selectedIds.has(row.id)} onChange={(event) => toggle(row.id, event.currentTarget.checked)}/></td> : null}{fields.map((field) => <td key={field.key} data-label={field.label} title={formatFieldValue(row.values[field.key], field)}>{href && isRecordLinkField(field, descriptor) ? <a className="a-entity-list__record-link" href={href}>{renderFieldValue(row.values[field.key], field, query)}</a> : renderFieldValue(row.values[field.key], field, query)}</td>)}<td className="a-entity-list__bookmark-cell" data-label="Favourite"><BookmarkButton identity={identity} favourite={bookmarkedIds.has(row.id)} pending={pendingBookmarkIds.has(row.id)} onChange={(favourite) => onBookmark(row, favourite)}/></td><td className="a-entity-list__row-actions"><RowMenu descriptor={descriptor} row={row}/></td></tr>; });
  const columnCount = fields.length + 2 + Number(selectionEnabled);
  return <div className="a-entity-list__table-wrap" aria-busy={loading}><table className="a-entity-list__table"><caption className="a-visually-hidden">{descriptor.surface.title}</caption><thead><tr>{selectionEnabled ? <th scope="col" className="a-entity-list__selection-cell"><Checkbox aria-label="Select current page" checked={pageSelected} onChange={(event) => { const next = new Set(selectedIds); for (const row of page.rows) if (event.currentTarget.checked) next.add(row.id); else next.delete(row.id); onSelectionChange(next); }}/></th> : null}{fields.map((field) => { const sortIndex = sort.findIndex((item) => item.field === field.key), active = sortIndex >= 0 ? sort[sortIndex] : undefined; return <th key={field.key} scope="col" aria-sort={active ? active.direction === "asc" ? "ascending" : "descending" : "none"} style={field.defaultWidth ? { width: field.defaultWidth, minWidth: field.defaultWidth } : undefined}>{field.sortable ? <button type="button" className="a-entity-list__sort-header" aria-label={sortHeaderLabel(field.label, active, sortIndex, sort.length)} title={sortHeaderTitle(active, descriptor.limits.maxSortLevels)} onClick={(event) => onSort(field.key, event.shiftKey)}><span>{field.label}</span><ColumnSortIndicator active={active} priority={sort.length > 1 ? sortIndex + 1 : undefined}/></button> : field.label}</th>; })}<th scope="col" className="a-entity-list__bookmark-heading"><span className="a-visually-hidden">Favourite</span></th><th scope="col" className="a-entity-list__actions-heading"><span className="a-visually-hidden">Actions</span></th></tr></thead><tbody>{group ? groups.flatMap((item) => [<tr className="a-entity-list__group-row" key={`group-${item.label}`}><th colSpan={columnCount} scope="rowgroup">{item.label} <span>{item.count}</span></th></tr>, ...tableRows(item.rows)]) : tableRows(page.rows)}</tbody></table></div>;
}

function SelectionBar({ descriptor, page, selectedRows, bookmarkedIds, selectedCount, allMatching, onBookmarks, onSelectAllMatching, onExport, onClear }: { readonly descriptor: EntityListDescriptorV1; readonly page?: EntityListResultV1; readonly selectedRows: readonly EntityListRowV1[]; readonly bookmarkedIds: ReadonlySet<string>; readonly selectedCount: number; readonly allMatching: boolean; readonly onBookmarks: (operation: "add" | "remove") => void; readonly onSelectAllMatching: () => void; readonly onExport?: () => void; readonly onClear: () => void }) { const total = page?.pagination.total, bookmarkedCount = selectedRows.filter((row) => bookmarkedIds.has(row.id)).length; return <div className="a-entity-list__selection-bar" role="status"><strong>{allMatching && total !== undefined ? new Intl.NumberFormat().format(total) : new Intl.NumberFormat().format(selectedCount)} selected</strong><span>{selectedCount === page?.rows.length ? `${selectedCount} records on this page selected.` : ""}</span>{!allMatching && total !== undefined && total > selectedCount && descriptor.dataOperations?.export.filtered.state === "enabled" ? <Button size="small" variant="secondary" onClick={onSelectAllMatching}>Select all {new Intl.NumberFormat().format(total)} matching records</Button> : null}{!allMatching ? <Menu><MenuTrigger><StarIcon size={16}/>Favourites <ChevronDownIcon size={14}/></MenuTrigger><MenuContent>{bookmarkedCount < selectedRows.length ? <MenuItem onClick={() => onBookmarks("add")}><StarIcon size={16}/>Add selected to favourites</MenuItem> : null}{bookmarkedCount > 0 ? <MenuItem onClick={() => onBookmarks("remove")}><StarIcon size={16}/>Remove selected from favourites</MenuItem> : null}</MenuContent></Menu> : <span>Favourites apply only to explicitly selected records.</span>}{onExport ? <Button size="small" variant="secondary" onClick={onExport}><DownloadIcon size={16}/>Export</Button> : null}<Button size="small" variant="ghost" onClick={onClear}>Clear selection</Button></div>; }
function BookmarkButton({ identity, favourite, pending, onChange }: { readonly identity: string; readonly favourite: boolean; readonly pending: boolean; readonly onChange: (favourite: boolean) => void }) { const label = favourite ? `Remove ${identity} from favourites` : `Add ${identity} to favourites`; return <button type="button" className="a-entity-list__bookmark" data-bookmarked={favourite || undefined} aria-label={label} aria-pressed={favourite} title={label} disabled={pending} onClick={() => onChange(!favourite)}><StarIcon size={18}/></button>; }
function RowMenu({ descriptor, row }: { readonly descriptor: EntityListDescriptorV1; readonly row: EntityListRowV1 }) { const identity = formatFieldValue(row.values[descriptor.entity.identityField], descriptor.fields.find((field) => field.key === descriptor.entity.identityField)), href = recordHref(descriptor, row); return <Menu><MenuTrigger aria-label={`Actions for ${identity}`} title={`Actions for ${identity}`}><MoreVerticalIcon size={18}/></MenuTrigger><MenuContent><MenuItem onClick={() => void navigator.clipboard?.writeText(identity)}>Copy {descriptor.fields.find((field) => field.key === descriptor.entity.identityField)?.label ?? "identity"}</MenuItem>{href ? <MenuItem onClick={() => window.location.assign(href)}>Open record</MenuItem> : null}</MenuContent></Menu>; }
function ListFooter({ descriptor, state, page, loading, cursorHistory, onPrevious, onNext, onPageSize }: { readonly descriptor: EntityListDescriptorV1; readonly state: ListLocationStateV1; readonly page: EntityListResultV1; readonly loading: boolean; readonly cursorHistory: readonly (string | undefined)[]; readonly onPrevious: () => void; readonly onNext: () => void; readonly onPageSize: (value: number) => void }) { const pageSize = state.pageSize ?? descriptor.limits.defaultPageSize, start = page.rows.length ? (state.pageIndex ?? cursorHistory.length) * pageSize + 1 : 0, end = start ? start + page.rows.length - 1 : 0, formattedRange = page.rows.length ? `${new Intl.NumberFormat().format(start)}–${new Intl.NumberFormat().format(end)}` : "No records", total = page.pagination.total, countPrefix = page.pagination.countMode === "approximate" ? "≈" : "", summary = total === undefined ? `Showing ${formattedRange}${page.pagination.hasNext ? " · more available" : ""}` : `Showing ${formattedRange} of ${countPrefix}${new Intl.NumberFormat().format(total)}`; return <nav className="a-entity-list__pagination" aria-label="List pagination"><span aria-live="polite" title={page.pagination.countMode === "cached" ? "Recently calculated result count" : undefined}>{summary}</span><div className="a-entity-list__page-controls"><Label><span>Rows per page</span><Select value={pageSize} onChange={(event) => onPageSize(Number(event.currentTarget.value))}>{descriptor.limits.allowedPageSizes.map((size) => <option value={size} key={size}>{size}</option>)}</Select></Label><Button size="small" variant="secondary" disabled={!cursorHistory.length || loading} onClick={onPrevious}>Previous</Button><Button size="small" variant="secondary" disabled={!page.pagination.hasNext || !page.pagination.nextCursor || loading} onClick={onNext}>Next</Button></div></nav>; }

function recordHref(descriptor: EntityListDescriptorV1, row: EntityListRowV1): string | undefined { return descriptor.entity.detailRouteTemplate?.replace(":recordId", encodeURIComponent(row.id)); }
function isRecordLinkField(field: ListFieldDescriptorV1, descriptor: EntityListDescriptorV1): boolean { return field.key === descriptor.entity.identityField || field.semanticRole === "title"; }
function ColumnSortIndicator({ active, priority }: { readonly active?: ListSortV1; readonly priority?: number }) { const Icon = active?.direction === "asc" ? ArrowUpIcon : active?.direction === "desc" ? ArrowDownIcon : ArrowUpDownIcon; return <span className={`a-entity-list__sort-indicator${active ? " a-entity-list__sort-indicator--active" : ""}`} aria-hidden="true"><Icon size={15}/>{active && priority ? <small>{priority}</small> : null}</span>; }
function sortHeaderLabel(label: string, active: ListSortV1 | undefined, index: number, levels: number): string { const action = !active ? "sort ascending" : active.direction === "asc" ? "sort descending" : "clear sorting"; if (!active) return `${label}, not sorted. Activate to ${action}.`; return `${label}, sorted ${active.direction === "asc" ? "ascending" : "descending"}${levels > 1 ? `, priority ${index + 1}` : ""}. Activate to ${action}.`; }
function sortHeaderTitle(active: ListSortV1 | undefined, maximum: number): string { const action = !active ? "Sort ascending" : active.direction === "asc" ? "Sort descending" : "Clear sorting"; return maximum > 1 ? `${action}. Shift-click to manage multi-column sorting.` : action; }

function renderFieldValue(value: JsonValue | undefined, field: ListFieldDescriptorV1, query?: string): ReactNode { const display = formatFieldValue(value, field), highlighted = highlightText(display, query); if (field.semanticRole === "status") { const normalized = String(value ?? "").toLowerCase(); return <span className={`a-entity-list__status a-entity-list__status--${normalized === "active" ? "success" : normalized === "draft" ? "warning" : "neutral"}`}><span aria-hidden="true"/>{highlighted}</span>; } return highlighted; }
function formatFieldValue(value: JsonValue | undefined, field?: ListFieldDescriptorV1): string { if (value === undefined || value === null || value === "") return "—"; if (typeof value === "boolean") return value ? "Yes" : "No"; if (typeof value === "object") return JSON.stringify(value); if (field?.valueKind === "datetime" || field?.valueKind === "date") { const date = new Date(String(value)); if (!Number.isNaN(date.getTime())) return new Intl.DateTimeFormat(undefined, field.valueKind === "date" ? { dateStyle: "medium" } : { dateStyle: "medium", timeStyle: "short" }).format(date); } if (field?.semanticRole === "country_code" && typeof Intl.DisplayNames === "function") { try { return new Intl.DisplayNames(undefined, { type: "region" }).of(String(value).toUpperCase()) ?? String(value); } catch { return String(value); } } if (field?.valueKind === "enum") return String(value).replace(/[_-]+/g, " ").replace(/\b\w/g, (character) => character.toUpperCase()); return String(value); }
async function copyText(value: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) { await navigator.clipboard.writeText(value); return true; }
    const control = document.createElement("textarea");
    control.value = value; control.readOnly = true; control.className = "a-visually-hidden"; document.body.append(control); control.select();
    const copied = typeof document.execCommand === "function" && document.execCommand("copy");
    control.remove(); return copied;
  } catch { return false; }
}
function highlightText(value: string, query?: string): ReactNode { const needle = query?.trim(); if (!needle || needle.length < 2) return value; const index = value.toLocaleLowerCase().indexOf(needle.toLocaleLowerCase()); if (index < 0) return value; return <>{value.slice(0, index)}<mark>{value.slice(index, index + needle.length)}</mark>{value.slice(index + needle.length)}</>; }
function searchHint(descriptor: EntityListDescriptorV1): string { const priority = (field: ListFieldDescriptorV1) => field.key === descriptor.entity.identityField ? 0 : /display.?name|\bname\b/i.test(`${field.key} ${field.label}`) ? 1 : field.semanticRole === "country_code" || /country/i.test(`${field.key} ${field.label}`) ? 2 : 10 + field.defaultOrder; return [...descriptor.fields].sort((left, right) => priority(left) - priority(right)).slice(0, 3).map((field) => field.label.replace(new RegExp(`^${descriptor.entity.label}\\s+`, "i"), "").toLocaleLowerCase()).join(", "); }
function filterPriority(field: ListFieldDescriptorV1): number { const value = `${field.key} ${field.label}`; return field.semanticRole === "status" || /\bstatus\b/i.test(value) ? 0 : /category|group/i.test(value) ? 1 : field.semanticRole === "country_code" || /country/i.test(value) ? 2 : field.semanticRole === "updated_at" || /updated|modified/i.test(value) ? 3 : 10 + field.defaultOrder; }
function groupedRows(page: EntityListResultV1, group: string | undefined, descriptor: EntityListDescriptorV1): readonly { readonly label: string; readonly count: number; readonly rows: readonly EntityListRowV1[] }[] { if (!group) return [{ label: "All records", count: page.rows.length, rows: page.rows }]; const field = descriptor.fields.find((candidate) => candidate.key === group), authoritativeCounts = new Map((page.groups ?? []).map((bucket) => [formatFieldValue(bucket.value, field), bucket.count ?? 0])), buckets = new Map<string, EntityListRowV1[]>(); for (const row of page.rows) { const label = formatFieldValue(row.values[group], field), bucket = buckets.get(label) ?? []; bucket.push(row); buckets.set(label, bucket); } return [...buckets].sort(([left], [right]) => left.localeCompare(right)).map(([label, grouped]) => ({ label, count: authoritativeCounts.get(label) ?? grouped.length, rows: grouped })); }
function nextSort(current: readonly ListSortV1[], field: string, maximum: number, additive: boolean): readonly ListSortV1[] { if (!additive || maximum <= 1) return nextPrimarySort(current, field); const index = current.findIndex((item) => item.field === field); if (index < 0) return Object.freeze([...current, { field, direction: "asc" as const }].slice(0, maximum)); const active = current[index]!; if (active.direction === "asc") return Object.freeze(current.map((item, itemIndex) => itemIndex === index ? { ...item, direction: "desc" as const } : item)); return Object.freeze(current.filter((_item, itemIndex) => itemIndex !== index)); }
function titleCase(value: string): string { return value.replace(/[_-]+/g, " ").replace(/\b\w/g, (character) => character.toUpperCase()); }
function moveItem<T>(items: readonly T[], from: number, to: number): readonly T[] { if (to < 0 || to >= items.length) return items; const next = [...items], [item] = next.splice(from, 1); if (item !== undefined) next.splice(to, 0, item); return next; }
function operatorLabel(operator: ListFilterOperator): string { return ({ eq: "Equals", ne: "Does not equal", in: "Any of", contains: "Contains", starts_with: "Starts with", gt: "Greater than", gte: "At least", lt: "Less than", lte: "At most", between: "Between", is_null: "Is empty", is_not_null: "Is not empty", relative: "Relative period" })[operator]; }
function writeLocation(state: ListLocationStateV1, descriptor: EntityListDescriptorV1, history: "replace" | "push") { const query = encodeListLocationState(state, descriptor).toString(), href = `${window.location.pathname}${query ? `?${query}` : ""}`; if (history === "push") window.history.pushState(window.history.state, "", href); else window.history.replaceState(window.history.state, "", href); }
function asTransportError(cause: unknown): ApiTransportError { return cause instanceof ApiTransportError ? cause : new ApiTransportError("parse", "The list response could not be verified", 0, undefined, undefined, undefined, undefined, { cause }); }
function ListFrame({ title, loading, error, retry }: { readonly title: string; readonly loading: boolean; readonly error?: ApiTransportError; readonly retry: () => void }) { return <section className="a-entity-list" aria-labelledby="page-title"><ContentHeader eyebrow="Read-only list" title={title}/>{error ? <ErrorState error={error} retry={retry}/> : loading ? <LoadingTable columns={5}/> : null}</section>; }
function ErrorState({ error, retry, compact = false }: { readonly error: ApiTransportError; readonly retry: () => void; readonly compact?: boolean }) { return <Card className={`a-entity-list__state${compact ? " a-entity-list__state--inline" : ""}`} role="alert"><Badge tone="danger">Unavailable</Badge><div><h2>{compact ? "The latest results could not be loaded" : "The list could not be loaded"}</h2><p>{error.message}</p>{error.requestId ? <small>Request ID: {error.requestId}</small> : null}</div><Button size="small" variant="secondary" onClick={retry}>Try again</Button></Card>; }
function LoadingTable({ columns }: { readonly columns: number }) { return <Card className="a-entity-list__loading" aria-label="Loading records">{Array.from({ length: Math.max(3, columns) }, (_, index) => <Skeleton key={index}/>)}</Card>; }

export { describeFilter, nextPrimarySort, visibleListFields, withoutNavigation } from "./state";
export { ListScopeControl, type ListScopeControlProps, type ListScopeOption } from "./scope-control";
export { RecordTransferWorkspace } from "./transfer-workspace";
