"use client";
import {useEffect,useState} from "react";
interface Member {candidateId:string;principalCode:string;groupCode:string;scopeName:string;scope:{kind:string;targetId:string;propagationMode:string};proposalSha256:string;}
interface Batch {batchId:string;batchSha256:string;reviewMode:string;decision:string;roleCode:string;members:Member[];selfReviewAcknowledgementRequired:boolean;}
interface Item {candidateId:string;proposal:{rationale:string;responsibilities:{responsibility:string;capabilities:string[]}[];retainedLegacyCapabilities:string[];conditions:{effectiveFrom:string;effectiveUntil:string;mfa?:string;separationOfDuties?:string};};}
interface Review {reviewerId:string;platformReviewComplete:boolean;complete:boolean;assurance:string;request?:{requestSha256:string;batches:Batch[]};items?:Item[];receipts:{reference:string;remainingRows:number}[];}
const endpoint="/api/governance/named-role-review";
function csrf(){const cookie=document.cookie.split("; ").find(c=>c.startsWith("__Host-athyper-csrf=")||c.startsWith("athyper-csrf="));return cookie?decodeURIComponent(cookie.slice(cookie.indexOf("=")+1)):"";}
export function NamedRoleReview(){
 const [review,setReview]=useState<Review>(),[error,setError]=useState(""),[selected,setSelected]=useState<string[]>([]),[own,setOwn]=useState<string[]>([]),[business,setBusiness]=useState(false),[security,setSecurity]=useState(false),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[submission,setSubmission]=useState<string>();
 useEffect(()=>{const controller=new AbortController();setReview(undefined);setSelected([]);setOwn([]);setBusiness(false);setSecurity(false);setSubmission(undefined);void fetch(endpoint,{cache:"no-store",signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.code??"Review unavailable");setReview(b);setError("");}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[reload]);
 const toggle=(id:string)=>{setSubmission(undefined);setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);setOwn(s=>s.filter(x=>x!==id));};
 async function approve(){if(!review?.request)return;setBusy(true);setError("");const id=submission??crypto.randomUUID();setSubmission(id);try{const r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrf()},body:JSON.stringify({submissionId:id,requestSha256:review.request.requestSha256,approvedBatchIds:selected,selfReviewAcknowledgedBatchIds:own.filter(id=>selected.includes(id)),confirmBusiness:business,confirmSecurity:security})});const body=await r.json();if(!r.ok){if(body.code==="REVIEW_STEP_UP_REQUIRED")setReview({...review,assurance:"baseline"});throw Error(body.code??"Approval was not recorded");}setReload(x=>x+1);}catch(e){setError(e instanceof Error?e.message:"Approval unavailable");}finally{setBusy(false);}}
 const batches=review?.request?.batches??[],ready=selected.length>0&&business&&security&&batches.filter(b=>selected.includes(b.batchId)&&b.selfReviewAcknowledgementRequired).every(b=>own.includes(b.batchId));
 return <main style={{padding:"2rem",maxWidth:1100,margin:"auto"}}><h1>Business Partner responsibility review</h1><p>Reviewer: {review?.reviewerId??"Verifying identity"} · Business and security decisions</p><p>Approve the captured responsibility proposals. Existing grants stay unchanged. Publication, current-grant validation and activation require separate approval.</p>
 {error?<p role="alert">{error} <button type="button" onClick={()=>setReload(x=>x+1)}>Reload review</button></p>:null}
 {!review&&!error?<p role="status">Loading review…</p>:null}
 {review?.receipts.map(r=><p key={r.reference} role="status">Recorded: {r.reference}. Remaining rows: {r.remainingRows}.</p>)}
 {review?.complete?<h2>Your assigned mappings have recorded approval</h2>:null}
 {review&&!review.complete&&review.assurance!=="elevated"?<section><h2>Verify your identity</h2><p>MFA is required before submitting approval. Return here after verification and select the manifests you approve.</p><form action="/api/auth/step-up/start?returnTo=%2Fmdg%2Fauthorization-review" method="post" onSubmit={e=>{const input=e.currentTarget.elements.namedItem("csrfToken") as HTMLInputElement;input.value=csrf();}}><input type="hidden" name="csrfToken"/><button type="submit">Continue to MFA</button></form></section>:null}
 {review?.request?<><p>{batches.length} review manifests remain. Selection is never automatic.</p><button type="button" disabled={busy} onClick={()=>{setSubmission(undefined);setSelected(batches.filter(b=>b.reviewMode==="equivalent_batch").map(b=>b.batchId));setOwn([]);}}>Select equivalent batches only</button> <button type="button" disabled={busy} onClick={()=>{setSubmission(undefined);setSelected([]);setOwn([]);}}>Clear selection</button>
 <fieldset disabled={busy}><legend>Manifests and individual exceptions</legend>{batches.map(b=>{const item=review.items?.find(i=>i.candidateId===b.members[0]?.candidateId);return <section key={b.batchId} style={{border:"1px solid #ccd3dc",padding:"1rem",margin:"1rem 0"}}><label><input type="checkbox" checked={selected.includes(b.batchId)} onChange={()=>toggle(b.batchId)}/> {b.decision.replaceAll("_"," ")} · {b.members.length} mappings · {b.reviewMode.replaceAll("_"," ")}</label><p>{item?.proposal.rationale}</p><details><summary>Review capabilities, exact scopes and conditions</summary><p>Role: {b.roleCode}</p>{item?.proposal.responsibilities.map(r=><div key={r.responsibility}><h3>{r.responsibility}</h3><ul>{r.capabilities.map(c=><li key={c}>{c}</li>)}</ul></div>)}<p>Retained legacy capabilities: {item?.proposal.retainedLegacyCapabilities.join(", ")||"None"}</p><p>Proposed window: {item?.proposal.conditions.effectiveFrom} through {item?.proposal.conditions.effectiveUntil}. Retention/exclusion dates do not alter grant validity.</p>{item?.proposal.conditions.mfa?<p>MFA: {item.proposal.conditions.mfa}. {item.proposal.conditions.separationOfDuties}</p>:null}<table><thead><tr><th>Account / group</th><th>Exact scope</th><th>Propagation</th></tr></thead><tbody>{b.members.map(m=><tr key={m.candidateId}><td>{m.principalCode} / {m.groupCode}</td><td>{m.scopeName} · {m.scope.kind} · {m.scope.targetId}</td><td>{m.scope.propagationMode}</td></tr>)}</tbody></table><details><summary>Revision references</summary><p>{b.batchId}: {b.batchSha256}</p>{b.members.map(m=><p key={m.candidateId}>{m.principalCode}: {m.proposalSha256}</p>)}</details></details>{b.selfReviewAcknowledgementRequired?<label><input type="checkbox" disabled={!selected.includes(b.batchId)} checked={own.includes(b.batchId)} onChange={()=>{setSubmission(undefined);setOwn(s=>s.includes(b.batchId)?s.filter(id=>id!==b.batchId):[...s,b.batchId]);}}/> I explicitly acknowledge that this proposal concerns my own membership.</label>:null}</section>;})}</fieldset>
 <fieldset disabled={busy}><legend>Approval decision</legend><label><input type="checkbox" checked={business} onChange={e=>{setBusiness(e.target.checked);setSubmission(undefined);}}/> I approve the selected capabilities, exact scopes, propagation and effective dates.</label><br/><label><input type="checkbox" checked={security} onChange={e=>{setSecurity(e.target.checked);setSubmission(undefined);}}/> I approve the selected MFA, separation-of-duties and deny/revocation conditions. Grants and activation remain unchanged.</label></fieldset>
 <button type="button" disabled={busy||!ready||review.assurance!=="elevated"} onClick={()=>void approve()}>{busy?"Recording approval…":`Approve ${selected.length} selected manifests`}</button></>:null}
 </main>;
}
