import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { BookPeriodService, FinanceNumberingService, FinancePostingGuard, RoundingResolver } from "@athyper/server-service-finance";
import { HttpError, defineRouteContract, registerContractRoute, type Application, type RequestHandler, type Response } from "@athyper/server-runtime-http";

export function registerFinanceRoutes(application: Application, options: { readonly authenticate: RequestHandler; readonly readContext: (response: Response) => VerifiedRequestContext; readonly periods: BookPeriodService<any>; readonly rounding: RoundingResolver; readonly postingGuard?: FinancePostingGuard; readonly numbering?: FinanceNumberingService<any> }): void {
  const handle=(work:(request:any,context:VerifiedRequestContext)=>Promise<unknown>)=>async(request:any,response:Response,next:(error?:unknown)=>void)=>{try{response.json(await work(request,options.readContext(response)));}catch(error){next(financeHttpError(error));}};
  registerContractRoute(application,contracts.transition,options.authenticate,handle((request,context)=>{const body=object(request.body),actor=actorFrom(context);return options.periods.transition({actor,coordinates:{companyCodeId:uuid(body["companyCodeId"]),ledgerBookId:uuid(request.params["ledgerBookId"]),fiscalPeriodId:uuid(request.params["fiscalPeriodId"])},targetStatus:periodStatus(body["targetStatus"]),expectedVersion:positiveInteger(request.headers["if-match"]),...(body["authorizeReopen"]===true?{authorizeReopen:true}:{}),...(text(body["reopenReason"])?{reopenReason:text(body["reopenReason"])!}:{}),...(record(body["reopenApprovalEvidence"])?{reopenApprovalEvidence:record(body["reopenApprovalEvidence"])!}:{})});}));
  registerContractRoute(application,contracts.rounding,options.authenticate,handle((request,context)=>{const body=object(request.body),actor=actorFrom(context);return options.rounding.resolve({tenantId:actor.tenantId,actor,companyCodeId:uuid(body["companyCodeId"]),currencyCode:currency(body["currencyCode"]),slot:required(body["slot"]) as never});}));
  if(options.postingGuard)registerContractRoute(application,contracts.admission,options.authenticate,handle((request,context)=>{const body=object(request.body),coordinates=object(body["coordinates"]),source=object(body["source"]);return options.postingGuard!.admit({actor:actorFrom(context),permissionCode:required(body["permissionCode"]),coordinates:{companyCodeId:uuid(coordinates["companyCodeId"]),ledgerBookId:uuid(coordinates["ledgerBookId"]),fiscalPeriodId:uuid(coordinates["fiscalPeriodId"]),currencyCode:currency(coordinates["currencyCode"])},roundingSlot:required(body["roundingSlot"]) as never,source:{sourceType:required(source["sourceType"]),sourceId:uuid(source["sourceId"]),version:positiveInteger(source["version"]),hash:sha256(source["hash"])}});}));
  if(options.numbering){
    registerContractRoute(application,contracts.numberAllocation,options.authenticate,handle((request,context)=>{const body=object(request.body),fx=record(body["fxTrace"]);return options.numbering!.allocate({actor:actorFrom(context),commandId:uuid(body["commandId"]),idempotencyKey:required(body["idempotencyKey"]),occurredAt:isoDate(body["occurredAt"]),companyCodeId:uuid(body["companyCodeId"]),ledgerBookId:uuid(body["ledgerBookId"]),fiscalPeriodId:uuid(body["fiscalPeriodId"]),documentId:uuid(body["documentId"]),documentType:required(body["documentType"]),jurisdictionCode:required(body["jurisdictionCode"]).toUpperCase(),transactionCurrencyCode:currency(body["transactionCurrencyCode"]),baseCurrencyCode:currency(body["baseCurrencyCode"]),...(fx?{fxTrace:{sourceCode:required(fx["sourceCode"]),sourceVersion:required(fx["sourceVersion"]),rateId:uuid(fx["rateId"]),rateVersion:positiveInteger(fx["rateVersion"]),rateDate:required(fx["rateDate"]),fromCurrencyCode:currency(fx["fromCurrencyCode"]),toCurrencyCode:currency(fx["toCurrencyCode"]),rate:required(fx["rate"])}}:{})});}));
    registerContractRoute(application,contracts.numberReconciliation,options.authenticate,handle((request,context)=>{const query=object(request.query);return options.numbering!.reconcile({actor:actorFrom(context),policyId:uuid(query["policyId"]),policyRevision:required(query["policyRevision"]),...(text(query["fiscalPeriodId"])?{fiscalPeriodId:uuid(query["fiscalPeriodId"])}:{})});}));
  }
}

const schema={type:"object",additionalProperties:true} as const;
export const financeRouteContracts={transition:defineRouteContract({method:"post",path:"/api/finance/books/:ledgerBookId/periods/:fiscalPeriodId/transitions",operationId:"finance.bookPeriods.transition",summary:"Transition a finance book period",tags:["Finance"],authenticated:true,permission:"finance.period.manage",request:{headers:{type:"object",properties:{"If-Match":{type:"integer",minimum:1}},required:["If-Match"]},body:schema},responses:{200:{description:"Book period transitioned",body:schema},400:{description:"Invalid transition"},403:{description:"Forbidden"},404:{description:"Not found"},409:{description:"Version conflict"}}}),rounding:defineRouteContract({method:"post",path:"/api/finance/rounding/resolve",operationId:"finance.rounding.resolve",summary:"Resolve finance rounding evidence",tags:["Finance"],authenticated:true,permission:"finance.ledger.read",request:{body:schema},responses:{200:{description:"Rounding evidence",body:schema},403:{description:"Forbidden"},404:{description:"Not found"}}}),admission:defineRouteContract({method:"post",path:"/api/finance/posting-admissions",operationId:"finance.postingAdmissions.create",summary:"Resolve posting admission evidence",tags:["Finance"],authenticated:true,request:{body:schema},responses:{200:{description:"Posting admission",body:schema},403:{description:"Forbidden"},409:{description:"Posting blocked"}}}),numberAllocation:defineRouteContract({method:"post",path:"/api/finance/numbering/allocations",operationId:"finance.numbering.allocations.create",summary:"Allocate a governed finance document number",tags:["Finance","Numbering"],authenticated:true,permission:"finance.numbering.allocate",request:{body:schema},responses:{200:{description:"Number allocated",body:schema},400:{description:"Invalid allocation"},403:{description:"Forbidden"},404:{description:"Policy not found"},409:{description:"Period closed or numbering conflict"}}}),numberReconciliation:defineRouteContract({method:"get",path:"/api/finance/numbering/reconciliation",operationId:"finance.numbering.reconciliation.read",summary:"Reconcile finance number allocations",tags:["Finance","Numbering"],authenticated:true,permission:"finance.numbering.reconcile",request:{query:schema},responses:{200:{description:"Numbering reconciliation report",body:schema},400:{description:"Invalid query"},403:{description:"Forbidden"}}})} as const;
const contracts=financeRouteContracts;
function actorFrom(context:VerifiedRequestContext){if(context.planeKey!=="neon")throw new HttpError(400,"FINANCE_NEON_REQUIRED","Finance is available only on Neon");return{tenantId:context.tenantId,principalId:context.principalId,planeKey:"neon" as const,correlationId:context.correlationId??context.requestId,permissionCodes:context.permissions.allowed};}
function financeHttpError(error:unknown):unknown{const value=error as {code?:string;message?:string;details?:Readonly<Record<string,unknown>>};if(!value?.code?.startsWith("FINANCE_"))return error;const status=value.code==="FINANCE_PERMISSION_DENIED"?403:value.code==="FINANCE_NOT_FOUND"?404:["FINANCE_EXPECTED_VERSION_CONFLICT","FINANCE_IDEMPOTENCY_CONFLICT","FINANCE_PERIOD_CLOSED"].includes(value.code)?409:400;return new HttpError(status,value.code,value.message??value.code,value.details);}
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new HttpError(400,"FINANCE_INVALID_REQUEST","JSON object required");return value as Record<string,unknown>;}
function record(value:unknown):Readonly<Record<string,unknown>>|undefined{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:undefined;}
function text(value:unknown):string|undefined{return typeof value==="string"&&value.trim()?value.trim():undefined;}
function required(value:unknown):string{const result=text(value);if(!result)throw new HttpError(400,"FINANCE_INVALID_REQUEST","Required value is missing");return result;}
function uuid(value:unknown):string{const result=required(value);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(result))throw new HttpError(400,"FINANCE_INVALID_UUID","UUID required");return result;}
function positiveInteger(value:unknown):number{const raw=Array.isArray(value)?value[0]:value,parsed=Number(typeof raw==="string"?raw.replace(/^"|"$/g,""):raw);if(!Number.isSafeInteger(parsed)||parsed<1)throw new HttpError(428,"FINANCE_EXPECTED_VERSION_REQUIRED","Positive version required");return parsed;}
function currency(value:unknown):string{const result=required(value).toUpperCase();if(!/^[A-Z]{3}$/.test(result))throw new HttpError(400,"FINANCE_INVALID_CURRENCY","ISO currency code required");return result;}
function sha256(value:unknown):string{const result=required(value).toLowerCase();if(!/^[a-f0-9]{64}$/.test(result))throw new HttpError(400,"FINANCE_INVALID_HASH","SHA-256 hash required");return result;}
function isoDate(value:unknown):string{const result=required(value),parsed=new Date(result);if(Number.isNaN(parsed.valueOf()))throw new HttpError(400,"FINANCE_INVALID_DATE","ISO date required");return parsed.toISOString();}
function periodStatus(value:unknown):"future"|"open"|"soft_close"|"hard_close"{const result=required(value);if(!["future","open","soft_close","hard_close"].includes(result))throw new HttpError(400,"FINANCE_INVALID_STATUS","Invalid period status");return result as "future"|"open"|"soft_close"|"hard_close";}
