import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

// Public, prospect-facing docs site. Content is staged from docs/ by
// tooling/scripts/docs/stage-content.mjs (see package.json "prebuild") —
// only files with `audience: public` frontmatter ever land here. The
// sidebar is manual and grows one approved section at a time; it is never
// autogenerated, so an unreviewed page can't surface in nav just by
// existing in src/content/docs/.
export default defineConfig({
  site: "https://docs.athyper.com",
  integrations: [
    starlight({
      title: "athyper Docs",
      description: "athyper business workflow documentation.",
      sidebar: [
        // Add entries here as workspace docs clear editorial review and
        // gain `audience: public` frontmatter. Empty until the first
        // promotion (see plan rollout step 2: organization-setup first).
      ],
    }),
  ],
});
