-- Whole-graph native bootstrap persistence of existing entity-facing AI declarations.
-- No AI editor, provider execution, learned-candidate promotion or mutation grants.
-- Existing scoped reads, schema guards, compiler resource qualification and review remain required.
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='metadata.entity_ai_profile'::regclass AND relrowsecurity AND relforcerowsecurity) THEN RAISE EXCEPTION 'NATIVE_BOOTSTRAP_RLS_REQUIRED: entity_ai_profile'; END IF; END $$;
GRANT INSERT(id,change_set_id,entity_id,tenant_id,created_by,enabled,description,aliases,context_kinds,search_profile_id,vocabulary_locale) ON metadata.entity_ai_profile TO athyper_product_command_app;
CREATE POLICY native_bootstrap_insert ON metadata.entity_ai_profile FOR INSERT TO athyper_product_command_app WITH CHECK(vocabulary_locale IS NULL AND tenant_id IS NULL AND created_by=master.current_principal_id_soft() AND entity_command_private.native_bootstrap_writable(change_set_id,entity_id));
CREATE POLICY native_bootstrap_insert_fence ON metadata.entity_ai_profile AS RESTRICTIVE FOR INSERT TO athyper_product_command_app WITH CHECK(vocabulary_locale IS NULL AND tenant_id IS NULL AND created_by=master.current_principal_id_soft() AND entity_command_private.native_bootstrap_writable(change_set_id,entity_id));
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='metadata.entity_ai_field'::regclass AND relrowsecurity AND relforcerowsecurity) THEN RAISE EXCEPTION 'NATIVE_BOOTSTRAP_RLS_REQUIRED: entity_ai_field'; END IF; END $$;
GRANT INSERT(id,change_set_id,entity_id,tenant_id,created_by,ai_profile_id,entity_field_id,position) ON metadata.entity_ai_field TO athyper_product_command_app;
CREATE POLICY native_bootstrap_insert ON metadata.entity_ai_field FOR INSERT TO athyper_product_command_app WITH CHECK(tenant_id IS NULL AND created_by=master.current_principal_id_soft() AND entity_command_private.native_bootstrap_writable(change_set_id,entity_id));
CREATE POLICY native_bootstrap_insert_fence ON metadata.entity_ai_field AS RESTRICTIVE FOR INSERT TO athyper_product_command_app WITH CHECK(tenant_id IS NULL AND created_by=master.current_principal_id_soft() AND entity_command_private.native_bootstrap_writable(change_set_id,entity_id));
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='metadata.entity_ai_binding'::regclass AND relrowsecurity AND relforcerowsecurity) THEN RAISE EXCEPTION 'NATIVE_BOOTSTRAP_RLS_REQUIRED: entity_ai_binding'; END IF; END $$;
GRANT INSERT(id,change_set_id,entity_id,tenant_id,created_by,ai_profile_id,binding_kind,contract_key,contract_version,required,operation_id,position) ON metadata.entity_ai_binding TO athyper_product_command_app;
CREATE POLICY native_bootstrap_insert ON metadata.entity_ai_binding FOR INSERT TO athyper_product_command_app WITH CHECK(tenant_id IS NULL AND created_by=master.current_principal_id_soft() AND entity_command_private.native_bootstrap_writable(change_set_id,entity_id));
CREATE POLICY native_bootstrap_insert_fence ON metadata.entity_ai_binding AS RESTRICTIVE FOR INSERT TO athyper_product_command_app WITH CHECK(tenant_id IS NULL AND created_by=master.current_principal_id_soft() AND entity_command_private.native_bootstrap_writable(change_set_id,entity_id));
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='metadata.entity_ai_reference'::regclass AND relrowsecurity AND relforcerowsecurity) THEN RAISE EXCEPTION 'NATIVE_BOOTSTRAP_RLS_REQUIRED: entity_ai_reference'; END IF; END $$;
GRANT INSERT(id,change_set_id,entity_id,tenant_id,created_by,ai_profile_id,reference_kind,relation_id,source_field_id,collection_contract_key,collection_contract_version,position) ON metadata.entity_ai_reference TO athyper_product_command_app;
CREATE POLICY native_bootstrap_insert ON metadata.entity_ai_reference FOR INSERT TO athyper_product_command_app WITH CHECK(tenant_id IS NULL AND created_by=master.current_principal_id_soft() AND entity_command_private.native_bootstrap_writable(change_set_id,entity_id));
CREATE POLICY native_bootstrap_insert_fence ON metadata.entity_ai_reference AS RESTRICTIVE FOR INSERT TO athyper_product_command_app WITH CHECK(tenant_id IS NULL AND created_by=master.current_principal_id_soft() AND entity_command_private.native_bootstrap_writable(change_set_id,entity_id));
