import type { AtlasContentBlock, AtlasFinishReason, AtlasModelMessage, AtlasModelProvider, AtlasProviderError, AtlasProviderEvent, AtlasProviderInvocation, AtlasProviderUsage } from "@athyper/server-contract-ai";

export const OPENAI_RESPONSES_ADAPTER_ID = "openai-responses";
export const OPENAI_RESPONSES_ADAPTER_VERSION = "1";
const DEFAULT_URL = "https://api.openai.com/v1/responses";
export interface OpenAiAdapterOptions { readonly fetch?: typeof fetch; readonly endpoint?: string; readonly timeoutMs?: number; readonly projectId?: string }

export class OpenAiModelProvider implements AtlasModelProvider {
  readonly providerId = "openai" as const; readonly adapterId = OPENAI_RESPONSES_ADAPTER_ID; readonly adapterVersion = OPENAI_RESPONSES_ADAPTER_VERSION;
  private readonly fetcher: typeof fetch; private readonly endpoint: string; private readonly timeoutMs: number; private readonly projectId?: string;
  constructor(options: OpenAiAdapterOptions = {}) { this.fetcher = options.fetch ?? fetch; this.endpoint = options.endpoint ?? DEFAULT_URL; this.timeoutMs = options.timeoutMs ?? 120_000; this.projectId = options.projectId?.trim() || undefined; }
  async *invoke(invocation: AtlasProviderInvocation): AsyncIterable<AtlasProviderEvent> {
    const mismatch = validate(invocation, this); if (mismatch) { yield { kind: "failed", error: mismatch }; return; }
    const scope = requestScope(invocation.signal, this.timeoutMs);
    try {
      const response = await this.fetcher(this.endpoint, { method: "POST", headers: { "content-type": "application/json", accept: "text/event-stream", authorization: `Bearer ${invocation.credential.secret}`, ...(this.projectId ? { "openai-project": this.projectId } : {}) }, body: JSON.stringify(buildBody(invocation)), signal: scope.signal });
      if (!response.ok) { yield { kind: "failed", error: httpError(response.status) }; return; }
      if (!response.body || !(response.headers.get("content-type") ?? "").toLowerCase().startsWith("text/event-stream")) { yield { kind: "failed", error: protocol("invalid_stream") }; return; }
      const calls = new Map<string, { callId: string; name: string; json: string }>(); let started = false; let terminal = false;
      for await (const frame of readSse(response.body)) {
        if (!frame.data || frame.data === "[DONE]") continue; let event: any; try { event = JSON.parse(frame.data); } catch { yield { kind: "failed", error: protocol("invalid_json") }; return; }
        if (event.type === "response.created") { const model = nonEmpty(event.response?.model); if (!model) { yield { kind: "failed", error: protocol("missing_model") }; return; } started = true; yield { kind: "response_started", providerRequestId: nonEmpty(event.response?.id) ?? nonEmpty(response.headers.get("x-request-id")), actualModelId: model }; }
        else if (event.type === "response.output_text.delta" && typeof event.delta === "string") yield { kind: "text_delta", text: event.delta };
        else if (event.type === "response.refusal.delta" && typeof event.delta === "string") yield { kind: "refusal", reasonCode: "provider_refusal" };
        else if (event.type === "response.output_item.added" && event.item?.type === "function_call") { const itemId = required(event.item.id ?? event.item.call_id); const call = { callId: required(event.item.call_id ?? event.item.id), name: required(event.item.name), json: typeof event.item.arguments === "string" ? event.item.arguments : "" }; calls.set(itemId, call); yield { kind: "tool_call_start", callId: call.callId, toolName: call.name }; }
        else if (event.type === "response.function_call_arguments.delta") { const itemId = required(event.item_id); const call = calls.get(itemId); if (!call || typeof event.delta !== "string") { yield { kind: "failed", error: protocol("orphan_tool_delta") }; return; } call.json += event.delta; yield { kind: "tool_call_input_delta", callId: call.callId, jsonFragment: event.delta }; }
        else if (event.type === "response.function_call_arguments.done") { const itemId = required(event.item_id); const call = calls.get(itemId); if (!call) { yield { kind: "failed", error: protocol("orphan_tool_completion") }; return; } const json = typeof event.arguments === "string" ? event.arguments : call.json; let args: Record<string, unknown>; try { args = JSON.parse(json || "{}"); } catch { yield { kind: "failed", error: protocol("invalid_tool_arguments") }; return; } yield { kind: "tool_call_complete", callId: call.callId, toolName: call.name, input: args }; calls.delete(itemId); }
        else if (event.type === "response.completed") { if (!started || event.response?.model !== invocation.binding.upstreamModelId) { yield { kind: "failed", error: protocol("actual_model_mismatch") }; return; } const usage = openAiUsage(event.response?.usage); if (usage) yield { kind: "usage", mode: "snapshot", final: true, usage }; terminal = true; yield { kind: "completed", reason: event.response?.output?.some((item: any) => item?.type === "function_call") ? "tool_call" : "stop" }; return; }
        else if (event.type === "response.incomplete") { const usage = openAiUsage(event.response?.usage); if (usage) yield { kind: "usage", mode: "snapshot", final: true, usage }; terminal = true; yield { kind: "completed", reason: incompleteReason(event.response?.incomplete_details?.reason) }; return; }
        else if (event.type === "response.failed" || event.type === "error") { terminal = true; yield { kind: "failed", error: providerFailure(event.error ?? event.response?.error) }; return; }
      }
      if (!terminal) yield { kind: "failed", error: protocol("stream_incomplete") };
    } catch (error) { if (scope.timedOut()) yield { kind: "failed", error: fail("timeout", "provider_timeout", true) }; else if (invocation.signal?.aborted || isAbort(error)) yield { kind: "cancelled" }; else yield { kind: "failed", error: fail("upstream_error", "provider_unavailable", true) }; }
    finally { scope.cleanup(); }
  }
}

/** Atlas supplies its own bounded history and explicitly disables provider storage. */
export function buildOpenAiResponsesRequest(invocation: AtlasProviderInvocation) { return buildBody(invocation); }
function buildBody(invocation: AtlasProviderInvocation) { return { model: invocation.binding.upstreamModelId, input: invocation.prompt.messages.flatMap(toOpenAiItems), max_output_tokens: invocation.prompt.maxOutputTokens, stream: true, store: false, safety_identifier: invocation.trace.safetyIdentifier, ...(invocation.prompt.tools?.length ? { tools: invocation.prompt.tools.map((tool) => ({ type: "function", name: tool.name, description: tool.description, parameters: tool.inputSchema, strict: true })) } : {}) }; }
function toOpenAiItems(message: AtlasModelMessage): unknown[] { const role = message.role === "system" ? "developer" : message.role; const text = message.content.filter((block): block is Extract<AtlasContentBlock, { type: "text" }> => block.type === "text"); const items: unknown[] = text.length ? [{ role, content: text.map((block) => ({ type: role === "assistant" ? "output_text" : "input_text", text: block.text })) }] : []; for (const block of message.content) { if (block.type === "tool_use") items.push({ type: "function_call", call_id: block.callId, name: block.toolName, arguments: JSON.stringify(block.input) }); else if (block.type === "tool_result") items.push({ type: "function_call_output", call_id: block.callId, output: JSON.stringify(block.result) }); } return items; }
function openAiUsage(value: any): AtlasProviderUsage | null { if (!value || typeof value !== "object") return null; const cached = finite(value.input_tokens_details?.cached_tokens); const reasoning = finite(value.output_tokens_details?.reasoning_tokens); const input = finite(value.input_tokens); const output = finite(value.output_tokens); return { inputTokens: input === undefined ? undefined : Math.max(0, input - (cached ?? 0)), outputTokens: output === undefined ? undefined : Math.max(0, output - (reasoning ?? 0)), cacheReadTokens: cached, cacheWriteTokens: finite(value.input_tokens_details?.cache_write_tokens), reasoningTokens: reasoning }; }
function incompleteReason(value: unknown): AtlasFinishReason { return value === "max_output_tokens" ? "length" : value === "content_filter" ? "content_filter" : "incomplete"; }
function providerFailure(error: any): AtlasProviderError { const code = nonEmpty(error?.code) ?? "provider_error"; if (code.includes("rate")) return fail("rate_limited", "rate_limited", true); if (code.includes("quota")) return fail("quota_exhausted", "quota_exhausted", false); if (code.includes("safety") || code.includes("content")) return fail("safety_block", "safety_block", false); return fail("upstream_error", code.slice(0, 100), true); }
function validate(invocation: AtlasProviderInvocation, adapter: OpenAiModelProvider): AtlasProviderError | null { const b = invocation.binding; if (b.providerId !== adapter.providerId || b.adapterId !== adapter.adapterId || b.adapterVersion !== adapter.adapterVersion || b.status !== "available" || !b.capabilities.streaming) return fail("invalid_request", "binding_adapter_mismatch", false); if (invocation.credential.ownerId !== b.credentialOwnerId || !invocation.credential.secret.trim()) return fail("authentication", "credential_binding_mismatch", false); if (!/^[a-f0-9]{64}$/.test(invocation.trace.safetyIdentifier)) return fail("invalid_request", "invalid_safety_identifier", false); return null; }
function httpError(status: number): AtlasProviderError { if (status === 401) return fail("authentication", "authentication_failed", false); if (status === 403) return fail("permission", "permission_denied", false); if (status === 429) return fail("rate_limited", "rate_limited", true); if (status >= 500) return fail("overloaded", "provider_overloaded", true); return fail("invalid_request", `provider_http_${status}`, false); }
function protocol(code: string): AtlasProviderError { return fail(code === "stream_incomplete" ? "stream_incomplete" : "protocol_error", code, false); }
function fail(errorClass: AtlasProviderError["errorClass"], code: string, retryable: boolean): AtlasProviderError { return { errorClass, code, safeMessage: "The Atlas provider request could not be completed.", retryable }; }
function required(value: unknown): string { const result = nonEmpty(value); if (!result) throw new Error("missing_provider_identifier"); return result; } function nonEmpty(value: unknown): string | null { return typeof value === "string" && value.trim() ? value : null; } function finite(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : undefined; }
async function* readSse(body: ReadableStream<Uint8Array>): AsyncGenerator<{ event: string; data: string }> { const reader = body.getReader(); const decoder = new TextDecoder(); let buffer = ""; try { while (true) { const read = await reader.read(); buffer += decoder.decode(read.value, { stream: !read.done }); const parts = buffer.split(/\r?\n\r?\n/); buffer = parts.pop() ?? ""; for (const part of parts) { const event = part.split(/\r?\n/).find((line) => line.startsWith("event:"))?.slice(6).trim() ?? ""; const data = part.split(/\r?\n/).filter((line) => line.startsWith("data:")).map((line) => line.slice(5).trimStart()).join("\n"); yield { event, data }; } if (read.done) break; } } finally { reader.releaseLock(); } }
function requestScope(parent: AbortSignal | undefined, timeoutMs: number) { const controller = new AbortController(); let timeout = false; const abort = () => controller.abort(parent?.reason); parent?.addEventListener("abort", abort, { once: true }); const timer = setTimeout(() => { timeout = true; controller.abort(); }, timeoutMs); return { signal: controller.signal, timedOut: () => timeout, cleanup: () => { clearTimeout(timer); parent?.removeEventListener("abort", abort); } }; }
function isAbort(error: unknown): boolean { return error instanceof DOMException && error.name === "AbortError"; }
