"use client";

import type { ExperienceSurface } from "@athyper/contract-platform-dashboard";
import { defaultExperienceSurface } from "@athyper/contract-platform-dashboard/defaults";
import { SEMANTIC_ICONS } from "@athyper/platform-icons";
import { PlatformHome } from "@athyper/platform-shell";
import { useApiClient,useExperienceNavigation,useSessionIdentity } from "@athyper/platform-shell-app-foundation";
import { useActivityCenterData } from "@athyper/platform-shell-activity-center-data";
import { BrowserExperienceSurface } from "@athyper/platform-shell-dashboard/client";
import { useWorkspaceModuleRelevance } from "@athyper/platform-shell-dashboard/module-relevance";
import { moduleBadgesFromItems,WorkspaceModuleTabs } from "@athyper/platform-shell-dashboard/workspace-navigation";
import type { ExperienceRuntimeRegistry } from "@athyper/platform-shell-dashboard";
import { useCallback,useMemo } from "react";
import { studioCatalogRoutes } from "@/lib/catalog-routes";

function AtlasWelcome(){const navigation=useExperienceNavigation(),props=useMemo(()=>homeProps(navigation),[navigation]);return <PlatformHome {...props}/>;}
const registry:ExperienceRuntimeRegistry={dataSources:{"catalog.summary":context=>({value:Number(context.entityCount??context.moduleCount??0),items:[]})},actions:{"catalog.navigate":input=>safe(input.path)},extensions:{"studio.atlas-welcome":AtlasWelcome,"studio.preview":()=> <p>Studio preview extension</p>},icons:SEMANTIC_ICONS,assets:{"brand:studio/composer":"/brand/studio-composer.webp"}};

export function StudioExperienceSurface({surfaceKey,workspaceCode,moduleCode,context}:Readonly<{surfaceKey:string;workspaceCode?:string;moduleCode?:string;context?:Readonly<Record<string,string>>}>){const navigation=useExperienceNavigation(),workspace=workspaceCode?navigation.find(item=>item.code===workspaceCode):undefined;if((workspaceCode&&!workspace)||(moduleCode&&!workspace?.modules.some(item=>item.code===moduleCode)))return <AccessUnavailable/>;return workspace?<StudioWorkspaceExperience surfaceKey={surfaceKey} workspaceCode={workspace.code} workspaceName={workspace.name} entitledModuleCodes={workspace.modules.map(item=>item.code)} activeModuleCode={moduleCode} context={context}/>:<ResolvedStudioSurface surfaceKey={surfaceKey} context={context}/>;}
function StudioWorkspaceExperience({surfaceKey,workspaceCode,workspaceName,entitledModuleCodes,activeModuleCode,context}:{readonly surfaceKey:string;readonly workspaceCode:string;readonly workspaceName:string;readonly entitledModuleCodes:readonly string[];readonly activeModuleCode?:string;readonly context?:Readonly<Record<string,string>>}){const route=studioCatalogRoutes.find(item=>item.code===workspaceCode),scope=useSessionIdentity().scope,relevance=useWorkspaceModuleRelevance("studio",`${scope?.tenantId??"unknown"}:${scope?.principalId??"unknown"}`,workspaceCode,entitledModuleCodes,activeModuleCode),activity=useActivityCenterData(),badges=useMemo(()=>route?moduleBadgesFromItems(route,activity.inbox??[]):{},[route,activity.inbox]);if(!route)return <AccessUnavailable/>;return <><WorkspaceModuleTabs workspace={route} workspaceName={workspaceName} orderedModuleCodes={relevance.orderedModuleCodes} pinnedModuleCodes={relevance.pinnedModuleCodes} activeModuleCode={activeModuleCode} badges={badges} onTogglePinned={relevance.togglePinned}/><ResolvedStudioSurface surfaceKey={surfaceKey} context={context} framedHeader visibleModuleCodes={entitledModuleCodes} orderedModuleCodes={relevance.orderedModuleCodes} pinnedModuleCodes={relevance.pinnedModuleCodes} badges={badges} badgesLoading={activity.loading===true} onTogglePinned={relevance.togglePinned}/></>;}
function ResolvedStudioSurface({surfaceKey,context,framedHeader=false,visibleModuleCodes,orderedModuleCodes=[],pinnedModuleCodes=[],badges={},badgesLoading=false,onTogglePinned}:{readonly surfaceKey:string;readonly context?:Readonly<Record<string,string>>;readonly framedHeader?:boolean;readonly visibleModuleCodes?:readonly string[];readonly orderedModuleCodes?:readonly string[];readonly pinnedModuleCodes?:readonly string[];readonly badges?:Readonly<Record<string,string>>;readonly badgesLoading?:boolean;readonly onTogglePinned?:(moduleCode:string)=>void}){const fallback=defaultExperienceSurface(surfaceKey,"studio"),transformSurface=useCallback((surface:ExperienceSurface):ExperienceSurface=>orderSurface(surface,visibleModuleCodes,orderedModuleCodes),[visibleModuleCodes,orderedModuleCodes]);if(!fallback)return <SurfaceUnavailable/>;return <BrowserExperienceSurface client={useApiClient()} surfaceKey={surfaceKey} registry={registry} fallback={fallback} context={context} framedHeader={framedHeader} hideHeader={surfaceKey==="studio.home"} transformSurface={transformSurface} modulePresentation={{pinnedModuleCodes,badges,badgesLoading,onTogglePinned}}/>;}
function homeProps(navigation:ReturnType<typeof useExperienceNavigation>){const entitled=new Map(navigation.map(item=>[item.code,item])),routes=studioCatalogRoutes.flatMap(workspace=>{const access=entitled.get(workspace.code);return access?[{workspace,access}]:[];});return{suggestions:["Review my priorities","Plan today’s work","Review pending approvals"],workspaces:routes.map(({workspace,access})=>({name:access.name,description:`Build and govern with ${access.modules.length} authorized modules.`,href:`/${workspace.routeSlug}`,status:"Available workspace",modules:access.modules.map(item=>item.name)})),quickActions:routes.flatMap(({workspace,access})=>access.modules.slice(0,1).flatMap(module=>{const route=workspace.modules.find(item=>item.code===module.code);return route?[{label:`Open ${module.name}`,description:`Continue work in ${access.name}`,href:`/${workspace.routeSlug}/${route.routeSlug}`}]:[]})).slice(0,4),searchItems:routes.flatMap(({workspace,access})=>[{title:access.name,description:"Open workspace overview",href:`/${workspace.routeSlug}`,category:"Workspace",keywords:[workspace.code]},...access.modules.flatMap(module=>{const route=workspace.modules.find(item=>item.code===module.code);return route?[{title:module.name,description:`Open ${access.name}`,href:`/${workspace.routeSlug}/${route.routeSlug}`,category:"Module",keywords:[module.code]}]:[];})]),citationRoutes:{}} as const;}
function orderSurface(surface:ExperienceSurface,visibleModuleCodes?:readonly string[],orderedModuleCodes:readonly string[]=[]):ExperienceSurface{if(!visibleModuleCodes)return surface;const visible=new Set(visibleModuleCodes),rank=new Map(orderedModuleCodes.map((code,index)=>[code,index])),blocks=surface.blocks.filter(block=>!block.id.startsWith("module.")||visible.has(block.id.slice(7))),fixed=blocks.filter(block=>!block.id.startsWith("module.")),modules=blocks.filter(block=>block.id.startsWith("module.")).sort((left,right)=>(rank.get(left.id.slice(7))??Number.MAX_SAFE_INTEGER)-(rank.get(right.id.slice(7))??Number.MAX_SAFE_INTEGER));return{...surface,blocks:[...fixed,...modules]};}
function AccessUnavailable(){return <section className="athyper-experience-state" role="alert"><h1>Access unavailable</h1><p>This route is outside your current workspace and module entitlements.</p><a href="/home">Return to Studio home</a></section>;}
function SurfaceUnavailable(){return <section className="athyper-experience-state" role="alert"><h1>Experience unavailable</h1><p>The governed experience surface is not registered.</p><a href="/home">Return to Studio home</a></section>;}
function safe(value:string|number|boolean|undefined){const path=typeof value==="string"?value:"/home";return /^\/[a-z0-9][a-z0-9/_-]*(?:\?[a-z0-9=&._-]+)?$/i.test(path)&&!path.includes("//")?path:"/home";}
