import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";

const root=resolve(import.meta.dirname,"../../.."),read=(path:string)=>readFile(resolve(root,path),"utf8");
test("P2 rollout controller is named, staged, measured, reversible, and deletion-free",async()=>{const[controller,observer,evaluator,cohorts,observations,status]=await Promise.all([read("db/scripts/manage-business-partner-360-rollout.ts"),read("db/scripts/record-business-partner-360-rollout-observation.ts"),read("packages/services/master-data/src/business-partner-360-release-gates.ts"),read("../docs/architecture/evidence/business-partner-360-rollout-cohorts.json"),read("../docs/architecture/evidence/business-partner-360-rollout-observations.json"),read("../docs/architecture/evidence/business-partner-360-rollout-current-status.json")]);for(const action of["enable-internal","promote-canary","promote-broad","rollback","retirement-check"])assert.match(controller,new RegExp(`"${action}"`));assert.doesNotMatch(controller,/action[^\n]*(?:delete|remove|retire)["']/i);const thresholdSource=`${controller}${observer}${evaluator}`.replaceAll("_","");for(const threshold of["60","1440","10080","100","1000","10000"])assert.ok(thresholdSource.includes(threshold));for(const gate of["P0_NOT_CLOSED","P1_NOT_RELEASE_READY"])assert.match(controller,new RegExp(gate));assert.match(observer,/P0 is not closed/);assert.match(observer,/P1 is not release ready/);assert.match(controller,/pg_advisory_xact_lock/);assert.match(observer,/Prometheus returned no finite sample/);const cohort=JSON.parse(cohorts),ledger=JSON.parse(observations),current=JSON.parse(status);assert.deepEqual(cohort.internal,["athyper"]);assert.deepEqual(cohort.canary,["technostat"]);assert.deepEqual(ledger.observations,[]);assert.equal(current.after.flag.rolloutPct,0);assert.deepEqual(current.after.overrides,[]);assert.equal(current.entry.internalEligible,false);assert.equal(current.deletionAvailable,false);});
test("P2 inventories every retained aggregate boundary and fails retirement closed",async()=>{const[inventoryText,retirementText,dashboard,evaluator]=await Promise.all([read("../docs/architecture/evidence/business-partner-360-legacy-consumer-inventory.json"),read("../docs/architecture/evidence/business-partner-360-retirement-evidence.json"),read("../stack/config/telemetry/provisioning/dashboards/json/business-partner-360.json"),read("packages/services/master-data/src/business-partner-360-release-gates.ts")]),inventory=JSON.parse(inventoryText),retirement=JSON.parse(retirementText);assert.equal(inventory.knownConsumerCount,inventory.surfaces.filter((item:any)=>item.kind==="consumer"&&item.status!=="migrated").length);for(const surface of inventory.surfaces)await access(resolve(root,"..",surface.path));assert.match(dashboard,/get-aggregate/);assert.equal(retirement.evidence.legacyCalls,-1);assert.equal(retirement.evidence.observationDays,0);assert.equal(retirement.evidence.telemetryRetentionDays,1);assert.equal(retirement.evidence.trafficEvidenceRef,null);assert.equal(retirement.evidence.knownConsumers,1);assert.equal(retirement.evidence.rollbackApproved,false);assert.deepEqual(retirement.evidence.ownerApprovals,[]);for(const reason of["LEGACY_TRAFFIC_PRESENT","KNOWN_CONSUMERS_REMAIN","OBSERVATION_WINDOW_INCOMPLETE","TELEMETRY_RETENTION_INSUFFICIENT","TRAFFIC_EVIDENCE_MISSING","ZERO_CALL_WINDOW_INVALID","ROLLBACK_NOT_APPROVED","OWNER_APPROVALS_INCOMPLETE"])assert.match(evaluator,new RegExp(reason));});
test("P2 operational controller remains aligned with the canonical release evaluator",async()=>{const[controller,observer,evaluator]=await Promise.all([read("db/scripts/manage-business-partner-360-rollout.ts"),read("db/scripts/record-business-partner-360-rollout-observation.ts"),read("packages/services/master-data/src/business-partner-360-release-gates.ts")]);for(const imported of["evaluateBusinessPartner360Approvals","evaluateBusinessPartner360Release","evaluateBusinessPartner360Retirement"])assert.match(controller,new RegExp(imported));for(const token of["500","750","75*1024","100*1024","0.01","0.05","60","1_000","10_000","30","OWNER_APPROVALS_INCOMPLETE"])assert.ok(`${observer}${evaluator}`.replaceAll(" ","").replaceAll("_","").includes(token.replaceAll("_","")),`rollout threshold drifted: ${token}`);});
