-- Inactive G6 surface migration. Apply only through the signed incremental-retirement runner.
DO $$ BEGIN IF EXISTS(SELECT 1 FROM document.business_partner_invitation WHERE business_partner_request_id IS NOT NULL) OR EXISTS(SELECT 1 FROM document.business_partner_invitation_recovery WHERE request_id IS NOT NULL) OR EXISTS(SELECT 1 FROM document.mesh_business_partner_acceptance_event WHERE business_partner_request_id IS NOT NULL) THEN RAISE EXCEPTION 'legacy request bindings remain'; END IF;END $$;
ALTER TABLE document.business_partner_invitation DROP COLUMN business_partner_request_id CASCADE;
ALTER TABLE document.business_partner_invitation_recovery DROP COLUMN request_id CASCADE;
ALTER TABLE document.mesh_business_partner_acceptance_event DROP COLUMN business_partner_request_id CASCADE;
DROP TABLE document.business_partner_request_contact_channel CASCADE;
DROP TABLE document.business_partner_request_contact_person CASCADE;
DROP TABLE document.business_partner_request_address CASCADE;
DROP TABLE document.business_partner_request_identifier CASCADE;
DROP TABLE document.business_partner_request_tax_registration CASCADE;
DROP TABLE document.business_partner_request_classification CASCADE;
DROP TABLE document.business_partner_request_certification CASCADE;
DROP TABLE document.business_partner_request_materialization_item CASCADE;
DROP TABLE document.business_partner_request_validation CASCADE;
DROP TABLE document.business_partner_request_evidence CASCADE;
DROP TABLE document.business_partner_request CASCADE;
DROP FUNCTION IF EXISTS document.command_backfill_business_partner_request_cases(uuid,text,bigint,text,uuid,text,uuid,bigint,text,text,uuid,uuid);
DROP FUNCTION IF EXISTS document.fn_business_partner_request_approvers(uuid,uuid,uuid,uuid);
DROP FUNCTION IF EXISTS document.trg_guard_business_partner_request_payload_boundary();
DROP FUNCTION IF EXISTS document.trg_guard_business_partner_request_extension();
DROP FUNCTION IF EXISTS document.trg_guard_business_partner_request();
DROP FUNCTION IF EXISTS document.trg_guard_business_partner_request_registration();
DROP FUNCTION IF EXISTS document.trg_guard_business_partner_request_evidence();
DO $$ BEGIN IF to_regclass('document.entity_case') IS NULL OR to_regclass('document.business_partner_request') IS NOT NULL THEN RAISE EXCEPTION 'request-family retirement invariant failed'; END IF;END $$;
