-- ============================================================================
-- event/00_bootstrap.sql
-- Pre-table schema types and sequences.
-- Generated from the live Neon database event schema. Do not hand-edit.
-- ============================================================================
