-- ============================================================================
-- event/02_pre_constraint.sql
-- No pre-constraint routines are required by the live schema.
-- Generated from the live Neon database event schema. Do not hand-edit.
-- ============================================================================
