import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {hash} from './named-role-review.mjs';import {createAuthenticatedOperationReview} from './authenticated-operation-review.mjs';
const origin='https://neon.dev.athyper.test';
async function setup(t){const dir=await mkdtemp(join(tmpdir(),'operation-review-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));const bytes=await readFile('governance/policy/reviews/business-partner-operation-workflow.dev.json','utf8'),packet=JSON.parse(bytes);await writeFile(join(dir,'packet.json'),bytes);await writeFile(join(dir,'nomination.json'),await readFile('governance/policy/reviews/business-partner-operation-reviewers.dev.json'));const reviewer=packet.reviewers[0];const session={tenantId:reviewer.homeTenantId,principalId:reviewer.principalId,plane:'neon',realmKey:'athyper',authEpoch:1,assurance:'elevated',acceptedCsrfTokens:['csrf']};const options={enabled:true,origin,packetPath:join(dir,'packet.json'),packetSha256:hash(bytes),nominationPath:join(dir,'nomination.json'),outputDirectory:join(dir,'output'),resolveSession:async()=>session,currentIdentity:async()=>({tenantId:session.tenantId,principalId:session.principalId,authEpoch:session.authEpoch})};return{dir,packet,session,options,handler:createAuthenticatedOperationReview(options)};}
const get=()=>new Request(origin+'/api/governance/operation-review');const body=p=>({packetRevision:p.packetRevision,submissionId:'10000000-0000-4000-8000-000000000001',confirmBusiness:true,confirmSecurity:true,decisions:[{operation:p.rows[0].operation,proposalSha256:p.rows[0].proposalSha256,decision:'approve',reason:'Synthetic test decision'}]});const post=(b,headers={})=>new Request(get(),{method:'POST',headers:{origin,'content-type':'application/json','x-csrf-token':'csrf',...headers},body:JSON.stringify(b)});
test('anonymous, non-reviewer, baseline writes and bad CSRF fail closed',async t=>{const s=await setup(t);s.options.resolveSession=async()=>undefined;assert.equal((await s.handler(get())).status,401);s.options.resolveSession=async()=>({...s.session,principalId:'other'});assert.equal((await s.handler(get())).status,403);s.options.resolveSession=async()=>s.session;s.session.assurance='baseline';assert.equal((await s.handler(get())).status,200);assert.equal((await s.handler(post(body(s.packet)))).status,403);s.session.assurance='elevated';assert.equal((await s.handler(post(body(s.packet),{'x-csrf-token':'wrong'}))).status,403);});
test('records explicit choices idempotently with no publication/grant authority',async t=>{const s=await setup(t),b=body(s.packet);assert.equal((await s.handler(post(b))).status,201);const r=await(await s.handler(post(b))).json();assert.equal(r.replayed,true);assert.equal(r.assessment.proposalReviewComplete,false);assert.equal(r.assessment.activationAuthorized,false);assert.equal((await s.handler(post({...b,submissionId:'20000000-0000-4000-8000-000000000002'}))).status,409);const stored=await readFile(join(s.dir,'output/state.json'),'utf8');assert(!stored.includes('csrf'));});
test('second reviewer rejection leaves proposal unresolved',async t=>{const s=await setup(t),b=body(s.packet);await s.handler(post(b));s.session.principalId=s.packet.reviewers[1].principalId;const result=await(await s.handler(post({...b,submissionId:'20000000-0000-4000-8000-000000000002',decisions:b.decisions.map(d=>({...d,decision:'reject'}))}))).json();assert.equal(result.assessment.rows[0].state,'rejected_or_conflicting');});
test('spoofed identity, duplicate rows, stale proposal and changed nomination are rejected',async t=>{const s=await setup(t),b=body(s.packet);assert.equal((await s.handler(post({...b,reviewerId:'catl.owner'}))).status,400);assert.equal((await s.handler(post({...b,decisions:[...b.decisions,...b.decisions]}))).status,400);assert.equal((await s.handler(post({...b,decisions:b.decisions.map(d=>({...d,proposalSha256:'stale'}))}))).status,400);await writeFile(s.options.nominationPath,'{}');assert.equal((await s.handler(get())).status,409);});
test('authority changes before commit do not save decisions',async t=>{const s=await setup(t);let calls=0;s.options.currentIdentity=async()=>({tenantId:s.session.tenantId,principalId:s.session.principalId,authEpoch:s.session.authEpoch,profileHash:++calls===1?'before':'after'});assert.equal((await s.handler(post(body(s.packet)))).status,409);});
