import {test} from 'node:test';
import assert from 'node:assert/strict';
import {prepareNamedRoleReview,assessNamedRoleReview,proposalHash} from './named-role-review.mjs';
const candidate={tenant_id:'tenant',tenant_code:'tenant',principal_id:'person',principal_code:'review-subject',principal_status:'active',group_id:'group',role_id:'role',role_code:'admin',scope_target_id:'scope',scope_entity_id:'org',scope_kind:'operating_organization',propagation_mode:'subtree',has_current_plane_membership:true,role_permission_codes:['neon.relationship.entity_case.decide','neon.relationship.business_partner.read']};
const source=()=>({grantsChanged:false,grantChanges:[],candidates:[structuredClone(candidate)]});
const setup=()=>{const inventory=source(),packet=prepareNamedRoleReview(inventory,'sha');packet.reviewers=[{id:'business-owner',name:'Business Owner',authorityReference:'user-nomination',domains:['business'],tenantIds:['tenant']},{id:'security-owner',name:'Security Owner',authorityReference:'user-nomination',domains:['security'],tenantIds:['tenant']}];const item=packet.items[0];item.proposal={decision:'approve_responsibilities',responsibilities:[{responsibility:'case_approver',capabilities:['neon.relationship.entity_case.decide'],scope:item.existingScope}],conditions:{mfa:'required',mfaRationale:'Approval requires step-up',makerMayApprove:false,approverMayApply:false,separationOfDuties:'Owning command checks maker/checker and applier',denyAndRevocationPrecedence:true,effectiveFrom:'2026-09-10T00:00:00Z',effectiveUntil:null,expiryPolicy:'no_expiry_reviewed',scopeCoverage:'current_and_future_descendants_reviewed'},grantChanges:[]};recordApprovals(packet);return{inventory,packet};};
function recordApprovals(packet){const i=packet.items[0],digest=proposalHash({candidateId:i.candidateId,sourceSha256:'sha',proposal:i.proposal});i.approvals=['business','security'].map(domain=>({domain,reviewerId:`${domain}-owner`,decision:'approve',reference:'review-record',approvedAt:'2026-09-10T00:00:00Z',proposalSha256:digest}));}
test('preparation never assigns stewards from admin names',()=>{const p=prepareNamedRoleReview(source(),'sha');assert.deepEqual(p.approvedAssignments,[]);assert.equal(p.items[0].proposal.decision,'pending');assert.ok(!JSON.stringify(p.items[0].candidateResponsibilities).includes('steward'));assert.equal(assessNamedRoleReview(source(),p,'sha').namedRoleReviewComplete,false);});
test('both nominated domains can approve an exact proposal without applying grants',()=>{const {inventory,packet}=setup();const r=assessNamedRoleReview(inventory,packet,'sha');assert.equal(r.namedRoleReviewComplete,true);assert.equal(r.approvedAssignments.length,1);assert.equal(r.activationEligible,false);assert.equal(r.applySupported,false);});
test('missing, unauthorized or wrong-tenant reviewers cannot approve',()=>{for(const change of ['missing','tenant','authority']){const {inventory,packet}=setup();if(change==='missing')packet.items[0].approvals.pop();else if(change==='tenant')packet.reviewers[1].tenantIds=['other'];else packet.reviewers[1].authorityReference=null;assert.equal(assessNamedRoleReview(inventory,packet,'sha').namedRoleReviewComplete,false);}});
test('editing proposal or refreshing inventory invalidates acceptance',()=>{const {inventory,packet}=setup();assert.equal(assessNamedRoleReview(inventory,packet,'new-sha').namedRoleReviewComplete,false);packet.items[0].proposal.conditions.effectiveFrom='2026-10-10T00:00:00Z';assert.equal(assessNamedRoleReview(inventory,packet,'sha').namedRoleReviewComplete,false);});
test('scoped grants cannot become tenant authority or gain capabilities',()=>{for(const change of ['scope','capability']){const {inventory,packet}=setup();const role=packet.items[0].proposal.responsibilities[0];if(change==='scope')role.scope={...role.scope,kind:'tenant',targetId:'tenant'};else role.capabilities.push('neon.relationship.entity_case.materialize');recordApprovals(packet);assert.equal(assessNamedRoleReview(inventory,packet,'sha').namedRoleReviewComplete,false);}});
test('critical MFA and separation of duties remain required even with recorded approvals',()=>{const {inventory,packet}=setup();packet.items[0].proposal.conditions.makerMayApprove=true;recordApprovals(packet);assert.ok(assessNamedRoleReview(inventory,packet,'sha').rows[0].gates.includes('critical_mfa_or_separation_missing'));});
test('legal entity never turns into company code automatically',()=>{const i=source();i.candidates[0].scope_kind='legal_entity';const p=prepareNamedRoleReview(i,'sha');assert.ok(p.items[0].flags.includes('legal_entity_is_not_company_code'));assert.equal(p.items[0].existingScope.kind,'legal_entity');});
test('misleading reader roles and cross-role conflicts are flagged',()=>{const i=source();i.candidates[0].role_code='business-partner-reader';i.candidates[0].role_permission_codes.push('neon.relationship.business_partner.update','neon.relationship.entity_case.create');const item=prepareNamedRoleReview(i,'sha').items[0];assert.ok(item.flags.includes('reader_name_includes_mutation_or_sensitive_access'));assert.ok(item.flags.includes('principal_has_requester_and_approver_candidates'));});
test('retain legacy decision requires rationale and both reviews, not an assignment',()=>{const {inventory,packet}=setup();packet.items[0].proposal={decision:'retain_legacy_only',rationale:'Target capability definition remains pending',responsibilities:[],grantChanges:[]};recordApprovals(packet);const r=assessNamedRoleReview(inventory,packet,'sha');assert.equal(r.namedRoleReviewComplete,true);assert.deepEqual(r.approvedAssignments,[]);});
test('missing or duplicate rows cannot yield completion',()=>{const {inventory,packet}=setup();packet.items=[];assert.equal(assessNamedRoleReview(inventory,packet,'sha').unresolvedRows,1);const j=setup();j.packet.items.push(j.packet.items[0]);assert.throws(()=>assessNamedRoleReview(j.inventory,j.packet,'sha'),/Duplicate/);});
