import {test} from 'node:test';
import assert from 'node:assert/strict';
import {prepareNamedRoleReview,assessNamedRoleReview} from './named-role-review.mjs';
import {recommendNamedRoles,recordBatchApproval,buildReviewBatches} from './named-role-recommendations.mjs';
const from=new Date(Date.now()+86400000).toISOString(),until=new Date(Date.now()+91*86400000).toISOString();
const base={tenant_id:'tenant',tenant_code:'tenant',principal_id:'person',principal_code:'requester',principal_status:'active',group_id:'group',group_code:'requesters',role_id:'role',role_code:'case-admin',scope_target_id:'scope',scope_entity_id:'org',scope_name:'Organization',scope_key:'organization:org',scope_kind:'operating_organization',propagation_mode:'subtree',has_current_plane_membership:true,role_permission_codes:['neon.relationship.entity_case.create','neon.relationship.entity_case.read','neon.relationship.entity_case.decide','neon.relationship.entity_case.materialize','neon.relationship.business_partner.update']};
function setup(candidates=[base,{...base,principal_id:'second',principal_code:'second',scope_target_id:'scope2',scope_entity_id:'org2'}]){const inventory={grantsChanged:false,grantChanges:[],candidates:structuredClone(candidates)};const draft=prepareNamedRoleReview(inventory,'sha');draft.reviewers=[{id:'reviewer',name:'Named reviewer',principalId:'reviewer-principal',authorityReference:'explicit nomination',domains:['business','security'],tenantIds:['tenant']}];return{inventory,packet:recommendNamedRoles(inventory,draft,'sha',{from,until})};}
const approval=packet=>({decision:'approve',domains:['business','security'],reviewerId:'reviewer',reference:'Explicit batch approval received',approvedAt:new Date().toISOString(),batchId:packet.batches[0].batchId,batchSha256:packet.batches[0].batchSha256});
test('every recommendation is complete apart from approval and retains unmapped permissions',()=>{const {inventory,packet}=setup();const r=assessNamedRoleReview(inventory,packet,'sha');assert.ok(r.rows.every(row=>row.gates.length===2&&row.gates.every(g=>g.endsWith('_approval_missing_or_stale'))));assert.ok(packet.items[0].proposal.retainedLegacyCapabilities.includes('neon.relationship.entity_case.decide'));assert.equal(packet.items[0].proposal.legacyGrantEffect,'unchanged');assert.equal(packet.items[0].proposal.conditions.activationRequired,true);});
test('equivalent batch lists every exact principal, scope and proposal revision',()=>{const {packet}=setup();assert.equal(packet.batches.length,1);assert.equal(packet.batches[0].members.length,2);assert.deepEqual(new Set(packet.batches[0].members.map(m=>m.scope.targetId)),new Set(['org','org2']));});
test('explicit batch approval resolves exactly its members without activating grants',()=>{const {inventory,packet}=setup();const reviewed=recordBatchApproval(inventory,packet,'sha',approval(packet));const r=assessNamedRoleReview(inventory,reviewed,'sha');assert.equal(r.unresolvedRows,0);assert.equal(r.approvedAssignments.length,2);assert.equal(r.activationEligible,false);assert.deepEqual(r.grantChanges,[]);assert.equal(packet.items[0].approvals.length,0);});
test('changing one member invalidates the whole approved batch',()=>{const {inventory,packet}=setup();const reviewed=recordBatchApproval(inventory,packet,'sha',approval(packet));reviewed.items[0].proposal.rationale+=' Changed.';assert.equal(assessNamedRoleReview(inventory,reviewed,'sha').unresolvedRows,2);assert.throws(()=>recordBatchApproval(inventory,{...packet,items:reviewed.items.map(i=>({...i,approvals:[]}))},'sha',approval(packet)),/Batch changed/);});
test('stale inventories and batch manifests cannot record approval',()=>{const {inventory,packet}=setup();assert.throws(()=>recordBatchApproval(inventory,packet,'different',approval(packet)),/Inventory changed/);assert.throws(()=>recordBatchApproval(inventory,packet,'sha',{...approval(packet),batchSha256:'stale'}),/Batch changed/);});
test('missing domains and wrong reviewers remain blocked',()=>{const {inventory,packet}=setup();assert.throws(()=>recordBatchApproval(inventory,packet,'sha',{...approval(packet),domains:['business']}),/Explicit/);assert.throws(()=>recordBatchApproval(inventory,packet,'sha',{...approval(packet),reviewerId:'unknown'}),/Reviewer/);});
test('approval cannot overwrite prior review evidence',()=>{const {inventory,packet}=setup();const reviewed=recordBatchApproval(inventory,packet,'sha',approval(packet));assert.throws(()=>recordBatchApproval(inventory,reviewed,'sha',approval(packet)),/Existing approval/);});
test('fixtures excluded from target keep every original grant',()=>{const {packet}=setup([{...base,role_code:'acceptance.bp.test',scope_key:'acceptance.bp.test'}]);const i=packet.items[0];assert.equal(i.proposal.decision,'exclude_from_target');assert.deepEqual(i.proposal.retainedLegacyCapabilities,[...base.role_permission_codes].sort());assert.equal(i.proposal.legacyGrantEffect,'unchanged');assert.equal(i.reviewMode,'individual_exception');});
test('legal entity and tenant legacy mutations never become company/steward roles',()=>{const {packet}=setup(['legal_entity','tenant'].map((kind,n)=>({...base,scope_kind:kind,scope_target_id:`scope${n}`,role_permission_codes:['neon.relationship.business_partner.update']})));assert.ok(packet.items.every(i=>i.proposal.decision==='retain_legacy_only'&&i.proposal.responsibilities.length===0));});
test('reviewer-as-subject must be separately acknowledged',()=>{const {inventory,packet}=setup([{...base,principal_id:'reviewer-principal'}]);assert.equal(packet.batches[0].reviewMode,'individual_exception');assert.throws(()=>recordBatchApproval(inventory,packet,'sha',approval(packet)),/acknowledgement/);const reviewed=recordBatchApproval(inventory,packet,'sha',{...approval(packet),selfReviewAcknowledged:true});assert.equal(assessNamedRoleReview(inventory,reviewed,'sha').unresolvedRows,0);reviewed.items[0].approvals.forEach(a=>delete a.selfReviewAcknowledged);assert.equal(assessNamedRoleReview(inventory,reviewed,'sha').unresolvedRows,1);});
test('missing capability disposition and expired assignment window cannot be approved',()=>{for(const kind of ['capability','window']){const {inventory,packet}=setup();if(kind==='capability')packet.items[0].proposal.retainedLegacyCapabilities=[];else packet.items[0].proposal.conditions.effectiveUntil='2000-01-01T00:00:00Z';packet.batches=buildReviewBatches(packet).sort((a,b)=>Number(b.members.some(m=>m.candidateId===packet.items[0].candidateId))-Number(a.members.some(m=>m.candidateId===packet.items[0].candidateId)));assert.throws(()=>recordBatchApproval(inventory,packet,'sha',approval(packet)),/conditions/);}});
