import type{VerifiedRequestContext}from"@athyper/server-contract-auth";import type{ContentServices}from"./content-service.js";import type{Application,RequestHandler,Response}from"express";import{ContentError,ContentQuotaExceededError}from"./errors.js";
import type{createContentResourceService}from"./content-resource-service.js";
export function registerContentRoutes(app:Application,o:{authenticate:RequestHandler;readContext:(response:Response)=>VerifiedRequestContext;content:ContentServices;resources?:ReturnType<typeof createContentResourceService>}){const route=(work:(req:any,c:VerifiedRequestContext)=>Promise<{status?:number;body?:unknown}>)=>async(req:any,res:Response,next:any)=>{try{const out=await work(req,o.readContext(res));if(out.status===204){res.status(204).end();return;}res.status(out.status??200).json(out.body);}catch(e){handle(e,res,next);}};
 app.get('/api/content/items',o.authenticate,route(async(r,c)=>({body:await o.content.browser.list({context:c,...optional(r.query,'kind','status','localeCode','cursor'),...(r.query.parentId!==undefined?{parentId:r.query.parentId==='null'?null:String(r.query.parentId)}:{}),limit:num(r.query.limit)})})));
 app.post('/api/content/items',o.authenticate,route(async(r,c)=>{const b=body(r);return{status:201,body:await o.content.editor.create({context:c,code:requiredString(b.code,'code'),title:requiredString(b.title,'title'),slug:requiredString(b.slug,'slug'),bodyJson:b.bodyJson,kind:string(b.kind),parentId:b.parentId===null?null:string(b.parentId),localeCode:string(b.localeCode),summary:b.summary===null?null:string(b.summary),metadata:object(b.metadata),bodyFormat:b.bodyFormat?String(b.bodyFormat)as any:undefined,changeSummary:string(b.changeSummary)})};}));
 app.get('/api/content/items/:id',o.authenticate,route(async(r,c)=>{const value=await o.content.browser.get({context:c,contentItemId:uuid(r.params.id)});if(!value)throw new ContentError(404,'CONTENT_NOT_FOUND','Content item was not found');return{body:value};}));
 app.patch('/api/content/items/:id',o.authenticate,route(async(r,c)=>({body:await o.content.editor.update({context:c,contentItemId:uuid(r.params.id),expectedRowVersion:requiredInt(body(r).expectedRowVersion),...body(r)})})));
 app.get('/api/content/items/:id/versions',o.authenticate,route(async(r,c)=>({body:await o.content.browser.versions({context:c,contentItemId:uuid(r.params.id)})})));
 app.get('/api/content/items/:id/versions/:versionId',o.authenticate,route(async(r,c)=>({body:await o.content.browser.version({context:c,contentItemId:uuid(r.params.id),versionId:uuid(r.params.versionId)})})));
 app.post('/api/content/items/:id/versions',o.authenticate,route(async(r,c)=>{const b=body(r);return{status:201,body:await o.content.editor.createVersion({context:c,contentItemId:uuid(r.params.id),expectedRowVersion:requiredInt(b.expectedRowVersion),bodyJson:b.bodyJson,bodyFormat:String(b.bodyFormat??'slate')as any,changeSummary:string(b.changeSummary)})};}));
 app.post('/api/content/items/:id/versions/:versionId/restore',o.authenticate,route(async(r,c)=>{const b=body(r);return{status:201,body:await o.content.editor.restoreVersion({context:c,contentItemId:uuid(r.params.id),versionId:uuid(r.params.versionId),expectedRowVersion:requiredInt(b.expectedRowVersion),changeSummary:string(b.changeSummary)})};}));
 for(const[to,path]of[['REVIEW','submit'],['PUBLISHED','publish'],['ARCHIVED','archive']]as const)app.post(`/api/content/items/:id/${path}`,o.authenticate,route(async(r,c)=>({body:await o.content.editor.transition({context:c,contentItemId:uuid(r.params.id),expectedRowVersion:requiredInt(body(r).expectedRowVersion),to})})));
 app.get('/api/content/items/:id/acl',o.authenticate,route(async(r,c)=>({body:await o.content.acl.list({context:c,contentItemId:uuid(r.params.id)})})));
 app.post('/api/content/items/:id/acl',o.authenticate,route(async(r,c)=>{const b=body(r);return{status:201,body:await o.content.acl.grant({context:c,contentItemId:uuid(r.params.id),subjectType:String(b.subjectType)as any,subjectId:string(b.subjectId),accessLevel:String(b.accessLevel)as any,expiresAt:string(b.expiresAt)})};}));
 app.delete('/api/content/items/:id/acl/:grantId',o.authenticate,route(async(r,c)=>({body:{revoked:await o.content.acl.revoke({context:c,contentItemId:uuid(r.params.id),grantId:uuid(r.params.grantId)})}})));
 app.get('/api/content/quota',o.authenticate,route(async(r,c)=>({body:await o.content.quota.usage({context:c,kind:string(r.query.kind)})})));
 if(o.content.search)app.get('/api/content/search',o.authenticate,route(async(r,c)=>({body:await o.content.search!.search({context:c,text:String(r.query.q??''),kind:string(r.query.kind),status:string(r.query.status)as any,localeCode:string(r.query.localeCode),page:num(r.query.page),pageSize:num(r.query.pageSize)})})));
 app.post('/api/content/items/:id/reindex',o.authenticate,route(async(r,c)=>{await o.content.reindex({context:c,contentItemId:uuid(r.params.id)});return{status:202,body:{accepted:true}};}));
 if(o.resources){
  app.get('/api/content/items/:id/links',o.authenticate,route(async(r,c)=>({body:await o.resources!.listLinks(c,uuid(r.params.id))})));
  app.post('/api/content/items/:id/links',o.authenticate,route(async(r,c)=>{const b=body(r);return{status:201,body:await o.resources!.createLink(c,uuid(r.params.id),{targetContentItemId:uuid(b.targetContentItemId),relationType:string(b.relationType),displayOrder:optionalInt(b.displayOrder),metadata:object(b.metadata)})};}));
  app.delete('/api/content/items/:id/links/:linkId',o.authenticate,route(async(r,c)=>{const deleted=await o.resources!.deleteLink(c,uuid(r.params.id),uuid(r.params.linkId));if(!deleted)throw new ContentError(404,'CONTENT_LINK_NOT_FOUND','Content link was not found');return{status:204};}));
  app.get('/api/content/items/:id/attachments',o.authenticate,route(async(r,c)=>({body:await o.resources!.listAttachments(c,uuid(r.params.id))})));
  app.post('/api/content/items/:id/attachments',o.authenticate,route(async(r,c)=>{const b=body(r);return{status:201,body:await o.resources!.linkAttachment(c,uuid(r.params.id),{attachmentId:uuid(b.attachmentId),linkKind:string(b.linkKind),displayOrder:optionalInt(b.displayOrder),metadata:object(b.metadata)})};}));
  app.delete('/api/content/items/:id/attachments/:attachmentId',o.authenticate,route(async(r,c)=>{const deleted=await o.resources!.unlinkAttachment(c,uuid(r.params.id),uuid(r.params.attachmentId));if(!deleted)throw new ContentError(404,'CONTENT_ATTACHMENT_NOT_FOUND','Content attachment was not found');return{status:204};}));
  app.get('/api/content/items/:id/attachments/:attachmentId/versions',o.authenticate,route(async(r,c)=>({body:await o.resources!.listAttachmentVersions(c,uuid(r.params.id),uuid(r.params.attachmentId))})));
 }
}
function handle(e:unknown,res:Response,next:(e?:unknown)=>void){if(e instanceof ContentQuotaExceededError)res.setHeader('Retry-After',String(e.retryAfterSeconds));if(e instanceof ContentError){res.status(e.status).type('application/problem+json').json({type:`https://athyper.dev/problems/${e.code.toLowerCase()}`,title:e.code,status:e.status,detail:e.message,code:e.code,...e.details});}else next(e);}function body(r:any):Record<string,any>{if(!r.body||typeof r.body!=='object'||Array.isArray(r.body))throw new ContentError(400,'INVALID_BODY','JSON object required');return r.body;}function uuid(v:unknown){const x=String(v??'');if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x))throw new ContentError(400,'INVALID_ID','UUID required');return x;}function num(v:unknown){if(v===undefined)return undefined;const n=Number(v);return Number.isInteger(n)?n:Number.NaN;}function optionalInt(v:unknown){if(v===undefined)return undefined;const n=Number(v);if(!Number.isInteger(n)||n<0)throw new ContentError(400,'INVALID_DISPLAY_ORDER','displayOrder must be a non-negative integer');return n;}function requiredInt(v:unknown){const n=Number(v);if(!Number.isInteger(n)||n<1)throw new ContentError(400,'INVALID_ROW_VERSION','expectedRowVersion is required');return n;}function requiredString(v:unknown,name:string){if(typeof v!=='string'||!v.trim())throw new ContentError(400,'INVALID_CONTENT_FIELD',`${name} is required`);return v;}function string(v:unknown){return typeof v==='string'?v:undefined;}function object(v:unknown){return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:undefined;}function optional(q:any,...keys:string[]){return Object.fromEntries(keys.filter(k=>typeof q[k]==='string').map(k=>[k,q[k]]));}
