import{sql,type Transaction}from"kysely";import type{ContentAttachment,ContentItemLink,ContentResourceRepository}from"./ports.js";
export type ContentResourceTransaction=Transaction<Record<string,never>>;
interface LinkRow{id:string;source_content_item_id:string;target_content_item_id:string;relation_type:string;display_order:number;metadata:Record<string,unknown>;created_at:Date|string;created_by:string;}
interface AttachmentRow{link_id:string;attachment_id:string;file_name:string;content_type:string|null;size_bytes:string|number|null;status:string;version_no:number;parent_attachment_id:string|null;series_id:string|null;link_kind:string;display_order:number;metadata:Record<string,unknown>;created_at:Date|string;}
export function createKyselyContentResourceRepository():ContentResourceRepository<ContentResourceTransaction>{return{
 async listLinks(c,itemId,tx){const r=await sql<LinkRow>`SELECT id,source_content_item_id,target_content_item_id,relation_type,display_order,metadata,created_at,created_by FROM document.content_item_link WHERE tenant_id=${c.tenantId}::uuid AND source_content_item_id=${itemId}::uuid ORDER BY display_order,created_at,id`.execute(tx);return r.rows.map(link);},
 async createLink(i,tx){const r=await sql<LinkRow>`INSERT INTO document.content_item_link(id,tenant_id,source_content_item_id,target_content_item_id,relation_type,display_order,metadata,created_by) VALUES(${i.id}::uuid,${i.context.tenantId}::uuid,${i.sourceContentItemId}::uuid,${i.targetContentItemId}::uuid,${i.relationType},${i.displayOrder},${JSON.stringify(i.metadata)}::jsonb,${i.context.principalId}::uuid) RETURNING id,source_content_item_id,target_content_item_id,relation_type,display_order,metadata,created_at,created_by`.execute(tx);return link(required(r.rows[0]));},
 async deleteLink(c,id,tx){const r=await sql`DELETE FROM document.content_item_link WHERE tenant_id=${c.tenantId}::uuid AND id=${id}::uuid`.execute(tx);return Number(r.numAffectedRows??0n)>0;},
 async listAttachments(c,itemId,tx){const r=await attachmentRows(sql<AttachmentRow>`SELECT l.id AS link_id,a.id AS attachment_id,a.file_name,a.content_type,a.size_bytes,a.status::text,a.version_no,a.parent_attachment_id,a.series_id,l.link_kind,l.display_order,l.metadata,l.created_at FROM document.attachment_link l JOIN document.attachment_series s ON s.tenant_id=l.tenant_id AND s.id=l.attachment_series_id JOIN document.attachment a ON a.tenant_id=l.tenant_id AND a.id=COALESCE(l.pinned_attachment_id,s.current_attachment_id) WHERE l.tenant_id=${c.tenantId}::uuid AND l.entity_type='content.item' AND l.entity_id=${itemId} AND a.is_active ORDER BY l.display_order,l.created_at,l.id`,tx);return r;},
 async linkAttachment(i,tx){const inserted=await sql<{link_id:string;attachment_series_id:string;link_kind:string;display_order:number;metadata:Record<string,unknown>;created_at:Date|string}>`INSERT INTO document.attachment_link(id,tenant_id,entity_type,entity_id,attachment_series_id,link_kind,display_order,metadata,created_by) SELECT ${i.id}::uuid,a.tenant_id,'content.item',${i.contentItemId},a.series_id,${i.linkKind},${i.displayOrder},${JSON.stringify(i.metadata)}::jsonb,${i.context.principalId}::uuid FROM document.attachment a WHERE a.tenant_id=${i.context.tenantId}::uuid AND a.id=${i.attachmentId}::uuid AND a.status='active' AND a.is_active RETURNING id AS link_id,attachment_series_id,link_kind,display_order,metadata,created_at`.execute(tx);const link=required(inserted.rows[0]);const rows=await attachmentRows(sql<AttachmentRow>`SELECT ${link.link_id} AS link_id,a.id AS attachment_id,a.file_name,a.content_type,a.size_bytes,a.status::text,a.version_no,a.parent_attachment_id,a.series_id,${link.link_kind} AS link_kind,${link.display_order}::integer AS display_order,${JSON.stringify(link.metadata)}::jsonb AS metadata,${link.created_at}::timestamptz AS created_at FROM document.attachment_series s JOIN document.attachment a ON a.tenant_id=s.tenant_id AND a.id=s.current_attachment_id WHERE s.tenant_id=${i.context.tenantId}::uuid AND s.id=${link.attachment_series_id}::uuid`,tx);return required(rows[0]);},
 async unlinkAttachment(c,itemId,attachmentId,tx){const r=await sql`DELETE FROM document.attachment_link l USING document.attachment a WHERE l.tenant_id=${c.tenantId}::uuid AND l.entity_type='content.item' AND l.entity_id=${itemId} AND a.tenant_id=l.tenant_id AND a.id=${attachmentId}::uuid AND a.series_id=l.attachment_series_id`.execute(tx);return Number(r.numAffectedRows??0n)>0;},
 async listAttachmentVersions(c,itemId,attachmentId,tx){return attachmentRows(sql<AttachmentRow>`SELECT l.id AS link_id,a.id AS attachment_id,a.file_name,a.content_type,a.size_bytes,a.status::text,a.version_no,a.parent_attachment_id,a.series_id,l.link_kind,l.display_order,l.metadata,l.created_at FROM document.attachment requested JOIN document.attachment_link l ON l.tenant_id=requested.tenant_id AND l.attachment_series_id=requested.series_id JOIN document.attachment a ON a.tenant_id=requested.tenant_id AND a.series_id=requested.series_id WHERE requested.tenant_id=${c.tenantId}::uuid AND requested.id=${attachmentId}::uuid AND l.entity_type='content.item' AND l.entity_id=${itemId} ORDER BY a.version_no DESC`,tx);}
};}
async function attachmentRows(query:any,tx:ContentResourceTransaction):Promise<ContentAttachment[]>{const r=await query.execute(tx)as{rows:AttachmentRow[]};return r.rows.map(attachment);}function link(r:LinkRow):ContentItemLink{return{id:r.id,sourceContentItemId:r.source_content_item_id,targetContentItemId:r.target_content_item_id,relationType:r.relation_type,displayOrder:r.display_order,metadata:r.metadata,createdAt:iso(r.created_at),createdBy:r.created_by};}function attachment(r:AttachmentRow):ContentAttachment{return{linkId:r.link_id,attachmentId:r.attachment_id,fileName:r.file_name,contentType:r.content_type,sizeBytes:r.size_bytes===null?null:Number(r.size_bytes),status:r.status,versionNo:r.version_no,parentAttachmentId:r.parent_attachment_id,seriesId:r.series_id,linkKind:r.link_kind,displayOrder:r.display_order,metadata:r.metadata,createdAt:iso(r.created_at)};}function required<T>(v:T|undefined):T{if(!v)throw new Error("Content resource persistence conflict");return v;}function iso(v:Date|string){return v instanceof Date?v.toISOString():new Date(v).toISOString();}
