import{sql}from"kysely";import type{ContentQuotaLedger}from"./ports.js";import type{ContentTransaction}from"./kysely-content-repository.js";import{ContentQuotaExceededError}from"./errors.js";
export function createKyselyContentQuotaLedger():ContentQuotaLedger<ContentTransaction>{return{
 async reserve(i,tx){const kind=`content.items.${i.kind}`;await sql`INSERT INTO document.content_quota_usage(tenant_id,quota_kind,created_by)VALUES(${i.context.tenantId}::uuid,${kind},${i.context.principalId}::uuid)ON CONFLICT DO NOTHING`.execute(tx);const u=await lock(i.context.tenantId,kind,tx);const existing=await sql`SELECT id FROM document.content_quota_reservation WHERE tenant_id=${i.context.tenantId}::uuid AND quota_kind=${kind} AND content_item_id=${i.contentItemId}::uuid`.execute(tx);if(existing.rows[0])return;if(num(u.used_items)+num(u.reserved_items)+1>i.limitItems)throw new ContentQuotaExceededError(i.limitItems,num(u.used_items),num(u.reserved_items),i.retryAfterSeconds);await sql`INSERT INTO document.content_quota_reservation(tenant_id,quota_kind,content_item_id,expires_at,created_by)VALUES(${i.context.tenantId}::uuid,${kind},${i.contentItemId}::uuid,${i.expiresAt}::timestamptz,${i.context.principalId}::uuid)`.execute(tx);await sql`UPDATE document.content_quota_usage SET reserved_items=reserved_items+1,updated_at=clock_timestamp(),updated_by=${i.context.principalId}::uuid WHERE tenant_id=${i.context.tenantId}::uuid AND quota_kind=${kind}`.execute(tx);},
 async commit(i,tx){const kind=`content.items.${i.kind}`;await lock(i.context.tenantId,kind,tx);const r=await sql<{id:string;status:string}>`SELECT id,status FROM document.content_quota_reservation WHERE tenant_id=${i.context.tenantId}::uuid AND quota_kind=${kind} AND content_item_id=${i.contentItemId}::uuid FOR UPDATE`.execute(tx);if(!r.rows[0]||r.rows[0].status==='committed')return;await sql`UPDATE document.content_quota_usage SET reserved_items=reserved_items-1,used_items=used_items+1,updated_at=clock_timestamp(),updated_by=${i.context.principalId}::uuid WHERE tenant_id=${i.context.tenantId}::uuid AND quota_kind=${kind}`.execute(tx);await sql`UPDATE document.content_quota_reservation SET status='committed',committed_at=clock_timestamp() WHERE id=${r.rows[0].id}::uuid`.execute(tx);},
 async release(i,tx){const kind=`content.items.${i.kind}`;await lock(i.context.tenantId,kind,tx);const r=await sql<{id:string;status:string}>`SELECT id,status FROM document.content_quota_reservation WHERE tenant_id=${i.context.tenantId}::uuid AND quota_kind=${kind} AND content_item_id=${i.contentItemId}::uuid FOR UPDATE`.execute(tx);if(!r.rows[0]||!['reserved','committed'].includes(r.rows[0].status))return;const column=r.rows[0].status==='reserved'?sql`reserved_items`:sql`used_items`;await sql`UPDATE document.content_quota_usage SET ${column}=${column}-1 WHERE tenant_id=${i.context.tenantId}::uuid AND quota_kind=${kind}`.execute(tx);await sql`UPDATE document.content_quota_reservation SET status='released',released_at=clock_timestamp()WHERE id=${r.rows[0].id}::uuid`.execute(tx);},
 async usage(i,tx){const r=await sql<{used_items:string;reserved_items:string}>`SELECT used_items,reserved_items FROM document.content_quota_usage WHERE tenant_id=${i.context.tenantId}::uuid AND quota_kind=${`content.items.${i.kind}`}`.execute(tx);return{usedItems:num(r.rows[0]?.used_items),reservedItems:num(r.rows[0]?.reserved_items)};},
 async expire(i,tx){const r=await sql<{quota_kind:string;count:string}>`WITH expired AS(UPDATE document.content_quota_reservation SET status='expired',released_at=clock_timestamp()WHERE id IN(SELECT id FROM document.content_quota_reservation WHERE tenant_id=${i.context.tenantId}::uuid AND status='reserved' AND expires_at<=clock_timestamp()ORDER BY expires_at FOR UPDATE SKIP LOCKED LIMIT ${i.limit})RETURNING quota_kind)SELECT quota_kind,count(*) count FROM expired GROUP BY quota_kind`.execute(tx);for(const row of r.rows)await sql`UPDATE document.content_quota_usage SET reserved_items=GREATEST(0,reserved_items-${num(row.count)})WHERE tenant_id=${i.context.tenantId}::uuid AND quota_kind=${row.quota_kind}`.execute(tx);return r.rows.reduce((n,x)=>n+num(x.count),0);},
 async reconcile(i,tx){const count=await sql<{count:string}>`SELECT count(*) count FROM document.content_item WHERE tenant_id=${i.context.tenantId}::uuid AND kind=${i.kind}`.execute(tx),value=num(count.rows[0]?.count),kind=`content.items.${i.kind}`;await sql`INSERT INTO document.content_quota_usage(tenant_id,quota_kind,used_items,created_by)VALUES(${i.context.tenantId}::uuid,${kind},${value},${i.context.principalId}::uuid)ON CONFLICT(tenant_id,quota_kind)DO UPDATE SET used_items=${value},updated_at=clock_timestamp(),updated_by=${i.context.principalId}::uuid`.execute(tx);return value;}
};}
async function lock(tenant:string,kind:string,tx:ContentTransaction){const r=await sql<{used_items:string;reserved_items:string}>`SELECT used_items,reserved_items FROM document.content_quota_usage WHERE tenant_id=${tenant}::uuid AND quota_kind=${kind} FOR UPDATE`.execute(tx);return r.rows[0]!;}function num(v:unknown){return Number(v??0);}
