import{sql,type Transaction}from"kysely";import type{ContentAttachment,ContentItemLink,ContentResourceRepository}from"./ports.js";
export type ContentResourceTransaction=Transaction<Record<string,never>>;
interface LinkRow{id:string;source_content_item_id:string;target_content_item_id:string;relation_type:string;display_order:number;metadata:Record<string,unknown>;created_at:Date|string;created_by:string;}
interface AttachmentRow{link_id:string;attachment_id:string;file_name:string;content_type:string|null;size_bytes:string|number|null;status:string;version_no:number;parent_attachment_id:string|null;series_id:string|null;link_kind:string;display_order:number;metadata:Record<string,unknown>;created_at:Date|string;}
export function createKyselyContentResourceRepository():ContentResourceRepository<ContentResourceTransaction>{return{
 async listLinks(c,itemId,tx){const r=await sql<LinkRow>`SELECT id,source_content_item_id,target_content_item_id,relation_type,display_order,metadata,created_at,created_by FROM document.content_item_link WHERE tenant_id=${c.tenantId}::uuid AND source_content_item_id=${itemId}::uuid ORDER BY display_order,created_at,id`.execute(tx);return r.rows.map(link);},
 async createLink(i,tx){const r=await sql<LinkRow>`INSERT INTO document.content_item_link(id,tenant_id,source_content_item_id,target_content_item_id,relation_type,display_order,metadata,created_by) VALUES(${i.id}::uuid,${i.context.tenantId}::uuid,${i.sourceContentItemId}::uuid,${i.targetContentItemId}::uuid,${i.relationType},${i.displayOrder},${JSON.stringify(i.metadata)}::jsonb,${i.context.principalId}::uuid) RETURNING id,source_content_item_id,target_content_item_id,relation_type,display_order,metadata,created_at,created_by`.execute(tx);return link(required(r.rows[0]));},
 async deleteLink(c,id,tx){const r=await sql`DELETE FROM document.content_item_link WHERE tenant_id=${c.tenantId}::uuid AND id=${id}::uuid`.execute(tx);return Number(r.numAffectedRows??0n)>0;},
 async listAttachments(c,itemId,tx){const r=await attachmentRows(sql<AttachmentRow>`SELECT l.id AS link_id,a.id AS attachment_id,a.file_name,a.content_type,a.size_bytes,a.status::text,a.version_no,a.parent_attachment_id,a.series_id,l.link_kind,l.display_order,l.metadata,l.created_at FROM document.attachment_link l JOIN document.attachment a ON a.tenant_id=l.tenant_id AND a.id=l.attachment_id WHERE l.tenant_id=${c.tenantId}::uuid AND l.entity_type='content.item' AND l.entity_id=${itemId} AND a.is_active ORDER BY l.display_order,l.created_at,l.id`,tx);return r;},
 async linkAttachment(i,tx){const r=await sql<AttachmentRow>`INSERT INTO document.attachment_link(id,tenant_id,entity_type,entity_id,attachment_id,attachment_series_id,link_kind,display_order,metadata,created_by) SELECT ${i.id}::uuid,a.tenant_id,'content.item',${i.contentItemId},a.id,a.series_id,${i.linkKind},${i.displayOrder},${JSON.stringify(i.metadata)}::jsonb,${i.context.principalId}::uuid FROM document.attachment a WHERE a.tenant_id=${i.context.tenantId}::uuid AND a.id=${i.attachmentId}::uuid AND a.status='active' AND a.is_active RETURNING id AS link_id,attachment_id,(SELECT file_name FROM document.attachment WHERE id=attachment_id) AS file_name,(SELECT content_type FROM document.attachment WHERE id=attachment_id) AS content_type,(SELECT size_bytes FROM document.attachment WHERE id=attachment_id) AS size_bytes,(SELECT status::text FROM document.attachment WHERE id=attachment_id) AS status,(SELECT version_no FROM document.attachment WHERE id=attachment_id) AS version_no,(SELECT parent_attachment_id FROM document.attachment WHERE id=attachment_id) AS parent_attachment_id,attachment_series_id AS series_id,link_kind,display_order,metadata,created_at`.execute(tx);return attachment(required(r.rows[0]));},
 async unlinkAttachment(c,itemId,attachmentId,tx){const r=await sql`DELETE FROM document.attachment_link WHERE tenant_id=${c.tenantId}::uuid AND entity_type='content.item' AND entity_id=${itemId} AND attachment_id=${attachmentId}::uuid`.execute(tx);return Number(r.numAffectedRows??0n)>0;},
 async listAttachmentVersions(c,itemId,attachmentId,tx){return attachmentRows(sql<AttachmentRow>`SELECT l.id AS link_id,a.id AS attachment_id,a.file_name,a.content_type,a.size_bytes,a.status::text,a.version_no,a.parent_attachment_id,a.series_id,l.link_kind,l.display_order,l.metadata,l.created_at FROM document.attachment_link l JOIN document.attachment root ON root.tenant_id=l.tenant_id AND root.id=l.attachment_id JOIN document.attachment a ON a.tenant_id=root.tenant_id AND (a.id=root.id OR (root.series_id IS NOT NULL AND a.series_id=root.series_id)) WHERE l.tenant_id=${c.tenantId}::uuid AND l.entity_type='content.item' AND l.entity_id=${itemId} AND l.attachment_id=${attachmentId}::uuid ORDER BY a.version_no DESC`,tx);}
};}
async function attachmentRows(query:any,tx:ContentResourceTransaction):Promise<ContentAttachment[]>{const r=await query.execute(tx)as{rows:AttachmentRow[]};return r.rows.map(attachment);}function link(r:LinkRow):ContentItemLink{return{id:r.id,sourceContentItemId:r.source_content_item_id,targetContentItemId:r.target_content_item_id,relationType:r.relation_type,displayOrder:r.display_order,metadata:r.metadata,createdAt:iso(r.created_at),createdBy:r.created_by};}function attachment(r:AttachmentRow):ContentAttachment{return{linkId:r.link_id,attachmentId:r.attachment_id,fileName:r.file_name,contentType:r.content_type,sizeBytes:r.size_bytes===null?null:Number(r.size_bytes),status:r.status,versionNo:r.version_no,parentAttachmentId:r.parent_attachment_id,seriesId:r.series_id,linkKind:r.link_kind,displayOrder:r.display_order,metadata:r.metadata,createdAt:iso(r.created_at)};}function required<T>(v:T|undefined):T{if(!v)throw new Error("Content resource persistence conflict");return v;}function iso(v:Date|string){return v instanceof Date?v.toISOString():new Date(v).toISOString();}
