import{sql,type Transaction}from"kysely";import type{ContentDocument,ContentItem,ContentVersion}from"@athyper/server-contract-content";import type{ContentRepository}from"./ports.js";
export type ContentTransaction=Transaction<Record<string,never>>;type Row=Record<string,unknown>;
export function createKyselyContentRepository():ContentRepository<ContentTransaction>{return{
 async list(i,tx){const result=await sql<Row>`SELECT ci.* FROM document.content_item ci WHERE ci.tenant_id=${i.context.tenantId}::uuid AND (${i.kind??null}::text IS NULL OR ci.kind=${i.kind??null}) AND (${i.status??null}::text IS NULL OR ci.status=${i.status??null}) AND (${i.localeCode??null}::text IS NULL OR ci.locale_code=${i.localeCode??null}) AND (${i.parentId===undefined?"unset":i.parentId??"root"}='unset' OR (${i.parentId??null}::uuid IS NULL AND ci.parent_id IS NULL) OR ci.parent_id=${i.parentId??null}::uuid) AND (${i.cursor??null}::uuid IS NULL OR ci.id<${i.cursor??null}::uuid) ORDER BY ci.id DESC LIMIT ${i.limit+1}`.execute(tx);const rows=result.rows,more=rows.length>i.limit,items=rows.slice(0,i.limit).map(item);return{items,...(more?{nextCursor:String(rows[i.limit-1]?.["id"])}:{})};},
 async get(c,id,tx){const result=await sql<Row>`SELECT ci.*,${c.planeKey}::text plane_key,v.id version_id,v.content_item_id,v.version,v.body_json,v.body_format,v.change_summary,v.checksum,v.created_at version_created_at,v.created_by version_created_by FROM document.content_item ci LEFT JOIN snapshot.content_item_version v ON v.tenant_id=ci.tenant_id AND v.id=ci.current_version_id WHERE ci.tenant_id=${c.tenantId}::uuid AND ci.id=${id}::uuid`.execute(tx);return result.rows[0]?document(result.rows[0]):null;},
 async create(i,tx){await sql`INSERT INTO document.content_item(id,tenant_id,code,title,kind,parent_id,locale_code,slug,summary,metadata,status,created_by)VALUES(${i.id}::uuid,${i.context.tenantId}::uuid,${i.code},${i.title},${i.kind},${i.parentId}::uuid,${i.localeCode},${i.slug},${i.summary},${JSON.stringify(i.metadata)}::jsonb,'DRAFT',${i.context.principalId}::uuid)`.execute(tx);await sql`INSERT INTO snapshot.content_item_version(id,tenant_id,content_item_id,version,body_json,body_format,change_summary,checksum,created_by)VALUES(${i.versionId}::uuid,${i.context.tenantId}::uuid,${i.id}::uuid,1,${JSON.stringify(i.bodyJson)}::jsonb,${i.bodyFormat},${i.changeSummary},${i.checksum},${i.context.principalId}::uuid)`.execute(tx);await sql`UPDATE document.content_item SET current_version_id=${i.versionId}::uuid WHERE tenant_id=${i.context.tenantId}::uuid AND id=${i.id}::uuid`.execute(tx);return required(await this.get(i.context,i.id,tx));},
 async update(i,tx){const sets:unknown[]=[];if(i.title!==undefined)sets.push(sql`title=${i.title}`);if(i.slug!==undefined)sets.push(sql`slug=${i.slug}`);if(i.summary!==undefined)sets.push(sql`summary=${i.summary}`);if(i.metadata!==undefined)sets.push(sql`metadata=${JSON.stringify(i.metadata)}::jsonb`);if(!sets.length)return(await this.get(i.context,i.id,tx))?.item??null;const result=await sql<Row>`UPDATE document.content_item SET ${sql.join(sets,sql`,`)},row_version=row_version+1,updated_at=clock_timestamp(),updated_by=${i.context.principalId}::uuid WHERE tenant_id=${i.context.tenantId}::uuid AND id=${i.id}::uuid AND row_version=${i.expectedRowVersion} RETURNING *`.execute(tx);return result.rows[0]?item(result.rows[0]):null;},
 async appendVersion(i,tx){const locked=await sql<Row>`SELECT row_version,COALESCE((SELECT max(version) FROM snapshot.content_item_version WHERE tenant_id=${i.context.tenantId}::uuid AND content_item_id=${i.id}::uuid),0) next_version FROM document.content_item WHERE tenant_id=${i.context.tenantId}::uuid AND id=${i.id}::uuid FOR UPDATE`.execute(tx);if(Number(locked.rows[0]?.["row_version"])!==i.expectedRowVersion)return null;const existing=await sql<Row>`SELECT id FROM snapshot.content_item_version WHERE tenant_id=${i.context.tenantId}::uuid AND content_item_id=${i.id}::uuid AND checksum=${i.checksum}`.execute(tx);const versionId=String(existing.rows[0]?.["id"]??i.versionId);if(!existing.rows[0])await sql`INSERT INTO snapshot.content_item_version(id,tenant_id,content_item_id,version,body_json,body_format,change_summary,checksum,created_by)VALUES(${i.versionId}::uuid,${i.context.tenantId}::uuid,${i.id}::uuid,${Number(locked.rows[0]?.["next_version"]??0)+1},${JSON.stringify(i.bodyJson)}::jsonb,${i.bodyFormat},${i.changeSummary},${i.checksum},${i.context.principalId}::uuid)`.execute(tx);await sql`UPDATE document.content_item SET current_version_id=${versionId}::uuid,row_version=row_version+1,updated_at=clock_timestamp(),updated_by=${i.context.principalId}::uuid WHERE tenant_id=${i.context.tenantId}::uuid AND id=${i.id}::uuid`.execute(tx);return required(await this.get(i.context,i.id,tx));},
 async version(c,itemId,versionId,tx){const r=await sql<Row>`SELECT * FROM snapshot.content_item_version WHERE tenant_id=${c.tenantId}::uuid AND content_item_id=${itemId}::uuid AND id=${versionId}::uuid`.execute(tx);return r.rows[0]?version(r.rows[0]):null;},
 async versions(c,itemId,tx){const r=await sql<Row>`SELECT * FROM snapshot.content_item_version WHERE tenant_id=${c.tenantId}::uuid AND content_item_id=${itemId}::uuid ORDER BY version DESC`.execute(tx);return r.rows.map(version);},
 async transition(i,tx){const r=await sql<Row>`UPDATE document.content_item SET status=${i.to},status_changed_at=clock_timestamp(),status_changed_by=${i.context.principalId}::uuid,row_version=row_version+1,updated_at=clock_timestamp(),updated_by=${i.context.principalId}::uuid WHERE tenant_id=${i.context.tenantId}::uuid AND id=${i.id}::uuid AND row_version=${i.expectedRowVersion} AND status IN (${sql.join(i.from)}) RETURNING *`.execute(tx);return r.rows[0]?item(r.rows[0]):null;}
};}
function item(r:Row):ContentItem{return{id:String(r["id"]),tenantId:String(r["tenant_id"]),code:String(r["code"]),title:String(r["title"]),kind:String(r["kind"]),parentId:r["parent_id"]?String(r["parent_id"]):null,localeCode:String(r["locale_code"]),slug:String(r["slug"]),summary:r["summary"]?String(r["summary"]):null,currentVersionId:r["current_version_id"]?String(r["current_version_id"]):null,metadata:object(r["metadata"]),status:String(r["status"])as ContentItem["status"],rowVersion:Number(r["row_version"]??1),createdAt:date(r["created_at"]),updatedAt:r["updated_at"]?date(r["updated_at"]):null};}
function version(r:Row):ContentVersion{return{id:String(r["id"]??r["version_id"]),contentItemId:String(r["content_item_id"]),version:Number(r["version"]),bodyJson:r["body_json"],bodyFormat:String(r["body_format"])as ContentVersion["bodyFormat"],changeSummary:r["change_summary"]?String(r["change_summary"]):null,checksum:String(r["checksum"]),createdAt:date(r["created_at"]??r["version_created_at"]),createdBy:String(r["created_by"]??r["version_created_by"])};}
function document(r:Row):ContentDocument{return{planeKey:String(r["plane_key"]??"unknown"),item:item(r),currentVersion:r["version_id"]?version(r):null};}function object(v:unknown){return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};}function date(v:unknown){return v instanceof Date?v.toISOString():String(v);}function required<T>(v:T|null):T{if(!v)throw new Error("Content item not found after write");return v;}
