import type { SetupWorkspaceContract } from "@athyper/runtime-contracts";

export const FINANCE_SETUP_WORKSPACE = {
  schemaVersion: "1.0",
  code: "finance-setup",
  workspaceCode: "FIN",
  workspaceSlug: "finance",
  label: "Finance Setup",
  description: "Company accounting, payment, treasury, tax and certification setup.",
  basePath: "/finance/setup",
  contributingModuleCodes: ["FND", "ACC", "PAY", "TREASURY"],
  scopePolicies: [
    { type: "tenant", routeSegment: "tenant", selectionMode: "explicit", required: false },
    { type: "legal_entity", routeSegment: "legal-entity", selectionMode: "explicit", required: false },
    { type: "company_code", routeSegment: "company", selectionMode: "automatic_single", required: true },
    { type: "company_book", routeSegment: "company-book", selectionMode: "fixed", required: false },
  ],
  domains: [
    {
      code: "foundation",
      routeSegment: "foundation",
      label: "Foundation",
      description: "Organization, accounts, books and fiscal calendar",
      iconKey: "building",
      order: 10,
      ownerModuleCode: "ACC",
      contributingModuleCodes: ["FND"],
      requiredModuleCodes: ["ACC"],
      requiredPermissions: ["finance.setup.view"],
      supportedScopeTypes: ["company_code"],
      sections: [
        { code: "organization", routeSegment: "organization", label: "Organization & Currency", order: 10 },
        { code: "accounts", routeSegment: "accounts", label: "Chart of Accounts & GL Accounts", order: 20 },
        { code: "books", routeSegment: "books", label: "Books & Ledgers", order: 30 },
        { code: "calendar", routeSegment: "calendar", label: "Fiscal Calendar & Periods", order: 40 },
      ],
    },
    {
      code: "currency-fx",
      routeSegment: "currency-fx",
      label: "Currency & FX",
      description: "Policies, rates, imports and revaluation",
      iconKey: "coins",
      order: 20,
      ownerModuleCode: "TREASURY",
      contributingModuleCodes: ["ACC"],
      requiredModuleCodes: ["TREASURY"],
      requiredPermissions: ["finance.setup.view"],
      supportedScopeTypes: ["tenant", "company_code", "company_book"],
    },
    {
      code: "tax",
      routeSegment: "tax",
      label: "Tax",
      description: "Registrations, determination and posting coverage",
      iconKey: "receipt-text",
      order: 30,
      ownerModuleCode: "ACC",
      contributingModuleCodes: [],
      requiredModuleCodes: ["ACC"],
      requiredPermissions: ["finance.setup.view"],
      supportedScopeTypes: ["tenant", "company_code"],
    },
    {
      code: "payments",
      routeSegment: "payments",
      label: "Payments",
      description: "Payment policy, routing and settlement",
      iconKey: "circle-dollar",
      order: 40,
      ownerModuleCode: "PAY",
      contributingModuleCodes: ["ACC"],
      requiredModuleCodes: ["PAY"],
      requiredPermissions: ["finance.setup.view"],
      supportedScopeTypes: ["tenant", "company_code"],
    },
    {
      code: "banking",
      routeSegment: "banking",
      label: "Banking",
      description: "House banks, interfaces and reconciliation",
      iconKey: "landmark",
      order: 50,
      ownerModuleCode: "TREASURY",
      contributingModuleCodes: ["PAY"],
      requiredModuleCodes: ["TREASURY"],
      requiredPermissions: ["finance.setup.view"],
      supportedScopeTypes: ["company_code"],
    },
    {
      code: "certification",
      routeSegment: "certification",
      label: "Certification",
      description: "Readiness checks and rollout decision",
      iconKey: "shield-check",
      order: 60,
      ownerModuleCode: "ACC",
      contributingModuleCodes: ["PAY", "TREASURY"],
      requiredModuleCodes: ["ACC"],
      requiredPermissions: ["finance.setup.view"],
      supportedScopeTypes: ["company_code"],
      anchor: "certification-readiness",
    },
  ],
  overview: {
    title: "Setup overview",
    description: "Readiness and configuration status across Finance modules.",
    layout: "cards",
    showDomainProgress: true,
    showAttention: true,
    showRecentActivity: false,
    certificationEnabled: true,
  },
  capabilities: {
    readiness: true,
    certification: true,
    issues: true,
    activity: true,
    search: false,
    export: false,
  },
} as const satisfies SetupWorkspaceContract;
