import type { FinanceActor, TaxCalculationLine, TaxCalculationRepository, TaxCreditCoordinate, TaxCreditMovement, TaxCreditMovementCommand, TaxCreditRepository } from "@athyper/server-contract-finance";
import { sql, type Transaction } from "kysely";

type DB = Record<string, never>; type Tx = Transaction<DB>; type Row = Record<string, unknown>;

export class KyselyTaxCalculationRepository implements TaxCalculationRepository<Tx> {
  async append(actor: FinanceActor, line: TaxCalculationLine, tx: Tx): Promise<TaxCalculationLine> { const c = line.coordinates, s = line.source; const row = (await sql<Row>`INSERT INTO ledger.tax_calculation(id,tenant_id,company_code_id,ledger_book_id,fiscal_period_id,source_entity_type,source_entity_id,source_line_id,jurisdiction_id,tax_type_id,tax_group_id,tax_rate_schedule_id,component_code,tax_direction,tax_treatment,rate_kind,rate_value,calculation_basis_code,taxable_base_amount,tax_amount,rounding_adjustment,recoverability,recoverable_amount,nonrecoverable_amount,currency_code,base_currency_amount,exchange_rate,rule_snapshot,rate_snapshot,basis_snapshot,evidence_hash,reverses_calculation_id,idempotency_key,posted_at,posted_by,created_by) VALUES(${line.id}::uuid,${actor.tenantId}::uuid,${c.companyCodeId}::uuid,${c.ledgerBookId}::uuid,${c.fiscalPeriodId}::uuid,${s.sourceType},${s.sourceId}::uuid,${s.sourceLineId ?? null}::uuid,${line.jurisdictionId}::uuid,${line.taxTypeId}::uuid,${line.taxGroupId}::uuid,${line.taxRateScheduleId}::uuid,${line.componentCode},${line.taxDirection.toLowerCase()},${line.taxTreatment.toLowerCase()},${line.rateKind},${line.rateValue}::numeric,${line.calculationBasisCode},${line.taxableBaseAmount}::numeric,${line.taxAmount}::numeric,${line.roundingAdjustment}::numeric,${line.recoverability},${line.recoverableAmount}::numeric,${line.nonrecoverableAmount}::numeric,${c.currencyCode},${line.baseCurrencyAmount}::numeric,${line.exchangeRate}::numeric,${JSON.stringify(line.ruleSnapshot)}::jsonb,${JSON.stringify(line.rateSnapshot)}::jsonb,${JSON.stringify(line.basisSnapshot)}::jsonb,${line.evidenceHash},${line.reversesCalculationId ?? null}::uuid,${line.idempotencyKey},${line.postedAt}::timestamptz,${actor.principalId}::uuid,${actor.principalId}::uuid) RETURNING *`.execute(tx)).rows[0]; if (!row) throw new Error("FINANCE_TAX_APPEND_FAILED"); return mapCalculation(row); }
  async get(actor: FinanceActor, id: string, tx: Tx) { const row = (await sql<Row>`SELECT * FROM ledger.tax_calculation WHERE tenant_id=${actor.tenantId}::uuid AND id=${id}::uuid`.execute(tx)).rows[0]; return row ? mapCalculation(row) : undefined; }
  async getCalculation(actor: FinanceActor, id: string, tx: Tx) { return this.get(actor, id, tx); }
  async findReversal(actor: FinanceActor, originalId: string, tx: Tx) { const row = (await sql<Row>`SELECT * FROM ledger.tax_calculation WHERE tenant_id=${actor.tenantId}::uuid AND reverses_calculation_id=${originalId}::uuid LIMIT 1`.execute(tx)).rows[0]; return row ? mapCalculation(row) : undefined; }
}

export class KyselyTaxCreditRepository implements TaxCreditRepository<Tx> {
  async append(command: TaxCreditMovementCommand, tx: Tx): Promise<TaxCreditMovement> { const p = command.payload; const row = (await sql<Row>`INSERT INTO ledger.tax_credit_movement(id,tenant_id,company_code_id,ledger_book_id,fiscal_period_id,jurisdiction_id,tax_type_id,tax_bucket,movement_type,amount,currency_code,source_tax_calculation_id,reverses_movement_id,idempotency_key,reason,created_by) VALUES(${command.commandId}::uuid,${command.actor.tenantId}::uuid,${p.companyCodeId}::uuid,${p.ledgerBookId}::uuid,${p.fiscalPeriodId}::uuid,${p.jurisdictionId}::uuid,${p.taxTypeId}::uuid,${p.taxBucket},${p.movementType},${p.amount}::numeric,${p.currencyCode},${p.sourceTaxCalculationId ?? null}::uuid,${p.reversesMovementId ?? null}::uuid,${command.idempotencyKey},${p.reason ?? null},${command.actor.principalId}::uuid) RETURNING *`.execute(tx)).rows[0]; if (!row) throw new Error("FINANCE_TAX_CREDIT_APPEND_FAILED"); return mapMovement(row); }
  async get(actor: FinanceActor, id: string, tx: Tx) { const row = (await sql<Row>`SELECT * FROM ledger.tax_credit_movement WHERE tenant_id=${actor.tenantId}::uuid AND id=${id}::uuid`.execute(tx)).rows[0]; return row ? mapMovement(row) : undefined; }
  async findReversal(actor: FinanceActor, originalId: string, tx: Tx) { const row = (await sql<Row>`SELECT * FROM ledger.tax_credit_movement WHERE tenant_id=${actor.tenantId}::uuid AND reverses_movement_id=${originalId}::uuid LIMIT 1`.execute(tx)).rows[0]; return row ? mapMovement(row) : undefined; }
  async listForSource(actor: FinanceActor, sourceId: string, tx: Tx) { await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`${actor.tenantId}:tax-credit:${sourceId}`},0))`.execute(tx); return (await sql<Row>`SELECT * FROM ledger.tax_credit_movement WHERE tenant_id=${actor.tenantId}::uuid AND source_tax_calculation_id=${sourceId}::uuid ORDER BY created_at,id`.execute(tx)).rows.map(mapMovement); }
  async list(actor: FinanceActor, coordinate: TaxCreditCoordinate, asOf: string, tx: Tx) { return (await sql<Row>`SELECT * FROM ledger.tax_credit_movement WHERE tenant_id=${actor.tenantId}::uuid AND company_code_id=${coordinate.companyCodeId}::uuid AND ledger_book_id=${coordinate.ledgerBookId}::uuid AND jurisdiction_id=${coordinate.jurisdictionId}::uuid AND tax_type_id=${coordinate.taxTypeId}::uuid AND tax_bucket=${coordinate.taxBucket} AND currency_code=${coordinate.currencyCode} AND created_at<=${asOf}::timestamptz ORDER BY created_at,id`.execute(tx)).rows.map(mapMovement); }
}

function mapCalculation(r: Row): TaxCalculationLine { const basis = obj(r["basis_snapshot"]); const source = obj(basis["source"]); return { id: String(r["id"]), coordinates: { companyCodeId: String(r["company_code_id"]), ledgerBookId: String(r["ledger_book_id"]), fiscalPeriodId: String(r["fiscal_period_id"]), currencyCode: String(r["currency_code"]).trim() }, source: { sourceType: String(r["source_entity_type"]), sourceId: String(r["source_entity_id"]), version: Number(source["version"]), hash: String(source["hash"]), ...(r["source_line_id"] ? { sourceLineId: String(r["source_line_id"]) } : {}) }, jurisdictionId: String(r["jurisdiction_id"]), taxTypeId: String(r["tax_type_id"]), taxGroupId: String(r["tax_group_id"]), taxRateScheduleId: String(r["tax_rate_schedule_id"]), componentCode: String(r["component_code"]), taxDirection: String(r["tax_direction"]) as TaxCalculationLine["taxDirection"], taxTreatment: String(r["tax_treatment"]) as TaxCalculationLine["taxTreatment"], rateKind: String(r["rate_kind"]) as TaxCalculationLine["rateKind"], rateValue: String(r["rate_value"]), calculationBasisCode: String(r["calculation_basis_code"]), taxableBaseAmount: String(r["taxable_base_amount"]), taxAmount: String(r["tax_amount"]), roundingAdjustment: String(r["rounding_adjustment"]), recoverability: String(r["recoverability"]) as TaxCalculationLine["recoverability"], recoverableAmount: String(r["recoverable_amount"]), nonrecoverableAmount: String(r["nonrecoverable_amount"]), baseCurrencyAmount: String(r["base_currency_amount"]), exchangeRate: String(r["exchange_rate"]), ruleSnapshot: obj(r["rule_snapshot"]) as unknown as TaxCalculationLine["ruleSnapshot"], rateSnapshot: obj(r["rate_snapshot"]) as unknown as TaxCalculationLine["rateSnapshot"], basisSnapshot: basis as unknown as TaxCalculationLine["basisSnapshot"], evidenceHash: String(r["evidence_hash"]), ...(r["reverses_calculation_id"] ? { reversesCalculationId: String(r["reverses_calculation_id"]) } : {}), idempotencyKey: String(r["idempotency_key"]), postedAt: date(r["posted_at"]) }; }
function mapMovement(r: Row): TaxCreditMovement { return { id: String(r["id"]), companyCodeId: String(r["company_code_id"]), ledgerBookId: String(r["ledger_book_id"]), fiscalPeriodId: String(r["fiscal_period_id"]), jurisdictionId: String(r["jurisdiction_id"]), taxTypeId: String(r["tax_type_id"]), taxBucket: String(r["tax_bucket"]) as TaxCreditMovement["taxBucket"], movementType: String(r["movement_type"]) as TaxCreditMovement["movementType"], amount: String(r["amount"]), currencyCode: String(r["currency_code"]).trim(), ...(r["source_tax_calculation_id"] ? { sourceTaxCalculationId: String(r["source_tax_calculation_id"]) } : {}), ...(r["reverses_movement_id"] ? { reversesMovementId: String(r["reverses_movement_id"]) } : {}), idempotencyKey: String(r["idempotency_key"]), ...(r["reason"] ? { reason: String(r["reason"]) } : {}), createdAt: date(r["created_at"]) }; }
function obj(value: unknown): Record<string, unknown> { if (typeof value === "string") try { return JSON.parse(value) as Record<string, unknown>; } catch { return {}; } return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function date(value: unknown) { return value instanceof Date ? value.toISOString() : String(value); }
