import { describe, expect, it } from "vitest";
import type { FinanceActor, ResolvedTaxConfiguration, TaxCalculationCommand, TaxCalculationLine, TaxCalculationRepository, TaxCreditCoordinate, TaxCreditMovement, TaxCreditMovementCommand, TaxCreditRepository } from "@athyper/server-contract-finance";
import { InMemoryFinanceCommandRepository } from "../shared/in-memory-command-repository.js";
import { canonicalFinanceHash } from "../shared/canonical.js";
import { RoundingResolver } from "../shared/rounding-resolver.js";
import { TaxCalculationService, taxEvidenceHash } from "./tax-calculation-service.js";
import { rebuildTaxCreditBalance, TaxCreditService } from "./tax-credit-service.js";

const actor: FinanceActor = { tenantId: "tenant", principalId: "principal", planeKey: "neon", correlationId: "correlation" };
const transaction = { run: async <T>(_actor: FinanceActor, work: (tx: object) => Promise<T>) => work({}) };
const permissions = { isAllowed: async () => true };
const audit = { record: async () => undefined };
const outbox = { append: async () => undefined };
const guard = { assertPeriodOpen: async () => ({} as never) };
const rounding = new RoundingResolver({ listCandidates: async request => [{ contextId: `context-${request.currencyCode}`, companyCodeId: "company", currencyCode: request.currencyCode, slot: "LINE_TAX", ruleId: `round-${request.currencyCode}`, ruleCode: "TAX", method: "ROUND_HALF_UP", precisionDigits: 4, roundingIncrement: "0.0001", revision: "1" }], getCurrencyDefaults: async () => undefined });

class Calculations implements TaxCalculationRepository<object> {
  readonly lines: TaxCalculationLine[] = [];
  async append(_actor: FinanceActor, line: TaxCalculationLine) { this.lines.push(line); return line; }
  async get(_actor: FinanceActor, id: string) { return this.lines.find(line => line.id === id); }
  async findReversal(_actor: FinanceActor, id: string) { return this.lines.find(line => line.reversesCalculationId === id); }
}

function configuration(rates: readonly [string, string][], compound = false): ResolvedTaxConfiguration { return { taxGroupId: "group", compound, rule: { ruleId: "rule", ruleCode: "VAT", revision: "2026-01-01", effectiveFrom: "2026-01-01", taxGroupId: "group", priority: 10, sourceHash: "rule-hash", groupRevision: "2026-01-01", groupSourceHash: "group-hash", roundingRuleId: "round", matchEvidence: {} }, components: rates.map(([code, rateValue], index) => ({ scheduleId: `schedule-${code}`, revision: "2026-01-01", effectiveFrom: "2026-01-01", jurisdictionId: "jurisdiction", taxTypeId: `type-${code}`, componentCode: code, calculationSequence: index + 1, taxDirection: "SALE", taxTreatment: rateValue === "0" ? "ZERO_RATED" : "STANDARD", rateKind: "PERCENT", rateValue, calculationBasisCode: "LINE_NET", recoverability: "NONE", sourceHash: `hash-${code}` })) }; }
function command(id: string, amount: string, pricingMode: "inclusive" | "exclusive", extra: Partial<TaxCalculationCommand["payload"]> = {}): TaxCalculationCommand { const payload: TaxCalculationCommand["payload"] = { coordinates: { companyCodeId: "company", ledgerBookId: "book", fiscalPeriodId: "period", currencyCode: "USD" }, source: { sourceType: "document.invoice", sourceId: "invoice", sourceLineId: "line", version: 7, hash: "invoice-hash" }, resolution: { taxDate: "2026-08-11", transactionDirection: "SALE" }, pricingMode, amount, baseCurrencyCode: "MYR", exchangeRate: "4.5000000000", postedAt: "2026-08-11T00:00:00.000Z", ...extra }; const base = { commandId: id, commandCode: "finance.tax.calculate", idempotencyKey: id, actor, payload }; return { ...base, requestFingerprint: fingerprint(base.commandCode, payload) }; }
function service(repo: Calculations, getConfig: () => ResolvedTaxConfiguration) { return new TaxCalculationService({ transactions: transaction, commands: new InMemoryFinanceCommandRepository<object>(), repository: repo, configuration: { resolve: async () => getConfig() }, sources: { loadImmutable: async (_actor, source) => source }, rounding, guard, permissions, audit, outbox }); }
function applied<T>(result: { kind: string; output?: T }): T { expect(result.kind).toBe("applied"); return result.output!; }

describe("F5 tax calculation ledger", () => {
  it("calculates exclusive multi-rate groups and FX without binary floating point", async () => { const repo = new Calculations(); const output = applied(await service(repo, () => configuration([["STATE", "6"], ["LOCAL", "2.5"]])).calculate(command("11111111-1111-4111-8111-111111111111", "100.0000", "exclusive"))); expect(output.lines.map(line => line.taxAmount)).toEqual(["6.0000", "2.5000"]); expect(output.totalTaxAmount).toBe("8.5000"); expect(output.totalBaseCurrencyAmount).toBe("38.2500"); });
  it("backs tax out of inclusive pricing and handles zero-rated components", async () => { const repo = new Calculations(); const output = applied(await service(repo, () => configuration([["VAT", "15"], ["ZERO", "0"]])).calculate(command("22222222-2222-4222-8222-222222222222", "115.0000", "inclusive"))); expect(output.lines).toHaveLength(1); expect(output.lines[0]).toMatchObject({ taxableBaseAmount: "100.0000", taxAmount: "15.0000" }); });
  it("rejects ordinary non-positive amounts and uses linked exact negatives for reversal", async () => { const repo = new Calculations(); const tax = service(repo, () => configuration([["VAT", "10"]])); await expect(tax.calculate(command("30000000-0000-4000-8000-000000000000", "-1.0000", "exclusive"))).rejects.toThrow(/linked reversal/); const original = applied(await tax.calculate(command("33333333-3333-4333-8333-333333333333", "20.0000", "exclusive"))).lines[0]!; const reversal = applied(await tax.calculate(command("44444444-4444-4444-8444-444444444444", "20.0000", "exclusive", { reversesCalculationIds: [original.id] }))).lines[0]!; expect(reversal).toMatchObject({ taxableBaseAmount: "-20.0000", taxAmount: "-2.0000", baseCurrencyAmount: "-9.0000", reversesCalculationId: original.id }); expect(reversal.evidenceHash).toBe(taxEvidenceHash(reversal.ruleSnapshot, reversal.rateSnapshot, reversal.basisSnapshot)); expect(tax.replay(reversal)).toEqual(reversal); await expect(tax.calculate(command("45555555-5555-4555-8555-555555555555", "20.0000", "exclusive", { reversesCalculationIds: [original.id] }))).rejects.toThrow(/already been reversed/); });
  it("replays solely from bounded snapshots after mutable configuration changes", async () => { const repo = new Calculations(); let current = configuration([["VAT", "10"]]); const tax = service(repo, () => current); const line = applied(await tax.calculate(command("55555555-5555-4555-8555-555555555555", "75.0000", "exclusive"))).lines[0]!; current = configuration([["VAT", "99"]]); expect(tax.replay(line)).toEqual(line); expect(taxEvidenceHash(line.ruleSnapshot, line.rateSnapshot, line.basisSnapshot)).toBe(line.evidenceHash); const tampered = { ...line, rateSnapshot: { ...line.rateSnapshot, rateValue: "99" } }; expect(() => tax.replay(tampered)).toThrow(/evidence hash/); });
});

class Credits implements TaxCreditRepository<object> { readonly rows: TaxCreditMovement[] = []; async append(c: TaxCreditMovementCommand) { const row = { id: c.commandId, ...c.payload, idempotencyKey: c.idempotencyKey, createdAt: String(c.payload["createdAt"] ?? "2026-08-11T00:00:00.000Z") } as TaxCreditMovement; this.rows.push(row); return row; } async get(_a: FinanceActor, id: string) { return this.rows.find(row => row.id === id); } async findReversal(_a: FinanceActor, id: string) { return this.rows.find(row => row.reversesMovementId === id); } async listForSource(_a: FinanceActor, id: string) { return this.rows.filter(row => row.sourceTaxCalculationId === id); } async list(_a: FinanceActor, coordinate: TaxCreditCoordinate, asOf: string) { return this.rows.filter(row => row.companyCodeId === coordinate.companyCodeId && row.createdAt <= asOf); } }
const creditCoordinate: TaxCreditCoordinate = { companyCodeId: "company", ledgerBookId: "book", fiscalPeriodId: "period", jurisdictionId: "jurisdiction", taxTypeId: "vat", taxBucket: "input", currencyCode: "USD" };
function creditCommand(id: string, amount: string, extra: Partial<TaxCreditMovementCommand["payload"]> = {}): TaxCreditMovementCommand { const payload = { ...creditCoordinate, movementType: "posting" as const, amount, sourceTaxCalculationId: "tax", ...extra }; const base = { commandId: id, commandCode: "finance.tax_credit.move", idempotencyKey: id, actor, payload }; return { ...base, requestFingerprint: fingerprint(base.commandCode, payload) }; }
function fingerprint(commandCode: string, payload: Readonly<Record<string, unknown>>) { return canonicalFinanceHash({ commandCode, tenantId: actor.tenantId, principalId: actor.principalId, payload, expectedVersion: undefined }); }

describe("F5 tax-credit ledger", () => {
  it("rebuilds point-in-time balances and exactly reverses bucket movements", async () => { const repo = new Credits(); const credits = new TaxCreditService({ guard, transactions: transaction, commands: new InMemoryFinanceCommandRepository<object>(), repository: repo, sourceCalculations: { getCalculation: async () => ({ coordinates: creditCoordinate, jurisdictionId: creditCoordinate.jurisdictionId, taxTypeId: creditCoordinate.taxTypeId, taxDirection: "purchase", recoverableAmount: "12.5000" } as unknown as TaxCalculationLine) }, permissions, audit, outbox }); const original = applied(await credits.move(creditCommand("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", "12.5000"))).movement; repo.rows.push({ ...original, id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", amount: "2.5000", movementType: "adjustment", sourceTaxCalculationId: undefined, idempotencyKey: "later", createdAt: "2026-08-12T00:00:00.000Z" }); expect((await credits.balance(actor, creditCoordinate, "2026-08-11T23:59:59.000Z")).amount).toBe("12.5000"); const reversal = applied(await credits.move(creditCommand("cccccccc-cccc-4ccc-8ccc-cccccccccccc", "-12.5000", { movementType: "reversal", reversesMovementId: original.id }))).movement; expect(reversal.reversesMovementId).toBe(original.id); expect((await credits.rebuild(actor, creditCoordinate, "2026-08-13T00:00:00.000Z")).amount).toBe("2.5000"); });
  it("makes rebuild deterministic regardless of input order", () => { const rows: TaxCreditMovement[] = [{ id: "2", ...creditCoordinate, movementType: "adjustment", amount: "-1.0000", idempotencyKey: "2", createdAt: "2026-02-01T00:00:00Z" }, { id: "1", ...creditCoordinate, movementType: "posting", amount: "5.0000", idempotencyKey: "1", createdAt: "2026-01-01T00:00:00Z" }]; expect(rebuildTaxCreditBalance(creditCoordinate, "2026-12-31T00:00:00Z", rows)).toMatchObject({ amount: "4.0000", movementCount: 2, lastMovementId: "2" }); });
});
