import { describe,expect,it,vi } from "vitest";
import { ProjectionReconciliationWorker, classifyProjectionFailure, projectionJobIdentity, type ProjectionReconciliationRepository, type ProjectionReconciliationWork } from "../index.js";

const at=new Date("2026-08-15T00:00:00.000Z");
function work(overrides:Partial<ProjectionReconciliationWork>={}):ProjectionReconciliationWork{const base={attemptId:"10000000-0000-4000-8000-000000000001",authorityTenantId:"10000000-0000-4000-8000-000000000002",projectionId:"10000000-0000-4000-8000-000000000003",desiredVersion:7,desiredHash:"a".repeat(64),targetPlane:"neon" as const,targetTenantId:"10000000-0000-4000-8000-000000000004",attemptNo:1,claimTokenHash:"",fencingToken:4,desiredPayload:{source:"studio"}},merged={...base,...overrides};return{...merged,jobIdentityHash:overrides.jobIdentityHash??projectionJobIdentity(merged)};}
function harness(item:ProjectionReconciliationWork,error?:Error,current=true){const state={businessStatus:"active",observation:"pending"};const repository={claim:vi.fn(async input=>({...item,claimTokenHash:input.claimTokenHash})),current:vi.fn(async()=>current),start:vi.fn(async()=>true),succeed:vi.fn(async()=>{state.observation="in_sync";return true;}),fail:vi.fn(async(_coordinate,input)=>{state.observation=input.deadLetter?"failed":"retry";return true;}),replay:vi.fn(async()=>true),health:vi.fn()} as unknown as ProjectionReconciliationRepository;const targets={apply:vi.fn(async()=>{if(error)throw error;return{desiredVersion:item.desiredVersion,desiredHash:item.desiredHash,targetProjectionId:item.projectionId};})};const alerts={outbox:vi.fn(async()=>undefined),metric:vi.fn(),capture:vi.fn()};const worker=new ProjectionReconciliationWorker({workerId:"studio-projection-worker",repository,targets,alerts,now:()=>at,maxAttempts:3});return{worker,repository,targets,alerts,state};}

describe("Studio-originated projection reconciliation",()=>{
  it("applies one exact desired version/hash and records an in-sync observation",async()=>{const item=work(),h=harness(item);await expect(h.worker.runOne("claim-secret")).resolves.toBe("succeeded");expect(h.targets.apply).toHaveBeenCalledWith(expect.objectContaining({projectionId:item.projectionId,desiredVersion:7,desiredHash:"a".repeat(64),targetPlane:"neon"}));expect(h.repository.succeed).toHaveBeenCalledWith(expect.objectContaining({fencingToken:4,desiredVersion:7,desiredHash:"a".repeat(64)}),expect.anything());expect(h.state.businessStatus).toBe("active");expect(h.state.observation).toBe("in_sync");});
  it("rejects a stale Studio job before touching the target plane",async()=>{const h=harness(work(),undefined,false);await expect(h.worker.runOne("claim-secret")).resolves.toBe("stale");expect(h.targets.apply).not.toHaveBeenCalled();expect(h.repository.fail).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({classification:"stale",deadLetter:true,errorCode:"PROJECTION_DESIRED_STATE_STALE"}));});
  it("classifies transient failures for retry and alerts through metrics",async()=>{const error=Object.assign(new Error("timeout"),{code:"TARGET_TIMEOUT"}),h=harness(work(),error);await expect(h.worker.runOne("claim-secret")).resolves.toBe("retry");expect(h.repository.fail).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({classification:"transient",deadLetter:false,nextAttemptAt:"2026-08-15T00:05:00.000Z"}));expect(h.alerts.metric).toHaveBeenCalledWith({targetPlane:"neon",classification:"transient",outcome:"retry"});expect(h.alerts.outbox).not.toHaveBeenCalled();});
  it("dead-letters exhausted work and emits outbox, metric, and exception alerts without suspending desired state",async()=>{const error=Object.assign(new Error("timeout"),{code:"TARGET_TIMEOUT"}),h=harness(work({attemptNo:3}),error);await expect(h.worker.runOne("claim-secret")).resolves.toBe("dead_letter");expect(h.repository.fail).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({deadLetter:true}));expect(h.alerts.outbox).toHaveBeenCalledOnce();expect(h.alerts.metric).toHaveBeenCalledWith(expect.objectContaining({outcome:"dead_letter"}));expect(h.alerts.capture).toHaveBeenCalledOnce();expect(h.state.businessStatus).toBe("active");});
  it("binds job identity to projection, target, attempt, desired version, and desired hash",async()=>{const item=work({jobIdentityHash:"f".repeat(64)}),h=harness(item);await expect(h.worker.runOne("claim-secret")).resolves.toBe("dead_letter");expect(h.targets.apply).not.toHaveBeenCalled();expect(h.repository.fail).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({classification:"permanent",errorCode:"PROJECTION_JOB_IDENTITY_MISMATCH"}));});
  it("classifies validation SQLSTATEs as permanent and retryable database failures as transient",()=>{expect(classifyProjectionFailure(Object.assign(new Error("check"),{code:"23514"}))).toBe("permanent");expect(classifyProjectionFailure(Object.assign(new Error("serialization"),{code:"40001"}))).toBe("transient");expect(classifyProjectionFailure(Object.assign(new Error("connection"),{code:"08006"}))).toBe("transient");});
});
