BEGIN;
DO $$
DECLARE
 t uuid;maker uuid;checker uuid;other_tenant uuid;contract_id uuid:=gen_random_uuid();contract_entity_id uuid:=gen_random_uuid();release_id uuid:=gen_random_uuid();revision_id uuid:=gen_random_uuid();
 cycle_type_id uuid:=gen_random_uuid();phase_id uuid:=gen_random_uuid();category_id uuid:=gen_random_uuid();template_id uuid:=gen_random_uuid();template_revision_id uuid:=gen_random_uuid();
 run1 uuid:=gen_random_uuid();task1 uuid:=gen_random_uuid();case1 uuid:=gen_random_uuid();run2 uuid:=gen_random_uuid();task2 uuid:=gen_random_uuid();case2 uuid:=gen_random_uuid();form_id uuid:=gen_random_uuid();r record;
BEGIN
 SELECT p.tenant_id,(array_agg(p.id ORDER BY p.id))[1],(array_agg(p.id ORDER BY p.id))[2] INTO t,maker,checker FROM master.principal p WHERE p.status='active' GROUP BY p.tenant_id HAVING count(*)>=2 ORDER BY p.tenant_id LIMIT 1;
 SELECT id INTO other_tenant FROM master.tenant WHERE id<>t ORDER BY id LIMIT 1;
 IF t IS NULL OR maker=checker OR other_tenant IS NULL THEN RAISE EXCEPTION 'G1 lifecycle probe requires two actors and another tenant';END IF;
 PERFORM set_config('app.current_tenant_id',t::text,true);PERFORM set_config('app.current_principal_id',maker::text,true);
 INSERT INTO runtime_meta.entity_contract(id,tenant_id,entity_id,entity_code,release_id,revision_id,release_no,contract_schema_code,contract_schema_version,entity_contract_hash,contract_json,publication_key,signature_algorithm,signing_key_id,signature,published_at,status,status_changed_at) VALUES(contract_id,t,contract_entity_id,'master.business_partner',release_id,revision_id,1,'athyper.entity-contract','1.0.0',repeat('e',64),'{"type":"object","required":["businessPartnerCode","name","ownershipClass"],"additionalProperties":false,"properties":{"businessPartnerCode":{"type":"string"},"name":{"type":"string"},"ownershipClass":{"type":"string"}}}'::jsonb,'g1.lifecycle','ed25519','g1-key','probe',clock_timestamp()-interval '1 second','published',clock_timestamp());
 INSERT INTO control.cycle_type(id,tenant_id,code,name,domain_code,frequency,status,status_changed_at,status_changed_by,created_by) VALUES(cycle_type_id,t,'G1.LIFECYCLE','G1 Lifecycle','governance_review','adhoc','active',clock_timestamp(),maker,maker);
 INSERT INTO control.cycle_phase(id,tenant_id,cycle_type_id,code,name,sort_order,status,status_changed_at,status_changed_by,created_by) VALUES(phase_id,t,cycle_type_id,'REVIEW','Review',1,'active',clock_timestamp(),maker,maker);
 INSERT INTO control.cycle_task_category(id,tenant_id,cycle_type_id,code,name,status,status_changed_at,status_changed_by,created_by) VALUES(category_id,t,cycle_type_id,'APPROVAL','Approval','active',clock_timestamp(),maker,maker);
 INSERT INTO control.cycle_task_template(id,tenant_id,cycle_type_id,phase_id,category_id,entity_code,code,name,completion_mode,status,status_changed_at,status_changed_by,created_by) VALUES(template_id,t,cycle_type_id,phase_id,category_id,'document.entity_case','DECIDE','Decide','manual','active',clock_timestamp(),maker,maker);
 INSERT INTO control.cycle_template_revision(id,tenant_id,cycle_type_id,revision_number,template_json,template_hash,topological_task_ids,idempotency_key,published_by,created_by) VALUES(template_revision_id,t,cycle_type_id,1,'{}',repeat('f',64),ARRAY[template_id],'g1-lifecycle-template',maker,maker);
 INSERT INTO governance.cycle_run(id,tenant_id,cycle_type_id,template_revision_id,template_revision_number,template_hash,code,name,idempotency_key,status,created_by) VALUES(run1,t,cycle_type_id,template_revision_id,1,repeat('f',64),'G1.RUN1','G1 Run 1','g1-lifecycle-run-1','draft',maker),(run2,t,cycle_type_id,template_revision_id,1,repeat('f',64),'G1.RUN2','G1 Run 2','g1-lifecycle-run-2','draft',maker);
 INSERT INTO governance.cycle_task(id,tenant_id,cycle_run_id,cycle_type_id,task_template_id,phase_id,code,name,completion_mode,owner_principal_id,status,created_by) VALUES(task1,t,run1,cycle_type_id,template_id,phase_id,'DECIDE','Decide','manual',checker,'pending',maker),(task2,t,run2,cycle_type_id,template_id,phase_id,'DECIDE','Decide','manual',checker,'pending',maker);

 SELECT * INTO r FROM document.command_entity_case_draft(t,case1,0,NULL,'G1.LIFECYCLE.1','master.business_partner','register',NULL,'g1-lifecycle-1',contract_id,repeat('e',64),form_id,1,repeat('a',64),'{"businessPartnerCode":"G1.INTERNAL.APPROVE","name":"Approve Me","ownershipClass":"internal"}','g1-life-draft-0001',maker,NULL);
 SELECT * INTO r FROM document.command_entity_case_lifecycle(t,case1,'submit',1,run1,task1,NULL,'g1-life-submit-0001',maker,NULL);
 IF r.row_version<>2 OR r.status<>'submitted' OR r.replayed THEN RAISE EXCEPTION 'G1 submit failed';END IF;
 SELECT * INTO r FROM document.command_entity_case_lifecycle(t,case1,'submit',1,run1,task1,NULL,'g1-life-submit-0001',maker,NULL);IF NOT r.replayed THEN RAISE EXCEPTION 'G1 submit replay failed';END IF;
 BEGIN PERFORM document.command_entity_case_lifecycle(t,case1,'approve',2,run1,task1,NULL,'g1-life-maker-denied',maker,NULL);RAISE EXCEPTION 'maker approved own case';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 PERFORM set_config('app.current_principal_id',checker::text,true);
 BEGIN PERFORM document.command_entity_case_lifecycle(t,case1,'approve',1,run1,task1,NULL,'g1-life-stale-denied',checker,NULL);RAISE EXCEPTION 'stale decision accepted';EXCEPTION WHEN serialization_failure THEN NULL;END;
 BEGIN PERFORM document.command_entity_case_lifecycle(other_tenant,case1,'approve',2,run1,task1,NULL,'g1-life-tenant-denied',checker,NULL);RAISE EXCEPTION 'wrong tenant accepted';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 PERFORM set_config('app.current_principal_id',checker::text,true);
 SELECT * INTO r FROM document.command_entity_case_lifecycle(t,case1,'approve',2,run1,task1,NULL,'g1-life-approve-0001',checker,NULL);
 IF r.row_version<>3 OR r.status<>'approved' OR (SELECT status FROM governance.cycle_task WHERE id=task1)<>'completed' OR (SELECT status FROM governance.cycle_run WHERE id=run1)<>'completed' THEN RAISE EXCEPTION 'G1 approval workflow commit failed';END IF;
 SELECT * INTO r FROM document.command_entity_case_lifecycle(t,case1,'approve',2,run1,task1,NULL,'g1-life-approve-0001',checker,NULL);IF NOT r.replayed THEN RAISE EXCEPTION 'G1 approval replay failed';END IF;
 SELECT * INTO r FROM master.command_materialize_internal_business_partner_case(t,case1,3,'g1-life-materialize-0001',checker,NULL);
 IF r.row_version<>4 OR r.case_status<>'materialized' OR r.replayed OR NOT EXISTS(SELECT 1 FROM master.business_partner b WHERE b.tenant_id=t AND b.id=r.business_partner_id AND b.status='active' AND b.ownership_class='internal' AND b.partner_category='organization') OR NOT EXISTS(SELECT 1 FROM snapshot.entity_snapshot_identity i JOIN snapshot.entity_snapshot s ON s.tenant_id=i.tenant_id AND s.snapshot_id=i.id WHERE i.tenant_id=t AND i.id=r.result_snapshot_id AND i.entity_type='master.business_partner' AND i.entity_id=r.business_partner_id AND s.payload_json='{"businessPartnerCode":"G1.INTERNAL.APPROVE","name":"Approve Me","ownershipClass":"internal"}'::jsonb) OR EXISTS(SELECT 1 FROM master.supplier s WHERE s.tenant_id=t AND s.business_partner_id=r.business_partner_id) OR EXISTS(SELECT 1 FROM master.customer c WHERE c.tenant_id=t AND c.business_partner_id=r.business_partner_id) THEN RAISE EXCEPTION 'G1 internal Business Partner materialization failed';END IF;
 SELECT * INTO r FROM master.command_materialize_internal_business_partner_case(t,case1,3,'g1-life-materialize-0001',checker,NULL);IF NOT r.replayed THEN RAISE EXCEPTION 'G1 materialization replay failed';END IF;
 BEGIN PERFORM master.command_materialize_internal_business_partner_case(t,case1,3,'g1-life-materialize-stale',checker,NULL);RAISE EXCEPTION 'stale materialization accepted';EXCEPTION WHEN serialization_failure THEN NULL;END;

 PERFORM set_config('app.current_principal_id',maker::text,true);
 PERFORM document.command_entity_case_draft(t,case2,0,NULL,'G1.LIFECYCLE.2','master.business_partner','register',NULL,'g1-lifecycle-2',contract_id,repeat('e',64),form_id,1,repeat('a',64),'{"businessPartnerCode":"G1.INTERNAL.REJECT","name":"Reject Me","ownershipClass":"internal"}','g1-life-draft-0002',maker,NULL);
 PERFORM document.command_entity_case_lifecycle(t,case2,'submit',1,run2,task2,NULL,'g1-life-submit-0002',maker,NULL);
 PERFORM set_config('app.current_principal_id',checker::text,true);
 BEGIN PERFORM document.command_entity_case_lifecycle(t,case2,'reject',2,run2,task2,'','g1-life-reject-empty',checker,NULL);RAISE EXCEPTION 'empty rejection reason accepted';EXCEPTION WHEN check_violation THEN NULL;END;
 SELECT * INTO r FROM document.command_entity_case_lifecycle(t,case2,'reject',2,run2,task2,'duplicate','g1-life-reject-0002',checker,NULL);IF r.status<>'rejected' OR r.row_version<>3 THEN RAISE EXCEPTION 'G1 rejection failed';END IF;
 IF (SELECT count(*) FROM governance.cycle_subject WHERE entity_case_id IN(case1,case2))<>2 OR (SELECT count(*) FROM snapshot.entity_case_snapshot_lineage WHERE entity_case_id IN(case1,case2))<>5 OR (SELECT count(*) FROM document.entity_case_command_evidence WHERE entity_case_id IN(case1,case2))<>7 OR (SELECT count(*) FROM document.entity_case_materialization WHERE entity_case_id=case1 AND status='succeeded')<>1 OR (SELECT count(*) FROM event.outbox WHERE aggregate_type='entity_case' AND aggregate_id IN(case1,case2))<>7 OR EXISTS(SELECT 1 FROM event.command_execution WHERE idempotency_key IN('g1-life-maker-denied','g1-life-stale-denied','g1-life-tenant-denied','g1-life-reject-empty','g1-life-materialize-stale')) THEN RAISE EXCEPTION 'G1 lifecycle atomic evidence failed';END IF;
END $$;
ROLLBACK;
SELECT 'G1_GOVERNED_ENTITY_CASE_LIFECYCLE_ROLLBACK_OK';
