import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {homedir} from "node:os";
import {Kysely,PostgresDialect,sql} from "kysely";
import pg from "pg";
import {createHrStage2Service} from "../../../../packages/services/master-data/src/hr-stage2-service.js";
const tenantId="11111111-1111-4111-8111-111111111111",actor="d4250b08-6e5e-5887-b4e1-6f3eb31d7c8c",companyCodeId="7e0e3d2c-c5fc-5960-b4c3-80153c1e95a7",serviceAccount="34ce3386-ed20-5933-91d1-699d38b197fe";
const host=process.env.PROBE_DB_HOST;
if(!host)throw Error("PROBE_DB_HOST is required");
const db=new Kysely<Record<string,never>>({dialect:new PostgresDialect({pool:new pg.Pool({host,database:"athyper_neon",user:"athyper_runtime",password:readFileSync(`${homedir()}/.athyper/instances/dev/secrets/runtime-db-password`,"utf8").trim(),max:1})})});
const rollback=Symbol("rollback");
let passed=false;
try{await db.transaction().execute(async tx=>{
  let allow=true;
  const service=createHrStage2Service({authorizer:{async authorize(input:any){const resource=input.resource??{};return {allowed:allow&&input.context.tenantId===tenantId&&(resource.companyCodeId?resource.companyCodeId===companyCodeId:resource.tenantId===tenantId)};}} as any,transactions:{async run(_plane:any,identity:any,work:any){await sql`SELECT set_config('app.database_plane','neon',true),set_config('app.current_tenant_id',${identity.tenantId},true),set_config('app.current_principal_id',${identity.principalId},true)`.execute(tx);return work(tx);}} as any,audit:{async record(){}} as any});
  const context=(principalId:string)=>({planeKey:"neon",tenantId,principalId,requestId:"44444444-4444-4444-8444-444444444444"}) as any;
  const catalog=await service.catalog(context(actor),companyCodeId);assert.equal(catalog.company["id"],companyCodeId);
  const authority=await service.employeeAuthority(context(actor),"1fc65c52-0aeb-558d-b8fe-21a8a652bdba",companyCodeId);assert.equal(authority.companyCodeId,companyCodeId);
  const code=`stage2_service_${Date.now()}`;
  const created=await service.createDraftPosition(context(actor),{companyCodeId,code,name:"Stage 2 service probe",validFrom:"2026-09-22"});assert.equal(created["status"],"draft");
  const replay=await service.createDraftPosition(context(actor),{companyCodeId,code,name:"Stage 2 service probe",validFrom:"2026-09-22"});assert.equal(replay.replayed,true);
  const refreshed=await service.catalog(context(actor),companyCodeId);assert(refreshed.positions.some(row=>row["code"]===code));
  const users=await service.users(context(actor),"Athyper",50);assert(users.some(row=>row["id"]===actor));
  const detail=await service.user(context(actor),actor);assert.equal(detail.principal["id"],actor);
  await sql`UPDATE master.employee SET principal_id=${actor}::uuid,updated_at=now(),updated_by=${actor}::uuid WHERE tenant_id=${tenantId}::uuid AND id='1fc65c52-0aeb-558d-b8fe-21a8a652bdba'::uuid`.execute(tx);
  const linkedUser=await service.user(context(actor),actor);assert(linkedUser.employmentLinks.some(row=>row["employee_id"]==="1fc65c52-0aeb-558d-b8fe-21a8a652bdba"));
  const linked=linkedUser.employmentLinks.find(row=>row["employee_id"]==="1fc65c52-0aeb-558d-b8fe-21a8a652bdba");assert(linked);
  const retry=(await sql<{employment_id:string;replayed:boolean}>`SELECT employment_id,replayed FROM document.command_internal_workforce_identity_intent(${tenantId}::uuid,(SELECT id FROM master.employment WHERE tenant_id=${tenantId}::uuid AND employee_id=${linked["employee_id"]}::uuid AND legal_entity_id=${linked["employer_organization_id"]}::uuid AND status='active' LIMIT 1),'active',true,${`stage2-user-retry-${Date.now()}`},${actor}::uuid,NULL::uuid)`.execute(tx)).rows[0];assert(retry&&!retry.replayed);
  const key=`stage2-service-${Date.now()}`;
  const own=await service.requestOwnProfileChange(context(actor),{idempotencyKey:key,preferredName:"Stage 2",displayName:"Stage 2 probe"});assert.equal(own["status"],"draft");
  const ownReplay=await service.requestOwnProfileChange(context(actor),{idempotencyKey:key,preferredName:"Stage 2",displayName:"Stage 2 probe"});assert.equal(ownReplay.replayed,true);
  const requests=await service.ownProfileRequest(context(actor));assert(requests.some(row=>row["id"]===own["id"]));
  const submitted=await service.submitOwnProfileRequest(context(actor),String(own["id"]),1);assert.equal(submitted["status"],"submitted");
  const reviewer="ff3d770b-fc3f-5b2c-a5c1-901954691ddf";
  const queue=await service.profileReviewQueue(context(reviewer));assert(queue.some(row=>row["id"]===own["id"]));
  await assert.rejects(service.decideProfileRequest(context(actor),{requestId:String(own["id"]),expectedVersion:2,decision:"apply"}),{status:403});
  const applied=await service.decideProfileRequest(context(reviewer),{requestId:String(own["id"]),expectedVersion:2,decision:"apply"});assert.equal(applied["status"],"applied");
  const changed=await service.user(context(actor),actor);assert.equal(changed.principal["preferred_name"],"Stage 2");
  const expectedUpdatedAt=changed.principal["profile_updated_at"]?new Date(String(changed.principal["profile_updated_at"])).toISOString():null;
  const adminChange=await service.adminUpdateProfile(context(reviewer),{principalId:actor,expectedUpdatedAt,displayName:"Stage 2 admin"});assert.equal(adminChange.replayed,false);
  const adminReload=await service.user(context(reviewer),actor);assert.equal(adminReload.principal["display_name"],"Stage 2 admin");
  await assert.rejects(service.adminUpdateProfile(context(reviewer),{principalId:serviceAccount,preferredName:"No"}),{status:409});
  const rejection=await service.requestOwnProfileChange(context(actor),{idempotencyKey:`stage2-reject-${Date.now()}`,displayName:"Rejected display"});
  await service.submitOwnProfileRequest(context(actor),String(rejection["id"]),1);
  const rejected=await service.decideProfileRequest(context(reviewer),{requestId:String(rejection["id"]),expectedVersion:2,decision:"reject",reason:"Local rejection probe"});assert.equal(rejected["status"],"rejected");
  const afterReject=await service.user(context(actor),actor);assert.equal(afterReject.principal["display_name"],"Stage 2 admin");



  const policyDefinitionId="7b84b98f-6814-4ee6-a65c-4959ca51df01";
  const policy=await service.createPolicyAssignment(context(actor),{idempotencyKey:`stage2-policy-${Date.now()}`,policyDefinitionId,scopeKind:"company",countryCode:"CA",companyCodeId,effectiveFrom:"2026-09-22"});assert.equal(policy["status"],"draft");
  await assert.rejects(service.publishPolicyAssignment(context(actor),String(policy["id"]),1),{status:403});
  const published=await service.publishPolicyAssignment(context(reviewer),String(policy["id"]),1);assert.equal(published["status"],"active");
  const effective=await service.resolvePolicy(context(actor),{companyCodeId,asOf:"2026-09-22"});assert(effective.selected.some(row=>row["id"]===policy["id"]));
  const policyRows=await service.policyAssignments(context(actor),companyCodeId);assert(policyRows.some(row=>row["id"]===policy["id"]));
  const countryDefault=await service.createPolicyAssignment(context(actor),{idempotencyKey:`stage2-country-${Date.now()}`,policyDefinitionId,scopeKind:"country",countryCode:"CA",effectiveFrom:"2026-09-22"});
  await service.publishPolicyAssignment(context(reviewer),String(countryDefault["id"]),1);
  const companyResolved=await service.resolvePolicy(context(actor),{companyCodeId,asOf:"2026-09-22"});assert.equal(companyResolved.selected.find(row=>row["entity_type"]==="hr.leave.entitlement")?.["scope_kind"],"company");assert(companyResolved.overridden.some(row=>row["scope_kind"]==="country"));
  const site=(await sql<{id:string}>`INSERT INTO master.site(tenant_id,code,name,company_code_id,site_type,country_code,status,created_by) VALUES(${tenantId}::uuid,${`stage2-site-${Date.now()}`},'Stage 2 probe site',${companyCodeId}::uuid,'office','CA','active',${actor}::uuid) RETURNING id`.execute(tx)).rows[0];assert(site);
  const sitePolicy=await service.createPolicyAssignment(context(actor),{idempotencyKey:`stage2-site-policy-${Date.now()}`,policyDefinitionId,scopeKind:"site",countryCode:"CA",companyCodeId,siteId:site.id,effectiveFrom:"2026-09-22"});
  await service.publishPolicyAssignment(context(reviewer),String(sitePolicy["id"]),1);
  const siteResolved=await service.resolvePolicy(context(actor),{companyCodeId,siteId:site.id,asOf:"2026-09-22"});assert.equal(siteResolved.selected.find(row=>row["entity_type"]==="hr.leave.entitlement")?.["scope_kind"],"site");assert.equal(siteResolved.overridden.filter(row=>row["entity_type"]==="hr.leave.entitlement").length,2);

  const setupCode=`stage2-governed-${Date.now()}`;
  const familyDraft=await service.draftSetup(context(actor),{kind:"job_family",code:`${setupCode}-family`,name:"Stage 2 governed family"});assert.equal(familyDraft.status,"draft");
  await assert.rejects(service.publishSetup(context(actor),String(familyDraft.approvalId),1),{status:403});
  const familyPublished=await service.publishSetup(context(reviewer),String(familyDraft.approvalId),1);assert.equal(familyPublished.status,"active");
  await assert.rejects(service.publishSetup(context(reviewer),String(familyDraft.approvalId),1),{status:409});
  const functionDraft=await service.draftSetup(context(actor),{kind:"job_function",code:`${setupCode}-function`,name:"Stage 2 governed function",jobFamilyId:String(familyDraft.id)});await service.publishSetup(context(reviewer),String(functionDraft.approvalId),1);
  const gradeDraft=await service.draftSetup(context(actor),{kind:"pay_grade",code:`${setupCode}-grade`,name:"Stage 2 governed grade",currencyCode:"CAD"});await service.publishSetup(context(reviewer),String(gradeDraft.approvalId),1);
  const jobDraft=await service.draftSetup(context(actor),{kind:"job",code:`${setupCode}-job`,name:"Stage 2 governed job",jobFamilyId:String(familyDraft.id),jobFunctionId:String(functionDraft.id),payGradeId:String(gradeDraft.id)});await service.publishSetup(context(reviewer),String(jobDraft.approvalId),1);
  const siteDraft=await service.draftSetup(context(actor),{kind:"site",companyCodeId,code:`${setupCode}-site`,name:"Stage 2 governed site",siteType:"office"});await service.publishSetup(context(reviewer),String(siteDraft.approvalId),1);
  const calendarDraft=await service.draftSetup(context(actor),{kind:"holiday_calendar",companyCodeId,code:`${setupCode}-calendar`,name:"Stage 2 governed calendar",siteId:String(siteDraft.id)});await service.publishSetup(context(reviewer),String(calendarDraft.approvalId),1);
  const positionDraft=await service.draftSetup(context(actor),{kind:"position",companyCodeId,code:`${setupCode}-position`,name:"Stage 2 governed position",validFrom:"2026-09-22",jobId:String(jobDraft.id),siteId:String(siteDraft.id)});await service.publishSetup(context(reviewer),String(positionDraft.approvalId),1);
  const setupQueue=await service.setupDrafts(context(actor),companyCodeId);assert(setupQueue.some(row=>row["id"]===positionDraft.approvalId&&row["status"]==="published"));
  const today=new Date().toISOString().slice(0,10),futureDay=new Date(Date.now()+30*86_400_000).toISOString().slice(0,10);
  const orgAssignment=await service.draftOrgCompanyAssignment(context(actor),{companyCodeId,orgUnitId:"9c721422-89c4-54b8-add1-675dbef775fe",effectiveFrom:today});
  await assert.rejects(service.publishOrgCompanyAssignment(context(actor),String(orgAssignment["id"]),1),{status:403});
  const orgPublished=await service.publishOrgCompanyAssignment(context(reviewer),String(orgAssignment["id"]),1);assert.equal(orgPublished["status"],"active");
  assert((await service.orgCompanyAssignments(context(actor),companyCodeId)).some(row=>row["id"]===orgAssignment["id"]));
  await sql`SAVEPOINT stage2_org_overlap`.execute(tx);
  const overlapOrg=await service.draftOrgCompanyAssignment(context(actor),{companyCodeId,orgUnitId:"9c721422-89c4-54b8-add1-675dbef775fe",effectiveFrom:today});
  await assert.rejects(service.publishOrgCompanyAssignment(context(reviewer),String(overlapOrg["id"]),1),{status:409});
  await sql`ROLLBACK TO SAVEPOINT stage2_org_overlap`.execute(tx);
  const dayDraft=await service.draftCalendarDay(context(actor),{companyCodeId,calendarId:String(calendarDraft.id),holidayDate:futureDay,name:"Synthetic future holiday"});
  await assert.rejects(service.publishCalendarDay(context(actor),String(dayDraft["id"]),1),{status:403});
  const dayPublished=await service.publishCalendarDay(context(reviewer),String(dayDraft["id"]),1);assert.equal(dayPublished["status"],"published");
  assert((await service.calendarDayChanges(context(actor),companyCodeId)).some(row=>row["id"]===dayDraft["id"]));
  const sourceDay=(await sql<{id:string}>`SELECT id FROM master.holiday_calendar_day WHERE tenant_id=${tenantId}::uuid AND holiday_calendar_id=${calendarDraft.id}::uuid AND holiday_date=${futureDay}::date`.execute(tx)).rows[0];assert(sourceDay);
  await sql`SAVEPOINT stage2_guard_probe`.execute(tx);
  let guardRejected=false;try{await sql`UPDATE master.hr_org_company_assignment SET effective_from=${futureDay}::date WHERE id=${orgAssignment["id"]}::uuid`.execute(tx);}catch(error){guardRejected=(error as {code?:string}).code==="23514";}finally{await sql`ROLLBACK TO SAVEPOINT stage2_guard_probe`.execute(tx);}assert(guardRejected,"published organization scope must be immutable");
  await assert.rejects(service.publishCalendarDay(context(reviewer),String(dayDraft["id"]),1),{status:409});
  await assert.rejects(service.draftCalendarDay(context(actor),{companyCodeId,calendarId:String(calendarDraft.id),holidayDate:today,name:"Past date"}),{status:400});
  await assert.rejects(service.draftSetup(context(actor),{kind:"site",companyCodeId:"99999999-9999-4999-8999-999999999999",code:`${setupCode}-wrong`,name:"Wrong scope",siteType:"office"}),{status:403});

  await assert.rejects(service.requestOwnProfileChange(context(serviceAccount),{idempotencyKey:"stage2-service-account",preferredName:"Denied"}),{status:403});
  await assert.rejects(service.catalog(context(actor),"99999999-9999-4999-8999-999999999999"),{status:403});
  allow=false;await assert.rejects(service.catalog(context(actor),companyCodeId),{status:403});
  allow=true;
  const overlapping=await service.createPolicyAssignment(context(actor),{idempotencyKey:`stage2-overlap-${Date.now()}`,policyDefinitionId,scopeKind:"company",countryCode:"CA",companyCodeId,effectiveFrom:"2026-09-22"});
  await assert.rejects(service.publishPolicyAssignment(context(reviewer),String(overlapping["id"]),1),{status:409});
  passed=true;throw rollback;
});}catch(error){if(error!==rollback)throw error;}finally{await db.destroy();}
assert(passed);console.log("HR_STAGE2_SERVICE_ROLLBACK_OK");
