import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { Application, NextFunction, Request, RequestHandler, Response } from "@athyper/server-runtime-http";
import { NeonAccountBankLinkageError, type BusinessPartnerAccountBankLinkageService, type MeshBankDisclosureEnvelope } from "./business-partner-account-bank-linkage.js";

export function registerBusinessPartnerAccountBankLinkageRoutes(app:Application,options:{authenticate:RequestHandler;readContext:(response:Response)=>VerifiedRequestContext;service:BusinessPartnerAccountBankLinkageService;telemetry?:(event:{operation:string;outcome:"success"|"denied"|"error";statusCode:number;durationMs:number})=>void}){
 const route=(operation:string,work:(request:Request,context:VerifiedRequestContext,response:Response)=>Promise<unknown>):RequestHandler=>async(request,response,next)=>{const started=performance.now();let outcome:"success"|"denied"|"error"="success",statusCode=200;try{const result=await work(request,options.readContext(response),response);if(!response.headersSent)response.json(result);statusCode=response.statusCode;}catch(cause){outcome=cause instanceof NeonAccountBankLinkageError&&cause.status===403?"denied":"error";statusCode=cause instanceof NeonAccountBankLinkageError?cause.status:500;handle(cause,response,next);}finally{options.telemetry?.({operation,outcome,statusCode,durationMs:performance.now()-started});}};
 app.post("/api/neon/mesh-business-partner-account-links",options.authenticate,route("link.request",async(req,ctx,res)=>{const b=object(req.body),result=await options.service.requestAccountLink({context:ctx,profileProjectionId:uuid(b["profileProjectionId"],"profileProjectionId"),businessPartnerId:uuid(b["businessPartnerId"],"businessPartnerId"),...(b["onboardingRequestId"]?{onboardingRequestId:uuid(b["onboardingRequestId"],"onboardingRequestId")}:{}),idempotencyKey:text(b["idempotencyKey"]??req.get("idempotency-key"),"idempotencyKey")});res.status(result.replayed?200:201);return result;}));
 app.get("/api/neon/mesh-business-partner-account-links/:linkId",options.authenticate,route("link.read",(req,ctx)=>options.service.getAccountLink({context:ctx,linkId:uuid(req.params["linkId"],"linkId")})));
 app.post("/api/neon/mesh-business-partner-account-links/:linkId/decisions",options.authenticate,route("link.decide",(req,ctx)=>{const b=object(req.body);return options.service.decideAccountLink({context:ctx,linkId:uuid(req.params["linkId"],"linkId"),decision:choice(b["decision"],["approve","reject"]as const,"decision"),...(b["reason"]?{reason:String(b["reason"])}:{})});}));
 app.post("/api/neon/mesh-bank-account-events",options.authenticate,route("bank.receive",async(req,ctx,res)=>{const result=await options.service.receiveBankDisclosure({context:ctx,envelope:object(req.body)as unknown as MeshBankDisclosureEnvelope});res.status(result.disposition==="applied"?201:202);return result;}));
 app.post("/api/neon/business-partner-bank-verifications",options.authenticate,route("bank.verify.start",async(req,ctx,res)=>{const b=object(req.body),result=await options.service.startBankVerification({context:ctx,bankProjectionId:uuid(b["bankProjectionId"],"bankProjectionId"),supplierCompanyProfileId:uuid(b["supplierCompanyProfileId"],"supplierCompanyProfileId"),idempotencyKey:text(b["idempotencyKey"]??req.get("idempotency-key"),"idempotencyKey")});res.status(result.replayed?200:201);return result;}));
 app.post("/api/neon/business-partner-bank-verifications/:verificationId/decisions",options.authenticate,route("bank.verify.decide",(req,ctx)=>{const b=object(req.body);return options.service.decideBankVerification({context:ctx,verificationId:uuid(req.params["verificationId"],"verificationId"),decision:choice(b["decision"],["verify","reject"]as const,"decision"),...(b["candidateBankAccountLinkId"]?{candidateBankAccountLinkId:uuid(b["candidateBankAccountLinkId"],"candidateBankAccountLinkId")}:{}),...(b["verificationMethod"]?{verificationMethod:String(b["verificationMethod"])}:{}),...(b["evidence"]?{evidence:object(b["evidence"])}:{}),...(b["reason"]?{reason:String(b["reason"])}:{})});}));
 app.post("/api/neon/business-partner-bank-verifications/:verificationId/applications",options.authenticate,route("bank.apply",(req,ctx)=>options.service.applyBankVerification({context:ctx,verificationId:uuid(req.params["verificationId"],"verificationId")})));
}
function object(v:unknown){if(!v||typeof v!=="object"||Array.isArray(v))throw invalid("JSON object required");return v as Record<string,unknown>;}function text(v:unknown,name:string){const x=String(v??"");if(!x)throw invalid(`${name} is required`);return x;}function uuid(v:unknown,name:string){const x=text(v,name);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x))throw invalid(`${name} must be a UUID`);return x;}function choice<const T extends readonly string[]>(v:unknown,values:T,name:string):T[number]{const x=String(v);if(!values.includes(x))throw invalid(`${name} must be ${values.join(" or ")}`);return x as T[number];}function invalid(message:string){return new NeonAccountBankLinkageError(400,"NEON_ACCOUNT_BANK_INVALID",message);}function handle(cause:unknown,response:Response,next:NextFunction){if(!(cause instanceof NeonAccountBankLinkageError)){next(cause);return;}response.status(cause.status).type("application/problem+json").json({type:`https://athyper.dev/problems/${cause.code.toLowerCase()}`,title:cause.code,status:cause.status,detail:cause.message,code:cause.code});}
