import { createHash } from "node:crypto";
import { sql, type Transaction } from "kysely";
import type { Authorizer, VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { BusinessPartnerRequestService } from "@athyper/server-contract-master-data";

type Tx = Transaction<Record<string, never>>;
type Row = Readonly<Record<string, unknown>>;
const ALGORITHM = Object.freeze({ code: "mesh_business_partner_candidate_v1", version: 1, weights: { accountCode: 100, legalName: 80, displayName: 60, websiteHost: 25, countryCode: 10 }, tieBreak: ["score_desc", "code_asc", "id_asc"] });
export const businessPartnerProfileMatchPermissions = Object.freeze({ create: "neon.business_partner_profile_match.create", read: "neon.business_partner_profile_match.read", request: "neon.business_partner_profile_match.request" } as const);
export const acceptedMeshBusinessPartnerFieldPaths = Object.freeze(["partner.accountCode", "partner.displayName", "partner.legalName", "partner.legalForm", "partner.countryCode", "partner.incorporationDate", "partner.websiteUrl", "partner.description"] as const);

export class NeonProfileMatchError extends Error { constructor(readonly status: number, readonly code: string, message: string) { super(message); this.name = "NeonProfileMatchError"; } }
export interface ProfileMatchTransactions { run<T>(plane: "neon", actor: { tenantId: string; principalId: string; requestId?: string; correlationId?: string }, work: (tx: Tx) => Promise<T>): Promise<T>; }
export interface ProfileMatchCandidate { readonly businessPartnerId: string; readonly code: string; readonly name: string; readonly displayName?: string; readonly legalName?: string; readonly legalForm?: string; readonly countryCode?: string; readonly incorporationDate?: string; readonly websiteUrl?: string; readonly description?: string; readonly score: number; readonly reasons: readonly string[]; readonly fingerprint: string; }
export interface ProfileMatch { readonly id: string; readonly snapshotId: string; readonly projectionId: string; readonly sourcePayloadHash: string; readonly sourcePublicationVersion: number; readonly operatingOrganizationId: string; readonly companyCodeId?: string; readonly candidateBusinessPartnerId?: string; readonly algorithm: { readonly code: string; readonly version: number; readonly hash: string }; readonly rankedCandidates: readonly ProfileMatchCandidate[]; readonly fieldDiff: readonly Readonly<Record<string, unknown>>[]; readonly diffHash: string; readonly createdAt: string; readonly replayed: boolean; }

export interface BusinessPartnerProfileMatchRepository {
  source(tenantId: string, snapshotId: string, tx: Tx): Promise<{ projectionId: string; publicationId: string; publicationVersion: number; payloadHash: string; payload: Readonly<Record<string, unknown>> } | null>;
  candidates(tenantId: string, operatingOrganizationId: string, tx: Tx): Promise<readonly CandidateRow[]>;
  matchByKey(tenantId: string, key: string, tx: Tx): Promise<Row | null>;
  match(tenantId: string, id: string, tx: Tx): Promise<Row | null>;
  createMatch(input: MatchInsert, tx: Tx): Promise<Row | null>;
  acceptanceByKey(tenantId: string, key: string, tx: Tx): Promise<Row | null>;
  createAcceptance(input: AcceptanceInsert, tx: Tx): Promise<Row | null>;
  caseEvent(tenantId: string, acceptanceId: string, tx: Tx): Promise<Row | null>;
  appendCaseEvent(input: { tenantId: string; acceptanceId: string; caseId: string; fingerprint: string; principalId: string }, tx: Tx): Promise<void>;
}
interface CandidateRow { id: string; code: string; name: string; displayName?: string; legalName?: string; legalForm?: string; countryCode?: string; incorporationDate?: string; websiteUrl?: string; description?: string; }
interface MatchInsert { tenantId: string; projectionId: string; snapshotId: string; payloadHash: string; publicationVersion: number; operatingOrganizationId: string; companyCodeId?: string; candidateId?: string; candidateFingerprint?: string; algorithmHash: string; ranked: readonly ProfileMatchCandidate[]; diff: readonly Readonly<Record<string, unknown>>[]; diffHash: string; key: string; principalId: string; }
interface AcceptanceInsert { tenantId: string; matchId: string; snapshotId: string; paths: readonly string[]; payload: Readonly<Record<string, unknown>>; hash: string; key: string; principalId: string; }

export class KyselyBusinessPartnerProfileMatchRepository implements BusinessPartnerProfileMatchRepository {
  async source(tenantId: string, snapshotId: string, tx: Tx) { const row=(await sql<Row>`SELECT p.id projection_id,s.publication_id,s.publication_version,s.payload_hash,s.payload_json FROM snapshot.mesh_business_partner_profile_received s JOIN control.mesh_business_partner_profile_projection p ON p.tenant_id=s.tenant_id AND p.current_snapshot_id=s.id WHERE s.tenant_id=${tenantId}::uuid AND s.id=${snapshotId}::uuid AND p.projection_status='active'`.execute(tx)).rows[0]; return row?{projectionId:String(row["projection_id"]),publicationId:String(row["publication_id"]),publicationVersion:Number(row["publication_version"]),payloadHash:String(row["payload_hash"]),payload:object(row["payload_json"])}:null; }
  async candidates(tenantId: string, operatingOrganizationId: string, tx: Tx) { const rows=(await sql<Row>`SELECT DISTINCT bp.id,bp.code,bp.name,bp.display_name,bp.legal_name,bp.legal_form,bp.registration_country_code,bp.incorporation_date,bp.website_url,bp.description FROM master.business_partner bp JOIN master.business_partner_operating_organization_assignment a ON a.tenant_id=bp.tenant_id AND a.business_partner_id=bp.id WHERE bp.tenant_id=${tenantId}::uuid AND a.operating_organization_id=${operatingOrganizationId}::uuid AND bp.is_active AND a.is_active ORDER BY bp.code,bp.id LIMIT 500`.execute(tx)).rows; return rows.map(row=>({id:String(row["id"]),code:String(row["code"]),name:String(row["name"]),...optional(row,"display_name","displayName"),...optional(row,"legal_name","legalName"),...optional(row,"legal_form","legalForm"),...optional(row,"registration_country_code","countryCode"),...optional(row,"incorporation_date","incorporationDate"),...optional(row,"website_url","websiteUrl"),...optional(row,"description","description")})); }
  async matchByKey(tenantId:string,key:string,tx:Tx){return (await sql<Row>`SELECT * FROM document.mesh_business_partner_match WHERE tenant_id=${tenantId}::uuid AND idempotency_key=${key}`.execute(tx)).rows[0]??null;}
  async match(tenantId:string,id:string,tx:Tx){return (await sql<Row>`SELECT * FROM document.mesh_business_partner_match WHERE tenant_id=${tenantId}::uuid AND id=${id}::uuid`.execute(tx)).rows[0]??null;}
  async createMatch(i:MatchInsert,tx:Tx){return (await sql<Row>`INSERT INTO document.mesh_business_partner_match(tenant_id,projection_id,snapshot_id,source_payload_hash,source_publication_version,operating_organization_id,company_code_id,candidate_business_partner_id,candidate_fingerprint,algorithm_code,algorithm_version,algorithm_hash,ranked_candidates,field_diff,diff_hash,idempotency_key,created_by) VALUES(${i.tenantId}::uuid,${i.projectionId}::uuid,${i.snapshotId}::uuid,${i.payloadHash},${i.publicationVersion},${i.operatingOrganizationId}::uuid,${i.companyCodeId??null}::uuid,${i.candidateId??null}::uuid,${i.candidateFingerprint??null},${ALGORITHM.code},${ALGORITHM.version},${i.algorithmHash},${JSON.stringify(i.ranked)}::jsonb,${JSON.stringify(i.diff)}::jsonb,${i.diffHash},${i.key},${i.principalId}::uuid) ON CONFLICT(tenant_id,idempotency_key) DO NOTHING RETURNING *`.execute(tx)).rows[0]??null;}
  async acceptanceByKey(tenantId:string,key:string,tx:Tx){return (await sql<Row>`SELECT a.*,linked.entity_case_id FROM document.mesh_business_partner_acceptance a LEFT JOIN LATERAL(SELECT COALESCE(event.entity_case_id,NULLIF(to_jsonb(event)->>'business_partner_request_id','')::uuid)entity_case_id FROM document.mesh_business_partner_acceptance_event event WHERE event.tenant_id=a.tenant_id AND event.acceptance_id=a.id AND event.event_kind IN('case_created','request_created') ORDER BY(event.event_kind='case_created')DESC,event.lifecycle_version DESC LIMIT 1)linked ON true WHERE a.tenant_id=${tenantId}::uuid AND a.request_idempotency_key=${key}`.execute(tx)).rows[0]??null;}
  async createAcceptance(i:AcceptanceInsert,tx:Tx){const row=(await sql<Row>`INSERT INTO document.mesh_business_partner_acceptance(tenant_id,match_id,snapshot_id,accepted_field_paths,proposed_payload,acceptance_hash,request_idempotency_key,created_by) VALUES(${i.tenantId}::uuid,${i.matchId}::uuid,${i.snapshotId}::uuid,${i.paths}::text[],${JSON.stringify(i.payload)}::jsonb,${i.hash},${i.key},${i.principalId}::uuid) ON CONFLICT(tenant_id,request_idempotency_key) DO NOTHING RETURNING *`.execute(tx)).rows[0]; if(row) await sql`INSERT INTO document.mesh_business_partner_acceptance_event(tenant_id,acceptance_id,lifecycle_version,event_kind,event_fingerprint,recorded_by) VALUES(${i.tenantId}::uuid,${String(row["id"])}::uuid,1,'prepared',${i.hash},${i.principalId}::uuid)`.execute(tx); return row??null;}
  async caseEvent(tenantId:string,acceptanceId:string,tx:Tx){return (await sql<Row>`SELECT event.*,COALESCE(event.entity_case_id,NULLIF(to_jsonb(event)->>'business_partner_request_id','')::uuid)entity_case_id FROM document.mesh_business_partner_acceptance_event event WHERE event.tenant_id=${tenantId}::uuid AND event.acceptance_id=${acceptanceId}::uuid AND event.event_kind IN('case_created','request_created') ORDER BY(event.event_kind='case_created')DESC,event.lifecycle_version DESC LIMIT 1`.execute(tx)).rows[0]??null;}
  async appendCaseEvent(i:{tenantId:string;acceptanceId:string;caseId:string;fingerprint:string;principalId:string},tx:Tx){await sql`INSERT INTO document.mesh_business_partner_acceptance_event(tenant_id,acceptance_id,lifecycle_version,event_kind,entity_case_id,event_fingerprint,recorded_by) VALUES(${i.tenantId}::uuid,${i.acceptanceId}::uuid,2,'case_created',${i.caseId}::uuid,${i.fingerprint},${i.principalId}::uuid) ON CONFLICT(tenant_id,acceptance_id,lifecycle_version) DO NOTHING`.execute(tx);}
}

export function createBusinessPartnerProfileMatchService(options:{authorizer:Authorizer;repository:BusinessPartnerProfileMatchRepository;transactions:ProfileMatchTransactions;businessPartnerRequests:BusinessPartnerRequestService}) {
  return Object.freeze({
    async create(input:{context:VerifiedRequestContext;snapshotId:string;operatingOrganizationId:string;companyCodeId?:string;candidateBusinessPartnerId?:string;idempotencyKey:string}) {
      validateContext(input.context); const snapshotId=uuid(input.snapshotId,"snapshotId"), orgId=uuid(input.operatingOrganizationId,"operatingOrganizationId"), companyId=input.companyCodeId?uuid(input.companyCodeId,"companyCodeId"):undefined, candidateId=input.candidateBusinessPartnerId?uuid(input.candidateBusinessPartnerId,"candidateBusinessPartnerId"):undefined, key=idempotency(input.idempotencyKey);
      await authorize(options.authorizer,input.context,businessPartnerProfileMatchPermissions.create,orgId,companyId);
      return options.transactions.run("neon",actor(input.context),async tx=>{
        const existing=await options.repository.matchByKey(input.context.tenantId,key,tx); if(existing) { if(String(existing["snapshot_id"])!==snapshotId||String(existing["operating_organization_id"])!==orgId||nullable(existing["company_code_id"])!==companyId||nullable(existing["candidate_business_partner_id"])!==candidateId)throw failure(409,"MESH_PROFILE_MATCH_KEY_COLLISION","Idempotency key was reused with different match coordinates");return mapMatch(existing,true); }
        const source=await options.repository.source(input.context.tenantId,snapshotId,tx); if(!source) throw failure(409,"MESH_PROFILE_SNAPSHOT_NOT_ACTIVE","Snapshot is not the current active verified MESH projection");
        const partner=object(source.payload["partner"]); const ranked=(await options.repository.candidates(input.context.tenantId,orgId,tx)).map(candidate=>rank(partner,candidate)).sort((a,b)=>b.score-a.score||a.code.localeCompare(b.code)||a.businessPartnerId.localeCompare(b.businessPartnerId));
        const selected=candidateId?ranked.find(value=>value.businessPartnerId===candidateId):undefined;
        if(candidateId&&!selected) throw failure(409,"MESH_PROFILE_CANDIDATE_OUT_OF_SCOPE","Candidate is not active in the selected operating organization");
        const diff=makeDiff(partner,selected); const diffHash=hash(diff),algorithmHash=hash(ALGORITHM);
        const created=await options.repository.createMatch({tenantId:input.context.tenantId,projectionId:source.projectionId,snapshotId,payloadHash:source.payloadHash,publicationVersion:source.publicationVersion,operatingOrganizationId:orgId,...(companyId?{companyCodeId:companyId}:{}),...(selected?{candidateId:selected.businessPartnerId,candidateFingerprint:selected.fingerprint}:{}),algorithmHash,ranked,diff,diffHash,key,principalId:input.context.principalId},tx);
        return mapMatch(created??(await options.repository.matchByKey(input.context.tenantId,key,tx))!,!created);
      });
    },
    async get(input:{context:VerifiedRequestContext;matchId:string}) { validateContext(input.context); const id=uuid(input.matchId,"matchId"); return options.transactions.run("neon",actor(input.context),async tx=>{const row=await options.repository.match(input.context.tenantId,id,tx);if(!row)throw failure(404,"MESH_PROFILE_MATCH_NOT_FOUND","Match was not found");await authorize(options.authorizer,input.context,businessPartnerProfileMatchPermissions.read,String(row["operating_organization_id"]),nullable(row["company_code_id"]));return mapMatch(row,false);}); },
    async createRequest(input:{context:VerifiedRequestContext;matchId:string;acceptedFieldPaths:readonly string[];idempotencyKey:string}) {
      validateContext(input.context); const matchId=uuid(input.matchId,"matchId"),key=idempotency(input.idempotencyKey),paths=pathsOf(input.acceptedFieldPaths);
      const prepared=await options.transactions.run("neon",actor(input.context),async tx=>{const match=await options.repository.match(input.context.tenantId,matchId,tx);if(!match)throw failure(404,"MESH_PROFILE_MATCH_NOT_FOUND","Match was not found");await authorize(options.authorizer,input.context,businessPartnerProfileMatchPermissions.request,String(match["operating_organization_id"]),nullable(match["company_code_id"]));const source=await options.repository.source(input.context.tenantId,String(match["snapshot_id"]),tx);if(!source)throw failure(409,"MESH_PROFILE_SNAPSHOT_NOT_ACTIVE","Pinned source snapshot was withdrawn or superseded before acceptance");const payload=acceptedPayload(object(source.payload["partner"]),paths);const acceptanceHash=hash({matchId,paths,payload,sourcePayloadHash:String(match["source_payload_hash"])});let acceptance=await options.repository.acceptanceByKey(input.context.tenantId,key,tx);if(acceptance&&String(acceptance["acceptance_hash"])!==acceptanceHash)throw failure(409,"MESH_PROFILE_ACCEPTANCE_KEY_COLLISION","Idempotency key was reused with different accepted fields");acceptance??=await options.repository.createAcceptance({tenantId:input.context.tenantId,matchId,snapshotId:String(match["snapshot_id"]),paths,payload,hash:acceptanceHash,key,principalId:input.context.principalId},tx);acceptance??=await options.repository.acceptanceByKey(input.context.tenantId,key,tx);return{match,source,acceptance:acceptance!,payload,acceptanceHash};});
      const existingRequestId=nullable(prepared.acceptance["entity_case_id"]); if(existingRequestId)return{acceptanceId:String(prepared.acceptance["id"]),caseId:existingRequestId,requestId:existingRequestId,replayed:true};
      const proposedRole=meshProposedRole(prepared.source.payload),target=nullable(prepared.match["candidate_business_partner_id"]);
      const result=await options.businessPartnerRequests.create({context:input.context,idempotencyKey:`mesh-match:${key}`,kind:target?(proposedRole==="customer"?"add_customer":"add_supplier"):"new_partner",source:{kind:"mesh",systemCode:"athyper_mesh",entityCode:`${proposedRole}_business_partner_profile`,entityId:prepared.source.publicationId,projectionId:String(prepared.match["snapshot_id"]),version:prepared.source.publicationVersion,payloadHash:prepared.source.payloadHash},...(target?{targetBusinessPartnerId:target}:{}),requestedRole:proposedRole,operatingOrganizationId:String(prepared.match["operating_organization_id"]),...(prepared.match["company_code_id"]?{companyCodeId:String(prepared.match["company_code_id"])}:{}),proposedPayload:{...prepared.payload,partnerCategory:"organization",...(proposedRole==="customer"?{customerType:"corporate"}:{supplierType:"general"})}});
      await options.transactions.run("neon",actor(input.context),tx=>options.repository.appendCaseEvent({tenantId:input.context.tenantId,acceptanceId:String(prepared.acceptance["id"]),caseId:result.request.id,fingerprint:hash({acceptanceHash:prepared.acceptanceHash,caseId:result.request.id}),principalId:input.context.principalId},tx));
      return{acceptanceId:String(prepared.acceptance["id"]),caseId:result.request.id,requestId:result.request.id,replayed:result.replayed};
    }
  });
}
export type BusinessPartnerProfileMatchService=ReturnType<typeof createBusinessPartnerProfileMatchService>;

function rank(source:Readonly<Record<string,unknown>>,candidate:CandidateRow):ProfileMatchCandidate{let score=0;const reasons:string[]=[];const add=(ok:boolean,points:number,reason:string)=>{if(ok){score+=points;reasons.push(reason);}};add(normal(source["accountCode"])===normal(candidate.code),100,"ACCOUNT_CODE_EXACT");add(normal(source["legalName"])===normal(candidate.legalName),80,"LEGAL_NAME_NORMALIZED");add(normal(source["displayName"])===normal(candidate.displayName??candidate.name),60,"DISPLAY_NAME_NORMALIZED");add(host(source["websiteUrl"])!==""&&host(source["websiteUrl"])===host(candidate.websiteUrl),25,"WEBSITE_HOST_EXACT");add(normal(source["countryCode"])!==""&&normal(source["countryCode"])===normal(candidate.countryCode),10,"COUNTRY_CODE_EXACT");const base={businessPartnerId:candidate.id,code:candidate.code,name:candidate.name,...(candidate.displayName?{displayName:candidate.displayName}:{}),...(candidate.legalName?{legalName:candidate.legalName}:{}),...(candidate.legalForm?{legalForm:candidate.legalForm}:{}),...(candidate.countryCode?{countryCode:candidate.countryCode}:{}),...(candidate.incorporationDate?{incorporationDate:candidate.incorporationDate}:{}),...(candidate.websiteUrl?{websiteUrl:candidate.websiteUrl}:{}),...(candidate.description?{description:candidate.description}:{}),score,reasons};return{...base,fingerprint:hash(base)};}
function makeDiff(source:Readonly<Record<string,unknown>>,candidate?:ProfileMatchCandidate){return acceptedMeshBusinessPartnerFieldPaths.map(path=>{const field=path.slice(8);const sourceValue=source[field]??null;const candidateValue=candidate?candidate[field as keyof ProfileMatchCandidate]??null:null;return{path,sourceValue,candidateValue,equal:stable(sourceValue)===stable(candidateValue)};});}
function acceptedPayload(source:Readonly<Record<string,unknown>>,paths:readonly string[]){if(!paths.includes("partner.legalName"))throw failure(400,"MESH_PROFILE_LEGAL_NAME_REQUIRED","Legal name must be explicitly accepted for the onboarding request");const map:Record<string,string>={accountCode:"partnerCode",displayName:"displayName",legalName:"legalName",legalForm:"legalForm",countryCode:"registrationCountryCode",incorporationDate:"incorporationDate",websiteUrl:"websiteUrl",description:"description"};const result:Record<string,unknown>={};for(const path of paths){const field=path.slice(8),value=source[field];if(value!==undefined&&value!==null&&String(value).trim()!=="")result[map[field]!]=value;}if(!result["legalName"])throw failure(409,"MESH_PROFILE_LEGAL_NAME_MISSING","Pinned MESH snapshot has no legal name to accept");return result;}
function meshProposedRole(payload:Readonly<Record<string,unknown>>):"supplier"|"customer"{const recipient=object(payload["recipient"]),role=recipient["proposedNeonRole"];if(role!=="supplier"&&role!=="customer")throw failure(409,"MESH_PROFILE_ROLE_INVALID","Verified MESH projection must propose supplier or customer role");return role;}
function mapMatch(row:Row,replayed:boolean):ProfileMatch{return{id:String(row["id"]),snapshotId:String(row["snapshot_id"]),projectionId:String(row["projection_id"]),sourcePayloadHash:String(row["source_payload_hash"]),sourcePublicationVersion:Number(row["source_publication_version"]),operatingOrganizationId:String(row["operating_organization_id"]),...(row["company_code_id"]?{companyCodeId:String(row["company_code_id"])}:{}),...(row["candidate_business_partner_id"]?{candidateBusinessPartnerId:String(row["candidate_business_partner_id"])}:{}),algorithm:{code:String(row["algorithm_code"]),version:Number(row["algorithm_version"]),hash:String(row["algorithm_hash"])},rankedCandidates:array(row["ranked_candidates"]) as unknown as ProfileMatchCandidate[],fieldDiff:array(row["field_diff"]) as Readonly<Record<string,unknown>>[],diffHash:String(row["diff_hash"]),createdAt:new Date(String(row["created_at"])).toISOString(),replayed};}
async function authorize(authorizer:Authorizer,context:VerifiedRequestContext,permissionCode:string,orgId:string,companyId?:string){const decision=await authorizer.authorize({context,permissionCode,resource:{tenantId:context.tenantId,operatingOrganizationId:orgId,...(companyId?{companyCodeId:companyId}:{})}});if(!decision.allowed)throw failure(403,"FORBIDDEN",`Permission denied: ${permissionCode}`);}
function validateContext(value:VerifiedRequestContext){if(value.planeKey!=="neon")throw failure(400,"NEON_PROFILE_MATCH_REQUIRED","Profile matching executes only in NEON");}
function actor(value:VerifiedRequestContext){return{tenantId:value.tenantId,principalId:value.principalId,requestId:value.requestId,correlationId:value.correlationId};}
function pathsOf(values:readonly string[]){if(!Array.isArray(values)||values.length<1||values.length>8)throw failure(400,"MESH_PROFILE_ACCEPTANCE_INVALID","Select between one and eight supported fields");const paths=[...new Set(values)].sort();if(paths.length!==values.length||paths.some(path=>!(acceptedMeshBusinessPartnerFieldPaths as readonly string[]).includes(path)))throw failure(400,"MESH_PROFILE_ACCEPTANCE_INVALID","Accepted fields must be unique supported MESH profile paths");return paths;}
function idempotency(value:string){const text=String(value).trim();if(text.length<8||text.length>200)throw failure(400,"MESH_PROFILE_IDEMPOTENCY_INVALID","Idempotency key must contain 8 to 200 characters");return text;}
function uuid(value:string,name:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value)))throw failure(400,"MESH_PROFILE_MATCH_INVALID",`${name} must be a UUID`);return String(value);}
function object(value:unknown):Readonly<Record<string,unknown>>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Readonly<Record<string,unknown>>:{};}
function array(value:unknown):readonly unknown[]{return Array.isArray(value)?value:[];}
function optional(row:Row,column:string,key:string){return row[column]==null?{}:{[key]:String(row[column])};}
function nullable(value:unknown){return value==null?undefined:String(value);}
function normal(value:unknown){return String(value??"").normalize("NFKC").trim().toLocaleLowerCase("en").replace(/[^a-z0-9]/g,"");}
function host(value:unknown){try{return new URL(String(value??"")).hostname.toLowerCase().replace(/^www\./,"");}catch{return "";}}
function stable(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;return`{${Object.entries(value as Record<string,unknown>).filter(([,v])=>v!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;}
function hash(value:unknown){return createHash("sha256").update(stable(value)).digest("hex");}
function failure(status:number,code:string,message:string){return new NeonProfileMatchError(status,code,message);}
