import { describe,expect,it,vi } from "vitest";
import type { JobHandler } from "@athyper/server-contract-jobs";
import { financeEntryPoints,type NeonFinanceRegistration } from "./register-finance.js";
import { financeJobDefinitions,financeWorkerNames,registerFinanceJobHandlers } from "./finance-jobs.js";

const actor={tenantId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",principalId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",planeKey:"neon" as const,correlationId:"correlation",permissionCodes:["finance.planning.run"]};
function registration():NeonFinanceRegistration{return{executionPlane:"neon",flags:{f2BudgetPlanning:true,f3LedgerCommitments:false,f4InventoryFifo:false,f5Tax:false,f6Closing:false},slices:{f2:{enabled:true,entryPoints:financeEntryPoints.f2,services:{},readiness:async()=>({status:"healthy"})},f3:{enabled:false,entryPoints:financeEntryPoints.f3,services:{},readiness:async()=>({status:"healthy"})},f4:{enabled:false,entryPoints:financeEntryPoints.f4,services:{},readiness:async()=>({status:"healthy"})},f5:{enabled:false,entryPoints:financeEntryPoints.f5,services:{},readiness:async()=>({status:"healthy"})},f6:{enabled:false,entryPoints:financeEntryPoints.f6,services:{},readiness:async()=>({status:"healthy"})}},enqueue:vi.fn(),executeWorker:vi.fn(async()=>({runId:"run"}))};}
function envelope(tenantId=actor.tenantId){return{id:"job",name:"finance.planning.execute",queue:"finance",data:{actor,runId:"run"},attempt:1,maxAttempts:5,enqueuedAt:new Date().toISOString(),execution:{planeKey:"neon" as const,scope:"tenant" as const,tenantId,principalId:actor.principalId}};}
describe("finance durable handlers",()=>{
  it("binds every declared worker exactly once",()=>{const declared=Object.values(financeEntryPoints).flat().filter(point=>point.kind==="worker").map(point=>point.code);expect([...financeWorkerNames].sort()).toEqual([...new Set(declared)].sort());});
  it("registers definitions only for enabled slice workers",()=>{expect(financeJobDefinitions(registration()).map(item=>item.name)).toEqual(["finance.planning.execute"]);});
  it("executes through the composition worker and rejects coordinate drift",async()=>{const finance=registration(),handlers=new Map<string,JobHandler>();registerFinanceJobHandlers({register:(_queue,name,handler)=>handlers.set(name,handler)},finance);const handler=handlers.get("finance.planning.execute")!;await expect(handler.handle(envelope(),{signal:new AbortController().signal,attempt:1,reportProgress:async()=>undefined})).resolves.toEqual({status:"completed",output:{result:{runId:"run"}}});expect(finance.executeWorker).toHaveBeenCalledWith("finance.planning.execute",expect.objectContaining({runId:"run"}));await expect(handler.handle(envelope("dddddddd-dddd-4ddd-8ddd-dddddddddddd"),{signal:new AbortController().signal,attempt:1,reportProgress:async()=>undefined})).rejects.toThrow("FINANCE_JOB_COORDINATE_MISMATCH");});
});
