#!/usr/bin/env tsx
import {readFile} from "node:fs/promises";import{resolve}from"node:path";import pg from"pg";
const ACTOR="00000000-0000-0000-0000-000000000000";
function arg(n:string){return process.argv.find(v=>v.startsWith(`${n}=`))?.slice(n.length+1)}
type Plane="neon"|"mesh";type Action="prepare"|"certify"|"activate"|"rollback"|"status";
interface Coordinate{plane:Plane;entityCode:string;operationKey:string;sourceEntityOperationId:string;sourceReleaseHash:string;sourceArtifactHash:string}
interface Manifest{contractVersion:string;operations:Coordinate[]}
const url=arg("--database-url"),expected=arg("--expected-database"),plane=arg("--plane") as Plane,action=(arg("--action")??"status") as Action,operation=arg("--operation"),reason=arg("--reason")??`P5-E6 ${action}`,ticket=arg("--ticket")??null;
if(!url||!expected||!["neon","mesh"].includes(plane)||!["prepare","certify","activate","rollback","status"].includes(action))throw new Error("Explicit URL/database/plane and valid action required");
if(["activate","rollback"].includes(action)&&!operation)throw new Error(`${action} requires --operation`);
const manifest=JSON.parse(await readFile(resolve(import.meta.dirname,"../../config/qualification/p5-e6-operation-activation-manifest.v1.json"),"utf8")) as Manifest;
const selected=manifest.operations.filter(x=>x.plane===plane&&(!operation||x.operationKey===operation));if(!selected.length)throw new Error("manifest coordinate not found");
const client=new pg.Client({connectionString:url});await client.connect();
try{const identity=await client.query<{database_name:string}>("select current_database() database_name");if(identity.rows[0]?.database_name!==expected)throw new Error("P5-E6 database guard rejected target");await client.query("begin");await client.query("select set_config('app.database_plane',$1,true)",[plane]);
 for(const c of selected){const binding=await client.query(`select 1 from authz.entity_operation_scope_binding where plane_code=$1 and entity_code=$2 and operation_key=$3 and source_entity_operation_id=$4::uuid and source_release_hash=$5 and source_compiled_hash=$6 and status='published' limit 1`,[plane,c.entityCode,c.operationKey,c.sourceEntityOperationId,c.sourceReleaseHash,c.sourceArtifactHash]);if(!binding.rowCount)throw new Error(`manifest drift:${c.operationKey}`);
  if(action==="prepare")await client.query("select ops.set_authorization_operation_rollout($1,$2,$3::uuid,$4,$5,'shadow',$6::uuid,$7,$8)",[plane,c.entityCode,c.sourceEntityOperationId,c.sourceReleaseHash,c.sourceArtifactHash,ACTOR,reason,ticket]);
  if(action==="certify"||action==="activate"){const inserted=await client.query<{id:string}>("select ops.certify_authorization_operation_parity($1,$2,$3::uuid,$4,$5,$6::uuid)::text id",[plane,c.entityCode,c.sourceEntityOperationId,c.sourceReleaseHash,c.sourceArtifactHash,ACTOR]);const cert=await client.query<{status:string,sample_count:string,required_cohort_count:number,covered_cohort_count:number}>("select status,sample_count::text,required_cohort_count,covered_cohort_count from ops.authorization_parity_certification where id=$1::uuid",[inserted.rows[0]!.id]);const row=cert.rows[0]!;process.stdout.write(`P5_E6_CERT operation=${c.operationKey} status=${row.status} samples=${row.sample_count} cohorts=${row.covered_cohort_count}/${row.required_cohort_count}\n`);if(action==="activate")await client.query("select ops.set_authorization_operation_rollout($1,$2,$3::uuid,$4,$5,'active',$6::uuid,$7,$8)",[plane,c.entityCode,c.sourceEntityOperationId,c.sourceReleaseHash,c.sourceArtifactHash,ACTOR,reason,ticket]);}
  if(action==="rollback")await client.query("select ops.set_authorization_operation_rollout($1,$2,$3::uuid,$4,$5,'legacy',$6::uuid,$7,$8)",[plane,c.entityCode,c.sourceEntityOperationId,c.sourceReleaseHash,c.sourceArtifactHash,ACTOR,reason,ticket]);
 }
 await client.query("commit");const state=await client.query(`select r.entity_code,b.operation_key,r.mode,r.source_release_hash,r.source_artifact_hash,c.status certification_status,c.sample_count,c.covered_cohort_count,c.required_cohort_count from ops.authorization_operation_rollout r left join authz.entity_operation_scope_binding b on b.source_entity_operation_id=r.source_entity_operation_id and b.source_release_hash=r.source_release_hash and b.tenant_id is null left join ops.authorization_parity_certification c on c.id=r.certification_id where r.plane_code=$1 order by b.operation_key`,[plane]);process.stdout.write(JSON.stringify({manifest:manifest.contractVersion,plane,action,rows:state.rows},null,2)+"\n");
}catch(e){await client.query("rollback").catch(()=>{});throw e}finally{await client.end()}
