import type { VerifiedRequestContext } from "@athyper/server-contract-auth";

export type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };
export type EffectiveStatus = "draft" | "active" | "suspended" | "retired";
export interface EffectiveWindow { readonly effectiveFrom: string; readonly effectiveUntil?: string; }
export interface Versioned { readonly id: string; readonly version: number; }
export interface CacheInvalidator { invalidate(input: { readonly namespace: "features" | "parameters" | "lookups" | "rounding" | "entitlements" | "connectors"; readonly tenantId?: string; readonly keys?: readonly string[] }): Promise<void>; }

export interface FeatureFlagDefinition extends EffectiveWindow { readonly id: string; readonly code: string; readonly defaultEnabled: boolean; readonly rolloutPct?: number; readonly status: "active" | "retired"; }
export interface FeatureFlagOverride extends Versioned, EffectiveWindow { readonly tenantId: string; readonly featureFlagId: string; readonly enabled: boolean; readonly reason: string; readonly status: "active" | "expired"; }
export interface FeatureFlagRepository { getDefinition(code: string): Promise<FeatureFlagDefinition | undefined>; listDefinitions(): Promise<readonly FeatureFlagDefinition[]>; getOverride(tenantId: string, featureFlagId: string): Promise<FeatureFlagOverride | undefined>; saveOverride(input: Omit<FeatureFlagOverride, "id" | "version" | "status"> & { readonly id?: string; readonly expectedVersion?: number }, actorId: string): Promise<FeatureFlagOverride>; expireOverride(tenantId: string, id: string, expectedVersion: number | undefined, actorId: string): Promise<FeatureFlagOverride>; }

export type ParameterValueType = "boolean" | "integer" | "number" | "string" | "enum" | "duration" | "json";
export type ParameterReloadMode = "immediate" | "next_request" | "next_login" | "restart" | "external_provider";
export interface ParameterDefinition { readonly id: string; readonly code: string; readonly valueType: ParameterValueType; readonly defaultValue: JsonValue; readonly minValue?: number; readonly maxValue?: number; readonly allowedValues?: readonly JsonValue[]; readonly tenantCanOverride: boolean; readonly reloadMode: ParameterReloadMode; readonly cacheTtlSeconds: number; readonly status: "active" | "retired"; }
export interface TenantParameterValue extends Versioned, EffectiveWindow { readonly tenantId: string; readonly parameterDefinitionId: string; readonly value: JsonValue; readonly reason?: string; readonly status: "active" | "expired"; }
export interface ParameterRepository { getDefinition(code: string): Promise<ParameterDefinition | undefined>; listDefinitions(): Promise<readonly ParameterDefinition[]>; getValue(tenantId: string, definitionId: string): Promise<TenantParameterValue | undefined>; saveValue(input: Omit<TenantParameterValue, "id" | "version" | "status"> & { readonly id?: string; readonly expectedVersion?: number }, actorId: string): Promise<TenantParameterValue>; expireValue(tenantId: string, id: string, expectedVersion: number | undefined, actorId: string): Promise<TenantParameterValue>; }

export interface LookupValue { readonly id: string; readonly code: string; readonly name: string; readonly tenantId?: string; readonly sortOrder: number; readonly metadata: Readonly<Record<string, JsonValue>>; readonly status: "active" | "retired"; }
export interface LookupDomainRevision extends Versioned { readonly code: string; readonly name: string; readonly sourceSchema: string; readonly extensible: boolean; readonly values: readonly LookupValue[]; readonly status: "active" | "retired"; }
export interface LookupDesiredState { readonly desiredStateId: string; readonly targetPlane: "studio" | "neon" | "mesh"; readonly sourceRevision: number; readonly domain: LookupDomainRevision; }
export interface LookupRepository { getDomain(code: string, version?: number): Promise<LookupDomainRevision | undefined>; listDomains(): Promise<readonly LookupDomainRevision[]>; publishDesiredState(input: LookupDesiredState, actorId: string): Promise<LookupDomainRevision>; isValueReferenced(domainCode: string, valueCode: string, tenantId?: string): Promise<boolean>; retireValue(input: { readonly domainCode: string; readonly valueCode: string; readonly tenantId?: string; readonly expectedVersion?: number }, actorId: string): Promise<LookupDomainRevision>; }

export type RoundingMethod = "ROUND_HALF_UP" | "ROUND_HALF_EVEN" | "ROUND_UP" | "ROUND_DOWN" | "TRUNCATE";
export interface RoundingContext { readonly companyCodeId?: string; readonly currencyCode?: string; readonly slot?: string; }
export interface RoundingAggregate extends Versioned { readonly tenantId: string; readonly code: string; readonly name: string; readonly method: RoundingMethod; readonly precisionDigits?: number; readonly roundingIncrement?: string; readonly contexts: readonly RoundingContext[]; readonly status: EffectiveStatus; }
export interface RoundingRepository { list(tenantId: string): Promise<readonly RoundingAggregate[]>; get(tenantId: string, id: string): Promise<RoundingAggregate | undefined>; save(input: Omit<RoundingAggregate, "version"> & { readonly expectedVersion?: number }, actorId: string): Promise<RoundingAggregate>; retire(tenantId: string, id: string, expectedVersion: number | undefined, actorId: string): Promise<RoundingAggregate>; }
export interface RoundingSimulation { readonly input: string; readonly output: string; readonly ruleId: string; readonly ruleCode: string; readonly specificity: number; }

export interface BankValidationFixture { readonly input: BankValidationInput; readonly valid: boolean; }
export interface BankValidationInput { readonly countryCode: string; readonly currencyCode?: string; readonly railCode: string; readonly accountIdentifier?: string; readonly bankIdentifier?: string; readonly bic?: string; readonly branchCode?: string; }
export interface BankValidationRule extends Versioned { readonly code: string; readonly countryCode: string; readonly currencyCode?: string; readonly railCode: string; readonly priority: number; readonly accountRequired: boolean; readonly bankRequired: boolean; readonly bicAllowed: boolean; readonly bicRequired: boolean; readonly branchRequired: boolean; readonly accountPattern?: string; readonly bankPattern?: string; readonly branchPattern?: string; readonly checksumValidated: boolean; readonly fixtures: readonly BankValidationFixture[]; readonly status: "draft" | "active" | "retired"; }
export interface BankValidationRepository { list(): Promise<readonly BankValidationRule[]>; get(id: string): Promise<BankValidationRule | undefined>; publish(rule: BankValidationRule, actorId: string): Promise<BankValidationRule>; }
export interface BankValidationResult { readonly valid: boolean; readonly ruleId?: string; readonly issues: readonly string[]; }

export interface EntitlementPlan { readonly code: string; readonly version: number; readonly modules: readonly string[]; readonly limits: Readonly<Record<string, number | null>>; readonly effectiveFrom: string; readonly effectiveUntil?: string; }
export interface TenantEntitlementOverride extends Versioned, EffectiveWindow { readonly tenantId: string; readonly planCode: string; readonly moduleCode?: string; readonly limitCode?: string; readonly limitValue?: number; readonly reason: string; readonly status: "active" | "expired"; }
export interface EntitlementRepository { listPlans(): Promise<readonly EntitlementPlan[]>; getPlan(code: string, at: string): Promise<EntitlementPlan | undefined>; listModules(): Promise<readonly string[]>; getOverride(tenantId: string, id: string): Promise<TenantEntitlementOverride | undefined>; saveOverride(input: Omit<TenantEntitlementOverride, "id" | "version" | "status"> & { readonly id?: string; readonly expectedVersion?: number }, actorId: string): Promise<TenantEntitlementOverride>; expireOverride(tenantId: string, id: string, expectedVersion: number | undefined, actorId: string): Promise<TenantEntitlementOverride>; }

export interface ConnectorDraft extends Versioned { readonly tenantId: string; readonly connectorTypeId: string; readonly code: string; readonly name: string; readonly baseUrl?: string; readonly secretReference?: string; readonly config: Readonly<Record<string, JsonValue>>; readonly endpoints: readonly ConnectorEndpointDraft[]; readonly status: "draft" | "active" | "suspended" | "deprecated"; }
export interface ConnectorEndpointDraft { readonly code: string; readonly path: string; readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE"; readonly kind: string; readonly requestSchema?: Readonly<Record<string, JsonValue>>; }
export interface ConnectorRepository { get(tenantId: string, id: string): Promise<ConnectorDraft | undefined>; save(input: Omit<ConnectorDraft, "version"> & { readonly expectedVersion?: number }, actorId: string): Promise<ConnectorDraft>; transition(tenantId: string, id: string, status: ConnectorDraft["status"], expectedVersion: number | undefined, actorId: string): Promise<ConnectorDraft>; }
export interface ConnectorHealthJobs { enqueue(input: { readonly tenantId: string; readonly connectorId: string; readonly requestedBy: string }): Promise<string>; }

export interface ControlServiceCommand<T> { readonly context: VerifiedRequestContext; readonly payload: T; readonly expectedVersion?: number; }
