import {createOperation,encodePathSegment,type HttpClient} from "@athyper/platform-api-client";import type {SummaryQuery} from "./business-partner-360-client";
export type CommercialSectionCode="banking"|"qualifications-certificates"|"credit";export interface CommercialSection{readonly schemaVersion:1;readonly sectionCode:CommercialSectionCode;readonly state:"ready"|"empty"|"partial";readonly data:Readonly<Record<string,unknown>>;readonly provenance:readonly Readonly<{sourceObject:string;observedAt:string}>[];}
export interface AuthorizedAttachmentDownload{readonly attachmentId:string;readonly url:string;readonly expiresAt:string;}
export interface CommercialQuery extends SummaryQuery{readonly sectionCode:CommercialSectionCode;}export interface BankReveal{readonly bankAccountLinkId:string;readonly value:string;readonly expiresAt:string;}
const read=createOperation<CommercialSection>({method:"GET",path:({businessPartnerId,section})=>`/api/neon/business-partners/${encodePathSegment(businessPartnerId)}/360/${encodePathSegment(section)}`,parse:parse});
const reveal=createOperation<BankReveal,Readonly<{bankAccountLinkId:string;purpose:string;revealId:string;purposeExpiresAt:string}>>({method:"POST",path:({businessPartnerId})=>`/api/neon/business-partners/${encodePathSegment(businessPartnerId)}/360/banking/reveal`,parse:value=>record(value) as unknown as BankReveal});
const downloadAttachment=createOperation<AuthorizedAttachmentDownload,Readonly<{expirySeconds:number}>>({method:"POST",path:({attachmentId})=>`/api/attachments/${encodePathSegment(attachmentId)}/download`,parse:value=>record(value) as unknown as AuthorizedAttachmentDownload});
export function createBusinessPartner360CommercialClient(http:HttpClient){return{read:(query:CommercialQuery,signal?:AbortSignal)=>http.request(read,{params:{businessPartnerId:query.businessPartnerId,section:query.sectionCode==="qualifications-certificates"?"qualifications":query.sectionCode},query:{roleLens:query.roleLens,...(query.operatingOrganizationId?{operatingOrganizationId:query.operatingOrganizationId}:{}),...(query.companyCodeId?{companyCodeId:query.companyCodeId}:{}),...(query.legalEntityId?{legalEntityId:query.legalEntityId}:{}),...(query.asOf?{asOf:query.asOf}:{}),permissionEpoch:query.authEpoch},signal}),revealBank:(businessPartnerId:string,bankAccountLinkId:string,purpose:string,signal?:AbortSignal)=>http.request(reveal,{params:{businessPartnerId},body:{bankAccountLinkId,purpose,...revealClaim()},signal}),downloadAttachment:(attachmentId:string,signal?:AbortSignal)=>http.request(downloadAttachment,{params:{attachmentId},body:{expirySeconds:120},signal})};}
export function commercialQueryKey(query:CommercialQuery){return["business-partner-360",query.tenantId,query.principalId,query.businessPartnerId,query.sectionCode,query.roleLens,query.operatingOrganizationId??"global",query.companyCodeId??"no-company",query.legalEntityId??"no-legal-entity",query.asOf??"current",query.authEpoch]as const;}
function revealClaim(){return{revealId:crypto.randomUUID(),purposeExpiresAt:new Date(Date.now()+30_000).toISOString()};}
function parse(value:unknown){const body=record(value),serialized=JSON.stringify(body);if(/"(?:accountIdValue|accountNumber|iban|taxNumber|riskClassCode|riskScore|riskBand)"\s*:/i.test(serialized))throw new TypeError("Commercial control response contains a restricted field");if(body["schemaVersion"]!==1||!body["data"]||typeof body["data"]!=="object")throw new TypeError("Commercial control section contract is invalid");return body as unknown as CommercialSection;}function record(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError("Commercial control response must be an object");return value as Record<string,unknown>;}
