import {createOperation,encodePathSegment,type HttpClient} from "@athyper/platform-api-client";
import type {SummaryQuery} from "./business-partner-360-client";

export interface NetworkSection {readonly schemaVersion:1;readonly sectionCode:"network";readonly state:"ready"|"empty"|"partial"|"stale"|"unavailable";readonly data:Readonly<Record<string,unknown>>;readonly provenance:readonly Readonly<{plane:string;service:string;sourceObject:string;observedAt:string}>[];}
export interface NetworkQuery extends SummaryQuery {readonly sectionCode:"network";}
const operation=createOperation<NetworkSection>({method:"GET",path:({businessPartnerId})=>`/api/neon/business-partners/${encodePathSegment(businessPartnerId)}/360/network`,parse});
export function createBusinessPartner360NetworkClient(http:HttpClient){return{read:(query:NetworkQuery,signal?:AbortSignal)=>http.request(operation,{params:{businessPartnerId:query.businessPartnerId},query:{roleLens:query.roleLens,...(query.operatingOrganizationId?{operatingOrganizationId:query.operatingOrganizationId}:{}),...(query.companyCodeId?{companyCodeId:query.companyCodeId}:{}),...(query.legalEntityId?{legalEntityId:query.legalEntityId}:{}),...(query.asOf?{asOf:query.asOf}:{}),permissionEpoch:query.authEpoch},signal})};}
export function networkQueryKey(query:NetworkQuery){return["business-partner-360",query.tenantId,query.principalId,query.businessPartnerId,"network",query.roleLens,query.operatingOrganizationId??"global",query.companyCodeId??"no-company",query.legalEntityId??"no-legal-entity",query.asOf??"current",query.authEpoch]as const;}
export function isNetworkPayloadSafe(value:unknown){return !/"(?:person|workforce|employee|employment|payload|proposedPayload|fieldDiff|rankedCandidates|accountNumber|accountLast4|iban|routingNumber|bankAccount)"\s*:/i.test(JSON.stringify(value));}
function parse(value:unknown){const body=record(value);if(!isNetworkPayloadSafe(body))throw new TypeError("Network response contains a prohibited payload field");if(body["schemaVersion"]!==1||body["sectionCode"]!=="network"||!record(body["data"]))throw new TypeError("Network section contract is invalid");return body as unknown as NetworkSection;}function record(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError("Network response must be an object");return value as Record<string,unknown>;}
