import {test as bpTest,authenticate} from "./bp-v1-009.fixture";
import type {BrowserContext,Page} from "@playwright/test";

type Environment=Readonly<Record<string,string|undefined>>;const environment=(globalThis as typeof globalThis&{process?:{env?:Environment}}).process?.env??{};
export type R3Config=Readonly<{invitationToken:string;inviteeEmail:string;otherRequestId:string;meshSnapshotId:string;meshCandidateBusinessPartnerId?:string;applicant:{username:string;password:string}}>;
export function readR3Config(source:Environment=environment):R3Config{return Object.freeze({invitationToken:required(source,"PLAYWRIGHT_BP_R3_INVITATION_TOKEN"),inviteeEmail:required(source,"PLAYWRIGHT_BP_R3_INVITEE_EMAIL"),otherRequestId:uuid(required(source,"PLAYWRIGHT_BP_R3_OTHER_REQUEST_ID"),"PLAYWRIGHT_BP_R3_OTHER_REQUEST_ID"),meshSnapshotId:uuid(required(source,"PLAYWRIGHT_BP_R3_MESH_SNAPSHOT_ID"),"PLAYWRIGHT_BP_R3_MESH_SNAPSHOT_ID"),...(source.PLAYWRIGHT_BP_R3_MESH_CANDIDATE_BP_ID?{meshCandidateBusinessPartnerId:uuid(source.PLAYWRIGHT_BP_R3_MESH_CANDIDATE_BP_ID,"PLAYWRIGHT_BP_R3_MESH_CANDIDATE_BP_ID")} : {}),applicant:Object.freeze({username:required(source,"PLAYWRIGHT_BP_R3_APPLICANT_USER"),password:required(source,"PLAYWRIGHT_BP_R3_APPLICANT_PASSWORD")})});}
export const test=bpTest.extend<{r3:{config:R3Config;applicantPage:Page}}>({r3:async({browser,bpActors},use)=>{const config=readR3Config(),baseURL=environment.PLAYWRIGHT_NEON_BASE_URL??environment.PLAYWRIGHT_BASE_URL??"https://neon.athyper.local",context:BrowserContext=await browser.newContext({
      storageState: { cookies: [], origins: [] },baseURL,ignoreHTTPSErrors:true,viewport:{width:1280,height:800}});try{if(new Set([config.applicant.username,bpActors.config.requester.username,bpActors.config.approver.username,bpActors.config.materializer.username]).size!==4)throw new Error("R3 requires distinct applicant, requester, approver and materializer users");const applicant=await authenticate(context,config.applicant);await use({config,applicantPage:applicant.page});}finally{await context.close();}}});
function required(source:Environment,name:string){const value=source[name]?.trim();if(!value)throw new Error(`R3 fixture is mandatory: configure ${name}; this journey never skips`);return value;}
function uuid(value:string,name:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))throw new Error(`${name} must be a UUID`);return value;}
