import { createOperation, encodePathSegment, type HttpClient } from "@athyper/platform-api-client";

export type WorkforceRequestStatus="draft"|"validating"|"validation_failed"|"pending_approval"|"returned"|"approved"|"rejected"|"applying"|"applied"|"failed"|"cancelled"|"superseded";
export interface WorkforceRequest{readonly id:string;readonly requestNo:string;readonly kind:"onboard_person"|"add_employment"|"change_employment"|"offboard_employment";readonly sourceKind:"manual"|"portal"|"import"|"api";readonly legalEntityId:string;readonly companyCodeId?:string;readonly orgUnitId?:string;readonly positionId?:string;readonly protectedProfileContentItemId?:string;readonly requestedChanges:Readonly<Record<string,unknown>>;readonly status:WorkforceRequestStatus;readonly rowVersion:number;readonly createdAt:string;readonly workflow?:{readonly requestId:string;readonly stageId:string;readonly workItemId:string;readonly workItemVersion:number};readonly materializedPersonId?:string;readonly materializedEmployeeId?:string;readonly materializedEmploymentId?:string;readonly materializedWorkAssignmentId?:string;readonly materializedOnboardingCaseId?:string;readonly materializationSnapshotId?:string;}
export interface WorkforceOnboardingDraft{readonly legalEntityId:string;readonly companyCodeId:string;readonly orgUnitId:string;readonly positionId?:string;readonly protectedProfileContentItemId:string;readonly requestedChanges:Readonly<Record<string,unknown>>;}

const create=createOperation<{readonly request:WorkforceRequest;readonly replayed:boolean},Readonly<{idempotencyKey:string;kind:"onboard_person";sourceKind:"manual";legalEntityId:string;companyCodeId:string;orgUnitId:string;positionId?:string;protectedProfileContentItemId:string;requestedChanges:Readonly<Record<string,unknown>>}>>({method:"POST",path:"/api/neon/workforce-requests",idempotency:"required"});
const list=createOperation<readonly WorkforceRequest[]>({method:"GET",path:"/api/neon/workforce-requests",parse:value=>{if(!Array.isArray(value))throw new TypeError("Workforce request list must be an array");return value as readonly WorkforceRequest[];}});
const get=createOperation<WorkforceRequest>({method:"GET",path:({requestId})=>`/api/neon/workforce-requests/${encodePathSegment(requestId)}`});
const action=(name:"validate"|"submit"|"decision"|"apply")=>createOperation<unknown,Readonly<Record<string,unknown>>>({method:"POST",path:({requestId})=>`/api/neon/workforce-requests/${encodePathSegment(requestId)}/${name}`,idempotency:name==="validate"?"forbidden":"required"});
export function createWorkforceClient(http:HttpClient){return Object.freeze({
  onboard:(draft:WorkforceOnboardingDraft,key=commandKey("onboard"))=>http.request(create,{body:{idempotencyKey:key,kind:"onboard_person",sourceKind:"manual",...draft},idempotencyKey:key}),
  list:(companyCodeId?:string,status?:WorkforceRequestStatus,signal?:AbortSignal)=>http.request(list,{query:{companyCodeId,status,limit:100},signal}),
  get:(requestId:string,signal?:AbortSignal)=>http.request(get,{params:{requestId},signal}),
  validate:(requestId:string,expectedVersion:number)=>http.request(action("validate"),{params:{requestId},body:{expectedVersion}}),
  submit:(requestId:string,expectedVersion:number,key=commandKey("submit"))=>http.request(action("submit"),{params:{requestId},body:{expectedVersion,idempotencyKey:key},idempotencyKey:key}),
  decide:(request:WorkforceRequest,decision:"approve"|"return"|"reject",reason:string,key=commandKey(decision))=>{if(!request.workflow)throw new Error("No active People workflow is available");return http.request(action("decision"),{params:{requestId:request.id},body:{workflowRequestId:request.workflow.requestId,workItemId:request.workflow.workItemId,expectedRequestVersion:request.rowVersion,expectedWorkItemVersion:request.workflow.workItemVersion,decision,reason,idempotencyKey:key},idempotencyKey:key});},
  apply:(requestId:string,expectedVersion:number,key=commandKey("apply"))=>http.request(action("apply"),{params:{requestId},body:{expectedVersion,idempotencyKey:key},idempotencyKey:key}),
});}
function commandKey(action:string):string{return `workforce-ui-${action}-${globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`}`;}
