import { createOperation, encodePathSegment, type HttpClient } from "@athyper/platform-api-client";

export type WorkforceRequestStatus="draft"|"validating"|"validation_failed"|"pending_approval"|"returned"|"approved"|"rejected"|"applying"|"applied"|"failed"|"cancelled"|"superseded";
export interface WorkforceRequest{readonly id:string;readonly requestNo:string;readonly kind:"onboard_person"|"add_employment"|"change_employment"|"offboard_employment";readonly sourceKind:"manual"|"portal"|"import"|"api";readonly legalEntityId:string;readonly companyCodeId?:string;readonly orgUnitId?:string;readonly positionId?:string;readonly protectedProfileContentItemId?:string;readonly requestedChanges:Readonly<Record<string,unknown>>;readonly status:WorkforceRequestStatus;readonly rowVersion:number;readonly createdAt:string;readonly workflow?:{readonly requestId:string;readonly stageId:string;readonly workItemId:string;readonly workItemVersion:number};readonly materializedPersonId?:string;readonly materializedEmployeeId?:string;readonly materializedEmploymentId?:string;readonly materializedWorkAssignmentId?:string;readonly materializedOnboardingCaseId?:string;readonly materializationSnapshotId?:string;}
export interface WorkforceOnboardingDraft{readonly legalEntityId:string;readonly companyCodeId:string;readonly orgUnitId:string;readonly positionId?:string;readonly protectedProfileContentItemId:string;readonly requestedChanges:Readonly<Record<string,unknown>>;}
export type EmployeeLifecycleStatus="employed"|"future"|"suspended"|"ended"|"unassigned";
export type EmployeeDirectorySort="name"|"number"|"status";
export interface EmployeeSummary{readonly personId:string;readonly employeeId:string;readonly employeeNumber:string;readonly displayName:string;readonly companyCodeId?:string;readonly companyCode?:string;readonly companyName?:string;readonly department?:string;readonly positionName?:string;readonly managerEmployeeId?:string;readonly managerName?:string;readonly employmentStatus?:EmployeeLifecycleStatus;readonly assignmentStatus?:"current"|"future"|"ended";readonly asOfDate:string;readonly hireDate?:string;readonly terminationDate?:string;readonly onboardingStatus?:string;}
export interface EmployeeDirectoryPage{readonly items:readonly EmployeeSummary[];readonly nextCursor?:string;}
export interface EmployeeDirectoryQuery{readonly companyCodeId:string;readonly status?:EmployeeLifecycleStatus;readonly search?:string;readonly sort?:EmployeeDirectorySort;readonly cursor?:string;readonly limit?:number;readonly signal?:AbortSignal;}
export interface EmployeeEmployment{readonly id:string;readonly legalEntityId?:string;readonly companyCodeId?:string;readonly companyCode?:string;readonly companyName?:string;readonly employmentNumber?:string;readonly employmentType?:string;readonly status?:string;readonly lifecycleStatus:EmployeeLifecycleStatus;readonly primary:boolean;readonly hireDate?:string;readonly serviceDate?:string;readonly probationEndDate?:string;readonly terminationDate?:string;}
export interface EmployeeAssignment{readonly id:string;readonly employmentId?:string;readonly type:string;readonly lifecycleStatus:"current"|"future"|"ended";readonly positionId?:string;readonly positionName?:string;readonly orgUnitId?:string;readonly orgUnitName?:string;readonly managerEmployeeId?:string;readonly managerName?:string;readonly fte:number;readonly effectiveFrom:string;readonly effectiveUntil?:string;}
export interface EmployeeDetail extends EmployeeSummary{readonly firstName:string;readonly lastName:string;readonly preferredName?:string;readonly email?:string;readonly phone?:string;readonly principalId?:string;readonly employment?:EmployeeEmployment;readonly assignment?:EmployeeAssignment;readonly employments:readonly EmployeeEmployment[];readonly assignments:readonly EmployeeAssignment[];readonly onboarding?:{readonly id:string;readonly requestId:string;readonly status:string;readonly checklist:readonly {readonly code:string;readonly label:string;readonly status:string;readonly required:boolean}[]};readonly returnedRequest?:Readonly<Record<string,unknown>>;readonly readiness:{readonly eligible:boolean;readonly reasons:readonly string[];readonly evidenceVersion:number};}
export type EmployeeSectionCode="team"|"requests"|"documents"|"comments"|"audit"|"education"|"priorEmployment";
export interface EmployeeSectionItem{readonly id:string;readonly kind:EmployeeSectionCode;readonly title:string;readonly subtitle?:string;readonly status?:string;readonly occurredAt?:string;readonly href?:string;readonly metadata?:Readonly<Record<string,unknown>>;}
export interface EmployeeSectionPage{readonly section:EmployeeSectionCode;readonly items:readonly EmployeeSectionItem[];readonly nextCursor?:string;}
export interface EmployeeEvidence{readonly personId:string;readonly purpose:string;readonly expiresAt:string;readonly fields:Readonly<Record<string,unknown>>;readonly redactedFields:readonly string[];}
export interface EmployeeSavedView{readonly id:string;readonly name:string;readonly state:Readonly<Record<string,unknown>>;readonly scope:"personal"|"shared"|"system";readonly version:number;}

const create=createOperation<{readonly request:WorkforceRequest;readonly replayed:boolean},Readonly<{idempotencyKey:string;kind:"onboard_person";sourceKind:"manual";legalEntityId:string;companyCodeId:string;orgUnitId:string;positionId?:string;protectedProfileContentItemId:string;requestedChanges:Readonly<Record<string,unknown>>}>>({method:"POST",path:"/api/neon/workforce-requests",idempotency:"required"});
const list=createOperation<readonly WorkforceRequest[]>({method:"GET",path:"/api/neon/workforce-requests",parse:value=>{if(!Array.isArray(value))throw new TypeError("Workforce request list must be an array");return value as readonly WorkforceRequest[];}});
const get=createOperation<WorkforceRequest>({method:"GET",path:({requestId})=>`/api/neon/workforce-requests/${encodePathSegment(requestId)}`});
const action=(name:"validate"|"submit"|"decision"|"apply")=>createOperation<unknown,Readonly<Record<string,unknown>>>({method:"POST",path:({requestId})=>`/api/neon/workforce-requests/${encodePathSegment(requestId)}/${name}`,idempotency:name==="validate"?"forbidden":"required"});
const employeeList=createOperation<EmployeeDirectoryPage>({method:"GET",path:"/api/neon/workforce",parse:value=>{const page=value as EmployeeDirectoryPage;if(!page||!Array.isArray(page.items))throw new TypeError("Employee directory response must contain items");return page;}});
const employeeGet=createOperation<EmployeeDetail>({method:"GET",path:({employeeId})=>`/api/neon/workforce/${encodePathSegment(employeeId)}`});
const employeeSection=createOperation<EmployeeSectionPage>({method:"GET",path:({employeeId,section})=>`/api/neon/workforce/${encodePathSegment(employeeId)}/sections/${encodePathSegment(section)}`});
const employeeReveal=createOperation<EmployeeEvidence,Readonly<{purpose:"employment"|"payroll"|"benefits"|"compliance"|"health";fields:readonly string[]}>>({method:"POST",path:({personId})=>`/api/neon/people/${encodePathSegment(personId)}/restricted-evidence/read`,idempotency:"forbidden"});
const profileMutation=createOperation<{readonly id:string;readonly rowVersion:number;readonly archived:boolean},Readonly<{kind:"education"|"priorEmployment";recordId?:string;expectedVersion?:number;archive?:boolean;data?:Readonly<Record<string,unknown>>}>>({method:"POST",path:({employeeId})=>`/api/neon/workforce/${encodePathSegment(employeeId)}/profile-records`,idempotency:"forbidden"});
const savedViewList=createOperation<readonly EmployeeSavedView[]>({method:"GET",path:"/api/platform/saved-views/employee",parse:value=>{if(!Array.isArray(value))throw new TypeError("Saved-view response must be an array");return value as readonly EmployeeSavedView[];}});
const savedViewCreate=createOperation<EmployeeSavedView,Readonly<{name:string;surfaceCode:string;state:Readonly<Record<string,unknown>>}>>({method:"POST",path:"/api/platform/saved-views/employee",idempotency:"forbidden"});
export function createWorkforceClient(http:HttpClient){return Object.freeze({
  onboard:(draft:WorkforceOnboardingDraft,key=commandKey("onboard"))=>http.request(create,{body:{idempotencyKey:key,kind:"onboard_person",sourceKind:"manual",...draft},idempotencyKey:key}),
  list:(companyCodeId?:string,status?:WorkforceRequestStatus,signal?:AbortSignal)=>http.request(list,{query:{companyCodeId,status,limit:100},signal}),
  get:(requestId:string,signal?:AbortSignal)=>http.request(get,{params:{requestId},signal}),
  validate:(requestId:string,expectedVersion:number)=>http.request(action("validate"),{params:{requestId},body:{expectedVersion}}),
  submit:(requestId:string,expectedVersion:number,key=commandKey("submit"))=>http.request(action("submit"),{params:{requestId},body:{expectedVersion,idempotencyKey:key},idempotencyKey:key}),
  decide:(request:WorkforceRequest,decision:"approve"|"return"|"reject",reason:string,key=commandKey(decision))=>{if(!request.workflow)throw new Error("No active People workflow is available");return http.request(action("decision"),{params:{requestId:request.id},body:{workflowRequestId:request.workflow.requestId,workItemId:request.workflow.workItemId,expectedRequestVersion:request.rowVersion,expectedWorkItemVersion:request.workflow.workItemVersion,decision,reason,idempotencyKey:key},idempotencyKey:key});},
  apply:(requestId:string,expectedVersion:number,key=commandKey("apply"))=>http.request(action("apply"),{params:{requestId},body:{expectedVersion,idempotencyKey:key},idempotencyKey:key}),
});}
export function createEmployeeClient(http:HttpClient){return Object.freeze({
  list:(query:EmployeeDirectoryQuery)=>http.request(employeeList,{query:{companyCodeId:query.companyCodeId,status:query.status,search:query.search,sort:query.sort,cursor:query.cursor,limit:query.limit??20},signal:query.signal}),
  get:(employeeId:string,signal?:AbortSignal)=>http.request(employeeGet,{params:{employeeId},signal}),
  section:(employeeId:string,section:EmployeeSectionCode,query:{readonly companyCodeId?:string;readonly cursor?:string;readonly limit?:number;readonly signal?:AbortSignal}={})=>http.request(employeeSection,{params:{employeeId,section},query:{companyCodeId:query.companyCodeId,cursor:query.cursor,limit:query.limit??20},signal:query.signal}),
  reveal:(personId:string,purpose:"employment"|"payroll"|"benefits"|"compliance"|"health",fields:readonly string[])=>http.request(employeeReveal,{params:{personId},body:{purpose,fields}}),
  mutateProfile:(employeeId:string,body:{kind:"education"|"priorEmployment";recordId?:string;expectedVersion?:number;archive?:boolean;data?:Readonly<Record<string,unknown>>})=>http.request(profileMutation,{params:{employeeId},body}),
  savedViews:(signal?:AbortSignal)=>http.request(savedViewList,{query:{surface:"employee_directory"},signal}),
  saveView:(name:string,state:Readonly<Record<string,unknown>>)=>http.request(savedViewCreate,{body:{name,surfaceCode:"employee_directory",state}}),
});}
function commandKey(action:string):string{return `workforce-ui-${action}-${globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`}`;}
