"use client";
import {useApiClient,usePermissions} from "@athyper/platform-shell-app-foundation";
import {Badge,Button,Card,Input,Label,Select,Skeleton} from "@athyper/platform-ui";
import {useEffect,useMemo,useState,type FormEvent} from "react";
import {createHrStage2Client,type EffectivePolicies,type PolicyAssignment,type SetupCatalog} from "./stage2-client";
function label(error:unknown){return error instanceof Error?error.message:"Policy service unavailable";}
export function HrPolicyApplicability({catalog,companyCodeId}:{catalog:SetupCatalog;companyCodeId:string}){
 const client=useApiClient(),api=useMemo(()=>createHrStage2Client(client),[client]),permissions=usePermissions();
 const [assignments,setAssignments]=useState<readonly PolicyAssignment[]>([]),[effective,setEffective]=useState<EffectivePolicies>(),[asOf,setAsOf]=useState(new Date().toISOString().slice(0,10)),[siteId,setSiteId]=useState(""),[scopeKind,setScopeKind]=useState<"country"|"company"|"site">("company"),[error,setError]=useState<string>(),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const countryCode=catalog.company.country_code;
 useEffect(()=>{const controller=new AbortController();setError(undefined);Promise.all([api.policyAssignments(companyCodeId,controller.signal),api.effectivePolicies({companyCodeId,asOf,...(siteId?{siteId}:{})},controller.signal)]).then(([rows,resolved])=>{setAssignments(rows);setEffective(resolved);}).catch(cause=>{if(!controller.signal.aborted)setError(label(cause));});return()=>controller.abort();},[api,companyCodeId,asOf,siteId,refresh]);
 const canDraft=scopeKind==="country"?permissions.has("neon.hr.policy.country.write"):permissions.has("neon.hr.setup.write");
 async function draft(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!countryCode)return;const fields=new FormData(event.currentTarget);setBusy(true);setError(undefined);try{await api.createPolicyAssignment({idempotencyKey:crypto.randomUUID(),policyDefinitionId:String(fields.get("policyDefinitionId")??""),scopeKind,countryCode,...(scopeKind!=="country"?{companyCodeId}:{}),...(scopeKind==="site"?{siteId:String(fields.get("siteId")??"")}:{}),effectiveFrom:String(fields.get("effectiveFrom")??""),...(fields.get("effectiveUntil")?{effectiveUntil:String(fields.get("effectiveUntil"))}:{})});event.currentTarget.reset();setRefresh(value=>value+1);}catch(cause){setError(label(cause));}finally{setBusy(false);}}
 async function publish(row:PolicyAssignment){setBusy(true);setError(undefined);try{await api.publishPolicyAssignment(row.id,row.row_version);setRefresh(value=>value+1);}catch(cause){setError(label(cause));}finally{setBusy(false);}}
 return <Card className="wf-section"><h2>Effective HR policy</h2><p>Country default → company override → site override. Each published assignment fixes its policy version and effective interval.</p>{!countryCode?<p>Configure the company country before assigning policies.</p>:<><div className="wf-section-grid"><div><Label htmlFor="hr-policy-date">As of</Label><Input id="hr-policy-date" type="date" value={asOf} onChange={event=>setAsOf(event.target.value)}/></div><div><Label htmlFor="hr-policy-site">Site</Label><Select id="hr-policy-site" value={siteId} onChange={event=>setSiteId(event.target.value)}><option value="">Company default</option>{catalog.sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</Select></div></div>{error?<p role="alert">{error}</p>:null}{!effective?<Skeleton label="Resolving HR policies"/>:effective.unconfigured?<p>No published HR policy applies to {countryCode} / {catalog.company.name} on {asOf}.</p>:<><h3>Selected versions</h3><ul>{effective.selected.map(row=><li key={row.id}>{row.entity_type} · v{row.policy_version_no} · {row.scope_kind} · from {row.effective_from}</li>)}</ul>{effective.overridden.length?<details><summary>Overridden assignments and conflict explanation</summary><ul>{effective.overridden.map(row=><li key={row.id}>{row.entity_type} · v{row.policy_version_no} · {row.scope_kind}: {row.reason}</li>)}</ul></details>:null}</>}
 <h3>Policy assignments</h3>{assignments.length?<div className="wf-table-wrap"><table className="wf-table"><thead><tr><th>Policy</th><th>Scope</th><th>Effective</th><th>Status</th><th>Action</th></tr></thead><tbody>{assignments.map(row=><tr key={row.id}><td>{row.entity_type} · v{row.policy_version_no}</td><td>{row.scope_kind}{row.site_id?` · ${row.site_id}`:""}</td><td>{row.effective_from} – {row.effective_until??"open"}</td><td><Badge>{row.status}</Badge></td><td>{row.status==="draft"&&permissions.has("neon.hr.policy.publish")?<Button variant="secondary" disabled={busy} onClick={()=>void publish(row)}>Publish</Button>:"—"}</td></tr>)}</tbody></table></div>:<p>No HR policy assignments in this scope.</p>}
 {canDraft?<form className="wf-section-stack" onSubmit={draft}><h3>Create draft policy assignment</h3><div className="wf-section-grid"><div><Label htmlFor="hr-policy-scope">Scope</Label><Select id="hr-policy-scope" value={scopeKind} onChange={event=>setScopeKind(event.target.value as "country"|"company"|"site")}><option value="company">Company</option><option value="site">Site</option>{permissions.has("neon.hr.policy.country.write")?<option value="country">Country default</option>:null}</Select></div><div><Label htmlFor="hr-policy-definition">Policy version</Label><Select id="hr-policy-definition" name="policyDefinitionId" required><option value="">Choose</option>{catalog.policies.filter(policy=>typeof policy["definition_hash"]==="string").map(policy=><option key={String(policy["id"])} value={String(policy["id"])}>{String(policy["name"])} · v{String(policy["version_no"])}</option>)}</Select></div>{scopeKind==="site"?<div><Label htmlFor="hr-policy-assignment-site">Site</Label><Select id="hr-policy-assignment-site" name="siteId" required><option value="">Choose</option>{catalog.sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</Select></div>:null}<div><Label htmlFor="hr-policy-from">Effective from</Label><Input id="hr-policy-from" name="effectiveFrom" type="date" required/></div><div><Label htmlFor="hr-policy-until">Effective until (exclusive)</Label><Input id="hr-policy-until" name="effectiveUntil" type="date"/></div></div><Button type="submit" disabled={busy||!catalog.policies.length}>{busy?"Saving…":"Create draft"}</Button><p>Another authorized reviewer must publish the draft. Overlapping active versions at one scope are rejected.</p></form>:null}</>}</Card>;
}
