-- Generated by scripts/checks/security/generate-security-definer-contract.ts.
-- Final hardening must run after every plane manifest entry.
DO $hardening$
DECLARE
    routine record;
    exception jsonb;
    target_owner text;
    identity_signature text;
    configured_path text;
    path_schema text;
    trusted_path text[];
BEGIN
    FOR routine IN
        SELECT p.oid, p.prokind, p.proconfig, n.nspname AS schema_name, p.proname AS routine_name,
               pg_get_function_identity_arguments(p.oid) AS identity_arguments,
               oidvectortypes(p.proargtypes) AS argument_types
          FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE p.prosecdef AND n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
           AND n.nspname NOT LIKE 'pg_%'
    LOOP
        identity_signature := routine.schema_name || '.' || routine.routine_name || '(' || routine.argument_types || ')';
        SELECT value INTO exception FROM jsonb_array_elements('[
  {
    "signature": "ai.fn_atlas_conversation_access(uuid, uuid, boolean)",
    "owner": "athyper_bypass_ai",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "ai.fn_is_atlas_conversation(uuid, uuid)",
    "owner": "athyper_bypass_ai",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "ai.trg_allocate_atlas_message_sequence()",
    "owner": "athyper_bypass_ai",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "audit.append_platform_event(text, audit.operation_d, text, uuid, uuid, audit.outcome_d, audit.event_severity_d, jsonb, uuid, text, timestamp with time zone)",
    "owner": "athyper_bypass_audit",
    "rowSecurityOff": false,
    "reason": "Platform-scoped audit append, including a required platform scope identifier."
  },
  {
    "signature": "audit.ensure_monthly_partitions(date, integer)",
    "owner": "$ddlOwner",
    "rowSecurityOff": false,
    "reason": "DDL-only creation/attachment of audit partitions; requires parent ownership."
  },
  {
    "signature": "audit.install_schema_row_triggers(text)",
    "owner": "$ddlOwner",
    "rowSecurityOff": false,
    "reason": "DDL-only installation of audit row triggers on declared tenant tables."
  },
  {
    "signature": "authz.fn_activate_application_projection(uuid, uuid, bigint, text, uuid)",
    "owner": "athyper_projection_owner",
    "rowSecurityOff": false,
    "reason": "Existing dedicated publication/projection owner and grants remain unchanged."
  },
  {
    "signature": "authz.fn_activate_entity_operation_projection(uuid, timestamp with time zone)",
    "owner": "athyper_projection_owner",
    "rowSecurityOff": false,
    "reason": "Existing dedicated publication/projection owner and grants remain unchanged."
  },
  {
    "signature": "authz.fn_resolve_active_application_projections(text, text[], text)",
    "owner": "athyper_bypass_authz",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "authz.fn_restore_entity_operation_projection(uuid, timestamp with time zone)",
    "owner": "athyper_projection_owner",
    "rowSecurityOff": false,
    "reason": "Existing dedicated publication/projection owner and grants remain unchanged."
  },
  {
    "signature": "authz.fn_retire_entity_operation_projection(uuid, timestamp with time zone)",
    "owner": "athyper_projection_owner",
    "rowSecurityOff": false,
    "reason": "Existing dedicated publication/projection owner and grants remain unchanged."
  },
  {
    "signature": "authz.fn_stage_application_projection(uuid, jsonb, jsonb, jsonb, uuid)",
    "owner": "athyper_projection_owner",
    "rowSecurityOff": false,
    "reason": "Existing dedicated publication/projection owner and grants remain unchanged."
  },
  {
    "signature": "authz.fn_stage_entity_operation_projection(uuid, uuid, text, uuid, text, jsonb)",
    "owner": "athyper_projection_owner",
    "rowSecurityOff": false,
    "reason": "Existing dedicated publication/projection owner and grants remain unchanged."
  },
  {
    "signature": "control.claim_connector_health_job()",
    "owner": "athyper_bypass_control",
    "rowSecurityOff": false,
    "reason": "Plane-wide connector health queue leasing."
  },
  {
    "signature": "control.fn_cron_schedules_for_scheduler()",
    "owner": "athyper_bypass_control",
    "rowSecurityOff": false,
    "reason": "Plane-wide scheduler discovery of enabled schedules."
  },
  {
    "signature": "control.fn_mark_cron_schedule_reconciled(uuid, timestamp with time zone, timestamp with time zone)",
    "owner": "athyper_bypass_control",
    "rowSecurityOff": false,
    "reason": "Plane-wide scheduler reconciliation of a discovered schedule."
  },
  {
    "signature": "control.publication_policy_enrollment_is_active(uuid, text, uuid, uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "document.fn_workflow_sla_due_tenants(timestamp with time zone, integer)",
    "owner": "athyper_bypass_document",
    "rowSecurityOff": false,
    "reason": "Bounded worker discovery of tenants with due workflow items."
  },
  {
    "signature": "document.process_document_candidates()",
    "owner": "athyper_bypass_document",
    "rowSecurityOff": false,
    "reason": "Bounded worker discovery of pending process document jobs."
  },
  {
    "signature": "event.fn_authorization_bump_epoch(text, uuid, text)",
    "owner": "athyper_bypass_event",
    "rowSecurityOff": false,
    "reason": "Global/tenant/plane authorization epoch application for invalidation processing."
  },
  {
    "signature": "event.fn_authorization_claim_invalidations(text, integer, integer)",
    "owner": "athyper_bypass_event",
    "rowSecurityOff": false,
    "reason": "Bounded plane-wide invalidation queue leasing."
  },
  {
    "signature": "event.fn_authorization_complete_invalidation(uuid, text)",
    "owner": "athyper_bypass_event",
    "rowSecurityOff": false,
    "reason": "Completion of a leased plane-wide invalidation item."
  },
  {
    "signature": "event.fn_authorization_fail_invalidation(uuid, text, text, integer)",
    "owner": "athyper_bypass_event",
    "rowSecurityOff": false,
    "reason": "Failure/retry handling of a leased plane-wide invalidation item."
  },
  {
    "signature": "event.fn_notification_work_tenants(text, text, integer)",
    "owner": "athyper_bypass_event",
    "rowSecurityOff": false,
    "reason": "Bounded worker discovery of notification tenant work."
  },
  {
    "signature": "master.fn_refresh_mv_cpa()",
    "owner": "$ddlOwner",
    "rowSecurityOff": false,
    "reason": "Maintenance-only refresh of the owned materialized account view."
  },
  {
    "signature": "master.fn_resolve_principal_identity(uuid, master.identity_provider_d, text, text)",
    "owner": "athyper_identity_resolver_owner",
    "rowSecurityOff": false,
    "reason": "Verified-provider subject bootstrap before principal context exists; dedicated tenant-read policies retain RLS and exact tenant/subject predicates."
  },
  {
    "signature": "master.purge_expired_reference_choices(integer)",
    "owner": "athyper_bypass_master",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "mesh.catalog_is_visible(uuid)",
    "owner": "athyper_bypass_mesh",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "mesh.catalog_item_is_visible(uuid)",
    "owner": "athyper_bypass_mesh",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "mesh.catalog_price_is_visible(uuid)",
    "owner": "athyper_bypass_mesh",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "mesh.fn_catalog_publication_snapshot(uuid)",
    "owner": "athyper_bypass_mesh",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "mesh.lock_profile_publication_relationship(uuid, uuid, uuid)",
    "owner": "athyper_bypass_mesh",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "mesh.profile_publication_is_visible(uuid)",
    "owner": "athyper_bypass_mesh",
    "rowSecurityOff": true,
    "reason": "Existing explicit RLS bypass; retain its source visibility or maintenance guards. This exception requires deployment review and excludes runtime owner membership."
  },
  {
    "signature": "onboarding.fn_guest_case_has_access(uuid, uuid, text)",
    "owner": "athyper_bypass_onboarding",
    "rowSecurityOff": false,
    "reason": "Guest token validation used by onboarding RLS policies; avoids recursive policy evaluation."
  },
  {
    "signature": "ops.acknowledge_record_transfer_cleanup(text, uuid, text, uuid, text, text, timestamp with time zone)",
    "owner": "athyper_bypass_ops",
    "rowSecurityOff": false,
    "reason": "Worker acknowledgement matching the discovered transfer and object key."
  },
  {
    "signature": "ops.record_transfer_cleanup_candidates(text, timestamp with time zone, integer)",
    "owner": "athyper_bypass_ops",
    "rowSecurityOff": false,
    "reason": "Bounded worker discovery of expired transfer artifacts across tenants."
  },
  {
    "signature": "ops.record_transfer_stuck_counts(timestamp with time zone, integer)",
    "owner": "athyper_bypass_ops",
    "rowSecurityOff": false,
    "reason": "Plane-wide worker health counts for stalled transfers."
  },
  {
    "signature": "publication.fn_compilation_recovery_source(jsonb, boolean)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_compiled_entity_compilation_source(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_compiled_entity_compilation_source_v2(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_compiled_entity_compilation_source_v3(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_coordinated_deployment_recovery_source(uuid, text)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Exact original-policy and signed-deployment evidence for independently reviewed coordinated recovery; read-only and tenant-scoped."
  },
  {
    "signature": "publication.fn_create_system_entity_release(uuid, uuid, bigint, jsonb, text[], uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_create_system_entity_successor(uuid, uuid, bigint, uuid, jsonb, text[], uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_entity_successor_enrollment_source(jsonb)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_entity_successor_saved_graph(uuid, uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_human_execution_context(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_human_publication_preparation_source(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_human_publication_review_evidence(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_human_review_identity_status(uuid, uuid, uuid, uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_human_reviewed_entity_policy(jsonb, uuid, text)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_link_system_entity_release(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_record_system_entity_validation(uuid, bigint, jsonb, jsonb, uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_recoverable_deployment_coordinates(timestamp with time zone, uuid, integer)",
    "owner": "athyper_publication_recovery_owner",
    "rowSecurityOff": false,
    "reason": "Existing dedicated publication/projection owner and grants remain unchanged."
  },
  {
    "signature": "publication.fn_store_system_entity_artifact(uuid, text, jsonb, jsonb)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_system_entity_authority(uuid, text)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_system_entity_execution_metadata(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_system_entity_successor_policy(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "publication.fn_transition_system_entity_change_set(uuid, bigint, text, text, uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login RLS-bound owner for exact enrolled global Entity publication and source evidence."
  },
  {
    "signature": "runtime_meta.fn_locked_live_read_resources(text[], uuid, text, integer)",
    "owner": "athyper_definer_live_read",
    "rowSecurityOff": false,
    "reason": "Dedicated non-login locked evidence reader; no activation authority or application UPDATE grant."
  },
  {
    "signature": "publication.fn_native_compilation_recovery_source(jsonb, boolean)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Bounded read-only native recovery evidence; existing original-policy human review and exact release/job/source group required."
  },
  {
    "signature": "publication.native_worker_entity_visible(uuid)",
    "owner": "athyper_definer_product_publication",
    "rowSecurityOff": false,
    "reason": "Worker reference identity visibility derives from exact currently enrolled native human publication sources."
  }
]'::jsonb)
            WHERE value->>'signature' = identity_signature;
        IF ('row_security=off' = ANY(COALESCE(routine.proconfig, ARRAY[]::text[])))
           IS DISTINCT FROM COALESCE((exception->>'rowSecurityOff')::boolean, false) THEN
            RAISE EXCEPTION 'Unlisted or changed RLS bypass signature: %', identity_signature;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM jsonb_array_elements_text('[
  "ai.fn_atlas_conversation_access(uuid, uuid, boolean)",
  "ai.fn_is_atlas_conversation(uuid, uuid)",
  "ai.trg_allocate_atlas_message_sequence()",
  "audit.append_event(text, audit.operation_d, text, uuid, audit.outcome_d, audit.event_severity_d, text, uuid, uuid, text, jsonb, jsonb, text[], jsonb, uuid, text, timestamp with time zone)",
  "audit.append_platform_event(text, audit.operation_d, text, uuid, uuid, audit.outcome_d, audit.event_severity_d, jsonb, uuid, text, timestamp with time zone)",
  "audit.create_hash_anchor(uuid, text, timestamp with time zone, timestamp with time zone, uuid)",
  "audit.ensure_monthly_partitions(date, integer)",
  "audit.install_schema_row_triggers(text)",
  "audit.trg_capture_row_change()",
  "audit.trg_prepare_audit_log()",
  "audit.verify_hash_anchor(uuid)",
  "authz.fn_activate_application_projection(uuid, uuid, bigint, text, uuid)",
  "authz.fn_activate_entity_operation_projection(uuid, timestamp with time zone)",
  "authz.fn_internal_permission_is_assignable_at_scope(uuid, uuid, uuid, authz.propagation_mode_d)",
  "authz.fn_internal_scope_assignment_covers_target(uuid, uuid, uuid, authz.propagation_mode_d)",
  "authz.fn_permission_is_assignable_at_scope(uuid, uuid, uuid)",
  "authz.fn_reconcile_expired_authority(uuid, timestamp with time zone, uuid)",
  "authz.fn_resolve_active_application_projections(text, text[], text)",
  "authz.fn_restore_entity_operation_projection(uuid, timestamp with time zone)",
  "authz.fn_retire_entity_operation_projection(uuid, timestamp with time zone)",
  "authz.fn_revoke_principal_trusted_devices(uuid, uuid, uuid, text)",
  "authz.fn_scope_assignment_covers_target(uuid, uuid, uuid, authz.propagation_mode_d)",
  "authz.fn_stage_application_projection(uuid, jsonb, jsonb, jsonb, uuid)",
  "authz.fn_stage_entity_operation_projection(uuid, uuid, text, uuid, text, jsonb)",
  "authz.trg_validate_delegation_activation()",
  "authz.trg_validate_group_role()",
  "authz.trg_validate_scoped_authority()",
  "control.admin_lookup_domain_change_allowed(text, boolean, boolean)",
  "control.admin_lookup_value_referenced(uuid)",
  "control.assemble_partner_decision(uuid, uuid, text, jsonb, jsonb, uuid)",
  "control.capture_entitlement_plan(uuid)",
  "control.claim_connector_health_job()",
  "control.command_business_partner_capability(uuid, uuid, text, boolean, bigint, text, text, uuid)",
  "control.command_business_partner_decision(uuid, text, uuid, text, bigint, text, text, text, jsonb, uuid)",
  "control.command_business_partner_lifecycle(uuid, text, uuid, text, bigint, text, text, uuid)",
  "control.command_create_business_partner_decision(uuid, text, uuid, text, uuid, uuid, uuid, uuid, jsonb, text, uuid)",
  "control.command_customer_lifecycle(uuid, uuid, uuid, uuid, uuid, text, bigint, text, date, text, jsonb, text, uuid)",
  "control.fn_activate_owner_type(uuid, uuid)",
  "control.fn_add_owner_type_purpose(uuid, uuid, text, text)",
  "control.fn_cron_schedules_for_scheduler()",
  "control.fn_deprecate_owner_type(uuid, uuid)",
  "control.fn_mark_cron_schedule_reconciled(uuid, timestamp with time zone, timestamp with time zone)",
  "control.fn_record_business_partner_mutation(uuid, text, uuid, uuid, text, text, text, bigint, text, text, text, jsonb, uuid)",
  "control.fn_register_owner_type(uuid, text, text, text, text, text, text, text, text, boolean, boolean, boolean)",
  "control.fn_remove_owner_type_purpose(uuid, uuid, text, text)",
  "control.fn_validate_owner_type_target(text, text, text, text, boolean, text)",
  "control.generate_fiscal_periods(uuid, uuid, integer, uuid, uuid, boolean)",
  "control.lock_parameter_definition(uuid)",
  "control.lookup_value_has_references(uuid)",
  "control.publication_policy_enrollment_is_active(uuid, text, uuid, uuid)",
  "control.trg_capture_entitlement_plan()",
  "control.trg_capture_lookup_extension()",
  "control.trg_guard_lookup_domain_references()",
  "control.trg_lock_cycle_domain_reference()",
  "control.trg_lookup_reference_active()",
  "control.trg_record_customer_lifecycle_mutation()",
  "control.trg_version_entitlement_plan_components()",
  "document.collaboration_mention_candidates(text)",
  "document.collaboration_principal_candidates(text, uuid)",
  "document.command_entity_case_attachment(uuid, uuid, text, uuid, text, text, uuid)",
  "document.command_entity_case_draft(uuid, uuid, bigint, uuid, text, text, text, uuid, text, uuid, text, uuid, bigint, text, jsonb, text, uuid, uuid)",
  "document.command_entity_case_lifecycle(uuid, uuid, text, bigint, uuid, uuid, text, text, uuid, uuid)",
  "document.command_entity_case_validation(uuid, uuid, bigint, uuid, text, text, text, jsonb, jsonb, jsonb, jsonb, text, uuid, uuid)",
  "document.command_internal_workforce_identity_intent(uuid, uuid, text, boolean, text, uuid, uuid)",
  "document.command_materialize_supplier_activation_case(uuid, uuid, bigint, uuid, uuid, text, text, uuid, uuid)",
  "document.command_process_document_job(uuid, uuid, text, uuid, jsonb, uuid)",
  "document.command_process_task_escalate(uuid, uuid, uuid, uuid, bigint, text, text, uuid)",
  "document.command_process_task_information(uuid, uuid, uuid, uuid, text, bigint, text, text, uuid)",
  "document.command_publish_workforce_requisition(uuid, uuid, bigint, jsonb, text, uuid)",
  "document.command_record_process_contribution(uuid, uuid, uuid, bigint, uuid, text, jsonb)",
  "document.command_worker_engagement_iam_projection(uuid, uuid, bigint, text, uuid, uuid)",
  "document.command_worker_engagement_iam_projection(uuid, uuid, bigint, text, uuid, uuid, jsonb)",
  "document.command_worker_engagement_terminate(uuid, uuid, bigint, text, uuid, uuid, text, timestamp with time zone, jsonb)",
  "document.command_worker_operational_placement_activate(uuid, uuid, bigint, text, uuid, uuid, date, date, uuid, uuid, uuid, uuid, uuid, uuid, uuid, uuid, numeric, boolean, jsonb, jsonb)",
  "document.command_workforce_iam_projection(uuid, uuid, bigint, text, uuid, uuid)",
  "document.fn_company_setup_case_approvers(uuid, uuid, uuid)",
  "document.fn_resolve_business_partner_duplicate(uuid, uuid, uuid, text, text, jsonb, jsonb, uuid, uuid)",
  "document.fn_workflow_sla_due_tenants(timestamp with time zone, integer)",
  "document.fn_workforce_request_approvers(uuid, uuid, uuid, uuid)",
  "document.process_case_has_contributor(uuid, uuid, uuid)",
  "document.process_case_reviewers(uuid, uuid, text)",
  "document.process_document_candidates()",
  "document.sweep_process_information_due(uuid, uuid, integer)",
  "document.trg_capture_comment_revision()",
  "document.trg_process_task_information_guard()",
  "document.trg_process_task_subject()",
  "event.fn_authorization_bump_epoch(text, uuid, text)",
  "event.fn_authorization_claim_invalidations(text, integer, integer)",
  "event.fn_authorization_complete_invalidation(uuid, text)",
  "event.fn_authorization_emit_invalidation(text, text, uuid, text, text, character, jsonb, timestamp with time zone)",
  "event.fn_authorization_fail_invalidation(uuid, text, text, integer)",
  "event.fn_notification_claim_deliveries(uuid, text, integer, integer)",
  "event.fn_notification_work_tenants(text, text, integer)",
  "event.fn_notification_worker_principal(uuid)",
  "event.fn_outbox_purge_completed(interval, integer)",
  "event.trg_capture_authorization_invalidation()",
  "governance.command_link_business_partner_onboarding_subject(uuid, uuid, text, uuid, text, boolean, uuid)",
  "governance.command_link_supplier_onboarding_work(uuid, uuid, uuid, uuid)",
  "master.activate_payment_term(uuid, uuid, uuid)",
  "master.command_materialize_business_partner_change_case(uuid, uuid, bigint, text, uuid, uuid)",
  "master.command_materialize_business_partner_company_case(uuid, uuid, bigint, text, uuid, uuid)",
  "master.command_materialize_business_partner_registration_case(uuid, uuid, bigint, text, uuid, uuid)",
  "master.command_materialize_business_partner_role_case(uuid, uuid, bigint, text, uuid, uuid)",
  "master.command_materialize_internal_business_partner_case(uuid, uuid, bigint, text, uuid, uuid)",
  "master.command_materialize_mesh_profile_change_case(uuid, uuid, bigint, text, uuid, uuid)",
  "master.fn_materialize_business_partner_case_relationships()",
  "master.fn_pin_business_partner_child_activation(uuid, uuid, jsonb, boolean)",
  "master.fn_refresh_mv_cpa()",
  "master.fn_resolve_dimension_set(jsonb, uuid)",
  "master.fn_resolve_principal_identity(uuid, master.identity_provider_d, text, text)",
  "master.purge_expired_reference_choices(integer)",
  "master.retire_payment_term(uuid, uuid, uuid)",
  "master.seed_audit_reason_catalog(uuid, uuid)",
  "master.seed_condition_type_catalog(uuid, uuid)",
  "master.trg_check_partner_organization_identity()",
  "master.trg_emit_operating_assignment_invalidation()",
  "master.trg_guard_partner_organization_identity()",
  "master.trg_initialize_partner_organization_identity()",
  "master.trg_record_organization_amendment()",
  "master.trg_sync_organization_scope_target()",
  "mesh.catalog_is_visible(uuid)",
  "mesh.catalog_item_is_visible(uuid)",
  "mesh.catalog_price_is_visible(uuid)",
  "mesh.command_accept_network_relationship(uuid, bigint, text, text, uuid)",
  "mesh.command_catalog_lifecycle(uuid, text, bigint, text, text, uuid)",
  "mesh.command_discover_network_relationship(uuid, uuid, uuid, uuid, date, date, text, text, uuid)",
  "mesh.command_document_envelope_lifecycle(uuid, text, text, bigint, text, text, uuid)",
  "mesh.command_issue_registration_exchange(uuid, uuid, uuid, text, text, text, integer, text, jsonb, text, timestamp with time zone, text, text, uuid)",
  "mesh.command_network_account_lifecycle(uuid, text, bigint, text, text, uuid)",
  "mesh.command_network_relationship_lifecycle(uuid, text, bigint, text, text, uuid)",
  "mesh.command_open_canonical_party_correlation_case(uuid, uuid, text, text, uuid)",
  "mesh.command_publish_catalog(uuid, bigint, text, text, uuid)",
  "mesh.command_registration_exchange_lifecycle(uuid, text, bigint, text, text, uuid)",
  "mesh.command_reject_network_relationship(uuid, bigint, text, text, uuid)",
  "mesh.command_relationship_capability_lifecycle(uuid, text, bigint, text, text, uuid)",
  "mesh.command_request_network_relationship(uuid, uuid, uuid, uuid, text, date, date, text, text, uuid)",
  "mesh.command_request_relationship_capability(uuid, text, date, date, jsonb, text, text, uuid)",
  "mesh.command_resolve_canonical_party_correlation_case(uuid, text, bigint, text, text, uuid)",
  "mesh.command_retrieve_bank_protected_token(uuid, integer, text, text, uuid)",
  "mesh.command_rotate_bank_protected_token(uuid, text, integer, text, text, uuid)",
  "mesh.command_submit_document_envelope(text, uuid, uuid, mesh.document_direction_d, uuid, uuid, uuid, uuid, uuid, text, text, text, text, text, jsonb, uuid)",
  "mesh.command_suspend_network_relationship(uuid, bigint, text, text, uuid)",
  "mesh.command_terminate_network_relationship(uuid, bigint, text, text, uuid)",
  "mesh.fn_catalog_publication_snapshot(uuid)",
  "mesh.fn_record_network_command(uuid, uuid, text, uuid, text, text, text, bigint, text, text, text, jsonb, uuid)",
  "mesh.fn_upsert_network_scope(uuid, authz.scope_kind_d, uuid, uuid, text, text, authz.scope_status_d, uuid, text)",
  "mesh.lock_profile_publication_relationship(uuid, uuid, uuid)",
  "mesh.profile_publication_is_visible(uuid)",
  "mesh.read_eligible_bank_disclosure_source(uuid, uuid, uuid, uuid, text)",
  "mesh.read_eligible_bank_disclosure_source_v2(uuid, uuid, uuid, uuid, text)",
  "mesh.trg_record_network_lifecycle()",
  "mesh.trg_sync_network_account_scope()",
  "mesh.trg_sync_network_relationship_scopes()",
  "metadata.fn_import_publication_recovery(uuid, uuid, text, text, text, jsonb, text, timestamp with time zone)",
  "metadata.fn_product_learning_source(uuid, text, text)",
  "metadata.fn_revoke_publication_recovery(uuid, text)",
  "metadata.fn_succeed_publication_recovery(uuid, uuid, jsonb, text, timestamp with time zone)",
  "metadata.trg_entity_learning_ancestry()",
  "onboarding.fn_access_token_raw()",
  "onboarding.fn_advance_case_status(uuid, onboarding.case_status_d, text, uuid)",
  "onboarding.fn_bind_onboarding_guest_context(uuid, uuid, text)",
  "onboarding.fn_can_read_onboarding_case(uuid, uuid)",
  "onboarding.fn_create_case_with_target(text, uuid, shared.application_plane_d, uuid, uuid, uuid, uuid, uuid, uuid, jsonb, jsonb, uuid, uuid, onboarding.entry_mode_d, text, onboarding.activation_criticality_d)",
  "onboarding.fn_guest_case_has_access(uuid, uuid, text)",
  "ops.acknowledge_record_transfer_cleanup(text, uuid, text, uuid, text, text, timestamp with time zone)",
  "ops.record_transfer_cleanup_candidates(text, timestamp with time zone, integer)",
  "ops.record_transfer_stuck_counts(timestamp with time zone, integer)",
  "publication.fn_acknowledge_activation(uuid, text, text, uuid, jsonb)",
  "publication.fn_authorization_successor_compilation_source(uuid)",
  "publication.fn_collection_configuration_compilation_source(uuid)",
  "publication.fn_compilation_recovery_source(jsonb, boolean)",
  "publication.fn_compiled_entity_compilation_source(uuid)",
  "publication.fn_compiled_entity_compilation_source_v2(uuid)",
  "publication.fn_compiled_entity_compilation_source_v3(uuid)",
  "publication.fn_confirm_metadata_activation(uuid, text, uuid)",
  "publication.fn_coordinated_deployment_recovery_source(uuid, text)",
  "publication.fn_create_deployment(uuid, uuid, text, text, text, integer, uuid, uuid)",
  "publication.fn_create_system_entity_release(uuid, uuid, bigint, jsonb, text[], uuid)",
  "publication.fn_create_system_entity_successor(uuid, uuid, bigint, uuid, jsonb, text[], uuid)",
  "publication.fn_emit_outbox(uuid, text, text, text, uuid, uuid, uuid, jsonb)",
  "publication.fn_entity_successor_enrollment_source(jsonb)",
  "publication.fn_entity_successor_saved_graph(uuid, uuid)",
  "publication.fn_human_execution_context(uuid)",
  "publication.fn_human_publication_preparation_source(uuid)",
  "publication.fn_human_publication_review_evidence(uuid)",
  "publication.fn_human_review_identity_status(uuid, uuid, uuid, uuid)",
  "publication.fn_human_reviewed_entity_policy(jsonb, uuid, text)",
  "publication.fn_initial_baseline_compilation_source(uuid)",
  "publication.fn_link_system_entity_release(uuid)",
  "publication.fn_native_compilation_recovery_source(jsonb, boolean)",
  "publication.fn_prepare_authorization_successor(uuid, jsonb)",
  "publication.fn_prepare_collection_configuration_release(uuid, jsonb)",
  "publication.fn_prepare_document_collection_release(uuid, jsonb)",
  "publication.fn_prepare_initial_baseline_release(uuid, uuid, jsonb)",
  "publication.fn_prepare_runtime_restoration(uuid)",
  "publication.fn_record_system_entity_validation(uuid, bigint, jsonb, jsonb, uuid)",
  "publication.fn_recoverable_deployment_coordinates(timestamp with time zone, uuid, integer)",
  "publication.fn_runtime_restoration_compilation_source(uuid)",
  "publication.fn_store_system_entity_artifact(uuid, text, jsonb, jsonb)",
  "publication.fn_system_entity_authority(uuid, text)",
  "publication.fn_system_entity_execution_metadata(uuid)",
  "publication.fn_system_entity_successor_policy(uuid)",
  "publication.fn_transition_artifact(uuid, publication.artifact_status_d, text, text, text)",
  "publication.fn_transition_deployment(uuid, publication.deployment_status_d, jsonb)",
  "publication.fn_transition_release(uuid, publication.release_status_d, uuid, uuid, jsonb)",
  "publication.fn_transition_system_entity_change_set(uuid, bigint, text, text, uuid)",
  "publication.native_worker_entity_visible(uuid)",
  "runtime_meta.fn_activate_release(uuid, jsonb)",
  "runtime_meta.fn_active_business_partner_definition(text)",
  "runtime_meta.fn_active_entity_descriptor(text, text)",
  "runtime_meta.fn_active_release(text)",
  "runtime_meta.fn_locked_live_read_resources(text[], uuid, text, integer)",
  "runtime_meta.fn_rollback_release(text, uuid, jsonb)",
  "runtime_meta.fn_stage_applied_release_payload(uuid, jsonb)",
  "runtime_meta.fn_stage_entity_projection(uuid, jsonb)",
  "runtime_meta.fn_stage_release(text, uuid, bigint, uuid, text, jsonb)",
  "runtime_meta.fn_stage_release_projection(text, uuid, bigint, uuid, text, jsonb, jsonb)",
  "runtime_meta.fn_verify_release(uuid, text, jsonb)",
  "shared.current_tenant_id()",
  "shared.current_tenant_id_soft()",
  "snapshot.fn_capture_entity(text, uuid, text, integer, text, bigint, text, snapshot.capture_kind_d, jsonb, uuid, uuid, timestamp with time zone, timestamp with time zone, snapshot.retention_class_d, text)",
  "snapshot.fn_get_entity_snapshot(uuid)",
  "snapshot.fn_publish_compiled_artifact(uuid, text, text, text, text, jsonb, jsonb, numeric)",
  "snapshot.fn_verify_entity_snapshot_chain(text, uuid)",
  "snapshot.fn_verify_entity_snapshot_hash(uuid)",
  "trustiam.lock_identity_replay_projection(uuid, uuid)"
]'::jsonb) approved(signature) WHERE approved.signature=identity_signature) THEN
            RAISE EXCEPTION 'Unregistered source definer signature: %; reconcile catalog drift before applying ownership changes', identity_signature;
        END IF;
        target_owner := COALESCE(exception->>'owner', '{
  "ai": "athyper_definer_ai",
  "audit": "athyper_definer_audit",
  "authz": "athyper_definer_authz",
  "control": "athyper_definer_control",
  "document": "athyper_definer_document",
  "event": "athyper_definer_event",
  "governance": "athyper_definer_governance",
  "master": "athyper_definer_master",
  "mesh": "athyper_definer_mesh",
  "metadata": "athyper_definer_metadata",
  "onboarding": "athyper_definer_onboarding",
  "ops": "athyper_definer_ops",
  "publication": "athyper_definer_publication",
  "runtime_meta": "athyper_definer_runtime_meta",
  "shared": "athyper_definer_shared",
  "snapshot": "athyper_definer_snapshot",
  "trustiam": "athyper_definer_trustiam"
}'::jsonb->>routine.schema_name);
        IF target_owner = '$ddlOwner' THEN target_owner := current_user; END IF;
        IF target_owner IS NULL THEN RAISE EXCEPTION 'Unregistered definer schema: %', routine.schema_name; END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = target_owner) THEN
            RAISE EXCEPTION 'Definer owner % does not exist', target_owner;
        END IF;
        IF exception IS NULL AND EXISTS (
            SELECT 1 FROM pg_roles WHERE rolname = target_owner AND (rolsuper OR rolbypassrls OR rolcanlogin OR rolcreaterole OR rolcreatedb OR rolreplication)
        ) THEN RAISE EXCEPTION 'Ordinary definer owner % must be non-login and RLS-bound', target_owner; END IF;
        IF routine.prokind = 'p' THEN
            EXECUTE format('ALTER PROCEDURE %I.%I(%s) OWNER TO %I', routine.schema_name, routine.routine_name, routine.identity_arguments, target_owner);
            EXECUTE format('REVOKE EXECUTE ON PROCEDURE %I.%I(%s) FROM PUBLIC', routine.schema_name, routine.routine_name, routine.identity_arguments);
        ELSE
            EXECUTE format('ALTER FUNCTION %I.%I(%s) OWNER TO %I', routine.schema_name, routine.routine_name, routine.identity_arguments, target_owner);
            EXECUTE format('REVOKE EXECUTE ON FUNCTION %I.%I(%s) FROM PUBLIC', routine.schema_name, routine.routine_name, routine.identity_arguments);
        END IF;
        SELECT substring(setting FROM length('search_path=') + 1) INTO configured_path
          FROM unnest(COALESCE(routine.proconfig, ARRAY[]::text[])) setting WHERE setting LIKE 'search_path=%';
        IF configured_path IS NULL THEN
            RAISE EXCEPTION 'SECURITY DEFINER % lacks an explicit search_path', identity_signature;
        END IF;
        trusted_path := ARRAY['pg_catalog'];
        FOREACH path_schema IN ARRAY string_to_array(configured_path, ',') LOOP
            path_schema := trim(both '"' FROM btrim(path_schema));
            IF path_schema IN ('pg_catalog', 'pg_temp') THEN CONTINUE; END IF;
            IF NOT '["ai","audit","authz","control","document","event","governance","ledger","master","mesh","metadata","onboarding","ops","publication","runtime_meta","shared","snapshot","trustiam"]'::jsonb ? path_schema THEN
                RAISE EXCEPTION 'SECURITY DEFINER % has an untrusted search_path schema: %', identity_signature, path_schema;
            END IF;
            IF EXISTS (
                SELECT 1 FROM pg_namespace n,
                    LATERAL aclexplode(COALESCE(n.nspacl, acldefault('n', n.nspowner))) acl
                WHERE n.nspname=path_schema AND acl.grantee=0 AND acl.privilege_type='CREATE'
            ) OR EXISTS (
                SELECT 1 FROM pg_roles r WHERE r.rolname IN ('athyper_runtime', 'athyper_worker')
                  AND to_regnamespace(path_schema) IS NOT NULL
                  AND has_schema_privilege(r.oid, to_regnamespace(path_schema), 'CREATE')
            ) THEN
                RAISE EXCEPTION 'SECURITY DEFINER % search_path schema % is writable by runtime or PUBLIC', identity_signature, path_schema;
            END IF;
            IF NOT path_schema = ANY(trusted_path) THEN trusted_path := array_append(trusted_path, path_schema); END IF;
        END LOOP;
        trusted_path := array_append(trusted_path, 'pg_temp');
        EXECUTE format('ALTER %s %I.%I(%s) SET search_path = %s',
            CASE WHEN routine.prokind='p' THEN 'PROCEDURE' ELSE 'FUNCTION' END,
            routine.schema_name, routine.routine_name, routine.identity_arguments,
            (SELECT string_agg(quote_ident(value), ', ') FROM unnest(trusted_path) value));
    END LOOP;
END
$hardening$;
