"use client";
import {useEffect,useState} from 'react';
type Row={operation:string;proposalSha256:string;proposal:{disposition:string;rationale:string;target:string;effect:string;priorApproval?:unknown;permission:{existingCode:string;proposedCode:string;catalogAction:string};scope:unknown;handler:unknown;workflow:unknown;conditions:unknown;remainingEngineering:string[]}};
type Data={reviewerId:string;assurance:string;packetRevision:string;rows:Row[];receipts:{reference:string;reviewerId:string;decisions:{operation:string;decision:string}[]}[];assessment:{remainingRows:number;unresolvedRows:number;proposalReviewComplete:boolean}};
const endpoint='/api/governance/operation-review';
function csrf(){const c=document.cookie.split('; ').find(c=>c.startsWith('__Host-athyper-csrf=')||c.startsWith('athyper-csrf='));return c?decodeURIComponent(c.slice(c.indexOf('=')+1)):'';}
export function OperationReview(){const [data,setData]=useState<Data>(),[error,setError]=useState(''),[selection,setSelection]=useState<Record<string,string>>({}),[reason,setReason]=useState(''),[business,setBusiness]=useState(false),[security,setSecurity]=useState(false),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[id,setId]=useState<string>();
useEffect(()=>{const controller=new AbortController();setData(undefined);setSelection({});setBusiness(false);setSecurity(false);setId(undefined);void fetch(endpoint,{cache:'no-store',signal:controller.signal}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.code);setData(b);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[reload]);
const selected=Object.entries(selection).filter(([,v])=>v);async function submit(){if(!data)return;setBusy(true);setError('');const submissionId=id??crypto.randomUUID();setId(submissionId);try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf()},body:JSON.stringify({packetRevision:data.packetRevision,submissionId,confirmBusiness:business,confirmSecurity:security,decisions:selected.map(([operation,decision])=>({operation,decision,proposalSha256:data.rows.find(r=>r.operation===operation)!.proposalSha256,reason}))})});const b=await r.json();if(!r.ok){if(b.code==='REVIEW_STEP_UP_REQUIRED')setData({...data,assurance:'baseline'});throw Error(b.code);}setReload(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Review unavailable');}finally{setBusy(false);}}
return <main style={{padding:'2rem',maxWidth:1100,margin:'auto'}}><h1>Business Partner operation review</h1><p>Reviewer: {data?.reviewerId??'Verifying identity'}</p><p>Review proposals only. New permissions receive no grants. Publication, enforcement and activation need separate qualification and approval.</p><p>Both nominated reviewers must independently accept a proposal. Rejection or disagreement keeps it blocked.</p>{error?<p role="alert">{error}</p>:null}<button onClick={()=>setReload(x=>x+1)}>Reload review</button>
{data&&data.assurance!=='elevated'?<form method="post" action="/api/auth/step-up/start?returnTo=%2Fmdg%2Foperation-review" onSubmit={e=>{(e.currentTarget.elements.namedItem('csrfToken') as HTMLInputElement).value=csrf();}}><input type="hidden" name="csrfToken"/><button>Continue to MFA</button></form>:null}
{data?<><p>{data.assessment.remainingRows} proposals await decisions; {data.assessment.unresolvedRows} unresolved. Native publication is not enabled by this screen.</p>{data.receipts.map(r=><p key={r.reference}>Recorded {r.reviewerId}: {r.reference}</p>)}<fieldset disabled={busy}><legend>Exact operation proposals</legend>{data.rows.map(row=>{const previous=data.receipts.find(r=>r.reviewerId===data.reviewerId&&r.decisions.some(d=>d.operation===row.operation));return <section key={row.operation} style={{border:'1px solid #bbb',padding:'1rem',margin:'1rem 0'}}><h2>{row.operation}: proposed {row.proposal.disposition}</h2><p>{row.proposal.rationale}</p><p>Existing permission: {row.proposal.permission.existingCode}<br/>Proposed permission: {row.proposal.permission.proposedCode}<br/>Catalog action: {row.proposal.permission.catalogAction}</p><details><summary>Exact scope, handler, workflow and conditions</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify({target:row.proposal.target,effect:row.proposal.effect,priorApproval:row.proposal.priorApproval,scope:row.proposal.scope,handler:row.proposal.handler,workflow:row.proposal.workflow,conditions:row.proposal.conditions,remainingEngineering:row.proposal.remainingEngineering,proposalSha256:row.proposalSha256},null,2)}</pre></details>{previous?<p>Decision recorded; a changed decision needs a new proposal revision.</p>:<label>Decision for {row.operation} <select value={selection[row.operation]??''} onChange={e=>{setId(undefined);setSelection({...selection,[row.operation]:e.target.value});}}><option value="">No decision</option><option value="approve">Accept proposed {row.proposal.disposition}</option><option value="reject">Reject proposal</option></select></label>}</section>;})}
<label>Reason for the selected decisions <textarea maxLength={2000} value={reason} onChange={e=>{setReason(e.target.value);setId(undefined);}}/></label><p>Submit separate batches when reasons differ.</p><label><input type="checkbox" checked={business} onChange={e=>{setBusiness(e.target.checked);setId(undefined);}}/> I confirm the selected business semantics and exact permission/scope proposals.</label><br/><label><input type="checkbox" checked={security} onChange={e=>{setSecurity(e.target.checked);setId(undefined);}}/> I confirm security conditions. This does not authorize grants or activation.</label></fieldset><button disabled={busy||!selected.length||!business||!security||!reason.trim()||data.assurance!=='elevated'} onClick={()=>void submit()}>Record {selected.length} explicit decisions</button></>:null}</main>;
}
