import {describe,expect,it,vi} from "vitest";
import {createMeilisearchIndex} from "../index.js";

const document={id:"x",planeKey:"neon",tenantId:"t",attachmentId:"a",entityType:"invoice",entityId:"e",title:"Invoice",text:"body",contentType:"application/pdf",fileName:"a.pdf",piiTypes:[],updatedAt:"2026-08-09T00:00:00Z"} as const;
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});

describe("Meilisearch index",()=>{
  it("forces plane and tenant filters server-side",async()=>{const fetch=vi.fn(async(_url:string,_init?:RequestInit)=>json({hits:[],estimatedTotalHits:0,processingTimeMs:2}));const index=createMeilisearchIndex({baseUrl:"http://searchcore:7700",apiKey:"secret",fetch:fetch as never});await index.search({planeKey:"mesh",tenantId:"tenant-1",text:"invoice",entityTypes:["invoice"],limit:20,offset:0});const body=JSON.parse(String(fetch.mock.calls[0]![1]!.body)) as {filter:string[]};expect(body.filter).toEqual(expect.arrayContaining(['plane_key = "mesh"','tenant_id = "tenant-1"','entity_type IN ["invoice"]']));});
  it("waits for an accepted write task and never puts the key in the body",async()=>{const fetch=vi.fn(async(url:string,_init?:RequestInit)=>url.endsWith("/tasks/7")?json({uid:7,status:"succeeded"}):json({taskUid:7},202));const index=createMeilisearchIndex({baseUrl:"http://searchcore:7700",apiKey:"master-secret",taskPollIntervalMs:0,fetch:fetch as never});await index.upsert(document);expect(fetch).toHaveBeenCalledTimes(2);expect(String(fetch.mock.calls[0]![1]!.body)).not.toContain("master-secret");expect(fetch.mock.calls[1]?.[0]).toBe("http://searchcore:7700/tasks/7");});
  it("polls an enqueued task until it succeeds",async()=>{let polls=0;const fetch=vi.fn(async(url:string)=>{if(!url.endsWith("/tasks/8"))return json({taskUid:8},202);polls++;return json({uid:8,status:polls===1?"enqueued":"succeeded"});});const index=createMeilisearchIndex({baseUrl:"http://searchcore:7700",apiKey:"secret",taskPollIntervalMs:0,fetch:fetch as never});await index.remove("x");expect(polls).toBe(2);});
  it("surfaces asynchronous task failures",async()=>{const fetch=vi.fn(async(url:string)=>url.endsWith("/tasks/9")?json({uid:9,status:"failed",error:{code:"invalid_document",message:"document is too large"}}):json({taskUid:9},202));const index=createMeilisearchIndex({baseUrl:"http://searchcore:7700",apiKey:"secret",taskPollIntervalMs:0,fetch:fetch as never});await expect(index.upsert(document)).rejects.toThrow("Meilisearch task 9 failed: document is too large");});
  it("creates an absent index and waits for settings",async()=>{const fetch=vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith("/indexes/documents")&&!init?.method)return json({},404);if(url.endsWith("/tasks/1"))return json({uid:1,status:"succeeded"});if(url.endsWith("/tasks/2"))return json({uid:2,status:"succeeded"});return json({taskUid:JSON.parse(String(init?.body)).uid?1:2},202);});const index=createMeilisearchIndex({baseUrl:"http://searchcore:7700",apiKey:"secret",taskPollIntervalMs:0,fetch:fetch as never});await index.initialize();expect(fetch.mock.calls.map(call=>call[0])).toEqual(["http://searchcore:7700/indexes/documents","http://searchcore:7700/indexes","http://searchcore:7700/tasks/1","http://searchcore:7700/indexes/documents/settings","http://searchcore:7700/tasks/2"]);});
  it("does not enqueue duplicate creation for an existing index",async()=>{const fetch=vi.fn(async(url:string,init?:RequestInit)=>{if(url.endsWith("/tasks/2"))return json({uid:2,status:"succeeded"});if(url.endsWith("/indexes/documents")&&!init?.method)return json({uid:"documents"});return json({taskUid:2},202);});const index=createMeilisearchIndex({baseUrl:"http://searchcore:7700",apiKey:"secret",taskPollIntervalMs:0,fetch:fetch as never});await index.initialize();expect(fetch.mock.calls.map(call=>call[0])).toEqual(["http://searchcore:7700/indexes/documents","http://searchcore:7700/indexes/documents/settings","http://searchcore:7700/tasks/2"]);});
  it("rejects malformed accepted task responses",async()=>{const fetch=vi.fn(async()=>json({},202));const index=createMeilisearchIndex({baseUrl:"http://searchcore:7700",apiKey:"secret",fetch:fetch as never});await expect(index.upsert(document)).rejects.toThrow("valid taskUid");});
});
