import type { AtlasExperienceDefinition } from "@athyper/platform-shell";
export const DEFAULT_DEFINITION = Object.freeze<AtlasExperienceDefinition>({
  schema: "atlas-experience-definition/1",
  scope: "home",
  widgets: [
    {
      code: "home.recommendations",
      kind: "recommendations",
      title: "Recommended for you",
      enabled: true,
      planes: ["neon", "mesh", "studio"],
      order: 10,
    },
    {
      code: "home.quick-actions",
      kind: "quick-actions",
      title: "Quick actions",
      enabled: true,
      planes: ["neon", "mesh", "studio"],
      order: 20,
    },
    {
      code: "home.workspaces",
      kind: "workspaces",
      title: "Workspaces",
      enabled: true,
      planes: ["neon", "mesh", "studio"],
      order: 30,
    },
    {
      code: "home.recent",
      kind: "recent",
      title: "Recently opened",
      enabled: true,
      planes: ["neon", "mesh", "studio"],
      order: 40,
    },
  ],
  searchSources: [
    {
      code: "mdg.navigation",
      kind: "navigation",
      label: "MDG navigation",
      enabled: true,
      planes: ["neon", "mesh", "studio"],
      routePrefix: "/mdg",
    },
    {
      code: "business-partner.records",
      kind: "record",
      label: "Business Partner records",
      enabled: true,
      planes: ["neon"],
      permissionCode: "master.business_partner.read",
      entityCode: "business_partner",
      routePrefix: "/mdg/business-partner",
    },
    {
      code: "business-partner.knowledge",
      kind: "knowledge",
      label: "Business Partner governed knowledge",
      enabled: true,
      planes: ["neon", "mesh", "studio"],
      permissionCode: "ai.agent.tools.read",
      entityCode: "business_partner",
    },
  ],
  prompts: [
    {
      code: "bp.find-supplier",
      label: "Find a supplier",
      prompt: "Find a supplier and show the governed source records",
      enabled: true,
      planes: ["neon", "mesh"],
      agentCode: "business-partner-guide",
    },
    {
      code: "bp.review-duplicates",
      label: "Review duplicate candidates",
      prompt:
        "Show business partner duplicate candidates that need my attention",
      enabled: true,
      planes: ["neon"],
      agentCode: "business-partner-steward",
    },
    {
      code: "bp.explain-publication",
      label: "Explain publication",
      prompt: "Explain how an approved business partner change is published",
      enabled: true,
      planes: ["studio", "mesh"],
      agentCode: "business-partner-guide",
    },
  ],
  agents: [
    {
      code: "business-partner-guide",
      name: "Business Partner Guide",
      description:
        "Permission-aware answers grounded in governed Business Partner sources.",
      enabled: true,
      planes: ["neon", "mesh", "studio"],
      publicModelId: "atlas-fast",
      dataClass: "internal",
      promptRevision: "prompt-r1",
      toolCodes: ["records_query"],
    },
    {
      code: "business-partner-steward",
      name: "Business Partner Steward",
      description:
        "Steward assistance with governed previews for approved Business Partner tools.",
      enabled: true,
      planes: ["neon"],
      publicModelId: "atlas-fast",
      dataClass: "confidential",
      promptRevision: "prompt-r1",
      toolCodes: ["records_query", "business_partner_update"],
    },
  ],
});
