import{createHash,randomUUID}from"node:crypto";import type{AttachmentIdentity,AttachmentLifecycleScheduler,AttachmentStatus,AttachmentUploadIntent,LegalHoldRepository,SeriesRepository,StagedUpload}from"@athyper/server-contract-attachments";import type{MalwareScanner}from"@athyper/server-contract-malware-scanning";import type{ObjectStorage}from"@athyper/server-contract-object-storage";import type{PlaneTransactionCoordinator}from"@athyper/server-foundation/transaction";import type{AttachmentQuotaLedger,AttachmentQuotaPolicyResolver}from"./quota.js";
export interface AttachmentRecord{readonly id:string;readonly status:AttachmentStatus;readonly storageKey:string;readonly quarantineKey?:string;readonly thumbnailKey?:string;readonly previewKey?:string;readonly isCurrent:boolean;readonly isActive:boolean;readonly hasLegalHold:boolean;readonly expiresAt?:string;readonly retentionUntil?:string;readonly seriesId?:string;}
export interface AttachmentRepository<T>{createStaged(input:AttachmentUploadIntent&{storageKey:string;expiresAt:string},tx:T):Promise<AttachmentRecord>;load(identity:AttachmentIdentity,tx:T):Promise<AttachmentRecord|null>;finalizeClean(identity:AttachmentIdentity,input:{storageKey:string;sha256:string;sizeBytes:number;contentType:string},tx:T):Promise<AttachmentRecord>;quarantine(identity:AttachmentIdentity,reason:string,tx:T):Promise<void>;deactivate(identity:AttachmentIdentity,reason:string,tx:T):Promise<void>;expire(identity:AttachmentIdentity,tx:T):Promise<void>;markPurged(identity:AttachmentIdentity,tx:T):Promise<void>;}
export interface AttachmentLifecycleOptions<T>{readonly transactions:PlaneTransactionCoordinator<T>;readonly repository:AttachmentRepository<T>;readonly storage:ObjectStorage;readonly scanner:MalwareScanner;readonly quota:AttachmentQuotaLedger<T>;readonly quotaPolicies:AttachmentQuotaPolicyResolver;readonly scheduler?:AttachmentLifecycleScheduler;readonly uploadUrlTtlSeconds?:number;readonly seriesRepository?:SeriesRepository<T>;readonly legalHoldRepository?:LegalHoldRepository<T>;}
export interface AttachmentLifecycle{stage(input:AttachmentUploadIntent):Promise<StagedUpload>;finalize(identity:AttachmentIdentity,contentType:string):Promise<AttachmentRecord>;deactivate(identity:AttachmentIdentity,reason?:string):Promise<void>;expire(identity:AttachmentIdentity):Promise<void>;purge(identity:AttachmentIdentity):Promise<boolean>;}
export function createAttachmentLifecycle<T>(o:AttachmentLifecycleOptions<T>):AttachmentLifecycle{const uploadTtl=o.uploadUrlTtlSeconds??900;return{
 async stage(input){valid(input);if(!input.sizeBytes||input.sizeBytes<1)throw new TypeError("Attachment size is required");const policy=await o.quotaPolicies.resolve(input),key=stagingKey(input),expiresAt=new Date(Date.now()+policy.reservationTtlSeconds*1000).toISOString();await o.transactions.run(input.planeKey,input,async tx=>{const reserved=await o.quota.reserve({...input,bytes:input.sizeBytes!,policy,expiresAt},tx);if(reserved==='created')await o.repository.createStaged({...input,storageKey:key,expiresAt},tx);});const current=await o.transactions.run(input.planeKey,input,tx=>o.repository.load(input,tx));if(!current)throw new Error("Attachment reservation exists without staged resource");return{attachmentId:input.attachmentId,storageKey:current.storageKey,uploadUrl:await o.storage.createUploadUrl(current.storageKey,uploadTtl),expiresAt:current.expiresAt??expiresAt};},
 async finalize(identity,contentType){const current=await o.transactions.run(identity.planeKey,identity,tx=>o.repository.load(identity,tx));if(!current)throw new Error("Attachment not found");if(current.status==='active')return current;if(!['uploading','uploaded','pending'].includes(current.status))throw new Error("Attachment is not awaiting upload");const bytes=await o.storage.get(current.storageKey),scan=await o.scanner.scan({content:bytes,contentType,fileName:current.id});if(scan.status!=="clean"){await o.transactions.run(identity.planeKey,identity,async tx=>{await o.repository.quarantine(identity,"malware_detected",tx);await o.quota.release(identity,tx);});throw new Error("Attachment was quarantined");}const destinationKey=activeKey(identity);await o.storage.copy(current.storageKey,destinationKey);const digest=createHash("sha256").update(bytes).digest("hex"),policy=await o.quotaPolicies.resolve(identity);const saved=await o.transactions.run(identity.planeKey,identity,async tx=>{await o.quota.commit({...identity,actualBytes:bytes.byteLength,policy},tx);return o.repository.finalizeClean(identity,{storageKey:destinationKey,sha256:digest,sizeBytes:bytes.byteLength,contentType},tx);});await o.storage.delete(current.storageKey).catch(()=>undefined);await o.scheduler?.scheduleExtraction(identity);await o.scheduler?.scheduleDerivatives({...identity,sourceSha256:digest});return saved;},
 async deactivate(identity,reason="deactivated"){await o.transactions.run(identity.planeKey,identity,async tx=>{await o.repository.deactivate(identity,reason,tx);await o.quota.release(identity,tx);});await o.scheduler?.schedulePurge(identity);},
 async expire(identity){await o.transactions.run(identity.planeKey,identity,async tx=>{await o.repository.expire(identity,tx);await o.quota.release(identity,tx);});await o.scheduler?.schedulePurge(identity);},
 async purge(identity){const current=await o.transactions.run(identity.planeKey,identity,tx=>o.repository.load(identity,tx));if(!current||current.hasLegalHold)return false;if(current.retentionUntil&&new Date(current.retentionUntil)>new Date())return false;if(current.seriesId&&o.seriesRepository&&o.legalHoldRepository){const[held,series]=await o.transactions.run(identity.planeKey,identity,tx=>Promise.all([o.legalHoldRepository!.hasActiveHold(identity.tenantId,current.seriesId!,tx),o.seriesRepository!.load(identity.tenantId,current.seriesId!,tx)]));if(held||(series?.retentionUntil&&new Date(series.retentionUntil)>new Date()))return false;}for(const key of[current.storageKey,current.thumbnailKey,current.previewKey])if(key)await o.storage.delete(key).catch(()=>undefined);await o.transactions.run(identity.planeKey,identity,async tx=>{await o.repository.markPurged(identity,tx);await o.quota.release(identity,tx);});return true;}
};}
function stagingKey(i:AttachmentIdentity){return`quarantine/${i.planeKey}/${i.tenantId}/${i.attachmentId}/${randomUUID()}`;}function activeKey(i:AttachmentIdentity){return`attachments/${i.planeKey}/${i.tenantId}/${i.attachmentId}/original`;}function valid(i:AttachmentUploadIntent){if(!/^[0-9a-f-]{36}$/i.test(i.attachmentId)||!/^[0-9a-f-]{36}$/i.test(i.tenantId)||!/^[0-9a-f-]{36}$/i.test(i.principalId))throw new TypeError("Attachment identity must contain UUIDs");if(!i.fileName.trim()||!i.contentType.trim())throw new TypeError("Attachment filename and content type are required");}
