import {randomUUID}from"node:crypto";import {sql,type Transaction} from "kysely";
import type {AttachmentRecord,AttachmentRepository} from "./attachment-lifecycle.js";

export type AttachmentTransaction=Transaction<Record<string,never>>;
interface Row{ id:string;status:AttachmentRecord["status"];storage_key:string;thumbnail_key:string|null;preview_key:string|null;is_current:boolean;is_active:boolean;expires_at:Date|string|null;retention_until:Date|string|null;series_id:string|null;has_legal_hold:boolean; }

export function createKyselyAttachmentRepository(storageBucket:string):AttachmentRepository<AttachmentTransaction>{if(!storageBucket.trim())throw new TypeError("Attachment storage bucket is required");return{
  async createStaged(input,tx){let parent:{id:string;version_no:number;series_id:string|null}|undefined,seriesId=input.seriesId;if(input.parentAttachmentId){const loaded=await sql<{id:string;version_no:number;series_id:string|null}>`SELECT id,version_no,series_id FROM document.attachment WHERE tenant_id=${input.tenantId}::uuid AND id=${input.parentAttachmentId}::uuid AND is_active FOR UPDATE`.execute(tx);parent=loaded.rows[0];if(!parent)throw new Error("Parent attachment not found");seriesId??=parent.series_id??randomUUID();if(parent.series_id&&input.seriesId&&parent.series_id!==input.seriesId)throw new Error("Attachment series mismatch");if(!parent.series_id){await sql`INSERT INTO document.attachment_series(id,tenant_id,current_attachment_id,created_by) VALUES(${seriesId}::uuid,${input.tenantId}::uuid,${parent.id}::uuid,${input.principalId}::uuid)`.execute(tx);await sql`UPDATE document.attachment SET series_id=${seriesId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND id=${parent.id}::uuid`.execute(tx);await sql`UPDATE document.attachment_link SET attachment_series_id=${seriesId}::uuid WHERE tenant_id=${input.tenantId}::uuid AND attachment_id=${parent.id}::uuid`.execute(tx);}}
    const result=await sql<Row>`INSERT INTO document.attachment(id,tenant_id,file_name,original_filename,content_type,size_bytes,kind,storage_bucket,storage_key,version_no,parent_attachment_id,series_id,is_current,is_active,is_virus_scanned,expires_at,uploaded_by,metadata,status,created_by) VALUES(${input.attachmentId}::uuid,${input.tenantId}::uuid,${input.fileName},${input.fileName},${input.contentType},${input.sizeBytes??null},'attachment',${storageBucket},${input.storageKey},${parent?parent.version_no+1:1},${parent?.id??null}::uuid,${seriesId??null}::uuid,${parent?false:true},true,false,${input.expiresAt}::timestamptz,${input.principalId}::uuid,${JSON.stringify({staged_size_bytes:input.sizeBytes??null,...(input.entityType?{entity_type:input.entityType}:{}),...(input.entityId?{entity_id:input.entityId}:{})})}::jsonb,'uploading',${input.principalId}::uuid) RETURNING *,false AS has_legal_hold`.execute(tx);return map(required(result.rows[0]));},
  async load(identity,tx){const result=await sql<Row>`SELECT attachment.*,EXISTS(SELECT 1 FROM document.attachment_legal_hold hold WHERE hold.tenant_id=attachment.tenant_id AND hold.attachment_series_id=attachment.series_id AND hold.released_at IS NULL) AS has_legal_hold FROM document.attachment attachment WHERE attachment.tenant_id=${identity.tenantId}::uuid AND attachment.id=${identity.attachmentId}::uuid AND attachment.uploaded_by=${identity.principalId}::uuid LIMIT 1`.execute(tx);return result.rows[0]?map(result.rows[0]):null;},
  async finalizeClean(identity,input,tx){const result=await sql<Row>`UPDATE document.attachment SET storage_key=${input.storageKey},sha256=${input.sha256},size_bytes=${input.sizeBytes},content_type=${input.contentType},status='active',is_active=true,is_virus_scanned=true,expires_at=NULL,status_changed_at=clock_timestamp(),status_changed_by=${identity.principalId}::uuid,updated_by=${identity.principalId}::uuid WHERE tenant_id=${identity.tenantId}::uuid AND id=${identity.attachmentId}::uuid AND uploaded_by=${identity.principalId}::uuid AND status IN('pending','uploading','uploaded') RETURNING *,false AS has_legal_hold`.execute(tx);const row=required(result.rows[0]);if(row.series_id){await sql`UPDATE document.attachment SET is_current=(id=${identity.attachmentId}::uuid),updated_by=${identity.principalId}::uuid WHERE tenant_id=${identity.tenantId}::uuid AND series_id=${row.series_id}::uuid`.execute(tx);await sql`UPDATE document.attachment_series SET current_attachment_id=${identity.attachmentId}::uuid,updated_at=clock_timestamp(),updated_by=${identity.principalId}::uuid WHERE tenant_id=${identity.tenantId}::uuid AND id=${row.series_id}::uuid`.execute(tx);await sql`UPDATE document.attachment_link SET attachment_id=${identity.attachmentId}::uuid WHERE tenant_id=${identity.tenantId}::uuid AND attachment_series_id=${row.series_id}::uuid`.execute(tx);}return map({...row,is_current:true});},
  async quarantine(identity,reason,tx){await sql`UPDATE document.attachment SET status='quarantined',is_active=false,metadata=metadata||${JSON.stringify({quarantine_reason:reason})}::jsonb,status_changed_at=clock_timestamp(),status_changed_by=${identity.principalId}::uuid,updated_by=${identity.principalId}::uuid WHERE tenant_id=${identity.tenantId}::uuid AND id=${identity.attachmentId}::uuid`.execute(tx);},
  async deactivate(identity,reason,tx){await sql`UPDATE document.attachment SET status='deleted',is_active=false,metadata=metadata||${JSON.stringify({deactivation_reason:reason})}::jsonb,status_changed_at=clock_timestamp(),status_changed_by=${identity.principalId}::uuid,updated_by=${identity.principalId}::uuid WHERE tenant_id=${identity.tenantId}::uuid AND id=${identity.attachmentId}::uuid`.execute(tx);},
  async expire(identity,tx){await sql`UPDATE document.attachment SET status='expired',is_active=false,status_changed_at=clock_timestamp(),status_changed_by=${identity.principalId}::uuid,updated_by=${identity.principalId}::uuid WHERE tenant_id=${identity.tenantId}::uuid AND id=${identity.attachmentId}::uuid`.execute(tx);},
  async markPurged(identity,tx){await sql`UPDATE document.attachment SET status='deleted',is_active=false,storage_key='purged/'||id::text,status_changed_at=clock_timestamp(),status_changed_by=${identity.principalId}::uuid,updated_by=${identity.principalId}::uuid WHERE tenant_id=${identity.tenantId}::uuid AND id=${identity.attachmentId}::uuid`.execute(tx);},
};}
function map(row:Row):AttachmentRecord{return{id:row.id,status:row.status,storageKey:row.storage_key,...(row.thumbnail_key?{thumbnailKey:row.thumbnail_key}:{}),...(row.preview_key?{previewKey:row.preview_key}:{}),isCurrent:row.is_current,isActive:row.is_active,hasLegalHold:Boolean(row.has_legal_hold),...(row.expires_at?{expiresAt:iso(row.expires_at)}:{}),...(row.retention_until?{retentionUntil:iso(row.retention_until)}:{}),...(row.series_id?{seriesId:row.series_id}:{})};}
function required(row:Row|undefined):Row{if(!row)throw new Error("Attachment persistence conflict");return row;}
function iso(value:Date|string):string{return value instanceof Date?value.toISOString():new Date(value).toISOString();}
