import { nativeStructuralMembers } from "@athyper/server-contract-meta-entity-authoring";
const nativeColumns = (family: keyof typeof nativeStructuralMembers) => [
  "id",
  ...Object.keys(nativeStructuralMembers[family].columns),
];
// Existing native graph projection; target normalized F0 contracts remain separately gated.
export const BRANCH_COLUMNS = {
  entity_capability: [
    "id",
    "capabilityKey",
    "declaration",
    "binding",
    "profile",
    "profileDefinition",
    "overrides",
  ],
  entity_class_profile: [
    "entityClass",
    "profileVersion",
    "fallbackName",
    "description",
    "defaultBackingKind",
    "defaultApiExposure",
    "defaultReadMode",
    "defaultWriteMode",
    "defaultConcurrencyMode",
    "defaultChangePolicy",
  ],
  entity_runtime_profile: [
    "id",
    "profileKey",
    "backingKind",
    "storagePlane",
    "storageSchema",
    "storageObject",
    "apiExposure",
    "readMode",
    "writeMode",
    "readHandlerKey",
    "writeHandlerKey",
    "createMode",
    "concurrencyMode",
    "recordVersionFieldKey",
    "tenantFieldKey",
    "softDeleteFieldKey",
    "draftTtlHours",
  ],
  entity_field: [
    "id",
    "fieldKey",
    "description",
    "dataType",
    "typeConfig",
    "cardinality",
    "valueOrigin",
    "writeMode",
    "storagePath",
    "defaultSpec",
    "computationSpec",
    "validationSpec",
    "dataClassification",
    "retentionPolicyCode",
    "status",
    "replacementFieldKey",
    "deprecatedSinceReleaseNo",
    "plannedRemovalReleaseNo",
  ],
  entity_key: nativeColumns("keys"),
  entity_key_field: nativeColumns("keyFields"),
  entity_search_profile: nativeColumns("searchProfiles"),
  entity_search_field: nativeColumns("searchFields"),
  entity_relation: nativeColumns("relations"),
  entity_relation_target:
    nativeColumns("relationTargets").concat("targetEntityCode"),
  entity_relation_field: nativeColumns("relationFields"),
  entity_surface: [
    "id",
    "surfaceKey",
    "surfaceKind",
    "title",
    "description",
    "layoutKind",
    "layoutConfig",
    "isDefault",
    "status",
    "replacementSurfaceKey",
    "deprecatedSinceReleaseNo",
    "plannedRemovalReleaseNo",
  ],
  entity_surface_section: [
    "id",
    "entitySurfaceId",
    "sectionKey",
    "parentSectionId",
    "sectionKind",
    "title",
    "description",
    "position",
    "columnCount",
    "collapsible",
    "collapsedByDefault",
    "layoutConfig",
  ],
  entity_surface_field_binding: [
    "id",
    "entitySurfaceId",
    "entitySurfaceSectionId",
    "entityFieldId",
    "bindingKey",
    "position",
    "labelOverride",
    "helpText",
    "placeholder",
    "widgetKey",
    "columnSpan",
    "showRequiredIndicator",
    "displayConfig",
    "visibilityRule",
    "editabilityRule",
    "status",
  ],
  entity_operation: [
    "id",
    "operationKey",
    "operationKind",
    "label",
    "description",
    "handlerKey",
    "permissionCode",
    "executionMode",
    "idempotencyMode",
    "inputSurfaceKey",
    "confirmationSurfaceKey",
    "resultSurfaceKey",
    "requiresMfa",
    "auditEventCode",
    "status",
    "replacementOperationKey",
    "deprecatedSinceReleaseNo",
    "plannedRemovalReleaseNo",
  ],
  entity_operation_permission: [
    "id",
    "entityOperationId",
    "targetPlane",
    "permissionCode",
    "permissionKind",
    "status",
  ],
  entity_surface_operation: [
    "id",
    "entitySurfaceId",
    "entityOperationId",
    "entitySurfaceSectionId",
    "placementKey",
    "interactionTarget",
    "selectionMode",
    "position",
    "labelOverride",
    "iconKey",
    "presentationVariant",
    "confirmationSurfaceId",
    "visibilityRule",
    "status",
  ],
  entity_operation_rule: [
    "id",
    "entityOperationId",
    "ruleKey",
    "priority",
    "decision",
    "planeCode",
    "lifecycleStateCode",
    "lifecycleTransitionCode",
    "requiredCapabilityCode",
    "reasonCode",
    "status",
  ],
  entity_flow: [
    "id",
    "flowKey",
    "flowKind",
    "title",
    "description",
    "navigationMode",
    "entryOperationId",
    "completionOperationId",
    "allowDraftResume",
    "status",
    "replacementFlowKey",
    "deprecatedSinceReleaseNo",
    "plannedRemovalReleaseNo",
  ],
  entity_flow_step: [
    "id",
    "entityFlowId",
    "entitySurfaceId",
    "stepKey",
    "position",
    "titleOverride",
    "description",
    "entryCondition",
    "completionCondition",
    "isOptional",
  ],
  entity_policy_binding: [
    "id",
    "entityOperationId",
    "policyDefinitionId",
    "bindingKey",
    "bindingStage",
    "enforcement",
    "priority",
    "inputMapping",
    "status",
  ],
  entity_field_policy_binding: [
    "id",
    "entityFieldId",
    "entityOperationId",
    "policyDefinitionId",
    "bindingKey",
    "bindingStage",
    "enforcement",
    "priority",
    "inputMapping",
    "status",
  ],
  entity_contract_test_case: [
    "id",
    "testKey",
    "testKind",
    "title",
    "description",
    "targetPlane",
    "entityOperationId",
    "entityFlowId",
    "inputContext",
    "expectedOutcome",
    "expectedDiagnosticCodes",
    "status",
  ],
  entity_lifecycle_binding: [
    "id",
    "entityFieldId",
    "bindingKey",
    "targetPlane",
    "lifecycleCode",
    "lifecycleRevision",
    "required",
    "status",
  ],
  entity_lifecycle_operation_binding: [
    "id",
    "entityLifecycleBindingId",
    "entityOperationId",
    "mappingKey",
    "transitionCode",
    "status",
  ],
  entity_numbering_binding: [
    "id",
    "entityFieldId",
    "entityOperationId",
    "bindingKey",
    "targetPlane",
    "policyCode",
    "policyRevision",
    "assignmentMode",
    "required",
    "status",
  ],
  entity_operation_scope_binding: [
    "id",
    "entityOperationId",
    "bindingKey",
    "targetPlane",
    "decisionMode",
    "scopeKind",
    "coordinateSource",
    "coordinateKey",
    "resolverKey",
    "missingValueBehavior",
    "status",
  ],
  entity_change_case_binding: [
    "id",
    "entityOperationId",
    "bindingKey",
    "caseKind",
    "caseEntityCode",
    "workflowKey",
    "materializationBindingKey",
    "status",
  ],
  entity_operation_context_requirement: [
    "id",
    "entityOperationId",
    "coordinateKey",
    "sourceKind",
    "sourceFieldKey",
    "required",
    "status",
  ],
  entity_field_reference_binding: [
    "id",
    "entityFieldId",
    "bindingKey",
    "referenceKind",
    "targetEntityCode",
    "lookupDomain",
    "resolverKey",
    "requireActive",
    "status",
  ],
  entity_materialization_binding: [
    "id",
    "bindingKey",
    "targetEntityCode",
    "materializerKey",
    "targetCollectionKey",
    "status",
  ],
  entity_materialization_field_mapping: [
    "id",
    "entityMaterializationBindingId",
    "sourceFieldKey",
    "targetFieldKey",
    "transformKey",
    "required",
    "position",
  ],
} as const;
