import { createOperation, encodePathSegment, type HttpClient } from "@athyper/platform-api-client";

export type RequestStatus="draft"|"validating"|"validation_failed"|"pending_approval"|"returned"|"approved"|"rejected"|"applying"|"applied"|"failed"|"cancelled"|"superseded";
export interface PartnerRequest {readonly id:string;readonly requestNo:string;readonly kind:string;readonly source:Readonly<{kind:string}>;readonly requestedRole?:"supplier"|"customer";readonly operatingOrganizationId?:string;readonly companyCodeId?:string;readonly proposedPayload:Readonly<Record<string,unknown>>;readonly validationSummary:Readonly<Record<string,unknown>>;readonly duplicateSummary:Readonly<Record<string,unknown>>;readonly changeImpact:Readonly<Record<string,unknown>>;readonly workflowRequestId?:string;readonly materializedBusinessPartnerId?:string;readonly materializedSupplierId?:string;readonly materializedCustomerId?:string;readonly materializedSupplierCompanyProfileId?:string;readonly materializedCustomerCompanyProfileId?:string;readonly materializedOperatingOrganizationAssignmentId?:string;readonly materializationSnapshotId?:string;readonly submittedAt?:string;readonly submittedBy?:string;readonly approvedAt?:string;readonly approvedBy?:string;readonly appliedAt?:string;readonly appliedBy?:string;readonly status:RequestStatus;readonly rowVersion:number;readonly createdAt:string;readonly updatedAt?:string;}
export interface ValidationFinding{readonly ruleCode:string;readonly severity:"info"|"warning"|"error";readonly fieldPath:string;readonly outcome:"passed"|"failed"|"skipped";readonly messageCode:string;readonly evidenceReference:Readonly<Record<string,unknown>>;}
export interface RequestView{readonly request:PartnerRequest;readonly validationFindings:readonly ValidationFinding[];readonly workflow?:Readonly<{requestId:string;stageId:string;workItemId:string;workItemVersion:number;workItemStatus:string;definition:Readonly<{code:string;version:number;hash:string}>}>;}
export interface PartnerAggregate{readonly businessPartner:Readonly<{id:string;code:string;name:string;displayName?:string;legalName?:string;partnerCategory:string;legalForm?:string;registrationCountryCode?:string;incorporationDate?:string;websiteUrl?:string;description?:string;aliases:readonly string[];status:string;createdAt:string;updatedAt?:string}>;readonly suppliers:readonly Readonly<{id:string;supplierCode:string;supplierType:string;status:string;createdAt:string;updatedAt?:string}>[];readonly customers:readonly Readonly<{id:string;customerCode:string;customerType:string;status:string;designations:readonly Readonly<{id:string;type:string;priorityTier?:number;effectiveFrom:string;effectiveUntil?:string}>[];createdAt:string;updatedAt?:string}>[];readonly supplierCompanyProfiles:readonly Readonly<{id:string;supplierId:string;companyCodeId:string;currencyCode?:string;paymentTermId?:string;status:string;createdAt:string;updatedAt?:string}>[];readonly customerCompanyProfiles:readonly Readonly<{id:string;customerId:string;companyCodeId:string;currencyCode?:string;paymentTermId?:string;statementCycleCode?:string;status:string;createdAt:string;updatedAt?:string}>[];readonly organizationAssignments:readonly Readonly<{id:string;operatingOrganizationId:string;operatingOrganizationCode:string;operatingOrganizationName:string;partnerRole:string;status:string;effectiveFrom:string;effectiveUntil?:string}>[];readonly onboardingRequests:readonly PartnerRequest[];}
export interface PartnerEligibility{readonly businessPartnerId:string;readonly role:"supplier"|"customer";readonly operatingOrganizationId:string;readonly operationCode:string;readonly businessDate:string;readonly eligible:boolean;readonly reasons:readonly Readonly<{code:string;severity:"blocking"|"warning";recordId?:string;detail?:string}>[];readonly qualifications:readonly Readonly<{id:string;qualificationTypeCode:string;decision:string;effectiveFrom?:string;effectiveUntil?:string;nextReviewAt?:string;rowVersion:number}>[];readonly riskAssessment?:Readonly<{id:string;status:string;riskBand:string;overallScore?:number;nextReviewAt?:string;version:number}>;readonly activeBlockIds:readonly string[];readonly preferredSupplier:boolean;readonly effectivePreferenceIds:readonly string[];readonly decisionFingerprint:string;}
export interface CustomerCreditReview{readonly id:string;readonly businessPartnerId:string;readonly customerId:string;readonly operatingOrganizationId:string;readonly companyCodeId:string;readonly reviewTypeCode:string;readonly requestedCreditLimit?:number;readonly requestedCurrencyCode?:string;readonly approvedCreditLimit?:number;readonly approvedCurrencyCode?:string;readonly riskClassCode?:string;readonly decision:string;readonly decisionReason?:string;readonly effectiveFrom:string;readonly effectiveUntil?:string;readonly rowVersion:number;readonly createdAt:string;readonly createdBy:string;}
export interface PartnerRequestDraft{readonly operatingOrganizationId:string;readonly companyCodeId?:string;readonly proposedPayload:Readonly<Record<string,unknown>>;}
export interface PartnerRoleExtensionDraft{readonly businessPartnerId:string;readonly role:"supplier"|"customer";readonly operatingOrganizationId:string;readonly companyCodeId?:string;readonly proposedPayload:Readonly<Record<string,unknown>>;}
export interface PartnerScopeConfigurationDraft{readonly businessPartnerId:string;readonly kind:"assign_organization"|"configure_company";readonly role:"supplier"|"customer";readonly operatingOrganizationId:string;readonly companyCodeId?:string;readonly proposedPayload:Readonly<Record<string,unknown>>;}

const createRequest=createOperation<{readonly request:PartnerRequest;readonly replayed:boolean},Readonly<{idempotencyKey:string;kind:"new_partner"|"add_supplier"|"add_customer"|"assign_organization"|"configure_company";source:Readonly<{kind:"manual"}>;targetBusinessPartnerId?:string;requestedRole:"supplier"|"customer";operatingOrganizationId?:string;companyCodeId?:string;proposedPayload:Readonly<Record<string,unknown>>}>>({method:"POST",path:"/api/neon/business-partner-requests",idempotency:"required",parse:parseMutation});
const listRequests=createOperation<readonly PartnerRequest[]>({method:"GET",path:"/api/neon/business-partner-requests",parse:parseList});
const readView=createOperation<RequestView>({method:"GET",path:({requestId})=>`/api/neon/business-partner-requests/${encodePathSegment(requestId)}/view`,parse:parseView});
const patchRequest=createOperation<PartnerRequest,Readonly<{expectedVersion:number;proposedPayload:Readonly<Record<string,unknown>>;operatingOrganizationId?:string;companyCodeId?:string|null}>>({method:"PATCH",path:({requestId})=>`/api/neon/business-partner-requests/${encodePathSegment(requestId)}`,idempotency:"required",parse:parseRequest});
const validateRequest=createOperation<Readonly<{request:PartnerRequest;validation:Readonly<{valid:boolean;findings:readonly ValidationFinding[]}>}>,Readonly<{expectedVersion:number}>>({method:"POST",path:({requestId})=>`/api/neon/business-partner-requests/${encodePathSegment(requestId)}/validate`,idempotency:"required"});
const submitRequest=createOperation<Readonly<{request:PartnerRequest;workflow:Readonly<{requestId:string;stageId:string;workItemId:string}>;replayed:boolean}>,Readonly<{expectedVersion:number;idempotencyKey:string}>>({method:"POST",path:({requestId})=>`/api/neon/business-partner-requests/${encodePathSegment(requestId)}/submit`,idempotency:"required"});
const decideRequest=createOperation<Readonly<{request:PartnerRequest;replayed:boolean}>,Readonly<{workflowRequestId:string;workItemId:string;expectedRequestVersion:number;expectedWorkItemVersion:number;decision:"return"|"reject"|"approve";reason:string;idempotencyKey:string}>>({method:"POST",path:({requestId})=>`/api/neon/business-partner-requests/${encodePathSegment(requestId)}/decisions`,idempotency:"required"});
const applyRequest=createOperation<Readonly<{request:PartnerRequest;materialization:Readonly<{businessPartnerId:string;partnerRole:"supplier"|"customer";roleId:string;supplierId?:string;customerId?:string;companyProfileId?:string;operatingOrganizationAssignmentId?:string;snapshotId:string}>;replayed:boolean}>,Readonly<{expectedVersion:number;idempotencyKey:string}>>({method:"POST",path:({requestId})=>`/api/neon/business-partner-requests/${encodePathSegment(requestId)}/apply`,idempotency:"required"});
const readAggregate=createOperation<PartnerAggregate>({method:"GET",path:({businessPartnerId})=>`/api/neon/business-partners/${encodePathSegment(businessPartnerId)}`,parse:parseAggregate});
const readEligibility=createOperation<PartnerEligibility>({method:"GET",path:({businessPartnerId})=>`/api/neon/business-partners/${encodePathSegment(businessPartnerId)}/eligibility`,parse:parseEligibility});
const listCustomerCredit=createOperation<readonly CustomerCreditReview[]>({method:"GET",path:({businessPartnerId})=>`/api/neon/business-partners/${encodePathSegment(businessPartnerId)}/customer-credit-reviews`,parse:value=>{if(!Array.isArray(value))throw new TypeError("Customer credit response must be an array");return value as unknown as readonly CustomerCreditReview[];}});
const createCustomerCredit=createOperation<Readonly<{review:CustomerCreditReview;replayed:boolean}>,Readonly<Record<string,unknown>>>({method:"POST",path:({businessPartnerId})=>`/api/neon/business-partners/${encodePathSegment(businessPartnerId)}/customer-credit-reviews`,idempotency:"required"});
const decideCustomerCredit=createOperation<Readonly<{review:CustomerCreditReview;replayed:boolean}>,Readonly<Record<string,unknown>>>({method:"POST",path:({reviewId})=>`/api/neon/customer-credit-reviews/${encodePathSegment(reviewId)}/decisions`,idempotency:"required"});
const customerLifecycle=createOperation<Readonly<{customerId:string;status:string;eventId:string;replayed:boolean;readiness?:PartnerEligibility}>,Readonly<Record<string,unknown>>>({method:"POST",path:({businessPartnerId})=>`/api/neon/business-partners/${encodePathSegment(businessPartnerId)}/customer-lifecycle`,idempotency:"required"});

export function createBusinessPartnerClient(http:HttpClient){return Object.freeze({
  create:(draft:PartnerRequestDraft,key=commandKey("create"))=>http.request(createRequest,{body:{idempotencyKey:key,kind:"new_partner",source:{kind:"manual"},requestedRole:"supplier",...draft},idempotencyKey:key}),
  onboardCustomer:(draft:PartnerRequestDraft,key=commandKey("create-customer"))=>http.request(createRequest,{body:{idempotencyKey:key,kind:"new_partner",source:{kind:"manual"},requestedRole:"customer",...draft},idempotencyKey:key}),
  extend:(draft:PartnerRoleExtensionDraft,key=commandKey(`add-${draft.role}`))=>http.request(createRequest,{body:{idempotencyKey:key,kind:draft.role==="supplier"?"add_supplier":"add_customer",source:{kind:"manual"},targetBusinessPartnerId:draft.businessPartnerId,requestedRole:draft.role,operatingOrganizationId:draft.operatingOrganizationId,...(draft.companyCodeId?{companyCodeId:draft.companyCodeId}:{}),proposedPayload:draft.proposedPayload},idempotencyKey:key}),
  configureScope:(draft:PartnerScopeConfigurationDraft,key=commandKey(draft.kind))=>http.request(createRequest,{body:{idempotencyKey:key,kind:draft.kind,source:{kind:"manual"},targetBusinessPartnerId:draft.businessPartnerId,requestedRole:draft.role,operatingOrganizationId:draft.operatingOrganizationId,...(draft.companyCodeId?{companyCodeId:draft.companyCodeId}:{}),proposedPayload:draft.proposedPayload},idempotencyKey:key}),
  list:(operatingOrganizationId:string,status?:RequestStatus,signal?:AbortSignal)=>http.request(listRequests,{query:{operatingOrganizationId,status,limit:100},signal}),
  view:(requestId:string,signal?:AbortSignal)=>http.request(readView,{params:{requestId},signal}),
  patch:(requestId:string,body:Parameters<typeof patch>[0],key=commandKey("save"))=>http.request(patchRequest,{params:{requestId},body,idempotencyKey:key}),
  validate:(requestId:string,expectedVersion:number,key=commandKey("validate"))=>http.request(validateRequest,{params:{requestId},body:{expectedVersion},idempotencyKey:key}),
  submit:(requestId:string,expectedVersion:number,key=commandKey("submit"))=>http.request(submitRequest,{params:{requestId},body:{expectedVersion,idempotencyKey:key},idempotencyKey:key}),
  decide:(requestId:string,input:Omit<Parameters<typeof decide>[0],"idempotencyKey">,key=commandKey(input.decision))=>http.request(decideRequest,{params:{requestId},body:{...input,idempotencyKey:key},idempotencyKey:key}),
  apply:(requestId:string,expectedVersion:number,key=commandKey("apply"))=>http.request(applyRequest,{params:{requestId},body:{expectedVersion,idempotencyKey:key},idempotencyKey:key}),
  aggregate:(businessPartnerId:string,operatingOrganizationId:string,signal?:AbortSignal)=>http.request(readAggregate,{params:{businessPartnerId},query:{operatingOrganizationId},signal}),
  eligibility:(businessPartnerId:string,operatingOrganizationId:string,operationCode="purchasing",businessDate=new Date().toISOString().slice(0,10),signal?:AbortSignal,companyCodeId?:string,role:"supplier"|"customer"="supplier")=>http.request(readEligibility,{params:{businessPartnerId},query:{role,operatingOrganizationId,...(companyCodeId?{companyCodeId}:{}),operationCode,businessDate},signal}),
  customerCreditReviews:(businessPartnerId:string,operatingOrganizationId:string,companyCodeId:string,signal?:AbortSignal)=>http.request(listCustomerCredit,{params:{businessPartnerId},query:{operatingOrganizationId,companyCodeId},signal}),
  createCustomerCredit:(businessPartnerId:string,body:Readonly<Record<string,unknown>>,key=commandKey("customer-credit"))=>http.request(createCustomerCredit,{params:{businessPartnerId},body:{...body,idempotencyKey:key},idempotencyKey:key}),
  decideCustomerCredit:(reviewId:string,body:Readonly<Record<string,unknown>>,key=commandKey("customer-credit-decision"))=>http.request(decideCustomerCredit,{params:{reviewId},body:{...body,idempotencyKey:key},idempotencyKey:key}),
  transitionCustomer:(businessPartnerId:string,body:Readonly<Record<string,unknown>>,key=commandKey("customer-lifecycle"))=>http.request(customerLifecycle,{params:{businessPartnerId},body:{...body,idempotencyKey:key},idempotencyKey:key}),
});}
type PatchBody={expectedVersion:number;proposedPayload:Readonly<Record<string,unknown>>;operatingOrganizationId?:string;companyCodeId?:string|null};
type DecisionBody={workflowRequestId:string;workItemId:string;expectedRequestVersion:number;expectedWorkItemVersion:number;decision:"return"|"reject"|"approve";reason:string;idempotencyKey:string};
function patch(value:PatchBody):PatchBody{return value;} function decide(value:DecisionBody):DecisionBody{return value;}
export function commandKey(action:string):string{return `bp-ui-${action}-${globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`}`;}
function parseMutation(value:unknown){const body=record(value);return Object.freeze({request:parseRequest(body.request),replayed:Boolean(body.replayed)});}
function parseList(value:unknown):readonly PartnerRequest[]{if(!Array.isArray(value))throw new TypeError("Business Partner request list must be an array");return Object.freeze(value.map(parseRequest));}
function parseView(value:unknown):RequestView{const body=record(value),workflow=body.workflow===undefined?undefined:record(body.workflow);return Object.freeze({request:parseRequest(body.request),validationFindings:Array.isArray(body.validationFindings)?Object.freeze(body.validationFindings.map(parseFinding)):[],...(workflow?{workflow:{requestId:text(workflow.requestId),stageId:text(workflow.stageId),workItemId:text(workflow.workItemId),workItemVersion:positive(workflow.workItemVersion),workItemStatus:text(workflow.workItemStatus),definition:record(workflow.definition) as unknown as RequestView["workflow"] extends infer W?W extends {definition:infer D}?D:never:never}}:{})});}
function parseRequest(value:unknown):PartnerRequest{const body=record(value);return body as unknown as PartnerRequest;}
function parseFinding(value:unknown):ValidationFinding{return record(value) as unknown as ValidationFinding;}
function parseAggregate(value:unknown):PartnerAggregate{return record(value) as unknown as PartnerAggregate;}
function parseEligibility(value:unknown):PartnerEligibility{return record(value) as unknown as PartnerEligibility;}
function record(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError("API response must be an object");return value as Record<string,unknown>;}
function text(value:unknown):string{if(typeof value!=="string"||!value.trim())throw new TypeError("API response string is required");return value;}
function positive(value:unknown):number{if(!Number.isSafeInteger(value)||Number(value)<1)throw new TypeError("API response version is invalid");return Number(value);}
