"use client";
import { useApiClient, useToasts } from "@athyper/platform-shell-app-foundation";
import { PageSurface } from "@athyper/platform-surface-kit";
import { Button, Card, Input, Label } from "@athyper/platform-ui";
import { useNeonWorkContext } from "@athyper/product-neon-shell";
import { useMemo, useState, type FormEvent } from "react";
import { createBusinessPartnerClient } from "./client";

export function NewCustomerRequest(){const http=useApiClient(),api=useMemo(()=>createBusinessPartnerClient(http),[http]),work=useNeonWorkContext(),toast=useToasts(),[organizationId,setOrganizationId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string>();const companyCodeId=work.selection.mode==="company"?work.selection.companyCodeId:undefined;async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError(undefined);const data=new FormData(event.currentTarget);try{const legalName=value(data,"legalName"),result=await api.onboardCustomer({operatingOrganizationId:organizationId,...(companyCodeId?{companyCodeId}:{}),proposedPayload:{name:legalName,legalName,displayName:optional(data,"displayName")??legalName,partnerCategory:"organization",ownershipClass:"external",customerType:"corporate",registrationCountryCode:value(data,"registrationCountryCode").toUpperCase()}});toast.push({tone:"success",title:"Customer request created",detail:result.request.requestNo});window.location.assign(`/mdg/business-partner/requests/${encodeURIComponent(result.request.id)}`);}catch(cause){setError(cause instanceof Error?cause.message:"Unexpected customer request error");setBusy(false);}}return <PageSurface title="New customer onboarding request" description="Register an organization customer in an authorized sales scope." actions={<a className="a-button a-button--secondary" href="/mdg/business-partner/requests">Cancel</a>}><form className="bp-form" onSubmit={submit}><Card className="bp-section"><h2>Sales scope</h2><div className="bp-grid"><div className="bp-field"><Label htmlFor="customer-org">Operating organization ID</Label><Input id="customer-org" value={organizationId} onChange={event=>setOrganizationId(event.currentTarget.value)} required pattern="[0-9a-fA-F-]{36}"/></div><div className="bp-field"><Label htmlFor="customer-country">Registration country</Label><Input id="customer-country" name="registrationCountryCode" required minLength={2} maxLength={2}/></div><div className="bp-field"><Label htmlFor="customer-name">Legal name</Label><Input id="customer-name" name="legalName" required maxLength={255}/></div><div className="bp-field"><Label htmlFor="customer-display">Display name</Label><Input id="customer-display" name="displayName" maxLength={255}/></div></div></Card>{error?<div className="bp-error" role="alert">{error}</div>:null}<Button type="submit" loading={busy} disabled={!organizationId}>Create customer draft</Button></form></PageSurface>;}
function value(data:FormData,name:string):string{const result=data.get(name);if(typeof result!=="string"||!result.trim())throw new Error(`${name} is required`);return result.trim();}
function optional(data:FormData,name:string):string|undefined{const result=data.get(name);return typeof result==="string"&&result.trim()?result.trim():undefined;}
