-- GENERATED by compile-authority.ts. DO NOT EDIT.
-- Deterministic, idempotent neon authority for the local clean-reset profile.
DO $canonical_authority$
DECLARE
  v_tid uuid;
  v_scope_id uuid;
  v_system uuid := '00000000-0000-0000-0000-000000000000'::uuid;
BEGIN
  v_tid := nullif(trim(current_setting('app.seed_tenant_id', true)), '')::uuid;
  IF v_tid IS NULL THEN
    RAISE EXCEPTION '[canonical-neon-authority] tenant not found';
  END IF;

  INSERT INTO master.auth_scope_target (
    id, tenant_id, plane_code, scope_kind, tenant_scope_id, scope_key,
    display_name, status, metadata, created_by
  )
  VALUES (
    md5(v_tid::text || ':auth-scope:neon:tenant')::uuid,
    v_tid, 'neon', 'tenant', v_tid, v_tid::text,
    'neon tenant scope', 'active',
    '{"seed_owner":"canonical-authorization-v2"}'::jsonb, v_system
  )
  ON CONFLICT (tenant_id, plane_code, scope_kind, scope_key) DO UPDATE
    SET status = EXCLUDED.status,
        display_name = EXCLUDED.display_name,
        metadata = EXCLUDED.metadata;

  SELECT id INTO STRICT v_scope_id
  FROM master.auth_scope_target
  WHERE tenant_id = v_tid AND plane_code = 'neon'
    AND scope_kind = 'tenant' AND scope_key = v_tid::text;

  INSERT INTO master.auth_role (
    id, tenant_id, plane_code, code, name, description, role_kind,
    status, source_type, source_ref, metadata, created_by
  )
  SELECT md5(v_tid::text || ':auth-role:neon:' || role_seed.code)::uuid,
         v_tid, 'neon', role_seed.code, role_seed.name,
         'Canonical direct-permission role', 'system', 'active',
         'seed', 'wave3.neon-admin.authority.v1',
         '{"seed_owner":"canonical-authorization-v2"}'::jsonb, v_system
  FROM (VALUES
      ('neon.access.viewer', 'Neon viewer access'),
      ('neon.access.reporter', 'Neon reporter access'),
      ('neon.access.requester', 'Neon requester access'),
      ('neon.access.agent', 'Neon agent access'),
      ('neon.access.manager', 'Neon manager access'),
      ('neon.access.owner', 'Neon owner access'),
      ('neon.access.admin', 'Neon admin access')
  ) AS role_seed(code, name)
  ON CONFLICT (tenant_id, plane_code, code) DO UPDATE
    SET name = EXCLUDED.name,
        status = EXCLUDED.status,
        source_ref = EXCLUDED.source_ref,
        metadata = EXCLUDED.metadata;

  INSERT INTO master.auth_role_permission (
    id, tenant_id, plane_code, role_id, permission_id, status,
    metadata, created_by
  )
  SELECT md5(role_row.id::text || ':' || permission_seed.permission_id::text)::uuid,
         v_tid, 'neon', role_row.id,
         permission_seed.permission_id, 'active',
         '{"seed_owner":"canonical-authorization-v2"}'::jsonb, v_system
  FROM (VALUES

  ) AS permission_seed(role_code, permission_id)
  JOIN master.auth_role role_row
    ON role_row.tenant_id = v_tid
   AND role_row.plane_code = 'neon'
   AND role_row.code = permission_seed.role_code
  ON CONFLICT (tenant_id, plane_code, role_id, permission_id) DO UPDATE
    SET status = EXCLUDED.status,
        metadata = EXCLUDED.metadata;

  INSERT INTO master.auth_group (
    id, tenant_id, plane_code, code, name, description, status,
    is_system, source_type, source_ref, metadata, created_by
  )
  SELECT md5(v_tid::text || ':auth-group:neon:' || group_seed.code)::uuid,
         v_tid, 'neon', group_seed.code, group_seed.code,
         'Canonical authorization group', 'active', true, 'seed',
         'wave3.neon-admin.authority.v1',
         '{"seed_owner":"canonical-authorization-v2"}'::jsonb, v_system
  FROM (VALUES
      ('neon.access.viewer', 'neon.access.viewer'),
      ('neon.access.reporter', 'neon.access.reporter'),
      ('neon.access.requester', 'neon.access.requester'),
      ('neon.access.agent', 'neon.access.agent'),
      ('neon.access.manager', 'neon.access.manager'),
      ('neon.access.owner', 'neon.access.owner'),
      ('neon.access.admin', 'neon.access.admin'),
      ('neon.access.quarantine', NULL::text)
  ) AS group_seed(code, role_code)
  ON CONFLICT (tenant_id, plane_code, code) DO UPDATE
    SET status = EXCLUDED.status,
        source_ref = EXCLUDED.source_ref,
        metadata = EXCLUDED.metadata;

  INSERT INTO master.auth_group_role (
    id, tenant_id, plane_code, group_id, role_id, scope_target_id,
    status, source_type, source_ref, metadata, created_by
  )
  SELECT md5(group_row.id::text || ':' || role_row.id::text || ':' || v_scope_id::text)::uuid,
         v_tid, 'neon', group_row.id, role_row.id, v_scope_id,
         'active', 'seed', 'wave3.neon-admin.authority.v1',
         '{"seed_owner":"canonical-authorization-v2"}'::jsonb, v_system
  FROM (VALUES
      ('neon.access.viewer', 'neon.access.viewer'),
      ('neon.access.reporter', 'neon.access.reporter'),
      ('neon.access.requester', 'neon.access.requester'),
      ('neon.access.agent', 'neon.access.agent'),
      ('neon.access.manager', 'neon.access.manager'),
      ('neon.access.owner', 'neon.access.owner'),
      ('neon.access.admin', 'neon.access.admin'),
      ('neon.access.quarantine', NULL::text)
  ) AS group_seed(code, role_code)
  JOIN master.auth_group group_row
    ON group_row.tenant_id = v_tid
   AND group_row.plane_code = 'neon'
   AND group_row.code = group_seed.code
  JOIN master.auth_role role_row
    ON role_row.tenant_id = v_tid
   AND role_row.plane_code = 'neon'
   AND role_row.code = group_seed.role_code
  WHERE group_seed.role_code IS NOT NULL
  ON CONFLICT (tenant_id, plane_code, group_id, role_id, scope_target_id) DO UPDATE
    SET status = EXCLUDED.status,
        source_ref = EXCLUDED.source_ref,
        metadata = EXCLUDED.metadata;

  INSERT INTO master.auth_plane_membership (
    id, tenant_id, plane_code, principal_id, status, source_type,
    source_ref, metadata, created_by
  )
  SELECT md5(principal.id::text || ':auth-plane:neon')::uuid,
         v_tid, 'neon', principal.id, 'active', 'seed',
         'wave3.neon-admin.authority.v1',
         '{"seed_owner":"canonical-authorization-v2"}'::jsonb, v_system
  FROM master.principal principal
  WHERE principal.tenant_id = v_tid
    AND principal.status = 'active'
    AND NOT principal.is_locked
    
  ON CONFLICT (tenant_id, plane_code, principal_id) DO UPDATE
    SET status = EXCLUDED.status,
        source_ref = EXCLUDED.source_ref,
        metadata = EXCLUDED.metadata;

  INSERT INTO master.auth_group_member (
    id, tenant_id, plane_code, group_id, principal_id, status,
    source_type, source_ref, metadata, created_by
  )
  SELECT md5(group_row.id::text || ':' || principal.id::text)::uuid,
         v_tid, 'neon', group_row.id, principal.id, 'active',
         'seed', 'wave3.neon-admin.authority.v1',
         '{"seed_owner":"canonical-authorization-v2"}'::jsonb, v_system
  FROM master.principal principal
  JOIN master.auth_group group_row
    ON group_row.tenant_id = v_tid
   AND group_row.plane_code = 'neon'
   AND group_row.code = CASE
             WHEN regexp_replace(principal.code, '^.*\.', '') IN
                  ('viewer', 'reporter', 'requester', 'agent', 'manager', 'owner', 'admin')
               THEN 'neon.access.' || regexp_replace(principal.code, '^.*\.', '')
             ELSE 'neon.access.quarantine'
           END
  WHERE principal.tenant_id = v_tid
    AND principal.status = 'active'
    AND NOT principal.is_locked
    
  ON CONFLICT (tenant_id, plane_code, group_id, principal_id) DO UPDATE
    SET status = EXCLUDED.status,
        source_ref = EXCLUDED.source_ref,
        metadata = EXCLUDED.metadata;
END
$canonical_authority$;
