"use client";
import { useEffect, useState, type FormEvent } from "react";
import type { EntityDetailDescriptorV1, EntityFormDescriptorV1, EntityRecordV1, EntitySurfaceFieldV1 } from "@athyper/contract-platform-entity-runtime";
import { entityDescriptorClient } from "@athyper/platform-entity-descriptor-client";
import { PageFrame, PageHeader } from "@athyper/platform-shell";
import { useApiClient } from "@athyper/platform-shell-app-foundation";
import { Button, Card, Checkbox, Input, Label, Select } from "@athyper/platform-ui";

export function EntityFormRuntime({ entityCode, recordId, onCommitted }: { readonly entityCode: string; readonly recordId?: string; readonly onCommitted?: (recordId: string) => void }) {
  const client = useApiClient(), mode = recordId ? "edit" : "create";
  const [descriptor, setDescriptor] = useState<EntityFormDescriptorV1>(), [record, setRecord] = useState<EntityRecordV1>(), [values, setValues] = useState<Record<string, unknown>>({}), [status, setStatus] = useState("Loading published metadata…"), [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; setStatus("Loading published metadata…"); Promise.all([entityDescriptorClient.form(client, entityCode, mode), recordId ? entityDescriptorClient.record(client, entityCode, recordId) : Promise.resolve(undefined)]).then(([nextDescriptor, nextRecord]) => { if (!active) return; setDescriptor(nextDescriptor); setRecord(nextRecord); setValues(nextRecord ? Object.fromEntries(nextDescriptor.fields.map((field) => [field.key, nextRecord.values[field.key] ?? ""])) : {}); setStatus(""); }).catch((error) => active && setStatus(safeError(error))); return () => { active = false; }; }, [client, entityCode, mode, recordId]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!descriptor) return; setSaving(true); setStatus(""); try { const input = Object.fromEntries(descriptor.fields.filter((field) => !field.readOnly).flatMap((field) => values[field.key] === "" && !field.required ? [] : [[field.key, normalize(values[field.key], field)]])); const key = `entity-${mode}-${crypto.randomUUID()}`; const receipt = recordId ? await entityDescriptorClient.patch(client, entityCode, recordId, input, record?.version ?? 0, key) : await entityDescriptorClient.create(client, entityCode, input, key); setStatus(`${descriptor.entity.label} saved.`); onCommitted?.(receipt.recordId); } catch (error) { setStatus(safeError(error)); } finally { setSaving(false); } };
  if (!descriptor) return <PageFrame><PageHeader level="collection" context="Published metadata" title={humanize(entityCode)}/><Card><p role="status">{status}</p></Card></PageFrame>;
  return <PageFrame><PageHeader level="collection" context={`${descriptor.entity.label} · ${mode === "create" ? "Create" : "Edit"}`} title={descriptor.title} description={descriptor.description} metadata={<span>Release {descriptor.revision.release}</span>}/><form onSubmit={submit}><Card>{descriptor.fields.map((field) => <Field key={field.key} field={field} value={values[field.key]} onChange={(value) => setValues((current) => ({ ...current, [field.key]: value }))}/>)}</Card><div><Button type="submit" loading={saving}>{descriptor.submit.label}</Button></div><p role="status">{status}</p></form></PageFrame>;
}

export function EntityDetailRuntime({ entityCode, recordId, editHref }: { readonly entityCode: string; readonly recordId: string; readonly editHref?: string }) {
  const client = useApiClient(), [descriptor, setDescriptor] = useState<EntityDetailDescriptorV1>(), [record, setRecord] = useState<EntityRecordV1>(), [status, setStatus] = useState("Loading governed record…");
  useEffect(() => { let active = true; Promise.all([entityDescriptorClient.detail(client, entityCode), entityDescriptorClient.record(client, entityCode, recordId)]).then(([nextDescriptor, nextRecord]) => { if (!active) return; setDescriptor(nextDescriptor); setRecord(nextRecord); setStatus(""); }).catch((error) => active && setStatus(safeError(error))); return () => { active = false; }; }, [client, entityCode, recordId]);
  if (!descriptor || !record) return <PageFrame><PageHeader level="collection" context="Published metadata" title={humanize(entityCode)}/><Card><p role="status">{status}</p></Card></PageFrame>;
  return <PageFrame><PageHeader level="collection" context={`${descriptor.entity.label} · Detail`} title={String(record.values[descriptor.titleField] ?? record.id)} metadata={<><span>Release {descriptor.revision.release}</span>{record.version !== undefined ? <span>Version {record.version}</span> : null}</>} actions={editHref && descriptor.actions.some((action) => action.kind === "edit") ? <a className="a-button a-button--secondary" href={editHref}>Edit</a> : undefined}/><Card><dl>{descriptor.fields.map((field) => <div key={field.key}><dt>{field.label}</dt><dd>{display(record.values[field.key])}</dd></div>)}</dl></Card><p role="status">{status}</p></PageFrame>;
}

function Field({ field, value, onChange }: { readonly field: EntitySurfaceFieldV1; readonly value: unknown; readonly onChange: (value: unknown) => void }) { const id = `entity-field-${field.key}`; if (field.kind === "boolean") return <Label htmlFor={id}><Checkbox id={id} checked={value === true} disabled={field.readOnly} onChange={(event) => onChange(event.currentTarget.checked)}/>{field.label}</Label>; if (field.options?.length) return <Label htmlFor={id}><span>{field.label}</span><Select id={id} value={String(value ?? "")} required={field.required} disabled={field.readOnly} onChange={(event) => onChange(event.currentTarget.value)}><option value="">Select…</option>{field.options.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</Select></Label>; return <Label htmlFor={id}><span>{field.label}</span><Input id={id} value={String(value ?? "")} required={field.required} readOnly={field.readOnly} type={inputType(field.kind)} onChange={(event) => onChange(event.currentTarget.value)}/></Label>; }
function inputType(kind: EntitySurfaceFieldV1["kind"]): "text" | "number" | "date" | "datetime-local" { if (["integer", "decimal", "money"].includes(kind)) return "number"; if (kind === "date") return "date"; if (kind === "datetime") return "datetime-local"; return "text"; }
function normalize(value: unknown, field: EntitySurfaceFieldV1): unknown { if (["integer", "decimal", "money"].includes(field.kind) && typeof value === "string") return Number(value); return value; }
function display(value: unknown): string { if (value === null || value === undefined || value === "") return "—"; if (typeof value === "object") return JSON.stringify(value); return String(value); }
function humanize(value: string): string { return value.replace(/[_.-]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function safeError(error: unknown): string { return error instanceof Error && error.message ? error.message : "The governed entity surface is unavailable."; }
