-- ============================================================================
-- document/01r_tables_people.sql
-- Concept: People Management transactional documents and payroll facts
-- Depends on: document core/workflow tables, master People tables
-- ============================================================================

CREATE TABLE IF NOT EXISTS document.shift_assignment (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL DEFAULT '',
    employee_id uuid NOT NULL,
    shift_type_id uuid NOT NULL,
    work_date date NOT NULL,
    planned_start_at timestamptz NOT NULL,
    planned_end_at timestamptz NOT NULL,
    source_type text NOT NULL DEFAULT 'schedule',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'scheduled',
    is_active boolean GENERATED ALWAYS AS (status IN ('scheduled', 'worked', 'adjusted')) STORED,
    status_changed_at timestamptz,
    status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT shift_assignment_pkey PRIMARY KEY (id),
    CONSTRAINT shift_assignment_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT shift_assignment_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT shift_assignment_employee_date_uq UNIQUE (tenant_id, employee_id, work_date),
    CONSTRAINT shift_assignment_time_chk CHECK (planned_end_at > planned_start_at),
    CONSTRAINT shift_assignment_date_consistency_chk CHECK (planned_start_at::date = work_date),
    CONSTRAINT shift_assignment_status_chk CHECK (status IN ('scheduled', 'worked', 'adjusted', 'cancelled')),
    CONSTRAINT shift_assignment_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT shift_assignment_shift_type_fk FOREIGN KEY (tenant_id, shift_type_id) REFERENCES master.shift_type (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.time_punch (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    employee_id uuid NOT NULL,
    shift_assignment_id uuid,
    punch_at timestamptz NOT NULL,
    punch_type text NOT NULL,
    source_type text NOT NULL DEFAULT 'manual',
    device_ref text,
    geo_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'accepted',
    is_active boolean GENERATED ALWAYS AS (status = 'accepted') STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT time_punch_pkey PRIMARY KEY (id),
    CONSTRAINT time_punch_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT time_punch_type_chk CHECK (punch_type IN ('in', 'out', 'break_start', 'break_end')),
    CONSTRAINT time_punch_source_type_chk CHECK (source_type IN ('manual', 'biometric', 'mobile', 'rfid', 'kiosk', 'system')),
    CONSTRAINT time_punch_status_chk CHECK (status IN ('accepted', 'rejected', 'voided')),
    CONSTRAINT time_punch_json_chk CHECK (jsonb_typeof(geo_payload) = 'object' AND jsonb_typeof(raw_payload) = 'object'),
    CONSTRAINT time_punch_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT time_punch_shift_fk FOREIGN KEY (tenant_id, shift_assignment_id) REFERENCES document.shift_assignment (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.attendance_day (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    employee_id uuid NOT NULL,
    shift_assignment_id uuid,
    attendance_date date NOT NULL,
    scheduled_minutes smallint NOT NULL DEFAULT 0,
    worked_minutes smallint NOT NULL DEFAULT 0,
    paid_minutes smallint NOT NULL DEFAULT 0,
    overtime_minutes smallint NOT NULL DEFAULT 0,
    late_minutes smallint NOT NULL DEFAULT 0,
    early_leave_minutes smallint NOT NULL DEFAULT 0,
    absence_minutes smallint NOT NULL DEFAULT 0,
    first_in_at timestamptz,
    last_out_at timestamptz,
    calculation_trace jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'open',
    is_active boolean GENERATED ALWAYS AS (status IN ('open', 'approved', 'locked')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT attendance_day_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_day_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT attendance_day_employee_date_uq UNIQUE (tenant_id, employee_id, attendance_date),
    CONSTRAINT attendance_day_minutes_chk CHECK (
        scheduled_minutes >= 0 AND worked_minutes >= 0 AND paid_minutes >= 0
        AND overtime_minutes >= 0 AND late_minutes >= 0 AND early_leave_minutes >= 0 AND absence_minutes >= 0
    ),
    CONSTRAINT attendance_day_overtime_consistency_chk CHECK (worked_minutes <= scheduled_minutes + overtime_minutes),
    CONSTRAINT attendance_day_status_chk CHECK (status IN ('open', 'approved', 'locked', 'voided')),
    CONSTRAINT attendance_day_trace_chk CHECK (jsonb_typeof(calculation_trace) = 'object'),
    CONSTRAINT attendance_day_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT attendance_day_shift_fk FOREIGN KEY (tenant_id, shift_assignment_id) REFERENCES document.shift_assignment (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.attendance_adjustment_request (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL DEFAULT '',
    employee_id uuid NOT NULL,
    attendance_day_id uuid,
    workflow_request_id uuid,
    requested_by uuid,
    reason_code text,
    reason_text text,
    requested_values jsonb NOT NULL DEFAULT '{}'::jsonb,
    approved_values jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft', 'submitted', 'approved')) STORED,
    status_changed_at timestamptz,
    status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT attendance_adjustment_request_pkey PRIMARY KEY (id),
    CONSTRAINT attendance_adjustment_request_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT attendance_adjustment_request_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT attendance_adjustment_request_json_chk CHECK (
        jsonb_typeof(requested_values) = 'object' AND jsonb_typeof(approved_values) = 'object'
    ),
    CONSTRAINT attendance_adjustment_request_status_chk CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'cancelled')),
    CONSTRAINT attendance_adjustment_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT attendance_adjustment_day_fk FOREIGN KEY (tenant_id, attendance_day_id) REFERENCES document.attendance_day (tenant_id, id),
    CONSTRAINT attendance_adjustment_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.leave_request (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL DEFAULT '',
    employee_id uuid NOT NULL,
    leave_type_id uuid NOT NULL,
    leave_plan_id uuid,
    workflow_request_id uuid,
    start_date date NOT NULL,
    end_date date NOT NULL,
    start_half text,
    end_half text,
    requested_quantity numeric(12,4) NOT NULL,
    approved_quantity numeric(12,4),
    reason text,
    attachment_required boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft', 'submitted', 'approved')) STORED,
    status_changed_at timestamptz,
    status_changed_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT leave_request_pkey PRIMARY KEY (id),
    CONSTRAINT leave_request_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT leave_request_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT leave_request_dates_chk CHECK (end_date >= start_date),
    CONSTRAINT leave_request_quantity_chk CHECK (requested_quantity > 0 AND (approved_quantity IS NULL OR approved_quantity >= 0)),
    CONSTRAINT leave_request_half_chk CHECK (
        (start_half IS NULL OR start_half IN ('first', 'second'))
        AND (end_half IS NULL OR end_half IN ('first', 'second'))
    ),
    CONSTRAINT leave_request_status_chk CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'cancelled', 'withdrawn')),
    CONSTRAINT leave_request_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT leave_request_type_fk FOREIGN KEY (tenant_id, leave_type_id) REFERENCES master.leave_type (tenant_id, id),
    CONSTRAINT leave_request_plan_fk FOREIGN KEY (tenant_id, leave_plan_id) REFERENCES master.leave_plan (tenant_id, id),
    CONSTRAINT leave_request_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.leave_balance_entry (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    employee_id uuid NOT NULL,
    leave_plan_id uuid,
    leave_type_id uuid NOT NULL,
    entry_date date NOT NULL,
    period_start date,
    period_end date,
    quantity_delta numeric(12,4) NOT NULL,
    balance_after numeric(12,4),
    source_doc_type text NOT NULL,
    source_doc_id uuid,
    description text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT leave_balance_entry_pkey PRIMARY KEY (id),
    CONSTRAINT leave_balance_entry_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT leave_balance_entry_period_chk CHECK (period_end IS NULL OR period_start IS NULL OR period_end >= period_start),
    CONSTRAINT leave_balance_entry_source_chk CHECK (btrim(source_doc_type) <> ''),
    CONSTRAINT leave_balance_entry_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT leave_balance_entry_plan_fk FOREIGN KEY (tenant_id, leave_plan_id) REFERENCES master.leave_plan (tenant_id, id),
    CONSTRAINT leave_balance_entry_type_fk FOREIGN KEY (tenant_id, leave_type_id) REFERENCES master.leave_type (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.compensation_assignment (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL DEFAULT '',
    employee_id uuid NOT NULL,
    employment_id uuid,
    pay_group_id uuid NOT NULL,
    pay_structure_id uuid,
    currency_code char(3) NOT NULL,
    base_amount numeric(18,4) NOT NULL DEFAULT 0,
    annualized_amount numeric(18,4),
    effective_from date NOT NULL,
    effective_until date,
    status text NOT NULL DEFAULT 'active',
    is_active boolean GENERATED ALWAYS AS (status = 'active') STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT compensation_assignment_pkey PRIMARY KEY (id),
    CONSTRAINT compensation_assignment_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT compensation_assignment_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT compensation_assignment_dates_chk CHECK (effective_until IS NULL OR effective_until >= effective_from),
    CONSTRAINT compensation_assignment_amount_chk CHECK (base_amount >= 0 AND (annualized_amount IS NULL OR annualized_amount >= 0)),
    CONSTRAINT compensation_assignment_currency_chk CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT compensation_assignment_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT compensation_assignment_employment_fk FOREIGN KEY (tenant_id, employment_id) REFERENCES master.employment (tenant_id, id),
    CONSTRAINT compensation_assignment_group_fk FOREIGN KEY (tenant_id, pay_group_id) REFERENCES master.pay_group (tenant_id, id),
    CONSTRAINT compensation_assignment_structure_fk FOREIGN KEY (tenant_id, pay_structure_id) REFERENCES master.pay_structure (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.compensation_change (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL DEFAULT '',
    employee_id uuid NOT NULL,
    compensation_assignment_id uuid,
    workflow_request_id uuid,
    change_reason text,
    effective_date date NOT NULL,
    old_values jsonb NOT NULL DEFAULT '{}'::jsonb,
    new_values jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft', 'submitted', 'approved')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT compensation_change_pkey PRIMARY KEY (id),
    CONSTRAINT compensation_change_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT compensation_change_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT compensation_change_json_chk CHECK (jsonb_typeof(old_values) = 'object' AND jsonb_typeof(new_values) = 'object'),
    CONSTRAINT compensation_change_status_chk CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'cancelled')),
    CONSTRAINT compensation_change_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT compensation_change_assignment_fk FOREIGN KEY (tenant_id, compensation_assignment_id) REFERENCES document.compensation_assignment (tenant_id, id),
    CONSTRAINT compensation_change_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.payroll_period (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    pay_group_id uuid NOT NULL,
    period_year smallint NOT NULL,
    period_number smallint NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    pay_date date NOT NULL,
    status text NOT NULL DEFAULT 'open',
    is_active boolean GENERATED ALWAYS AS (status IN ('open', 'processing')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT payroll_period_pkey PRIMARY KEY (id),
    CONSTRAINT payroll_period_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT payroll_period_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT payroll_period_group_period_uq UNIQUE (tenant_id, pay_group_id, period_year, period_number),
    CONSTRAINT payroll_period_number_chk CHECK (period_number BETWEEN 1 AND 53),
    CONSTRAINT payroll_period_dates_chk CHECK (period_end >= period_start),
    CONSTRAINT payroll_period_status_chk CHECK (status IN ('open', 'processing', 'closed', 'locked')),
    CONSTRAINT payroll_period_group_fk FOREIGN KEY (tenant_id, pay_group_id) REFERENCES master.pay_group (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.payroll_run (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    payroll_period_id uuid NOT NULL,
    run_type text NOT NULL DEFAULT 'regular',
    run_no smallint NOT NULL DEFAULT 1,
    calculation_started_at timestamptz,
    calculation_completed_at timestamptz,
    approved_at timestamptz,
    approved_by uuid,
    posted_journal_entry_id uuid,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft', 'calculated', 'approved', 'posted')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT payroll_run_pkey PRIMARY KEY (id),
    CONSTRAINT payroll_run_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT payroll_run_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT payroll_run_period_no_uq UNIQUE (tenant_id, payroll_period_id, run_no),
    CONSTRAINT payroll_run_journal_uq UNIQUE (tenant_id, posted_journal_entry_id),
    CONSTRAINT payroll_run_no_chk CHECK (run_no >= 1),
    CONSTRAINT payroll_run_type_chk CHECK (run_type IN ('regular', 'offcycle', 'correction', 'final')),
    CONSTRAINT payroll_run_status_chk CHECK (status IN ('draft', 'calculating', 'calculated', 'approved', 'posted', 'cancelled', 'reversed')),
    CONSTRAINT payroll_run_period_fk FOREIGN KEY (tenant_id, payroll_period_id) REFERENCES document.payroll_period (tenant_id, id),
    CONSTRAINT payroll_run_journal_fk FOREIGN KEY (tenant_id, posted_journal_entry_id) REFERENCES document.journal_entry (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.payroll_run_employee (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    payroll_run_id uuid NOT NULL,
    employee_id uuid NOT NULL,
    inclusion_reason text,
    exclusion_reason text,
    status text NOT NULL DEFAULT 'included',
    is_active boolean GENERATED ALWAYS AS (status IN ('included', 'calculated')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT payroll_run_employee_pkey PRIMARY KEY (id),
    CONSTRAINT payroll_run_employee_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT payroll_run_employee_uq UNIQUE (tenant_id, payroll_run_id, employee_id),
    CONSTRAINT payroll_run_employee_status_chk CHECK (status IN ('included', 'excluded', 'calculated', 'error')),
    CONSTRAINT payroll_run_employee_run_fk FOREIGN KEY (tenant_id, payroll_run_id)
        REFERENCES document.payroll_run (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT payroll_run_employee_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.payroll_result (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    payroll_run_id uuid NOT NULL,
    payroll_run_employee_id uuid NOT NULL,
    employee_id uuid NOT NULL,
    currency_code char(3) NOT NULL,
    gross_amount numeric(18,4) NOT NULL DEFAULT 0,
    employee_deduction_amount numeric(18,4) NOT NULL DEFAULT 0,
    employer_contribution_amount numeric(18,4) NOT NULL DEFAULT 0,
    net_amount numeric(18,4) NOT NULL DEFAULT 0,
    calculation_trace jsonb NOT NULL DEFAULT '{}'::jsonb,
    render_output_id uuid,
    status text NOT NULL DEFAULT 'calculated',
    is_active boolean GENERATED ALWAYS AS (status IN ('calculated', 'approved', 'posted')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT payroll_result_pkey PRIMARY KEY (id),
    CONSTRAINT payroll_result_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT payroll_result_employee_uq UNIQUE (tenant_id, payroll_run_id, employee_id),
    CONSTRAINT payroll_result_amount_chk CHECK (
        gross_amount >= 0 AND employee_deduction_amount >= 0
        AND employer_contribution_amount >= 0 AND net_amount >= 0
    ),
    CONSTRAINT payroll_result_net_consistency_chk CHECK (
        ABS(net_amount - (gross_amount - employee_deduction_amount)) < 0.005
    ),
    CONSTRAINT payroll_result_currency_chk CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT payroll_result_trace_chk CHECK (jsonb_typeof(calculation_trace) = 'object'),
    CONSTRAINT payroll_result_status_chk CHECK (status IN ('calculated', 'approved', 'posted', 'voided')),
    CONSTRAINT payroll_result_run_fk FOREIGN KEY (tenant_id, payroll_run_id) REFERENCES document.payroll_run (tenant_id, id),
    CONSTRAINT payroll_result_run_employee_fk FOREIGN KEY (tenant_id, payroll_run_employee_id) REFERENCES document.payroll_run_employee (tenant_id, id),
    CONSTRAINT payroll_result_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT payroll_result_render_fk FOREIGN KEY (tenant_id, render_output_id) REFERENCES document.render_output (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.payroll_result_line (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    payroll_result_id uuid NOT NULL,
    line_no smallint NOT NULL,
    pay_component_id uuid NOT NULL,
    component_type text NOT NULL,
    quantity numeric(18,4),
    rate numeric(18,8),
    amount numeric(18,4) NOT NULL,
    currency_code char(3) NOT NULL,
    formula_expression_version_id uuid,
    evaluated_inputs jsonb NOT NULL DEFAULT '{}'::jsonb,
    evaluated_outputs jsonb NOT NULL DEFAULT '{}'::jsonb,
    evaluation_trace jsonb NOT NULL DEFAULT '{}'::jsonb,
    cost_center_id uuid,
    profit_center_id uuid,
    project_id uuid,
    site_id uuid,
    gl_role text,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT payroll_result_line_pkey PRIMARY KEY (id),
    CONSTRAINT payroll_result_line_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT payroll_result_line_no_uq UNIQUE (tenant_id, payroll_result_id, line_no),
    CONSTRAINT payroll_result_line_no_chk CHECK (line_no > 0),
    CONSTRAINT payroll_result_line_amount_chk CHECK (amount >= 0),
    CONSTRAINT payroll_result_line_component_type_chk CHECK (
        component_type IN ('earning', 'deduction', 'employer_contribution', 'statutory', 'memo')
    ),
    CONSTRAINT payroll_result_line_currency_chk CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT payroll_result_line_json_chk CHECK (
        jsonb_typeof(evaluated_inputs) = 'object'
        AND jsonb_typeof(evaluated_outputs) = 'object'
        AND jsonb_typeof(evaluation_trace) = 'object'
    ),
    CONSTRAINT payroll_result_line_result_fk FOREIGN KEY (tenant_id, payroll_result_id)
        REFERENCES document.payroll_result (tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT payroll_result_line_component_fk FOREIGN KEY (tenant_id, pay_component_id) REFERENCES master.pay_component (tenant_id, id),
    CONSTRAINT payroll_result_line_formula_fk FOREIGN KEY (tenant_id, formula_expression_version_id) REFERENCES control.formula_expression_version (tenant_id, id),
    CONSTRAINT payroll_result_line_cost_center_fk FOREIGN KEY (tenant_id, cost_center_id) REFERENCES master.cost_center (tenant_id, id),
    CONSTRAINT payroll_result_line_profit_center_fk FOREIGN KEY (tenant_id, profit_center_id) REFERENCES master.profit_center (tenant_id, id),
    CONSTRAINT payroll_result_line_project_fk FOREIGN KEY (tenant_id, project_id) REFERENCES master.project (tenant_id, id),
    CONSTRAINT payroll_result_line_site_fk FOREIGN KEY (tenant_id, site_id) REFERENCES master.site (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.employee_tax_declaration (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL DEFAULT '',
    employee_id uuid NOT NULL,
    employment_id uuid,
    tax_year smallint NOT NULL,
    country_code char(2) NOT NULL,
    workflow_request_id uuid,
    submitted_at timestamptz,
    approved_at timestamptz,
    approved_by uuid,
    status text NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft', 'submitted', 'approved')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT employee_tax_declaration_pkey PRIMARY KEY (id),
    CONSTRAINT employee_tax_declaration_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT employee_tax_declaration_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT employee_tax_declaration_country_chk CHECK (country_code ~ '^[A-Z]{2}$'),
    CONSTRAINT employee_tax_declaration_status_chk CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'superseded')),
    CONSTRAINT employee_tax_declaration_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT employee_tax_declaration_employment_fk FOREIGN KEY (tenant_id, employment_id) REFERENCES master.employment (tenant_id, id),
    CONSTRAINT employee_tax_declaration_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.employee_tax_declaration_line (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    employee_tax_declaration_id uuid NOT NULL,
    line_no smallint NOT NULL,
    declaration_code text NOT NULL,
    amount numeric(18,4),
    quantity numeric(18,4),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT employee_tax_declaration_line_pkey PRIMARY KEY (id),
    CONSTRAINT employee_tax_declaration_line_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT employee_tax_declaration_line_no_uq UNIQUE (tenant_id, employee_tax_declaration_id, line_no),
    CONSTRAINT employee_tax_declaration_line_payload_chk CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT employee_tax_declaration_line_parent_fk FOREIGN KEY (tenant_id, employee_tax_declaration_id)
        REFERENCES document.employee_tax_declaration (tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS document.hr_case (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    employee_id uuid,
    case_type text NOT NULL DEFAULT 'general',
    priority text NOT NULL DEFAULT 'normal',
    assigned_to uuid,
    opened_at timestamptz NOT NULL DEFAULT now(),
    closed_at timestamptz,
    resolution_summary text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'open',
    is_active boolean GENERATED ALWAYS AS (status IN ('open', 'in_progress', 'pending')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT hr_case_pkey PRIMARY KEY (id),
    CONSTRAINT hr_case_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT hr_case_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT hr_case_type_chk CHECK (case_type IN ('general', 'grievance', 'disciplinary', 'health', 'other')),
    CONSTRAINT hr_case_priority_chk CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    CONSTRAINT hr_case_closed_chk CHECK (closed_at IS NULL OR closed_at >= opened_at),
    CONSTRAINT hr_case_status_chk CHECK (status IN ('open', 'in_progress', 'pending', 'resolved', 'closed', 'cancelled')),
    CONSTRAINT hr_case_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.onboarding_case (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    person_id uuid,
    employee_id uuid,
    target_start_date date,
    checklist jsonb NOT NULL DEFAULT '[]'::jsonb,
    workflow_request_id uuid,
    status text NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft', 'active')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT onboarding_case_pkey PRIMARY KEY (id),
    CONSTRAINT onboarding_case_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT onboarding_case_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT onboarding_case_json_chk CHECK (jsonb_typeof(checklist) = 'array'),
    CONSTRAINT onboarding_case_status_chk CHECK (status IN ('draft', 'active', 'completed', 'cancelled')),
    CONSTRAINT onboarding_case_person_fk FOREIGN KEY (tenant_id, person_id) REFERENCES master.person (tenant_id, id),
    CONSTRAINT onboarding_case_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT onboarding_case_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.offboarding_case (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    employee_id uuid NOT NULL,
    target_exit_date date NOT NULL,
    reason_code text,
    checklist jsonb NOT NULL DEFAULT '[]'::jsonb,
    workflow_request_id uuid,
    status text NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft', 'active')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT offboarding_case_pkey PRIMARY KEY (id),
    CONSTRAINT offboarding_case_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT offboarding_case_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT offboarding_case_json_chk CHECK (jsonb_typeof(checklist) = 'array'),
    CONSTRAINT offboarding_case_status_chk CHECK (status IN ('draft', 'active', 'completed', 'cancelled')),
    CONSTRAINT offboarding_case_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT offboarding_case_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.policy_acknowledgment (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    employee_id uuid NOT NULL,
    policy_code text NOT NULL,
    policy_version text NOT NULL,
    acknowledged_at timestamptz NOT NULL DEFAULT now(),
    acknowledgment_channel text NOT NULL DEFAULT 'self_service',
    evidence_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT policy_acknowledgment_pkey PRIMARY KEY (id),
    CONSTRAINT policy_acknowledgment_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT policy_acknowledgment_policy_uq UNIQUE (tenant_id, employee_id, policy_code, policy_version),
    CONSTRAINT policy_acknowledgment_payload_chk CHECK (jsonb_typeof(evidence_payload) = 'object'),
    CONSTRAINT policy_acknowledgment_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS document.people_request (
    id uuid NOT NULL DEFAULT shared.uuidv7(),
    tenant_id uuid NOT NULL,
    code text NOT NULL,
    name text NOT NULL DEFAULT '',
    employee_id uuid NOT NULL,
    request_type text NOT NULL,
    target_entity text,
    target_id uuid,
    workflow_request_id uuid,
    requested_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    approved_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'draft',
    is_active boolean GENERATED ALWAYS AS (status IN ('draft', 'submitted', 'approved')) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL,
    updated_at timestamptz,
    updated_by uuid,
    CONSTRAINT people_request_pkey PRIMARY KEY (id),
    CONSTRAINT people_request_tenant_id_uq UNIQUE (tenant_id, id),
    CONSTRAINT people_request_code_uq UNIQUE (tenant_id, code),
    CONSTRAINT people_request_type_chk CHECK (
        request_type IN ('profile_change', 'bank_update', 'contact_change', 'document_request', 'other')
    ),
    CONSTRAINT people_request_payload_chk CHECK (
        jsonb_typeof(requested_payload) = 'object' AND jsonb_typeof(approved_payload) = 'object'
    ),
    CONSTRAINT people_request_status_chk CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'cancelled')),
    CONSTRAINT people_request_employee_fk FOREIGN KEY (tenant_id, employee_id) REFERENCES master.employee (tenant_id, id),
    CONSTRAINT people_request_workflow_fk FOREIGN KEY (tenant_id, workflow_request_id) REFERENCES document.workflow_request (tenant_id, id)
);
