-- ============================================================================
-- document/01w_ap_p3_asset_refactor.sql
-- Concept: PIL Asset Refactor (HISTORICAL)
--
-- Replaced 2026-06-22 by the two-field model:
--   • lineitem.asset_class_id   (PIL/CL/GRL — what class of asset is being acquired)
--   • accounting_distribution.asset_id   (specific master.asset this split posts against)
--
-- The PIL.asset_class_id column + FK are now declared directly in
-- 01e_tables_invoice.sql and 03_constraints.sql. The previous discriminator
-- (asset_treatment) and target_asset_id are dropped — "is this an asset line?"
-- = (asset_class_id IS NOT NULL); the specific asset binding moves to AD.
-- ============================================================================
