-- ============================================================================
-- document/01x_ad_asset_fields.sql
-- Concept: AD asset frozen fields (HISTORICAL)
--
-- Replaced 2026-06-22 by the two-field model. AD now carries a single
-- asset_id column (declared in 01b_tables_journal.sql, FK in 03_constraints.sql).
-- The previous frozen-field set (is_capex, asset_class_id, asset_posting_target,
-- target_asset_id) is dropped — capex routing is derived at posting time from
-- (AD.asset_id, PIL.asset_class_id, asset_class.capitalization_threshold).
-- ============================================================================
