-- ============================================================================
-- document/01z_ap_h4_improvements.sql
-- Concept: HISTORICAL — content split into proper-phase files per HF2-3
-- Spec: Hardening Sprint H-Fix-2 §HF2-3
--
-- The H4 improvements bundle previously lived in this single 01* file:
--   §A v_ap_settlement_graph
--   §B invoice_match_case rollup function + trigger
--   §C over-allocation guard function + trigger
--   §D BRCL active-uniqueness function + trigger
--   §E payment amount reconciliation function + trigger
--
-- That meant functions, triggers, and views were all created at provisioner
-- phase 40, which conflicts with helper functions like log.trg_prevent_mutation
-- defined at phase 80. The content has been split into:
--
--   05_functions_ap_improvements.sql  — function bodies (phase 80)
--   06_triggers_ap_improvements.sql   — trigger attachments (phase 90)
--   07_views_ap_improvements.sql      — view definitions (phase 100)
--
-- This file is left as a stub for traceability. The CREATE OR REPLACE in the
-- replacement files makes the migration idempotent — running an older clone
-- (with old 01z behavior) followed by the new files leaves the live DB on the
-- corrected definitions.
-- ============================================================================

-- (Intentionally empty.)
