-- ============================================================================
-- snapshot/00_bootstrap.sql
-- Concept: Snapshot Bootstrap — no pre-table functions required for this schema
-- Depends on: 01_schemas/001_schemas.sql
-- Note: No bootstrap functions required for the snapshot schema.
-- ============================================================================
