import { atlasAdminSchemas, type AtlasExperienceDefinition } from "@athyper/server-contract-ai";
import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import { HttpError, defineRouteContract, registerContractRoute, type RuntimeSchema } from "@athyper/server-runtime-http";
import type { Application, Request, RequestHandler, Response } from "express";
import type { AtlasExperienceConfigurationService } from "./experience-configuration.js";

const objectSchema={type:"object"} as const;
export function registerAtlasExperienceRoutes(app:Application,options:{authenticate:RequestHandler;readContext:(response:Response)=>VerifiedRequestContext;authorizeAdmin:(context:VerifiedRequestContext)=>Promise<boolean>;experience:AtlasExperienceConfigurationService}):void{
  registerContractRoute(app,contract("get","/api/atlas/experience","atlas.experience.get","Read the permission-filtered Atlas experience"),options.authenticate,async(request,response,next)=>{try{response.json(await options.experience.resolve(options.readContext(response),queryScope(request)));}catch(error){next(error);}});
  const admin=(work:(request:Request,context:VerifiedRequestContext)=>Promise<unknown>):RequestHandler=>async(request,response,next)=>{try{const context=options.readContext(response);if(!await options.authorizeAdmin(context)){response.status(403).json({code:"PERMISSION_DENIED"});return;}response.json(await work(request,context));}catch(error){next(error);}};
  registerContractRoute(app,contract("get","/api/admin/atlas/experience/draft","atlas.admin.experience.draft","Read the Studio Atlas experience draft",undefined,true),options.authenticate,admin((request,context)=>options.experience.draft(context,queryScope(request))));
  registerContractRoute(app,contract("put","/api/admin/atlas/experience/draft","atlas.admin.experience.saveDraft","Save a versioned Studio Atlas experience draft",atlasAdminSchemas.experienceDefinition,true),options.authenticate,admin((request,context)=>{const body=object(request.body);return options.experience.saveDraft(context,definition(body),body.expectedRevision===undefined?undefined:positiveInteger(body.expectedRevision));}));
  registerContractRoute(app,contract("post","/api/admin/atlas/experience/publish","atlas.admin.experience.publish","Publish the current Studio Atlas experience draft",atlasAdminSchemas.experiencePublish,true),options.authenticate,admin((request,context)=>{const body=object(request.body);return options.experience.publish(context,text(body.scope,"scope"),positiveInteger(body.expectedRevision));}));
}
function contract(method:"get"|"put"|"post",path:string,id:string,summary:string,body?:RuntimeSchema,admin=false){return defineRouteContract({method,path,operationId:id,summary,tags:[admin?"Atlas Administration":"Atlas"],authenticated:true,...(admin?{permission:"studio.platform.catalog.manage"}:{}),...(body?{request:{body}}:{}),responses:{200:{description:"Atlas experience response",body:method==="get"?{type:["object","null"]}:objectSchema},400:{description:"Invalid request"},403:{description:"Permission denied"},409:{description:"Revision conflict"}}});}
function queryScope(request:Request):string{const scope=request.query.scope;if(scope===undefined)return "home";if(typeof scope!=="string"||!/^[a-z][a-z0-9_.:-]{0,127}$/.test(scope.trim()))throw new HttpError(400,"ATLAS_EXPERIENCE_INVALID_SCOPE","scope is invalid");return scope.trim();}
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value))throw new TypeError("JSON object required.");return value as Record<string,unknown>;}
function definition(body:Record<string,unknown>):AtlasExperienceDefinition{return{schema:body.schema as "atlas-experience-definition/1",scope:body.scope as string,widgets:body.widgets as never,searchSources:body.searchSources as never,prompts:body.prompts as never,agents:body.agents as never};}
function positiveInteger(value:unknown):number{const result=Number(value);if(!Number.isSafeInteger(result)||result<1)throw new TypeError("A positive revision is required.");return result;}
function text(value:unknown,label:string):string{if(typeof value!=="string"||!value.trim()||value.length>128)throw new TypeError(`${label} is invalid.`);return value.trim();}
