import { atlasAdminSchemas, type AtlasCredentialAdministration, type AtlasMonitoringDashboard, type AtlasPolicyAdministration, type AtlasProviderId, type AtlasTenantQuotaManager } from "@athyper/server-contract-ai";
import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import { defineRouteContract, registerContractRoute, type RuntimeSchema } from "@athyper/server-runtime-http";
import type { Application, Request, RequestHandler, Response } from "express";
import { AtlasServiceError } from "./errors.js";
import { handleAtlasError } from "./atlas-routes.js";
import { AtlasKnowledgeService } from "./knowledge.js";

export function registerAtlasAdminRoutes(app:Application,options:{authenticate:RequestHandler;readContext:(response:Response)=>VerifiedRequestContext;authorize:(context:VerifiedRequestContext)=>Promise<boolean>;credentials:AtlasCredentialAdministration;knowledge:AtlasKnowledgeService;policies:AtlasPolicyAdministration;quotas:AtlasTenantQuotaManager;dashboards:AtlasMonitoringDashboard}):void{
  const route=(work:(body:Record<string,unknown>,context:VerifiedRequestContext,request:Request)=>Promise<unknown>):RequestHandler=>async(req,res,next)=>{try{const context=options.readContext(res);if(!await options.authorize(context)){res.status(403).json({code:"PERMISSION_DENIED"});return;}res.json(await work(req.body===undefined?{}:object(req.body),context,req));}catch(error){handleAtlasError(error,res,next);}};
  registerContractRoute(app,contract("put","/api/admin/atlas/credentials/:providerId","credentials.put","Create or rotate an Atlas provider credential",atlasAdminSchemas.credential),options.authenticate,route((body,context,request)=>options.credentials.createOrRotate({context,providerId:provider(String(request.params.providerId)),secret:text(body.secret,"secret",32_768)})));
  registerContractRoute(app,contract("delete","/api/admin/atlas/credentials/:providerId","credentials.revoke","Revoke an Atlas provider credential"),options.authenticate,async(req,res,next)=>{try{const context=options.readContext(res);if(!await options.authorize(context)){res.status(403).json({code:"PERMISSION_DENIED"});return;}res.json(await options.credentials.revoke({context,providerId:provider(String(req.params.providerId))}));}catch(error){handleAtlasError(error,res,next);}});
  registerContractRoute(app,contract("post","/api/admin/atlas/knowledge/sources","knowledge.sources.register","Register an Atlas knowledge source",atlasAdminSchemas.knowledgeSource),options.authenticate,route((body,context)=>options.knowledge.registerSource({context,sourceKind:text(body.sourceKind,"sourceKind",64),sourceId:text(body.sourceId,"sourceId",256),permissionCode:text(body.permissionCode,"permissionCode",128),...(typeof body.entityCode==="string"?{entityCode:text(body.entityCode,"entityCode",128)}:{})})));
  registerContractRoute(app,contract("post","/api/admin/atlas/knowledge/sources/retract","knowledge.sources.retract","Retract an Atlas knowledge source",atlasAdminSchemas.retractSource),options.authenticate,route(async(body,context)=>{await options.knowledge.retract({context,sourceId:text(body.sourceId,"sourceId",256),...(body.sourceKind===undefined?{}:{sourceKind:text(body.sourceKind,"sourceKind",64)}),delete:body.delete===true});return{status:body.delete===true?"deleted":"retracted"};}));
  registerContractRoute(app,contract("put","/api/admin/atlas/action-policies","actionPolicies.put","Set an Atlas action policy",atlasAdminSchemas.actionPolicy),options.authenticate,route((body,context)=>options.policies.putActionPolicy({context,expectedRevision:optional(body.expectedRevision),policy:{actionCode:text(body.actionCode,"actionCode",128),docClass:nullable(body.docClass),autonomyLevel:one(body.autonomyLevel,["disabled","suggest","assist","auto"] as const),minConfidenceForAuto:numberOrNull(body.minConfidenceForAuto),requiresHumanConfirmation:body.requiresHumanConfirmation!==false}})));
  registerContractRoute(app,contract("put","/api/admin/atlas/confidence-thresholds","confidenceThresholds.put","Set Atlas confidence thresholds",atlasAdminSchemas.confidenceThreshold),options.authenticate,route((body,context)=>options.policies.putConfidenceThreshold({context,expectedRevision:optional(body.expectedRevision),threshold:{actionCode:text(body.actionCode,"actionCode",128),docClass:nullable(body.docClass),modelId:nullable(body.modelId),minForSuggest:number(body.minForSuggest),minForAssist:number(body.minForAssist),minForAuto:number(body.minForAuto),driftAlertBelow:numberOrNull(body.driftAlertBelow),driftWindowHours:number(body.driftWindowHours)}})));
  registerContractRoute(app,contract("get","/api/admin/atlas/quota","quota.get","Read the current tenant Atlas quota"),options.authenticate,route((_body,context)=>options.quotas.snapshot(context)));
  registerContractRoute(app,contract("put","/api/admin/atlas/quota","quota.put","Set the current tenant Atlas quota",atlasAdminSchemas.quotaPolicy),options.authenticate,route((body,context)=>options.quotas.putPolicy(context,{maxRequests:integer(body.maxRequests),maxInputTokens:integer(body.maxInputTokens),maxOutputTokens:integer(body.maxOutputTokens),windowSeconds:integer(body.windowSeconds)})));
  registerContractRoute(app,contract("get","/api/admin/atlas/monitoring/calibration","monitoring.calibration","Read the Atlas calibration dashboard",undefined,atlasAdminSchemas.dashboardQuery),options.authenticate,route((_body,context,request)=>options.dashboards.calibration({context,windowHours:queryWindow(request)})));
  registerContractRoute(app,contract("get","/api/admin/atlas/monitoring/drift","monitoring.drift","Read the Atlas drift dashboard",undefined,atlasAdminSchemas.dashboardQuery),options.authenticate,route((_body,context,request)=>options.dashboards.drift({context,windowHours:queryWindow(request)})));
}
function contract(method:"get"|"post"|"put"|"delete",path:string,id:string,summary:string,body?:RuntimeSchema,query?:RuntimeSchema){return defineRouteContract({method,path,operationId:`atlas.admin.${id}`,summary,tags:["Atlas Administration"],authenticated:true,permission:"atlas.admin.manage",...(body||query?{request:{...(body?{body}:{}),...(query?{query}:{})}}:{}),responses:{200:{description:"Successful Atlas administration response",body:id==="credentials.revoke"?{anyOf:[atlasAdminSchemas.response,{type:"null"}]}:atlasAdminSchemas.response},400:{description:"Invalid request"},403:{description:"Permission denied"},409:{description:"Revision conflict"}}});}
function queryWindow(request:Request):number{const value=request.query.windowHours===undefined?24:Number(request.query.windowHours);if(!Number.isSafeInteger(value)||value<1||value>8760)throw new AtlasServiceError("INVALID_ARGUMENT","Monitoring window is invalid.");return value;}
function object(v:unknown):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v))throw new AtlasServiceError("INVALID_ARGUMENT","JSON object required.");return v as Record<string,unknown>;}function text(v:unknown,name:string,max:number):string{if(typeof v!=="string"||!v.trim()||Buffer.byteLength(v,"utf8")>max)throw new AtlasServiceError("INVALID_ARGUMENT",`${name} is invalid.`);return v.trim();}function provider(v:string):AtlasProviderId{if(!["openai","anthropic","gemini"].includes(v))throw new AtlasServiceError("INVALID_ARGUMENT","Provider is invalid.");return v as AtlasProviderId;}function nullable(v:unknown):string|null{return v==null?null:text(v,"value",256);}function optional(v:unknown):string|undefined{return v==null?undefined:text(v,"revision",256);}function number(v:unknown):number{const n=Number(v);if(!Number.isFinite(n))throw new AtlasServiceError("INVALID_ARGUMENT","Number required.");return n;}function integer(v:unknown):number{const n=number(v);if(!Number.isSafeInteger(n)||n<1)throw new AtlasServiceError("INVALID_ARGUMENT","Positive integer required.");return n;}function numberOrNull(v:unknown):number|null{return v==null?null:number(v);}function one<T extends string>(v:unknown,values:readonly T[]):T{if(typeof v!=="string"||!values.includes(v as T))throw new AtlasServiceError("INVALID_ARGUMENT","Enum value is invalid.");return v as T;}
