import type { AtlasCalibrationDashboardItem, AtlasCalibrationEvidence, AtlasDriftAlertPublisher, AtlasDriftBaseline, AtlasDriftDashboardItem, AtlasFeedbackEvidence, AtlasInferenceEvidence, AtlasMonitoringDashboard, AtlasMonitoringLedger } from "@athyper/server-contract-ai";
import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { PlaneTransactionCoordinator } from "@athyper/server-foundation/transaction";
import type { JobHandler } from "@athyper/server-contract-jobs";
import { sql, type Transaction } from "kysely";
type Db=Record<string,never>;type Tx=Transaction<Db>;
export const ATLAS_MONITORING_QUEUE="atlas.monitoring",RUN_ATLAS_DRIFT_JOB="atlas.monitoring.drift";
export interface AtlasDriftJobPayload{readonly tenantId:string;readonly principalId:string;readonly actionCode:string;readonly docClass:string|null;readonly modelId:string;readonly modelRevision:string;readonly promptRevision:string;readonly policyRevision:string;readonly windowHours:number;}

export class KyselyAtlasMonitoringLedger implements AtlasMonitoringLedger {
  constructor(private readonly transactions:PlaneTransactionCoordinator<Tx>){}
  appendInference(i:AtlasInferenceEvidence):Promise<void>{pins(i);return this.tx(i.tenantId,i.createdBy,async tx=>{await sql`INSERT INTO ai.ai_inference_log (id,tenant_id,log_type,inference_type,model_id,model_version,txn_id,confidence,reasoning_chain,input,output,action_type,prediction_type,correlation_id,created_at,created_by) VALUES (${i.inferenceId}::uuid,${i.tenantId}::uuid,'system',${i.inferenceType},${i.modelId}::uuid,${i.modelVersion},${i.transactionId??null}::uuid,${i.confidence??null},${JSON.stringify({model_revision:i.modelRevision,prompt_revision:i.promptRevision,policy_revision:i.policyRevision})}::jsonb,NULL,NULL,${i.actionCode??null},${i.predictionType??null},${i.correlationId??null}::uuid,${i.createdAt}::timestamptz,${i.createdBy}::uuid)`.execute(tx);});}
  appendFeedback(i:AtlasFeedbackEvidence):Promise<void>{return this.tx(i.tenantId,i.submittedBy,async tx=>{await sql`INSERT INTO ai.ai_feedback_log (id,tenant_id,log_type,feedback_type,target_id,verdict,reason_code,evidence_snapshot,detail,submitted_by,submitted_at,created_at,created_by) VALUES (${i.feedbackId}::uuid,${i.tenantId}::uuid,'business',${required(i.feedbackType,128)},${i.targetId??null}::uuid,${i.verdict},${i.reasonCode??null},NULL,NULL,${i.submittedBy}::uuid,${i.submittedAt}::timestamptz,${i.submittedAt}::timestamptz,${i.submittedBy}::uuid)`.execute(tx);});}
  appendCalibration(i:AtlasCalibrationEvidence):Promise<void>{pins(i);return this.tx(i.tenantId,i.createdBy,async tx=>{await sql`INSERT INTO ai.ai_calibration_log (id,tenant_id,log_type,calibration_type,threshold_before,threshold_after,calibration_trigger,metric_name,metric_value,sample_count,calibration_detail,calibrated_by,created_at,created_by) VALUES (${i.calibrationId}::uuid,${i.tenantId}::uuid,'system',${required(i.calibrationType,128)},${i.thresholdBefore??null},${i.thresholdAfter??null},${required(i.trigger,128)},${i.metricName??null},${i.metricValue??null},${i.sampleCount??null},${JSON.stringify({model_revision:i.modelRevision,prompt_revision:i.promptRevision,policy_revision:i.policyRevision})}::jsonb,${i.createdBy}::uuid,${i.createdAt}::timestamptz,${i.createdBy}::uuid)`.execute(tx);});}
  private tx<T>(tenantId:string,principalId:string,work:(tx:Tx)=>Promise<T>):Promise<T>{return this.transactions.run("neon",{tenantId,principalId},work);}
}

export class KyselyAtlasDriftMonitor {
  constructor(private readonly options:{transactions:PlaneTransactionCoordinator<Tx>;alerts:AtlasDriftAlertPublisher;minimumSamples?:number}){}
  swapBaseline(input:AtlasDriftBaseline):Promise<void>{pins(input);ratio(input.meanConfidence);if(!Number.isSafeInteger(input.sampleSize)||input.sampleSize<1||!Number.isFinite(input.stdDevConfidence)||input.stdDevConfidence<0)throw new Error("Drift baseline statistics are invalid.");return this.tx(input.tenantId,input.createdBy,async tx=>{await sql`UPDATE ai.ai_drift_baseline SET is_current=false,superseded_at=${input.at}::timestamptz,updated_at=${input.at}::timestamptz,updated_by=${input.createdBy}::uuid WHERE tenant_id=${input.tenantId}::uuid AND action_code=${input.actionCode} AND doc_class IS NOT DISTINCT FROM ${input.docClass} AND model_id=${input.modelId} AND is_current=true`.execute(tx);await sql`INSERT INTO ai.ai_drift_baseline (id,tenant_id,action_code,doc_class,model_id,baseline_date,sample_size,mean_confidence,std_dev_confidence,p5_confidence,p95_confidence,feature_stats,is_current,created_at,created_by) VALUES (${input.baselineId}::uuid,${input.tenantId}::uuid,${input.actionCode},${input.docClass},${input.modelId},${input.at}::date,${input.sampleSize},${input.meanConfidence},${input.stdDevConfidence},${input.p5Confidence??null},${input.p95Confidence??null},${JSON.stringify({model_revision:input.modelRevision,prompt_revision:input.promptRevision,policy_revision:input.policyRevision})}::jsonb,true,${input.at}::timestamptz,${input.createdBy}::uuid)`.execute(tx);});}
  async run(input:{tenantId:string;principalId:string;actionCode:string;docClass:string|null;modelId:string;modelRevision:string;promptRevision:string;policyRevision:string;windowHours:number}):Promise<{alerted:boolean;sampleCount:number}>{pins(input);const result=await this.tx(input.tenantId,input.principalId,async tx=>{const stats=await sql<{sample_count:string|number;mean_confidence:string|number|null}>`SELECT count(*) AS sample_count,avg(confidence) AS mean_confidence FROM ai.ai_inference_log WHERE tenant_id=${input.tenantId}::uuid AND action_type=${input.actionCode} AND model_id=${input.modelId}::uuid AND model_version=${input.modelRevision} AND reasoning_chain->>'prompt_revision'=${input.promptRevision} AND reasoning_chain->>'policy_revision'=${input.policyRevision} AND created_at>=now()-(${input.windowHours}||' hours')::interval AND confidence IS NOT NULL`.execute(tx);const baseline=await sql<{mean_confidence:string|number;feature_stats:unknown}>`SELECT mean_confidence,feature_stats FROM ai.ai_drift_baseline WHERE tenant_id=${input.tenantId}::uuid AND action_code=${input.actionCode} AND doc_class IS NOT DISTINCT FROM ${input.docClass} AND model_id=${input.modelId} AND is_current=true LIMIT 1`.execute(tx);const sampleCount=Number(stats.rows[0]?.sample_count??0);const metric=Number(stats.rows[0]?.mean_confidence??0);if(sampleCount<(this.options.minimumSamples??20)||!baseline.rows[0])return{alerted:false,sampleCount,metric,baseline:null as number|null};const pinsValue=object(baseline.rows[0].feature_stats);if(pinsValue["model_revision"]!==input.modelRevision||pinsValue["prompt_revision"]!==input.promptRevision||pinsValue["policy_revision"]!==input.policyRevision)throw new Error("Drift baseline revision pins do not match the inference window.");const base=Number(baseline.rows[0].mean_confidence);const alerted=metric<base;await sql`INSERT INTO ai.ai_monitoring_log (tenant_id,log_type,monitor_type,model_id,metric_name,metric_value,baseline_value,is_alert,is_alert_sent,window_start,window_end,detail,created_by) VALUES (${input.tenantId}::uuid,'system','drift',${input.modelId}::uuid,'mean_confidence',${metric},${base},${alerted},false,now()-(${input.windowHours}||' hours')::interval,now(),${JSON.stringify({action_code:input.actionCode,doc_class:input.docClass,sample_count:sampleCount,model_revision:input.modelRevision,prompt_revision:input.promptRevision,policy_revision:input.policyRevision})}::jsonb,${input.principalId}::uuid)`.execute(tx);return{alerted,sampleCount,metric,baseline:base};});if(result.alerted&&result.baseline!==null)await this.options.alerts.publish({tenantId:input.tenantId,actionCode:input.actionCode,modelId:input.modelId,metricValue:result.metric,baselineValue:result.baseline,sampleCount:result.sampleCount,modelRevision:input.modelRevision,promptRevision:input.promptRevision,policyRevision:input.policyRevision});return{alerted:result.alerted,sampleCount:result.sampleCount};}
  private tx<T>(tenantId:string,principalId:string,work:(tx:Tx)=>Promise<T>):Promise<T>{return this.options.transactions.run("neon",{tenantId,principalId},work);}
}
export class KyselyAtlasMonitoringDashboard implements AtlasMonitoringDashboard{
  constructor(private readonly transactions:PlaneTransactionCoordinator<Tx>){}
  async calibration(input:{context:VerifiedRequestContext;windowHours:number}):Promise<{windowHours:number;items:readonly AtlasCalibrationDashboardItem[]}>{window(input.windowHours);const rows=await this.transactions.run("neon",input.context,async tx=>(await sql<Record<string,unknown>>`SELECT calibration_type,metric_name,count(*)::int AS changes,coalesce(sum(sample_count),0)::int AS sample_count,(array_agg(metric_value ORDER BY created_at DESC))[1] AS latest_metric_value,(array_agg(threshold_before ORDER BY created_at DESC))[1] AS latest_threshold_before,(array_agg(threshold_after ORDER BY created_at DESC))[1] AS latest_threshold_after,max(created_at) AS latest_at FROM ai.ai_calibration_log WHERE tenant_id=${input.context.tenantId}::uuid AND created_at>=now()-(${input.windowHours}||' hours')::interval GROUP BY calibration_type,metric_name ORDER BY max(created_at) DESC`.execute(tx)).rows);return{windowHours:input.windowHours,items:rows.map(row=>({calibrationType:String(row["calibration_type"]??"unknown"),metricName:nullableText(row["metric_name"]),changes:Number(row["changes"]??0),sampleCount:Number(row["sample_count"]??0),latestMetricValue:nullableNumber(row["latest_metric_value"]),latestThresholdBefore:nullableNumber(row["latest_threshold_before"]),latestThresholdAfter:nullableNumber(row["latest_threshold_after"]),latestAt:new Date(String(row["latest_at"])).toISOString()}))};}
  async drift(input:{context:VerifiedRequestContext;windowHours:number}):Promise<{windowHours:number;items:readonly AtlasDriftDashboardItem[]}>{window(input.windowHours);const rows=await this.transactions.run("neon",input.context,async tx=>(await sql<Record<string,unknown>>`SELECT coalesce(detail->>'action_code','unknown') AS action_code,detail->>'doc_class' AS doc_class,coalesce(model_id::text,'unknown') AS model_id,count(*)::int AS checks,count(*) FILTER(WHERE is_alert)::int AS alerts,(array_agg(metric_value ORDER BY created_at DESC))[1] AS latest_metric_value,(array_agg(baseline_value ORDER BY created_at DESC))[1] AS latest_baseline_value,coalesce((array_agg(detail->>'sample_count' ORDER BY created_at DESC))[1],'0') AS latest_sample_count,max(created_at) AS latest_at FROM ai.ai_monitoring_log WHERE tenant_id=${input.context.tenantId}::uuid AND monitor_type='drift' AND created_at>=now()-(${input.windowHours}||' hours')::interval GROUP BY detail->>'action_code',detail->>'doc_class',model_id ORDER BY max(created_at) DESC`.execute(tx)).rows);return{windowHours:input.windowHours,items:rows.map(row=>({actionCode:String(row["action_code"]),docClass:nullableText(row["doc_class"]),modelId:String(row["model_id"]),checks:Number(row["checks"]??0),alerts:Number(row["alerts"]??0),latestMetricValue:nullableNumber(row["latest_metric_value"]),latestBaselineValue:nullableNumber(row["latest_baseline_value"]),latestSampleCount:Number(row["latest_sample_count"]??0),latestAt:new Date(String(row["latest_at"])).toISOString()}))};}
}
export function createAtlasDriftHandler(monitor:KyselyAtlasDriftMonitor):JobHandler<typeof RUN_ATLAS_DRIFT_JOB,AtlasDriftJobPayload>{return{async handle(job){const result=await monitor.run(job.data);return{status:"completed",output:result};}};}
function pins(v:{modelRevision:string;promptRevision:string;policyRevision:string}){required(v.modelRevision,256);required(v.promptRevision,256);required(v.policyRevision,256);}function required(v:string,max:number){const r=v.trim();if(!r||Buffer.byteLength(r,"utf8")>max)throw new Error("Monitoring identifier is invalid.");return r;}function ratio(v:number){if(!Number.isFinite(v)||v<0||v>1)throw new Error("Monitoring confidence is invalid.");}function window(v:number){if(!Number.isSafeInteger(v)||v<1||v>8760)throw new Error("Monitoring window is invalid.");}function nullableText(v:unknown):string|null{return v==null?null:String(v);}function nullableNumber(v:unknown):number|null{return v==null?null:Number(v);}function object(v:unknown):Record<string,unknown>{return(typeof v==="string"?JSON.parse(v):v??{}) as Record<string,unknown>;}
