import { randomUUID } from "node:crypto";
import type { AtlasQuotaReservation, AtlasTenantQuotaManager, AtlasTenantQuotaPolicy, AtlasTenantQuotaSnapshot } from "@athyper/server-contract-ai";
import type { VerifiedRequestContext } from "@athyper/server-contract-auth";
import type { PlaneTransactionCoordinator, TransactionActor } from "@athyper/server-foundation/transaction";
import { sql, type Transaction } from "kysely";
import { AtlasServiceError } from "./errors.js";

type Tx=Transaction<Record<string,never>>;

interface TenantWindow {
  startsAtMs: number;
  usedRequests: number;
  usedInputTokens: number;
  usedOutputTokens: number;
  reservedInputTokens: number;
  reservedOutputTokens: number;
}
interface ReservationRecord { readonly reservation: AtlasQuotaReservation; readonly input: number; readonly output: number }

/** Process-local atomic quota manager. A distributed deployment can provide the same contract from Redis or SQL. */
export class InMemoryAtlasTenantQuotaManager implements AtlasTenantQuotaManager {
  private readonly policies = new Map<string, AtlasTenantQuotaPolicy>();
  private readonly windows = new Map<string, TenantWindow>();
  private readonly reservations = new Map<string, ReservationRecord>();
  constructor(private readonly options: { readonly defaultPolicy: AtlasTenantQuotaPolicy; readonly now?: () => Date; readonly createId?: () => string }) { validatePolicy(options.defaultPolicy); }

  async reserve(input: Parameters<AtlasTenantQuotaManager["reserve"]>[0]): Promise<AtlasQuotaReservation> {
    const estimatedInputTokens = count(input.estimatedInputTokens); const maxOutputTokens = count(input.maxOutputTokens);
    const policy = this.policy(input.context.tenantId); const window = this.window(input.context.tenantId, policy);
    if (window.usedRequests + 1 > policy.maxRequests || window.usedInputTokens + window.reservedInputTokens + estimatedInputTokens > policy.maxInputTokens || window.usedOutputTokens + window.reservedOutputTokens + maxOutputTokens > policy.maxOutputTokens) {
      throw new AtlasServiceError("QUOTA_EXCEEDED", "The tenant Atlas quota is exhausted for the current window.");
    }
    window.usedRequests += 1; window.reservedInputTokens += estimatedInputTokens; window.reservedOutputTokens += maxOutputTokens;
    const reservation = Object.freeze({ reservationId: (this.options.createId ?? randomUUID)(), tenantId: input.context.tenantId, planeKey:input.context.planeKey, principalId:input.context.principalId, reservedInputTokens: estimatedInputTokens, reservedOutputTokens: maxOutputTokens });
    this.reservations.set(reservation.reservationId, { reservation, input: estimatedInputTokens, output: maxOutputTokens }); return reservation;
  }
  async settle(input: Parameters<AtlasTenantQuotaManager["settle"]>[0]): Promise<void> {
    const record = this.take(input.reservation); if (!record) return; const policy = this.policy(record.reservation.tenantId); const window = this.window(record.reservation.tenantId, policy);
    window.reservedInputTokens = Math.max(0, window.reservedInputTokens - record.input); window.reservedOutputTokens = Math.max(0, window.reservedOutputTokens - record.output);
    window.usedInputTokens += count(input.inputTokens); window.usedOutputTokens += count(input.outputTokens);
  }
  async release(reservation: AtlasQuotaReservation): Promise<void> {
    const record = this.take(reservation); if (!record) return; const policy = this.policy(record.reservation.tenantId); const window = this.window(record.reservation.tenantId, policy);
    window.reservedInputTokens = Math.max(0, window.reservedInputTokens - record.input); window.reservedOutputTokens = Math.max(0, window.reservedOutputTokens - record.output);
  }
  async snapshot(context: VerifiedRequestContext): Promise<AtlasTenantQuotaSnapshot> { const tenantId=context.tenantId;const policy = this.policy(tenantId); const window = this.window(tenantId, policy); return snapshot(tenantId, policy, window); }
  async putPolicy(context: VerifiedRequestContext, policy: AtlasTenantQuotaPolicy): Promise<AtlasTenantQuotaSnapshot> { validatePolicy(policy); this.policies.set(required(context.tenantId), Object.freeze({ ...policy })); return this.snapshot(context); }
  private policy(tenantId: string): AtlasTenantQuotaPolicy { return this.policies.get(required(tenantId)) ?? this.options.defaultPolicy; }
  private window(tenantId: string, policy: AtlasTenantQuotaPolicy): TenantWindow { const now = (this.options.now ?? (() => new Date()))().getTime(); let value = this.windows.get(tenantId); if (!value || now >= value.startsAtMs + policy.windowSeconds * 1_000) { value = { startsAtMs: now, usedRequests: 0, usedInputTokens: 0, usedOutputTokens: 0, reservedInputTokens: 0, reservedOutputTokens: 0 }; this.windows.set(tenantId, value); } return value; }
  private take(reservation: AtlasQuotaReservation): ReservationRecord | undefined { const value = this.reservations.get(reservation.reservationId); if (!value || value.reservation.tenantId !== reservation.tenantId) return undefined; this.reservations.delete(reservation.reservationId); return value; }
}

interface PolicyRow{max_requests:string|number;max_input_tokens:string|number;max_output_tokens:string|number;window_seconds:string|number}
interface WindowRow{window_started_at:string|Date;window_ends_at:string|Date;used_requests:string|number;used_input_tokens:string|number;used_output_tokens:string|number;reserved_input_tokens:string|number;reserved_output_tokens:string|number}
interface ReservationRow{status:"reserved"|"settled"|"released"|"expired";window_started_at:string|Date;reserved_input_tokens:string|number;reserved_output_tokens:string|number}

/** PostgreSQL-backed quota manager. Tenant advisory locks make reserve/settle atomic across host instances. */
export class KyselyAtlasTenantQuotaManager implements AtlasTenantQuotaManager{
  private readonly createId:()=>string;private readonly reservationTtlSeconds:number;
  constructor(private readonly options:{transactions:PlaneTransactionCoordinator<Tx>;defaultPolicy:AtlasTenantQuotaPolicy;reservationTtlSeconds?:number;createId?:()=>string}){validatePolicy(options.defaultPolicy);this.reservationTtlSeconds=options.reservationTtlSeconds??1_800;if(!Number.isSafeInteger(this.reservationTtlSeconds)||this.reservationTtlSeconds<1)throw new TypeError("Atlas quota reservation TTL must be a positive integer.");this.createId=options.createId??randomUUID;}
  reserve(input:Parameters<AtlasTenantQuotaManager["reserve"]>[0]):Promise<AtlasQuotaReservation>{const estimatedInputTokens=count(input.estimatedInputTokens),maxOutputTokens=count(input.maxOutputTokens);return this.options.transactions.run(input.context.planeKey,input.context,async tx=>{await tenantLock(tx,input.context.tenantId);const at=await databaseNow(tx);await this.reclaimExpired(tx,input.context,at);const policy=await this.policy(tx,input.context.tenantId),window=await this.ensureWindow(tx,input.context,policy,at);if(num(window.used_requests)+1>policy.maxRequests||num(window.used_input_tokens)+num(window.reserved_input_tokens)+estimatedInputTokens>policy.maxInputTokens||num(window.used_output_tokens)+num(window.reserved_output_tokens)+maxOutputTokens>policy.maxOutputTokens)throw new AtlasServiceError("QUOTA_EXCEEDED","The tenant Atlas quota is exhausted for the current window.");const reservation:AtlasQuotaReservation=Object.freeze({reservationId:this.createId(),tenantId:input.context.tenantId,planeKey:input.context.planeKey,principalId:input.context.principalId,reservedInputTokens:estimatedInputTokens,reservedOutputTokens:maxOutputTokens});const expiresAt=new Date(Math.min(at.getTime()+this.reservationTtlSeconds*1_000,date(window.window_ends_at).getTime()));await sql`INSERT INTO ai.atlas_tenant_quota_reservation(id,tenant_id,window_started_at,plane_key,principal_id,reserved_input_tokens,reserved_output_tokens,status,expires_at,created_by) VALUES(${reservation.reservationId}::uuid,${reservation.tenantId}::uuid,${date(window.window_started_at)}::timestamptz,${reservation.planeKey},${reservation.principalId}::uuid,${estimatedInputTokens},${maxOutputTokens},'reserved',${expiresAt}::timestamptz,${reservation.principalId}::uuid)`.execute(tx);await sql`UPDATE ai.atlas_tenant_quota_window SET used_requests=used_requests+1,reserved_input_tokens=reserved_input_tokens+${estimatedInputTokens},reserved_output_tokens=reserved_output_tokens+${maxOutputTokens},updated_at=clock_timestamp(),updated_by=${reservation.principalId}::uuid WHERE tenant_id=${reservation.tenantId}::uuid AND window_started_at=${date(window.window_started_at)}::timestamptz`.execute(tx);return reservation;});}
  settle(input:Parameters<AtlasTenantQuotaManager["settle"]>[0]):Promise<void>{const inputTokens=count(input.inputTokens),outputTokens=count(input.outputTokens),actor=actorFor(input.reservation);return this.options.transactions.run(input.reservation.planeKey,actor,async tx=>{await tenantLock(tx,input.reservation.tenantId);const row=(await sql<ReservationRow>`SELECT status,window_started_at,reserved_input_tokens,reserved_output_tokens FROM ai.atlas_tenant_quota_reservation WHERE id=${input.reservation.reservationId}::uuid AND tenant_id=${input.reservation.tenantId}::uuid FOR UPDATE`.execute(tx)).rows[0];if(!row||row.status==="settled"||row.status==="released")return;const reserved=row.status==="reserved";await sql`UPDATE ai.atlas_tenant_quota_window SET reserved_input_tokens=GREATEST(0,reserved_input_tokens-${reserved?num(row.reserved_input_tokens):0}),reserved_output_tokens=GREATEST(0,reserved_output_tokens-${reserved?num(row.reserved_output_tokens):0}),used_input_tokens=used_input_tokens+${inputTokens},used_output_tokens=used_output_tokens+${outputTokens},updated_at=clock_timestamp(),updated_by=${input.reservation.principalId}::uuid WHERE tenant_id=${input.reservation.tenantId}::uuid AND window_started_at=${date(row.window_started_at)}::timestamptz`.execute(tx);await sql`UPDATE ai.atlas_tenant_quota_reservation SET status='settled',actual_input_tokens=${inputTokens},actual_output_tokens=${outputTokens},settled_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by=${input.reservation.principalId}::uuid WHERE id=${input.reservation.reservationId}::uuid`.execute(tx);});}
  release(reservation:AtlasQuotaReservation):Promise<void>{const actor=actorFor(reservation);return this.options.transactions.run(reservation.planeKey,actor,async tx=>{await tenantLock(tx,reservation.tenantId);const row=(await sql<ReservationRow>`SELECT status,window_started_at,reserved_input_tokens,reserved_output_tokens FROM ai.atlas_tenant_quota_reservation WHERE id=${reservation.reservationId}::uuid AND tenant_id=${reservation.tenantId}::uuid FOR UPDATE`.execute(tx)).rows[0];if(!row||row.status!=="reserved")return;await sql`UPDATE ai.atlas_tenant_quota_window SET reserved_input_tokens=GREATEST(0,reserved_input_tokens-${num(row.reserved_input_tokens)}),reserved_output_tokens=GREATEST(0,reserved_output_tokens-${num(row.reserved_output_tokens)}),updated_at=clock_timestamp(),updated_by=${reservation.principalId}::uuid WHERE tenant_id=${reservation.tenantId}::uuid AND window_started_at=${date(row.window_started_at)}::timestamptz`.execute(tx);await sql`UPDATE ai.atlas_tenant_quota_reservation SET status='released',released_at=clock_timestamp(),updated_at=clock_timestamp(),updated_by=${reservation.principalId}::uuid WHERE id=${reservation.reservationId}::uuid`.execute(tx);});}
  snapshot(context:VerifiedRequestContext):Promise<AtlasTenantQuotaSnapshot>{return this.options.transactions.run(context.planeKey,context,async tx=>{await tenantLock(tx,context.tenantId);const at=await databaseNow(tx);await this.reclaimExpired(tx,context,at);const policy=await this.policy(tx,context.tenantId),window=await this.ensureWindow(tx,context,policy,at);return dbSnapshot(context.tenantId,policy,window);});}
  async putPolicy(context:VerifiedRequestContext,policy:AtlasTenantQuotaPolicy):Promise<AtlasTenantQuotaSnapshot>{validatePolicy(policy);await this.options.transactions.run(context.planeKey,context,async tx=>{await tenantLock(tx,context.tenantId);await sql`INSERT INTO ai.atlas_tenant_quota_policy(tenant_id,max_requests,max_input_tokens,max_output_tokens,window_seconds,created_by) VALUES(${context.tenantId}::uuid,${policy.maxRequests},${policy.maxInputTokens},${policy.maxOutputTokens},${policy.windowSeconds},${context.principalId}::uuid) ON CONFLICT(tenant_id) DO UPDATE SET max_requests=EXCLUDED.max_requests,max_input_tokens=EXCLUDED.max_input_tokens,max_output_tokens=EXCLUDED.max_output_tokens,window_seconds=EXCLUDED.window_seconds,revision=ai.atlas_tenant_quota_policy.revision+1,updated_at=clock_timestamp(),updated_by=${context.principalId}::uuid`.execute(tx);});return this.snapshot(context);}
  private async policy(tx:Tx,tenantId:string):Promise<AtlasTenantQuotaPolicy>{const row=(await sql<PolicyRow>`SELECT max_requests,max_input_tokens,max_output_tokens,window_seconds FROM ai.atlas_tenant_quota_policy WHERE tenant_id=${tenantId}::uuid`.execute(tx)).rows[0];return row?{maxRequests:num(row.max_requests),maxInputTokens:num(row.max_input_tokens),maxOutputTokens:num(row.max_output_tokens),windowSeconds:num(row.window_seconds)}:this.options.defaultPolicy;}
  private async ensureWindow(tx:Tx,context:VerifiedRequestContext,policy:AtlasTenantQuotaPolicy,at:Date):Promise<WindowRow>{let row=(await sql<WindowRow>`SELECT window_started_at,window_ends_at,used_requests,used_input_tokens,used_output_tokens,reserved_input_tokens,reserved_output_tokens FROM ai.atlas_tenant_quota_window WHERE tenant_id=${context.tenantId}::uuid AND window_started_at<=${at}::timestamptz AND window_ends_at>${at}::timestamptz ORDER BY window_started_at DESC LIMIT 1 FOR UPDATE`.execute(tx)).rows[0];if(!row){const endsAt=new Date(at.getTime()+policy.windowSeconds*1_000);row=(await sql<WindowRow>`INSERT INTO ai.atlas_tenant_quota_window(tenant_id,window_started_at,window_ends_at,created_by) VALUES(${context.tenantId}::uuid,${at}::timestamptz,${endsAt}::timestamptz,${context.principalId}::uuid) RETURNING window_started_at,window_ends_at,used_requests,used_input_tokens,used_output_tokens,reserved_input_tokens,reserved_output_tokens`.execute(tx)).rows[0]!;}return row;}
  private async reclaimExpired(tx:Tx,context:VerifiedRequestContext,at:Date):Promise<void>{const expired=(await sql<{window_started_at:string|Date;reserved_input_tokens:string|number;reserved_output_tokens:string|number}>`UPDATE ai.atlas_tenant_quota_reservation SET status='expired',released_at=${at}::timestamptz,updated_at=${at}::timestamptz,updated_by=${context.principalId}::uuid WHERE tenant_id=${context.tenantId}::uuid AND status='reserved' AND expires_at<=${at}::timestamptz RETURNING window_started_at,reserved_input_tokens,reserved_output_tokens`.execute(tx)).rows;const windows=new Map<string,{at:Date;input:number;output:number}>();for(const row of expired){const started=date(row.window_started_at),key=started.toISOString(),value=windows.get(key)??{at:started,input:0,output:0};value.input+=num(row.reserved_input_tokens);value.output+=num(row.reserved_output_tokens);windows.set(key,value);}for(const value of windows.values())await sql`UPDATE ai.atlas_tenant_quota_window SET reserved_input_tokens=GREATEST(0,reserved_input_tokens-${value.input}),reserved_output_tokens=GREATEST(0,reserved_output_tokens-${value.output}),updated_at=${at}::timestamptz,updated_by=${context.principalId}::uuid WHERE tenant_id=${context.tenantId}::uuid AND window_started_at=${value.at}::timestamptz`.execute(tx);}
}
async function tenantLock(tx:Tx,tenantId:string):Promise<void>{await sql`SELECT pg_advisory_xact_lock(hashtextextended(${`${tenantId}:atlas-quota`},0))`.execute(tx);}async function databaseNow(tx:Tx):Promise<Date>{const row=(await sql<{at:string|Date}>`SELECT clock_timestamp() AS at`.execute(tx)).rows[0];if(!row)throw new Error("Database clock is unavailable.");return date(row.at);}function actorFor(value:AtlasQuotaReservation):TransactionActor{return{tenantId:value.tenantId,principalId:value.principalId};}function dbSnapshot(tenantId:string,policy:AtlasTenantQuotaPolicy,row:WindowRow):AtlasTenantQuotaSnapshot{return Object.freeze({...policy,tenantId,usedRequests:num(row.used_requests),usedInputTokens:num(row.used_input_tokens)+num(row.reserved_input_tokens),usedOutputTokens:num(row.used_output_tokens)+num(row.reserved_output_tokens),resetsAt:date(row.window_ends_at).toISOString()});}function date(value:string|Date):Date{return value instanceof Date?value:new Date(value);}function num(value:string|number|null|undefined):number{return Number(value??0);}
function snapshot(tenantId:string,policy:AtlasTenantQuotaPolicy,window:TenantWindow):AtlasTenantQuotaSnapshot{return Object.freeze({...policy,tenantId,usedRequests:window.usedRequests,usedInputTokens:window.usedInputTokens+window.reservedInputTokens,usedOutputTokens:window.usedOutputTokens+window.reservedOutputTokens,resetsAt:new Date(window.startsAtMs+policy.windowSeconds*1_000).toISOString()});}
function validatePolicy(policy:AtlasTenantQuotaPolicy):void{for(const value of [policy.maxRequests,policy.maxInputTokens,policy.maxOutputTokens,policy.windowSeconds])if(!Number.isSafeInteger(value)||value<1)throw new TypeError("Atlas quota limits must be positive integers.");}
function count(value:number):number{if(!Number.isFinite(value)||value<0)throw new TypeError("Atlas quota usage must be non-negative.");return Math.ceil(value);}
function required(value:string):string{const result=value.trim();if(!result)throw new TypeError("Atlas tenant id is required.");return result;}
