http:
  routers:
    secretstore:
      rule: Host(`secrets.dev.athyper.test`)
      entryPoints: [https]
      tls: {}
      service: secretstore
  services:
    secretstore:
      loadBalancer:
        servers: [{url: "http://secretstore:8080"}]
tls:
  certificates:
    - certFile: /run/secrets/publication-tls-certificate
      keyFile: /run/secrets/publication-tls-private-key
