import {execFileSync} from 'node:child_process';import{mkdirSync,copyFileSync,cpSync,writeFileSync,readFileSync}from'node:fs';import{homedir}from'node:os';
const root=homedir()+'/.athyper/instances/dev/deployments/bp-release-19-isolated-20260910',build=root+'/build';mkdirSync(build,{recursive:true});
const manifest=JSON.parse(readFileSync(root+'/infrastructure.json','utf8'));
for(const name of ['host.mjs','release-boundary.mjs','case-bindings.mjs','import-policy.mjs','ai-retrieval.mjs'])copyFileSync('tooling/scripts/verification/isolated-execution/'+name,build+'/'+name);
cpSync('server/packages/services/records/dist',build+'/records',{recursive:true});
for(const name of ['business-partner-backend-mapping','business-partner-permission-transitions','business-partner-stored-scopes'])copyFileSync('server/apps/platform-host/dist/composition/'+name+'.js',build+'/'+name+'.js');
for(const name of ['kysely-context-refresh','kysely-permission-resolver'])copyFileSync('server/packages/platform/iam/dist/'+name+'.js',build+'/'+name+'.js');
copyFileSync('server/packages/services/master-data/dist/business-partner-governed-import-routes.js',build+'/business-partner-governed-import-routes.js');
copyFileSync('server/packages/services/master-data/dist/business-partner-request-validator.js',build+'/business-partner-request-validator.js');
for(const name of ['business-partner-request-service','kysely-business-partner-case-repository'])copyFileSync('server/packages/services/master-data/dist/'+name+'.js',build+'/'+name+'.js');
copyFileSync('server/packages/platform/ai/dist/entity-record-tool.js',build+'/entity-record-tool.js');
const ai=execFileSync('docker',['exec','athyper-dev-worker-1','readlink','-f','/app/server/node_modules/@athyper/server-platform-ai'],{encoding:'utf8'}).trim();
const records=execFileSync('docker',['exec','athyper-dev-worker-1','readlink','-f','/app/server/node_modules/@athyper/server-service-records'],{encoding:'utf8'}).trim();
copyFileSync('server/packages/platform/metadata/dist/descriptor-parser.js',build+'/descriptor-parser.js');
const metadata=execFileSync('docker',['exec','athyper-dev-worker-1','readlink','-f','/app/server/node_modules/@athyper/server-platform-metadata'],{encoding:'utf8'}).trim();
const masterData=execFileSync('docker',['exec','athyper-dev-worker-1','readlink','-f','/app/server/node_modules/@athyper/server-service-master-data'],{encoding:'utf8'}).trim();
const iam=execFileSync('docker',['exec','athyper-dev-worker-1','readlink','-f','/app/server/node_modules/@athyper/server-platform-iam'],{encoding:'utf8'}).trim();
execFileSync('docker',['tag',manifest.sourceWorkerImage,'athyper-bp-r19-base:20260910']);
const originalServices=execFileSync('docker',['run','--rm','--entrypoint','cat',manifest.sourceWorkerImage,'/app/server/dist/composition/register-services.js'],{encoding:'utf8',maxBuffer:3000000});
const hook='const observeAuthority = (authority) => {';
if(originalServices.split(hook).length!==2)throw Error('ISOLATED_COMPOSITION_PATCH_ANCHOR_MISMATCH');
const importHook='if (Object.values(BUSINESS_PARTNER_360_PERMISSIONS).includes(input.permissionCode))';
if(originalServices.split(importHook).length!==2)throw Error('IMPORT_POLICY_PATCH_ANCHOR_MISMATCH');
writeFileSync(build+'/register-services.js',originalServices.replace(hook,hook+'\n        if (dependencies.isolatedExecutionAuthority) authority=dependencies.isolatedExecutionAuthority(authority);').replace(importHook,"if(input.permissionCode === 'neon.relationship.bp_target.import' && dependencies.isolatedExecutionImportPolicy) return dependencies.isolatedExecutionImportPolicy.evaluate(input);\n                    "+importHook));
writeFileSync(build+'/Dockerfile',`FROM athyper-bp-r19-base:20260910\nUSER root\nCOPY entity-record-tool.js ${ai}/dist/entity-record-tool.js\nCOPY records/ ${records}/dist/\nCOPY descriptor-parser.js ${metadata}/dist/descriptor-parser.js\nCOPY business-partner-*.js register-services.js /app/server/dist/composition/\nCOPY kysely-context-refresh.js kysely-permission-resolver.js ${iam}/dist/\nCOPY business-partner-governed-import-routes.js ${masterData}/dist/business-partner-governed-import-routes.js\nCOPY business-partner-request-validator.js ${masterData}/dist/business-partner-request-validator.js\nCOPY business-partner-request-service.js kysely-business-partner-case-repository.js ${masterData}/dist/\nCOPY host.mjs release-boundary.mjs case-bindings.mjs import-policy.mjs ai-retrieval.mjs /app/server/isolated/\nWORKDIR /app/server\nENTRYPOINT ["node","/app/server/isolated/host.mjs"]\n`);
execFileSync('docker',['build','-t','athyper-bp-r19-isolated:20260910',build],{stdio:'inherit'});
