import{execFileSync}from'node:child_process';import{readFileSync,writeFileSync,existsSync}from'node:fs';import{createHash,randomUUID}from'node:crypto';import{artifactHash,releaseId}from'./release-boundary.mjs';import{assertAuthorityUnchanged}from'./authority-check.mjs';
const output='governance/policy/reports/business-partner-release-19-isolated-import.dev.json';
const report=existsSync(output)?JSON.parse(readFileSync(output,'utf8')):{schemaVersion:1,kind:'release19_authenticated_governed_import',runId:randomUUID(),releaseId,artifactHash,checks:[],importQualified:false,directWritesRejected:false};
const save=()=>writeFileSync(output,JSON.stringify(report,null,2)+'\n');
const send=(name,path,method,data,expected=[200])=>{const authority=assertAuthorityUnchanged();const result=JSON.parse(execFileSync('docker',['exec','-i','athyper-bp-r19-auth-client','node','/client/session-client.mjs','catl.admin',path,method],{input:JSON.stringify(data??{}),encoding:'utf8',maxBuffer:3000000,stdio:['pipe','pipe','pipe']}));if(assertAuthorityUnchanged().sha256!==authority.sha256)throw Error('AUTHORITY_CHANGED');const passed=expected.includes(result.status)&&result.artifact===artifactHash;report.checks.push({name,status:result.status,passed,artifact:result.artifact,code:result.body.code??result.body.error?.code,authorityHash:authority.sha256,requestRef:createHash('sha256').update(result.requestId??'').digest('hex'),checkedAt:new Date().toISOString()});save();console.log(JSON.stringify(report.checks.at(-1)));if(!passed){writeFileSync('/tmp/bp-r19-build/last-import-response.json',JSON.stringify(result,null,2));throw Error(name+':'+result.status);}return result.body;};
const runId=report.runId,org='a478f9c0-8226-5d22-9599-b8fb27a45180';
const batch={schemaVersion:1,release:{releaseId,compiledHash:'83ca015f869bfe90bce4a8bb4eedc5d5ffa48f50523faa8a04997dd9b4d923ec'},batch:{schemaVersion:1,batchKey:'isolated-import-'+runId,rows:[{rowKey:'supplier-0001',operatingOrganizationId:org,proposedPayload:{legalName:'Isolated Governed Import '+runId,registrationCountryCode:'GB',ownershipClass:'internal',supplierType:'intercompany'},extensions:{addresses:[{clientItemKey:'primary-address',definitionFieldCode:'relationship.address.primary',purpose:'default',line1:'1 Import Qualification Road',city:'London',postalCode:'SW1A 1AA',countryCode:'GB',isPrimary:true,normalizedHash:createHash('sha256').update(runId).digest('hex')}],contactPersons:[{clientItemKey:'primary-contact',definitionFieldCode:'relationship.contact.primary',contactName:'Import Qualification Contact',isPrimary:true}],contactChannels:[{clientItemKey:'primary-email',definitionFieldCode:'relationship.contact.email',contactClientItemKey:'primary-contact',channelType:'email',value:'import-'+runId+'@example.test',purpose:'default',isPrimary:true}]}}]}};
try{
 send('direct_create_deferred','/api/records/business_partner','POST',{legalName:'Forbidden Direct '+runId},[403,409]);
 send('direct_update_deferred','/api/records/business_partner/f7688c3d-8c92-5651-a469-da3f4f786375','PATCH',{legalName:'Forbidden Direct '+runId},[403,409]);send('legacy_direct_import_rejected','/api/records/business_partner/imports','POST',{operation:'create',scopeCoordinate:{operatingOrganizationId:org}},[403]);report.directWritesRejected=true;
 const imported=send('governed_import','/api/neon/business-partner-imports','POST',batch);const outcome=imported.outcomes?.[0];
 if(!['created','replayed'].includes(outcome?.status))throw Error('IMPORT_DRAFT_NOT_CREATED');report.importRequestId=outcome.requestId;
 const view=send('import_governed_draft','/api/neon/business-partner-cases/'+outcome.requestId+'/view','GET');
 if(view.request.status!=='draft'||view.request.source?.kind!=='import'||view.request.targetBusinessPartnerId)throw Error('IMPORT_GOVERNANCE_BOUNDARY_FAILED');
 const replay=send('import_idempotent_replay','/api/neon/business-partner-imports','POST',batch);if(replay.outcomes?.[0]?.status!=='replayed'||replay.outcomes[0].requestId!==outcome.requestId)throw Error('IMPORT_REPLAY_MISMATCH');
 const conflict=structuredClone(batch);conflict.batch.rows[0].proposedPayload.legalName+=' Changed';const rejectedRetry=send('changed_import_retry_rejected','/api/neon/business-partner-imports','POST',conflict);if(rejectedRetry.outcomes?.[0]?.status!=='failed'||rejectedRetry.outcomes[0].requestId)throw Error('IMPORT_CONFLICT_ACCEPTED');
 const invalid=structuredClone(batch);invalid.batch.batchKey+='-invalid';invalid.batch.rows[0].proposedPayload.ownershipClass='internal';invalid.batch.rows[0].proposedPayload.supplierType='general';send('incompatible_import_rejected_before_write','/api/neon/business-partner-imports','POST',invalid,[400]);
 const mismatch={...batch,release:{...batch.release,releaseId:'126721f6-a2e5-45e2-91bf-0d6a1b660c56'}};send('wrong_release_import_rejected','/api/neon/business-partner-imports','POST',mismatch,[409]);
 report.importQualified=true;report.completedAt=new Date().toISOString();delete report.blocker;
}catch(e){report.blocker=e.message;console.log({blocked:report.blocker});process.exitCode=1;}finally{save();}
