"use client";
import { Input, Checkbox } from "@athyper/platform-ui";
import { PostalAddress, safeChannelHref } from "../related-record";
export type ContactDraft = Readonly<{ displayName?: string; role?: string; email?: string; phone?: string; primary?: boolean }>;
export type AddressDraft = Readonly<{ line1?: string; line2?: string; locality?: string; region?: string; postalCode?: string; countryCode?: string; purpose?: string; primary?: boolean }>;
const text=(value:unknown)=>typeof value==="string"?value:"";
export function ContactSummaryRenderer({ data }: { readonly data: unknown }) { const value=(data&&typeof data==="object"?(data as any).value:data)??{}; const name=text(value.displayName??value.name), email=text(value.email), phone=text(value.phone); return <div className="a-summary-contact"><strong>{name||"No designated contact"}</strong>{text(value.role??value.businessTitle)?<p>{text(value.role??value.businessTitle)}</p>:null}{email?<a href={safeChannelHref("email",email)}>{email}</a>:null}{phone?<a href={safeChannelHref("phone",phone)}>{phone}</a>:null}</div>; }
export function AddressSummaryRenderer({ data }: { readonly data: unknown }) { const value=(data&&typeof data==="object"?(data as any).value:data)??{}; return <div className="a-summary-address"><strong>{text(value.purpose)||"Primary address"}</strong><PostalAddress values={value}/>{value.verified===true?<small>Verified</small>:null}</div>; }
export function ContactEditor({ value, onChange, disabled=false }: { readonly value: ContactDraft; readonly onChange:(next:ContactDraft)=>void; readonly disabled?:boolean }) { const set=(key:keyof ContactDraft,next:unknown)=>onChange({...value,[key]:next}); return <div className="a-contact-editor"><label>Name<Input value={value.displayName??""} disabled={disabled} onChange={e=>set("displayName",e.currentTarget.value)}/></label><label>Role<Input value={value.role??""} disabled={disabled} onChange={e=>set("role",e.currentTarget.value)}/></label><label>Email<Input type="email" value={value.email??""} disabled={disabled} onChange={e=>set("email",e.currentTarget.value)}/></label><label>Phone<Input value={value.phone??""} disabled={disabled} onChange={e=>set("phone",e.currentTarget.value)}/></label><label><Checkbox checked={value.primary===true} disabled={disabled} onChange={e=>set("primary",e.currentTarget.checked)}/>Primary contact</label></div>; }
export function AddressEditor({ value, onChange, disabled=false }: { readonly value: AddressDraft; readonly onChange:(next:AddressDraft)=>void; readonly disabled?:boolean }) { const set=(key:keyof AddressDraft,next:unknown)=>onChange({...value,[key]:next}); return <div className="a-address-editor">{([['line1','Address line 1'],['line2','Address line 2'],['locality','City'],['region','Region'],['postalCode','Postal code'],['countryCode','Country code'],['purpose','Purpose']] as const).map(([key,label])=><label key={key}>{label}<Input value={value[key]??""} disabled={disabled} onChange={e=>set(key,e.currentTarget.value)}/></label>)}<label><Checkbox checked={value.primary===true} disabled={disabled} onChange={e=>set("primary",e.currentTarget.checked)}/>Primary address</label></div>; }
