import { describe, expect, it } from "vitest";
import { createBusinessPartnerNetworkExchangeService, type BusinessPartnerNetworkExchangeRepository } from "./business-partner-network-exchange.js";

const tenant="11111111-1111-4111-8111-111111111111",account="22222222-2222-4222-8222-222222222222",principal="33333333-3333-4333-8333-333333333333";
const context={tenantId:tenant,principalId:principal,planeKey:"mesh",realmKey:"tenant",authEpoch:1,assurance:"baseline",requestId:"request",profileHash:"profile",permissions:{tenantId:tenant,principalId:principal,principalFingerprint:"fingerprint",planeKey:"mesh",profileHash:"profile",schemaHash:"schema",resolvedAt:1,networkAccountId:account,allowed:[],denied:[],planLocked:[],planeExcluded:[],entries:[],authorizationScopes:[]}} as const;

function fixture(outcome:"accepted"|"internal_sponsor_required"|"rejected"="accepted"){const calls:{kind:string;input:Record<string,unknown>}[]=[];const result={id:"44444444-4444-4444-8444-444444444444",status:"issued",rowVersion:1,evidenceId:"55555555-5555-4555-8555-555555555555",replayed:false};const repository:BusinessPartnerNetworkExchangeRepository={async workspace(_tenant,accountId){calls.push({kind:"workspace",input:{accountId}});return{actingAccount:{id:accountId,code:"supplier",displayName:"Supplier",role:"supplier",status:"active"},relationships:[],capabilities:[],registrationExchanges:[]};},async requestRelationship(input){calls.push({kind:"relationship",input});return{...result,status:"requested"};},async transitionRelationship(input){calls.push({kind:"relationship.transition",input});return{...result,status:input.action==="accept"?"active":"terminated"};},async requestCapability(input){calls.push({kind:"capability",input});return{...result,status:"requested"};},async transitionCapability(input){calls.push({kind:"capability.transition",input});return result;},async issueExchange(input){calls.push({kind:"exchange",input});return result;},async transitionExchange(input){calls.push({kind:"exchange.transition",input});return{...result,status:input.action==="accept"?"accepted":"rejected"};}};const service=createBusinessPartnerNetworkExchangeService({repository,selfRegistrationPolicy:{async evaluate(){calls.push({kind:"policy",input:{}});return{outcome,evaluationId:"policy-evaluation-001",policyVersion:"2026.09",evidenceHash:"c".repeat(64),evaluatedAt:"2026-09-05T00:00:00.000Z",reasonCodes:[outcome]};}},authorizer:{async authorize(){return{allowed:true};}},transactions:{async run(_plane,_actor,work){return work({} as never);}}});return{calls,service};}

describe("MESH Business Partner relationship and registration exchange",()=>{
 it("binds a relationship request to the selected account instead of browser-supplied actor authority",async()=>{const value=fixture();await value.service.requestRelationship({context,actorRole:"supplier",counterpartyTenantId:"66666666-6666-4666-8666-666666666666",counterpartyAccountId:"77777777-7777-4777-8777-777777777777",relationshipKind:"commercial",reason:"Supplier relationship request",idempotencyKey:"relationship-001"});expect(value.calls[0]?.input).toMatchObject({tenantId:tenant,accountId:account,actorId:principal,actorRole:"supplier"});});
 it("records an accepted external policy evaluation in exchange evidence only",async()=>{const value=fixture();const issued=await issue(value.service);const accepted=await value.service.transitionExchange({context,exchangeId:issued.id,action:"accept",expectedVersion:issued.rowVersion,reason:"Policy accepted",idempotencyKey:"registration-accept-001"});expect(issued.policyEvaluation?.outcome).toBe("accepted");expect(accepted.status).toBe("accepted");expect(value.calls.map(item=>item.kind)).toEqual(["policy","exchange","exchange.transition"]);expect(value.calls.find(item=>item.kind==="exchange")?.input.intentSnapshot).toMatchObject({policyEvaluation:{evaluationId:"policy-evaluation-001",evidenceHash:"c".repeat(64)}});expect(value.calls.some(item=>item.kind.includes("master"))).toBe(false);});
 it("requires an internal sponsor before offering a lifecycle command",async()=>{const value=fixture("internal_sponsor_required");await expect(issue(value.service)).rejects.toMatchObject({status:409,code:"MESH_INTERNAL_SPONSOR_REQUIRED"});expect(value.calls.map(item=>item.kind)).toEqual(["policy"]);});
 it("rejects policy-denied self-registration without creating an exchange",async()=>{const value=fixture("rejected");await expect(issue(value.service)).rejects.toMatchObject({status:403,code:"MESH_SELF_REGISTRATION_REJECTED"});expect(value.calls.map(item=>item.kind)).toEqual(["policy"]);});
 it("fails closed when no acting network account was verified",async()=>{const value=fixture();await expect(value.service.workspace({context:{...context,permissions:{...context.permissions,networkAccountId:undefined}}})).rejects.toMatchObject({status:409,code:"MESH_NETWORK_ACCOUNT_CONTEXT_REQUIRED"});});
});

function issue(service:ReturnType<typeof fixture>["service"]){return service.issueExchange({context,counterpartyTenantId:"66666666-6666-4666-8666-666666666666",counterpartyAccountId:"77777777-7777-4777-8777-777777777777",intentKind:"supplier_self_registration",relationshipKind:"commercial",contractName:"mesh.supplier.registration",contractVersion:1,contractHash:"a".repeat(64),intentSnapshot:{displayName:"Supplier"},invitationTokenHash:"b".repeat(64),expiresAt:"2026-12-01T00:00:00.000Z",reason:"Self registration",idempotencyKey:"registration-001"});}
