import {sql,type Transaction} from "kysely";
import type {PlaneKey} from "@athyper/server-foundation/context";
import type {PlaneTransactionCoordinator} from "@athyper/server-foundation/transaction";

type Tx=Transaction<Record<string,never>>;
export interface SlaBreachCandidate{readonly id:string;readonly tenantId:string;readonly title:string;readonly assigneePrincipalId:string|null;readonly dueAt:string;readonly rowVersion:number;readonly payload:Readonly<Record<string,unknown>>;}
export interface SlaReminderCandidate extends SlaBreachCandidate{readonly reminderAt:string;readonly reminderIndex:number;}
export interface SlaAutomationRepository<Transaction>{claim(input:{tenantId:string;now:string;limit:number},transaction:Transaction):Promise<readonly SlaBreachCandidate[]>;record(input:{candidate:SlaBreachCandidate;actorPrincipalId:string;now:string;escalatedTo?:string},transaction:Transaction):Promise<boolean>;claimReminders?(input:{tenantId:string;now:string;limit:number},transaction:Transaction):Promise<readonly SlaReminderCandidate[]>;recordReminder?(input:{candidate:SlaReminderCandidate;actorPrincipalId:string;now:string},transaction:Transaction):Promise<boolean>;}
export interface WorkflowDelegationResolver<Transaction=unknown>{resolve(input:{tenantId:string;delegatorPrincipalId:string;permissionCode:string;effectiveAt:string},transaction:Transaction):Promise<string|null>;}
export interface SlaAutomationResult{readonly inspected:number;readonly breached:number;readonly escalated:number;readonly skipped:number;readonly reminded?:number;}

export function createWorkflowSlaAutomation<Transaction>(options:{repository:SlaAutomationRepository<Transaction>;transactions:PlaneTransactionCoordinator<Transaction>;delegations?:WorkflowDelegationResolver<Transaction>;now?:()=>Date}){return{async sweep(scope:{planeKey:PlaneKey;tenantId:string;principalId:string;limit?:number}):Promise<SlaAutomationResult>{const limit=scope.limit??100;if(!Number.isInteger(limit)||limit<1||limit>500)throw new TypeError("SLA sweep limit must be between 1 and 500");const now=(options.now?.()??new Date()).toISOString();return options.transactions.run(scope.planeKey,scope,async transaction=>{let reminded=0;const reminders=options.repository.claimReminders&&options.repository.recordReminder?await options.repository.claimReminders({tenantId:scope.tenantId,now,limit},transaction):[];for(const candidate of reminders)if(await options.repository.recordReminder!({candidate,actorPrincipalId:scope.principalId,now},transaction))reminded++;const candidates=await options.repository.claim({tenantId:scope.tenantId,now,limit},transaction);let breached=0,escalated=0,skipped=0;for(const candidate of candidates){let escalatedTo=explicitEscalation(candidate.payload);if(!escalatedTo&&candidate.assigneePrincipalId&&options.delegations)escalatedTo=await options.delegations.resolve({tenantId:scope.tenantId,delegatorPrincipalId:candidate.assigneePrincipalId,permissionCode:"workflow.work_item.complete",effectiveAt:now},transaction)??undefined;const applied=await options.repository.record({candidate,actorPrincipalId:scope.principalId,now,...(escalatedTo?{escalatedTo}:{})},transaction);if(!applied)skipped++;else if(escalatedTo)escalated++;else breached++;}return{inspected:candidates.length+reminders.length,breached,escalated,skipped,...(reminded?{reminded}:{})};});}};}

export function createKyselyWorkflowDelegationResolver():WorkflowDelegationResolver<Tx>{return{async resolve(input,transaction){return(await sql<{delegate_id:string}>`SELECT delegation.delegate_id FROM authz.delegation delegation JOIN authz.delegation_grant grant_row ON grant_row.tenant_id=delegation.tenant_id AND grant_row.delegation_id=delegation.id JOIN authz.permission permission ON permission.id=grant_row.permission_id WHERE delegation.tenant_id=${input.tenantId}::uuid AND delegation.delegator_id=${input.delegatorPrincipalId}::uuid AND delegation.status='active' AND delegation.effective_from<=${input.effectiveAt}::timestamptz AND delegation.effective_until>${input.effectiveAt}::timestamptz AND permission.canonical_code=${input.permissionCode} AND permission.status='published' ORDER BY delegation.effective_until,delegation.id LIMIT 1`.execute(transaction)).rows[0]?.delegate_id??null;}};}

export function createKyselySlaAutomationRepository():SlaAutomationRepository<Tx>{return{
 async claimReminders(input,transaction){const rows=(await sql<Record<string,unknown>>`SELECT item.id,item.tenant_id,item.title,item.assignee_principal_id,item.due_at,item.row_version,item.payload,((reminder.value #>> '{}')::timestamptz + COALESCE(item.due_at-(item.payload#>>'{sla,dueAt}')::timestamptz,interval '0')) reminder_at,(reminder.ordinality-1)::int reminder_index FROM document.work_item item CROSS JOIN LATERAL jsonb_array_elements(COALESCE(item.payload->'remindersAt','[]'::jsonb)) WITH ORDINALITY reminder(value,ordinality) WHERE item.tenant_id=${input.tenantId}::uuid AND item.status IN ('open','claimed','in_progress','blocked') AND ((reminder.value #>> '{}')::timestamptz + COALESCE(item.due_at-(item.payload#>>'{sla,dueAt}')::timestamptz,interval '0'))<=${input.now}::timestamptz AND NOT COALESCE(item.payload->'sla_reminders_sent','[]'::jsonb) ? (reminder.ordinality-1)::text ORDER BY (reminder.value #>> '{}')::timestamptz,item.id FOR UPDATE OF item SKIP LOCKED LIMIT ${input.limit}`.execute(transaction)).rows;return rows.map(row=>({...candidate(row),reminderAt:new Date(String(row["reminder_at"])).toISOString(),reminderIndex:Number(row["reminder_index"])}));},
 async recordReminder(input,transaction){const updated=await sql`UPDATE document.work_item SET payload=jsonb_set(payload,'{sla_reminders_sent}',COALESCE(payload->'sla_reminders_sent','[]'::jsonb)||to_jsonb(${String(input.candidate.reminderIndex)}::text),true),row_version=row_version+1,updated_by=${input.actorPrincipalId}::uuid WHERE tenant_id=${input.candidate.tenantId}::uuid AND id=${input.candidate.id}::uuid AND row_version=${input.candidate.rowVersion} AND NOT COALESCE(payload->'sla_reminders_sent','[]'::jsonb)?${String(input.candidate.reminderIndex)} RETURNING id`.execute(transaction);if(Number(updated.numAffectedRows)!==1)return false;await sql`INSERT INTO event.outbox(tenant_id,topic,event_type,event_key,entity_type,entity_id,aggregate_type,aggregate_id,actor_id,source,payload,created_by) VALUES(${input.candidate.tenantId}::uuid,'platform.workflow.sla','workflow.work_item.reminder',${`workflow-reminder:${input.candidate.id}:${input.candidate.reminderIndex}`},'workflow.work_item',${input.candidate.id}::uuid,'workflow.work_item',${input.candidate.id}::uuid,${input.actorPrincipalId}::uuid,'workflow.sla-automation',${JSON.stringify({title:input.candidate.title,priority:"high",due_at:input.candidate.dueAt,reminder_at:input.candidate.reminderAt,entity_type:"workflow.work_item",entity_id:input.candidate.id,...(input.candidate.assigneePrincipalId?{recipient_principal_ids:[input.candidate.assigneePrincipalId]}:{})})}::jsonb,${input.actorPrincipalId}::uuid) ON CONFLICT (tenant_id,event_key) WHERE event_key IS NOT NULL DO NOTHING`.execute(transaction);return true;},
 async claim(input,transaction){const rows=(await sql<Record<string,unknown>>`SELECT id,tenant_id,title,assignee_principal_id,due_at,row_version,payload FROM document.work_item WHERE tenant_id=${input.tenantId}::uuid AND status IN ('open','claimed','in_progress','blocked') AND due_at<=${input.now}::timestamptz AND NOT (payload ? 'sla_breach') ORDER BY due_at,id FOR UPDATE SKIP LOCKED LIMIT ${input.limit}`.execute(transaction)).rows;return rows.map(row=>({id:String(row["id"]),tenantId:String(row["tenant_id"]),title:String(row["title"]),assigneePrincipalId:row["assignee_principal_id"]==null?null:String(row["assignee_principal_id"]),dueAt:new Date(String(row["due_at"])).toISOString(),rowVersion:Number(row["row_version"]),payload:object(row["payload"])}));},
 async record(input,transaction){const recipientPrincipalId=input.escalatedTo??input.candidate.assigneePrincipalId;const evidence={breachedAt:input.now,dueAt:input.candidate.dueAt,previousAssigneePrincipalId:input.candidate.assigneePrincipalId,...(input.escalatedTo?{escalatedTo:input.escalatedTo}:{})};const updated=await sql`UPDATE document.work_item SET priority='urgent',assignee_principal_id=CASE WHEN payload ? 'attemptId' THEN assignee_principal_id ELSE COALESCE(${input.escalatedTo??null}::uuid,assignee_principal_id) END,payload=payload||${JSON.stringify({sla_breach:evidence})}::jsonb,row_version=row_version+1,updated_by=${input.actorPrincipalId}::uuid WHERE tenant_id=${input.candidate.tenantId}::uuid AND id=${input.candidate.id}::uuid AND row_version=${input.candidate.rowVersion} AND NOT (payload ? 'sla_breach')`.execute(transaction);if(Number(updated.numAffectedRows)!==1)return false;const eventKey=`workflow-sla:${input.candidate.id}:${input.candidate.dueAt}`;await sql`INSERT INTO event.outbox(tenant_id,topic,event_type,event_key,entity_type,entity_id,aggregate_type,aggregate_id,actor_id,source,payload,created_by) VALUES(${input.candidate.tenantId}::uuid,'platform.workflow.sla',${input.escalatedTo?'workflow.work_item.escalated':'workflow.work_item.sla_breached'},${eventKey},'workflow.work_item',${input.candidate.id}::uuid,'workflow.work_item',${input.candidate.id}::uuid,${input.actorPrincipalId}::uuid,'workflow.sla-automation',${JSON.stringify({...evidence,title:input.candidate.title,priority:"urgent",due_at:input.candidate.dueAt,entity_type:"workflow.work_item",entity_id:input.candidate.id,...(recipientPrincipalId?{recipient_principal_ids:[recipientPrincipalId]}:{})})}::jsonb,${input.actorPrincipalId}::uuid) ON CONFLICT (tenant_id,event_key) WHERE event_key IS NOT NULL DO NOTHING`.execute(transaction);return true;}
};}
function candidate(row:Record<string,unknown>):SlaBreachCandidate{return{id:String(row["id"]),tenantId:String(row["tenant_id"]),title:String(row["title"]),assigneePrincipalId:row["assignee_principal_id"]==null?null:String(row["assignee_principal_id"]),dueAt:new Date(String(row["due_at"])).toISOString(),rowVersion:Number(row["row_version"]),payload:object(row["payload"])};}
function explicitEscalation(payload:Readonly<Record<string,unknown>>):string|undefined{const value=payload["sla_escalation_principal_id"];return typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)?value:undefined;}
function object(value:unknown):Readonly<Record<string,unknown>>{const parsed=typeof value==="string"?JSON.parse(value) as unknown:value;return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as Readonly<Record<string,unknown>>:{};}
