-- ============================================================================
-- Runtime parameter definitions
-- Product-owned defaults for auth/session/login/logout/inactivity behavior.
-- Tenants can view all active non-hidden rows and override rows marked
-- tenant_visibility = configurable.
-- ============================================================================

INSERT INTO control.parameter_definition (
    code,
    namespace,
    display_name,
    description,
    owner_model,
    control_level,
    tenant_visibility,
    data_type,
    unit,
    default_value,
    product_value,
    min_value,
    max_value,
    allowed_values,
    runtime_reload,
    cache_ttl_seconds,
    is_security_sensitive,
    is_runtime_reloadable,
    sort_order,
    metadata,
    created_by
)
SELECT
    v.code,
    v.namespace,
    v.display_name,
    v.description,
    'product',
    v.control_level,
    v.tenant_visibility,
    v.data_type,
    v.unit,
    v.default_value::jsonb,
    NULLIF(v.product_value, '')::jsonb,
    NULLIF(v.min_value, '')::jsonb,
    NULLIF(v.max_value, '')::jsonb,
    NULLIF(v.allowed_values, '')::jsonb,
    v.runtime_reload,
    v.cache_ttl_seconds,
    v.is_security_sensitive,
    v.is_runtime_reloadable,
    v.sort_order,
    v.metadata::jsonb,
    '00000000-0000-0000-0000-000000000000'::uuid
FROM (VALUES
    ('auth.session.absolute_ttl_seconds', 'auth.session', 'BFF session absolute TTL', 'Maximum Redis-backed web session lifetime before a full login is required.', 'tenant_configurable', 'configurable', 'integer', 'seconds', '28800', '28800', '1800', '43200', NULL, 'next_login', 300, true, true, 10, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"SESSION_TTL_SECONDS"}'),
    ('auth.pkce.state_ttl_seconds', 'auth.login', 'PKCE state TTL', 'Maximum lifetime of the OAuth PKCE state record used during sign in.', 'system_controlled', 'readonly', 'integer', 'seconds', '1800', '1800', '300', '3600', NULL, 'next_request', 300, true, true, 20, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"PKCE_STATE_TTL_SECONDS"}'),
    ('auth.idle.timeout_seconds', 'auth.inactivity', 'Inactivity timeout', 'Idle duration after which the session is locked and the user must sign in again.', 'tenant_configurable', 'configurable', 'integer', 'seconds', '900', '900', '300', '3600', NULL, 'immediate', 300, true, true, 30, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"IDLE_TIMEOUT_SECONDS"}'),
    ('auth.idle.warning_seconds', 'auth.inactivity', 'Inactivity warning lead time', 'How long before idle expiry the browser warning dialog is shown.', 'tenant_configurable', 'configurable', 'integer', 'seconds', '120', '120', '30', '600', NULL, 'immediate', 300, false, true, 40, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"IDLE_WARNING_SECONDS"}'),
    ('auth.heartbeat.interval_ms', 'auth.inactivity', 'Activity heartbeat interval', 'Minimum interval between active-browser touch calls that update lastSeenAt.', 'tenant_configurable', 'configurable', 'integer', 'milliseconds', '300000', '300000', '60000', '600000', NULL, 'immediate', 300, false, true, 50, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"HEARTBEAT_INTERVAL_MS"}'),
    ('auth.token.client_refresh_lead_seconds', 'auth.token', 'Client refresh lead time', 'Browser token refresh starts this many seconds before access token expiry.', 'system_controlled', 'readonly', 'integer', 'seconds', '90', '90', '30', '300', NULL, 'immediate', 300, true, true, 60, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"CLIENT_REFRESH_BEFORE_EXPIRY_SECONDS"}'),
    ('auth.token.server_refresh_buffer_seconds', 'auth.token', 'Server refresh buffer', 'Server-side session reads refresh the access token when it is inside this expiry buffer.', 'system_controlled', 'readonly', 'integer', 'seconds', '120', '120', '60', '600', NULL, 'next_request', 300, true, true, 70, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"SERVER_REFRESH_BUFFER_SECONDS"}'),
    ('auth.refresh.lock_ttl_seconds', 'auth.refresh', 'Refresh lock TTL', 'Distributed Redis lock lifetime used to prevent refresh-token rotation races.', 'system_controlled', 'readonly', 'integer', 'seconds', '10', '10', '3', '60', NULL, 'next_request', 300, true, true, 80, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"REFRESH_LOCK_TTL_SECONDS"}'),
    ('auth.refresh.lock_wait_ms', 'auth.refresh', 'Refresh lock wait', 'How long a concurrent request waits before reading a rotated session.', 'system_controlled', 'readonly', 'integer', 'milliseconds', '300', '300', '50', '2000', NULL, 'next_request', 300, false, true, 90, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"REFRESH_LOCK_WAIT_MS"}'),
    ('auth.refresh.sid_rotation_grace_seconds', 'auth.refresh', 'SID rotation grace', 'Short lookup window from old SID to new SID for in-flight requests.', 'system_controlled', 'readonly', 'integer', 'seconds', '30', '30', '5', '120', NULL, 'next_request', 300, true, true, 100, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"REFRESH_ROTATION_GRACE_SECONDS"}'),
    ('auth.session.expired_redirect_countdown_seconds', 'auth.session', 'Expired-session redirect countdown', 'Countdown shown before an expired-session dialog redirects to sign in.', 'tenant_configurable', 'configurable', 'integer', 'seconds', '30', '30', '5', '300', NULL, 'immediate', 300, false, true, 110, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"SESSION_EXPIRED_REDIRECT_COUNTDOWN_SECONDS"}'),
    ('auth.mfa.pending_ttl_seconds', 'auth.mfa', 'MFA pending TTL', 'How long an MFA-pending browser state can live before restarting sign in.', 'tenant_configurable', 'configurable', 'integer', 'seconds', '900', '900', '300', '1800', NULL, 'next_request', 300, true, true, 120, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"MFA_PENDING_TTL_SECONDS"}'),
    ('auth.mfa.trusted_device_ttl_days', 'auth.mfa', 'Trusted device lifetime', 'How long a remembered device can bypass repeated MFA challenges.', 'tenant_configurable', 'configurable', 'integer', 'days', '30', '30', '1', '90', NULL, 'next_request', 300, true, true, 130, '{"source":"apps/web/lib/auth/session-policy.ts","fallback_constant":"TRUSTED_DEVICE_TTL_DAYS"}'),
    ('runtime.mfa.step_up_ttl_seconds', 'runtime.mfa', 'Step-up elevation TTL', 'How long a successful MFA step-up remains valid for sensitive actions.', 'tenant_configurable', 'configurable', 'integer', 'seconds', '600', '600', '60', '1800', NULL, 'next_request', 300, true, true, 140, '{"source":"server/framework/runtime/services/iam/mfa/step-up.service.ts"}'),
    ('runtime.session.cache_ttl_seconds', 'runtime.session', 'Runtime session cache TTL', 'Cache lifetime for resolved runtime session context.', 'system_controlled', 'readonly', 'integer', 'seconds', '300', '300', '60', '900', NULL, 'next_request', 300, true, true, 150, '{"source":"server/framework/runtime/services/iam/session/session.service.ts"}'),
    ('runtime.bootstrap.cache_ttl_seconds', 'runtime.session', 'Runtime bootstrap cache TTL', 'Cache lifetime for tenant bootstrap data used by the shell.', 'system_controlled', 'readonly', 'integer', 'seconds', '300', '300', '60', '900', NULL, 'next_request', 300, false, true, 160, '{"source":"server/framework/runtime/services/iam/bootstrap/bootstrap.service.ts"}'),
    ('auth.logout.revoke_refresh_tokens', 'auth.logout', 'Revoke refresh tokens on logout', 'Whether logout attempts to revoke the active Keycloak refresh token.', 'system_controlled', 'readonly', 'boolean', NULL, 'true', 'true', NULL, NULL, NULL, 'external_provider', 300, true, true, 170, '{"source":"apps/web/app/api/auth/logout/route.ts"}'),
    ('auth.logout.clear_all_bff_namespaces', 'auth.logout', 'Clear all BFF session namespaces', 'Whether logout clears every known BFF session namespace for the user.', 'system_controlled', 'readonly', 'boolean', NULL, 'true', 'true', NULL, NULL, NULL, 'next_request', 300, true, true, 180, '{"source":"apps/web/app/api/auth/logout/route.ts"}'),
    ('keycloak.token.access_ttl_seconds', 'keycloak.token', 'Keycloak access token TTL', 'Reference value for the Keycloak realm/client access token lifetime.', 'system_controlled', 'readonly', 'integer', 'seconds', '900', '900', '60', '3600', NULL, 'external_provider', 300, true, false, 190, '{"source":"Keycloak realm configuration","external":true}'),
    ('keycloak.sso.idle_timeout_seconds', 'keycloak.session', 'Keycloak SSO idle timeout', 'Reference value for the Keycloak SSO idle timeout.', 'system_controlled', 'readonly', 'integer', 'seconds', '1800', '1800', '300', '86400', NULL, 'external_provider', 300, true, false, 200, '{"source":"Keycloak realm configuration","external":true}'),
    ('keycloak.sso.max_lifespan_seconds', 'keycloak.session', 'Keycloak SSO max lifespan', 'Reference value for the Keycloak SSO maximum session lifespan.', 'system_controlled', 'readonly', 'integer', 'seconds', '36000', '36000', '1800', '604800', NULL, 'external_provider', 300, true, false, 210, '{"source":"Keycloak realm configuration","external":true}'),
    ('keycloak.refresh.revoke_tokens_enabled', 'keycloak.refresh', 'Keycloak revoke refresh tokens', 'Reference value for Keycloak refresh-token revocation behavior.', 'system_controlled', 'readonly', 'boolean', NULL, 'true', 'true', NULL, NULL, NULL, 'external_provider', 300, true, false, 220, '{"source":"Keycloak realm configuration","external":true}'),
    ('keycloak.refresh.max_reuse', 'keycloak.refresh', 'Keycloak refresh max reuse', 'Reference value for refresh token max reuse. Zero means single-use rotation.', 'system_controlled', 'readonly', 'integer', 'count', '0', '0', '0', '10', NULL, 'external_provider', 300, true, false, 230, '{"source":"Keycloak realm configuration","external":true}'),
    ('auth.cookie.session_name', 'auth.cookie', 'Session cookie name', 'Name of the secure HTTP-only BFF session cookie.', 'system_controlled', 'readonly', 'string', NULL, '"neon_sid"', '"neon_sid"', NULL, NULL, NULL, 'restart', 300, true, false, 240, '{"source":"apps/web auth routes"}'),
    ('auth.cookie.csrf_name', 'auth.cookie', 'CSRF cookie name', 'Name of the secure HTTP-only CSRF binding cookie.', 'system_controlled', 'readonly', 'string', NULL, '"__csrf"', '"__csrf"', NULL, NULL, NULL, 'restart', 300, true, false, 250, '{"source":"apps/web auth routes"}'),
    ('auth.cookie.mfa_pending_name', 'auth.cookie', 'MFA pending cookie name', 'Name of the secure HTTP-only MFA pending cookie.', 'system_controlled', 'readonly', 'string', NULL, '"neon_mfa_pending"', '"neon_mfa_pending"', NULL, NULL, NULL, 'restart', 300, true, false, 260, '{"source":"apps/web auth routes"}'),
    ('auth.cookie.realm_name', 'auth.cookie', 'Realm cookie name', 'Name of the login realm hint cookie.', 'system_controlled', 'readonly', 'string', NULL, '"neon_realm"', '"neon_realm"', NULL, NULL, NULL, 'restart', 300, false, false, 270, '{"source":"apps/web auth routes"}')
) AS v(
    code,
    namespace,
    display_name,
    description,
    control_level,
    tenant_visibility,
    data_type,
    unit,
    default_value,
    product_value,
    min_value,
    max_value,
    allowed_values,
    runtime_reload,
    cache_ttl_seconds,
    is_security_sensitive,
    is_runtime_reloadable,
    sort_order,
    metadata
)
ON CONFLICT (code) DO UPDATE SET
    namespace = EXCLUDED.namespace,
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    control_level = EXCLUDED.control_level,
    tenant_visibility = EXCLUDED.tenant_visibility,
    data_type = EXCLUDED.data_type,
    unit = EXCLUDED.unit,
    default_value = EXCLUDED.default_value,
    product_value = EXCLUDED.product_value,
    min_value = EXCLUDED.min_value,
    max_value = EXCLUDED.max_value,
    allowed_values = EXCLUDED.allowed_values,
    runtime_reload = EXCLUDED.runtime_reload,
    cache_ttl_seconds = EXCLUDED.cache_ttl_seconds,
    is_security_sensitive = EXCLUDED.is_security_sensitive,
    is_runtime_reloadable = EXCLUDED.is_runtime_reloadable,
    sort_order = EXCLUDED.sort_order,
    metadata = EXCLUDED.metadata,
    status = 'active',
    updated_at = now(),
    updated_by = EXCLUDED.created_by;
